### ISSUE TITLE
Simplified user interface for starting tests

### ISSUE THREAD

**Issue by MarcoMinghini** [INSPIRE-MIF/helpdesk-validator#10]
Several MS experts and representatives have reported that the current user interface (UI) for selecting test suites and starting tests is considered difficult, especially for occasional or novice users, who do not understand the notion of conformance classes and do not know which ones to select.

Therefore, in addition to the current (more expert) UI, a simplified UI for starting tests might be added to the ETF, similar to the one of the Geoportal's evaluation tool (http://inspire-geoportal.ec.europa.eu/validator2/). In this UI, the user can simply upload a resource (or a link to a resource); the ETF should then figure out the type of resource (e.g. WMS-based view service, Atom-based download service, data set containing AD and BU features, etc.) and offer and pre-select in a dialogue/page all conformance classes that could be tested on the identified resource to the user, who can then choose to deselect one or several conformance classes, before launching the test. Alternatively, instead of pre-selecting all conformance classes, only a limited set of conformance classes can be pre-selected for each specific resource, based on: a) the feedback from the INSPIRE community; b) the analysis of which tests are more often selected for each type of resource.

An alternative way to simplify the UI could be to simply offer a list of known resource types & sub-types (e.g. view-WMS, view-WMTS, download-Atom, download-WFS, data set/spatial object types) and pre-select all tests based on the user's selection (rather than analysis of the resource).

What are your views, comments and suggestions about this potential improvement?

**Comment by MarieLambois** [comment]
Would be a very nice improvement. Pre-selection would be even nicer but according to me the alternative solution, offering a simple and clean interface, might be enough. 
I guess that people know if they are testing a WMS, a metadata or a data. 
Moreover, sometimes you might point to a WFS to test it as a download service or sometimes you might want to test the data served.

**Comment by thijsbrentjens** [comment]
Agree with @MarieLambois 

A note: we should also consider that this makes it easier for non-experts to test resources (which is good). However, interpreting the test results could be very hard for these users and we can expect more reports on that. So, error reporting would probably need some improvements and/or we should accept that not all issues are easy to understand. As discussed in the webconf, I'll create separate, specific issues if users don't understand a certain report

**Comment by MarcoMinghini** [comment]
[2017.4 meeting 2018-11-15] the improvement proposal is considered to be useful, but with a low priority for implementation.

**Comment by AntoRot** [comment]
I agree too with @MarieLambois in preferring the alternative solution.

**Comment by IGNCNIG** [comment]
I agree with @AntoRot, it would be simple for the user to choose a resource type from a list ( Download service, view service, WMTS, metadata, dataset themes,..) and then the ETF should  offer and pre-select in a dialogue/page all conformance classes that could be tested on the identified resource to the user.

**Comment by LauraAlemany** [comment]
In my opinion it could be useful to include 2 generic labels in the Metadata (TG version 2.0) – BETA section:
1) One for selecting all test related to Dataset and Series metadata.
2) Another one for selecting test related to Services metadata.

Something like this:

![image](https://user-images.githubusercontent.com/33545308/58173082-aa91cb00-7c9a-11e9-8394-6e3420868eea.png)

**Comment by MarcoMinghini** [comment]
Since the same issue was raised again, and more in general in order to offer users an easier experience when starting a test, a new user interface of the Validator will be developed by the JRC. This interface will be also in line with the look & feel of the European Commission.

**Comment by MarcoMinghini** [comment]
Dear all,
some updates on the new UI of the Reference Validator that we are developing at the JRC. It addresses two needs:
* provide an easier and more intuitive way for users to find and select the tests they want to run
* be in line with the visual identity of the European Commission

To give you an idea of how it will work, please have a look at the mockup below. Initially, the user will only see the first question and select the type of resource to validate (in this case a Download Service); then, the second question will appear and the user will select the type of Download Service (in this case a WFS); then the third question will appear and the user will select the type of WFS (in this case a Direct WFS). The _Advanced options_  button will allow to open a section (for more experienced users) where the single conformance classes will be selectable/deselectable, as it currently happens in the Validator. Then the user can upload the resource/enter the URL and start validation. 

![Validator_mockup](https://user-images.githubusercontent.com/14758434/76201925-55f11980-61f4-11ea-9291-32793e6f9fcc.png)

We plan to have a first prototype available within a couple of months. Updates will be shared here.

**Comment by ghost** [comment]
Very interesting discussion so far!

As stated in [this](https://github.com/inspire-eu-validation/community/issues/162) discussion issue several organisations are currently using ETF-Webapp for validation purposes. In this moment there is a possibility to use **CORE** etf-validator and/or **INSPIRE** etf-validator which are currently distrubuted using two different channels.

Many organisations are using INSPIRE etf-validator with the standard (neutral) UI which we are currently having on production and staging instance. 

Is it planned to distrubute neutral UI within the [release](https://github.com/inspire-eu-validation/community/releases) page in order to enable simple reuse of INSPIRE etf-validator in the community?

**Comment by MarcoMinghini** [comment]
Dear @DeordD,
the planned change of the UI will only interest the INSPIRE Reference Validator, and is aimed at facilitating MS organisations in using it. But behind the new UI the same API will be used, i.e. core functionality will be exactly the same as it is now.

The idea is exactly to separate the 'ETF' (seen as the functionality, i.e. the API) from the UI, that could be different for each organisation using the ETF. In this logic, the standard UI will probably remain available on the ETF repository, and the INSPIRE-specific one will be provided in the INSPIRE GitHub environment.

I hope this clarifies your question. More feedback from the community is of course welcome.
We will soon announce when a prototype of the new UI will be available.

**Comment by ghost** [comment]
Dear @MarcoMinghini ,

thanks a lot for your feedback. This clarifies my question. 

It would be nice if all bug fixes, non-UI specific enhancements including schema caches implementation developed in INSPIRE etf-validator could be merged in the next version of CORE etf-validator. 

Kind regards

**Comment by MarcoMinghini** [comment]
Dear all,
as you might have already noticed, the new UI has been recently included in the [staging instance](http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/) of the INSPIRE Reference Validator. Starting with the next release scheduled for mid-June (see the release plan [here](https://github.com/INSPIRE-MIF/helpdesk-validator/tree/master/release%20strategy)), the new UI will be also included in the [production instance](https://inspire.ec.europa.eu/validator/).

Thank you for contributing to this initial discussion on improving the UI, and thanks to those who have tested the new UI and providing us with useful feedback and suggestions.

I close this issue, but please do not hesitate to open other issues to provide additional feedback, should this be needed.
