### ISSUE TITLE
Metadata element: hierarchyLevelName - multiplicity

### ISSUE THREAD

**Issue by fantamir** [INSPIRE-MIF/helpdesk-validator#100]
In the past, the hierarchyLevelName element was not used in the INSPIRE metadata profile. Therefore, we used this element in the Czech metadata profile (which, to simplify its structure,  contains INSPIRE part plus several national items) in one of national items: specific flag indicating whether given dataset or map service should be harvested to the INSPIRE geoportal. In such case, the gmx:Anchor string "_http://geoportal.gov.cz/inspire_" is used in this element as follows:

<gmd:hierarchyLevelName>
 <gmx:Anchor xlink:href="http://geoportal.gov.cz/inspire"></gmx:Anchor>
</gmd:hierarchyLevelName>

Now, the hierarchyLevelName element is used in the INSPIRE metadata in the item 1.3 "Resource type". Since the multiplicity of this element is [1] only, we cannot use the hierarchyLevelName element for the purposes described above anymore. This creates the significant problem for us, because all metadata created in the past by tens of providers should be modified accordingly. Would it be possible to change the multiplicity of the hierarchyLevelName element from [1] to [1..n], to allow using of given metadata element not only for specification of the resource type, but also as the flag in the national part of the metadata?

**Comment by MarcoMinghini** [comment]
Dear @fantamir,

in MD TG v.2.0 there is actually an inconsistency in wording between Requirements 1.1 (about datasets and dataset series) and and 3.1 (about services).

Requirement 1.1 states that **the first** `gmd:hierarchyLevel` child element of `gmd:MD_Metadata` should be considered, while this is not stated in Requirement 3.1.

Both the `gmd:hierarchyLevel` and `gmd:hierarchyLevelName` elements are not mandated by ISO (where they have multiplicity 0..*) but are mandated by INSPIRE. However, it makes sense to keep the consistency between the requirements on datasets/series and services (and relax the test on Requirement 3.1, allowing multiple occurrences of the elements), however we should first check that this change would not break the harvesting process made by the Geoportal.

We will be back with some final feedback on this issue.

**Comment by fantamir** [comment]
Dear Marco,

Thank you very much for your reply. 
We will highly appreciate, if you provide the decision by Friday 22nd of November at the latest. We should present the solution and implementation of this issue and release the update of the Czech metadata profile on the important meeting of our national INSPIRE data providers on Monday 25th of November. Thank you very much.

**Comment by MarcoMinghini** [comment]
Dear @fantamir, 
we made the needed checks from the Geoportal side (thanks to @dartasensi) and I can confirm that the presence of multiple occurrences of the `gmd:hierarchyLevelName` element does not interfere with the harvesting process.

Therefore, the test can be relaxed ad explained above (cc: @josemasensio @danielnavarrogeo).

**Comment by josemasensio** [comment]
Dear @fantamir, @MarcoMinghini,

We have updated the test. Now it allows one or more than one `gmd:hierarchyLevelName`. Changes are available in [staging instance](http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/) please feel free to check everything is working as expected. 

Best regards.

**Comment by MarcoMinghini** [comment]
Dear @fantamir,
can you please check with some of your metadata and inform us if the outcome of the test is the one expected? Thank you.

**Comment by fantamir** [comment]
Dear Marco and other colleagues,

Thank you very much. 
We have tested our metadata with multiple hierarchyLevelName element ( https://dev.bnhelp.cz/projects/micka6/record/xml/5a4c757b-30c8-4edf-ab2f-40f5585671f1 ) on staging instance and it works OK.

**Comment by josemasensio** [comment]
Dear @fantamir,

Glad to hear that!
If there is no other question, we will mark the issue as solved.
Best regards.

**Comment by fantamir** [comment]
Dear colleagues,

unfortunately, we have to re-open this issue. According to the latest experience of Czech State Administration of Land Surveying and Cadastre experts, it seems, validator now allows multiple using of hierarchyLevelName element with Anchor, but validation is failed in the case of multiple using of hierarchyLevelName element with CharacterString. 
Could you please check and fix this problem?
Thank you very much

example:
.......
<gmd:hierarchyLevelName>
    <gco:CharacterString>služba</gco:CharacterString>
  </gmd:hierarchyLevelName>
  <gmd:hierarchyLevelName>
    <gco:CharacterString>META_WFS-GN_SERVICE</gco:CharacterString>
  </gmd:hierarchyLevelName>
  <gmd:hierarchyLevelName>
    <gmx:Anchor xlink:href="http://geoportal.gov.cz/inspire">http://geoportal.gov.cz/inspire</gmx:Anchor>
  </gmd:hierarchyLevelName>
  <gmd:hierarchyLevelName>
    <gmx:Anchor xlink:href="test">test</gmx:Anchor>
  </gmd:hierarchyLevelName>
.......
(second occurence of hierarchyLevelName element with Anchor was added just for testing purposes)

metadata xml file is attached:
[MET20_CZ-CUZK-WFS-GN.zip](https://github.com/inspire-eu-validation/community/files/4661908/MET20_CZ-CUZK-WFS-GN.zip)

validation results:
https://inspire.ec.europa.eu/validator/v2/TestRuns/EIDa0251ded-211f-4749-a58c-1e6207f0d774.html

**Comment by danielnavarrogeo** [comment]
Dear @fantamir 

Thank you for pointing to this issue. We will analyze what has been changed.

Regards

**Comment by danielnavarrogeo** [comment]
Dear @fantamir 

A fix has been developed and it is ready for testing in [staging instance](http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/).

Could you please check it and provide us feedback?

Regards

**Comment by fantamir** [comment]
Dear colleagues,

thank you very much. We have tested the metadata validation in staging instance and multiple using of hierarchyLevelName with CharacterString is now OK.

Regards
