### ISSUE TITLE
INSPIRE validator doesn`t recognize ATOM Digital certificate- SPAIN

### ISSUE THREAD

**Issue by abadppa0** [INSPIRE-MIF/helpdesk-validator#1008]
Hello,
The INSPIRE validator does not recognise the ATOM of FEGA. We have tested installing the ATOM in another organisation and the validator does recognise it without problems, but when the ATOM URL depends on FEGA, the validator says "ERROR An error has occured".

- **ATOM URL:** https://www.fega.gob.es/atom/es.fega.sigpac.xml
- **FEGA** is "Spanish Agrarian Guarantee Fund", https://www.fega.gob.es/en

Here are the steps:
1. The INSPIRE validator does not recognise the ATOM service.
2. If the ATOM XML is copied to a server of another organisation, which has another certificate, the validator is recognised it and the validator's output is Ok,	
3. Therefore, we think that there may be a problem with the certificate of the original server, since the difference in the publication of the XML in one organisation and another is the certificate.

I enclose the FEGA´s certificate ![certificado_FEGA](https://github.com/INSPIRE-MIF/helpdesk-validator/assets/82525124/9cc60e3f-4dba-4501-b628-7e8e3bc10a49)

and this is the error message 
[Error certificate.txt](https://github.com/INSPIRE-MIF/helpdesk-validator/files/13345852/Error.certificate.txt)

Thank you very much for your help.
Paloma Abad

**Comment by fabiovinci** [comment]
Dear @abadppa0,

thank you for reporting the issue, we will have a look asap.

**Comment by DanielMartinPerezdeLeon** [comment]
Dear @abadppa0,

Thank you for notifying us about this problem. After incorporating the provided certificate, the reported issue appears to be resolved. To ensure seamless functionality, we are updating the staging deploy of the INSPIRE VALIDATOR with this certificate. You can verify the URL's functionality in the staging environment by visiting http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/home/index.html.

Furthermore, rest assured that this certificate will be included in the upcoming official release of the VALIDATOR. Should you encounter any additional issues or have further feedback, please don't hesitate to reach out to us.

Regards,

**Comment by pablobarreira** [comment]
Dear all. 

I am in charge of the data that abadppa0 is refering to. Is it possible that the certificate is not already included in the staging deploy? 

We have tried and got this error right now:
[error.txt](https://github.com/INSPIRE-MIF/helpdesk-validator/files/13374327/error.txt)

Thank you!

**Comment by pablobarreira** [comment]
Hi again.

A few days ago (21st of november) the staging environment was working good with the certificate that we have the problems. 

Now seems to be failing again with the same certificate, getting the same error as we report at first. 

Could you please try to have a look to it? Thank you in advance

**Comment by jenriquesoriano** [comment]
Dear @pablobarreira , 

it seems that the info for the tests cannot be accessed using the provided url (https://www.fega.gob.es/atom/es.fega.sigpac.xml).
Since we have verified that the certificate has been loaded in the Staging instance and you verified this some days ago (November 21st), could you confirm the details of the URL you are testing? 

Thanks a lot.

Best regards,

**Comment by pablobarreira** [comment]
Hi!

We are not using that URL because previously it asks to accept terms and conditions. We internally remove that requirement and we are using: https://www.fega.gob.es/atom3/es.fega.sigpac.xml

Thanks in advance

**Comment by jenriquesoriano** [comment]
Dear @pablobarreira ,

thanks for your feedback and the provided url for the atom service.
We have tested it in the [Staging environment](http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/home/index.html) and it is working correctly.
Please see the resulting [test report](http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/test-reports/details.html?id=EID6da1858c-7292-4ce8-a4e0-0790d384f5fc).

Please let us know if the issue persists from your side.

Best regards,

**Comment by pablobarreira** [comment]
Now it seems to be working.

Could you please tell us a prevision of when is it going to be working on the https://inspire.ec.europa.eu/validator/test-selection/index.html ; cause we dont know when it is the next release.

Thank you again for your help!

**Comment by fabiovinci** [comment]
Dear @pablobarreira,

the next release is scheduled for January 15, 2024 ([v2024.0](https://github.com/INSPIRE-MIF/helpdesk-validator/milestone/20)).

**Comment by DanielMartinPerezdeLeon** [comment]
Dear @pablobarreira,

Thank you for notifying us about this problem. It seems the certificate for opendata.skgeodesy.sk expired just a few days after we released the next validator version. We have updated it in our [staging environment](http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/home/index.html), so you can keep testing in there.

Furthermore, rest assured that the certificate will be updated in the upcoming hot-fix of the VALIDATOR coming soon. Should you encounter any additional issues or have further feedback, please don't hesitate to reach out to us.

Regards,
