### ISSUE TITLE
CSW ETS Test - Extended Capabilities - Mandatory elements

### ISSUE THREAD

**Issue by manilly** [INSPIRE-MIF/helpdesk-validator#101]
Hi,

as requested by Marco Minghini I've tested the ETS for CSW at the ETF Staging Validator Instance.

I've have a question/bug regarding the test
Test-Result: http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/v2/TestRuns/EID747d3888-5b8d-453d-afed-570f95cd5348.html
CSW-Endpoint: https://geometadaten.lfrz.at/at.lfrz.discoveryservices/srv/ger/csw?service=CSW&request=GetCapabilities&version=2.0.2

**Extended Capabilities - Mandatory elements**
Error-Message: `Exactly one '/Capabilities/ServiceProvider/role' element shall be provided. It was found 0 or more than 1.`
But we have exactly one ServiceProvider with exactly one role:
```
<ows:ServiceProvider>
    <ows:ProviderName>Bundesministerium für Nachhaltigkeit und Tourismus</ows:ProviderName>
    <ows:ProviderSite xlink:href="https://geometadaten.lfrz.at/at.lfrz.discoveryservices" />
    <ows:ServiceContact>
      <ows:IndividualName>Wolfgang Fahrner</ows:IndividualName>
      <ows:PositionName>Administrator</ows:PositionName>
      <ows:ContactInfo>
        <ows:Phone>
          <ows:Voice />
          <ows:Facsimile />
        </ows:Phone>
        <ows:Address>
          <ows:DeliveryPoint>Stubenring 1</ows:DeliveryPoint>
          <ows:City>Wien</ows:City>
          <ows:AdministrativeArea />
          <ows:PostalCode>1010</ows:PostalCode>
          <ows:Country>Österreich</ows:Country>
          <ows:ElectronicMailAddress>wolfgang.fahrner@bmnt.gv.at</ows:ElectronicMailAddress>
        </ows:Address>
        <ows:HoursOfService />
        <ows:ContactInstructions />
      </ows:ContactInfo>
      **<ows:Role>pointOfContact</ows:Role>**
    </ows:ServiceContact>
  </ows:ServiceProvider>
```

**Comment by manilly** [comment]
Maybe the test is case insensitive
--> looking for `role` but only finding `Role`?

**Comment by josemasensio** [comment]
Dear @manilly,

Thank you for your message. We will check the issue as soon as possible. It looks like the validator checks for `role` instead of `Role`. We are going to correct it now.

Best regards.

**Comment by josemasensio** [comment]
Dear @manilly,

We published the solution on [staging](http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/) enviroment. 

Please, can you check that everything is ok and give us your feedback?

Best regards.

**Comment by manilly** [comment]
@josemasensio 
unfortunately not. new/same error `Exactly one '/Capabilities/ServiceProvider/Role' element shall be provided. It was found 0 or more than 1.` despite having the role element in the csw GetCapabilities
http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/v2/TestRuns/EID032db6f3-6bba-4cd7-b34a-b18afdf6491c.html
https://geometadaten.lfrz.at/at.lfrz.discoveryservices/srv/ger/csw?request=GetCapabilities&service=CSW&version=2.0.2

At least in the error text, the message has changed to Role with uppercase R ;)

**Comment by josemasensio** [comment]
Dear @manilly,
Please check it now. 

Best regards.

**Comment by manilly** [comment]
perfect, works now as expected
