### ISSUE TITLE
INSPIRE Validator does not recognize ATOM certificate - Slovakia

### ISSUE THREAD

**Issue by peterkysel27** [INSPIRE-MIF/helpdesk-validator#1012]
Hello,
we have the same problem as our colleagues from Spain here (https://github.com/INSPIRE-MIF/helpdesk-validator/issues/1008). When we try to validate an ATOM (no matter if I use production or staging validator), we get an error message.

Link to the ATOM: https://opendata.skgeodesy.sk/atom/INSPIRE_AU_dlsFeed.atom

If we tried the ATOM on another server (for example on https://ako.vugk.sk/atom/INSPIRE_AU_dlsFeed.atom), the validator works normally. So we think the problem could be with the certificate.

Here is our certificate:
![certificate](https://github.com/INSPIRE-MIF/helpdesk-validator/assets/153062514/6cb2d865-584b-4352-9d05-8063b86028cd)

And here is the error message: 
[error.txt](https://github.com/INSPIRE-MIF/helpdesk-validator/files/13577689/error.txt)

Thank you very much for your help.
Peter Kysel

**Comment by jenriquesoriano** [comment]
Dear @peterkysel27 ,

thank you for communicating the issue.
We will proceed to include the certificate in the Staging Instance and come back to you as soon as it is updated and ready to test.

Best regards,

**Comment by DanielMartinPerezdeLeon** [comment]
Dear @peterkysel27 ,

Thank you for bringing this issue to our attention.

We've successfully incorporated the certificate into our staging deployment, resolving the accessibility problem for the ATOM. You can verify it and use other urls on http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/home/index.html. 

Furthermore, rest assured that this certificate will be included in the upcoming official release of the VALIDATOR. Should you encounter any additional issues or have further feedback, please don't hesitate to reach out to us.

Regards,

**Comment by peterkysel27** [comment]
The staging version of the validator works well now. Thank you.

**Comment by peterkysel27** [comment]
Hello.
Is this change already included in the production version of the validator? When I tried to validate our ATOM Feed today, I got the same error as before...
![image](https://github.com/INSPIRE-MIF/helpdesk-validator/assets/153062514/fdf4af56-c737-4b1b-b963-107326bf6110)

Even the staging version is not working. Here is the error message:
[error2.txt](https://github.com/INSPIRE-MIF/helpdesk-validator/files/14430213/error2.txt)
Could it be the problem that there was a new certificate issued? (see the picture below)
![certificate2](https://github.com/INSPIRE-MIF/helpdesk-validator/assets/153062514/fd85de8a-31ac-459a-9432-7b0cb21890fb)

Thanks for your help.
Peter Kysel

**Comment by DanielMartinPerezdeLeon** [comment]
Dear @peterkysel27,

Thank you for notifying us about this problem. It seems the certificate for opendata.skgeodesy.sk expired just a few days after we released the next validator version. We have updated it in our [staging environment](http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/home/index.html), so you can keep testing in there.

Furthermore, rest assured that the certificate will be updated in the upcoming hot-fix of the VALIDATOR coming soon. Should you encounter any additional issues or have further feedback, please don't hesitate to reach out to us.

Regards,

**Comment by peterkysel27** [comment]
Thank you, the staging version is working properly now. But what could be the reason that it is not working after the certificate is issued? When we tried to put the feeds to another server with another adress (ako.vugk.sk) for testing purposes, the validator was working properly without having to write to you to include the certificate in the validator...

**Comment by DanielMartinPerezdeLeon** [comment]
Dear @peterkysel27,

It looks like the certificate we used for opendata.skgeodesy.sk was valid only until february 20th. Consequently, any VALIDATOR instance utilized until that date should have been able to access the portal resources without issues.

We have updated the certificate in the staging environment, so any other instances should not be able to test opendata.skgeodesy.sk resources unless the certificate is updated in the .../res folder of the Dockerfile image ZIP archive (We will be uploading this change in a release soon, but if you need any help with this beforehand you can contact us).

Essentially, the issue seems to be a matter of timing. If you require further clarification or assistance with updating the certificate or any other aspect, please don't hesitate to reach out. We're here to help and any further questions or details about this topic is appreciated, so please feel free to reply with any other questions.

Regards,

**Comment by peterkysel27** [comment]
Thanks for the explanation. The staging version of the validator works well now with all our feeds.

**Comment by fabiovinci** [comment]
The fix for this issue is now available in the [production instance](https://inspire.ec.europa.eu/validator/home/index.html).
For further details, please visit the [v2024.0.1 release notes](https://github.com/INSPIRE-MIF/helpdesk-validator/releases/tag/v2024.0.1).
