### ISSUE TITLE
Support for custom query parameters in WMS/WFS GetCapabilities or token authentication URL parameters

### ISSUE THREAD

**Issue by Kate-Lyndegaard** [INSPIRE-MIF/helpdesk-validator#1013]
We have WMS and WFS services that require token authentication provided in the URL.

Here is an example URL with token authentication: 
[https://haleconnect.com/ows/services/org.1326.b6b2f6ed-14da-4657-9e8e-e15538fd6d57_w[…]PeJ5vXhsyZpg34CjFY3ZBWgZwUgVG1SmoUFzMLeGCICihCrYVWY-xpa4qh7bQ](https://haleconnect.com/ows/services/org.1326.b6b2f6ed-14da-4657-9e8e-e15538fd6d57_wms?SERVICE=WMS&REQUEST=GetCapabilities&VERSION=1.3.0&kelvin_token=eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxMzI2IiwiZXhwIjoxNzAyOTczODUzfQ.Xw26pl4L7WJ5srMGyn6Gf1gOIPeJ5vXhsyZpg34CjFY3ZBWgZwUgVG1SmoUFzMLeGCICihCrYVWY-xpa4qh7bQ)

Currently, these services fail the WMS and WFS conformance classes because the token is not included in the validator requests. We would like to request that the validator support services which require token authentication, or alternatively custom query parameters in the WMS/WFS GetCapabilities.

**Comment by jenriquesoriano** [comment]
Dear @Kate-Lyndegaard ,

thank you for your enhancement suggestion.
In order to collect feedback from the community, we have converted this issue to a discussion, so we can obtain further input from the community.

Best regards,
