### ISSUE TITLE
About INSPIRE Reference Validator from Annex III Product and Industrial Facility from Romania

### ISSUE THREAD

**Issue by marianaapostol** [INSPIRE-MIF/helpdesk-validator#1014]
Dear all,

I need your support to clarify  why I can't trace the Inspire validator for product and industrial facilities Annex 3 for files that have already been reported/approved  to CE.

- - I attached the error log file;
-   I attached the file for which I tried to run the validation
-  the browser is google chrome version 119.0.6045.200 (Versiune oficială) (64 de biți)

[error_validator_EURegistry2022 .txt](https://github.com/INSPIRE-MIF/helpdesk-validator/files/13601062/error_validator_EURegistry2022.txt)
[EU_Registry_RO_2022.zip](https://github.com/INSPIRE-MIF/helpdesk-validator/files/13601074/EU_Registry_RO_2022.zip)

Best regard,

Mariana Apostol 
Head of Informational System Service from NEPA Bucharest

**Comment by fabiovinci** [comment]
Dear @marianaapostol,

your dataset is compliant with the EUReg application schema, which is based on a modified version of the INSPIRE 'Production And Industrial Facilities - Core' application schema (v4.0), so it is not valid according to the standard INSPIRE PF application schema.

The [Conformance Class 'GML application schema, Production and Industrial Facilities'](http://inspire.ec.europa.eu/id/ats/data-pf/master/pf-gml) will definitely fail, instead for the "gmlas.b.2: validate XML documents against declared schema" test you need to add the declaration of the gml schema (http://www.opengis.net/gml/3.2 http://schemas.opengis.net/gml/3.2.1/gml.xsd) in the schemaLocation attribute.

**Comment by fabiovinci** [comment]
Dear @marianaapostol,

I hope the provided answer was clear enough, so I will close the issue.
Please reopen the issue or open a new one if you have further questions.
