### ISSUE TITLE
Download link in Dataset ATOM Feed ends up with "The server experienced a several unexpected error"

### ISSUE THREAD

**Issue by peterkysel27** [INSPIRE-MIF/helpdesk-validator#1016]
Hello,

we tried to validate these ATOM feeds for Cadastral Parcels:
https://opendata.skgeodesy.sk/atom/INSPIRE_CP_KN_dlsFeed.atom
https://opendata.skgeodesy.sk/atom/INSPIRE_CP_UO_dlsFeed.atom

In the Dataset Feed section we always end up with error "The server experienced a several unexpected error. Please, try again later. if the problem persist, please contact with the helpdesk." for the download link of the dataset. See:
http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/test-run/details.html?id=EIDda212065-b851-4a92-9b81-dd3b975f6a2a
![image](https://github.com/INSPIRE-MIF/helpdesk-validator/assets/153062514/ed27641d-c9b5-4b7f-a1e6-d36348a61b9b)

I understand, that the HTTP status code have to be one of the mentioned. However, when I try to run the link, which was tested (https://opendata.skgeodesy.sk/8/0), the download of the ZIP file containing GML files starts normally with code 200. I tried to run it 7 times in a row and I always got code 200 (see the screenshot below). So we do not know why the validator shows the link as an error.
![image](https://github.com/INSPIRE-MIF/helpdesk-validator/assets/153062514/517c96db-7b8e-49c5-ace5-6a88bc8dfdde)

Could you, please, help me with this problem?

Best regards,
Peter Kysel

**Comment by fabiovinci** [comment]
Dear @peterkysel27,

I had a look at your ATOM services and it seems they are ok, it is strange that they both fails for the latest entry.
We will further investigate.

**Comment by peterkysel27** [comment]
Hello,

today we moved our ZIP files with Cadastral Parcels GML files to another location, because one of our customers had problems downloading them via automated script. After moving to another location, the validation of the ATOM feed ended up with "passed" result, so I am now closing this issue.

**Comment by justinelliotmeyers** [comment]
@peterkysel27 could you share a google drive link or something with the parcel files you have? Their sites are down (*they have been hacked). Really appreciate it!
