### ISSUE TITLE
Error while trying to test our Belgian Brussels CSW

### ISSUE THREAD

**Issue by fdumortier** [INSPIRE-MIF/helpdesk-validator#102]
Dear,

Following Marco's invitation to test our Brussels CSW, I tried it with following URLs and without tags (by the way, I don't know what this field is used for) :

1. http://www.geo.irisnet.be/geonetwork/srv/fre/csw 
2. http://www.geo.irisnet.be/geonetwork/srv/fre/csw?service=CSW 
3. http://www.geo.irisnet.be/geonetwork/srv/fre/csw?request=GetRecords&service=CSW
4. http://www.geo.irisnet.be/geonetwork/srv/fre/csw?request=GetRecords&service=CSW&version=2.0.2&resultType=results
5. http://www.geo.irisnet.be/geonetwork/srv/fre/csw?request=GetRecords&service=CSW&version=2.0.2&resultType=results&namespace=xmlns%28csw%3Dhttp%3A%2F%2Fwww.opengis.net%2Fcat%2Fcsw%2F2.0.2%29%2Cxmlns%28gmd%3Dhttp%3A%2F%2Fwww.isotc211.org%2F2005%2Fgmd%29&outputFormat=application%2Fxml&outputSchema=http%3A%2F%2Fwww.isotc211.org%2F2005%2Fgmd&elementSetName=full&constraint=keyword+LIKE+%27%25Reporting%20INSPIRE%25%27&constraintLanguage=CQL_TEXT&constraint_language_version=1.1.0&typeNames=gmd%3AMD_Metadata%2Cgmd:MD_Metadata

But every above mentioned URL fails with an errror. Error displayed for URL 1 to 4 is:
Test Run initialization failure
The test object type could not be determined. Check the uploaded / referenced resource. Uploaded files may only contain test data and no other files. If the problem persists, please contact the ETF system administrator of the server.

And for URL 5:
Test Run initialization failure
The Test Objekt Type 'Metadata records' is not one of the expected types that can be tested in this test run.

Kind regards,

François Du Mortier

**Comment by josemasensio** [comment]
Dear @fdumortier, 

Thank you for your message. We have checked and the correct url must be this one: http://www.geo.irisnet.be/geonetwork/srv/fre/csw?service=CSW&request=GetCapabilities&version=2.0.2

Please, check if this work. We will wait for your feedback.

Best regards.

**Comment by fdumortier** [comment]
Dear Jose,

It is already much better. But please note that in our case we need to select INSPIRE data sets metadata only (and not all of them) out of the CSW by applying the following filter:

&constraint=keyword+LIKE+%27%25Reporting%20INSPIRE%25%27&constraintLanguage=CQL_TEXT&constraint_language_version=1.1.0

And when I append this to the URL, your tool removes this filter. Is there another way to apply that filter?

(It would also be helpful to provide some explanation about how the URL should be encoded in the related field.)

Kind regards,

François Du Mortier

  [cid:cirb_48ee021e-930c-4d9c-b9ae-589a94eea2ab.png]

François DU MORTIER
Manager
Customer Solutions - Consultancy
Avenue des Arts 21, 1000 Bruxelles - cirb.brussels<http://cirb.brussels/> - disclaimer<http://cirb.brussels/disclaimer-1>
T +32 2 563 25 54 | G +32 497 59 91 64 | Helpdesk +32 2 801 00 00
Be green, leave it on the screen !                                          [cid:linkedIn_391f8333-965b-4b73-9dbc-f68a4356657b.png] <https://www.linkedin.com/company/cirb_cibg>   [cid:twitter_a7266c6c-f7c1-4a59-bfea-6e55a9e45977.png] <https://twitter.com/CIRB_CIBG>   [cid:instagram_6c5b6650-f542-425c-90ea-124ef97209c4.png] <https://www.instagram.com/cirb_cibg/>   [cid:logo_eco_mail2_ea9ebf7c-274d-4f6f-a7e5-3a2b8d3efa28.jpg] <http://www.environnement.brussels/thematiques/ville-durable/le-label-entreprise-ecodynamique>

De : Jose Asensio [mailto:notifications@github.com]
Envoyé : mercredi 28 août 2019 12:43
À : inspire-eu-validation/community <community@noreply.github.com>
Cc : DU MORTIER François <fdumortier@cirb.brussels>; Mention <mention@noreply.github.com>
Objet : Re: [inspire-eu-validation/community] Error while trying to test our Belgian Brussels CSW (#102)


Dear @fdumortier<https://github.com/fdumortier>,

Thank you for your message. We have checked and the correct url must be this one: http://www.geo.irisnet.be/geonetwork/srv/fre/csw?service=CSW&request=GetCapabilities&version=2.0.2

Please, check if this work. We will wait for your feedback.

Best regards.

**Comment by josemasensio** [comment]
Dear @fdumortier,

Thank you for replying. We will look into that. We will come back to when a decission is taken as soon as possible.

Greetings.

**Comment by MarcoMinghini** [comment]
Dear @fdumortier,
the validator just looks at the service itself, without any check on the metadata published by the service. So, the presence of the filter is not relevant.

After testing this Discovery Service, you can notice that an error is raised on [this assertion](https://github.com/inspire-eu-validation/discovery-service/blob/review-ats-csw-3.1/csw-iso-ap/at-12-discover-resource-matching-query.md). In particular, as you can see in the test report, this request raises an exception: 

http://www.geo.irisnet.be/geonetwork/srv/fre/csw?ELEMENTSETNAME=full&MAXRECORDS=1000&OUTPUTFORMAT=application%2Fxml&OUTPUTSCHEMA=http%3A%2F%2Fwww.isotc211.org%2F2005%2Fgmd&REQUEST=GetRecords&RESULTTYPE=results&SERVICE=CSW&TYPENAMES=csw%3ARecord&VERSION=2.0.2
