### ISSUE TITLE
Error response from daemon: Get "https://ghcr.io/v2/": EOF

### ISSUE THREAD

**Issue by noviljohnson** [INSPIRE-MIF/helpdesk-validator#1026]
hi
i am using this command docker pull ghcr.io/nlmatics/nlm-ingestor:latest
i am getting this error
Error response from daemon: Get "https://ghcr.io/v2/": EOF

for this " docker login ghcr.io -u username -p gh_pat " command also i am getting the same error.

thanks.

**Comment by Surya-R-1999** [comment]
Hi,

I'm also facing the same issue.  Could anyone resolve it? 

thanks

**Comment by DanielMartinPerezdeLeon** [comment]
Dear @noviljohnson, @Surya-R-1999 

Could you provide us with more info about the issue? 

It seems is not related with the INSPIRE-reference validator repository.

Thanks a lot.

**Comment by noviljohnson** [comment]
Hi @DanielMartinPerezdeLeon
i was following the steps mentioned in this repo https://github.com/nlmatics/nlm-ingestor
to deploy that model in my system.

i got the error while i was trying to pull docker image using the following command
" docker pull ghcr.io/nlmatics/nlm-ingestor:latest "
error:
" Error response from daemon: Get "https://ghcr.io/v2/": EOF "

i also tried the following command, got same error
" docker login ghcr.io -u username -p github_personalaccestoken "
error:
" Error response from daemon: Get "https://ghcr.io/v2/": EOF "

Docker version 24.0.7

i saw some docker issues here, so i posted mine as well.
so, please help us if could.


thank you.

**Comment by fabiovinci** [comment]
Dear @DanielMartinPerezdeLeon,

the docker issues posted in this repository are strictly related to the deployment of the INSPIRE Reference Validator.
So, we will close the issue. 
Thank you for your understanding.
