### ISSUE TITLE
Unable to open online version of the INSPIRE validator

### ISSUE THREAD

**Issue by dlutsVMM** [INSPIRE-MIF/helpdesk-validator#103]
Today when trying to access the validator from: http://inspire.ec.europa.eu/validator/about/
I get the following error message:

504 Gateway Time-out
nginx/1.14.1

OR:

![afbeelding](https://user-images.githubusercontent.com/51995472/63842559-1b750d00-c985-11e9-8f85-c9a367b5800f.png)

Occurs in Firefox 60.7

**Comment by carlospzurita** [comment]
Dear @dlutsVMM ,
We are aware of the error and we are working on restoring the service. We will get back to you when it's running again.

**Comment by josemasensio** [comment]
Dear @dlutsVMM,

Glad to inform you that the ETF validator is available again. 
Best regards.

**Comment by dlutsVMM** [comment]
Thank you, the problem is completly soflved.
And I think you can consider it to be 'tested'.
Me and other people have used it succesfully multiple times.
