### ISSUE TITLE
IACS validator - Keywords issues

### ISSUE THREAD

**Issue by marceaulouis** [INSPIRE-MIF/helpdesk-validator#1031]
I face issues with the IACS Conformance Class 2c validator. I constantly face errors regarding the keywords :

- I have to force the english version of "common agricultural policy" keyword from the GEMET Concepts thesaurus fot it to pass, french version is not recognised
- Similarly, the "Land cover" keywords from the INSPIRE data theme is not recognised
- Any  occurence of an "IACS" keyword elsewhere in the keywords generates an error
- It seems that there are problems recognising the anchors of the thesaurus titles

The metadata that I try to validate is here (conform with the Conformance Class 2b test) : https://metawal.wallonie.be/geonetwork/inspire/fre/csw?REQUEST=GetRecordById&SERVICE=CSW&version=2.0.2&elementSetName=full&outputSchema=http://www.isotc211.org/2005/gmd&id=314690bf-016c-4f07-a6d2-de894ba8020b

[IACS_MD_BE.zip](https://github.com/INSPIRE-MIF/helpdesk-validator/files/14370416/IACS_MD_BE.zip)

Best regards

**Comment by fabiovinci** [comment]
Dear @marceaulouis,

regarding the error related to the INSPIRE data theme, the Validator is looking for the values LPIS or GSAA, in case the CharacterString encoding is used (as in your case).

```xml
        <gmd:keyword>
            <gco:CharacterString>LPIS</gco:CharacterString>
        </gmd:keyword>
```

![image](https://github.com/INSPIRE-MIF/helpdesk-validator/assets/22212406/2bf22b5e-9106-4108-aea6-f71dccab78fa)

If the anchor encoding is used, the check is made on the href link, so, in this case, the element value can be provided in the national language.

```xml
        <gmd:keyword>
            <gmx:Anchor xlink:href="http://inspire.ec.europa.eu/metadata-codelist/IACSData/lpis">SIPA</gmx:Anchor>
        </gmd:keyword>
```

**Comment by fabiovinci** [comment]
Dear @marceaulouis,

it seems you corrected the metadata and now there are no more errors (Test report: https://inspire.ec.europa.eu/validator/test-reports/details.html?id=EID2568e62a-6b4e-43ae-85eb-6e3e26ee79be).
I will close the issue, please reopen it or open a new issue if the error persists.
