### ISSUE TITLE
AU(Administrative Units) - Error in boundary

### ISSUE THREAD

**Issue by CristinaMSL** [INSPIRE-MIF/helpdesk-validator#1036]
Dear INSPIRE support:

I have a question on the topic AU-Administrative Units.

When validating the GML, the following error appears:
 XML document 'GML_au_administrative_units_v4.gml', AdministrativeBoundary 'au_administrative_units_1': Feature does not correspond to an edge in the topological structure formed by the complete boundary graph of all Administrative Units features. It is not on the boundary of any administrative unit in the dataset.

![image](https://github.com/INSPIRE-MIF/helpdesk-validator/assets/160479583/a5605140-3716-42d2-801d-598178a93c5d)

We do not know very well, why this message comes out. 
We have used the FeatureType of "AdministrativeBoundary" to make the relationships.
The only thing we can think of from the message and the options given in the section: Source: Abstract Test Case 'Boundary', INSPIRE Data Specification on Administrative Units, A.3.9; is that this happens because in our project we only have 3 of 6 nationalLevel (AdministrativeHierarchyLevel).

Why could this be happening?

I am using HALE Studio and the official schema to perform my transformation.

Regards

**Comment by fabiovinci** [comment]
Dear @CristinaMSL,

the error should be because the validator does not find any administrative unit, in the dataset, whose contour corresponds to the boundary. Could you please confirm if this is the case?

If you send us the gml, we can have a look.

**Comment by CristinaMSL** [comment]
Hello Fabio.

Thank you very much. I will send you the gml.

**Comment by fabiovinci** [comment]
Dear @CristinaMSL,

I had a look at your gml file and I confirm that the error is due to the lack of the AdministrativeUnit feature types.
It would be best to create a unique dataset containing both feature types.

Please also consider that the Administrative Units data theme has been updated and the official AU application schema is now at version 5.0 (https://inspire.ec.europa.eu/schemas/au/5.0/AdministrativeUnits.xsd).

**Comment by fabiovinci** [comment]
Dear user,

we hope the solution provided helps you resolve the issue.
So we close this issue.
If there are any further questions or problems, please do not hesitate to reopen it or create a new issue.
