### ISSUE TITLE
The validator does not work

### ISSUE THREAD

**Issue by CristinaMSL** [INSPIRE-MIF/helpdesk-validator#1037]
Hello, is the inspire validator working properly? Since yesterday I have been having problems validating GML, from the different attachments. I get errors like 400, 413, 500 or just "there was an error".
The same thing happens when trying to validate gml, which I have already validated correctly from other issues already done.

What could be happening?

**Comment by jenriquesoriano** [comment]
Dear @CristinaMSL ,

thank you for your feedback.
The INSPIRE Reference Validator has had intermittent downtime during today.
Please note that it has been in the process of upload and testing of the [v2024.0.1 release](https://github.com/INSPIRE-MIF/helpdesk-validator/issues/1038).

In case you experience any issue, please do not hesitate to contact us.

Best regards,
