### ISSUE TITLE
ETF API production endpoint not available

### ISSUE THREAD

**Issue by klimeto** [INSPIRE-MIF/helpdesk-validator#104]
Dear ETF providers,

It seems the ETF API on the production environment is not available?

The NGINX web server times out:

```bash
root@vmi141395:~# curl "http://inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/v2/status"
<html>
<head><title>504 Gateway Time-out</title></head>
<body bgcolor="white">
<center><h1>504 Gateway Time-out</h1></center>
<hr><center>nginx/1.14.1</center>
</body>
</html>

```
Is it a planned maintenance window?

Many thanks,
Tomas

**Comment by josemasensio** [comment]
Dear @klimeto,
We are aware of the error and we are working on restoring the service. We will get back to you when it's running again.

Best regards.

**Comment by josemasensio** [comment]
Dear @klimeto,

Glad to inform you that the API is available again.
Best regards.

**Comment by ghost** [comment]
I also tried to use the API but it seems that service is down.

I used Swagger UI (Get extended service status) to verify if the service is online. 

Response Code is 404.

**Comment by josemasensio** [comment]
Dear @klimeto,

Thank you for your answer. We will check where the problem is to correct as soon as possible. 

Best regards

**Comment by MarcoMinghini** [comment]
@klimeto @DeordD the API is working regularly.
We noticed an error in the Swagger documentation, which was pointing to the wrong address (this is probably why you got a 404 response code).

**Comment by gdibw** [comment]
Thanks a lot for quick response.

Response code is 200. I also succesfully validated one metadata record.

In my opinion you can close the ticket.

**Comment by klimeto** [comment]
@MarcoMinghini @josemasensio 

Did you traceback what caused the crash of the ETF API production instance? 

The reason I ask is we use API of the **ETF INSPIRE Reference Validator** as a fundamental tool to validate INSPIRE resources provided by NSDI stakeholders in Slovakia in order to ensure we provide INSPIRE Geoportal downloadable and viewable datasets. 

Many thanks,
Tomas

**Comment by MarcoMinghini** [comment]
@carlospzurita did you have a chance to investigate?

@klimeto we are discussing internally how to limit the access to the API to avoid that the Validator crashes again. We will inform you once you can start again with your tests.

**Comment by klimeto** [comment]
@MarcoMinghini 

What do you mean by limiting the API?

How many requests the current ETF API can handle?

**Comment by MarcoMinghini** [comment]
@klimeto I mean that we need to set a limit in the API usage to allow anyone to use the Validator without the risk that it crashes, especially giving that more and more organizations will make use of the API in the future. For massive validations (especially if you have urgent needs and heavy performance requirements), our suggestion is to set up your own instance of the validator.

**Comment by klimeto** [comment]
@MarcoMinghini 

Could you share with me instructions on how to set up an instance of the last version of ETF with details on how to ensure that all ETS available in the INSPIRE reference validator production would be available in our own instance?

Many thanks!

**Comment by MarcoMinghini** [comment]
@klimeto we are organizing a developer workshop at the JRC on October 2 (October 1 is for users). How to setup an instance of the Validator to include specific ETS is among the topic addressed in the workshop (see the agenda [here](https://github.com/inspire-eu-validation/community/issues/20#issuecomment-524858688)). If you cannot come, all materials will be made available afterwards. If you want to attend, please let me know asap (there is still one seat available).

**Comment by klimeto** [comment]
@MarcoMinghini thanks a lot for invitation! I cannot make it for a whole day, but will try to attend the session on ETF deployment and CI.

**Comment by MarcoMinghini** [comment]
@klimeto you are welcome. Maybe just send me a confirmation by e-mail. See you soon in Ispra!

**Comment by klimeto** [comment]
@MarcoMinghini

Sorry i couldn't make it yesterday. 

Are or will be the materials for ETF deployment and ETS integration using Docker available?

Many thanks, 
Tomas

**Comment by MarcoMinghini** [comment]
Dear @klimeto 
it's a pity you could not make it for the workshop. Yes, we plan to collect all the workshop materials (slides + some step-by-step tutorials) in a new folder under the Community repository. We need some more days to finalize the materials in light of the comments received during the workshop.
An announcement will follow in #20 when the materials will be available.
