### ISSUE TITLE
INSPIRE Reference Validator: drinkingWaterProtectionArea

### ISSUE THREAD

**Issue by HelmoetOrdina** [INSPIRE-MIF/helpdesk-validator#1040]
Hi, I tried to test one of my INSPIRE files using the  INSPIRE Reference Validator and it complains (among others): 

The property 'zoneType' has a value 'drinkingWaterProtectionArea' that cannot be retrieved using HTTP.

But that's just the definition as is mentioned in https://inspire-mif.github.io/uml-models/approved/html/EARoot/EA2/EA3/EA3/EA1/EA8241.htm

So, why does the test complain?

Please find attached the file and the testing report.
[20240306_test_inspire_reference_validator.zip](https://github.com/INSPIRE-MIF/helpdesk-validator/files/14510355/20240306_test_inspire_reference_validator.zip)

Thank you for being patient on a relatively newbee on the INSPIRE front...

**Comment by fabiovinci** [comment]
Dear @HelmoetOrdina,

to get more information about a specific Validator test, you can have a look at its ATS (Abstract Test Suite) linked in the test report.

![image](https://github.com/INSPIRE-MIF/helpdesk-validator/assets/22212406/8d08629c-54af-4b5d-b318-6bcaeeac646f)

In particular, for the elements for which the datatype is a codelist you need to use the link of the related codelist value available in an online registry.

![image](https://github.com/INSPIRE-MIF/helpdesk-validator/assets/22212406/dc407c48-62fb-476c-88cb-9cf3faa27a5d)

So, in your case, you should encode the element as follows:

```xml
<am:zoneType xlink:href="http://inspire.ec.europa.eu/codelist/ZoneTypeCode/drinkingWaterProtectionArea"
                xlink:title="drinkingWaterProtectionArea"/>
```

**Comment by HelmoetOrdina** [comment]
Hi Fabio, thank you very much, I'll check and correct it.
