### ISSUE TITLE
Blue header and footer too wide and fixed in results page, information window too narrow (2024.0.1)

### ISSUE THREAD

**Issue by dhdeangelis** [INSPIRE-MIF/helpdesk-validator#1042]
With v. 2024.0.1, in both the public instance and a local docker instance, the results of a test are shown within a very narrow central window whereas the blue background header and footer are far too wide and fixed in place (see below). This happens at least in Firefox (123.0) and Chromium (120.0.6099.224) in Linux.

It is still possible to export the test results to html and look at the result without blue header and footer in any of those browsers. This is therefore possibly a minor annoyance and not a serious bug.

From the validator:

![image](https://github.com/INSPIRE-MIF/helpdesk-validator/assets/51515911/57811987-c948-47ae-b1b1-e58d4c58e18e)

As a free html:

![image](https://github.com/INSPIRE-MIF/helpdesk-validator/assets/51515911/f8a52daa-84a9-45ca-91ea-f8f39d72b722)

**Comment by fabiovinci** [comment]
Dear @dhdeangelis,

thank you for the notification, we will fix it in the next release.

**Comment by fabiovinci** [comment]
Dear @dhdeangelis ,

the solution is available in [staging](https://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/test-selection/index.html), I tested it and it works fine.
Can you check it too, please?

**Comment by dhdeangelis** [comment]
Thank you @fabiovinci, that's good news. However, I could see if it works because I get the red error box whenever I want to proceed.
![image](https://github.com/INSPIRE-MIF/helpdesk-validator/assets/51515911/ce0aa30f-1020-478c-b13f-50b66383be34)

**Comment by jenriquesoriano** [comment]
Dear @dhdeangelis ,
we cannot reproduce the issue you are facing in the [Staging environment](https://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/home/index.html).
Could you please detail it?
Thank you in advance.
Best,

**Comment by fabiovinci** [comment]
Dear @dhdeangelis,

thank you for the check, in the meantime, we will include the fix in the next release.

**Comment by dhdeangelis** [comment]
> we cannot reproduce the issue you are facing in the [Staging environment](https://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/home/index.html).
> Could you please detail it?

@jenriquesoriano I guess it had to do with some network setting, both Firefox and Chromium had warned of "unsafe" connection. Then, upon giving the link to a metadata post for example the red box appeared.

> thank you for the check, in the meantime, we will include the fix in the next release.

@fabiovinci that's wise, I guess the problem in testeing had to do with network configuration, etc as answered above.

Thank you all and good luck with the new release.

**Comment by dhdeangelis** [comment]
I can now confirm this issue is not present in the docker version of 2024.1
