### ISSUE TITLE
web validator browser window not resizable

### ISSUE THREAD

**Issue by lorincztamas** [INSPIRE-MIF/helpdesk-validator#1044]
Dear Validator Team!

The test report window launched from the 'https://inspire.ec.europa.eu/validator/test-run/index.html' website cannot be resized.
The older version used to use it, it was very inconvenient.
Please, can this be improved? Thank you

My browser: Google Chrome 122.0.6261.112  (64 bit)

![image](https://github.com/INSPIRE-MIF/helpdesk-validator/assets/136338170/2f019cb1-3007-426f-8fa8-3a919454727b)

Best wishes,
Tamás Lőrincz

**Comment by fabiovinci** [comment]
Dear @lorincztamas, 

thank you for reporting.
We will close the issue since the same issue is already open (#1042).
Please follow the mentioned issue for updates.
