### ISSUE TITLE
Captcha is not working

### ISSUE THREAD

**Issue by mmarkulj** [INSPIRE-MIF/helpdesk-validator#1047]
Captcha is not working
http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/home/index.html
so it's unable to start validator, pls help

**Comment by jenriquesoriano** [comment]
Dear @mmarkulj ,

We have tested the staging environment, and it appears to be working correctly. 
The issue may have been caused by a temporary unavailability of the captcha endpoint. 

Could you please confirm that it is now working properly?

Best regards,

**Comment by mmarkulj** [comment]
Hi, captcha is still unavailable

________________________________

**Comment by jenriquesoriano** [comment]
Estimado @mmarkulj,

the issue appears to be intermittent and is likely due to an external dependency.
We are actively working to solve it.

In the meantime, if the fail rate you obtain with the "Antispam" option is very high, we suggest using the "Audio" option instead of the "Antispam", as it appears to have a higher success rate.

![imagen](https://github.com/INSPIRE-MIF/helpdesk-validator/assets/25343632/f8c0e756-e1b6-49d0-a637-167c2523a5f8)

Best regards,

**Comment by mmarkulj** [comment]
Sorry, but it's the same with audio

________________________________

**Comment by mmarkulj** [comment]
> Estimado @mmarkulj,
> 
> the issue appears to be intermittent and is likely due to an external dependency. We are actively working to solve it.
> 
> In the meantime, if the fail rate you obtain with the "Antispam" option is very high, we suggest using the "Audio" option instead of the "Antispam", as it appears to have a higher success rate.
> 
> ![imagen](https://private-user-images.githubusercontent.com/25343632/313130742-f8c0e756-e1b6-49d0-a637-167c2523a5f8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA1MDQyNzcsIm5iZiI6MTcxMDUwMzk3NywicGF0aCI6Ii8yNTM0MzYzMi8zMTMxMzA3NDItZjhjMGU3NTYtZTFiNi00OWQwLWE2MzctMTY3YzI1MjNhNWY4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE1VDExNTkzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWExMzFiNzhmODExYTdjOThhZGI2YjIyNjg5MGMyYTMxNTk1YzMxNDBkODkzMDNlNGQ1OTM1NjgxZTFhYTg4NDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.TgB59onMzeByX2AlIAJ8BBnpNaIRFaeuo_2kUMxXtNg)
> 
> Best regards,

Dear @jenriquesoriano do you have any estimation for solving this issue?

**Comment by jenriquesoriano** [comment]
Dear @mmarkulj ,

unfortunately, the captcha service is provided by other unit in the EC, so it doesn't rely on us solving the issue itself.
We are considering to implement alternative solutions and will come back to you as soon as possible.

Keep in contact.

Best regards,

**Comment by mmarkulj** [comment]
Ok, thank you!

________________________________

**Comment by jenriquesoriano** [comment]
The issue was solved by the EC captcha team.
