### ISSUE TITLE
ETF validator online seems to be stuck

### ISSUE THREAD

**Issue by dlutsVMM** [INSPIRE-MIF/helpdesk-validator#105]
It seems that the online version of the validator is stuck. Since this morning around 8h33 no new validation reports have been generated. There is a long list of request waiting but none seem to be being processed.
![afbeelding](https://user-images.githubusercontent.com/51995472/64242258-82567100-cf05-11e9-936c-75a9b6155ade.png)

On the status page you can see 4 test reports running, but they do not seem to be advancing (the percentage does not change).

![afbeelding](https://user-images.githubusercontent.com/51995472/64242427-c47fb280-cf05-11e9-87bd-e3a7160f9067.png)

Is this an issue or is there a test being run which takes a long time?

**Comment by carlospzurita** [comment]
Dear @dlutsVMM 

Sorry about the inconvenience, we are investigating the issue. We will come back to you with some more information.

**Comment by carlospzurita** [comment]
The validator is up and running again. It was stuck in those tests and was rejecting any other request.

**Comment by dlutsVMM** [comment]
Thanks for solving the problem!
