### ISSUE TITLE
FeatureCollection for INSPIRE Theme AM

### ISSUE THREAD

**Issue by HelmoetOrdina** [INSPIRE-MIF/helpdesk-validator#1054]
Hi, I am struggeling validating my INSPIRE AMGWBG gml document. 

First, validation tells me: 

> XML document 'inspire-pv-am.nlam-gwbg.gml': 1:1219: cvc-elt.1.a: Cannot find the declaration of element 'gml:FeatureCollection'.

- logfile: 20240321_0921_validation_result.html
- input gml file: 20240321_0921_inspire-pv-am.nlam-gwbg.gml

The input file uses as xsi:schemaLocation="http://inspire.ec.europa.eu/schemas/am/4.0 http://inspire.ec.europa.eu/schemas/am/4.0/AreaManagementRestrictionRegulationZone.xsd" 

I tried to fix it by appending http://www.opengis.net/gml/3.2 http://schemas.opengis.net/gml/3.2.1/deprecatedTypes.xsd to xsi:schemaLocation, as suggested in [this](https://community.safe.com/general-10/inspire-validator-problem-23242?postid=147595#post147595) post.

However, the INSPIRE Reference Validator now complains: 

> XML document 'inspire-pv-am.nlam-gwbg.gml': 9:103: cvc-complex-type.2.4.a: Invalid content was found starting with element '{"http://inspire.ec.europa.eu/schemas/am/4.0":ManagementRestrictionOrRegulationZone}'. One of '{"http://www.opengis.net/gml/3.2":AbstractFeature}' is expected.

- logfile:             20240326_0757_validation_result.html
- input gml file:  20240326_0757_inspire-pv-am.nlam-gwbg.gml

I suspect that I’m using an old and deprecated FeatureCollection, but where to find the current XSD? Is this indeed about the FeatureCollection?

Really a lot of thanks for responding.
[20240321_0921_validation_result.zip](https://github.com/INSPIRE-MIF/helpdesk-validator/files/14755330/20240321_0921_validation_result.zip)

**Comment by fabiovinci** [comment]
Dear @HelmoetOrdina,

I confirm that you need to add the gml schema in the schemaLocation attribute to avoid the error "_'Cannot find the declaration of element 'gml:FeatureCollection'._"

Please consider that in your second gml file (20240326_0757_inspire-pv-am.nlam-gwbg.gml) there is an error in the namespace:

![image](https://github.com/INSPIRE-MIF/helpdesk-validator/assets/22212406/78d46a57-8ed9-462f-bae4-cc4204dbac02)

so the rigth nameSpace value should be:

```xml
xsi:schemaLocation="http://inspire.ec.europa.eu/schemas/am/4.0 http://inspire.ec.europa.eu/schemas/am/4.0/AreaManagementRestrictionRegulationZone.xsd http://www.opengis.net/gml/3.2 http://schemas.opengis.net/gml/3.2.1/gml.xsd">
```

In this way, all the mentioned errors are no longer present: https://inspire.ec.europa.eu/validator/test-run/details.html?id=EID79373994-fe5c-4468-934a-d8c8fb65b821

**Comment by HelmoetOrdina** [comment]
I feel astonishing embarrassed, such a simple mistake, taking so long time for me to fix. 🫢 Thank you very much.
