### ISSUE TITLE
HY - Standing Water

### ISSUE THREAD

**Issue by CristinaMSL** [INSPIRE-MIF/helpdesk-validator#1055]
Hello.

I am working with a HY theme project, specifically with the "StandingWater" featuretype.

When I validate the GML result of making the relations, the following error messages appear:

1- error in the field localid: XML document 'prueba17.gml', StandingWater 'hy_standingwater_116': The following feature properties have an empty value: localId. Although this is valid according to the XML schema, it is not valid according to the GML model. Please correct the process that generates the GML documents.

In this case, the field localid, is connected with inspiredid/identifier/localid.

2- Errors with geometry: the geometry fields are of type multypoligon and at the time of making the relations, I connect the geometry field with the geometry field and the following errors appear:

-SURFACE GEOMETRY ELEMENTS -> XML document 'prueba17.gml', StandingWater 'hy_standingwater_102': A surface geometry with an invalid GML object element 'gml:CompositeSurface' was found. Planar surface types are restricted to Polygon or Surface elements.

VALIDATEGEOMETRIES 1 -> XML document 'prueba17.gml', StandingWater 'hy_standingwater_273': The feature geometry is not a valid GML geometry. Error detected: Element Polygon at position 1 within element null (gml:id: hy_standingwater_273): Ring Self-intersection. Start: (4515167.390500001 306057.5467000007), end: (4515167.390500001 306057.5467000007), problem: (4515168.492600002 306057.6819000001)

What could be happening?

I leave the gml in case it can be of help to understand the errors that appear.
[prueba17.zip](https://github.com/INSPIRE-MIF/helpdesk-validator/files/14773150/prueba17.zip)

Thank you very much in advance

**Comment by CristinaMSL** [comment]
Hello Fabio.

After doing numerous tests, I have managed to solve the errors I was telling you about.

**Comment by fabiovinci** [comment]
Hi @CristinaMSL,

I'm happy to hear that you've resolved the issues and I'm sorry I couldn't take a look at your file sooner.
I will close the issue, please reopen it or open a new issue if you have other errors.
