### ISSUE TITLE
problems validating with href "https://inspire.ec.europa.eu"

### ISSUE THREAD

**Issue by montsemarco** [INSPIRE-MIF/helpdesk-validator#1057]
Hi, 
When validating [this metadata](https://sitmun.diba.cat/metadades/srv/api/records/SPADBBU08005E1M/formatters/xml) I got an error in the "Resource locator for View Service Linkage"

![image](https://github.com/INSPIRE-MIF/helpdesk-validator/assets/1905272/0a7bcbaa-feda-4f0b-bb3d-b5d00655c034)
 
However, if I change to http instead https in the WMS applicationProfile branch

![image](https://github.com/INSPIRE-MIF/helpdesk-validator/assets/1905272/f95bed32-8fe4-43a6-a92e-67fae444478f)

The validator pass the "Resource locator for View Service Linkage" test:

![image](https://github.com/INSPIRE-MIF/helpdesk-validator/assets/1905272/4e7f9c6b-b573-4c0f-a659-ae8797963ea2)

I guess that http**s**://inspire.ec.europa.eu/*** should be accepted in all the branches where appears. For instance, when I put http**s**://inspire.ec.europa.eu/metadata-codelist/SpatialDataServiceType/view in a navigator it's reacheable, moreover, when I put http://inspire.ec.europa.eu/metadata-codelist/SpatialDataServiceType/view it redirects automatically to http**s**://inspire.ec.europa.eu/metadata-codelist/SpatialDataServiceType/view.

Is an error of the validator or I should change http**s**://inspire.ec.europa.eu to http in all my metadata?

Thanks and best regards,

**Comment by fabiovinci** [comment]
Dear @montsemarco,

even if the links are redirected from HTTP to HTTPS the official URI of the codelist values is the one in HTTP as indicated in the INSPIRE Registry.
![image](https://github.com/INSPIRE-MIF/helpdesk-validator/assets/22212406/b340fe2b-0de0-46b7-9d1b-37ae6a364c8f)

For this reason, the validator looks for the value in HTTP.

**Comment by montsemarco** [comment]
HI Fabio, thanks for the explanation. I change the metadata to http.
Best regards,
Montse
