### ISSUE TITLE
Temporary issues on the production instance

### ISSUE THREAD

**Issue by DanielMartinPerezdeLeon** [INSPIRE-MIF/helpdesk-validator#1060]
Dear INSPIRE users,

We regret to inform you that the Validator is currently experiencing technical difficulties which are affecting the accuracy of test results. We are diligently working to resolve these issues, and we will notify you as soon as the Validator is operational again.

Thank you for your patience and understanding.

Kind regards,

**Comment by jenriquesoriano** [comment]
Dear community, 

the INSPIRE Reference Validator is back to normal operation.
Please excuse the inconvenience.

Best regards,
