### ISSUE TITLE
cvc-complex-type.2.4.a: Invalid content was found starting with element

### ISSUE THREAD

**Issue by HelmoetOrdina** [INSPIRE-MIF/helpdesk-validator#1061]
Hi, I'm currently working on the INSPIRE ProtectedSites theme. The resulting gml file is rejected by  the Reference Validator, it says: 

`"cvc-complex-type.2.4.a: Invalid content was found starting with element '{"http://inspire.ec.europa.eu/schemas/ps/4.0":ProtectedSite}'. One of '{"http://www.opengis.net/gml/3.2":AbstractFeature}' is expected.". All of my features get this (and only this) remark. 
`

My TargetSchemalocation is 

`xsi:schemaLocation="http://inspire.ec.europa.eu/schemas/ps/4.0 http://inspire.ec.europa.eu/schemas/ps/4.0/ProtectedSites.xsd http://www.opengis.net/gml/3.2 http://schemas.opengis.net/gml/3.2.1/gml.xsd"`

In the namespace declarations I list: 

`<gml:FeatureCollection xmlns:gss="http://www.isotc211.org/2005/gss"
                        xmlns:gn="http://inspire.ec.europa.eu/schemas/gn/4.0"
                        xmlns:base="http://inspire.ec.europa.eu/schemas/base/3.3"
                        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                        xmlns:gsr="http://www.isotc211.org/2005/gsr"
                        xmlns:gco="http://www.isotc211.org/2005/gco"
                        xmlns:gml="http://www.opengis.net/gml/3.2"
                        xmlns:ps="http://inspire.ec.europa.eu/schemas/ps/4.0"
                        xmlns:gmd="http://www.isotc211.org/2005/gmd"
                        xmlns:xlink="http://www.w3.org/1999/xlink"
                        xmlns:gts="http://www.isotc211.org/2005/gts"                                                       
                        gml:id="id7e73551d-89d2-4e4d-b064-1aad42ee58b0"
                        xsi:schemaLocation="http://inspire.ec.europa.eu/schemas/ps/4.0
                                http://inspire.ec.europa.eu/schemas/ps/4.0/ProtectedSites.xsd http://www.opengis.net/gml/3.2
                                http://schemas.opengis.net/gml/3.2.1/gml.xsd">`

I use a gml:featureCollection (which is in gml:deprecatedTypes.xsd) to present a list of ps:ProtectedSite (which is in ps:ProtectedSites.xsd) objects. 

Looking at the definition of ps:ProtectedSite, it says: 
![Schermafbeelding 2024-04-03 155152](https://github.com/INSPIRE-MIF/helpdesk-validator/assets/115150315/b120f799-58d7-49ab-ac75-f3a7df7bd917)

That means that _**is**_ a gml:AbstractFeature. 

So why is the validator complaining? These are my input file and the validator report: 
[nlpsnnn_20240403_1415.zip](https://github.com/INSPIRE-MIF/helpdesk-validator/files/14853257/nlpsnnn_20240403_1415.zip)

Thanks for any help!

**Comment by fabiovinci** [comment]
Dear @HelmoetOrdina,

your gml file is compliant to version 4 of the PS application schema.

The only test that fails is the "[Validation against INSPIRE official schema](https://github.com/inspire-eu-validation/data-ps/blob/master/ps-gml/official-schema-validation.md)" since the validator uses for this test the new version 5 of the schema.

It is recommended that you update your dataset to match the new version to ensure full compliance.

**Comment by HelmoetOrdina** [comment]
Hi Fabio, thanks again for the help, I'll try and fix it.
