### ISSUE TITLE
INSPIRE validator error when validating a network service (WMS) metadata

### ISSUE THREAD

**Issue by montsemarco** [INSPIRE-MIF/helpdesk-validator#1062]
When trying to validate this [network service (WMS) metadata](https://sitmun.diba.cat/metadades/srv/api/records/SPADBBUE1MWMS/formatters/xml)  I got this error:

![image](https://github.com/INSPIRE-MIF/helpdesk-validator/assets/1905272/15a80eb4-dc0b-478d-b14a-0f67cb9198b7)

Moreover, I got also two errors indicating that this URL are not accessible, but in a navigator they are reacheable.

- Common Requirements for ISO/TC 19139:2007 based INSPIRE metadata records
      General requirements
          md common req C.1: XML Schema

             'Validation failed: -1:-1: schema_reference.4: Failed to read schema document 
              'http://schemas.opengis.net/csw/2.0.2/profiles/apiso/1.0.0/apiso.xsd', because 1) could not find the document; 2) the 
              document could not be read; 3) the root element of the document is not <xsd:schema>.'.
                   
- Conformance  Class 3: INSPIRE Spatial Data Service baseline metadata.
      Identification
           md sds 3.6: Coupled Resource

                 'http://sitmun.diba.cat/csw/servlet?SERVICE=CSW&VERSION=2.0.2&REQUEST=GetRecordById&outputSchema=http://www.isotc211.org/2005/gmd&ElementSetName=full&ID=SPADBBU08000E1M' that cannot be accessed. An exception occured when accessing 
                 the resource. Error message: Connection failed.

Thanks for your help and best regards

**Comment by fabiovinci** [comment]
Dear @montsemarco,

it seems they are errors related to the temporary unavailability or overload of the validator.

I tried now to validate your metadata and it works, see the related report: https://inspire.ec.europa.eu/validator/test-run/details.html?id=EID8e7f4987-292f-4acc-a0f0-1739d7ed2b18.

I close the issue, please reopen it if the error persists.
