### ISSUE TITLE
us-gml.a.1 error when checking a data set with conformity class GML application schemas, Utility and Government Services

### ISSUE THREAD

**Issue by g-weber** [INSPIRE-MIF/helpdesk-validator#1069]
Dear all,

Similar to #1058 the attached test run reports an error for 

The attached test run with data set https://schullandschaft.brandenburg.de/edugis/wfs/us-govserv-education/kitas?SERVICE=WFS&version=2.0.0&REQUEST=GetFeature&Count=10&typename=us-govserv:GovernmentalService&srsname=EPSG:4258 ends with the following error in us-gml.a.1:

> The XML documents representing the spatial data set do not contain a feature of any of the spatial object types in the 'Utility and Government Services' application schemas. Therefore, the spatial data set cannot conform to this conformance class. If you have expected to find spatial objects from the application schema in the data set, please consult the statistics information to see the spatial object types that have been found.

The feature statistics information reports that 10 GovernmentalService features heve been found.

[Test run on 14_36 - 29.04.2024 with test suite Annex III - Utility and governmental services (US).html.zip](https://github.com/INSPIRE-MIF/helpdesk-validator/files/15149492/Test.run.on.14_36.-.29.04.2024.with.test.suite.Annex.III.-.Utility.and.governmental.services.US.html.zip)

**Comment by fabiovinci** [comment]
Dear @g-weber,

it seems similar to the mentioned issue, but trying to save your WFS response as an XML file and modifying the namespaces it validates.

![image](https://github.com/INSPIRE-MIF/helpdesk-validator/assets/22212406/f73518a4-3db6-4bb7-a711-3b69da9b1511)

Attached are the modified file and the validation report: [sample.zip](https://github.com/INSPIRE-MIF/helpdesk-validator/files/15167132/sample.zip)

Please take into account the option of fixing your dataset by using the updated schema version and the related namespaces.

**Comment by g-weber** [comment]
Dear @fabiovinci, 

thanks for your support

**Comment by g-weber** [comment]
Dear @fabiovinci, 

thanks for your support .
