### ISSUE TITLE
Staging instance not working

### ISSUE THREAD

**Issue by Ana-SGA** [INSPIRE-MIF/helpdesk-validator#1076]
Dear all,

I am trying to use staging instance of the INSPIRE Validator (since INSPIRE Validator is down at this moment) for metadata validation but I can't upload the metadata file. I'm using this link https://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/home/index.html. Can somebody please look?

**Comment by fabiovinci** [comment]
Dear @Ana-SGA,

thank you for reporting the issue. We will take a look at it as soon as possible.

**Comment by Ana-SGA** [comment]
Dear @fabiovinci,

are there any news regarding staging instance? At this moment I can't reach https://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/test-selection/index.html (Not Found).

**Comment by jenriquesoriano** [comment]
Dear @Ana-SGA , 

we are operating the Staging instance for some architectural improvements to be incorporated for the next release, so you may experience discontinuities in the service when using https.
Please use http instead: http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/home/index.html
We will keep you posted.

Best regards,

**Comment by Ana-SGA** [comment]
Dear @jenriquesoriano,

thank you for info. But using http instead of https is just temporary?

Kind regards

**Comment by jenriquesoriano** [comment]
Dear @Ana-SGA,

Yes, it was a temporary measure so you could continue using the staging environment.

You can now access both HTTP and HTTPS endpoints:

- http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/home/index.html
- https://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/home/index.html

Please also note that the staging instance may experience service interruptions, as it is intended for testing purposes before moving to production.

Best regards,

**Comment by Ana-SGA** [comment]
Dear @jenriquesoriano,

ok, thank you for the info. I will close the issue.
