### ISSUE TITLE
LU - Errors percentageLis and backgroudMapURI

### ISSUE THREAD

**Issue by CristinaMSL** [INSPIRE-MIF/helpdesk-validator#1077]
Hello.

I am contacting you regarding the LU topic, specifically with the feature type "Zoning Elements".

The following errors appear:

XML document 'test5-hale2.gml': 28:33: cvc-complex-type.2.4.a: Invalid content found starting with element '{"http://inspire.ec.europa.eu/schemas/lunom/4.0":percentageList}'. One is expected from '{"http://inspire.ec.europa.eu/schemas/lunom/4.0":orderedList}'.

XML document 'test5-hale2.gml': 40:33: cvc-complex-type.2.4.a: Invalid content found starting with element '{"http://inspire.ec.europa.eu/schemas/lunom/4.0":percentageList}'. An element '{"http://inspire.ec.europa.eu/schemas/lunom/4.0":orderedList}' is expected.

In this case, I don't quite understand what you are referring to. I have made several tests and I don't understand what is wrong? What could it be? The content is not correct?

Another error that appears is the following:

XML document 'test5-hale2.gml': 55:268: cvc-complex-type.2.4.a: Invalid content found starting with element '{"http://inspire.ec.europa.eu/schemas/plu/4.0":backgroudMapURI}'. An element '{"http://inspire.ec.europa.eu/schemas/plu/4.0":backgroundMapURI}' is expected.

In this case, it is understood that the url of the base map that is used to represent the planned land use information must be indicated. In my case, I have added the url that I consider represents this information and it does not accept it. Why is that?
[prueba5-hale2.zip](https://github.com/INSPIRE-MIF/helpdesk-validator/files/15260707/prueba5-hale2.zip)

I leave attached to the message the corresponding gml, so that it is easier to review it.

Thank you very much in advance.

I look forward to your reply.

**Comment by fabiovinci** [comment]
Dear @CristinaMSL,

regarding the first issue, please coinsider that the two related data types, [HILUCSPresence](https://github.com/INSPIRE-MIF/technical-guidelines/blob/main/data/lu/dataspecification_lu.adoc#53212-hilucspresence) and [SpecificPresence](https://github.com/INSPIRE-MIF/technical-guidelines/blob/main/data/lu/dataspecification_lu.adoc#53214-specificpresence), are "`Union`", so it means that **only** one of the two attributes should be provided, `orderedList` or `percentageList`.

![image](https://github.com/INSPIRE-MIF/helpdesk-validator/assets/22212406/338daaf0-9289-4ea1-89ef-b5440ddd2467)

For the second, you need to change the encoding as the URL needs to be entered as the element value and not using the `nilReason` attribute.

E.g.:
```xml
<plu:backgroudMapURI>https://idecyl.jcyl.es/vcig/?service=https://idecyl.jcyl.es/geoserver/lu/wms&amp;layer=siu_cyl_ambmun&amp;type=wms&amp;style=lu%3Asiu_cyl_ambmun_vcig&amp;bbox=160000,4440000,605000,4790000&amp;srs=EPSG:25830</plu:backgroudMapURI>
```
I hope this helps to provide a better understanding and clears up any confusion.

**Comment by CristinaMSL** [comment]
Hello.

Thank you very much for your quick response.

Regarding error 1, by selecting only one of the fields, the error has disappeared.

Regarding error 2, I tried relating the field as you indicated, but the error came up again:

XML document 'TEST14.0002.gml': 43:32: cvc-complex-type.2.4.a: Invalid content was found starting with element '{"http://inspire.ec.europa.eu/schemas/plu/4.0":backgroudMapURI}'. One of '{"http://inspire.ec.europa.eu/schemas/plu/4.0":backgroundMapURI}' is expected.
Why does the error keep occurring?

I leave again the gml, with which I have made the test and an image o
[prueba14-imagen.zip](https://github.com/INSPIRE-MIF/helpdesk-validator/files/15274501/prueba14-imagen.zip)
f the connection of the field in Hale.
[prueba14-hale2.zip](https://github.com/INSPIRE-MIF/helpdesk-validator/files/15274495/prueba14-hale2.zip)

Thank you very much in advance.

**Comment by JohannaOtt** [comment]
@CristinaMSL There was a breaking change in the [PLU 4.0](https://inspire.ec.europa.eu/schemas/plu/4.0/PlannedLandUse.xsd) schema fixing the spelling of backgrou**n**dMapURI.
Seems like you are still using the spelling from the "old" 4.0 version.

**Comment by CristinaMSL** [comment]
Hello!

I have checked the version of the schematic https://inspire.ec.europa.eu/schemas/plu/4.0/PlannedLandUse.xsd, which is the one I am using coming from the official Inspire website.

It is true, that when adding it to the HALE program, the n does not appear. 
![image](https://github.com/INSPIRE-MIF/helpdesk-validator/assets/160479583/7151bfe3-6f79-43e9-b895-fdc1d5c64229)


Where can I find the correct url containing the n? I have been checking the inspire and github pages and I have not located the right version.

**Comment by fabiovinci** [comment]
@JohannaOtt, thanks for spotting the error, I missed it.

@CristinaMSL, It appears that HALE is utilizing a cached schema. It is recommended that you upgrade HALE to the latest version, which imports the most recent version of the schemas.
![image](https://github.com/INSPIRE-MIF/helpdesk-validator/assets/22212406/0591a326-2ad0-4315-9958-f6e909b36b31)

**Comment by CristinaMSL** [comment]
Hello.

I have used the latest version of Hale (5.1.0) and it does show the "n" in backgroundmapuri:

![image](https://github.com/INSPIRE-MIF/helpdesk-validator/assets/160479583/df56f311-8de1-4154-a4a8-c70e1c89c8f9)

After updating my files and using dehale version 5.1.0, I have been able to validate the gmls correctly.

Thank you very much to both of you for your answers.

Best regards

**Comment by fabiovinci** [comment]
Dear @CristinaMSL,

great to hear that you were able to fix the errors.
I will close the issue and please reopen it or open a new one if necessary.
