### ISSUE TITLE
Validation of the Discovery Service

### ISSUE THREAD

**Issue by AntoRot** [INSPIRE-MIF/helpdesk-validator#108]
I tested the national Discovery Service with the endpoint https://geodati.gov.it/RNDT/csw?request=GetCapabilities&service=CSW&acceptFormats=application%2Fxml&LANGUAGE=ita, selecting the conformance class "Discovery Service - CSW Core" included in the staging instance of the Validator.

Here the Test Report: http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/v2/TestRuns/EIDb226328c-95be-420b-8ea7-aa4eba91fc77.html

Two errors were reported:
[1] 
> One or more 'ExtendedCapabilities/SpatialDataSetIdentifier/Code' elements shall be provided. It was found 0.

(see Test Step URI: http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/v2/TestRuns/EIDb226328c-95be-420b-8ea7-aa4eba91fc77.html?lang=it#EID02615985-016d-1000-775d-e420bbdeac47)

[2] 
> In the path /Capabilities/OperationsMetadata/Operation[@name="GetRecords"]/Constraint[@name="SupportedISOQueryables"]/Value the following mandatory element(s) is(are) missing: Subject, SpatialResolution, BoundingBox, Title, Abstract, Type, TemporalExtent.

 (see Test Step URI: http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/v2/TestRuns/EIDb226328c-95be-420b-8ea7-aa4eba91fc77.html?lang=it#EID02615bd3-016d-1000-3723-2f09cffefb32).

Concerning the issue [1], the error reported is not relevant as the ExtendedCapabilities/SpatialDataSetIdentifier/Code element is not required for the discovery services.

Concerning the issue [2], based on the section 7.5 and the table 23 in the OGC specification (i.e. OpenGIS Catalogue Services Specification 2.0.2 - ISO Metadata Application Profile), the constraint named SupportedISOQueryables should list only the supported **additional queryables** (defined in the section 7.4 of the mentioned specification) and not also the core queryables (defined in the section 7.2.3.1 of the mentioned specification). 
Consequently, the queryables properties Subject, BoundingBox, Title, Abstract and Type (defined as core queryables properties) shouldn't be included in the SupportedISOQueryables constraint (as made in the GetCapabilities document of the endpoint tested).
Furthermore, concerning the queryables properties Spatial Resolution and Temporal Extent, they should be listed through their components, i.e. Denominator, DistanceValue and DistanceUOM for Spatial Resolution and TempExtent_begin, TempExtent_end for Temporal Extent (see tables 11, 12 and 13 in the mentioned OGC specification). In the capabilities document of the endpoint tested those components are included.

The conclusion is that no error should be reported for the issues [1] and [2].

**Comment by josemasensio** [comment]
Dear @AntoRot,

Thank you for your message. We have to see if the changes that you mention are correct. We will mark this issue as 'For-discussion' and we will come back to you when a decision is taken.

Best regards.

**Comment by AntoRot** [comment]
Thanks @josemasensio!

You can also see the example of a GetCapabilites document provided in the OGC schemas repository: http://schemas.opengis.net/csw/2.0.2/examples/capabilities/Capabilities_tC22.xml .

Best regards.

**Comment by danielnavarrogeo** [comment]
Dear Antonio,

We have analyzed this issue and we agree with your comments.

Now it does not check the existance of element 'ExtendedCapabilities/SpatialDataSetIdentifier/Code' either the core queryables.

You can check the implemented solution in the staging environment.

Regards

**Comment by AntoRot** [comment]
Dear Daniel,

I checked again the discovery service endpoint and now the solution works fine.

Regards

**Comment by danielnavarrogeo** [comment]
Thanks! I label it as solved.
