### ISSUE TITLE
INSPIRE Validator - Uploading GML file (gml, zip) results in error 413

### ISSUE THREAD

**Issue by ftporthlnug** [INSPIRE-MIF/helpdesk-validator#1080]
[PS__DE7_0945HLNUG__epsg4258_240514_0910.zip](https://github.com/INSPIRE-MIF/helpdesk-validator/files/15308202/PS__DE7_0945HLNUG__epsg4258_240514_0910.zip)

Today (2024-05-14), I was trying several times to validate gml/xml files with file upload of the ETF of the INSPIRE Reference Validator 
for the Annex I Theme Protected Sites (PS).

Uploading with Chromium (Version 118.0.5993.159 (Offizieller Build) (64-Bit)) and Firefox (125.0.3) (currently the only browsers allowed from my organisation)
from different environments results every time in an error.
While trying to upload the file I receive the following error message
in a popup message (red colour) at the bottom right side of the screen:
##
ERROR
An error has occured uploading file (Code: 413 - )
##
Starting a test is not possible.

The file sizes are approx. 4-6 MB. Extensions .gml and .zip (zipped) give the same result (see uploaded file PS__DE7_0945HLNUG__epsg4258_240514_0910.zip).
The files are either newly generated/transformed files or files already validated with an earlier ETF version of 

There might be an issue with the availability, according to the hostory of issues

A similar message on 6 Mar 2024
https://github.com/INSPIRE-MIF/helpdesk-validator/issues/1037
said
"The INSPIRE Reference Validator has had intermittent downtime during today."

Older but slightly different messages (413 - too large) from 22 Dec 2021
https://github.com/INSPIRE-MIF/helpdesk-validator/issues/681
said
"It seems to be related to a global downtime on AWS."

Older but slightly different message (413 - too large) from 22 Sep 2021
https://github.com/INSPIRE-MIF/helpdesk-validator/issues/614

**Comment by fabiovinci** [comment]
Dear @ftporthlnug,

it seems there is an error when uploading files larger than 1 MB, even if they do not exceed the limit.

I validated a subset of your dataset, which only consists of one feature type with a GML file size of 367 KB, and it passed validation (see report: https://inspire.ec.europa.eu/validator/test-run/index.html?id=EIDf3b0aa0b-af35-45b8-ad3e-7de2e9a2cae1).

We will investigate the issue.

**Comment by DanielMartinPerezdeLeon** [comment]
Dear @ftporthlnug,

We have increased the maximum file size for uploads to the VALIDATOR back to the usual 50 MB. We tested the functionality with a 1 MB file, and it worked successfully. You should now be able to use your GML file without any issues.

If you encounter any other problems or have further questions, please don't hesitate to contact us.

Regards,

**Comment by fabiovinci** [comment]
Dear @ftporthlnug,

the validator is now able to load and validate your gml file, see the related test report https://inspire.ec.europa.eu/validator/test-run/index.html?id=EID11618e1a-e4fb-4520-bcc9-695dbf5a29ef

I will close the issue, please reopen it or open a new issue if the error persists.
