### ISSUE TITLE
When testing a WFS at "Direct WFS" option, appears an ERROR message

### ISSUE THREAD

**Issue by Vandapico** [INSPIRE-MIF/helpdesk-validator#1083]
Recently, when we try to star a test in our WFS Service, choosing the option "Direct WFS" in "Select the WFS type" appears an ERROR message,
![image](https://github.com/INSPIRE-MIF/helpdesk-validator/assets/160233194/0e21ce4f-0072-4eb3-9d12-85906539ef6b)

Here are some of the addresses we tried to test:
- https://wssig3.azores.gov.pt/geoserver/ps/wfs?service=wfs&version=1.0.0&request=GetCapabilities
- https://wssig3.azores.gov.pt/geoserver/ef/wfs?service=wfs&version=2.0.0&request=GetCapabilities

Can you explain what's happening?

Thank you.

**Comment by fabiovinci** [comment]
Dear @Vandapico,

thank you fro reporting the issue, we will have a look asap.

**Comment by DanielMartinPerezdeLeon** [comment]
Dear @Vandapico,

We apologize for the inconvenience you experienced while testing the WFS. The TEAMEngine driver for the VALIDATOR was temporarily down during that time. However, we have redeployed the TEAMEngine and tested the links you shared, and you should now be able to test the WFS again.

If you encounter any further issues or have additional questions, please don’t hesitate to reach out to us

Regards,

**Comment by Vandapico** [comment]
We still have the same problem testing the WFS. We've tested on different computers and browsers and we see the same error.

**Comment by DanielMartinPerezdeLeon** [comment]
Dear @Vandapico,

It appears that we are experiencing some difficulties reconnecting to the TEAMEngine, preventing the corresponding ETS to be loaded (WFS Direct, WFS 2.0 and OGC API-Features). 

We are actively working on analyzing and identifying the issue.
We will keep you posted.

Thank you for contacting us.

Regards,

**Comment by fabiovinci** [comment]
Dear @Vandapico,

the validator is now able to load your services.

I will close the issue, please reopen it or open a new issue if the error persists.
