### ISSUE TITLE
INSPIRE validator doesn`t recognize ATOM Digital certificate- SPAIN

### ISSUE THREAD

**Issue by pablobarreira** [INSPIRE-MIF/helpdesk-validator#1084]
Dear All,

I am Pablo Barreira from the Spanish Agricultural Guarantee Fund (FEGA) that belongs to Agricultural Ministry. We are INSPIRE data providers. First of all, I don't know if this issue should be NEW or I should have reopened this one (https://github.com/INSPIRE-MIF/helpdesk-validator/issues/1008). 

We have again the same problem when trying to validate our ATOM Download Service (ATOM URL: [https://www.fega.gob.es/atom/es.fega.sigpac.xml](https://www.fega.gob.es/atom/es.fega.sigpac.xml))

When we click to START TEST, in order to start the validation of the service and get the report, we get this:

![image](https://github.com/INSPIRE-MIF/helpdesk-validator/assets/151014127/71253a8b-05c8-4363-99f3-ee84f3b007da)

As you see, the validation could not be made, since there is a previous problem. This problem is related with our certificate, or the way you treat it as trustworthy or not. This is what we get in the web browser console:

![image](https://github.com/INSPIRE-MIF/helpdesk-validator/assets/151014127/65b7d04a-30bc-4be5-801d-98a9dbe07063)

Here is our certificate:

![image](https://github.com/INSPIRE-MIF/helpdesk-validator/assets/151014127/4a11e2ca-e096-466a-8995-86dc602ec1d9)

If you see (https://github.com/INSPIRE-MIF/helpdesk-validator/issues/1008), the certificate providaded has been renewed (the previous expired in 1st of May 2024). We don't know if you don't accept the certificate because it has been renewed or if you had to add it again as trustworthy. 

We also would like to ask if you could permanent add it to your repository or KeyStore in JAVA (not sure if this applies to it). I have contacted with my IT department, and they told us that, you might include the intermediate certification authority as trustworthy.

Thank you in advance for your help.

**Comment by DanielMartinPerezdeLeon** [comment]
Dear @pablobarreira,

We have updated the FEGA certificate on the  [VALIDATOR](https://inspire.ec.europa.eu/validator/home/index.html) . After testing it with the ATOM you shared, I’m pleased to inform you that you should now be able to test FEGA resources again without any issues.

If you encounter any further challenges or have additional questions, feel free to reach out.

Regards,

**Comment by pablobarreira** [comment]
Thank you, seems now it's working correctly.

Could you please confirm us, that, when the certificate expires next year, we would not have the same issue? I mean, do you now accept the certificate permantly?

Thank you for you help!

**Comment by jenriquesoriano** [comment]
Dear @pablobarrero,

thank you for your contribution and suggestion for improvement.

Typically, once a certificate is registered in the INSPIRE Reference Validator, it does not need to be periodically replaced, as the certificate is renewed over time before it expires, without needing to be substituted with another certificate.
However, your suggestion is valuable, as we understand that it could be useful for the community in cases similar to yours that could arise in the future, where the certificate expires and is replaced rather than renewed.

We are therefore exploring how to incorporate this feature automatically and hope to include it in futrue releases of the INSPIRE Reference Validator.

We will provide updates on the progress through the helpdesk.

Best regards,

**Comment by DanielMartinPerezdeLeon** [comment]
Dear @pablobarreira ,

We wanted to inform you that the new release [v2024.2](https://github.com/INSPIRE-MIF/helpdesk-validator/releases/tag/v2024.2) now automatically imports the FEGA certificate from its server. This update ensures that the issue you experienced should not recur when your certificate expires in the future.

If you have any further questions or encounter any other issues, please don't hesitate to reach out to us.

Best regards,
