### ISSUE TITLE
Problem when validating ATOM download service via INSPIRE VALIDATOR

### ISSUE THREAD

**Issue by pablobarreira** [INSPIRE-MIF/helpdesk-validator#1085]
Hello,

This is Pablo Barreira from Spanish Agricultural Guarantee Fund (Ministry of Agriculture).  First of all thank you for solving the problem with our certificate.[https://github.com/INSPIRE-MIF/helpdesk-validator/issues/1084](https://github.com/INSPIRE-MIF/helpdesk-validator/issues/1084 ). 

Related with this, we finally perfomed the validation of our ATOM download service ([https://www.fega.gob.es/atom/es.fega.sigpac.xml](https://www.fega.gob.es/atom/es.fega.sigpac.xml) this morning. Among the three main failing issues (two of them we can solve them by ourselves), there is one which we want to ask you about. Here is the complete report ([https://inspire.ec.europa.eu/validator/test-run/details.html?id=EIDdedc6cc8-809f-465b-a5e1-560602149228](https://inspire.ec.europa.eu/validator/test-run/details.html?id=EIDdedc6cc8-809f-465b-a5e1-560602149228)). And we want to ask you specifically about this one:
![image](https://github.com/INSPIRE-MIF/helpdesk-validator/assets/151014127/1a8b8035-eed2-4e94-9bf4-85c43e943c03)

We think this error might be due to an error in the validator when it verifies requirement 42:
TG Requirement 42: The OpenSearch description shall contain a 'Url' element that describes a template URL for the Describe Spatial Data Set operation. This template shall accept the INSPIRE parameters 'spatial_dataset_identifier_code', 'spatial_dataset_identifier_namespace' and the OpenSearch 'language' parameter. The 'Url' element shall have an attribute 'type' with a value of 'application/atom+xml' or 'application/xml' or 'text/xml' and an attribute 'rel' with the value 'describedby'.

The cited element is whithin https://www.fega.gob.es/atom/osd.xml, that adresses the requirement is this one:

![image](https://github.com/INSPIRE-MIF/helpdesk-validator/assets/151014127/7b89fa21-5e57-4d04-b8b1-94e3fead80db)

Could you please help us to solve this issue? Thank you in advance for your help.

**Comment by pablobarreira** [comment]
Dear all, have you any kind of answer for the question above?
Thank you in advance for your help.

**Comment by fabiovinci** [comment]
Dear @pablobarreira,

I confirm that your service is fine and should not result in an error for Requirement 42.
We are working to resolve the issue and will notify you when the solution is available for testing in the staging environment.

**Comment by fabiovinci** [comment]
Dear @pablobarreira,

the fix for this issue is available in the staging instance.

I tested your service and it is 100% valid (see report https://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/test-run/index.html?id=EID9e91e340-7c92-445a-8d4f-cbddcc0b52da).

Could you please conduct additional tests and confirm? Thanks

**Comment by pablobarreira** [comment]
Dear @fabiovinci .

I have performed the test right now in the staging environment and i get the same as you got. It is now solved!
Thank you so much for your help.

Would you mind to tell us when will this fix pass from the staging environment to the reference validator?

Thank you!

**Comment by fabiovinci** [comment]
Dear @pablobarreira,

thank you for confirmation, this fix will be available in the production instance in the coming days.
