### ISSUE TITLE
Several CVEs in the 2024.1 Docker version

### ISSUE THREAD

**Issue by larsnaesbye** [INSPIRE-MIF/helpdesk-validator#1088]
A quick scan shows a lot of vulnerabilities in dependencies in the latest version, that I think should be addressed in the next release.

In particular the Spring libraries and jackson-databind has some high severity CVEs.

**Comment by MarcoMinghini** [comment]
Dear @larsnaesbye, 
please have a look at the [Readme file](https://github.com/INSPIRE-MIF/helpdesk-validator/blob/master/README.md) of this repository to see how to correctly make the report. We are going to remove your message.
