### ISSUE TITLE
ETF API production instance not available anymore on http://inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/v2/status

### ISSUE THREAD

**Issue by klimeto** [INSPIRE-MIF/helpdesk-validator#109]
Dear INSPIRE reference validator API providers,

I tried to access the ETF API on the standard address and got HTTP 404 Not Found error:

```bash
root@vmi141395:/usr/local/src/rpi2-api/api# curl "http://inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/v2/status"
<html>
<head>
<meta http-equiv="Content-Type" content="text/html;charset=ISO-8859-1"/>
<title>Error 404 </title>
</head>
<body>
<h2>HTTP ERROR: 404</h2>
<p>Problem accessing /etf-webapp/v2/status. Reason:
<pre>    Not Found</pre></p>
<hr /><a href="http://eclipse.org/jetty">Powered by Jetty:// 9.3.6.v20151106</a><hr/>
</body>
</html>
```
Has the URL changed?

Many thanks,
Tomas

**Comment by MarcoMinghini** [comment]
Dear @klimeto, the correct URL is `http://inspire-validator.eu-west-1.elasticbeanstalk.com/validator/v2/status`

**Comment by klimeto** [comment]
Thanks @MarcoMinghini 

Have you changed the URL recently? I have been using the old URL till couple of days ago. 

As you can see also in this issue: #104 

Thanks a lot

**Comment by carlospzurita** [comment]
Dear @klimeto 
The internal URL of the validator was changed a couple days ago, during the maintenance period to restore the service after the report in #104 

From now on, it would be advisable to use the official host and context `http://inspire.ec.europa.eu/validator/`, as this will remain unchanged and redirect to the AWS generated URL.

Cheers.

**Comment by klimeto** [comment]
Thanks a lot @carlospzurita 

Will the staging instance URL remained unchanged? 

```
http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/v2/status
```
