### ISSUE TITLE
beginLifeSpanVersion not recognized in Road Transport Networks dataset (Transport Networks)

### ISSUE THREAD

**Issue by irg222** [INSPIRE-MIF/helpdesk-validator#1091]
Hi,

I have been working on the Transport Networks theme. Specifically in the Roads dataset, the field beginLifeSpanVersion is not recognised.

This is the validation report: [(https://inspire.ec.europa.eu/validator/test-run/index.html?id=EID450d3fb7-29b5-43e3-bc44-09929c83ecbc)]

And this is the gml file that has been validated:
[carretera_cyl_puntok_v1.0002.gml.zip](https://github.com/user-attachments/files/15970793/carretera_cyl_puntok_v1.0002.gml.zip)

I have worked in the same way with the field beginLifeSpanVersion in the data set of Air Transport and I didn't have any problems.

Am I missing Something? How can I fix it?

Kind regards,

Irati

**Comment by fabiovinci** [comment]
Dear @irg222,

just so you know, if you are using version 5 of the schema, make sure to update the related namespaces.
In particular, the following two namespaces need to be updated to the new versions:

```xml
  xmlns:net="http://inspire.ec.europa.eu/schemas/net/5.0"
  xmlns:base="http://inspire.ec.europa.eu/schemas/base/4.0"
```

These changes will solve the issue, see the related report: https://inspire.ec.europa.eu/validator/test-run/index.html?id=EID5aba30b6-759b-4155-9698-40eb647ae185

**Comment by fabiovinci** [comment]
Dear user,

we hope the solution provided helps you resolve the issue.
So we close this issue.
If there are any further questions or problems, please do not hesitate to reopen it or create a new issue.
