### ISSUE TITLE
Error namespelling - Tema Area management zones/restrictions/regulations and reporting units

### ISSUE THREAD

**Issue by CristinaMSL** [INSPIRE-MIF/helpdesk-validator#1092]
Hello, good afternoon.

I am validating a gml of the topic Area management zones/restrictions/regulations and reporting units.
After validating the gml, the following error has come up.
I am following the same steps as in previous tables, which have been validated without any problem.

![image](https://github.com/INSPIRE-MIF/helpdesk-validator/assets/160479583/b8367946-6479-4594-b6b6-aa90bbced468)

What could be happening?
[gml+testreport.zip](https://github.com/user-attachments/files/16053272/gml%2Btestreport.zip)

Below I leave attached the gml and the test report.

I am waiting for your response.

Thank you very much in advance.

**Comment by fabiovinci** [comment]
Dear @CristinaMSL,

regarding the specific error you reported, please note that the "`spelling`" element is not encoded correctly.
See the screenshot below for details:

![image](https://github.com/INSPIRE-MIF/helpdesk-validator/assets/22212406/ee8aeecb-6757-45aa-9f5e-fca3a4ed84bb)

In addition, upon reviewing the GML file, it appears that the encoding is incorrect as it only contains a `<am:ManagementRestrictionOrRegulationZone>` featureMember with numerous occurrences of a specific element (e.g. I counted 191 occurrences of the `am:thematicId` element).

I would recommend reviewing the method you use to generate the GML file.

**Comment by fabiovinci** [comment]
Dear user,

we hope the solution provided helps you resolve the issue.
So we close this issue.
If there are any further questions or problems, please do not hesitate to reopen it or create a new issue.
