### ISSUE TITLE
INSPIRE Validator not working

### ISSUE THREAD

**Issue by Ana-SGA** [INSPIRE-MIF/helpdesk-validator#1095]
Dear all,

it seems that INSPIRE Validator (including staging instance) is not working. I can open the page, but the part for verification never opens (picture attached) on both instances. Can someone please take a look?

Kind regards
![Capture](https://github.com/INSPIRE-MIF/helpdesk-validator/assets/77394573/17da0c61-a5e7-41e1-a861-11620ccc852d)

**Comment by MarcoMinghini** [comment]
Dear @Ana-SGA, as announced in https://github.com/INSPIRE-MIF/helpdesk-validator/issues/1096 there is an issue with the captcha service, which does not depend on our team as it's a central service. We are currently trying to get additional information and will provide updates in the other issue, so I will proceed to close this one.
