### ISSUE TITLE
at06-getcapabilities-view-service-metadata: Expected Content-Type header

### ISSUE THREAD

**Issue by Kate-Lyndegaard** [INSPIRE-MIF/helpdesk-validator#1099]
Hi,

I am testing the updated ATS/ETS for View Services on staging, using the following WMS:

https://test.haleconnect.de/ows/services/org.762.dd99d221-b7d1-4caa-aed4-7d45b09b1731_wms?SERVICE=WMS&REQUEST=GetCapabilities&VERSION=1.3.0

I receive the following error on at06-getcapabilities-view-service-metadata:

**Error**

Expected 'application/xml;charset=UTF-8' as Content-Type header but server returned 'application/xml' for url https://test.haleconnect.de/services/bsp/org.762.dd99d221-b7d1-4caa-aed4-7d45b09b1731/md/service/id_wms

Is there a requirement that specifies this header to be used as a fixed value?
The XML response uses an XML mechanism to communicate the charset used: `<?xml version="1.0" encoding="UTF-8"?>`

**Comment by fabiovinci** [comment]
Dear @Kate-Lyndegaard,

thank you for reporting the error.
Since you are in Scenario 1, the validator checks that the URL of the service metadata is working.
There are no specific requirements on the Content-Type header.
We will check the error.

**Comment by Kate-Lyndegaard** [comment]
Dear @fabiovinci 

Great, thank you very much:-)

**Comment by fabiovinci** [comment]
Dear @Kate-Lyndegaard,

the fix for this issue is already available in staging. It will be included in the next release.

**Comment by Kate-Lyndegaard** [comment]
Dear @fabiovinci 

Wow, that was fast! Our service is no longer failing the test- amazing. Thank you very much:-)
