### ISSUE TITLE
Validating services published from port 8080 does not work

### ISSUE THREAD

**Issue by klimeto** [INSPIRE-MIF/helpdesk-validator#11]
We are trying to validate the follwing ATOM services:

http://sluzby.vuvh.sk:8080/arcgis/server/arcgisoutput/INSPIRE_dls/RiverBasinDistricts/RBD_dlsFeed.xml

When we launch the test suite Conformance Class: Download Service - Pre-defined Atom the following error appears:

Test Run initialization failure
Connection refused (Connection refused)

Thank you for help.

**Comment by klimeto** [comment]
We are trying to validate the follwing ATOM services:

http://sluzby.vuvh.sk:8080/arcgis/server/arcgisoutput/INSPIRE_dls/RiverBasinDistricts/RBD_dlsFeed.xml

When we launch the test suite Conformance Class: Download Service - Pre-defined Atom the following error appears:

Test Run initialization failure
Connection refused (Connection refused)

Thank you for help.

**Comment by df-git** [comment]
Dear klimeto.
We have checked our system configuration. Con you please try now?

**Comment by josemasensio** [comment]
Dear @klimeto,

We are looking back and trying to solve and close old issues. Was the problem get fixed? 

Best regards.
