### ISSUE TITLE
Test Discovery Services on the INSPIRE Validator - Cy Error

### ISSUE THREAD

**Issue by dynamike76** [INSPIRE-MIF/helpdesk-validator#110]
We have used the staging instance of the Validator in order to test our INSPIRE national Discovery Services. Unfortunately we got the an error message, shown in the figures that follow 
![error 1](https://user-images.githubusercontent.com/19546395/64416080-30e1e980-d09f-11e9-8854-c543838cf533.jpg)

![error 2](https://user-images.githubusercontent.com/19546395/64416154-5a9b1080-d09f-11e9-936b-6e92a60b58d8.jpg)

Please note that the INSPIRE services are currently not accessible due to enhanced security which was decided to be applied by the Department of Lands and Surveys (DLS).
This is supposed to be a temporal measure. 

We have a question if the error message received is related to the measure taken by DLS?

**Comment by dynamike76** [comment]
The CSW is: 
http://eservices.dls.moi.gov.cy/geoportal_inspire/csw?Request=GetCapabilities&Service=CSW&Version=2.0.2

**Comment by josemasensio** [comment]
Dear @dynamike76, 

Thank you for your message. We will check why this is happening. 

Best regards.

**Comment by josemasensio** [comment]
Dear @dynamike76,

We have noticed that is a redirection issue. If you use `https` instead `http` the test will run.

Best regards.

**Comment by josemasensio** [comment]
Dear @dynamike76,

Does this solution work?

Best regards.

**Comment by dynamike76** [comment]
Dear Mr Asensio, hello.
Yes it did work.
My colleague will  forward  the results to Robert and Marco.
Regards
Mike
________________________________

**Comment by josemasensio** [comment]
Dear @dynamike76,

Glad to hear this, we will mark the issue as solved. 

Greetings

**Comment by MarcoMinghini** [comment]
@dynamike76 thanks for your feedback. We will mark the issue as solved, but please have a look at the errors raised by the Validator when validating the Discovery Service.
