### ISSUE TITLE
INSPIRE validator server error

### ISSUE THREAD

**Issue by tomicekj** [INSPIRE-MIF/helpdesk-validator#1108]
Dear INSPIRE validator dev team,

we use the INSPIRE validator (https://sdi.eea.europa.eu/validator/) in the EEA CLMS OSS QC TOOL (https://github.com/eea/copernicus_quality_tools) to validate the metadata of deliveries that are submitted to the EEA. We have recently encountered a possible service malfunction with an error message attached as a text file. We also provide the .xml file we used for this test. The test suite used is INSPIRE data sets and data set series interoperability metadata.

[server_error_plus_test_metadata_file.zip](https://github.com/user-attachments/files/16801505/server_error_plus_test_metadata_file.zip)

Kind regards,
Jiri Tomicek (Gisat, Ltd.)

**Comment by fabiovinci** [comment]
Dear @tomicekj,

It is not clear which version of the validator you are using, and retrieving error information from the txt test report is not simple.

In any case, your metadata is valid using the [INSPIRE Reference Validator](https://inspire.ec.europa.eu/validator/home/index.html) (see the related test report: https://inspire.ec.europa.eu/validator/test-run/details.html?id=EIDa0b62471-e64e-4b0a-9f87-bf665642f7a4).

Using the latest version of the validator is crucial to avoid resolved errors.

**Comment by fabiovinci** [comment]
Dear user,
we hope the solution provided helps you resolve the issue.
So we close this issue.
If there are any further questions or problems, please do not hesitate to reopen it or create a new issue.
