### ISSUE TITLE
Metadata error when validating service metadata - Coupled Resource

### ISSUE THREAD

**Issue by Ana-SGA** [INSPIRE-MIF/helpdesk-validator#1109]
Dear all,

can someone please take a look on this Validator Report https://inspire.ec.europa.eu/validator/test-run/details.html?id=EID5cb6dfbd-7100-4080-8293-83d9eff2769f? It is a report for validation of service metadata - we get an error for Coupled Resource, but we don't see why. This is the link to metadata https://geoportal.nipp.hr/geonetwork/srv/hrv/catalog.search?returnTo=catalog.edit#/metadata/83608abf-59af-496c-816b-e291f8019df4.

Thank you.

**Comment by antjacques** [comment]
Hi Ana,

You forgot to publish your metadata record:
![image](https://github.com/user-attachments/assets/8e742a0f-72ad-4012-b0de-e5498430b631)

**Comment by Ana-SGA** [comment]
Dear @antjacques ,

Gosh!! Thank you :D
