### ISSUE TITLE
Issues with INSPIRE Validator v4.0.0 and Monitoring Bulk Action Results Showing Zeros

### ISSUE THREAD

**Issue by arneladoc** [INSPIRE-MIF/helpdesk-validator#1110]
Hi INSPIRE Support Team,

We're in the process of setting up INSPIRE Validator v4.0.0 on our system and ran into some issues when trying to use the Monitoring Bulk Action feature. We're hoping you can help us figure out what's going wrong.

**What's happening:**
When we try to validate multiple GML files in bulk using the Monitoring Bulk Action, the results we're getting are a bit puzzling. Specifically, the counts for datasets, services, and series are all showing as zeros, even though we're sure the GML files are correctly formatted and should be recognized.
Here's a quick summary of what we're seeing in the results:
datasets = 0
series = 0
services = 0
unknown = 0
missing = 1 (this one does show up, but it's the only thing that isn't zero).
So, it seems like most of the categories aren’t being processed properly, or the validator isn't recognizing the files, aside from this one “missing” entry.
Details you might need:
INSPIRE Validator Version : 4.0.0
Monitoring Bulk Action Configuration :
validator_url: http://localhost:8080/validator/v2/
Number of files tested : [e.g., 5 GML files]
Results : Same zeros in several categories, except for missing .
File format : All .gml files.

**Errors we noticed:**

- Earlier, we had some trouble with the UUID identifier , where we saw errors like, "Illegal identifier length." That seems to be resolved now, but it's worth mentioning in case it's related.

- Now, the biggest issue is that we're getting zero counts for most of the categories, and we’re stuck on how to fix it.

**What we'd love help with:**

- Is the Monitoring Bulk Action feature fully compatible with INSPIRE Validator v4.0.0 ? Could there be any bugs with the latest version?

- What could be causing these zero counts across datasets, services, and other types?

- Are there any specific settings or configurations we should adjust, or any patches on the way that might fix this?

We’d appreciate any troubleshooting tips or steps to make sure Bulk Action is working correctly with this version.
Thanks in advance for your time and help!

**Comment by arneladoc** [comment]
Correction for the version we used v.2024.2

**Comment by fabiovinci** [comment]
Dear @arneladoc,

the Bulk Monitoring Validation Tool was created to verify XML metadata files.

Are you using it to validate datasets (in GML format as you mentioned)?

**Comment by arneladoc** [comment]
Dear @fabiovinci, 

We tried GML, but saw it didn't work, we also tried XML, but we get the same records, 0

**Comment by fabiovinci** [comment]
Dear @arneladoc,

could you please send us a sample metadata XML file you are attempting to validate?

**Comment by arneladoc** [comment]
@fabiovinci We are currently using GML files for our processes, which we are confident are correct. However, we're not entirely sure about the XML files we have, and we want to ensure they meet the required standards.

We primarily use GML exported from Hale Studio and FME, and these are working well for us. To improve our XML processes, could you kindly provide us with a sample of a valid XML file that meets INSPIRE standards?

**Comment by fabiovinci** [comment]
From your response, it seems you are trying to validate **datasets**!

Please keep in mind that the Bulk Monitoring Validation Tool was designed to validate **metadata**.

**Comment by arneladoc** [comment]
@fabiovinci How to create metadata from GML?

**Comment by fabiovinci** [comment]
It is not possible to automatically do this since they are different types of resources.

To create metadata for your dataset, please refer to the [Metadata Technical Guidance](https://github.com/INSPIRE-MIF/technical-guidelines/blob/main/metadata/metadata-iso19139/metadata-iso19139.adoc).

You can find an example metadata for datasets [here](https://github.com/INSPIRE-MIF/helpdesk-validator/blob/master/examples/Dataset_metadata_2.0_example.xml).

I hope this helps to clarify!

**Comment by arneladoc** [comment]
@fabiovinci Thank you very much for the answers. We got the information we needed. If we need anything else, we will be free to write

**Comment by arneladoc** [comment]
Dear, @fabiovinci 
We have initiated the Bulk Action tests and we're no longer receiving zero values. However, we are getting results in a JSON file but are unable to configure the CSV. Could you please review our XML to ensure everything is set up correctly?
[monitoring-bulk-validation-tool-master.zip](https://github.com/user-attachments/files/17027169/monitoring-bulk-validation-tool-master.zip)
[test.zip](https://github.com/user-attachments/files/17027171/test.zip)
