### ISSUE TITLE
HTTP Error 400 when uploading GML from local drive

### ISSUE THREAD

**Issue by joey-geoloog** [INSPIRE-MIF/helpdesk-validator#1119]
Similar issues: #1037, #983, #744

When uploading a GML file to [the validator](https://inspire.ec.europa.eu/validator/test-selection/index.html), attempting to run Annex III: EF tests, we receive HTTP error 400 before the test even starts. We've tried both with self generated files and further with GML files from other sources.

System details:
Windows 10, 11
Microsoft Edge for Business 129.0.2792.65 (Official build) (64-bit)
Both on and off corporate network
I've tried loading from a network location and a local drive and it still doesn't work, experience is for multiple colleagues on various pc's and connections.

![Screenshot 2024-10-01 144120](https://github.com/user-attachments/assets/64ff7b06-c26b-48cb-a70a-28bf5dded465)

file to be tested contains just the following content saved as *.gml:

```gml
<?xml version="1.0" encoding="UTF-8"?>
<ef:EnvironmentalMonitoringNetwork xmlns:ef="http://inspire.ec.europa.eu/schemas/ef/4.0" xmlns:gml="http://www.opengis.net/gml/3.2" xmlns:base="http://inspire.ec.europa.eu/schemas/base/3.3" xmlns:base2="http://inspire.ec.europa.eu/schemas/base2/2.0" xmlns:xlink="http://www.w3.org/1999/xlink" gml:id="GUF000000000101">
  <ef:inspireId>
    <base:Identifier>
      <base:localId>GUF000000000101</base:localId>
      <base:namespace>nl-imbro-ef-guf</base:namespace>
    </base:Identifier>
  </ef:inspireId>
  <ef:mediaMonitored xlink:href="http://inspire.ec.europa.eu/codelist/MediaValue/water"/>
  <ef:organisationLevel xlink:href="https://inspire.ec.europa.eu/codelist/LegislationLevelValue/sub-national"/>
  <ef:legalBackground>
    <base2:LegislationCitation>
      <base2:identificationNumber>identificatie beschikking-melding_IBM_01</base2:identificationNumber>
      <base2:dateEnteredIntoForce>2016-01-01</base2:dateEnteredIntoForce>
      <base2:level xlink:href="https://inspire.ec.europa.eu/codelist/LegislationLevelValue/sub-national"/>
    </base2:LegislationCitation>
  </ef:legalBackground>
  <ef:purpose>openbareDrinkwatervoorziening</ef:purpose>
  <ef:contains/>
</ef:EnvironmentalMonitoringNetwork>
```

The issues linked above vary from internal errors to proper declarations, we are currently validating with FME against the XSD but want to be able to do this using the INSPIRE validator. We are also trying to deploy a local installation but this will take some time.

Really appreciate your help here!

Joey

**Comment by joey-geoloog** [comment]
Just to let you know, when making an issue on the repo I received the below message per email

https://github.com/INSPIRE-MIF/helpdesk-validator/actions/runs/11126011692

![image](https://github.com/user-attachments/assets/5ad75bee-5d7b-48ef-8565-549d382e3328)

**Comment by fabiovinci** [comment]
Dear @joey-geoloog,

the Validator cannot recognize the document type as the gml should have the gml:FeatureCollection or wfs:FeatureCollection element as the root.
Make sure to apply the necessary corrections to your GML files.

Thanks for notifying the issue related to the action, we will check it.

**Comment by joey-geoloog** [comment]
@fabiovinci thank you very much! and great that you'll take the automation problem further. many thanks for your help.
