### ISSUE TITLE
Error with Conformity string comparison

### ISSUE THREAD

**Issue by kkoistinen** [INSPIRE-MIF/helpdesk-validator#112]
I validated service http://www.paikkatietohakemisto.fi/geonetwork/srv/en/csw?service=CSW&request=GetCapabilities in staging environment and got following error message:

Schema not valid: [org.xml.sax.SAXException: Fatal error: org.xml.sax.SAXParseException; lineNumber: 274; columnNumber: 91; cvc-enumeration-valid: Value 'COMMISSION REGULATION (EU) No 1089/2010 of 23 November 2010
implementing Directive 2007/2/EC of the European Parliament and of the Council as
regards interoperability of spatial data sets and services' is not facet-valid with respect to enumeration '[COMMISSION REGULATION (EU) No 1089/2010 of 23 November 2010 implementing Directive 2007/2/EC of the European Parliament and of the Council as regards interoperability of spatial data sets and services]'. It must be a value from the enumeration. Response did not validate against schema 'http://www.opengis.net/cat/csw/2.0.2 http://schemas.opengis.net/csw/2.0.2/CSW-discovery.xsd http://inspire.ec.europa.eu/schemas/inspire_ds/1.0 http://inspire.ec.europa.eu/schemas/inspire_ds/1.0/inspire_ds.xsd'.]

Valid and invalid strings look similar. There must be some extra space or new line character that causes this error. Could the validator be less strict in string validation or should I try to fix this somehow in our Geonetwork?

Best regards,
Kai Koistinen
National Land Survey of Finland

**Comment by josemasensio** [comment]
Dear @kkoistinen,
Thank you for your message. Please, could you tell us which test are you running? 

Best regards.

**Comment by kkoistinen** [comment]
Discovery Service - CSW Core

**Comment by josemasensio** [comment]
Dear @kkoistinen,

The error you are getting is from the schema validation http://inspire.ec.europa.eu/schemas/inspire_ds/1.0/inspire_ds.xsd. Inside this schema there are some enumerations (http://inspire.ec.europa.eu/schemas/common/1.0/enums/enum_eng.xsd), one of them with the value "COMMISSION REGULATION (EU) No 1089/2010 of 23 November 2010 implementing Directive 2007/2/EC of the European Parliament and of the Council as regards interoperability of spatial data sets and services", and we cannot relax the validation without changing the schema. To avoid this error you should have the value as itself.

Best regards.

**Comment by josemasensio** [comment]
Dear @kkoistinen,
Does this solution work?

Best regards.
