### ISSUE TITLE
Codelists validation errors

### ISSUE THREAD

**Issue by mwjsanders** [INSPIRE-MIF/helpdesk-validator#1123]
Since yesterday the Predefined ATOM tests fail in the test step 'Use INSPIRE media-types only'

The request executed by the test to the url https://inspire.ec.europa.eu/media-types/media-types.es.atom returns a http status code 406 and a body:
```
{
  "error" : {
    "code" : 406,
    "description" : "The requested media type is not supported",
    "description-code" : "unknown-format"
  }
}
```
Although a valid response with status code 200 is expected

example test report with this error: https://inspire.ec.europa.eu/validator/test-run/index.html?id=EIDe7d5333a-7b5b-4852-bcb1-206ab2a1ba2d

**Comment by juanluisrp** [comment]
We are suffering this in our local instance too.

**Comment by fabiovinci** [comment]
Dear all,

thank you for reporting the error.
It appears that there is a problem with the .atom format of the codelists.
We will take a look as soon as possible.

**Comment by fabiovinci** [comment]
Dear all,

the Registry issue has been resolved, and the .atom format of the codelists is once again available.

I will close the issue, please reopen it if the error persists.

**Comment by mwjsanders** [comment]
@fabiovinci 

This issue was solved last week, but now the error is back again

**Comment by fabiovinci** [comment]
Dear @mwjsanders,
thank you for bringing this to our attention.
We will have a look asap.

**Comment by fabiovinci** [comment]
Dear all,

we have verified that after applying the security patches and restarting the Registry server, the rules needed to download ATOM, CSV and ROR files were not applied.
The issue has been fixed and should not occur again.
