### ISSUE TITLE
Problem with validating metadata Conformance Class 1, 1.4: INSPIRE Theme Keyword

### ISSUE THREAD

**Issue by MariuszGasior04** [INSPIRE-MIF/helpdesk-validator#1126]
**- a description of the steps to reproduce your issue**
Validation of Metadata, Data sets and data set series,
Common Requirements for ISO/TC 19139:2007 based INSPIRE metadata records 
Conformance Class 1: 'Baseline metadata for data sets and data set series 
Conformance Class 2: 'INSPIRE data sets and data set series interoperability metadata' 

 'md datasets-and-series 1.4: INSPIRE Theme Keyword'
Test of metadata Conformance Class 1 doesn't pass. It seams like validator doesn't check all languages (officialLanguages) of GEMET - INSPIRE themes, version 1.0 with given keywords. 

**- the browser and version used**
Google Chrome 129.0.6668.101
Edge 129.0.2792.89 
**- a screenshot illustrating the problem**
![image](https://github.com/user-attachments/assets/cc0c8deb-1b62-4a02-8944-0391ec2141a0)
![image](https://github.com/user-attachments/assets/00b230c7-f9d5-475c-a440-d7a387350741)

**- the Test Report (ideally as an attachment to the issue)**
https://yzyiqfakm4.execute-api.eu-west-1.amazonaws.com/validator/v2/TestRuns/EID1face684-49b6-4f9c-b890-f7d207e278bb.html?lang=pl
**- the name of the Test that failed or better: change the `Level of Detail`
in the Report by clicking on `All Details`, then scroll down to the failed test
and copy the Link on the right-hand side of the `Assertion URI`**
https://yzyiqfakm4.execute-api.eu-west-1.amazonaws.com/validator/v2/TestRuns/EID1face684-49b6-4f9c-b890-f7d207e278bb.html?lang=pl#EID9b606d3a-b772-4580-9706-5dd92bc931f7
- the URL of your service / the file you have uploaded or referenced (as
an attachment).
[WORP_3_cykl.txt](https://github.com/user-attachments/files/17435341/WORP_3_cykl.txt)

**Comment by fabiovinci** [comment]
Dear @MariuszGasior04,

the error was due to the temporary unavailability of the `.atom` format of the codelists.
The issue in the Registry has been resolved.
I will close the issue, please reopen it if the error persists.
