### ISSUE TITLE
Web validator - error at session spin up with crs definitions results in failures in tests

### ISSUE THREAD

**Issue by joey-geoloog** [INSPIRE-MIF/helpdesk-validator#1127]
Dear team, Thanks in advance! 

web validator - production

I see the following error multiple times in the logfiles before I even get to see the report, progress is extremely slow.

`23.10.2024 12:36:00 - "[err:XQST0059] Could not instantiate de.interactive_instruments.etf.bsxm.GmlGeoX: org.deegree.cs.exceptions.CRSConfigurationException: com.ctc.wstx.exc.WstxEOFException: Unexpected EOF; was expecting a close tag for element <crs:CRSDefinitions>&#xA; at [r..."`

Links: [Logfile](https://[yzyiqfakm4.execute-api.eu-west-1.amazonaws.com/validator/v2/TestRuns/EIDa59f552c-4ea0-4040-be27-0ade03876b51/log](https://yzyiqfakm4.execute-api.eu-west-1.amazonaws.com/validator/v2/TestRuns/EIDa59f552c-4ea0-4040-be27-0ade03876b51/log)) | [Testobject](https://yzyiqfakm4.execute-api.eu-west-1.amazonaws.com/validator/v2/TestRuns/EIDa59f552c-4ea0-4040-be27-0ade03876b51.xml) | Name: Test run on 14:34 - 23.10.2024 with test suite Annex III - Environmental monitoring Facilities (EF)

This results in an error in the test results despite the geometry being declared properly.

![image](https://github.com/user-attachments/assets/a5d4a263-b573-47c7-8bbe-b6cea28fda08)

Assertion URI: https://yzyiqfakm4.execute-api.eu-west-1.amazonaws.com/validator/v2/TestRuns/EIDa59f552c-4ea0-4040-be27-0ade03876b51.html?lang=en#EIDa12eed3a-ba1b-4345-aa1e-9b908f068006

Logfile plaintext: [EIDa59f552c-4ea0-4040-be27-0ade03876b51.log](https://github.com/user-attachments/files/17491511/EIDa59f552c-4ea0-4040-be27-0ade03876b51.log)

**Comment by fabiovinci** [comment]
Dear @joey-geoloog,

Could you please provide us with a sample dataset so we can reproduce the errors? Thanks

**Comment by joey-geoloog** [comment]
Dear @fabiovinci 
Of course, apologies I thought I had already attached it. Here it is:
[bro_gu_inspire_ef.zip](https://github.com/user-attachments/files/17597971/bro_gu_inspire_ef.zip)

**Comment by joey-geoloog** [comment]
@fabiovinci Interestingly, running the exact same data through the validator today doesn't return the same error. So it appears to be something related to the instance that validator was running on, or the validator has been upgraded/patched in the meantime?

https://inspire.ec.europa.eu/validator/test-run/details.html?id=EID9d072c24-a068-4d8b-8622-a692b687bcc3

**Comment by fabiovinci** [comment]
Dear @joey-geoloog,

I'm glad to hear that you were able to validate it.

The error was likely due to a temporary overload; maintenance work was performed days later (https://github.com/INSPIRE-MIF/helpdesk-validator/issues/1130).

I will close the issue, please reopen it if the error persists.
