### ISSUE TITLE
How can freeNode be reported?

### ISSUE THREAD

**Issue by JohannaOtt** [INSPIRE-MIF/helpdesk-validator#113]
I validated a dataset with Transport Network - Air data.
The test with the ID EIDd6fa7b64-9a2a-490e-aebe-7411a4610407 reports: "verify for each TransportNode that the geometry (a gml:Point) is located at a position that touches a TransportLink.centrelineGeometry (a gml:LineString or gml:Curve), i.e. that the node is at the start or end of a transport link. Otherwise report freeNode."
As the dataset contains AerodromeNode objects and no reference to other Transport Networks, that error/message is comprehensible and fits to the IR Requirement in Annex II, Section 7.9.3
What I am confused about is the part "Otherwise report freeNode". I cannot find any documentation or further information anywhere else on how to mark/identify 'freeNodes' in my data. Do you have any suggestions for that?

**Comment by josemasensio** [comment]
Dear @JohannaOtt,

Please, could you use our [contribution guidelines](https://github.com/inspire-eu-validation/community/blob/master/contribution_guidelines.md) to help us more quickly locate what is causing this issue? 

We will like to have the file you are using, the problem you have and if is possible, a screenshot of the issue. Thanks in advice, this information will be useful for us.

Best regards.

**Comment by JohannaOtt** [comment]
@josemasensio Thank you for getting back to me. Unfortunately, there is not much information on how to start a discussion (which this issue is from my point of view) - if further information is needed, it might make sense to add it to the guidelines. Currently it is: "How to start a discussion
Please, make a short description about the topic you would like to discuss."

The data is confidential, if you give me an email address where I can send it, I will clarify with my customer if I am allowed to send it there.
The problem I have, is that the explanation of the test that fails (ID EIDd6fa7b64-9a2a-490e-aebe-7411a4610407) mentions I should report "freeNodes" to avoid the test failling and I don't see any information in the INSPIRE documents on how to report freeNodes.
I would like to know how I can realize the proposal the validator gives there. How can I mark a Node I am reporting as freeNode? Best case would be, if you even have an example of a GML file containing freeNodes.
Here is a screenshot of the message I am referring to: 
![grafik](https://user-images.githubusercontent.com/34163838/65044312-f577d280-d95c-11e9-8454-c98e8df55d20.png)

**Comment by josemasensio** [comment]
Dear @JohannaOtt 
You can send them to inspire-helpdesk@bilbomatica.com. 

Thank you, we will come back to you when a solution is provided.

**Comment by JohannaOtt** [comment]
Thank you for the quick replies! I sent the data our via email.

**Comment by JohannaOtt** [comment]
The email cannot be delivered with this error message:
We're writing to let you know that the group you tried to contact (inspire-helpdesk) may not exist, or you may not have permission to post messages to the group. A few more details on why you weren't able to post:

 * You might have spelled or formatted the group name incorrectly.
 * The owner of the group may have removed this group.
 * You may need to join the group before receiving permission to post.
 * This group may not be open to posting.

If you have questions related to this or any other Google Group, visit the Help Center at https://support.google.com/a/bilbomatica.es/bin/topic.py?topic=25838.

Thanks,

bilbomatica.es admins

**Comment by josemasensio** [comment]
Dear @JohannaOtt 

Apologise, is an internal problem, we will contact you when this is solved.

Regards

**Comment by josemasensio** [comment]
Dear @JohannaOtt,

Please, could you try to send the credentials now? 

Best regards.

**Comment by josemasensio** [comment]
Dear @JohannaOtt,

We have already received the file. We will start to check why the error is occurring as soon as possible.

Best regards.

**Comment by fabiovin** [comment]
Dear @JohannaOtt ,
as you stated
> that error/message is comprehensible and fits to the IR Requirement in Annex II, Section 7.9.3

the error is related to "Theme-specific Requirements – Geometry representation". Therefore, the validator checks that **each** node is present where a link connects or ends.
The name "`freeNode`" is just a label used in the ETS to identify these kinds of errors. There is no way to mark/identify '`freeNodes`' in the data, also because the Data Specification not foreseen that.

In any case, looking at Figure 40 (pag. 120) of the Data Specification it seems that an AerodromeNode could be an "isolated" node, without any "direct" connection with any "network link".
Probably the "AerodromeNode" feature type should be a generalisation of the "TransportPoint" feature type instead of the "TransportNode" feature type. In this way, the aerodrome nodes would not fit into the IR Requirement about the geometry representation.
What do you think about this?

If this interpretation is correct, the AerodromeNode could be excluded from "Geometry representation" test.

It could be an interesting discussion for the INSPIRE Community Forum, as it may require an IR review.  Could you please open it, if you think it's useful?

**Comment by JohannaOtt** [comment]
Dear @fabiovin ,

Looking at Figure 40 in the Data Specification, I had the impression an AerodromeNode needs a Link to a different kind of TransportNetwork (road, railway,...) via a NetworkConnection. But I see now that it is only used for logical connections and therefore is not a Link.
This does indeed lead to the conclusion that AerodromeNodes could be isolated notes. 
I opened this Thread for it in the Thematic Cluster: https://inspire.ec.europa.eu/forum/discussion/view/261634/tn-air-should-aerodromenode-be-a-transportnode-or-a-transportpoint

**Comment by JohannaOtt** [comment]
@fabiovin As the post in the Thematic Cluster would need some support in order to make it to an actual change request to the JRC, please feel free to add any further information/input you have.

**Comment by dperezBM** [comment]
Dear all,

Since this issue had no interaction time ago, we decided to close it. Please feel free to open a new one if needed.

Thank you and best regards.

**Comment by JohannaOtt** [comment]
As there is still no solution, I created https://github.com/INSPIRE-MIF/helpdesk/issues/62

**Comment by fabiovinci** [comment]
A schema change proposal to address the issue has been opened [here](https://github.com/INSPIRE-MIF/application-schemas/issues/61).

**Comment by fabiovinci** [comment]
Dear all,

according to the results of the [related schema change proposal](https://github.com/INSPIRE-MIF/application-schemas/issues/61), a related [TG change proposal](https://github.com/INSPIRE-MIF/technical-guidelines/issues/106) was opened. The change in the TG will clarify that an AirNode is not necessarily placed at the end or start of a Transport Link when it is not used for navigation/ATS purposes (Example: an AerodromeNode could either simply represent the aerodrome location (significantPoint = false) or act as transport node for connectivity (significantPoint = true).

An exception was already introduced in the [related ATS](https://github.com/inspire-eu-validation/data-tn/blob/master/tn-as/geometry.md) to skip the geometry test for the nodes related to the AirNode feature type (i.e. nodes related to the Navaid, DesignatedPoint, RunwayCentrelinePoint, AerodromeNode and TouchDownLiftOff feature types) for which the value of the `significantPoint` attribute is equal to "_false_",

The related fix will be introduced in the validator.

**Comment by dperezBM** [comment]
Dear @JohannaOtt,

The significantPoint= false exception has been applied for air related transport nodes and the solution is available in [staging environment](http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/home/index.html). Could you check if it is correct?

Regards

PS: @fabiovinci could you also check it?

**Comment by fabiovinci** [comment]
I tested the solution and can confirm that the exception works as expected.

**Comment by JohannaOtt** [comment]
@dperezBM I tried to test it but when trying to upload my file to the staging instance it fails 
![grafik](https://github.com/INSPIRE-MIF/helpdesk-validator/assets/34163838/863f21f2-1212-4a35-bdec-865368bb37cb)

**Comment by fabiovinci** [comment]
Hi @JohannaOtt,

the fix was included in the 2023.2 release, so you can test it in the production instance.

**Comment by JohannaOtt** [comment]
@fabiovinci Just tried to do so but that one is also running into an error 
![grafik](https://github.com/INSPIRE-MIF/helpdesk-validator/assets/34163838/f3c76a95-5c3e-4c43-af14-5012655e3596)
