### ISSUE TITLE
Version 2.0 metadata rules

### ISSUE THREAD

**Issue by mhogeweg** [INSPIRE-MIF/helpdesk-validator#114]
I have metadata that passes the version 1.3 validator, but fails the version 2.0 beta validation. See this report:
http://inspire.ec.europa.eu/validator/v2/TestRuns/EIDb9471602-09f3-49da-817a-00b53224326c.html

Should valid 1.3 metadata expected to be valid 2.0 metadata? Or will everyone across Europe have to rework their metadata to be compliant again?

**Comment by michellutz** [comment]
We can confirm what Peter already wrote: Version 2.0 of the MD TG were published in Dec 2016, with a 3-year(!) implementation deadline to enable a smooth transition (even though we note that many countries are only really starting now...).

The changes in the TG mainly aimed at clarifying requirements and make them more easily testable, but in some cases this meant also that the new version is not backwards-compatible to v1.3 (hence the new major version).

We suggest reading the section "Foreword to this version" and Annex F Mapping for Requirements in previous TG version" to get an overview of the changes and the implementation period.

**Comment by dperezBM** [comment]
Dear all,

Thank you very much for your contributions. We are about to close this topic. Please feel free to open another issue if necessary.

Best regards.
