### ISSUE TITLE
THE VALIDATOR DOES NOT PERFORM THE TESTS

### ISSUE THREAD

**Issue by jjgonzalezs** [INSPIRE-MIF/helpdesk-validator#1152]
The validator does not perform the tests. 

After successful upload of files

When trying to test the metadata and ISO compliance requirements, it gives an error message.

Screenshots are attached

![image](https://github.com/user-attachments/assets/9640a523-92b3-4ccb-af4f-62a970dc328e)

![image](https://github.com/user-attachments/assets/90d186cf-5b49-4d1f-98f0-673ab2d15428)

**Comment by fabiovinci** [comment]
Dear @jjgonzalezs,

could you please send us the metadata you are testing to reproduce the issue?

**Comment by jjgonzalezs** [comment]
Dear @fabiovinci 

I inform you that the validator now works correctly. Thanks for all
