### ISSUE TITLE
Dear team,

### ISSUE THREAD

**Issue by sofiaribeiro-apa** [INSPIRE-MIF/helpdesk-validator#1153]
Before reporting an issue with the INSPIRE Reference Validator deployed at JRC, please:
- check whether a similar issue has already been opened
- try to validate your resource after cleaning the browser cache (in case of error during the upload of the resource) 
- check the [list of known limitations](https://github.com/INSPIRE-MIF/helpdesk-validator/wiki/Known-limitations).

To report an issue, please replace these lines with a brief summary of your issue and the expected behaviour.

To help us investigate the issue, you may want to include:

- a description of the steps to reproduce your issue
- the browser and version used
- a screenshot illustrating the problem
- the Test Report (ideally as an attachment to the issue)
- the name of the Test that failed or better: change the `Level of Detail`
in the Report by clicking on `All Details`, then scroll down to the failed test
and copy the Link on the right-hand side of the `Assertion URI`
- the URL of your service / the file you have uploaded or referenced (as
an attachment).

If your service is protected or you have confidential data that you cannot
upload here, you can request an email address to which you can send URLs / files.
Please note that issues cannot be investigated for services/datasets that we cannot
access.

**Comment by fabiovinci** [comment]
It seems there was an error in the opening of this issue, as it contains only the default guidance text.
