### ISSUE TITLE
md common req C.11: Temporal Reference

### ISSUE THREAD

**Issue by Kate-Lyndegaard** [INSPIRE-MIF/helpdesk-validator#116]
Hi,

My metadata is returning a large number of errors for tests which validate the location of codelists, including md common req C.11 Temporal Reference. 

Can you please tell me why the following location is not acceptable?:
http://standards.iso.org/ittf/PubliclyAvailableStandards/ISO_19139_Schemas/resources/codelist/ML_gmxCodelists.xml#CI_DateTypeCode

Thank you.

Kind regards
//Kate

**Comment by josemasensio** [comment]
Dear @Kate-Lyndegaard,

Thank you for your message. To make it easier for us to find the issue, we recommend you follow these [contribution guidelines](https://github.com/inspire-eu-validation/community/blob/master/contribution_guidelines.md).

Best regards.

**Comment by Kate-Lyndegaard** [comment]
Dear @josemasensio,

Thank you for adding my comments.

**Test:** Common Requirements for ISO/TC 19139:2007 based INSPIRE metadata records - md common req C.11: Temporal Reference.
**Link to tested resource:** https://test.haleconnect.de/services/bsp/org.11.c8b5af02-83c4-4cf4-861c-0392ac1e1be6/md/dataset/dataset1
**Browser and version:** Firefox Quantum 69.0
**Screenshot:**
![grafik](https://user-images.githubusercontent.com/36956461/64848573-d2be8480-d611-11e9-9115-5bb6f72018b6.png)

I would like to know why there is an error reported for md common req C.11: Temporal Reference.
You can reproduce the error by running the URL given above through the Common Requirements for ISO/TC 19139:2007 based INSPIRE metadata records test.

Kind regards,
Kate

**Comment by josemasensio** [comment]
Dear @Kate-Lyndegaard,

I was trying to reproduce the issue but I can not see the long character list on my test report. 
Is this still happening to you?

Best regards

**Comment by Kate-Lyndegaard** [comment]
Dear @josemasensio,

Yes, I just re-tested it. When I run the URL (https://test.haleconnect.de/services/bsp/org.11.c8b5af02-83c4-4cf4-861c-0392ac1e1be6/md/dataset/dataset1) through the Common Requirements for ISO/TC 19139:2007 based INSPIRE metadata records test, with no other tests selected, I receive the error:

**Test results (Common Requirements for ISO/TC 19139:2007 based INSPIRE metadata records):**

[CommonReqTestResults.zip](https://github.com/inspire-eu-validation/community/files/3661550/CommonReqTestResults.zip)

Kind regards,
Kate

**Comment by josemasensio** [comment]
Dear @Kate-Lyndegaard,

What is happening here is that the metadata has `gmd:date/gmd:CI_Date/gmd:dateType/gmd:CI_DateTypeCode` with the wrong `@codeList`. The correct value should be `http://standards.iso.org/iso/19139/resources/gmxCodelists.xml#CI_DateTypeCode` instead of `http://standards.iso.org/ittf/PubliclyAvailableStandards/ISO_19139_Schemas/resources/codelist/ML_gmxCodelists.xml#CI_DateTypeCode`.

Best regards.

**Comment by josemasensio** [comment]
Dear @Kate-Lyndegaard,

Does this solution work? 

Best regards.
