### ISSUE TITLE
md common req C.5: Language Code

### ISSUE THREAD

**Issue by Kate-Lyndegaard** [INSPIRE-MIF/helpdesk-validator#117]
Hi,

My metadata receives an error message on this test because it references the following codelst:
"http://standards.iso.org/ittf/PubliclyAvailableStandards/ISO_19139_Schemas/resources/codelist/ML_gmxCodelists.xml#LanguageCode"

I would like to know why this is not accepted, and why the location is tested.

Thank you.

Kind regards
//Kate

**Comment by josemasensio** [comment]
Dear @Kate-Lyndegaard,

Thank you for your message. To make it easier for us to find the issue, we recommend you follow these contribution guidelines.

Best regards.

**Comment by Kate-Lyndegaard** [comment]
Hi @josemasensio,
My comments mirror the concerns expressed in #52 
Kind regards,
Kate

**Comment by josemasensio** [comment]
Dear @Kate-Lyndegaard,

As expressed on the [Technical Guidance](https://inspire.ec.europa.eu/sites/default/files/documents/metadata/inspire-tg-metadata-iso19139-2.0.1.pdf), on page 33, the attribute codeList shall be "http://www.loc.gov/standards/iso639-2/" and the attribute codeListValue shall contain one of the three-letter bibliographic language code values.

Best regards.

**Comment by Kate-Lyndegaard** [comment]
Dear @josemasensio,

Thank you for your response. For multi-lingual metadata, I will add multiple gmd:language elements.

Kind regards,
Kate
