### ISSUE TITLE
Typo:  Conformance Class 6: INSPIRE Interoperable Spatial Data Services metadata

### ISSUE THREAD

**Issue by Kate-Lyndegaard** [INSPIRE-MIF/helpdesk-validator#118]
Dear @josemasensio,

I believe you have a typo here:
![grafik](https://user-images.githubusercontent.com/36956461/64849158-11087380-d613-11e9-869e-d1cd4b2d5877.png)

Kind regards,
Kate

**Comment by josemasensio** [comment]
Dear @Kate-Lyndegaard,

We have modified this and is available on the [staging instance](http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/). If this does not appear, please try later.

Best regards.
