### ISSUE TITLE
Cannot find a declaration of element: FeatureCollection 

### ISSUE THREAD

**Issue by apfelnymous** [INSPIRE-MIF/helpdesk-validator#119]
Hello people, the validator reports an error (gmlas.b.2: validate xml documents) concerning a missing declaration of FeatureCollection. (XML document 'Geology.gml': 1:1454: cvc-elt.1.a: Cannot find the declaration of element 'gml:FeatureCollection'.) 

This is the FeatureCollection in my tested gml:

`<gml:FeatureCollection xmlns:gss="http://www.isotc211.org/2005/gss" 
xmlns:tn="http://inspire.ec.europa.eu/schemas/tn/4.0" 
xmlns:bu-base="http://inspire.ec.europa.eu/schemas/bu-base/4.0" 
xmlns:gco="http://www.isotc211.org/2005/gco" 
xmlns:gml="http://www.opengis.net/gml/3.2" 
xmlns:base="http://inspire.ec.europa.eu/schemas/base/3.3" 
xmlns:base2="http://inspire.ec.europa.eu/schemas/base2/2.0" 
xmlns:gsr="http://www.isotc211.org/2005/gsr" 
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xmlns:ge="http://inspire.ec.europa.eu/schemas/ge-core/4.0" 
xmlns:ad="http://inspire.ec.europa.eu/schemas/ad/4.0" 
xmlns:ge_gp="http://inspire.ec.europa.eu/schemas/ge_gp/4.0" 
xmlns:au="http://inspire.ec.europa.eu/schemas/au/4.0" 
xmlns:sams="http://www.opengis.net/samplingSpatial/2.0" 
xmlns:om="http://www.opengis.net/om/2.0" 
xmlns:gn="http://inspire.ec.europa.eu/schemas/gn/4.0" 
xmlns:gmd="http://www.isotc211.org/2005/gmd" 
xmlns:xlink="http://www.w3.org/1999/xlink" 
xmlns:sc="http://www.interactive-instruments.de/ShapeChange/AppInfo" 
xmlns:swe="http://www.opengis.net/swe/2.0" 
xmlns:net="http://inspire.ec.europa.eu/schemas/net/4.0" 
xmlns:gts="http://www.isotc211.org/2005/gts" 
xmlns:sam="http://www.opengis.net/sampling/2.0" 
xmlns:cp="http://inspire.ec.europa.eu/schemas/cp/4.0" 
gml:id="ide8862e59-76a2-4f7d-99ee-5bc43a1849ac" 
xsi:schemaLocation="http://inspire.ec.europa.eu/schemas/ge-core/4.0 http://inspire.ec.europa.eu/schemas/ge-core/4.0/GeologyCore.xsd">
...
...
...`

Any clue why it would not accept this ?

Kind regards

**Comment by MarcoMinghini** [comment]
Dear @apfelnymous,
can you please follow the instructions explained in the [contribution guidelines](https://github.com/inspire-eu-validation/community/blob/master/contribution_guidelines.md), in particular on how to report an issue? 
We need to get some more context about your issue in order to replicate and investigate it.
Thank you.

**Comment by apfelnymous** [comment]
**The full name of the test (conformance class) that generated the issue.**
Conformance class:INSPIRE GML application schemas, General requirements -> Schema validation -> gmlas.b.2: validate xml documents

**The resource or the link to the resource that you tested. If this has credentials, please send the credentials to inspire-helpdesk@bilbomatica.com.**

**A short description of the steps to reproduce your issue.**

**If possible, a screenshot illustrating the problem.**

The snippet I posted above.

**The browser and version used.**
Firefox Quantum 69.0.1

**Comment by fabiovin** [comment]
Dear @apfelnymous,
the error should be due to the lack of the `gml.xsd` schema in the `schamaLocation `element.
The validator requires the declaration of the schema in which the root element is defined (i.e. `gml:FeatureCollection`).
Please try to add the following value in the schemaLocation "http://www.opengis.net/gml/3.2 http://schemas.opengis.net/gml/3.2.1/gml.xsd".

Kind regards

**Comment by apfelnymous** [comment]
@josemasensio the gml ist 100+mb large.
@fabiovin Thank you, that solved it, I needed to add:
http://www.opengis.net/gml/3.2 and http://schemas.opengis.net/gml/3.2.1/deprecatedTypes.xsd
to the schemaLocation. I dont know why fme didnt do that, never needed to care about this with Hale Studio.

Ill need to check why one of my reference gml's has this "/3.2.1/depractedType.xsd" value unlike your recommendation.

Kind regards
János

**Comment by apfelnymous** [comment]
Ill need to check why one of my reference gml's has this "/3.2.1/depractedType.xsd" value unlike your recommendation.

Regards

**Comment by fabiovin** [comment]
@apfelnymous, the deprecatedTypes.xsd schema is included in the gml.xsd schema.
Therefore, it should not be necessary to declare it in the schemaLocation attribute.

**Comment by apfelnymous** [comment]
@fabiovin Thx alot !
