### ISSUE TITLE
Test md-iso.d.2: Service linkage fails on service link which is available from port 8080

### ISSUE THREAD

**Issue by klimeto** [INSPIRE-MIF/helpdesk-validator#12]
Dear provider,

The validator fails on validating the following service link:

http://sluzby.vuvh.sk:8080/arcgis/services/RiverBasinDistrict_external/MapServer/WMSServer?request=GetCapabilities&service=WMS

in the following MD record:

https://rpi.gov.sk/rpi_csw/service.svc/get?request=GetRecordById&service=CSW&version=2.0.2&elementSetName=full&outputschema=http://www.isotc211.org/2005/gmd&Id=https://data.gov.sk/set/rpi/gmd/42181810/4F1D29041153596EE0530210000A8020

However you can open the Capabilities in a browser, or even add the WMS layers in e.g. QGIS tool.

Could you help us to understand where the problem is?

Thank you.

**Comment by df-git** [comment]
Dear klimeto.
We have checked our system configuration. Con you please try now?
