### ISSUE TITLE
INSPIRE validator inoperative

### ISSUE THREAD

**Issue by pmendive** [INSPIRE-MIF/helpdesk-validator#122]
Hello

Is there any problem with the INSPIRE validator? it seems it is not working.

Thanks 

BR

**Comment by juanpelegrina** [comment]
Dear @pmendive 

we are currently working on maintenance works (issue #121). Sorry for the inconvenience. The staging version is available http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/

Regards
Juan

**Comment by MarcoMinghini** [comment]
The production instance of the Validator is up and running again. Sorry for the inconvenience.
