### ISSUE TITLE
Metadata test suite Conformance Class 4: INSPIRE Network Services metadata, nothing is tested 

### ISSUE THREAD

**Issue by idevisser** [INSPIRE-MIF/helpdesk-validator#125]
something changed today, in this test suite no tests are executed;

Total Count | Skipped | Failed | Warnings | Manual
-- | -- | -- | -- | --
Test suites | 0 | 0 | 0 | 0 | 0
Test cases | 0 | 0 | 0 | 0 | 0
Assertions | 0 | 0 | 0 | 0 | 0

Best regards Ine

**Comment by juanpelegrina** [comment]
Thanks @idevisser, 
we are aware of the situation, we are currently working on it. 
Regards

**Comment by josemasensio** [comment]
Dear @idevisser,

Could you please provide us with the instance and test you have run?

Best regards.

**Comment by idevisser** [comment]
Dear @josemasensio ,

I used this file 
[Voorbeeld_Metadata_Services_2019.zip](https://github.com/inspire-eu-validation/community/files/3710879/Voorbeeld_Metadata_Services_2019.zip)

 to test in the metadata  version 2.0 test suite with Conformance Class 4

best regards Ine

**Comment by carlospzurita** [comment]
Dear @idevisser ,

The tests are now executing just fine with the data you provided. You can check it on http://inspire.ec.europa.eu/validator .

Best.
