### ISSUE TITLE
Test run won't start

### ISSUE THREAD

**Issue by JohannaOtt** [INSPIRE-MIF/helpdesk-validator#126]
I just tried to validate metadata using the INSPIRE Validator, but the test run does not start with the following message:
![grafik](https://user-images.githubusercontent.com/34163838/66547156-e8ef3000-eb3e-11e9-9f30-825fdc4fe7f2.png)

Is the validator down currently or is there any maintenance going on?

I tried with both, external URL and file upload.
I am using Firefox 60.9.0esr on Windows 10.

Thank you in advance!
Johanna

**Comment by juanpelegrina** [comment]
Dear @JohannaOtt 
The Validator is currently down, we are doing some maintenance works, meanwhile, you can use the staging instance for testing purpose. It will hopefully be up and running in a couple of hours.  
Sorry for the inconvenient caused.

**Comment by juanpelegrina** [comment]
Dear @JohannaOtt 
We have finished with the maintenance works, please try again and let us know if you are having any problem.
Regards
Juan

**Comment by JohannaOtt** [comment]
Dear @juanpelegrina 
Thank you for the update - works again!

Regards, Johanna
