### ISSUE TITLE
wrong redirection when closing the Configure Test Run dialogue

### ISSUE THREAD

**Issue by MarcoMinghini** [INSPIRE-MIF/helpdesk-validator#13]
From the ETF page http://inspire-sandbox.jrc.ec.europa.eu/etf-webapp (or http://inspire-sandbox.jrc.ec.europa.eu/etf-webapp/#start-tests), after selecting the conformance class(es) to test and pressing _Start_, the _Configure Test Run_ dialogue opens:

![configure_test_run_dialogue](https://user-images.githubusercontent.com/14758434/48489382-383fba00-e823-11e8-9fa8-add7149d9443.png)

if the dialogue is closed (using the X button at the top left) because e.g. the user wants to change the conformance class(es) to test, the user is not redirected back to the page where the conformance class(es) can be selected/changed (http://inspire-sandbox.jrc.ec.europa.eu/etf-webapp/#start-tests), but to another page outside the ETF (http://inspire-sandbox.jrc.ec.europa.eu/#start-tests). The link is wrong.

**Comment by carlospzurita** [comment]
A fix for this bug is ready on https://github.com/guadaltel/etf-webapp/commit/9aa440eef264c7992c096c7dcae371dd5ba82a52. A pull request will be created for this issue to be merged on https://github.com/etf-validator/etf-webapp, after its corresponding review.

**Comment by MarcoMinghini** [comment]
A fix for this bug has been deployed in the Staging environment: http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp and it's waiting to be deployed in the Production environment.
