### ISSUE TITLE
Does the online validator supports ISO 19115-2:2019 MI_Metadata?

### ISSUE THREAD

**Issue by MartinePaepen** [INSPIRE-MIF/helpdesk-validator#130]
We need to validate a metadata file which is compliant to ISO 19115-2:2019.
It is using gmi:MI_Metadata xml and we are not able to upload the file.
Should this be supported in the online validator?
Is there a workaround?
Is this in the pipeline to support ISO 19115-2:2019 in the near future?

**Comment by MartinePaepen** [comment]
Any news on this issue: using gmi:MI_Metadata as defined in the ISO 19115-2:2019 standard?
Many thanks,
Martine

**Comment by MartinePaepen** [comment]
Can you inform me on the status? 
Thanks,
Martine

**Comment by MartinePaepen** [comment]
Can you explain what the status is?
Thanks

**Comment by dperezBM** [comment]
Dear @MartinePaepen,

We proceed to close this issue, as it has been duplicated in [issue 253](https://github.com/INSPIRE-MIF/helpdesk-validator/issues/253). Thank you very much for your contribution.

Regards.
