### ISSUE TITLE
TestRun got stacked

### ISSUE THREAD

**Issue by klimeto** [INSPIRE-MIF/helpdesk-validator#133]
Dear devs,

I experienced a random problem with a TestRun with the UUID:  EID81710380-615e-40aa-b24b-5545cac20f27.

I launched a test using ETF API at 2019-10-17 08:02:00 UTC with a successful HTTP 201 Created response from ETF API.

Since then the progress request:
```http://inspire-validator.eu-west-1.elasticbeanstalk.com/validator/v2/TestRuns/EID81710380-615e-40aa-b24b-5545cac20f27/progress```

returns status val = 0.

```json

{
val: "0",
max: "33",
log: [
"17.10.2019 08:01:58 - Preparing Test Run Testing run of type &#39;DATASET_METADATA_TG13&#39; sent by Slovak Register Of Spatial Information API for TestObject &#39;None&#39; (initiated Thu Oct 17 08:01:58 UTC 2019)",
"17.10.2019 08:01:58 - Resolving Executable Test Suite dependencies",
"17.10.2019 08:01:58 - Preparing 3 Test Task:",
"17.10.2019 08:01:58 -  TestTask 1 (9f62daa5-c601-4399-bbce-941afa877030)",
"17.10.2019 08:01:58 -  will perform tests on Test Object 'get_rec.xml' by using Executable Test Suite 'Conformance class: XML encoding of ISO 19115/19119 metadata (EID: e3500038-e37c-4dcf-806c-6bc82d585b3b, V: 0.2.0 )'",
"17.10.2019 08:01:58 -  with parameters: ",
"17.10.2019 08:01:58 - etf.testcases = *",
"17.10.2019 08:01:58 -  TestTask 2 (802d9e5b-f6dc-4561-83bb-828253dec100)",
"17.10.2019 08:01:58 -  will perform tests on Test Object 'get_rec.xml' by using Executable Test Suite 'Conformance class: INSPIRE Profile based on EN ISO 19115 and EN ISO 19119 (EID: ec7323d5-d8f0-4cfe-b23a-b826df86d58c, V: 0.2.9 )'",
"17.10.2019 08:01:58 -  with parameters: ",
"17.10.2019 08:01:58 - etf.testcases = *",
"17.10.2019 08:01:58 -  TestTask 3 (ad86311b-7da9-4b38-b7b2-e92363f5bb6b)",
"17.10.2019 08:01:58 -  will perform tests on Test Object 'get_rec.xml' by using Executable Test Suite 'Conformance class: Metadata for interoperability (EID: 9a31ecfc-6673-43c0-9a31-b4595fb53a98, V: 0.2.5 )'",
"17.10.2019 08:01:58 -  with parameters: ",
"17.10.2019 08:01:58 - etf.testcases = *",
"17.10.2019 08:01:58 - Test Tasks prepared and ready to be executed. Waiting for the scheduler to start.",
"17.10.2019 08:01:58 - Setting state to CREATED",
"17.10.2019 08:01:58 - Changed state from CREATED to INITIALIZING"
]
}
```
Could you please check what is happening on the ETF application side for this TestRun (EID81710380-615e-40aa-b24b-5545cac20f27)?

I used the the production ETF API endpoint: ```http://inspire-validator.eu-west-1.elasticbeanstalk.com/validator/v2```

Thank you!

**Comment by klimeto** [comment]
By reading the ETF API response data it seems it got stacked at INITIALIZING state.

Does it mean it got in the queue and is waiting for resources?

**Comment by josemasensio** [comment]
Dear @klimeto 

Yes that meeans that the validation was queued. If you access http://inspire-validator.eu-west-1.elasticbeanstalk.com/validator/v2/TestRuns/EID81710380-615e-40aa-b24b-5545cac20f27/progress you can see that the validation process has already finished and you can check the results in http://inspire-validator.eu-west-1.elasticbeanstalk.com/validator/v2/TestRuns/EID81710380-615e-40aa-b24b-5545cac20f27.

Best Regards,
Jose

**Comment by klimeto** [comment]
Thanks @josemasensio,

Would be possible to flag the status "queued" in the /progress endpoint so I can place in my code a logic which would be checking the status until queues changed to running?

To have actually a flag saying "status":"status_value"

Thanks

**Comment by carlospzurita** [comment]
Dear @klimeto 
Right now we are not planning in adding this functionality to the API. It will be discussed internally and evaluate the feasibility of this improvement.

In the meantime, could you use the Api call to http://inspire.ec.europa.eu/validator/v2/TestRuns?view=progress ? There you can find the already running Tests and check if any of yours is being executed.

**Comment by dperezBM** [comment]
Dear @klimeto,

Thank you very much for your contributions. We hope that the solution offered to you was to your convenience. 
Please feel free to open another issue if necessary.

Best regards.
