### ISSUE TITLE
Schema Validation of ISO 19115 community profile XML document

### ISSUE THREAD

**Issue by enricoboldrini** [INSPIRE-MIF/helpdesk-validator#134]
Error returned: Cannot find the declaration of element 'gmd:MD_Metadata'.

I'm validating a SeaDataNet XML document, that is a community profile of ISO 19115 metadata, drafted according to official ISO 19115 rules.
This document should be validated using the schema(s) specified in its xsi:schemaLocation. These schemas are in turn importing the official ISO/OGC schemas (http://schemas.seadatanet.org/Standards-Software/Metadata-formats/SDN2_CDI_ISO19139_10.0.1.xsd), as well as defining some community elements.
In particular, the gmd:MD_Metadata element definition should be correctly found in the imported ISO AP schemas: http://www.isotc211.org/schemas/2005/gmd/gmd.xsd.

- Test Report: http://inspire-sandbox.jrc.ec.europa.eu/etf-webapp/v2/TestRuns/EIDcb80f9ea-9d37-463a-9aaf-b45806194b35.html
- Assertion URI: http://inspire-sandbox.jrc.ec.europa.eu/etf-webapp//v2/TestRuns/EIDcb80f9ea-9d37-463a-9aaf-b45806194b35.html?lang=en#EID6885e93c-cfd6-4f9c-8220-85e47f913959
- Referenced file: https://s3.amazonaws.com/essi.documents/seadatanet-test-2.xml

**Comment by enricoboldrini** [comment]
Just a little update: in the staging validator the error persists, while the official validator works as expected now.

**Comment by danielnavarrogeo** [comment]
Dear @enricoboldrini 

Thank you for your comments.

The XML schema validation in metadata 1.3 in staging instance works now as the official instance.

Could you please try again in staging instance?

We are working on some issues related to XML schema validation for metadata 1.3. Therefore, some changes might be expected.

I would like to remind that support for MD TG 1.3 will stop at the end of the year. Then, it is recommend to use MD TG 2.0.

Regards

**Comment by enricoboldrini** [comment]
Dear @danielnavarrogeo,

thank you very much for the follow up and info. I confirm that currently validation is successful in both environments. Regarding removal of support for MD TG 1.3 in favor of MD TG 2.0: does it mean that ISO schema version 20060504 (the one used by OGC IS AP ISO) will not be validated by the ETF-validator from next year? (in favor of version 20070417?)

Thank you very much in advance for the info,

Enrico

**Comment by fabiovin** [comment]
Dear @enricoboldrini,

please note that the OGC IS AP ISO schema (http://schemas.opengis.net/csw/2.0.2/profiles/apiso/1.0.0/apiso.xsd) already make use of the OGC version 2007-04-17 of the gmd namespace, and consequently of the GML version 3.2.1.

**Comment by enricoboldrini** [comment]
Dear @fabiovin,

thank you for the hint, I didn't noticed that. It seems OGC changed from 2006 to 2007 schemata in the AP ISO bug fix version 1.0.1 (2018-03-21).
(as far as I can understand from here: http://schemas.opengis.net/csw/2.0.2/profiles/apiso/ReadMe.txt)
Summarizing, the suggestion is to upgrade to 2007 schemata because they will be the only ones supported from next year. Is it correct?

Thank you again,

Enrico

**Comment by fabiovin** [comment]
Dear Enrico,
this is not completely correct!
The transition period, from MD version 1.3 to version 2.0, will end in December. For this reason, support for MD TG 1.3 will stop.

In any case, the MD TG 2.0 provides for the use of `gmd.xsd` schemas which refer to the _GML 3.2.0_ version (TG Requirement C.1). For instance, http://www.isotc211.org/2005/gmd/gmd.xsd or http://schemas.opengis.net/iso/19139/20060504/gmd/gmd.xsd (see footnotes on page 28). Please note that in footnote 14 there is an error since the cited schema refers to _GML 3.2.0_ version and not to _3.2.1_.

**Comment by enricoboldrini** [comment]
O.k., perfect. Thank you for the follow up @fabiovin, that's appreciated.

Enrico

**Comment by josemasensio** [comment]
Dear @enricoboldrini,

Does the provided solution work?

Best regards.

**Comment by enricoboldrini** [comment]
Dear @josemasensio yes it works, thank you!

Enrico

**Comment by josemasensio** [comment]
Dear @enricoboldrini,

Glad to hear that. We will mark the issue as solved.

Best regards.
