### ISSUE TITLE
Validator IP addresses.

### ISSUE THREAD

**Issue by vicehovskis** [INSPIRE-MIF/helpdesk-validator#135]
Is it possible to get the list of IP addresses used in Inspire validator (http://inspire.ec.europa.eu/validator/) for validating metadata and services? We need to open access to the several services only from predefined IP addresses, so we can validate them properly.

**Comment by carlospzurita** [comment]
Dear @vicehovskis 
As it is right now, the validator is deployed in an AWS instance that assigns dynamically a new IP each time the instance is reloaded. Whatever maintenance work that would be performed on the instance will provoke the IP to change. If this is a punctual operation, we can provide you the current IP, but keep in mind that there is no guarantee that will remain as it is.

**Comment by dperezBM** [comment]
Dear @vicehovskis,

Thank you very much for your question. In case you have any other questions or problems, please feel free to open a new issue.

Best regards.
