### ISSUE TITLE
WAR files sharing for ETF prod and staging

### ISSUE THREAD

**Issue by klimeto** [INSPIRE-MIF/helpdesk-validator#136]
Dear devs,

Is it possible to share (if not yet accessible from github) both production and staging build .WAR files for ETF? 

I would like to set up a docker environment for ETF both prod and staging without a need to build it in order to have one to one correspondence with what you publish online from amazon?

Many thanks,
Tomas

**Comment by carlospzurita** [comment]
Dear @klimeto 
We can't share the .WAR file right now through this channel. However, we are planning to release very soon a Docker image containing a pre-built instance of the validator, using a copy of the .WAR file deployed in production. This Docker image will be updated with each release, to keep it aligned with the contents of the Reference Validator.

**Comment by klimeto** [comment]
Dear @carlospzurita,

Having a docker image with current release of ETF war sounds as a great idea and will be very useful. 

Do you plan to publish it via Docker registry or other registry?

Please keep us updated once you release the image, so we can test it within our staging environment. 

Thank you,
Tomas

**Comment by carlospzurita** [comment]
Dear @klimeto 
We still need to discuss the publishing internally, but it will probably be through DockerHub.
We will make an announcement on the community space whenever the image is ready.
Kind regards.

**Comment by josemasensio** [comment]
Dear @klimeto 
With the release of the v1.0.8, we also released a .war file. 
It comes into [this .zip file](https://github.com/inspire-eu-validation/community/releases/download/v1.0.8/etf-release-v1.0.8.zip), with the instructions to deploy it. 

Best regards.
