### ISSUE TITLE
Metadata - inconsistency of INSPIRE metadata codelist register with INSPIRE legislation

### ISSUE THREAD

**Issue by fantamir** [INSPIRE-MIF/helpdesk-validator#137]
The INSPIRE legislation "**COMMISSION REGULATION (EC) No 1205/2008 ....**"  - see here: [https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX:32008R1205](url) 
contains in **ANNEX - Metadata implementing rules - Part B, paragraph 8.1 Conditions applying to access and use** following sentence: 
_The element must have values. If no conditions apply to the access and use of the resource, ‘**no conditions apply**’ shall be used. If conditions are unknown, ‘**conditions unknown**’ shall be used._

On the other hand, the **INSPIRE metadata codelist register** for **Conditions Applying To Access and Use** available here: [http://inspire.ec.europa.eu/metadata-codelist/ConditionsApplyingToAccessAndUse](url) has following two items:

- **conditions to access and use unknown**
- **no conditions to access and use**

Please harmonize INSPIRE metadata codelist register with corresponding legislation or let us know, which wording shall we use in the English version of the metadata item 8.1 codelist in our metadata editor:

- "_conditions unknown_" or "_conditions to access and use unknown_" ?
- "_no conditions apply_" or "_no conditions to access and use_" ?

**Comment by fabiovin** [comment]
Dear @fantamir,

the values you mentioned are used in the registry as "`Label`", if you look at the "`ID`" (same as the http URL) you can see the official ones, mentioned in the IR.

Following the _TG Requirement C.18_ in the MD TG 2.0 you are obliged to use these values for the encoding of the related element.
So, the metadata element shall include a `gmx:Anchor` with attribute `xlink:href` containing one of the following values (in case they apply):

- http://inspire.ec.europa.eu/metadata-codelist/ConditionsApplyingToAccessAndUse/noConditionsApply

- http://inspire.ec.europa.eu/metadata-codelist/ConditionsApplyingToAccessAndUse/conditionsUnknown

I think that if you want to use a text, in addition to the URL, you can use the values "conditions unknown" and "no conditions apply".

**Comment by josemasensio** [comment]
Dear @fantamir,

Was the explanation provided by @fabiovin valid for you? 

Best regards.

**Comment by josemasensio** [comment]
After some internal tests, we checked that everything is working fine, so we will mark as solved this issue.

Best regards.
