### ISSUE TITLE
MD TG v2.0 C.21: Conformity specification

### ISSUE THREAD

**Issue by dartasensi** [INSPIRE-MIF/helpdesk-validator#139]
Hi,

During an analysis of this requirement, I think I found a missed check in the XQuery procedure, that could lead to false negative errors in validation.

The requirement says:
The title shall be given using the gmd:title child element of the citation element **with a Non-empty Free Text Element content**. For the INSPIRE Implementation Rule documents the value of the title element shall match exactly the official title of the cited document in the language of the metadata.

But the XQuery seems to check only for the presence of the gmd:title element, and no other checks are made on its children (refer to TG Req C.4 about the Free Text element).
https://github.com/inspire-eu-validation/ets-repository/blob/f38e7964888ce37a547ccb2a15966c56aba5a494/metadata/2.0/common/ets-md-common-bsxets.xml#L894

I've altered the reference sample of MD 2.0, introduced the error of empty title.
Tested against the production and staging validator, it _wrongly_ pass the test with SUCCESS.

To reproduce:
- use the attached sample [md_2.0_datasets_example-c.21-conformity_single_element_empty_title.xml.zip](https://github.com/inspire-eu-validation/community/files/3755895/md_2.0_datasets_example-c.21-conformity_single_element_empty_title.xml.zip)
- launch a validation on MD 2.0 Common req class

Best regards,
Davide Artasensi

**Comment by danielnavarrogeo** [comment]
Dear Davide,

Thank you for your comment. You are right, the test should check that the title is not empty as well.

We will modify the test and let you know when available in staging for testing.

Regards

**Comment by danielnavarrogeo** [comment]
Dear Davide,

The test now checks if the title is a non-empty free text. You can try it in the staging environment.

Regards

**Comment by dartasensi** [comment]
Thanks, I will try and give you a feedback.

Regards,
Davide

**Comment by dartasensi** [comment]
Dear Daniel,

after some tests, I found other problems within your fix.
Luckily I traced back your pull request, and I've made some comments about it.
Please, have a look here:
https://github.com/inspire-eu-validation/ets-repository/pull/347

Regards,
Davide

**Comment by danielnavarrogeo** [comment]
Dear Davide,

The test has been modified according to your suggestions. You can now test it in the staging environment.

Regards

**Comment by josemasensio** [comment]
Dear @dartasensi,

Does the solution that @danielnavarrogeo provide work?

Best regard.

**Comment by juanpelegrina** [comment]
Dear @dartasensi 

we are planning a release soon and we would like to include this issue on the next [milestone](https://github.com/inspire-eu-validation/community/milestone/1). Could you let us know if the solution implemented works as expected? 

Regards

**Comment by josemasensio** [comment]
After some internal tests, we checked that everything is working fine, so we will mark as solved this issue.

Best regards.

**Comment by MarcoMinghini** [comment]
I can confirm that the issue was solved.
