### ISSUE TITLE
Problem while referencing RoadServiceType on RoadNode

### ISSUE THREAD

**Issue by DLList** [INSPIRE-MIF/helpdesk-validator#140]
Hello,

I have a problem with the ETF-Validator that I'd like to solve here.

I am currently busy developing a tool for transforming street data into INSPIRE Transport Network Structures. I have created several INSPIRE Features and tested them with the validator. I have a problem with the feature class "RoadServiceType"

**My approach for creating INSPIRE-Data**

The following steps are performed:
(1) Development of a RoadNode and filling of the attribute formOfRoadNode with the CodeList value"http://inspire.ec.europa.eu/codelist/FormOfRoadNodeValue/roadServiceArea".
(2) Development of a RoadServiceType
(3) Referencing the RoadServiceType on the RoadNode.

**Testing the DataSet with the Validator**

The following error occurs when testing the data set with the validator:
"XML document 'Inspire-Data.xml', RoadServiceType 'RoadServiceType.ARV', property 'networkRef.element': The property references a resource at '#RoadNode.ARV', but the resource is a 'RoadNode' with an incorrect value for the 'formOfRoadNode' propery, which must be a 'roadServiceArea'. Found: 'http://inspire.ec.europa.eu/codelist/FormOfRoadNodeValue/roadServiceArea'".

The validator wants the attribute formOfRoadNode to be filled with the value 'roadServicaArea'. This is not possible because it is a CodeList attribute. This means that the corresponding URL must be specified here: 'http://inspire.ec.europa.eu/codelist/FormOfRoadNodeValue/roadServiceArea'.

**Alternative**

--

**Question**

Is this an error of the validator? 

Best regards,
Dawid

**Comment by josemasensio** [comment]
Dear @DLList,

Thank you for your message. Please, could you provide us with the file that you have tested? This will help us to create own internal test to fix this issue. 

Best regards.

**Comment by DLList** [comment]
Dear @josemasensio,

I hereby send you the data I have tested. 

Best regards

[Inspire-A2_NRW.zip](https://github.com/inspire-eu-validation/community/files/3886981/Inspire-A2_NRW.zip)

**Comment by josemasensio** [comment]
Dear @DLList,

After some research, we check that there is not an issue with the validator. 
As defined on the [corresponding TG](https://inspire.ec.europa.eu/documents/Data_Specifications/INSPIRE_DataSpecification_TN_v3.2.pdf) Page 58 of the document at section 5.4.2.1.8 and on the [Abstract Test Case](https://github.com/inspire-eu-validation/data-tn/blob/master/tn-ro-as/constraints.md) where the automated test is defined, the last bullet point is the definition of this automated test: 
>This property can only be associated with a spatial object of the type RoadServiceArea or RoadNode (when formOfRoadNode=roadServiceArea).

Checking inside the automated test, will check the `@xlink:href` of the element and then it will validate if the value of formOfRoadNode is a roadServiceArea. If this is not, the check will fail and it will raise an error. In this case, you filled the `@xlink:href` with a link which begins with `http:\\`, so the validator will be expecting an object. If you update the URI to URL and instead of `http:\\` you write `https:\\` there not have to be any problem.

Please, let us know if this clarification has solved your problem.

Best regards.

**Comment by DLList** [comment]
Dear @josemasensio,

I don't understand the problem. You mean that the value of the attribute "_formOfRoadNode_" _'http://inspire.ec.europa.eu/codelist/FormOfRoadNodeValue/roadServiceArea'_ is not INSPIRE compliant?
It should be _'https://inspire.ec.europa.eu/codelist/FormOfRoadNodeValue/roadServiceArea'_?

Best regards.

**Comment by josemasensio** [comment]
Dear @DLList,

Yes. You could use `https://inspire.ec.europa.eu/codelist/FormOfRoadNodeValue/roadServiceArea` inside the `@xlink:href`.

Best regards.

**Comment by DLList** [comment]
Dear @josemasensio,

ok, it's something new for me. 
And what about the RoadNodes with f.e. the formOfRoadNode-value: 
`http://inspire.ec.europa.eu/codelist/FormOfRoadNodeValue/junction`?
If I understand correctly, they should also change to: 
`https://inspire.ec.europa.eu/codelist/FormOfRoadNodeValue/junction`?

Best regards.

**Comment by michellutz** [comment]
Sorry to intervene here. 

You should NOT use **https** URIs for INSPIRE code list values. These have been defined as persistent ids (and will therefore remain) within the **http** URI space.

This should also not be the issue that you encountered. I will have a closer look into this now.

Cheers, Michael

**Comment by michellutz** [comment]
I think I tracked down the issue.

In https://github.com/inspire-eu-validation/ets-repository/blob/master/testquery-noggeo.xq line 222 the code list value is wrong (with an https URI):

` if ($root[((tn-ro3:formOfRoadNode/text() eq 'roadServiceArea') or (tn-ro:formOfRoadNode/@xlink:href eq 'https://inspire.ec.europa.eu/codelist/FormOfRoadNodeValue/roadServiceArea'))]) then ()`

Instead it should be:

` if ($root[((tn-ro3:formOfRoadNode/text() eq 'roadServiceArea') or (tn-ro:formOfRoadNode/@xlink:href eq 'http://inspire.ec.europa.eu/codelist/FormOfRoadNodeValue/roadServiceArea'))]) then ()`

**Comment by josemasensio** [comment]
Dear all,
We have updated the testquery-noggeo file as @michellutz commented above. The changes will be available on our [staging instance](http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/) tomorrow. 
Thank you and best regards.

**Comment by DLList** [comment]
Dear @michellutz,
thank you for the clearing of this topic.

Best regards.

**Comment by josemasensio** [comment]
Dear @DLList,

We will appreciate it if you could provide us with your feedback. Thank you.

Best regards.

**Comment by danielnavarrogeo** [comment]
Dear @DLList 

Could you please check the implemented solution in [staging](http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/) environment and provide us feedback?

Regards

**Comment by DLList** [comment]
Dear **@danielnavarrogeo** 

thank you for the help. The solution now appears to be correct.

Regards

**Comment by danielnavarrogeo** [comment]
Thank you @DLList for your feedback.

Regards
