### ISSUE TITLE
Maintenance works

### ISSUE THREAD

**Issue by josemasensio** [INSPIRE-MIF/helpdesk-validator#142]
Due maintenance works the INSPIRE Validator will be temporary down. Meanwhile, you can use the [staging instance ](http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/) for testing purpose. Sorry for the inconvenience.

**Comment by juanpelegrina** [comment]
Maintenance works done. Sorry for the inconvenience
