### ISSUE TITLE
Use of 2006 gmd xsd for dataset metadata?

### ISSUE THREAD

**Issue by pvgenuchten** [INSPIRE-MIF/helpdesk-validator#143]
[this Abstract test](https://github.com/inspire-eu-validation/metadata/blob/2.0/common/xml-schema.md) lists 3 schema locations for inspire metadata, to our understanding [this schema](http://schemas.opengis.net/iso/19139/20060504/gmd/gmd.xsd) can also be used to describe datasets and series. Would love to hear your thoughts on this.

The issue relates to #85, because the 2006 version links to a different gml version then the 2007 version, it would mean the validator should use the proper gml version based on the schema used.

**Comment by josegar74** [comment]
2006 schema version passes the [test](https://github.com/inspire-eu-validation/metadata/blob/2.0/common/xml-schema.md), although not even listed in the test.

It works fine, unless you use any `gml` element as seem the validator expects GML 3.2, while 2006 schemas doesn't support it.

Attached 2 files with same metadata, the only difference is the usage o an element with the `gml` namespace.

- Validates: [660c5966-6992-4297-a3fa-c4d3d77839662-no-gml.txt](https://github.com/inspire-eu-validation/community/files/3777996/660c5966-6992-4297-a3fa-c4d3d77839662-no-gml.txt)

- Doesn't validate: [660c5966-6992-4297-a3fa-c4d3d77839662-with-gml.txt](https://github.com/inspire-eu-validation/community/files/3777997/660c5966-6992-4297-a3fa-c4d3d77839662-with-gml.txt)

**Comment by danielnavarrogeo** [comment]
Dear @pvgenuchten and @josegar74,

This issue has been solved in #238. 

Would you mind checking the implemented solution in [staging](http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/) and provide us feedback?

Regards

**Comment by danielnavarrogeo** [comment]
Dear @pvgenuchten and @josegar74 

Since the issue has been validated in #238  we labeled this one as solved.

Please, do not hesitate to open a new issue if you find any.

Regards
