### ISSUE TITLE
Use of node() tests inside XPath expressions

### ISSUE THREAD

**Issue by dartasensi** [INSPIRE-MIF/helpdesk-validator#144]
In XPath terminology, `node()` is one of the node test functions. It can detect any "child" node of an axis (ie. text, comment, element and processing instructions).
Another function is `text()`, more restrictive to only text nodes (ie. node with pure text content).
I found some use of this node() test that could be enforced with the use of text() instead.
Therefore, I propose to quickly identify all the occurrences of `node()` in the ETS definition files, and replace them where needed.

Kind regards,
Davide

**Comment by josemasensio** [comment]
Dear @dartasensi,
Thank you for your message. We will discuss this internally and once a decision is taken, we will come back to you with the solution.

Best regards.

**Comment by danielnavarrogeo** [comment]
Dear Davide,

Thank you for you comment. The tests has been modified for using text() instead of node().

You can check it in staging environment.

Regards
