### ISSUE TITLE
Planned release of fixes for metadata validation (TG 1.3 and TG 2.0) on production instance

### ISSUE THREAD

**Issue by ghost** [INSPIRE-MIF/helpdesk-validator#146]
Hello everyone,

I have one question regarding planned release of fixes for metadata validation against TG 1.3, TG 2.0 and XML-Validation on production instance. 

Some fixes regarding metadata validation are available on staging instance and marked for release planning like it can be seen in https://github.com/inspire-eu-validation/community/projects/1#column-6702146.

Such fixes are:

https://github.com/inspire-eu-validation/community/issues/128 
https://github.com/inspire-eu-validation/community/issues/87
https://github.com/inspire-eu-validation/community/issues/118
...

I have also noticed that some [links](https://github.com/inspire-eu-validation/ets-repository/blob/3a48d7ee1f08c12dd544ad4b7d780ceef0e4aade/metadata/1.3/iso/ets-md-iso-bsxets.xml#L1250) to ATS description in HTML Report when using master branch are dead (HTTP 404). These fixes are already on staging instance and in staging branch. 
It would be nice to have those fixes in master branch.

When can we expect such fixes on production instance and master branch? I couldn't find the information about that [here](https://github.com/inspire-eu-validation/community/blob/master/release_planning.md).

Thanks a lot in advance!

**Comment by josemasensio** [comment]
Dear @DeordD,
There is no certain date already. At the moment you can use the [staging instance](http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/) which has the latest bug fixed. On our [changelog](https://github.com/inspire-eu-validation/community/blob/master/changelog.md) and [releases plan](https://github.com/inspire-eu-validation/community/blob/master/release_planning.md), you can check the changes done in each version and future releases. 

Best regards.

**Comment by ghost** [comment]
Dear @josemasensio,

thanks a lot for the information.

Best regards.
