### ISSUE TITLE
Validation of Conditions applying to access and use

### ISSUE THREAD

**Issue by MichaelOstling** [INSPIRE-MIF/helpdesk-validator#147]
This element is according to IR metadata multiple, since we can have conditions for both access **and** use separated. This is also listed in the TG Metadata 2.0

> In the Tables 1 and 2 of [Regulation 1205/2008], Part C, the multiplicity of this element is one or more
> for both data sets and services.

But when reading the requirements for this element it is limited to 

> Conditions for access and use of the described resource shall be described using exactly **one** gmd:resourceConstraints/gmd:MD_LegalConstraints element.

Why is this element not according to the Implementing rules? Are there specific reasons for this?
I know its bit late to find this out now, but we didn't notice this until the validator started to report on this.

/Michael

**Comment by josemasensio** [comment]
Dear @MichaelOstling 

You can have multiple Conditions for Access and Use and Limitations on Public Access. For example for Limitations on Public Access you should have exactly one gmd:resourceConstraints/gmd:MD_LegalConstraints element and inside exactly one gmd:accessConstraints element and at least one gmd:otherConstraints element with one Anchor element which xlink:href attribute is a URL starting with "http://inspire.ec.europa.eu/metadata-codelist/LimitationsOnPublicAccess/" and postfixed with one of values of code list LimitationsOnPublicAccess of the TG MD Annex D.1., but you can have as many gmd:otherConstraints as you need to define the limitations. You can check the abstract test suites in these links:

- https://github.com/inspire-eu-validation/metadata/blob/2.0/common/limitations-on-public-access.md
- https://github.com/inspire-eu-validation/metadata/blob/2.0/common/conditions-for-access-and-use.md

Let us know if you need more clarifications.

**Comment by josemasensio** [comment]
Dear @MichaelOstling,
Does this solution work?

Best regards.

**Comment by MichaelOstling** [comment]
Hi,
My point is that conditions for Access and Use can be Multiple. 
I want to be able to handle both AccessConstraints AND UseConstraints
Each having their own otherConstraints
 
Limitation on Public Access is one type AccessConstraints targeting a specific usergroup "the Public"

So I think when reading the Implementing rules for metadata you should be able to handle
1 Limitations on public access
2 Use Constraints
3 Access Constraints

I see that some kind of simplification is made. Where the TG Metadata is diverting from the IR Metadata. 

Am I wrong or have there been a decision to make this simplification ?
  
Kind Regards
Michael

**Comment by josemasensio** [comment]
Dear @MichaelOstling,
There are only two restrictions:
1. [Limitations on Public Access](https://github.com/inspire-eu-validation/metadata/blob/2.0/common/limitations-on-public-access.md)
2. [Conditions for Access and Use](https://github.com/inspire-eu-validation/metadata/blob/2.0/common/conditions-for-access-and-use.md)

On Limitations on Public Access, you must use Access Constraint with codeListValue attribute with the value of "otherRestriction" and with at least one anchor with the URL starting with "http://inspire.ec.europa.eu/metadata-codelist/LimitationsOnPublicAccess/" and postfixed with one of values of code list LimitationsOnPublicAccess of the [TG MD](https://github.com/inspire-eu-validation/metadata/blob/2.0/common/README.md#ref_TG_MD) Annex D.1.

On Conditions for Access and Use instead, you need at least one Conditions for Access and Use that is formed by one Access Constraint or one Use Constraint that his codeListValue attribute with the value of "otherRestrictions" and at least one One Anchor element which xlink:href attribute is a URL starting with "http://inspire.ec.europa.eu/metadata-codelist/ConditionsApplyingToAccessAndUse/" and postfixed with one of the values of code list ConditionsApplyingToAccessAndUse of the [TG MD](https://github.com/inspire-eu-validation/metadata/blob/2.0/common/README.md#ref_TG_MD) Annex D.2. or a non-empty free text.

You can create as many Limitations on Public Access or Conditions for Access and Use element as you want as long as the conditions mentioned above are fulfilled. So, if you want to use handle both AccessConstraints and UseConstraints, at least one of them has to fulfil the Conditions for Access and Use; or use AccessConstraint for Limitations of Access Constraint and then UseConstraint for Conditions of Access and Use, but both of them have to fulfil the conditions mentioned. 

If you have any other question, please let us know.

Best regards.

**Comment by josemasensio** [comment]
Dear @MichaelOstling,

Was the explanation provided valid for you?

Best regards.

**Comment by MichaelOstling** [comment]
Yes, thanks. 
Let me look into our metadata and see how we might change our validation

**Comment by josemasensio** [comment]
Dear @MichaelOstling,

Glad to hear that! Please, do not close this issue, we will mark as solved.
Best regards.
