### ISSUE TITLE
Error loading INSPIRE Validator - Abstract and Executable Test Suites

### ISSUE THREAD

**Issue by bettyfrancisco** [INSPIRE-MIF/helpdesk-validator#15]
Good Moning,

I'm trying to open the page 'Test your data, services or metadata' however seems it doesn't work.
Whenever I click on 'Start a Test' the link don't upload any matter. http://inspire-sandbox.jrc.ec.europa.eu/etf-webapp/

Is there any problem with the site? Does anyone have the same problem?
Waiting for any feedback.

Best Regards,

**Comment by frcaldeira** [comment]
Hello Betty,

I have notice the same behavior all day. I think the server might be down.

Regards

**Comment by michellutz** [comment]
Thanks for raising the issue. The server is indeed down and we are having some issues to restart it (see etf-validator/etf-webapp#175).

Sorry for the inconvenience.

**Comment by weezery** [comment]
Hello,

 I have the same problem since Friday.

Regards

**Comment by michellutz** [comment]
We have resolved the issue. The validator is back up again.

Sorry again for the inconvenience. We will keep investigating what caused the problem.

**Comment by nppozar** [comment]
Thank you for resolving the issue, but there are still problem with executing tests: Test run initialization failure - error. Does anyone have the same problem maybe?
Regards,
Nina

**Comment by michellutz** [comment]
Dear @nppozar, please open a separate issue for the problems you are having with initialising tests, including relevant details (what kind of test suites, data, ...). Thanks.
