### ISSUE TITLE
Handling of redirects in validation of OperatesOn for Services

### ISSUE THREAD

**Issue by MichaelOstling** [INSPIRE-MIF/helpdesk-validator#150]
We have a question on how redirects are handled in Inspire ETF Validator 

We have changed our National CSW-adresss so that IF a agency is calling our old CSW at
https://www.geodata.se/geonetwork/srv/eng/csw?
It is automatically redirected to
https://www.geodata.se/geodataportalen/srv/eng/csw?
Through a http 302 redirect

We see now that in ETF validator that the redirects are not accepted in validator.

Is that a proper handling in the validation? We see the redirect is properly handled on our side.

The ETF validator returns error on rule OperatesON
![2019-11-09_11-25-39](https://user-images.githubusercontent.com/6397818/68527121-cb4eeb00-02e3-11ea-8eec-55c83abd3b6d.png)

Validation is done using Firefox 69.03

The validation is done on metadata according to TG 1.3 for the record
https://www.geodata.se/geodataportalen/srv/eng/csw-inspire-swe?request=GetRecordById&service=CSW&version=2.0.2&elementSetName=full&outputSchema=csw:IsoRecord&id=8df63b07-46e5-45bd-aa06-3f43248617a3

The validation testrun URL is at (Im not sure if this is persistently stored)
http://inspire.ec.europa.eu/validator/v2/TestRuns/EID2abb26b6-5f8c-4c7f-bd15-004260e72aa7.html

Michael Östling (SE) /Lantmäteriet

**Comment by josemasensio** [comment]
Dear @MichaelOstling,
Thank you for your message. We tried to access the URL that you provided, but it returned 
`<response>
<info>No 'request' parameter found</info>
</response>`.

Would you please let us know when everything is working properly so that we can review the problem?
Thank you.

Best regards.

**Comment by MichaelOstling** [comment]
Hi,
What URL did you try to access?

I just tested both
https://www.geodata.se/geodataportalen/srv/eng/csw-inspire-swe?request=GetRecordById&service=CSW&version=2.0.2&elementSetName=full&outputSchema=csw:IsoRecord&id=8df63b07-46e5-45bd-aa06-3f43248617a3
AND
http://inspire.ec.europa.eu/validator/v2/TestRuns/EID2abb26b6-5f8c-4c7f-bd15-004260e72aa7.html

They work fine.

Kind Regards
Michael

**Comment by josemasensio** [comment]
Dear @MichaelOstling,

We have just fixed this issue. There was a parameter that did not allow the redirection of any URL which we have changed to allow it. The change will be available soon at the [staging instance](http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/).

Best regards.

**Comment by juanpelegrina** [comment]
Dear @MichaelOstling

We have already reloaded staging instance so the solution implemented is ready for testing. We have internally tested and works as expected, could you verify it? we are planning a release soon and we intend to include this issue on this [milestone.](https://github.com/inspire-eu-validation/community/milestones).

Regards

**Comment by MichaelOstling** [comment]
Thanks, Now it works fine. The redirects are handled correct

/Michael

**Comment by ghost** [comment]
Dear @josemasensio ,

does it mean that INSPIRE-Validator can also handle more than two redirects?

For example:
http://domain1/ -> https://domain1/ -> https://domain2/

Thanks a lot in advance!

**Comment by josemasensio** [comment]
Dear @DeordD,

There should not be problem redirecting as long as redirection code is one of the following codes ``'301' '302' '303' '307'``.

Best regards.

**Comment by ghost** [comment]
Dear @josemasensio ,

thanks a lot again. 

I will test it on staging as soon I generate corresponding example. 

After problem reported from @MichaelOstling is available on production instance I will test it too.

**Comment by ghost** [comment]
Dear @josemasensio ,

I have one more question. 

> 
> 

> 
> There should not be problem redirecting as long as redirection code is one of the following codes `'301' '302' '303' '307'`.
>

Does your statement applies to both production and staging instance? 

Or your statement will be also valid for production environment after the fix is deployed on production instance?

Thanks in advance.

**Comment by josemasensio** [comment]
Dear @DeordD,

The statement is only valid for [staging instance](http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/) because the master branch has the redirections blocked. 
At least until the deployment of the staging branch against master. Once the deployment is done, there should be no differences between them.

Best regards.

**Comment by MichaelOstling** [comment]
What date  have you estimated to add this enhancements for redirections into the production server ?
Michael
