### ISSUE TITLE
Tagging one dataset with more than one priority dataset keywords.

### ISSUE THREAD

**Issue by grigoriouelena** [INSPIRE-MIF/helpdesk-validator#152]
Has anyone tried to put more than one priority dataset keyword in one dataset metadata file?
I am not very familiar with the xml schema, so I cannot put the elements properly in the metadata file. 

I tried to repeat the whole gmd:descriptiveKeywords element but the validator returns an error for the multiple thesaurus declaration (the keywords originating from one thesaury should be grouped).

Any suggestions or examples please?

Thanks in advance.

Elena

**Comment by fabiovin** [comment]
Hi @grigoriouelena,
in the _Dataset metadata example_ available [here](https://inspire.ec.europa.eu/id/document/tg/metadata-iso19139/2.0/examples) there is an example of how to encode two (o more) keywords for the same thesaurus.

```
      <gmd:descriptiveKeywords>
        <gmd:MD_Keywords>
          <gmd:keyword>
            <gmx:Anchor xlink:href="https://www.eionet.europa.eu/gemet/en/concept/4614">land development</gmx:Anchor>
          </gmd:keyword>
             <gmd:keyword>
            <gmx:Anchor xlink:href="https://www.eionet.europa.eu/gemet/en/concept/11323">land use regime</gmx:Anchor>
          </gmd:keyword>
          <gmd:thesaurusName>
            <gmd:CI_Citation>
              <gmd:title>
                <gmx:Anchor xlink:href="https://www.eionet.europa.eu/gemet/en/concept/13102">GEMET - Concepts, version 4.1.3</gmx:Anchor>
              </gmd:title>
              <gmd:date>
                <gmd:CI_Date>
                  <gmd:date>
                    <gco:Date>2019-01-28</gco:Date>
                  </gmd:date>
                  <gmd:dateType>
                    <gmd:CI_DateTypeCode codeList="http://standards.iso.org/iso/19139/resources/gmxCodelists.xml#CI_DateTypeCode" codeListValue="publication">Publication</gmd:CI_DateTypeCode>
                  </gmd:dateType>
                </gmd:CI_Date>
              </gmd:date>
            </gmd:CI_Citation>
          </gmd:thesaurusName>
        </gmd:MD_Keywords>
      </gmd:descriptiveKeywords>
```

**Comment by juanpelegrina** [comment]
Dear Elena, 

have you managed to add two keywords to your dataset metadata file? please let us know if you have any questions.

Regards

**Comment by grigoriouelena** [comment]
Sorry for the late reply.

Thanks for the prompt response.
I had followed the example instructions but unfortunately the file does not pass the tests of  the validator.

I get errors for the following assertions:
http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/v2/TestRuns/EID5289b3ad-6250-40f8-b8aa-c0430bd39847.html?lang=en#EID46111d52-6dfe-44bc-8690-119c0d3c9a2a
http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/v2/TestRuns/EID5289b3ad-6250-40f8-b8aa-c0430bd39847.html?lang=en#EIDb8909d03-cfa5-4633-a729-49830151df47 (please ignore, it is discussed [here](https://github.com/inspire-eu-validation/community/issues/148) 
http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/v2/TestRuns/EID5289b3ad-6250-40f8-b8aa-c0430bd39847.html?lang=en#EIDde51ecd4-0667-4cdc-8dd9-415f8b81c1d9

The file I am testing is
[PS.ProtectedSitesNatura2000.zip](https://github.com/inspire-eu-validation/community/files/3840766/PS.ProtectedSitesNatura2000.zip)

**Comment by josemasensio** [comment]
Dear @grigoriouelena,

Thank you for your message. Unfortunately, when we fix an issue and we merge to staging, we have to reload the instance and all the reports are deleted. 

Please, could you use our [contribution guidelines](https://github.com/inspire-eu-validation/community/blob/master/contribution_guidelines.md#how-to-report-an-issue) in order to help us to locate where the problem is? Thank you.

Best regards.

**Comment by fabiovin** [comment]
Dear @grigoriouelena ,

I had a look at your xml file and I noticed that you inserted twice the _title_ for the _thesaurusName_.

```
<gmd:thesaurusName>
	<gmd:CI_Citation>
		<gmd:title>
			<gmx:Anchor xlink:href="http://inspire.ec.europa.eu/metadata-codelist/PriorityDataset">INSPIRE priority data set</gmx:Anchor>
		</gmd:title>
		<gmd:title>
			<gmx:Anchor xlink:href="http://inspire.ec.europa.eu/metadata-codelist/PriorityDataset">INSPIRE Priority data set</gmx:Anchor>
		</gmd:title>
```


If you remove one of them the metadata validates (http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/v2/TestRuns/EID5f71dcae-7db5-435c-b7e5-34820db46038.html).

**Comment by grigoriouelena** [comment]
Thanks!
Sorry for the extra effort.
