### ISSUE TITLE
Writing proper OGC URLs

### ISSUE THREAD

**Issue by MichaelOstling** [INSPIRE-MIF/helpdesk-validator#153]
Hi,
I guess we should now better, but I have a question for setting a proper URLs when setting the adress in ResourceLocator
In our Swedish Profile we use the protocol element for online links to define if a service is a WFS or WMS.
So we have nor been strict when users write their URLs . It has been accepted to add like:
http://gis-services.metria.se/arcgis/rest/services/nv/InspireNV_NVR/MapServer/exts/InspireView/service?

But I see now in reference validator  it is giving a warning since it returns 'text/html" instead of text/xml

Are the rules so that a full GetCapabilities request must be given for a online-URL like
http://gis-services.metria.se/arcgis/rest/services/nv/InspireNV_NVR/MapServer/exts/InspireView/service?request=getcapabilities&version=1.3.0&Service=WMS

This is the case for metadata-record
https://www.geodata.se/geodataportalen/srv/eng/csw-inspire-swe?request=GetRecordById&service=CSW&version=2.0.2&elementSetName=full&outputSchema=csw:IsoRecord&id=8df63b07-46e5-45bd-aa06-3f43248617a3

Kind Regards
Michael

**Comment by josemasensio** [comment]
Dear @MichaelOstling,


Thank you for your message. Please, could you tell us where are you getting this error message? We have tried to reproduce the error but we could not.

Best regards.

**Comment by josemasensio** [comment]
Dear @MichaelOstling,

Please, could you tell us where are you getting this error message? We have tried to reproduce the error but we could not.

Best regards.

**Comment by josemasensio** [comment]
Dear @MichaelOstling 

Without your feedback, we could not proceed to fix the issue. We will be waiting for a week, but if there is no feedback, we will close the issue.
Thanks for understanding.

Best regards.

**Comment by josemasensio** [comment]
Dear @MichaelOstling,

Please, could you tell us where are you getting this error message? We have tried to reproduce the error but we could not.

Best regards.

**Comment by alitka** [comment]
The warning message is related to the test "Conformance class: INSPIRE Profile based on EN ISO 19115 and EN ISO 19119" > Service tests > md-iso.d.2: Service linkage:

`The metadata record set has 1 record(s) with errors for this assertion.
XML document 'csw-inspire-swe.xml', record '8df63b07-46e5-45bd-aa06-3f43248617a3': The metadata record has a linkage property, which references a resource with media type 'text/html;charset=utf-8' at 'http://gis-services.metria.se/arcgis/rest/services/nv/InspireNV_NVR/MapServer/exts/InspireView/service?' which is not one of the media types indicating an INSPIRE network service. Please review the resource to check that it meets the linkage requirements; specifically, if the resource is a webpage, check that it provides further instructions or a client application that directly accesses the service.`

`XML document 'csw-inspire-swe.xml', record '8df63b07-46e5-45bd-aa06-3f43248617a3': The metadata record has a linkage property, which references a resource with media type 'text/html' at 'http://skyddadnatur.naturvardsverket.se/' which is not one of the media types indicating an INSPIRE network service. Please review the resource to check that it meets the linkage requirements; specifically, if the resource is a webpage, check that it provides further instructions or a client application that directly accesses the service.`

`XML document 'csw-inspire-swe.xml', record '8df63b07-46e5-45bd-aa06-3f43248617a3': The metadata record has a linkage property, which references a resource with media type 'text/html; charset=utf-8' at 'http://www.naturvardsverket.se/Var-natur/Skyddad-natur/' which is not one of the media types indicating an INSPIRE network service. Please review the resource to check that it meets the linkage requirements; specifically, if the resource is a webpage, check that it provides further instructions or a client application that directly accesses the service.`

**Comment by danielnavarrogeo** [comment]
Dear @MichaelOstling, @alitka 

The ETS is checking that the provided link in the ResourceLocator element responds with a wms:WMS_Capabilities, wcs:Capabilities, sos:Capabilities or atom:feed root element. 

If you do not provide the parameters with the url, and only the endpoint, the service responds an html. For instance:
* The link http://gis-services.metria.se/arcgis/rest/services/nv/InspireNV_NVR/MapServer/exts/InspireView/service responds a html file.
* While the url with the parameters http://gis-services.metria.se/arcgis/rest/services/nv/InspireNV_NVR/MapServer/exts/InspireView/service?request=getcapabilities&version=1.3.0&Service=WMS responds a xml WMS_Capabilities file.

Then, when you set the resourceLocator like in the first case, you are getting that a manual test is required. This does not mean that the test fails, just that it cannot be tested automatically.

Therefore, we think this is not an issue. You can get rid of the manual test by providing the full url with parameters, but you are still not getting failed result if you provide the url without them.

Regards

**Comment by MichaelOstling** [comment]
Hi sorry, for not replying on this before.
Someway it has passed me.

Thanks for clarifying.
I think the message was shown when validating metadata for the view-service.

I think we will add some processing in our CSW-endpoint and add the proper capabilities -parameters. So the URL is processed properly.
I think the behavior differs in for different vendors. I think Geoserver and Mapserver have other default behaviors.

Regards
Michael

**Comment by danielnavarrogeo** [comment]
Thank you @MichaelOstling for your feedback.

Regards
