### ISSUE TITLE
Staging instance: Example metadata record provided in community repo isn't valid against TG 2.0

### ISSUE THREAD

**Issue by ghost** [INSPIRE-MIF/helpdesk-validator#154]
**Problem description:**

I am currently using INSPIRE-Validator in order to check one service-metadata XML. 
I thought it was a good idea to compare [service-metadata](https://github.com/inspire-eu-validation/community/blob/master/examples/NetworkService_WMS_metadata_2.0_example) against my metadata record.

I validated it using [staging instance](http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/) and it is stated that reference-metadata record is not valid.

**Input**

[NetworkService_WMS_metadata_2.0_example.zip](https://github.com/inspire-eu-validation/community/files/3846619/NetworkService_WMS_metadata_2.0_example.zip)

**Steps to reproduce:**

1. download the metadata record https://raw.githubusercontent.com/inspire-eu-validation/community/master/examples/NetworkService_WMS_metadata_2.0_example 
2. Validate XML against Conformance Class 4: 'INSPIRE Network Services metadata' 
3. Check the result for Conformance Class 3
4. Metadata record is not valid against Conformance Class 3 
http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/v2/TestRuns/EID4e11d287-de27-441f-a25d-a5c57de735bb.html 

**Expected result:**

1. Metadate record should be valid against all Conformance Classes for services

**Validation result** 
![ValidationResult_Staging_Reference_MD_Service](https://user-images.githubusercontent.com/38787131/68860194-4ef44780-06e9-11ea-8b39-dddd60619706.jpg)

What am I doing wrong? Did someone else also had this problem?

Thanks a lot in advance!

Browser: Firefox Quantum 68.2.0esr (64-Bit)

**Comment by josemasensio** [comment]
Dear @DeordD,

Thank you for your message. There is an error on the validator. We will come back to you when the problem is solved.

Thank you.

**Comment by MarcoMinghini** [comment]
The same error was reported last week (see [this comment in another issue](https://github.com/inspire-eu-validation/community/issues/111#issuecomment-549840323)) and appeared in all metadata tests, before being solved.

**Comment by ghost** [comment]
Dear @MarcoMinghini ,

thanks a lot for the information. 

I am always trying to check if the problem is already described. 

This time I failed. :-1: 

Kind regards

**Comment by josemasensio** [comment]
Dear @DeordD,

We have modified the test fixing the error that blocked the test to execute. You can see the modifications at the [corresponding pull request](https://github.com/inspire-eu-validation/ets-repository/pull/365).
The changes are available at [staging instance](http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/).

Best regards.

**Comment by ghost** [comment]
Thanks a lot for nice support!

I have validated metadata record https://github.com/inspire-eu-validation/community/files/3846619/NetworkService_WMS_metadata_2.0_example.zip again against Conformance Class 4: 'INSPIRE Network Services metadata'. 

The problem is solved. 

HTML Report:
http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/v2/TestRuns/EIDb266261c-a6f2-4e76-8c88-12a4c9937798.html

Screenshot:
![grafik](https://user-images.githubusercontent.com/38787131/68865945-ed85a600-06f3-11ea-85d3-af927759f45a.png)

In my opinion this Issue can be closed.
