### ISSUE TITLE
Staging: Reports don't show up after click on "Test reports" 

### ISSUE THREAD

**Issue by ghost** [INSPIRE-MIF/helpdesk-validator#155]
**Description:**
Test reports aren't listed after click on "Test reports" tab.

**Steps to reproduce:**
1. http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/#test-reports
2. Reports don't show up
![test-reports-staging](https://user-images.githubusercontent.com/38787131/68928279-fb860600-0789-11ea-9c51-2073026e0ea0.jpg)

**Expected result:**
All reports should be shown in GUI.

**Browser**
Firefox Quantum: 68.2.0esr (64-Bit)

**Comment by josemasensio** [comment]
Dear @DeordD,

When a new feature is added to the staging environment, all the test reports that were recorded are removed because we have to remove the current and deploy again.

Best regards.

**Comment by ghost** [comment]
Dear @josemasensio ,

thanks a lot for the response.

I have validated some metadata records 10 minutes ago and I expected that those will show up.

When i validate now, should reports be shown?

**Comment by MarcoMinghini** [comment]
I have just validated a metadata record and the test report is correctly listed in the test reports page.
Perhaps the staging instance was re-deployed this morning?

**Comment by carlospzurita** [comment]
The instance was re-deployed to add some fixes on the ETS. This could had solved the issue on the reports disapeareance by itself.

**Comment by ghost** [comment]
Dear @MarcoMinghini ,

I have validated metadata records now and the report is generated and displayed in "Test reports" tab.

Thanks a lot for helping. 

In my opinion this issue can be closed.
