### ISSUE TITLE
Upload not working

### ISSUE THREAD

**Issue by danielmoraes09** [INSPIRE-MIF/helpdesk-validator#157]
Upload is not working in the website. Anyone else?

**Comment by juanpelegrina** [comment]
Dear @danielmoraes09 
We have deployed a new release today, so hopefully, you should be able to upload now. Please try again and let us know if you are still having problems
Regards

**Comment by josemasensio** [comment]
Dear @danielmoraes09,

Are you still having this issue?

Best regards.
