### ISSUE TITLE
Link to ETS-Repository used in INSPIRE-Validator production instance 

### ISSUE THREAD

**Issue by ghost** [INSPIRE-MIF/helpdesk-validator#159]
First of all, thanks a lot for providing a new version of INSPIRE-Validator with new functionalities and bug-fixing! 

I have questions regarding usage of ets-repository provided [here](https://github.com/inspire-eu-validation/ets-repository). 

We are currently using this repository (master branch) for our metadata-validator based on INSPIRE Conformance Classes for metadata records. 

And finally my questions:
1. Could you please provide a link to ets-repository which is currently used in INSPIRE-Validator production instance?
2. If this isn't already happened, do you plan to update ets-repository master branch?

Thanks in advance!

**Comment by josemasensio** [comment]
Dear @DeordD,

Thank you for your message.
1. Currently, the ETF Validator is pointing to [v1.0.8](https://github.com/inspire-eu-validation/ets-repository/tree/v1.0.8) branch on ets-repository.
2. We will discuss to merge on incoming days.

Best regards.

**Comment by ghost** [comment]
Dear @josemasensio ,

> We will discuss to merge on incoming days.

Are there any news regarding this topic?

Best regards.

**Comment by danieluct** [comment]
I have tried using that branch however the master branch of the ETF validator is unable to load the tests related to WMS or CSW. On a quick check, the tests that fail to load use soapui-version 5.4.0, while working ones use 5.3.0. Is the provided ETF validator also using a custom branch?

**Comment by danielnavarrogeo** [comment]
Dear @danieluct 

The last developments that add support to the test drivers for WMS and CSW, among others, are not yet included in the ETF master branch. A most updated branch in the ETF repository is ['next'](https://github.com/etf-validator/etf-webapp/tree/next). But it still lacks support for CSW.

However, you may want to use the docker image provided in the [release](https://github.com/inspire-eu-validation/community/releases) which is in the same point of development as the official INSPIRE reference validator.

Regards

**Comment by ghost** [comment]
Dear @josemasensio,

any news concernig discussion to merge [release branch](https://github.com/inspire-eu-validation/ets-repository/tree/v2020.1.2) into master branch?

Kind regards

**Comment by MarcoMinghini** [comment]
Dear @DeordD, this was done yesterday, see https://github.com/inspire-eu-validation/ets-repository/pull/441

**Comment by ghost** [comment]
Dear @MarcoMinghini ,

thanks a lot for the information.

Does it mean that one only have to rely on master branch in oder to trigger inspire-ets-repository update process?

Kind regards.

**Comment by danielnavarrogeo** [comment]
Dear @DeordD 

You may use master branch in order to use the latest stable release. Or, use a specific release branch to validate using a specific version of the validator.

Regards
