### ISSUE TITLE
Test suites executing issue

### ISSUE THREAD

**Issue by nppozar** [INSPIRE-MIF/helpdesk-validator#16]
Hello,

I'm having problem with executing test suites, I tried different ones with different data (including data which was successfully tested before - on test suite Protected sites for example).

Today I wanted to test zipped GML files of several data sets in test suite "Interoperable data sets in GML (Guidelines for the Encoding of Spatial Data version 3.3)" and test suite for "Administrative units" and I'm getting error (see the picture below).

![issue_etf](https://user-images.githubusercontent.com/45449924/49207883-883b8680-f3b6-11e8-8201-7ceb0f4d3ba9.png)

I also tried using tests in diferent internet browsers (Chrome, Mozilla, IE).

Thank you for your help!

Best regards,

Nina

**Comment by MarcoMinghini** [comment]
Thank you for reporting the problem, we are currently working to find a solution. We will keep you updated on this thread.

**Comment by nppozar** [comment]
Thank you for quick response, validator is working now. 
All the best,
Nina
