### ISSUE TITLE
md-iso.d.3: Coupled resource - URL as coupled resource expected (TG 1.3)

### ISSUE THREAD

**Issue by ghost** [INSPIRE-MIF/helpdesk-validator#163]
I have tested some metadata records in prodction instance against TG 1.3 Conformance Classes. 

Here is the report.
http://inspire.ec.europa.eu/validator/v2/TestRuns/EIDcac78783-ab4d-4b1a-922f-d6061432a014.html

Following message is shown:
The metadata record has a linkage property, but it references a resource at 'http://www.lgl-bw.de/10451069-e255-4698-9795-22195b2c79df' that cannot be accessed. The HTTP status code when requesting the resource is: '404'. A status code of '200' is expected. 

It seems that only URL in operatesOn is permitted. But, in Implementing Rules URIs are allowed.

**Comment by josemasensio** [comment]
Dear @DeordD,

Thank you for your message. Please, could you provide us with the metadata and the specific test that you have been testing? Thank you.

Best regards.

**Comment by ghost** [comment]
Dear @josemasensio ,

here is one service-metadata-record:
[md-iso.d.3 Coupled resource-URI.zip](https://github.com/inspire-eu-validation/community/files/3890924/md-iso.d.3.Coupled.resource-URI.zip)

I have validated it again and here is the report:
http://inspire.ec.europa.eu/validator/v2/TestRuns/EID0cefb9e3-d14a-435d-bccc-24396d25236f.html

P.S. Dataset- and series-metadata don't have this problem. It seems that URI is allowed there.

**Comment by josemasensio** [comment]
Dear @DeordD,

We were investigating and the problem is with the URI that returned 404, because the validator is expecting following error codes: `200, 204, 301, 302, 303, 307`. Please, can you run again the test or provide us with a working URI? Thank you.

Best regards.

P.S.: This issue is related with #150.

**Comment by ghost** [comment]
Dear @josemasensio ,

we only have URI as an identifier of the resource and in our case it isn't a locator. So it is expected that error code 404 will be returned.

My question is: Does URI has to be locator according to Implementing Rules and Technical Guidance 1.3 or URI as unique identifier (without pointing to the XML record) is also sufficient?

Best regards and thanks a lot for information given.

**Comment by josemasensio** [comment]
Dear @DeordD,

According to the [Coupled Resource ATS](https://github.com/inspire-eu-validation/metadata/blob/1.3/iso-19115-19119/coupled-resource.md), in the `SV_ServiceIdentification` element should be an HTTP URI that when retrieved using HTTP GET should return the metadata document describing the dataset exposed by this service.

Let us know if you have more questions.
Best regards.

**Comment by ghost** [comment]
Dear @josemasensio ,

thanks a lot for additional information.

> According to the Coupled Resource ATS, in the SV_ServiceIdentification element should be an HTTP URI that when retrieved using HTTP GET should return the metadata document describing the dataset exposed by this service.

In our opinion this is not stated in Implementing Rules respectively Technical Guidance Document 1.3. 

Can you please check if my statement above is correct?

If yes, than this should be fixed. 

Thanks in advance.

**Comment by josemasensio** [comment]
Dear @DeordD,

On the [TG 1.3](https://inspire.ec.europa.eu/documents/Metadata/MD_IR_and_ISO_20131029.pdf), at section 2.2.6 Coupled resource table, the domain is defined as:
> A unique resource identifier or locator (URL) of the MD_DataIdentification object.

So the validator is expecting a URI or a URL of the MD_DataIdentification object then can check that there is a metadata document describing the dataset exposed by this service.

Thanks.

**Comment by stbach** [comment]
Dear all,

interesting discussion. As stated in Implementing Rules that URIs are allowed the INSPRIE Validator shall also support the requirement. Is bug fixing already planned?

**Comment by josemasensio** [comment]
Dear @stbach,

Thank you for your message. In our interpretation of the TG, both URLs and URIs are allowed to the validator. The only requirement here is that they must point to an MD_DataIdentification object. In short, the link can not be null or can not return 404, therefore, there is not a bugfix planned   

In any case, the transition period from MD version 1.3 to version 2.0, will end on the 19 of December. For this reason, support for MD TG 1.3 will finish during the incoming days.

Please, let us know if you have any other question.
Best regards.
