### ISSUE TITLE
Could not validate CSW for url https://catalogue.creodias.eu/csw?request=GetCapabilities&service=CSW&version=2.0.2

### ISSUE THREAD

**Issue by snicholas** [INSPIRE-MIF/helpdesk-validator#168]
Trying to validate the url 

[https://catalogue.creodias.eu/csw?request=GetCapabilities&service=CSW&version=2.0.2](https://catalogue.creodias.eu/csw?request=GetCapabilities&service=CSW&version=2.0.2) 

the validator replies with:

Check the availability of the server. The URL could not be processed due to a server error: Returned HTTP status code was '500' (Internal Server Error )

Also tried calling the http version instead of the https 

[http://catalogue.creodias.eu/csw?request=GetCapabilities&service=CSW&version=2.0.2](http://catalogue.creodias.eu/csw?request=GetCapabilities&service=CSW&version=2.0.2) 

and this time the error is:

The test object type could not be determined. Check the uploaded / referenced resource. Uploaded files may only contain test data and no other files. If the problem persists, please contact the ETF system administrator of the server.

Attached the xml file from the above url.

Thanks,
    Nicholas
[csw.zip](https://github.com/inspire-eu-validation/community/files/3900392/csw.zip)

**Comment by danielnavarrogeo** [comment]
Dear @snicholas 

Thank you for the message. We are analyzing the issue.

Regards

**Comment by carlospzurita** [comment]
Dear @snicholas 
This is happening because the format of the URL with the parameters of the query can't be detected on the service respone. We need to check the rules on the validator to see if we need to crete a bugfix for this. We will keep you posted on this.

**Comment by danielnavarrogeo** [comment]
Dear @snicholas 

Looking at the capabilities document, we have seen many references to {csw.endpointaddress}. That is causing that the validator is not able to check the object type.

These url's should be set properly.

Regards

**Comment by carlospzurita** [comment]
Dear @snicholas 
We are checking the issue, and we detected that there is a redirection from the HTTP request to the HTTPS. The validator needs to be able to access the service through an HTTP interface. Right now, it is getting a 301 response code with the redirection, and can't detect the namespace and local name in the capabilities document.

You should set up the CSW service through a HTTP endpoint.

**Comment by snicholas** [comment]
Dear all,
    thank you for your effort. I will forward your insights to the owner.

Best,
    Nicholas
