### ISSUE TITLE
keywords from GEMET Thesaurus

### ISSUE THREAD

**Issue by manilly** [INSPIRE-MIF/helpdesk-validator#169]
Dear Validtor-Team,

when trying to validate atteched dataset, the ETF validator states following error:
`The metadata record set has 1 record(s) with errors for this assertion.
XML document '807bb1c4-921b-4915-8a90-0133a464e11b.xml', record '807bb1c4-921b-4915-8a90-0133a464e11b': A dataset (series) metadata record that uses 'GEMET - INSPIRE themes, version 1.0' as the title of the vocabulary that belongs to a block of descriptive keywords must have one keyword in this block that is a language specific or language neutral code value from the codelist at http://inspire.ec.europa.eu/theme. The detected keywords are: Bewirtschaftungsgebiete/Schutzgebiete/geregelte Gebiete und Berichterstattungseinheiten; Laubwald; Nadelwald; Wald; Forstökonomie; Forstwirtschaft; Waldwirtschaft; Saatgut.`

Inside the metadata there is a correct block with INSPIRE themes:
![image](https://user-images.githubusercontent.com/45065613/69861158-0d8e9b00-1298-11ea-9629-f52655598936.png)

And also keywords from thesaurus GEMET - Concepts, version 3.1
![image](https://user-images.githubusercontent.com/45065613/69861185-226b2e80-1298-11ea-93d0-2607ee7ae082.png)

Do you know what the problem is there, respectively is it a bug in etf validtor?

Thanks, Manuel

[807bb1c4-921b-4915-8a90-0133a464e11b.xml.txt](https://github.com/inspire-eu-validation/community/files/3904653/807bb1c4-921b-4915-8a90-0133a464e11b.xml.txt)

**Comment by alitka** [comment]
I can confirm the findings from @manilly .
You only can avoid this error, when you skip the word "GEMET" from the "GEMET - Concepts, version 3.1"-thesarus, but this couldn't be the solution!

I checked the ETS description and the test "md-iso.f.1: Dataset keyword" should only search for the term 'GEMET - INSPIRE themes, version 1.0' in the DescriptiveKeywords:

see ATS-snippet = 
> "The test first checks if a descriptiveKeywords block exists with vocabulary title (identified via gmd:thesaurusName/*/gmd:title/*/text()) **equal to 'GEMET - INSPIRE themes, version 1.0'**. If such a keyword block exists, then at least one keyword must be equal to one of the codes from the http://inspire.ec.europa.eu/theme codelist - either a language neutral code or one of the language specific code titles provided by the INSPIRE registry."

see ETS-snippet = 
`let $THEMES_TITLE := 'GEMET - INSPIRE themes, version 1.0'`
`let $relevantDescriptiveKeywordsBlocks := $record/gmd:identificationInfo[1]/*/gmd:descriptiveKeywords/*[gmd:thesaurusName/*/gmd:title/*/text() = $THEMES_TITLE]
`

**Comment by josemasensio** [comment]
Dear @manilly, @alitka,

As agreed in issue #106, the test was relaxed to check that the title contains any word from the "GEMET - INSPIRE themes, version 1.0" sentence with the purpose that it would validate in all languages. We realized that all languages must have to include "GEMET" in their sentence, so the test is expecting that the word is included in the sentence to validate.

In addition, we would like to remind you that support for metadata version 1.3 ends on the 19th of this month. For this reason, we recommend that you start using version 2.0, as it will still be supported.

Best regards.

**Comment by danielnavarrogeo** [comment]
Dear @manilly and @alitka 

A bug was found related with this issue and it has been already [solved](https://github.com/inspire-eu-validation/ets-repository/pull/400).

Now the test checks that at least one keyword from the thesaurus 'GEMET - INSPIRE themes, version 1.0' is provided. As stated in https://github.com/inspire-eu-validation/community/issues/106#issuecomment-532224298

Therefore, the test passes now when the thesaurus 'GEMET - Concepts, version 3.1' is provided additionally.

The bugfix is currently deployed in [staging](http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/).

Regards

**Comment by MarcoMinghini** [comment]
Before marking the issue as 'solved', @manilly / @alitka can you test the solution in the staging instance and confirm that it solved the problem? Thank you.

**Comment by manilly** [comment]
@MarcoMinghini @danielnavarrogeo 
tested on staging - works for us now (tested with same MD as mentioned in inital comment
thanks

**Comment by danielnavarrogeo** [comment]
Thank you @manilly for testing the solution.
