### ISSUE TITLE
Validation of namespace URI

### ISSUE THREAD

**Issue by AndersOstmanNovogit** [INSPIRE-MIF/helpdesk-validator#170]
Hi,

I am currently working on transforming Land Cover Data to INSPIRE, using HALE, on request of a country outside EU. When validating the GML file, I get 4 requests for manual inspection. I have a question about the fourth request.

It is about http://inspire.ec.europa.eu/validator/v2/TestRuns/EIDf587a4ee-e137-422c-95a9-2abbce2b9b74.html?lang=sv#, or requirements of namespaces to be more precise. 

All schemas being referenced are either from inspre, tc211, w3c, or interactive instruments. (Clemens).

The GML file is also making reference to a national Nomenclature, not registered in the INSPRE register, but that should be allowed.

Why do I get a request for manual inspection? Any comments from You?

Kind regards
Anders Östman

**Comment by danielnavarrogeo** [comment]
Dear @AndersOstmanNovogit,

The manual tests shown in the INSPIRE validator are shown when the validator is not able to validate automatically a requirement. This manual checks are required always, no matter the input.

For every manual test a description is provided in the Test Report. For instance, in 'gmlas.a.2: Modelling of additional spatial object types' test:

> Inspect the XML Schema namespace of each feature element. If a namespace URI does not start with "http://inspire.ec.europa.eu/schemas/" or "urn:x-inspire:specification:gmlas:" it is not one of the approved INSPIRE application schema namespaces. Review the extension documentation for the identified namespaces to check that any extensions do not overlap with the spatial object types and associated data types and enumerations that are defined in Annexes II, III and IV of the Implementing Rule.

From the validator perspective, your test status is PASSED.

Kind regards

**Comment by dperezBM** [comment]
Dear @AndersOstmanNovogit,

Thank you very much for your question. We hope that the answer you were offered at the time was to your convenience. 

Please feel free to open another issue if necessary.

Best regards.
