### ISSUE TITLE
Proposal for a session/workshop on the INSPIRE Conference in Dubrovnik 2020

### ISSUE THREAD

**Issue by alitka** [INSPIRE-MIF/helpdesk-validator#174]
Dear @MarcoMinghini and all,

Is there anyone interested in a joint session or workshop on the re-use of the INSPIRE Reference Validator? 

As you might know, we are currently developing a new version of our national validator (GDI-DE Testsuite) which will include the conformance classes of the INSPIRE Reference Validator. Likely, the new GDI-DE Testsuite will be launched before the INSPIRE Conference in Dubrovnik (scheduled release is the 1st quarter 2020). Other member states might have similar activities or future plans to re-use the INSPIRE Reference Validator in their own testing environments (see also [#162](https://github.com/inspire-eu-validation/community/issues/162)). Thus, it could be worthwhile for all to organise a session or workshop on the re-use of the INSPIRE Reference Validator and share experiences ("lessons learned") on this topic. We would be pleased to hear your feedback and if you’re interested to contribute to such a session.

Best regards,
Anja und Daniela

**Comment by danielnavarrogeo** [comment]
Dear @alitka 
Thank you for your comment. We would like to keep this space strictly for INSPIRE validator issues and to promote the use of the forum for any other related topic with INSPIRE. 

Then, I encourage you to open this discussion in the forum: https://inspire.ec.europa.eu/forum

Regards

**Comment by MarcoMinghini** [comment]
Dear @alitka and Daniela,
no problem to discuss this here.

We would be interested in participating in such a session and we encourage you to organize it (as you know, both sessions and talks have to be proposed before the submission deadline). We are available to submit a talk on the latest news and new features of the INSPIRE Validator, but then we suggest that the focus of the session is on experiences and lessons learnt from the use/re-use of the Validator at the national level.

So can you try to involve others (e.g. those who replied in #162) and organise the session? You may also want to use the Community Forum to discuss about this.

Best,
Marco

**Comment by alitka** [comment]
Thanks @danielnavarrogeo and @MarcoMinghini for pointing us towards the INSPIRE Community Forum. I opened a discussion on the platform, please see: [INSPIRE Community Forum - Proposal for a session/workshop on the INSPIRE Conference in Dubrovnik 2020](https://inspire.ec.europa.eu/forum/discussion/view/264016/proposal-for-a-sessionworkshop-on-the-inspire-conference-in-dubrovnik-2020).
