### ISSUE TITLE
TimePeriod Validation incorrect

### ISSUE THREAD

**Issue by Michael-81** [INSPIRE-MIF/helpdesk-validator#176]
The error output in the TimePeriod element is not correct. Modeling with Time Period is allowed.
Also the specification with a date time with time zone is correct according to ISO.

> "Technical Guidelines for the implementation of INSPIRE dataset and service metadata based on
ISO/TS 19139:2007" Page 20 

`<gmd:temporalElement>
        <gmd:EX_TemporalExtent uuid="ced59a10-aeee-4781-a8e3-121a9406e97f">
<gmd:extent>
<gml:TimePeriod gml:id="w8218aaac13ac27ab1aaa" frame="">
<gml:beginPosition>2007-12-04T08:00:00+01:00</gml:beginPosition>
<gml:endPosition>2007-04-13T16:15:00+02:00</gml:endPosition>
</gml:TimePeriod>
</gmd:extent>
</gmd:EX_TemporalExtent>
</gmd:temporalElement>`

Testclass:
Common Requirements for ISO/TC 19139:2007 based INSPIRE metadata records.

Test:
http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/v2/TestRuns/EID68b2e431-1956-4fad-90b4-7e941d5d3d6f.html

Element failure:
The metadata record set has 1 record(s) with errors for this assertion.
XML document 'GetRecordByIdServant$Get.xml', record '8f2f1de1-83c7-4459-85b5-eb45d88af0f7': 'Validation failed: 814:73: cvc-complex-type.2.4.a: Invalid content was found starting with element '{"http://www.opengis.net/gml":TimePeriod}'. One of '{"http://www.opengis.net/gml/3.2":AbstractTimePrimitive}' is expected.Validation failed: http://www.isotc211.org/2005/gmd/gmd.xsd, 2:35: s4s-elt-character: Non-whitespace characters are not allowed in schema elements other than 'xs:appinfo' and 'xs:documentation'. Saw '301 Moved Permanently'.Validation failed: 814:73: cvc-complex-type.2.4.a: Invalid content was found starting with element '{"http://www.opengis.net/gml":TimePeriod}'. One of '{"http://www.opengis.net/gml/3.2":AbstractTimePrimitive}' is expected.'.

**Comment by danielnavarrogeo** [comment]
Dear @Michael-81 
We are analyzing this issue. We will keep you posted.
Regards

**Comment by josemasensio** [comment]
Dear @Michael-81,
As discussed on the issue #92, there is a wrong attribute in the header, please make the following substitution:
- xmlns:gml="http://www.opengis.net/gml/ --> xmlns:gml="http://www.opengis.net/gml/3.2

Now the file is valid.

[Test report](https://github.com/inspire-eu-validation/community/files/3939341/Test.run.on.12_06.-.09.12.2019.with.test.suite.Conformance.Class.2_.INSPIRE.data.sets.and.data.set.series.interoperability.metadata.html.zip)

Best regards.
