### ISSUE TITLE
Problem with multiple reference dates

### ISSUE THREAD

**Issue by skafka** [INSPIRE-MIF/helpdesk-validator#177]
I have both the creation and revision date in the metadata record (According to TG Requirement C.11). The validator detects them as an error. 

`<gmd:date>
  <gmd:CI_Date>
    <gmd:date>
      <gco:Date>2005</gco:Date>
    </gmd:date>
    <gmd:dateType>
      <gmd:CI_DateTypeCode codeListValue="creation" codeList="http://standards.iso.org/iso/19139/resources/gmxCodelists.xml#CI_DateTypeCode">creation</gmd:CI_DateTypeCode>
     </gmd:dateType>
   </gmd:CI_Date>
</gmd:date>
<gmd:date>
  <gmd:CI_Date>
    <gmd:date>
      <gco:Date>2011</gco:Date>
    </gmd:date>
    <gmd:dateType>
      <gmd:CI_DateTypeCode codeListValue="revision" codeList="http://standards.iso.org/iso/19139/resources/gmxCodelists.xml#CI_DateTypeCode">revision</gmd:CI_DateTypeCode>
    </gmd:dateType>
  </gmd:CI_Date>
</gmd:date>`

Example record: https://egdi.geology.cz/record/xml/f2435e00-5e00-1243-b989-52caa6446ca8

**Comment by Michael-81** [comment]
@skafka : Your Datetype has only a Year information in it. In my opinion this is not correct.

`<gmd:date>
    <gco:Date>2005-01-01</gco:Date>
  </gmd:date>`

**Comment by skafka** [comment]
According ISO 8601 and ISO 19139 the date may be in the following formats YYYY / YYYY-MM / YYYY-MM-DD. Or there is some INSPIRE constraint regarding the date element?

**Comment by danielnavarrogeo** [comment]
Dear @skafka 
We are analyzing this issue. We will keep you posted.
Regards

**Comment by josemasensio** [comment]
Dear @skafka,
Thank you for your message. according to the [INSPIRE MD TG  2.0](https://inspire.ec.europa.eu/sites/default/files/documents/metadata/inspire-tg-metadata-iso19139-2.0.1.pdf), at TG Requirement C.11, the Date element must be used for a precise date:
 
> The date values shall be expressed using Gregorian calendar and in accordance with [ISO 8601] with either date precision or date and time precision. For date precision the gmd:CI_Date/gmd:date/gco:Date element, and for date and time precision gmd:CI_Date/gmd:date/gco:DateTime element shall be used.

![image](https://user-images.githubusercontent.com/50206416/70523430-57526d80-1b43-11ea-806f-c68229e83f69.png)


Also, on [ISO 8601:2004](https://www.iso.org/standard/40874.html) there is no reference about using only YYYY as accepted format:
> - calendar dates expressed in terms of calendar year, calendar month and calendar day of the month;
> - ordinal dates expressed in terms of calendar year and calendar day of the year;
> - week dates expressed in terms of calendar year, calendar week number and calendar day of the week;
> - local time based upon the 24-hour timekeeping system;
> - Coordinated Universal Time of day;
> - local time and the difference from Coordinated Universal Time;
> - combination of date and time of day;
> - time intervals;
> - recurring time intervals.

![image](https://user-images.githubusercontent.com/50206416/70523461-6afdd400-1b43-11ea-87c7-4a3f9ae690b9.png)

Please, let us know if you have any other questions. 
Best regards.

**Comment by dperezBM** [comment]
Dear @skafka,

On June 22, 2020, we updated MD 2.0 regex related to date and DateTime, including C.11. You can see its progress in [issue 331](https://github.com/INSPIRE-MIF/helpdesk-validator/issues/331).

If you have any other problems or bugs, please feel free to open another issue.

Best regards.
