### ISSUE TITLE
Multiple Metadata Point of Contact

### ISSUE THREAD

**Issue by skafka** [INSPIRE-MIF/helpdesk-validator#178]
I have metadata record with two gmd:contact elements (with one with role="pointOfContact") according to TG Requirement C.6, but the validator detects them as an error. 

Example metadata record: https://egdi.geology.cz/record/xml/f2435e00-5e00-1243-b989-52caa6446ca8

**Comment by danielnavarrogeo** [comment]
Dear @skafka 
We are analyzing this issue. We will keep you posted.
Regards

**Comment by josemasensio** [comment]
Dear @skafka,

Thank you for your message. There was an unspecific error message that was confusing. We have updated it. 

Also, we will appreciate it if you could provide us with your feedback.

Thank you and best regards.

**Comment by skafka** [comment]
Thank you very much for the quick response. But the validation result is the same on Staging deployment. It returns this error message: 
`The role information of the responsible party serving as metadata point of contact must have 'pointOfContact' as role (in gmd:CI_RoleCode/@codeListValue). The metadata record does not fulfill this requirement. Found: authorpointOfContact.`
So it looks like melting both contacts roles values together.

Thank you

**Comment by josemasensio** [comment]
Dear @skafka,

The changes are now available on [our staging instance](http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp).
We will appreciate it if you could provide us with your feedback.

Best regards.

**Comment by skafka** [comment]
Now, the error is reported:
`The role information of the responsible party serving as metadata point of contact must have 'pointOfContact' as role (in gmd:CI_RoleCode/@codeListValue). The metadata record does not fulfill this requirement. Found: author.`

It seems that only the first metadata contact instance is tested now, but I have two instances with "pointOfContact" and "author" roles. The validator should look for the instance with "pointOfContact" role if present.

Thank you

**Comment by josemasensio** [comment]
Dear @skafka,

As mentioned on [MD 2.0 TG Requirement C.6](https://inspire.ec.europa.eu/sites/default/files/documents/metadata/inspire-tg-metadata-iso19139-2.0.1.pdf#page=34&zoom=100,0,106), 
>  Attribute codeList shall be "http://standards.iso.org/iso/19139/resources/gmxCodelists.xml#CI_RoleCode" and
value of codeListValue attribute "pointOfContact"

![image](https://user-images.githubusercontent.com/50206416/70602671-39dddc00-1bf5-11ea-8bcf-ef5d6c25e2bf.png)


So, the value `author` is not allowed here. 

Please, let us know if you have any other questions.

Best regards.

**Comment by skafka** [comment]
OK, but I have two contact instances in my metadata record. (According to TG Requirement C.6:  The multiplicity of this element is 1..*.)  One has role "pointOfContact" and the second has role "author". My opinion is that one "pointOfContact" is enough. Or am I wrong?
See: https://egdi.geology.cz/record/xml/f2435e00-5e00-1243-b989-52caa6446ca8 

Thank you for patience.

**Comment by josemasensio** [comment]
Dear @skafka,

For every `contact` instance,  the attribute `@codeListValue` of the Role node must be "pointOfContact".
So, "author" value is not allowed. 

Maybe on our [ATS Metadata Point of Contact](https://github.com/inspire-eu-validation/metadata/blob/2.0/common/md-point-of-contact.md) is more clear about how to define a ResponsibleParty element. 

Please, let us know if this is ok for you. 

Best regards.

**Comment by michellutz** [comment]
I just read again the TG requirement. 

In my view, the IR asks to provide one or more Metadata point(s) of contact, incl. their name and e-mail. The TG then requires to use the `gmd:MD_metadata/gmd:contact/gmd:CI_ResponsibleParty` element to provide this information. For each such element _that describes a metadata point of contact_, the role element shall have the "pointOfContact" as `@codeListValue`. But this does not necessarily mean that there cannot be other contact information with other code list values in the metadata.

I think, the ATS and ETS should be modified accordingly. They should check whether there is at least one `gmd:MD_metadata/gmd:contact/gmd:CI_ResponsibleParty` element with "pointOfContact" as `@codeListValue`.

**Comment by danielnavarrogeo** [comment]
Thank you @michellutz for your comment.

We will change the ATS and ETS based on your proposal: 

> They should check whether there is at least one `gmd:MD_metadata/gmd:contact/gmd:CI_ResponsibleParty` element with "pointOfContact" as `@codeListValue`.

**Comment by danielnavarrogeo** [comment]
Dear @skafka 

The fix is now available in [staging instance](http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/).

Could you please check it and provide us feedback?

Regards

**Comment by skafka** [comment]
Now the validation is OK. Thank you very much. 

Regards

**Comment by danielnavarrogeo** [comment]
Thank you @skafka 

Please do not close the issue. We will keep it open and labeled as solved until is available in production instance.

Regards
