### ISSUE TITLE
ETF 2.1.0: Release due date 

### ISSUE THREAD

**Issue by ghost** [INSPIRE-MIF/helpdesk-validator#179]
Hi,

as a new version of ETF-Validator is planned, it would be nice to know when it will be released.

Due date is not set in next milestone:
https://github.com/etf-validator/governance/milestone/1

Am I looking at the right place?

P.S. If this issue shouldn't be discussed here could you please give me a hint where to place this question.

Best regards.

**Comment by danielnavarrogeo** [comment]
Dear @DeordD 

I think the release you mentioned is for the ETF, which is managed in the repository you have provided.

You might want to ask there.

Regards

**Comment by ghost** [comment]
Dear @danielnavarrogeo ,

thanks a lot. I will ask there.

Regards.
