### ISSUE TITLE
Error loading the ETF Web Interface

### ISSUE THREAD

**Issue by klimeto** [INSPIRE-MIF/helpdesk-validator#18]
Dears,

While trying to use the Web interface of the validator I received the following error:

Error loading the ETF Web Interface, please contact the System Administrator. Error message: Script error for "moment" http://requirejs.org/docs/errors.html#scripterror

from URL: http://inspire-sandbox.jrc.ec.europa.eu/etf-webapp/

![image](https://user-images.githubusercontent.com/7523262/50425345-7ee9f080-0874-11e9-9228-c9ffb51d887b.png)

Tomas

**Comment by michellutz** [comment]
Hi Tomas,

I cannot reproduce the error. The Webapp seems to be loading fine again now. Could you please check again?

Michael

**Comment by klimeto** [comment]
Hi Michael,

Now it works.

Must had been some temporal unavailability.

Maybe worth to check the logs around date stamp of my initial message to understand what actually happened.

Thanks,
Tomáš

**Comment by michellutz** [comment]
@df-git Could you please have a look in the logs (around 25 December 2018 18:45) and see if you can find the root cause of the error Tomas encountered?
