### ISSUE TITLE
Text string is validated instead of anchor URI

### ISSUE THREAD

**Issue by fantamir** [INSPIRE-MIF/helpdesk-validator#181]
According to the conclusion of the issue #84 (https://github.com/inspire-eu-validation/community/issues/84), the language neutral anchor URI should be tested only instead of the text string itself. With regard to the last but one comment available in the issue #84, it seems, the implemented solution does not work properly. The new issue is opened following the @josemasensio instruction in the last #84 comment.

**Comment by danielnavarrogeo** [comment]
Dear @fantamir 

Thank you for your comment. We are analyzing this issue.

Regards

**Comment by danielnavarrogeo** [comment]
Dear @fantamir 

Thank you for openning this issue. As you mentioned, only the xlink:href value of the Anchor element shall be tested. Not the content itself. We are fixing it.

Regards

**Comment by danielnavarrogeo** [comment]
Dear @fantamir 

The issue has been fixed and it is now ready for testing in [staging ](staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp) environment.

Could you please check that the issue is solved and provide us feedback?

Regards

**Comment by danielnavarrogeo** [comment]
Dear @fantamir 

Could you please check the implemented solution in [staging](http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/) environment and provide us feedback?

Regards

**Comment by alitka** [comment]
Dear @danielnavarrogeo,

I'm not fully sure, if I did a proper testing related to this issue. I upload three different external xml-files with the following entries for the TG Req. 3.4: 

option 1 (with correct language neutral anchor URI and correct text string)
`<gmd:keyword>`
`<gmx:Anchor xlink:href="http://inspire.ec.europa.eu/metadata-codelist/SpatialDataServiceCategory/infoMapAccessService">Dienst für den Zugriff auf grafische Darstellungen</gmx:Anchor>`
`</gmd:keyword>`
`</gmd:MD_Keywords>`

option 2 (with correct language neutral anchor URI, but incorrect text string)
`<gmd:keyword>`
`<gmx:Anchor xlink:href="http://inspire.ec.europa.eu/metadata-codelist/SpatialDataServiceCategory/comTransferService">Dienst für den Zugriff auf grafische Darstellungen</gmx:Anchor>`
`</gmd:keyword>`
`</gmd:MD_Keywords>`

option 3 (with incorrect language neutral anchor URI, but correct text string)
`<gmd:keyword>`
`<gmx:Anchor xlink:href="http://inspire.ec.europa.eu/metadata-codelist/SpatialDataServiceCategory/infoMapAccessService">Dienst gegevensoverdracht</gmx:Anchor>`
`</gmd:keyword>`
`</gmd:MD_Keywords>`

All three options passed the test, but I guess the option 3 shouldn't, right?
Best regards.

**Comment by danielnavarrogeo** [comment]
Dear @alitka 

In our opinion, the three options shall pass the test since the provided xlink:href in three options are valid:
* "http://inspire.ec.europa.eu/metadata-codelist/SpatialDataServiceCategory/infoMapAccessService"
* "http://inspire.ec.europa.eu/metadata-codelist/SpatialDataServiceCategory/comTransferService"
* "http://inspire.ec.europa.eu/metadata-codelist/SpatialDataServiceCategory/infoMapAccessService"

Why do you think that option 3 should not be right? Option 3 and 1 use the same xlink:href.

Regards
