### ISSUE TITLE
Typo error in code: Expected "harmonished" instead of "harmonised" for conformance Class 7

### ISSUE THREAD

**Issue by iuriemaxim** [INSPIRE-MIF/helpdesk-validator#183]
In the "Conformance Class 7 - Harmonised Spatial Data Services Metadata" the online validator expects the value "harmonished" instead of "harmonised" in the title of the CI_Citation  of the domain consistency specification.

It expects: 
<gmx:Anchor xlink:href="http://inspire.ec.europa.eu/id/ats/metadata/2.0/sds-harmonised">harmonished</gmx:Anchor>

While correct is
<gmx:Anchor xlink:href="http://inspire.ec.europa.eu/id/ats/metadata/2.0/sds-harmonised">harmonised</gmx:Anchor>

I expect that correct should be also:
<gmx:Anchor xlink:href="http://inspire.ec.europa.eu/id/ats/metadata/2.0/sds-harmonised"/>

This is a minor error, very easy to fix in the code, just delete the second "h" letter in the word "harmonis**h**ed".

**Comment by iuriemaxim** [comment]
Can you please let me know when this will be solved in the production, at
http://inspire.ec.europa.eu/validator/ ? This is necessary in order to be able to finish a project.

**Comment by danielnavarrogeo** [comment]
Dear @iuriemaxim 

This is currently fixed in [staging instance](http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/). Could you please check it and provide us feedback?

This fix will be included in the next release. Meanwhile, you might want to use staging.

Regards

**Comment by iuriemaxim** [comment]
Dear @danielnavarrogeo 

I confirm that it was fixed on staging.

Kind regards,
Iurie

**Comment by danielnavarrogeo** [comment]
Thank you @iuriemaxim,

Please do not close the issue. We will keep it open and labeled as solved until is available in production instance.

Regards
