### ISSUE TITLE
md-sds-interoperable 6.1 wrong error triggered for Coordinate reference System

### ISSUE THREAD

**Issue by iuriemaxim** [INSPIRE-MIF/helpdesk-validator#184]
When validating a metadata file for an interoperable SDS (conformance class 6), in which the reference system is encoded according to the TG, namely:

<gmd:referenceSystemInfo>
  <gmd:MD_ReferenceSystem>
    <gmd:referenceSystemIdentifier>
      <gmd:RS_Identifier>
        <gmd:code>
          <gmx:Anchor xlink:href="http://www.opengis.net/def/crs/EPSG/0/3035">EPSG:3035</gmx:Anchor>
        </gmd:code>
      </gmd:RS_Identifier>
    </gmd:referenceSystemIdentifier>
  </gmd:MD_ReferenceSystem>
</gmd:referenceSystemInfo>

the ETF validator in production (http://inspire.ec.europa.eu/validator) shows the following error as can be seen at http://inspire.ec.europa.eu/validator/v2/TestRuns/EIDc8de84bb-88d8-4ee7-a785-0c73b92fd883.html:

**_”The record must have an RS_Identifier element with non empty codeSpace element.”_**

However there is no such requirement, neither in the Technical Guidelines, neither in the ATS.

If a codeSpace element is provided:

<gmd:RS_Identifier>
  <gmd:code>
    <gmx:Anchor xlink:href="http://www.opengis.net/def/crs/EPSG/0/3035">EPSG:3035</gmx:Anchor>
  </gmd:code>
  <gmd:codeSpace>
    <gmx:Anchor xlink:href="http://www.opengis.net/def/crs/EPSG/0">EPSG</gmx:Anchor>
  </gmd:codeSpace>
</gmd:RS_Identifier>

then the validator shows an error indicating that a codeSpace element should not be provided, as can be seen at http://inspire.ec.europa.eu/validator/v2/TestRuns/EID4bcc8130-9aa4-4df2-b21e-c57f35abafd9.html:

**_”When one of the default Coordinate Reference Systems are used (annex D.4 of Technical Guide), it must be coded using the HTTP URI Identifier column of annex and codeSpace node must not exists.”_**

In such circumstances, there is no way to provide a metadata file for an interoperable or for an harmonised SDS that would be valid according to the ETF validator.

With the code that exist now on the master branch, the validator does not show any error. Please mark this bug as being solved, when it will be solved in production.

Please solve this bug in production in order to allow a project closure.

**Comment by danielnavarrogeo** [comment]
Dear @iuriemaxim 
Thank you for opening this issue. We are analyzing it and will provide you feedback as soon as it is solved.
Regards

**Comment by iuriemaxim** [comment]
Have a look at that section of code on master branch, as the validator does not trigger wrong errors for reference system with the code on master branch.
I supose it can be an easy fix to revert to the code that is availble on the master branch for this specific test related to reference system encoding.

**Comment by danielnavarrogeo** [comment]
Dear @iuriemaxim 

The issue has been fixed and it is available in [staging](http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/).

Could you please check it and provide us feedback?

Regards

**Comment by iuriemaxim** [comment]
Dear @danielnavarrogeo 

I confirm that the issue has been fixed on staging, as it can be seen here http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/v2/TestRuns/EIDc8f32887-bb3a-4fcf-8f7f-540b02146451.html

Please let me know where can I find the code updated as it is now on staging.

I am waiting to be implemented in production as well.

Happy New Year,
Iurie

**Comment by danielnavarrogeo** [comment]
Dear @iuriemaxim 

Happy New Year and thank you for your feedback. 

You can find the code for staging in https://github.com/inspire-eu-validation/ets-repository/tree/staging

Regards
