### ISSUE TITLE
Tests taking too long or not finishing

### ISSUE THREAD

**Issue by danielmoraes09** [INSPIRE-MIF/helpdesk-validator#185]
Hi,

I'm trying to test a set of data, since last friday (27/12) and it is taking too long to process or it even doesn't finish. It is a relatively small dataset (71 xml files).
I even let the test running on friday before going home and today when I got back to work it wasn't finished. The progress bar always stays at the same position (see printscreen attached).

I just tried to split the 71 files in small groups and it seems to work. But it is a little bit inconvenient because I'll have to manually group files and upload each group one by one.

Anyway, it is just a small feedback.

Thanks and have a happy new year.
![print_inspire](https://user-images.githubusercontent.com/57899414/71577512-58e0d700-2aec-11ea-8cb8-b0b09b71ad96.png)

**Comment by danielnavarrogeo** [comment]
Dear @danielmoraes09 

Thank you for your comment. Could you provide us the 71 xml files? 

If not, could you run the tests again and provide us feedback with the time spent and the link to the Test Report?

We are working on the improvement of metadata 2.0 performance and these results might be interesting for us.

Happy New Year.

**Comment by danielmoraes09** [comment]
Hi, Daniel,

 

I’m sorry but the 71 files were already modified and more files were added to their folder, so I lost track of them.

However, I tried to validate a new set of files and the same thing happened, ie validation runs, stops and never ends. Such files are attached to this email.

Thanks for you help.

 

 

 

De: Daniel Navarro [mailto:notifications@github.com] 
Enviada: 8 de janeiro de 2020 11:05
Para: inspire-eu-validation/community <community@noreply.github.com>
Cc: danielmoraes09 <daniel.moraes@geoglobal.pt>; Mention <mention@noreply.github.com>
Assunto: Re: [inspire-eu-validation/community] Tests taking too long or not finishing (#185)

 

Dear @danielmoraes09 <https://github.com/danielmoraes09> 

Thank you for your comment. Could you provide us the 71 xml files?

If not, could you run the tests again and provide us feedback with the time spent and the link to the Test Report?

We are working on the improvement of metadata 2.0 performance and these results might be interesting for us.

Happy New Year.

**Comment by danielnavarrogeo** [comment]
Dear @danielmoraes09 

I cannot find the attached files. Could you please send it to inspire-helpdesk@bilbomatica.com ?

Thank you

**Comment by carlospzurita** [comment]
Dear @danielmoraes09 

Did you have the opportunity to gather some of the tests files? We would like to advance on this issue and include on the oncoming release on the 15th of September. Please attach them to a comment here in the issue, or send it to inspire-helpdesk@bilbomatica.com

Thank you

**Comment by dperezBM** [comment]
Dear @sparlar,

In case you have any other questions or problems, please feel free to open a new issue.

Best regards.
