### ISSUE TITLE
Validator cannot be reached

### ISSUE THREAD

**Issue by JohannaOtt** [INSPIRE-MIF/helpdesk-validator#186]
When trying to use the INSPIRE Validator at http://inspire.ec.europa.eu/validator/, I get a 502 Bad Gateway error.

**Comment by juanpelegrina** [comment]
Dear Johanna, 
There are some maintenance works being carried out this morning. It should be done today. 
In the meantime, you can use the [Staging instance](http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/).
Sorry for the inconvenience
