### ISSUE TITLE
Wrong error triggered on C14-Temporal Extent if using gml:timePosition indeterminatePosition="now" when validating a DATA SET metadata

### ISSUE THREAD

**Issue by iuriemaxim** [INSPIRE-MIF/helpdesk-validator#188]
When validating metadata of a DATA SET, the online validator (incl. staging version) throws an error if the TimeInstant of the temporal extent is provided as being "now":

          <gmd:temporalElement>
            <gmd:EX_TemporalExtent>
              <gmd:extent>
                <gml:TimeInstant gml:id="ID48e87ef3-3878-4219-bba7-e87dd8d061e6">
                  <gml:timePosition indeterminatePosition="now"/>
                </gml:TimeInstant>
              </gmd:extent>
            </gmd:EX_TemporalExtent>
          </gmd:temporalElement>

The error is provided under "Common Requirements for ISO/TC 19139:2007 based on INSPIRE metadata records">"Identification">"md common req C:14: Temporal Extent".

Please see: http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/v2/TestRuns/EID818da1eb-3316-4635-9600-ee70f062db1c.html on staging environmen and http://inspire.ec.europa.eu/validator/v2/TestRuns/EID960d35a8-8775-44b9-810b-830eaf233076.html on production environment.

It is important to note that when testing a DATA SERVICE, the validator indicates correctly that there is no error, even if the the tests are sharing the same "Common Requirements for ISO/TC 19139:2007 based on INSPIRE metadata records", as it can be seen here: http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/v2/TestRuns/EID7a53ce17-4ad8-4ff9-8139-6e672ef36a88.html

I suppose that the code that is used for testing a DATA SERVICE metadata should be used for testing a DATA SET metadata as well.

Nota Bene: I tested a DATA SET metadata file against the Conformance Class 2 and a DATA SERVICE metadata files against conformance class 4 and 7. Incorrect error is triggered for DATA SET metadata only if using TimeInstant/timePosition as "now". The behavior is correct if providing "now" as endPosition part of a TimePeriod interval, including for DATA SET and DATA SERVICE metadata.

Best regards,
Iurie

**Comment by danielnavarrogeo** [comment]
Dear @iuriemaxim,

According with the TG Requirement C.14, the _gml:TimeInstant/gml:timePosition_ element shall contain a value ISO 8601 valid.

> A single individual date or a time period shall be encoded using one gmd:temporalElement/gmd:EX_TemporalExtent/gmd:extent element. For individual dates this element shall contain a gml:TimeInstant/gml:timePosition element with the date value given according to [ISO 8601].

The attribute _indeterminatePosition_ may be used with the elements _gml:startPosition_ or _gml:endPosition_ inside of _gml:TimePeriod_.

> For a single time period the gmd:temporalElement/gmd:EX_TemporalExtent/gmd:extent element shall contain a gml:TimePeriod element containing start and end dates of the period. In case the time period is open-ended with either the start or the end date unknown, the elements gml:startPosition or gml:endPosition may be used with an empty value and the attribute indeterminatePosition with value "unknown". If the temporal extent is on-going, the gml:endPosition may be used with an empty value and the attribute indeterminatePosition with value "now".

In the case you would like to use the attribute _indeterminatePosition="now"_, you may want to use a time period instead of an individual date.

Regards

**Comment by iuriemaxim** [comment]
Dear @danielnavarrogeo,

I am aware of the provisions of the TG. As I previously mentioned  when testing a metadata file for a DATA SERVICE, it provides a different result than when testing a metadata file for a DATA SET. And this is a bug.

I do not see any reason why this:

      <gmd:temporalElement>
        <gmd:EX_TemporalExtent>
          <gmd:extent>
            <gml:TimeInstant gml:id="ID48e87ef3-3878-4219-bba7-e87dd8d061e6">
              <gml:timePosition indeterminatePosition="now"/>
            </gml:TimeInstant>
          </gmd:extent>
        </gmd:EX_TemporalExtent>
      </gmd:temporalElement>
 
can be indicated for a DATA SERVICE, but cant be indicated for a DATA SET.

So if you want, you may split this into two issues:

1. Temporal extent for a DATA SET should be validated the same way as for a DATA SERVICE, as the TG does not provide any difference between these two, as they are both validated according to "Common Requirements for ISO/TC 19139:2007 based on INSPIRE metadata records">"Identification">"md common req C:14: Temporal Extent". 

2. A discussion if the TG is clear enough or not in order not to allow to provide timePosition as being indeterminate=”now” when providing the time as TimeInstant, but allowing to provide timePosition as being indeterminate=”now” when providing the time as TimePeriod. Personally I find it quite strange and difficult to understand why TimePeriod could be treated different than TimeInstant, especially when more and more spatial datasets contains near real-time data (i.e.: traffic, sensors, etc).

The proposed solution ”In the case you would like to use the attribute indeterminatePosition="now", you may want to use a time period instead of an individual date.” is not suitable. It would not be correct if a user will indicate a period of time if the dataset is representing always the data from the current day or for even from the current minute. Also it would not be practicable to update the metadata files daily just in order to indicate that the dataset is not referring anymore to 2020-01-07, but to 2020-01-08. Of course that providing a time interval such as 2020-01-01 - ”now” would be incorrect in order to indicate a dataset that is updated daily.

Iurie

**Comment by danielnavarrogeo** [comment]
Dear @iuriemaxim 

Thank you for the clarification. 

1. The first issue is a bug indeed as you mentioned. We are going to fix it.

2. Regarding the second issue, the TG seems to allow the use of the _indeterminatePosition="now"_ attribute with _gml:TimePeriod_ only. However, we understand your reasoning regarding real-time data and we are going to make the test more flexible. Therefore, it will accept _indeterminatePosition="now"_ with _gml:timePosition_.

Please, in order to reproduce the error in our environment, would you mind to provide us with the data by email sending them to inspire-helpdesk@bilbomatica.com ? All data sent to this address will be completely confidential and will only be used in order to improve the validator. Once the issue has been solved all data will be deleted.

Thank you and best regards.

**Comment by iuriemaxim** [comment]
Dear @danielnavarrogeo, @josemasensio,

In order for anybody to be able to reproduce the error, I think that easier than providing the metadata files, the following steps can be done:

1. Download the metadata files examples that are provided in Annex G of the Technical Guidance for the implementation of INSPIRE dataset and service metadata based on ISO/TS 19139:2007, that indicates the following link where the files are available https://inspire.ec.europa.eu/id/document/tg/metadata-iso19139/2.0/examples. 

2. There are two files there: one for a dataset and one for a network service. Test the dataset metadata against Metadata TG version 2.0 Conformance Class 2 and network service metadata against Metadata TG version 2.0 Conformance Class 4. Both will pass the validation.

3. Replace the temporal extent in both files with the following:

xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

      <gmd:temporalElement>
        <gmd:EX_TemporalExtent>
          <gmd:extent>
            <gml:TimeInstant gml:id="ID48e87ef3-3878-4219-bba7-e87dd8d061e6">
              <gml:timePosition indeterminatePosition="now"/>
            </gml:TimeInstant>
          </gmd:extent>
        </gmd:EX_TemporalExtent>
      </gmd:temporalElement>
 
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

4. Test the modified dataset metadata against Metadata TG version 2.0 Conformance Class 2 and the modified network service metadata against Metadata TG version 2.0 Conformance Class 4. The validator will indicate an error for the dataset metadata, while the network service metadata will pass the validation.

Let me know if any other information is necessary.

Best regards,
Iurie Maxim

**Comment by danielnavarrogeo** [comment]
Dear @iuriemaxim 

Thank for the steps to reproduce the error. We will come back to you when a solution is implemented.

Regards

**Comment by danielnavarrogeo** [comment]
Dear  @iuriemaxim 

The issue has been addressed and deployed in [staging](http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/) environment. 

Could you please check it and confirm that the issue has been fixed?

Regards

**Comment by iuriemaxim** [comment]
Dear @danielnavarrogeo 

I confirm that the issue was was fixed on the staging environment.

No other issues were found by us while testing different metadata files against the following Conformance Class tests for Metadata (TG version 2.0):
- CC 2 (dataset), - Includes Common + CC 1
- CC 4 (network services), includes Common + CC 3
- CC 7 (Spatial Data Services), Includes Common +CC 5 and CC 6.

Probably that the text "-BETA" can be soon removed and the code can be deployed in production.

Best regards,
Iurie

**Comment by danielnavarrogeo** [comment]
Dear @iuriemaxim 

Thank you for confirming that the issue has been fixed and for the general feedback regarding the ETS's for Metadata 2.0.

Indeed, the 'BETA' text [has been removed](https://github.com/inspire-eu-validation/ets-repository/commit/83cffde6d98ecaa36a17226c4f360ceba1560969) today and it will be updated soon in staging.

Regards
