### ISSUE TITLE
Error in test md-iso.f.1?

### ISSUE THREAD

**Issue by laers** [INSPIRE-MIF/helpdesk-validator#19]
The test on keyword in metadata (md-iso.f.1: Dataset keyword) might be broken... I have made some tests with compliant metadata and all the tests fails in md-iso.f.1. 

The message I get is: "The metadata record has keywords which originate from a controlled vocabulary 'GEMET - INSPIRE themes, version 1.0', but the date or date type is not correct. Date should be '2008-06-01' and date type 'publication'. The keywords are: Administrative units."

The test report is available at: http://inspire-sandbox.jrc.ec.europa.eu/etf-webapp//v2/TestRuns/EID4cf6e5cb-60d0-4b02-947b-5d43cdf4af79.html?lang=en

When I look into the xml-metadata document the date and date type seems to be correct. Can you reproduce the error?

One of the tested metadata is: https://geodata-info.dk/srv/eng/csw?service=CSW&request=GetRecordById&version=2.0.2&outputSchema=http://www.isotc211.org/2005/gmd&elementSetName=full&id=50f84f74-a55a-5ca2-e36e-d9d696434322

Thanks,
Lars DK

**Comment by inakidiazdecerio** [comment]
Dear @laers,

Thanks for reporting the issue. The issue has been already registered and the solution has been implemented, the pull request is pending to be accepted. Follow the discussion in the following link:
https://github.com/inspire-eu-validation/ets-repository/issues/180

Regards,
Iñaki
