### ISSUE TITLE
md sds 3.6: Coupled Resource

### ISSUE THREAD

**Issue by alitka** [INSPIRE-MIF/helpdesk-validator#190]
Testing a service metadata record causes an error concerning the Coupled Resource
- [x] description of the steps to reproduce the issue
1. go to http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp and select "Conformance Class 3: INSPIRE Spatial Data Service baseline metadata
2. start the test and upload an externale xml-file 
[service_DE_CoupledResource.zip](https://github.com/inspire-eu-validation/community/files/4040569/service_DE_CoupledResource.zip)
3. the error message returned for the test "Identification > md sds 3.6 Coupled Resource"
`The metadata record set has 1 record(s) with errors for this assertion.
XML document 'nw_md_service_mod.xml', record 'aa83fc4f-d0db-48a5-a3f1-b8d5d6392872': The metadata record has a linkage property, but it references a resource at 'https://registry.gdi-de.org/id/de.nw/inspire-au-basis-dlm' that cannot be accessed. The HTTP status code when requesting the resource is: '303'. A status code of '200' is expected.`
- [x] used browser and version `Firefox Browser 72.0 (64-Bit)`
- [x]  a screenshot illustrating the problem
![grafik](https://user-images.githubusercontent.com/29542183/72071378-ee017e00-32eb-11ea-8d57-99bc9d2c766c.png)
- [x] the Test Report (ideally as an attachment to the issue)
http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/v2/TestRuns/EIDce4b45da-a0c0-4e89-a8ec-9c74255b5ddb.html
- [x]  the name of the Test that failed or better: change the `Level of Detail`
http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/v2/TestRuns/EIDce4b45da-a0c0-4e89-a8ec-9c74255b5ddb.html#EID2a7b655d-0c83-4756-9176-83f2536dad4e

The test claims an error concerning the status code (redirect) of the response of the entry in the operatesOn-element (e. g. blocked redirections). The validator should expecting/accepting as a valid return also the following error codes: `200, 204, 301, 302, 303, 307`.

You already fixed this issue for md-iso.d.3: Coupled resource (Conformance class: INSPIRE Profile based on EN ISO 19115 and EN ISO 19119): see https://github.com/inspire-eu-validation/community/issues/163

![grafik](https://user-images.githubusercontent.com/29542183/72073013-5e5dce80-32ef-11ea-806d-72e682bcdbe2.png)

**Comment by danielnavarrogeo** [comment]
Dear @alitka 

Thank you for opening this issue. We are developing a solution for it.

Regards

**Comment by danielnavarrogeo** [comment]
Please, in order to reproduce the error in our environment, would you mind to provide us with the data by email sending them to inspire-helpdesk@bilbomatica.com ? All data sent to this address will be completely confidential and will only be used in order to improve the validator. Once the issue has been solved all data will be deleted.

Thank you and best regards.

**Comment by danielnavarrogeo** [comment]
Dear @alitka,

The issue has been addressed and deployed in [staging environment](http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/).

Could you please check it and confirm that the issue has been fixed?

Regards

**Comment by alitka** [comment]
Dear @danielnavarrogeo 
I have tested the xml-file again and everything is working properly. 
Thanks & regards.

**Comment by danielnavarrogeo** [comment]
Thank you @alitka.
