### ISSUE TITLE
Conformance Class 'View Service WMS' validator looking for exact place of inspire_vs.xsd

### ISSUE THREAD

**Issue by janneumann1** [INSPIRE-MIF/helpdesk-validator#191]
I'd like to know why is the validator looking for an exact place of the inspire_vs.xsd document in the ExtendedCapabilities. The assertion looks like this:
`if(!(capabilities.@'xsi:schemaLocation'.toString().contains(schemaName) ||
	capabilities.Capability.ExtendedCapabilities.@'xsi:schemaLocation'.toString().contains(schemaName))){
	String[] assertParams = ['error', 'Missing schema location reference to ' + schemaName];
	throw new TranslatableAssertionError('TR.invalidSchema', assertParams);
}`

But can't seem to find this hardcoded reference anywhere in XSD files.
Our GetCapabilities response references the XSD file on a local server, like e.g.:
`<ExtendedCapabilities xsi:schemaLocation="http://inspire.ec.europa.eu/schemas/inspire_vs/1.0 http://myserver/service/Schemas/inspire/inspire_vs/1.0/inspire_vs.xsd">`

Is this not correct?

**Comment by danielnavarrogeo** [comment]
Dear @janneumann1 

After analysing this issue we have decided to allow different url's. We will come back to you when it is ready for testing.

Regards

**Comment by danielnavarrogeo** [comment]
Dear @janneumann1 

The test does not check anymore whether 'http://inspire.ec.europa.eu/schemas/inspire_vs/1.0/inspire_vs.xsd' is provided in the schemaLocation attribute. However, the xml still shall be valid against that specific schema.

Could you please check it and confirm that the issue has been fixed?

Regards

**Comment by janneumann1** [comment]
Hi @danielnavarrogeo , I have re-tested it via http://inspire.ec.europa.eu/validator/ but it seems it still uses the original assertion code. Shall it be tested somewhere else?
Thanks

**Comment by danielnavarrogeo** [comment]
Sorry, yes. You can test it in [staging](http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/) environment.

**Comment by janneumann1** [comment]
Thanks. I can confirm that now it passed through that check.

**Comment by danielnavarrogeo** [comment]
Thank you for your feedback.

Regards

**Comment by iuriemaxim** [comment]
Hi,

I don't think it is correct that "The test does not check anymore whether 'http://inspire.ec.europa.eu/schemas/inspire_vs/1.0/inspire_vs.xsd' is provided in the schemaLocation attribute. However, the xml still shall be valid against that specific schema."

This can allow data providers to provide a the extended Capabilities section of the GetCapabilities document that will be not inline with the INSPIRE Extended Capabilities requirements.

This means that it will not be possible anymore to ensure interoperability.

There is a requirement in INSPIRE TGs stating that all INSPIRE XSD schemas should be used from this location https://inspire.ec.europa.eu/schemas/ that is regularly maintained (see readme.txt).

See https://inspire.ec.europa.eu/portfolio/xml-schemas

You should revert to previous code and consult with JRC as this could lead to major interoperability issues.

Iurie

**Comment by MarcoMinghini** [comment]
Dear @iuriemaxim,
I think there was a misunderstanding of the fix to this issue.

There might be a number of reasons to point to a local copy of the schema (for example to improve performance) so this should be allowed. What is important is that the XML document validates against the official schema (http://inspire.ec.europa.eu/schemas/inspire_vs/1.0/inspire_vs.xsd).

I hope this clarifies the solution.

**Comment by janneumann1** [comment]
It may be worth noting - [http://portal.opengeospatial.org/files/?artifact_id=38867](http://portal.opengeospatial.org/files/?artifact_id=38867) - section 12.4 tells:

> A server may reference an exact copy of these schemas located elsewhere, as long as they are readily accessible by clients. For example, it may be desirable to place the referenced schemas on the same network server as the OWS server, since that decreases the number of points of possible network failure. Such local copies of schemas should be organized into directories similar to http://schemas.opengis.net/. The server owner should insure that any such local copies are kept up-to-date with respect to the authoritative files at http://schemas.opengis.net/.

**Comment by iuriemaxim** [comment]
@janneumann1 That's correct.

But the link http://myserver/service/Schemas/inspire/inspire_vs/1.0/inspire_vs.xsd that was indicated by you is not readily accessible by clients.
This means that in this respect is not enough just to modify the test as it was done, but the test should:
1. verify if the link is accessible by clients and 
2. verify that the local copy is up-to-date. 

Otherwise the test should fail.
As the link is not accessibly by clients, it should fail the test as the interoperability is not ensured.
Unfortunately now such an XML file will pass the test even if the XML is not self-valid.

Maybe I am wrong, but this is my understanding.

Until these two tests will be implemented, I expect the bug to remain opened and the code to be reverted to its initial.
