### ISSUE TITLE
Metadata (TG version 1.3) keyords from other dictionaries are not acceped

### ISSUE THREAD

**Issue by iuriemaxim** [INSPIRE-MIF/helpdesk-validator#197]
A metadata file made according to version 1.3 of the TG for Metadata will not pass the tests if it has keywords from other dictionaries then those present in the code.

However, both TG 1.3 and 2.0 allows users to provide other keywords from other dictionaries.

Test that fails: md.iso.f.1: Dataset keyword

Even the text of the test is incorrect according to TG. It states:
"The test checks for each descriptiveKeywords block if it references either http://www.eionet.europa.eu/gemet/inspire_themes or any duplicate of that thesaurus, e.g. http://inspire.ec.europa.eu/theme."

The test should not check that **EACH** descriptiveKeywords block is referenced to that particular schema, but that there is **AT LEAST ONE** descriptiveKeyword block that is referenced to that particular schema.

For example adding the keyword "National" to indicate the "Spatial Scope" of the dataset as required by INSPIRE MIG in 2019 as can be seen at
https://webgate.ec.europa.eu/fpfis/wikis/display/InspireMIG/Spatial+scope+code+list
will fail the test.

<<gmd:descriptiveKeywords>>
	<<gmd:MD_Keywords>>
		<<gmd:keyword>>
			<gmx:Anchor xlink:href="http://inspire.ec.europa.eu/metadata-codelist/SpatialScope/national">National</gmx:Anchor>
		</gmd:keyword>
		<<gmd:thesaurusName>>
			<<gmd:CI_Citation>>
				<<gmd:title><
					<gmx:Anchor xlink:href="http://inspire.ec.europa.eu/metadata-codelist/SpatialScope">Spatial scope</gmx:Anchor>
				</gmd:title>
				<<gmd:date>>
					<<gmd:CI_Date>>
						<<gmd:date>>
							<gco:Date>2019-05-22</gco:Date>
						</gmd:date>
						<<gmd:dateType>>
							<gmd:CI_DateTypeCode codeList="http://standards.iso.org/iso/19139/resources/gmxCodelists.xml#CI_DateTypeCode" codeListValue="publication">publication</gmd:CI_DateTypeCode>
						</gmd:dateType>
					</gmd:CI_Date>
				</gmd:date>
			</gmd:CI_Citation>
		</gmd:thesaurusName>
	</gmd:MD_Keywords>
</gmd:descriptiveKeywords>

Same is happening for keywords from external dictionaries (i.e. from World Meteorological Organization):

<<gmd:descriptiveKeywords>>
	<<gmd:MD_Keywords>>
		<<gmd:keyword>>
			<gmx:Anchor xlink:href="https://codes.wmo.int/grib2/codeflag/4.2/_0-0-0">Temperature</gmx:Anchor>
		</gmd:keyword>
		<<gmd:thesaurusName>>
			<<gmd:CI_Citation>>
				<<gmd:title>>
					<gmx:Anchor xlink:href="https://codes.wmo.int/bufr4/codeflag">WMO Codes Registry, Register: GRIB2 codes and flags, Register: Parameter number, version 1</gmx:Anchor>
				</gmd:title>
				<<gmd:date>>
					<<gmd:CI_Date>>
						<<gmd:date>>
							<gco:Date>2014-09-03</gco:Date>
						</gmd:date>
						<<gmd:dateType>>
							<gmd:CI_DateTypeCode codeList="http://standards.iso.org/iso/19139/resources/gmxCodelists.xml#CI_DateTypeCode" codeListValue="publication">publication</gmd:CI_DateTypeCode>
						</gmd:dateType>
					</gmd:CI_Date>
				</gmd:date>
			</gmd:CI_Citation>
		</gmd:thesaurusName>
	</gmd:MD_Keywords>
</gmd:descriptiveKeywords>

Iurie

Note: version 1.3 of the TG for Metadata is discontinued from December 2019, being replaced by version 2.0 after 3 years of coexistence.
**The tests for version 2.0 of the metadata files will not fail this test. There is correctly implemented.**

**Comment by danielnavarrogeo** [comment]
Dear @iuriemaxim 

The metadata 1.3 and metadata 2.0 corresponds with different Technical Guidelines and there is not backward compatibility between them.

Additionally, the support to metadata 1.3 ended on December 2019. So the discussion is not meaningful anymore.

Regards
