### ISSUE TITLE
Inconsistency - Temporal Reference System in metadata files has manual validation in version 1.3 tests, while in version 2.0 is automatic

### ISSUE THREAD

**Issue by iuriemaxim** [INSPIRE-MIF/helpdesk-validator#198]
Even if there seems not to be any significant differences regarding Temporal Reference in version 1.3 of the TG for Metadata and version 2.0 of the TG, the Temporal Reference System has a manual validation in version 1.3 (md-iop.a.2: Temporal Reference System), while in version 2.0 the validation is automatic (md common req C.11: Temporal Reference).

Probably a manual validation as the one performed for version 1.3 (md-iop.a.2) should be added for the version 2.0 validation, or this manual validation should be removed from version 1.3 or the test that is used for version 2.0 to be used also for version 1.3.

Or probably there is an explanation why there is this difference.

Iurie

**Comment by danielnavarrogeo** [comment]
Dear 

The metadata 1.3 and metadata 2.0 corresponds with different Technical Guidelines and there is not backward compatibility between them.

Additionally, the support to metadata 1.3 ended on December 2019. So the discussion is not meaningful anymore.

Regards
