### ISSUE TITLE
Metadata (TG version 1.3) test should be marked as DEPRECATED

### ISSUE THREAD

**Issue by iuriemaxim** [INSPIRE-MIF/helpdesk-validator#199]
According to the TG for metadata version 2.0 available at https://inspire.ec.europa.eu/id/document/tg/metadata-iso19139
the transition period for TG version 1.3 expired in 19 December 2019.

Therefore the text "**Metadata (TG version 1.3)**" should appear in the validator as "**Metadata (TG version 1.3) - DEPRECATED from 19-12-2019**".

The text at page X in the TG version 2.0 states:

_"As many Member States have already implemented the previous version of the Technical Guidance
for metadata, the transition between version 1.3 and 2.0 will require some developments. It is
especially true for elements where it has been necessary to modify or clarify the structure or content of the required XML elements. The metadata handling and validating tools created to comply with the Technical Guidance version 1.3 may need updating to fully comply with this version.
To facilitate a smooth transition from version 1.3 to version 2.0, a transitional period of 3 years has
been defined, starting from 19 December 2016. During this period, the metadata records compliant
with both version 1.3 and 2.0 implementations will be considered as “compliant with the INSPIRE
Technical Guidelines for Metadata”. During the transitional period, the validator used in the INSPIRE
geoportal will validate against and will provide validation reports for both versions 1.3 and 2.0. The
better result will be used for the value of the compliance meter. After the transitional period, the
geoportal will only validate against version 2.0."_

**Comment by danielnavarrogeo** [comment]
Dear @iuriemaxim 

Thank you for your suggestion. We will consider it in future releases.

Regards
