### ISSUE TITLE
Workshop on the ETF validator

### ISSUE THREAD

**Issue by MarcoMinghini** [INSPIRE-MIF/helpdesk-validator#20]
During the last 2017.4 sub-group meeting, the idea was once again raised, whether it would be useful to organise a workshop at the JRC with national INSPIRE implementers using the ETF validator, to collect and discuss improvement proposals for the software.

Thus, we would like to collect your feedback on the following questions:
- Is this something your national implementers have requested?
- What should be the main purpose(s) of the workshop?
- How many people would you expect to participate from your country?
- What kind of activities should such a workshop include (discussions, demos, presentations, exercises, ...)?
- What could be other alternatives for collecting direct feedback from national implementers?

Please provide your answers by simply commenting this issue.
Thank you.

**Comment by AntoRot** [comment]
Here the text of the email I sent to you:

We are interested in the proposed workshop on ETF validator.
 
So far, the participants from Italy should be 3/4  people.
 
I think that the successful organizational schema of the workshop on the Re3gistry software could be also adopted in that occasion. So, the workshop should include sessions of presentation, discussion on improvement proposals and open issues, demos and exercises.
 
Since recently some technical working groups have been set up in Italy under the coordination activities for the implementation of INSPIRE Directive, those WGs can be the place for the national discussions. We already have involved them and we expect appropriate feedback.

**Comment by bgsmase** [comment]
We are not aware of UK national implementers using the validator and haven't had any requests for support.

**Comment by IGNCNIG** [comment]
In Spain the validator is used for several organizations to validate their metadata and it is an important tool. We are interested in this workshop in order to clarify some questions and exchange ideas and difficulties

**Comment by grillmayer** [comment]
In Austria the ETF is used from many organiations to validate metadata and dataset for all ETF available annex I . We also use the ETF as referenc implementation within our nationale Workshops to demonstrate the benefits of harmonsied datasets and to get an better understanding in GML Encoding. We are interested in a workshop in which we can discuss further developments and develop possible suggestions for improvement. I think 1-2 Person form Austria INSPIRE Community will participate.

**Comment by hogredan** [comment]
In Germany we just started to develop a new national validator. We like to include the ETF and its ETS in this new version. Thus, we are highly interested in this workshop in order to share questions and experiences regarding the use of ETF in other environments. I would expect 2-3 participants from Germany.

**Comment by MarcoMinghini** [comment]
As reported in issue #34, SK is also interested in a workshop, focused on developer-related topics:
- ETS extension and customisation (e.g. for MD TG 2.0)
- usage of the ETF API, in particular how to extract customised reports (this is also related to the discussion in issue #47)

**Comment by MarcoMinghini** [comment]
**2017.4 meeting 2019-05-22**

The workshop is planned for 2 days in September 2019. 

- JRC will come up with a draft agenda, for a 2-day workshop in September.
- JRC will start collecting nominations of people to attend as well as additional topics or suggestions.

**Comment by VeronikaKusova** [comment]
The Czech Republic is also interested in the workshop - especially on ETS extensions and other developer related topics. 2 people would like to participate.

**Comment by MarcoMinghini** [comment]
Dear all,
once again, thanks for the interest in the workshop on the INSPIRE reference validator and the suggestions you made.

We have officially started to organize the workshop, that will take place at the JRC in Ispra on **October 1-2, 2019**.

The workshop will cover two full days: on the first day it will address users of the validator, on the second day it will address developers working with the Validator.

At this preparatory stage, we would like to know how many people are interested to attend each workshop day and what are the topics they are most interested in.

For this reason, we setup a survey where you can express interest to attend the workshop and indicate your preference about the day(s) to attend and the topics to be covered: https://ec.europa.eu/eusurvey/runner/Validator-Workshop

We kindly ask you to circulate this message to the people from your countries who are working with the Validator, either as users or developers. The deadline for providing the expressions of interest is July 31, 2019.

Thank you.

**Comment by MarcoMinghini** [comment]
Dear all,
just a reminder - especially for those who expressed interest in this GitHub conversation - to please forward the invitation to fill in the [survey](https://ec.europa.eu/eusurvey/runner/Validator-Workshop) to your national experts (users/developers working with the INSPIRE validator). We would like that each person interested in attending the workshop fills in the survey by July 31.
Thank you.

**Comment by MarcoMinghini** [comment]
Thank you for expressing interest in the workshop on the INSPIRE Validator. We have now closed the survey. We will come back soon with an agenda proposal based on your input to the survey.

**Comment by MarcoMinghini** [comment]
Dear all,
attached you can find a draft agenda of the workshop.

Please note that Day 1 (workshop for users) is fully booked, while there are still a couple of seats available for Day 2 (workshop for developers). In case you are interested in the latter, please contact us.

[Workshop INSPIRE Validator 20191001-02 - draft agenda.pdf](https://github.com/inspire-eu-validation/community/files/3541282/Workshop.INSPIRE.Validator.20191001-02.-.draft.agenda.pdf)

**Comment by MarcoMinghini** [comment]
Workshop materials have been finalized and are now available in this new folder in the Community space: https://github.com/inspire-eu-validation/community/tree/master/training%20material

This issue will be soon closed unless there are other topics (relevant to the workshop) still to be discussed.
