### ISSUE TITLE
Inconsistency - Access and use conditions in metadata files has manual validation in version 1.3 tests, while in version 2.0 is automatic

### ISSUE THREAD

**Issue by iuriemaxim** [INSPIRE-MIF/helpdesk-validator#200]
The Access and use conditions has a manual validation in version 1.3 (md-iso.a.3: Access and use conditions), while in version 2.0 the validation is automatic (md common req C.17).

It is true that there are significant differences regarding Access and use conditions in version 1.3 of the TG for Metadata and version 2.0 of the TG, but none of these differences seems that can be considered as a reason to have a different approach for testing version 1.3 and version 2.0 metadata files.

Probably for version 1.3 test, either:
1) this manual validation in version 1.3 (md-iso.a.3) should be split into a manual validation and an automatic validation (similar to the one for version 2.0, but with different test as there are significant changes)
2) this manual validation in version 1.3 (md-iso.a.3) should be replaced with an automatic validation (similar to the one for version 2.0, but with different test as there are significant changes) and no manual validation to be required.

In this case for version 2.0 test:
1) if option 1 was chosen for version 1.3 test and the Access and use conditions are neither "no conditions apply" or "conditions unknown", a manual validation may be required for version 2.0 in order to ensure that "Descriptions of terms and conditions, including where applicable, the corresponding fees shall be provided through this element or a link where these terms and conditions are described."
2) if option 2 was chosen for version 1.3 test then no modifications are necessary for version 2.0 test.

Or probably there is an explanation why there is this difference.

This is also in relation with issue https://github.com/inspire-eu-validation/community/issues/194

A harmonization between the version 2.0 and version 1.3 tests for metadata ensure an easier transition from version 1.3 metadata files (discontinued from December 2019) to version 2.0 metadata files (supported by TG from 2016) for those data providers that did not performed this transition yet.

Iurie

**Comment by danielnavarrogeo** [comment]
Dear @iuriemaxim 

The metadata 1.3 and metadata 2.0 corresponds with different Technical Guidelines and there is not backward compatibility between them.

Additionally, the support to metadata 1.3 ended on December 2019. So the discussion is not meaningful anymore.

Regards
