### ISSUE TITLE
Indication of local XSD schemas that are not accessible by clients are passing viewService WMS test

### ISSUE THREAD

**Issue by iuriemaxim** [INSPIRE-MIF/helpdesk-validator#201]
Due to current modification performed when the issue https://github.com/inspire-eu-validation/community/issues/191 was solved, now it is possible to indicate local XSD schemas that are not accessible over the internet.

If the XSD schema referred in the header of the XML is not accessible over the internet, the XML file is not valid (self-valid).

Even more, the local schemas can have a completely different content than the official INSPIRE schemas located at https://inspire.ec.europa.eu/schemas/ and users may create XML files that would not validate against the official schemas, unless the tests would verify the file against the official schemas and not against the declared schemas in the XML file and therefore the interoperability would not be ensured.

For example an XML file having this content in the header would not be a valid XML file:

xsi:schemaLocation="http://inspire.ec.europa.eu/schemas/inspire_vs/1.0 http://myserver/service/Schemas/inspire/inspire_vs/1.0/inspire_vs.xsd"

An XML validator would report that the XSD schema was not found.

It is necessary to verify that:
1) the URLs provided in the xsi:schemaLocation element are accessible by clients
2) the URLs provided in the xsi:schemaLocation element are up-to-date

As indicated by @janneumann1, see http://portal.opengeospatial.org/files/?artifact_id=38867 - section 12.4 that mentions:

_"A server may reference an exact copy of these schemas located elsewhere, as long as they are readily accessible by clients. For example, it may be desirable to place the referenced schemas on the same network server as the OWS server, since that decreases the number of points of possible network failure. Such local copies of schemas should be organized into directories similar to http://schemas.opengis.net/. The server owner should insure that any such local copies are kept up-to-date with respect to the authoritative files at http://schemas.opengis.net/."_

Probably one solution for the issue https://github.com/inspire-eu-validation/community/issues/191 would be for JRC to make a redirect from http://inspire.ec.europa.eu/schemas/inspire_vs/1.0/ to http://inspire.ec.europa.eu/schemas/inspire_vs/1.0/inspire_vs.xsd
In this way, probably it would not be anymore necessary to declare the location of the schema for http://inspire.ec.europa.eu/schemas/inspire_vs/1.0/

Most if not all INSPIRE schemas have the same problem and need to be declared in the xsi:schemaLocation element in the header of the XML file. 

Therefore when removing the validation that the schemas in the xsi:schemaLocation element are not the official ones (in any test, not just for WMS GetCapabilities response), if the URL provided is not accessible over internet, than the XML files are not valid. Furthermore if the XSD files are accessible, but not up-to-date, the XML file would validate against the schemas declared in its header, but may not be valid against the official XSD schemas. In this way neither interoperability for the data sets, neither interoperability for the services cant be ensured.

Iurie

**Comment by danielnavarrogeo** [comment]
This issue is duplicated. issue #191.

**Comment by iuriemaxim** [comment]
@carlospzurita This was wrongly indicated as duplicate of the 191.

The issue is to indicate that the validator is not checking if the schemas are accessible by clients, nor that the local copies are kept up to date.

"A server may reference an exact copy of these schemas located elsewhere, as long as they are **readily accessible by clients**. For example, it may be desirable to place the referenced schemas on the same network server as the OWS server, since that decreases the number of points of possible network failure. Such local copies of schemas should be organized into directories similar to http://schemas.opengis.net/. The server owner should insure that any such **local copies are kept up-to-date** with respect to the authoritative files at http://schemas.opengis.net/."
