### ISSUE TITLE
md common req C.11: Temporal Reference

### ISSUE THREAD

**Issue by alitka** [INSPIRE-MIF/helpdesk-validator#202]
Issue related to https://github.com/inspire-eu-validation/community/issues/175

- [x]  description of the steps to reproduce the issue
1. go to http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp and select "Common Requirements for ISO/TC 19139:2007 based INSPIRE metadata records"
2. start the test and upload an externale xml-file
case 1 with codeListValue to "creation": [dataset_DE_temporalReferenceCreation.zip](https://github.com/inspire-eu-validation/community/files/4108950/dataset_DE_temporalReferenceCreation.zip)
case 2 with codeListValue to "revision": [dataset_DE_temporalReferenceRevision.zip](https://github.com/inspire-eu-validation/community/files/4108951/dataset_DE_temporalReferenceRevision.zip)
- [x] used browser and version: Firefox Browser 72.0 (64-Bit)
- [x] a screenshot illustrating the problem
case 1 with codeListValue to "creation":
![grafik](https://user-images.githubusercontent.com/29542183/73077381-593c7a00-3ec0-11ea-8fe1-bf583e5ebc0d.png)
case 2 with codeListValue to "revision": 
![grafik](https://user-images.githubusercontent.com/29542183/73077480-8a1caf00-3ec0-11ea-9221-3fd017f0246c.png)
- [x] the Test Report
case 1 with codeListValue to "creation": [report_DE_temporalReferenceRevision.zip](https://github.com/inspire-eu-validation/community/files/4108978/report_DE_temporalReferenceRevision.zip)
case 2 with codeListValue to "revision": [report_DE_temporalReferenceCreation.zip](https://github.com/inspire-eu-validation/community/files/4108977/report_DE_temporalReferenceCreation.zip)
- [x] the name of the Test that failed: 
case 1 with codeListValue to "creation": md common req C.12: Max One Date of Creation
case 2 with codeListValue to "revision": md common req C.13: Not more than one Date of Last Revision

To avoid this error, you have to change the codeListValue to "publication", but this couldn't be the solution! Could you check C.11 in combination with C.12 and C.13, please?

Thanks & regards.

**Comment by danielnavarrogeo** [comment]
Dear @alitka 

The issue has been addressed and deployed in [staging environment](http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/).

Could you please check it and confirm that the issue has been fixed?

Regards

**Comment by alitka** [comment]
Dear @danielnavarrogeo, 
I have tested the xml-files again, addional another xml-file also and everything is working properly.
Thanks and best regards!

**Comment by danielnavarrogeo** [comment]
Thank you @alitka  for your feedback.

Regards

**Comment by fabiovin** [comment]
Dear @danielnavarrogeo,
I have tested (in staging) the attached service metadata file in which all the three dates (creation, publication and revision) are present in the element: 
```
      <gmd:identificationInfo>
            <srv:SV_ServiceIdentification>
               <gmd:citation>
                  <gmd:CI_Citation>
```
One of them (revision) is encoded as `<gco:DateTime>`, this is correct but the validator throws an error for C.11 (http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/v2/TestRuns/EIDebddc447-d571-48a3-aef5-60771b920289.html).

If I try to encode it as `<gco:Date>` the error disappears (http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/v2/TestRuns/EIDe2cc00aa-77af-4c2d-b2df-98232856d031.html).

Could you please verify?

Thanks

[1.iso19139_mod_C.11-test.xml.zip](https://github.com/inspire-eu-validation/community/files/4170544/1.iso19139_mod_C.11-test.xml.zip)

**Comment by danielnavarrogeo** [comment]
Dear @fabiovin 

We will verify it and keep you posted.

Regards

**Comment by danielnavarrogeo** [comment]
Dear @fabiovin 

The error is due to not accepting a DateTime element without defining the time zone.

The following element is currently throwing an invalid date output:
```
<gco:DateTime>2013-09-30T11:15:00</gco:DateTime>
```
While adding Z or time zone validates properly:
```
<gco:DateTime>2013-09-30T11:15:00Z</gco:DateTime>
```
and
```
<gco:DateTime>2013-09-30T11:15:00+07:00</gco:DateTime>
```
We think the first option is also valid, as ISO 8601 considers that as a special case for local times. Therefore, we are going to update the test to accept that format as well.

Regards

**Comment by danielnavarrogeo** [comment]
Dear @fabiovin 

The DateTime without timezone is now accepted.

You can check it in [staging ](http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/)environment.

Regards

**Comment by fabiovin** [comment]
Dear @danielnavarrogeo,

I tested it and now the C.13 fails (http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/v2/TestRuns/EIDdbdaf2e1-f5a2-40ee-a06c-586915d0b06c.html), with the same behaviour, if I encode the element as <gco:Date> the errors disappears.

**Comment by danielnavarrogeo** [comment]
Dear @fabiovin 

It seems there was an error rebuilding staging.

We will rebuild it again and tell you when you can check it.

Regards

**Comment by danielnavarrogeo** [comment]
Dear @fabiovin 

You can check it again.

Sorry for the inconvenience.

Regards

**Comment by fabiovin** [comment]
Dear @danielnavarrogeo,
no problem!
Now it works!

**Comment by danielnavarrogeo** [comment]
Thank you @fabiovin for your feedback.
