### ISSUE TITLE
Production issues with GML validation

### ISSUE THREAD

**Issue by carlospzurita** [INSPIRE-MIF/helpdesk-validator#203]
Since some days ago, we have been experiencing some problems in the INSPIRE validator. This problems are related to an issue with the GML validation. There is a bug with the srsName and srsDeclaration detection from the <gml:posList> tag. By default the dimension is set to 2, and this provokes an error in the geometry parsing that throws an uncontrolled exception, and it ends in a memory leak.

We are working on a hotfix for this issue, but for now, it would be advisable to include the attributes srsName and srsDimension not only on the wrapping Geometry tag, but also on the <gml:posList> tag. This prevents the memory issues from happening and the validation can be performed.

We have an open discussion for this issue on the bugfix repository https://github.com/etf-validator/etf-webapp/issues/214 , which you can use as a technical reference.

Dear @DeordD , we have found references to the state Baden-Württemberg (BW) in some of the datasets that were related to this issue. Do you have any information on the user that is submitting the datasets, and maybe propose the workaround of the srsDimension?

**Comment by ghost** [comment]
Dear @carlospzurita, @MarcoMinghini  

thanks a lot for the information. 

> Dear @DeordD , we have found references to the state Baden-Württemberg (BW) in some of the datasets that were related to this issue. Do you have any information on the user that is submitting the datasets, and maybe propose the workaround of the srsDimension?

This is already communicated to the user which submitted the dataset. GML dataset won't be validated until this problem is fixed.  

Kind regards

**Comment by carlospzurita** [comment]
We have uploaded a workaround for this issue on [staging](http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/) . During validation, we take the `srsDimension` declared on the parent node of the GML entity, and we include it on the `gml:posList` if it exists. This way we prevent the exception in parsing the geometry. This is a temporary solution, and needs to be further analyzed, but at least you can submit your GML datasets to staging, check the results and share some feedback about the workaround.

**Comment by carlospzurita** [comment]
Dear @DeordD 
Did you or you're data providers had the opportunity to validate the GML with the problematic CRS, an check if the solution works fine?

**Comment by ghost** [comment]
Dear @carlospzurita ,

data provider has tested the same GML dataset on staging instance against following CCs:

![grafik](https://user-images.githubusercontent.com/38787131/76513983-77057480-6457-11ea-97c1-ce2c989a2736.png)

Following problem 

> this provokes an error in the geometry parsing that throws an uncontrolled exception, and it ends in a memory leak.

didn't occur. GML Validation was fully performed. 

Thanks a lot for the fix.

**Comment by danielnavarrogeo** [comment]
Thank you @DeordD for the feedback.

Regards
