### ISSUE TITLE
Validator frozen during test suite "Common Requirements for ISO/TC 19137:2007 based INSPIRE metadata records"

### ISSUE THREAD

**Issue by fdumortier** [INSPIRE-MIF/helpdesk-validator#204]
Hi,

My browser is Mozilla Firefox 72.0.2 (64 bits).

I used the validator to apply the test suite "Common Requirements for ISO/TC 19137:2007 based INSPIRE metadata records" on a full export of our CSW metadata records (90 records) in XML. To generate this XML file I invoked [this service](https://geobru-geonetwork.irisnet.be/geonetwork/srv/fre/csw?request=GetRecords&service=CSW&version=2.0.2&resultType=results&namespace=xmlns%28csw%3Dhttp%3A%2F%2Fwww.opengis.net%2Fcat%2Fcsw%2F2.0.2%29%2Cxmlns%28gmd%3Dhttp%3A%2F%2Fwww.isotc211.org%2F2005%2Fgmd%29&outputFormat=application%2Fxml&outputSchema=http%3A%2F%2Fwww.isotc211.org%2F2005%2Fgmd&startPosition=1&maxRecords=100&elementSetName=full&constraint=keyword+EQ+%27Reporting%20Inspire%27&constraintLanguage=CQL_TEXT&constraint_language_version=1.1.0&typeNames=gmd%3AMD_Metadata%2Cgmd:MD_Metadata). After a few seconds, the validator seems to be frozen. I uploaded a screen shot.
![validator-frozen](https://user-images.githubusercontent.com/28805451/73285117-d5eb9300-41f5-11ea-92a3-b8aac5d7a445.png)

Any hint to solve this issue?

Kind regards,

François

**Comment by danielnavarrogeo** [comment]
Dear @fdumortier 

The test has to download all the external files (i.e. schemas) for each validated metadata (90 times in this case) and this might take some time to finish.

Currrently there is a performance improvement, based on caching the external files, planned for the next release. We will let you know when it is ready for testing.

Regards.

**Comment by fdumortier** [comment]
Thanks ! Indeed, I got the results after more than 1 hour. Kind regards, François

**Comment by MarcoMinghini** [comment]
Dear @fdumortier,
we have now implemented the change mentioned above, see https://github.com/inspire-eu-validation/community/issues/205. You can test it in the [staging instance of the Validator](http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/), where the validation should be faster.
