### ISSUE TITLE
Validating Interoperable data sets in GML reports "Test Run initialization failure" if the links provided for validation are taking long time to be generated on the server

### ISSUE THREAD

**Issue by iuriemaxim** [INSPIRE-MIF/helpdesk-validator#207]
While validating **Interoperable data sets in GML (Guidelines for the Encoding of Spatial Data version 3.3)** and using the following conformance classes:
- Data consistency, General requirements
- INSPIRE GML application schemas, General requirements
- Information accessibility, General requirements
- Reference systems, General requirements

the validator reports "Test Run initialization failure: unknown error" if the links provided for validation are taking long time to be generated on the server.
An example of such a link (short-url to a WFS request) is:
https://inspire.meteoromania.ro/ids/OM_Observation.EnvironmentalMonitoringFacility.15335.TemperatureMinimumDailyCLIMAT.AllValuesWML20 
The error is indicating if the above link while selecting "Remote file (URL)" as "Data source".

The message "Test Run initialization failure: unknown error" is provided after about 60 seconds after pressing "Start button".

Time to generate the file with 21274 records on the server is about 50 seconds.

Most probably the validator provides the error "Test Run initialization failure" even if the file is valid, because the validator is not retrieving the file in a certain time.

The resource can be validated only if the file is firstly downloaded locally (i.e.: by typing the request in the browser and saving the file locally) and by using the option "File upload" instead of "Remote file (URL)".
The validator will report that the file is valid:
http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/v2/TestRuns/EIDfd989c93-96ba-4138-ba7f-23d07cfc4365.html

But this scenario does not allow for automation of the validation, neither is facile.

Another similar request with less records will not trigger the "Test Run initialization failure". A link to such an example is:
https://inspire.meteoromania.ro/ids/OM_Observation.EnvironmentalMonitoringFacility.15015.RelativeHumiditySYNOP.AllValuesWML20

The validator will indicate the file as being valid:
http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/v2/TestRuns/EIDecfa27bd-448d-44a3-8ea9-635f1ab7cfb7.html

Hope that there is a possibility to increase the time necessary for the WFS to generate the file.

Best regards,
Iurie Maxim
Essensys Software
Romania

**Comment by iuriemaxim** [comment]
The problem was solved due to some improvements that we made to DB and ETL (50 seconds -> 10 seconds). We could try to prepare a test with a larger number of records (i.e.: >100.000) that would take more than a minute to be generated by the WFS server.

**Comment by iuriemaxim** [comment]
Below are two similar requests, one with more than 75.000 records that takes about 30 seconds to be generated by the WFS server and the second one with more than 50.000 records that is generated in about 20 seconds. Usually the first will fail and the second will pass:

Request with more than 75.000 records
https://inspire.meteoromania.ro/WIGOS-WFS/ows?service=WFS&version=2.0.0&request=GetFeature&typeNames=om%3AOM_Observation&outputFormat=gml32&featureID=OM_Observation.EnvironmentalMonitoringFacility.15170.TemperatureAverageDailyCLIMAT.AllValuesWML20,OM_Observation.EnvironmentalMonitoringFacility.15020.TemperatureAverageDailyCLIMAT.AllValuesWML20,OM_Observation.EnvironmentalMonitoringFacility.15360.TemperatureMinimumDailyCLIMAT.AllValuesWML20
 
Request with more than 50.000 records
https://inspire.meteoromania.ro/WIGOS-WFS/ows?service=WFS&version=2.0.0&request=GetFeature&typeNames=om%3AOM_Observation&outputFormat=gml32&featureID=OM_Observation.EnvironmentalMonitoringFacility.15170.TemperatureAverageDailyCLIMAT.AllValuesWML20,OM_Observation.EnvironmentalMonitoringFacility.15020.TemperatureAverageDailyCLIMAT.AllValuesWML20

These two links should be used now in order to test the issue #207, instead of the previous ones.

More FeatureIDs can be added in the request if necessary.

**Comment by carlospzurita** [comment]
Dear @iuriemaxim 

All the operations that involves requests to external resources have a set timeout of 120 seconds. This is a value that is set up to let the machine resources of the validator be distributed between all the users in a balanced way. 

If you need to validate datasets this big, we would advise you to make `GetFeatures` request with fewer results, or download the features as a GML file and upload it for the TestRun (taking into account that the size limit in files is set to 20MB)

Kind regards.

**Comment by carlospzurita** [comment]
Dear @iuriemaxim 

Did you have any advances with this issue? We are going to move this to discussion, given that this is more related to a performance matter on the services communication and how to improve it.

Also, we recently upgraded the file size limit from 20MB to 50, so you can try to generate separete feature collections and upload them to the validator.

**Comment by iuriemaxim** [comment]
Dear @carlospzurita I suggest to close it by doing the following: 
- when testing GML data provided by a service it should be added a text stating that "there is a 120 seconds limitation for retrieving the dataset so please export data as a GML file and test it locally if the service is not able to serve the GML file in due time or better create cached GML files to be served by accessing the URL of the service" 
- and when testing a GML file loaded within the validator to add a text stating that "there is a limitation of 50 MB per GML file, so if larger files should be tested, then they should be split into smaller files."

However, the issue is related to a real test of the data, in the case if the ETF validator will be used to automatically check the data conformity within the Official INSPIRE Geoportal, to assess the degree to which a certain Member State and subsequently each Data Provider accomplished the Directive Obligations.
In case the dataset is huge (as in most cases it is normal to be for country wide datasets), then it will be the case that the data served by the service will be qualified as not valid even if the data is conformant, We found a solution to cache the data daily and to create redirects from those specific WFS requests directly to the daily cached GML files, but I am not expecting too many data providers to do this. Subsequently it would be most probably that some automatic tests to be considered fail even if actualy the data is conformant.
A potential solution would be to create a separate ETF instance to be used when automatically vaildating the content of the Geoportal and in that instance to set a higher time and a higher file size that should be set after manually analyzing those services which will fail due to time/size constrains.

What do you think?

Iurie

**Comment by carlospzurita** [comment]
Dear @iuriemaxim 

You are right that country wide datasets can take a lot of space and it may need a dedicated instance for testing the conformity. We need to discuss internally how to approach this in the future.

About the improvements on the validator side that you mentioned, in the case of services it would be a nice addition to have a message stating the timeout, and we are going to explore the best way to include it. For uploaded datasets, there is already a tooltip that states the maximum size of the dataset file.

**Comment by iuriemaxim** [comment]
@carlospzurita Thank you for taking into discussion the need of a dedicated instance for testing the conformity of data within the EC INSPIRE Geoportal with higher settings to allow country wide datasets validations.

You are right that for file size there is a note on mouse over the question mark as I did not noticed it. Just to understand, it is possible to upload 10 files of 50MB, but it is not possible to upload one file of 500 MB?

![image](https://user-images.githubusercontent.com/20813598/90659858-d741e300-e24d-11ea-8dfc-0b9ceedb3afb.png)

For testing services there is a text that can include also the limitation to 200 seconds. However I would suggest to be more clear that Direct download services requests are expected actually and not a ftp/http location where the GML or zip file resides, as actually the test is addressing to test the features that are in a dataset exposed via a download service, such as ATOM, WFS, WCS or SOS and not just a ftp/http link which would be a simple web service. It should rather state "URL of the download service request to access the feature type from the dataset."

![image](https://user-images.githubusercontent.com/20813598/90660393-85e62380-e24e-11ea-8188-f8f1a06531c1.png)

More details could be actually provided here as the information there is not too useful.

![image](https://user-images.githubusercontent.com/20813598/90661554-048f9080-e250-11ea-9cfb-6ebfe5ba656d.png)

**Comment by carlospzurita** [comment]
Dear @iuriemaxim 

We are adding the tooltip on the Start Test dialog specifying that a service endpoint URL needs to be provided, and that requests to said service have a timeout of 120 seconds.

**Comment by carlospzurita** [comment]
We have uploaded the enhancement discussed on the [staging instance](http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp). Please check it out and share any comments with us (you may need to clean the browser cache or open it up in a private window).

**Comment by iuriemaxim** [comment]
@carlospzurita 

Sorry but it is not clear at all what was implemented.

![680F55AF-CBE9-49CD-91DA-AAD33873EC44](https://user-images.githubusercontent.com/20813598/92414840-ad9a1e80-f15e-11ea-940c-b36ee3f0f8f2.jpeg)

**Comment by carlospzurita** [comment]
Sorry for the inconveniences, the change was applied to the services tests but not on the dataset tests. It has been modified accordingly.

**Comment by iuriemaxim** [comment]
@carlospzurita it is not the URL of an OGC service endpoint that should be indicated, but the URL request to an INSPIRE Spatial Data Service that retrieves spatial data encoded in GML format. I think that the word “request” is important as well as to use the therms that are in the INSPIRE Directive.

Any other option listed in the text is not an option according to INSPIRE Implementing Rules so I do not see any reason of listing them, except to induce some confusion.

**Comment by carlospzurita** [comment]
We have updated the message accordingly on the staging instance.

**Comment by iuriemaxim** [comment]
@carlospzurita That's fine now. Thank you.
