### ISSUE TITLE
While performing a Direct WFS Conformance test the validator will report a SpatialJoin error if the WFS is serving only points and multipoints due to an issue in CITE test

### ISSUE THREAD

**Issue by iuriemaxim** [INSPIRE-MIF/helpdesk-validator#209]
While performing a Download service - Direct WFS Conformance test for a WFS that does not serves an AbstractSurfaceType, the validator will report a Spatial joins (OGC 09-025r2: 7.9.2.5.3, A.1.12) due to the following issue in CITE test: opengeospatial/ets-wfs20#164

Link to test: https://inspire.meteoromania.ro/WIGOS/WFS?service=WFS&request=GetCapabilities

Result of the test: http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/v2/TestRuns/EID70a9a270-6b58-42a3-92b9-19d66767935b.html

A separate issue #208 is reported for the Spatial Filter CITE issue that can be seen in the above result of the test.

Until this issue will be fixed in CITE, this test should be skipped either for WFS that does not declare that serves an AbstractSurfaceType, either should be skipped at all for all geometries (if getting the geometry type is to difficult).

It would be highly appreciated if the EC validator would not be tied to other validators with their own issues.

Best regards,
Iurie Maxim
Essenys Software
Romania

**Comment by danielnavarrogeo** [comment]
Dear @iuriemaxim 

Thank you for your suggestions.

The INSPIRE Reference Validator is designed to be modular and to make use of OGC TEAM Engine so we do not reinvent the wheel. The issue should be solved in TEAM Engine.

You might be interesting in opening this issue in the corresponding OGC repository.

Regards

**Comment by iuriemaxim** [comment]
As it was asked to open this issue in the corresponding OGC repository, it should be seen that the issue was already opened in the corresponding OGC repository as it was mentioned in the description of the issue (opengeospatial/ets-wfs20#164)

I agree that the wheel should not be reinvented, but as the OCG CITE Team Engine test for WFS has some issues that affect the INSPIRE Official ETF validator, something should be done at the level of the ETF validator.

Because the INSPIRE Official ETF validator is used:
- by data providers
- by national representatives 
- by EC
until this issue will be fixed in CITE, this test should be skipped in the validator in order not to trigger wrong errors.

**Comment by danielnavarrogeo** [comment]
answered in #215

**Comment by iuriemaxim** [comment]
Here is what is written in the code of the OGC CITE Teamengine test for WFS (https://github.com/opengeospatial/ets-wfs20/blob/master/src/main/java/org/opengis/cite/iso19142/joins/SpatialJoinTests.java )

![image](https://user-images.githubusercontent.com/20813598/74648092-a6d99900-5185-11ea-95ed-40f4a9460f76.png)

As it can be seen, the code is incomplete and there are three TODO mentioned in the code.
The test will pass if at least one geometry is declared as polygon or if at least two geometries are declared as lines. If the geometries are declared as abstract the test will fail. If all geometries are declared as points, the test will fail. Therefore all datasets that are composed of points will fail this test. Example of datasets composed of points are sensors (Environmental Monitoring Facilities data theme).

**Comment by MarcoMinghini** [comment]
Dear @iuriemaxim, as mentioned in #208 I can see that OGC is working to fix this issue (the work is indicated as being in progress). Let's see how this develops.

**Comment by MarcoMinghini** [comment]
Dear @iuriemaxim,
we are in contact with OGC and we have been informed that they are working on this issue; they have a potential solution but it is yet to be implemented as a fix. They will inform us once the corresponding PR has been merged.

**Comment by iuriemaxim** [comment]
According to https://github.com/opengeospatial/ets-wfs20/issues/164#

now the CITE test is indicating that the spatial join should be made manually.

Therefore there are two solutions:
- the INSPIRE validator should interpret the message from the CITE test and integrate that message in a manual validation message displayed with orange colour (short term solution)
- the CITE bug should be reopened to perform an automatic validation (long term solution).

**Comment by iuriemaxim** [comment]
@carlospzurita, @danielnavarrogeo  Please mark this issue as “under analysis”, as now the INSPIRE Validator should be changed in order to interpret the message from CITE validator.

**Comment by carlospzurita** [comment]
Dear @iuriemaxim 
We are going to discuss the necessary changes on the validator side to reflect this change. However, take into account that the change would not take place until the CITE fix goes live on their production site

**Comment by iuriemaxim** [comment]
@carlospzurita Thank you for adding the “under analysis” label to address this issue in th EC validator as well.

I will check the CITE version in production as I understood that there are several CITE versions in production. Can you please indicate which CITE production version is used by the EC validator, or the exact link to this specific WFS CITE test that is used by the validator?

**Comment by iuriemaxim** [comment]
@carlospzurita 

I tested the the following WFS service https://inspire-staging.meteoromania.ro/WIGOS/WFS?service=WFS&version=2.0.0&request=GetCapabilities

with the current OGC CITE version 1.33 in production for WFS 2.0 from 2020-04-28 (see release notes at https://cite.opengeospatial.org/te2/about/wfs/2.0.0/site/changelog.html)

![image](https://user-images.githubusercontent.com/20813598/86285821-fe851800-bbed-11ea-8eac-58732852088a.png)

and the OGC CITE production version is indicating that the issue was fixed and deployed in production

![image](https://user-images.githubusercontent.com/20813598/86285709-c8479880-bbed-11ea-8b9e-782563d45253.png)

Therefore there is no need to wait until the fix will be put into production by OGC as it is already there.

It is just to ensure that the EC INSPIRE Validator is using this last version from OGC Team Engine.

The OGC Team Engine validator is showing that the above mentioned WFS service is valid (needing some manual validation for Spatial Join) and I am expecting that the EC Validator to indicate the same.

This issue and issue https://github.com/inspire-eu-validation/community/issues/214 should be solved in order to have a Reference WFS service too.

Then we can say that the following metadata and services are valid and this could help other data providers to create valid metadata and services by looking at certain valid examples:

Services:
WFS: https://inspire-staging.meteoromania.ro/WIGOS/WFS?service=WFS&version=2.0.0&request=GetCapabilities (Conformance Class: Download Service - Direct WFS and Conformance Class: Download Service - Predefined WFS)
WMS: https://inspire-staging.meteoromania.ro/WIGOS/WMS?service=WMS&version=1.3.0&request=GetCapabilities (Conformance Class: View Service - WMS)
CSV: https://inspire-staging.meteoromania.ro/geonetwork/srv/eng/csw?SERVICE=CSW&VERSION=2.0.2&REQUEST=GetCapabilities (Conformance Class: Discovery Services - WCS)

Metadata according to TG version 2.0:
WFS: https://inspire-staging.meteoromania.ro/WIGOS/MD-WFS (Conformance Class 4)
WMS: https://inspire-staging.meteoromania.ro/WIGOS/MD-WMS (Conformance Class 4)
Dataset: https://inspire-staging.meteoromania.ro/WIGOS/MD-DS (Conformance Class 2)

Data according to the following conformance classes
![image](https://user-images.githubusercontent.com/20813598/86288233-3beba480-bbf2-11ea-8220-4fe92e2cdd68.png)

One Environmantal Monitoring Facilitiy
https://inspire-staging.meteoromania.ro/WIGOS/WFS?service=WFS&version=2.0.0&request=GetFeature&typeNames=ef:EnvironmentalMonitoringFacility&count=1

One Environmental Monitoring Network
https://inspire-staging.meteoromania.ro/WIGOS/WFS?service=WFS&version=2.0.0&request=GetFeature&typeNames=ef:EnvironmentalMonitoringNetwork&count=1

Information about one monitoring facility
https://inspire.meteoromania.ro/ids/EnvironmentalMonitoringFacility.15020

One observing capability from one monitoring facility
http://inspire.meteoromania.ro/ids/EnvironmentalMonitoringFacility.15020/RelativeHumiditySYNOP

One observation from one monitoring facility
https://inspire.meteoromania.ro/ids/OM_Observation.EnvironmentalMonitoringFacility.15020.RelativeHumiditySYNOP.AllValuesWML20

And so on.

We have also other valid metadata, services and datasets for protected areas, administrative units and geographical names that are passing also their respective Conformance Classes for Data Themes (Annex 1).

So we are just waiting for these two issues to be fixed and from our perspective the Validator is fine, just to revert those relaxed tests that are against the requirements stipulated in the Technical Guidelines.

However we did not tested:
WMTS
Predefined SOS
WCS Core
ATOM (we are not interested, as anything can be provided trough ATOM)

If there are any Predefined SOS and WCS services that are passing the tests, please let us know,

Hope it helps.
Iurie

**Comment by MarcoMinghini** [comment]
Dear @iuriemaxim, all,
from a discussion with the OGC staff, we were informed that:

* the TEAM Engine beta instance is updated every month, while the TEAM Engine production instance is updated every 6 months. Next release is expected at the end of July. Therefore, all the fixes of interest for INSPIRE are not yet available in the production instance, but only in the beta instance.

* we are internally discussing that, given this timeline, it would be good to have our INSPIRE Validator staging instance pointing to the TEAM Engine staging instance, so that new fixes/developments can be immediately checked by the INSPIRE community.

Best regards,
Marco

**Comment by iuriemaxim** [comment]
@MarcoMinghini This will help a lot, as waiting time of several months for CITE fix + deploying in production and then other several months for implementation in the staging version of the Inspire Validator and then into production version is almost a year or even more.

**Comment by iuriemaxim** [comment]
@MarcoMinghini Please provide a deadline until the staging version of the Team Engine will be used by the staging version of the Validator. We do believe that changing one URL with another is not too complicated.

**Comment by carlospzurita** [comment]
Dear @iuriemaxim 
The [staging instance](http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp) is now pointing to the beta TEAM engine endpoint at https://cite.opengeospatial.org/te2. You can check out there the latest modifications.

**Comment by iuriemaxim** [comment]
@carlospzurita I tested on staging validator the following WFS service https://inspire.meteoromania.ro/WIGOS/WFS?service=WFS&request=GetCapabilities

Results are available at http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/v2/TestRuns/EID26854130-5265-48c5-a463-9f99db4ae9dd.html

It can be seen in the image below that the text provided by OCG Team Engine specify that "The Spatial Join test will need to be applied manually.". Therefore it should not be reported as an error and should not be displayed with red color, but with orange and should be indicated that manual validation is needed.

![image](https://user-images.githubusercontent.com/20813598/88666610-fd5de280-d0e8-11ea-8e0d-5e3fb83df31f.png)

So I can confirm that the text is the same as the one provided by OGC TEAM Engine. It is just that it should not be indicated as an error, but as a necessary manual validation. Therefore the issue should be marked "under development" in order to be fixed by correctly interpreting the OGC TEAM Engine text.

I can also confirm that the production version is indicating another error: "Two feature properties are required, but received 0", so definitely the staging INSPIRE validator is pointing to a different OGC TEAM Engine endpoint.

Iurie

**Comment by iuriemaxim** [comment]
@carlospzurita Do you have any information regarding this issue?

**Comment by carlospzurita** [comment]
Dear @iuriemaxim 
The validator is not able to distinguish this manual check from a failure on a TEAM Engine report, because it is marked as FAIL in the XML response from the OGC endpoint.

![imagen](https://user-images.githubusercontent.com/10537778/91152999-eeeef080-e6bf-11ea-9623-9aa8b6973326.png)

**Comment by iuriemaxim** [comment]
@carlospzurita Can you then treat this issue with OGC or interpret the OGC response for this test in another way or simply skip the test until a solution will be available?

**Comment by carlospzurita** [comment]
Dear @iuriemaxim 

For now, the Test can't be interpreted in any other way if the response is marked as failure, and skipping the test is dependent on the implementation on the OGC side as the TEAM engine endpoint has no way to configure the test run. Until the workaround is modified, there's not much that can be modified on the validator side.

**Comment by iuriemaxim** [comment]
According to https://github.com/opengeospatial/ets-wfs20/issues/175 the problem was solved on 9 October (but not tested with the provided service), nor put into staging or production environment of the OGC CITE TEAM Engine.

@carlospzurita there is any way to find when this can be visible in the staging environment of the INSPIRE Validator and when will be visible in the production environment of the INSPIRE Validator?

**Comment by iuriemaxim** [comment]
Following the deployment of https://github.com/inspire-eu-validation/community/issues/314#issuecomment-720351719 in Beta TEAM Engine two days ago, the problem of ”SpatialJoin error if the WFS is serving only points and multipoints„, was solved on staging environment. Waiting for it in production too. Can be marked as solved-to be moved into production.
OGC should move this fix to the production environment of the TeamEngine in order to be seen in the production environment of the INSPIRE validator..

Service tested:
https://inspire-staging.meteoromania.ro/WIGOS/WFS?Service=WFS&version=2.0.0&request=GetCapabilities

Test result on staging:
http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/v2/TestRuns/EID230fca28-f816-4dc0-b478-d015630d0af5.html

![image](https://user-images.githubusercontent.com/20813598/98128818-0963f800-1ec1-11eb-8bab-6f45f8b5c25c.png)

Waiting it on production environment.
Test result on production:
https://inspire.ec.europa.eu/validator/v2/TestRuns/EID991b1c0e-9c1f-4840-8d88-794fa73ecca0.html

![image](https://user-images.githubusercontent.com/20813598/98128625-cace3d80-1ec0-11eb-995c-83419fccaabf.png)

**Comment by iuriemaxim** [comment]
@carlospzurita Even if it is marked as ”external dependency”, shouldnt this be marked as solved becuase was solved by OGC on their staging environment? Or it will be marked as solved when will be solved in the OGC production environment?

**Comment by fabiovinci** [comment]
Dear all,

since all the issues opened in the external repositories and linked to this issue are closed, we close also this one.
Please feel free to reopen the issue or to open a new one if the problem persists.
