### ISSUE TITLE
WFS test is baased on a remote test on CITE and does not work when Team Engine is down

### ISSUE THREAD

**Issue by iuriemaxim** [INSPIRE-MIF/helpdesk-validator#212]
We encountered this error today 12 February 2020, in the morning while testing a WFS Dowload Service

![image](https://user-images.githubusercontent.com/20813598/74312398-4fe55580-4d7a-11ea-8dc6-1ae3cced2908.png)

Such message error could be avoided if a copy of the OGC CITE Team Engine would be installed and kept up to date in the ETF INSPIRE Validator production environment .

**Comment by danielnavarrogeo** [comment]
Dear @iuriemaxim 

Thank you for your suggestions.

The INSPIRE Reference Validator is designed to be modular and to make use of OGC TEAM Engine so we do not reinvent the wheel. The issue should be solved in TEAM Engine.

You might be interesting in opening this issue in the corresponding OGC repository.

Regards
