### ISSUE TITLE
md sds 3.4: Spatial Data Service Category

### ISSUE THREAD

**Issue by alitka** [INSPIRE-MIF/helpdesk-validator#213]
Issue related to #84 and #181 

- [x] description of the steps to reproduce the issue
1. go to http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp and select "Conformance Class 4: INSPIRE Network Services metadata." (include the test suites "Conformance Class 3: INSPIRE Spatial Data Service baseline metadata." and "Common Requirements for ISO/TC 19139:2007 based INSPIRE metadata records."
2. start the test and upload an externale xml-file
3. the error message returned for the test "Conformance Class 3: INSPIRE Spatial Data Service baseline metadata. > Identification > md sds 3.4: Spatial Data Service Category": 
`The metadata record set has 1 record(s) with errors for this assertion. XML document 'service_DE_spatialDataServiceCategory.xml', record '3edc9361-4f03-46dc-af54-c6b773004a9f': At least one keyword shall be given withe a child Anchor that includes an xlink:href attribute with one of the language-natural keyword values as defined in "Classification of Spatial Data Services" Part D 4.`
- [x] used browser and version: `Firefox Browser 72.0.2 (64-bit)`
- [x] screenshot to illustrate the problem
![grafik](https://user-images.githubusercontent.com/29542183/74314869-88833000-4d76-11ea-9be0-87dc94b92cd6.png)
- [x] the Test Report (as an attachment to the issue)
[testReport_service_DE_spatialDataServiceCategory.zip](https://github.com/inspire-eu-validation/community/files/4190565/testReport_service_DE_spatialDataServiceCategory.zip)
- [x] the name of the Test that failed: md sds 3.4: Spatial Data Service Category
http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/v2/TestRuns/EIDc0233f6e-27c6-4729-b28b-d96fbc9c4f1b.html?lang=de#EID0a4bd7c2-cea5-40c3-a87f-9d076b416957
- [x] uploaded file: [service_DE_spatialDataServiceCategory.zip](https://github.com/inspire-eu-validation/community/files/4190529/service_DE_spatialDataServiceCategory.zip)

The test claims an error concerning the "type" (gmx:Anchor instead of CharacterString) of keyword entry: 
`<gmd:keyword>`
`   <gmx:Anchor xlink:href="http://inspire.ec.europa.eu/metadata-codelist/SpatialDataServiceCategory/infoMapAccessService">infoMapAccessService</gmx:Anchor>`
~~`<gco:CharacterString>infoMapAccessService</gco:CharacterString>`~~
`</gmd:keyword>`
`</gmd:MD_Keywords>`

Related to the TG Requirement 3.4: metadata/2.0/req/sds/sds-category, it is only a recommendation using a gmx_Anchor-element instead of a CharacterString-Element.

TG **Recommendation** 3.2: metadata/2.0/rec/sds/sds-category-cv
> To make the reference to the keywords values in [Regulation 1205/2008], Part D 4 clear, these keywords should be expressed as keywords from a controlled vocabulary and using gmx:Anchor elements with references to the Classification of spatial data services code list in the INSPIRE registry54. The gmd:thesaurusName element of the enclosing gmd:MD_Keywords element should be added and it should contain the citation to the [Regulation 1205/2008], Part D 4 and its publication date according to section 2.4.5.

**Comment by iuriemaxim** [comment]
In the metadata file provided the link to the thesaurus is missing.

Our metadata for the WMS is passing the test with infoMapAccessService Anchor, but it is including as well a link to the thesaurus as it is stipulated in the above recommendation 3.2 of the Metadata TG version 2.0:

”The gmd:thesaurusName element of the enclosing gmd:MD_Keywords element should be added and it should contain the citation to the [Regulation 1205/2008], Part D 4 and its publication date according to section 2.4.5”.

It should look like this:

```
<gmd:descriptiveKeywords>
	<gmd:MD_Keywords>
		<gmd:keyword>
			<gmx:Anchor xlink:href="http://inspire.ec.europa.eu/metadata-codelist/SpatialDataServiceCategory/infoMapAccessService">infoMapAccessService</gmx:Anchor>
		</gmd:keyword>
		<gmd:thesaurusName>
			<gmd:CI_Citation>
				<gmd:title>
					<gmx:Anchor xlink:href="http://data.europa.eu/eli/reg/2008/1205">Commission Regulation (EC) No 1205/2008 of 3 December 2008 implementing Directive 2007/2/EC of the European Parliament and of the Council as regards metadata</gmx:Anchor>
				</gmd:title>
				<gmd:date>
					<gmd:CI_Date>
						<gmd:date>
							<gco:Date>2008-12-03</gco:Date>
						</gmd:date>
						<gmd:dateType>
							<gmd:CI_DateTypeCode codeList="http://standards.iso.org/iso/19139/resources/gmxCodelists.xml#CI_DateTypeCode" codeListValue="publication">publication</gmd:CI_DateTypeCode>
						</gmd:dateType>
					</gmd:CI_Date>
				</gmd:date>
			</gmd:CI_Citation>
		</gmd:thesaurusName>
	</gmd:MD_Keywords>
</gmd:descriptiveKeywords>
```

Metadata file to test that is passing the validation is accessible at:
https://inspire.meteoromania.ro/WIGOS/MD-WMS

Test result on staging:
http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/v2/TestRuns/EID6a9ec39b-ba1b-4b06-ac23-38b84d0fcbe6.html

It is passing as well in the production environment:
http://inspire.ec.europa.eu/validator/v2/TestRuns/EIDea00d741-64d4-4957-b642-ee93237579f2.html

Note: The links to the validator's results are not  permanent and will not work after the restart of the validators.

**However I have a question in relation to this:
How should be referenced the part D4 of the [Regulation 1205/2008]?
We just referenced the Regulation itself, not its part D4.**

On the other hand the test seems not to verify the content for the thesaurus to be be provided for the infoMapAccessService keyword.

Test will pass even if the thesaurus will be provided as 

`<gmx:Anchor xlink:href="http://data.europa.eu/zzzzzzzzzzzzzz">zzzzzzzzzzzzzzzzzzz</gmx:Anchor>`

Hope it helps

**Comment by danielnavarrogeo** [comment]
Dear @alitka 

We agree that the use of an Anchor element for providing the Spatial Data Service category is a recommendation and a CharacterString shall be allowed also.

We will fix it and let you know when it is ready for testing.

Regards

**Comment by danielnavarrogeo** [comment]
Dear @alitka 

The issue has been addressed and deployed in [staging environment](http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/).

Could you please check it and confirm that the issue has been fixed?

Regards

**Comment by alitka** [comment]
Dear @danielnavarrogeo,
I have tested the xml-files again, addional another xml-file also and everything is working properly.
Thanks and best regards!

**Comment by alitka** [comment]
Dear @iuriemaxim,
to your first comment
> However I have a question in relation to this:
> How should be referenced the part D4 of the [Regulation 1205/2008]?
> We just referenced the Regulation itself, not its part D4.

Related to the TG Example 4.2: Declaring Spatial Data Service category or subcategory as a keyword (p. 63) and the provided example under community/examples > NetworkService_WMS_metadata_2.0_example, the recommended expression for the thesaurus citation is:

`<gmd:thesaurusName>`
`	<gmd:CI_Citation>`
		`<gmd:title>`
			`<gmx:Anchor xlink:href="http://data.europa.eu/eli/reg/2008/1205">`
**`COMMISSION REGULATION (EC) No 1205/2008 of 3 December 2008 implementing Directive 2007/2/EC of the European Parliament and of the Council as regards metadata`**
`</gmx:Anchor>`
		`</gmd:title>`
		...
	`</gmd:CI_Citation>`
`</gmd:thesaurusName>`

To your second comment
> On the other hand the test seems not to verify the content for the thesaurus to be be provided for the infoMapAccessService keyword.
> Test will pass even if the thesaurus will be provided as

Related to the TG Requirement 3.4: metadata/2.0/req/sds/sds-category, it is also only a recommendation adding the gmd:thesaurusName element to this keyword:

TG **Recommendation** 3.2: metadata/2.0/rec/sds/sds-category-cv
> [...] The gmd:thesaurusName element of the enclosing gmd:MD_Keywords element should be added and it should contain the citation to the [Regulation 1205/2008], Part D 4 and its publication date according to section 2.4.5.

Best regards.

**Comment by danielnavarrogeo** [comment]
Thank you @alitka for your feedback.

Regards

**Comment by iuriemaxim** [comment]
By addressing this issue, more damage was done. See https://github.com/inspire-eu-validation/community/issues/319
