### ISSUE TITLE
Question in relation to closed issues #208 #209 #210

### ISSUE THREAD

**Issue by iuriemaxim** [INSPIRE-MIF/helpdesk-validator#215]
I think that is not a good idea just to close issues that are useful for other Data Providers. As these issues are visible in the INSPIRE Official validator and others will have the same problems, it is not fair to simply close them because they are due to a third party component.

I agree that the wheel should not be reinvented, but neither it is correct to simply close issues that exist in the ETF validator. In this context I am asking to re-open them and to treat them correctly and fair because they have implications in the evaluation of the Member States based on Reporting obligations according to existing INSPIRE IRs.

Having in mind the explanations provided within the issues #208, #209, #210 that are actually issues of the OCG CITE TeamEngine and taking into consideration that the ETF validator is the only official INSPIRE validating instrument, how will EC interpret in the official country reports that a WFS service is not passing the "WFS 2.0 (OGC 09-025r2/ISO 19142) Conformance Test Suite" that is a prerequisite for  the "Conformance Class: Download Service - Direct WFS"?

It would be possible that EC will interpret that the WFS service is not conform and the Member States will need to provide explanations that there are issues in OGC CITE Team Engine tests?

Wouldn't be easier and more appropriate to remove from the ETF validator exactly these tests that have issues in the OGC CITE Team Engine until they will be fixed by OGC?

Should EC/JRC discuss with OGC in order to solve those issues that impacts the Official INSPIRE ETF validator?

**Comment by danielnavarrogeo** [comment]
Dear @iuriemaxim 

We agree with you that we can reopen these issues to help other member states in the identification of this issue.

Regards

**Comment by iuriemaxim** [comment]
Thank you @danielnavarrogeo 

It can be noticed that there is pull request in CITE from 30 April 2019 that will solve at least one of the three issues that where identified in the OGC CITE Team Engine tests for WFS 2.0 (https://github.com/opengeospatial/ets-wfs20/pull/154), but even after 9 months this was not committed in production. So the things are moving very slow with CITE even when the code already exist to fix the issue.

Due to this fact and because the ETF is the official INSPIRE validator, please change the code of the ETF in order not to trigger these pseudo-errors within the ETF.

In the first stage please change in the ETF the texts that describes the errors in order to indicate these known issues in the OGC CITE tests for WFS 2.0. This should be something very easy to be implemented.

Changes should be done to these texts in order to indicate the known issues in the OGC CITE TeamEngine:
![image](https://user-images.githubusercontent.com/20813598/74424046-edfc1d00-4e59-11ea-8728-5ef70f45b4df.png)

![image](https://user-images.githubusercontent.com/20813598/74423928-c016d880-4e59-11ea-80dd-137d7f5e5537.png)



In this way the users of the ETF validator will be aware that the error is not in their service, but there are some issues with a third party validator that is used by ETF.

In a second stage, till the next evaluation of the Member States, it should be verified if the geometry is point and if so no to trigger anymore these issues in the ETF validator until the OGC CITE Team Engine tests will be fixed.

Probably OGC will not fix them till the next Member States evaluation that is held based on Monitoring and Reporting legislation (https://inspire.ec.europa.eu/Legislation/Monitoring-and-Reporting/69) and therefore it is important to implement some measures in the INSPIRE official ETF Validator till then.

**Comment by MarcoMinghini** [comment]
Dear @iuriemaxim, 
I have seen some activity on the OGC issue tracker over the last days so I am confident that they are addressing the problem. Please rest assured that we are closely monitoring the situation and we are also in contact with the OGC in order to receive their direct feedback about this.

**Comment by MarcoMinghini** [comment]
Dear @iuriemaxim, all,
we are in close contact with the OGC Team responsible for the TEAM Engine. As I commented in each separate issue affected by the TEAM Engine issues, the OGC Team has already addressed and solved the following issues, which will become effective from the next version planned for the end of April:
* https://github.com/opengeospatial/ets-wfs20/issues/163
* https://github.com/opengeospatial/ets-gml32/issues/46
* https://github.com/opengeospatial/ets-wfs20/issues/157

Instead, the solution of the following issue is a bit more complex and will take some more time:
* https://github.com/opengeospatial/ets-wfs20/issues/164

I would propose to close this issue and continue our discussion on each separate INSPIRE issue.

**Comment by iuriemaxim** [comment]
It is ok to close this one.

However would be more appropriate not to use ”discussion” tag for the referenced issues. They could be marked for example ”under development” even if they are under development by a third party, or to have a tag ”under development by OGC (CITE)”.
