### ISSUE TITLE
INSPIRE Annex III

### ISSUE THREAD

**Issue by DLList** [INSPIRE-MIF/helpdesk-validator#222]
Hello,

I have a question regarding the INSPIRE Annex III Specifications. Do corresponding test-suites for this specifications exist or are they still in the implementation phase for the first time?

Thanks for answer in advance and best regards,
Dawid

**Comment by fabiovin** [comment]
Dear @DLList,
the ATSs/ETSs for the Annex II & III data themes are under development.

In the meanwhile, you can use the 4 generic conformance classes available under the group "Interoperable data sets in GML (Guidelines for the Encoding of Spatial Data version 3.3)", to validate the common requirements and then you can check the theme-specific ones by hand.
For many Annex II&III data themes the theme-specific requirements are very few and in many cases cannot be verified automatically.

Please remember to add the following pair of values "http://www.opengis.net/gml/3.2 http://schemas.opengis.net/gml/3.2.1/gml.xsd" in the `xsi:schemaLocation` attribute, in addition to the pair of values related to the INSPIRE application schema.

Fabio

**Comment by DLList** [comment]
Dear @fabiovin,

thank you for the help. I will do as it is described.

Regards
Dawid

**Comment by dperezBM** [comment]
Dear @DLList 
As @fabiovin mentioned, Annex II and Annex III are currently under development, but we are updating [issue 336](https://github.com/INSPIRE-MIF/helpdesk-validator/issues/336) as we deploy new themes. 

We are closing this issue, but please feel free to open another one in case you need it.

Best regards.
