### ISSUE TITLE
INSPIRE Validator error: Cannot find the declaration of element 'gml:FeatureCollection'

### ISSUE THREAD

**Issue by LeonorQueiroz** [INSPIRE-MIF/helpdesk-validator#223]
Hello,
I'm harmonizing the EF Bathing Waters and appears the error below:

Conformance class: INSPIRE GML application schemas, General requir Conformance class: INSPIRE GML application schemas, General requir… Failed: 1 / 6 Failed: 1 / 6
Schema validation 
gmlas.b.2: validate XML documents
Messages “The dataset has 1 file(s) with errors for this assertion. The dataset has 1 file(s) with errors for this assertion. XML document 'teste10_18022020.gml': The file has 1 schema validation XML document 'teste10_18022020.gml': The file has 1 schema validation error(s). error(s). XML document 'teste10_18022020.gml': 1:1254: cvc-elt.1.a: Cannot find the XML document 'teste10_18022020.gml': 1:1254: cvc-elt.1.a: Cannot find the declaration of element 'gml:FeatureCollection'.”

It appears that the INSPIRE Directive application schema doesn't have/ doesn't find the Feature Collection or
the INSPIRE Directive application schema doesn’t correspond with INSPIRE Validator schema,
is this possible, what is the problem? Can you help me please?

Best regards,
Leonor Queiroz.

**Comment by fabiovin** [comment]
Hi @LeonorQueiroz,
the validator is not able to retrieve the declaration of element 'gml:FeatureCollection' from the INSPIRE application schemas, even though these last ones import the 'gml.xsd'.

So, you need to add the following pair of values "http://www.opengis.net/gml/3.2 http://schemas.opengis.net/gml/3.2.1/gml.xsd" in the xsi:schemaLocation attribute, in addition to the pair of values related to the INSPIRE application schema.

Fabio

**Comment by LeonorQueiroz** [comment]
Hello @fabiovin ,

Thank you for your answer.
Do you know here should I write the following pair of values "http://www.opengis.net/gml/3.2 http://schemas.opengis.net/gml/3.2.1/gml.xsd" that you recomended, because when i put them on the  xsi:schemaLocation it doesn't work with FME.
I've tried in diferente ways, but i steel have the same schema error.

Best regards,
Leonor Queiroz.

**Comment by LeonorQueiroz** [comment]
Hello @fabiovin,

I find out where i should put the pair.
We write inside the writer FME, the GML passes in INSPIRE Validator, but doesn't write/generates the points of the geometry.

What do you recommend?

Best regards,
Leonor Queiroz.

**Comment by LeonorQueiroz** [comment]
Hello @fabiovin,

Do you know here should I write the following pair of values "http://www.opengis.net/gml/3.2 http://schemas.opengis.net/gml/3.2.1/gml.xsd" on HALE?

Best regards,
Leonor Queiroz.

**Comment by fabiovin** [comment]
Hi @LeonorQueiroz,
I don't have experience with FME, so, unfortunately, I cannot help you.
In HALE there is no way to provide the values in advance during the alignment process, so I usually add it manually in the exported gml file.

**Comment by LeonorQueiroz** [comment]
Hi @fabiovin 
No problem, thank you very much.
I tried add it manually in the exported gml file, but in this way the INSPIRE Validator dont aceptetd. 
I think that i find out that the way to provide the values in advance during the alignment process on HALE. In the options: "Edit" and "Edit mapping relevant target types" for ativate the schemas that you need; and "File" and "Reload and update schemas". 
In FME is the option to edit the Target, "Advanced" and "Target xsi:schemaLocation URL:" and write all the shemas that you need.

Best regards,
Leonor Queiroz.

**Comment by apfelnymous** [comment]
@fabiovin Hi, Ive got a similiar problem with the attached file, the validator would say:

```
The dataset has 1 file(s) with errors for this assertion.
XML document 'Soil_ALKIS_test2.gml': The file has 500 schema validation error(s).
XML document 'Soil_ALKIS_test2.gml': 3:67: cvc-complex-type.2.4.a: Invalid content was found starting with element '{"http://www.opengis.net/om/2.0":OM_Observation}'. One of '{"http://www.opengis.net/gml/3.2":AbstractFeature}' is expected.
XML document 'Soil_ALKIS_test2.gml': 20:68: cvc-complex-type.2.4.a: Invalid content was found starting with element '{"http://www.opengis.net/om/2.0":OM_Observation}'. One of '{"http://www.opengis.net/gml/3.2":AbstractFeature}' is expected.
...
```

I tried to include serveral things in the schema location, but cant figure out whats missing, any clue ?
[Soil_ALKIS_test2.zip](https://github.com/inspire-eu-validation/community/files/5276489/Soil_ALKIS_test2.zip)

Kind regards
János

**Comment by LeonorQueiroz** [comment]
Hi @apfelnymous,

I believe that you need to add at least the following pair of values:
https://inspire.ec.europa.eu/schemas/so/4.0/ https://inspire.ec.europa.eu/schemas/so/4.0/Soil.xsd
http://www.opengis.net/om/2.0 http://schemas.opengis.net/om/2.0/observation.xsd
http://www.opengis.net/gml/3.2 http://schemas.opengis.net/gml/3.2.1/gml.xsd

if you are working with FME, go to Writer options and add the pair of values to Target xsi:schemaLocation URL.
if you are working with HALE, go Edit options and activate the schemas on ‘Edit mapping relevant target types’.

Hope this helps.

Best regards,
Leonor Queiroz.

**Comment by apfelnymous** [comment]
Hi @LeonorQueiroz,

thank you alot, while messing around with the schema locations I didnt see I always need to set it in even couples. Adding both http://www.opengis.net/om/2.0, http://schemas.opengis.net/om/2.0/observation.xsd and removing http://schemas.opengis.net/gml/3.2.1/gml.xsd did it.

I use hale, om_observation was already choosen as an target type as I use it in the alignment.
I dont see how to make it adding the right couple that way. I think they are working on it. 
https://github.com/halestudio/hale/issues/856

Kind regards
János

**Comment by LeonorQueiroz** [comment]
You're welcome!

In HALE you don't add the schemas pairs. You ativate, in the HALE options: "Edit" and "Edit mapping relevant target types" the schemas that you need; and "File" and "Reload and update schemas".
You need all the involved schemas, not only of the Soil schema.
I believe that working with Soil, its necessary too ativate the Base Type schema (because of Identifier class and others), OM_Observation schema, Geology schema (because Soil use some of the code lists), and Coverages (Base) and Observations schemas from Base Models.

Best regards,
Leonor Queiroz.

**Comment by dperezBM** [comment]
Dear all,

Since this issue had no interaction time ago, we decided to close it. Please feel free to open a new one if needed.

Thank you and best regards.
