### ISSUE TITLE
Null Pointer exceptions for WMTS

### ISSUE THREAD

**Issue by HolgerFritze** [INSPIRE-MIF/helpdesk-validator#225]
Hi all,

While performing the test **Conformance Class: View Service - WMTS** on [inspire.ec.europa.eu/validator/](inspire.ec.europa.eu/validator/) I get many NullPointerExceptions. 

It seems like the Validator “get’s stuck” before actually starting the test.

![Validator_null_pointer](https://user-images.githubusercontent.com/4929867/75021349-89ae0e80-5494-11ea-8508-a774e5576f0c.PNG)

The service I tested is [https://tiles.arcgis.com/tiles/yxqWib8HJGkXh9Vt/arcgis/rest/services/aireal/MapServer/WMTS/1.0.0/WMTSCapabilities.xml](https://tiles.arcgis.com/tiles/yxqWib8HJGkXh9Vt/arcgis/rest/services/aireal/MapServer/WMTS/1.0.0/WMTSCapabilities.xml). I'm aware this is not inspire compliant service, but it shows the same results as an internal service we are interested in.

Report: http://inspire.ec.europa.eu/validator/v2/TestRuns/EIDb5812ef8-cf03-4449-b33c-02c330d22a99.html

Do you have any idea why the valdiators doesn't recognize the Capabilities? 

Best 
Holger

**Comment by danielnavarrogeo** [comment]
Dear @HolgerFritze 

The issue is related to the way the tiles are requested using the TileMatrix defined in the capabilities document.

We are developing a solution and we will let you know when it is ready for testing.

Regards

**Comment by danielnavarrogeo** [comment]
Dear @HolgerFritze 

A solution has been implemented in [staging](http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/).

Could you please check and provide us feedback?

Remind that you shall provide the endpoint to the GetCapabilities request using http, not https. In your case:

http://tiles.arcgis.com/tiles/yxqWib8HJGkXh9Vt/arcgis/rest/services/aireal/MapServer/WMTS?service=WMTS&request=GetCapabilities

Regards

**Comment by danielnavarrogeo** [comment]
Dear @HolgerFritze 

Could you please check the fix in [staging instance](http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/) and provide us feedback?

Regards

**Comment by HolgerFritze** [comment]
Dear @danielnavarrogeo,
thanks a lot for taking care of this issue. I have tested the implementation in the staging system and can confirm the validatation proceeds beyond this NullPointeException issue.

However, I have two remarks:
* using the HTTP endpoint instead of HTTPS works, but in the capabilities document all links are https. Is the usage of htp over https a particularity of the staging system?
* the validation uses KVP, although a restful endpoint is provided. 

Not sure, whether this relates to this issue or another existing ones.

regards
Holger

**Comment by danielnavarrogeo** [comment]
Dear @HolgerFritze 

Thank you very much for testing and provide us feedback. We can then label this issue as solved.

Regarding your two remarks, the validator currently only support HTTP endpoints and KVP.

Regards
