### ISSUE TITLE
WMS View Service Issue while testing AC-MF layer names

### ISSUE THREAD

**Issue by danieluct** [INSPIRE-MIF/helpdesk-validator#227]
According to the Portrayal section of the [INSPIRE Data Specification on Atmospheric Conditions and Meteorological Geographical Features – Technical Guidelines](https://inspire.ec.europa.eu/id/document/tg/ac) at page 62: 
![image](https://user-images.githubusercontent.com/6768817/75054191-4aef7700-54db-11ea-85b1-fb5be841f48b.png)

So data providers can use any layer name for layers under the AC-MF data theme. Names such as ACMF.GRIB0-1-11 or ACMF.SnowDepth should be allowed. However, the validator triggers an error because these names are not found in its internal dictionary as can be seen in https://github.com/inspire-eu-validation/ets-repository/blob/cf007c52279f874324e9e554ab19b19651cd8112/service/vs-wms-soapui-project.xml#L929. The validator should accept not only the dictionary values, but also any string beginning with 'ACMF.'

**Comment by danielnavarrogeo** [comment]
Dear @danieluct 

Thank you for opening this issue. We agree that those layer names should be allowed for the case of Atmospheric Conditions and Meteorological Geographical Features.

We will add this option and let you know when it will be ready for testing.

Regards

**Comment by fabiovin** [comment]
Dear all,
the related Implementing rule ([COMMISSION REGULATION (EU) No 1253/2013](https://inspire.ec.europa.eu/documents/commission-regulation-eu-no-12532013-21-october-2013-amending-regulation-eu-no-10892010)) does not specify any layer for this data theme.
So, the validator should not check the layer name for this data theme.
Any value should be allowed.

**Comment by danielnavarrogeo** [comment]
Dear @danieluct 

The issue has been addressed and it is ready for testing in [staging](http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/).

Could you please check it and provide us feedback?

Regards

**Comment by iuriemaxim** [comment]
Dear @danielnavarrogeo 

Thank you for solving the issue. It was fixed for ACMF.

Links tested:
https://inspire.meteoromania.ro/WIGOS/WMS?service=WMS&request=GetCapabilities
https://inspire-staging.meteoromania.ro/WIGOS/WMS?service=WMS&request=GetCapabilities

It was implemented only for ACMF, or it was implemented also for other data themes that allow any layer names to be used ?

Regards,
Iurie

**Comment by danielnavarrogeo** [comment]
Dear @iuriemaxim 

Thank you for your feedback. It was fixed only for ACMF.

Regards
