### ISSUE TITLE
Dataset metadata with Finnish conformity title won't validate

### ISSUE THREAD

**Issue by kkoistinen** [INSPIRE-MIF/helpdesk-validator#228]
I'm trying to validate the attached file against INSPIRE metadata TG2.0 dataset metadata rules. I copied the conformity title from https://github.com/inspire-eu-validation/ets-repository/blob/424ec70639a0c8d58f5a5dfa49e212dcfb721fde/schemas/common/1.0/enums/enum_fin.xsd but it still fails the validation. When I change title to english version it succesfully validates. 
[fi_metadata_example.zip](https://github.com/inspire-eu-validation/community/files/4249827/fi_metadata_example.zip)

Is this a validator bug?

Best regards,
Kai Koistinen
NLS Finland

**Comment by danielnavarrogeo** [comment]
Dear @kkoistinen 

Thank you for reporting this issue. This is indeed a bug in the validator. 

We will fix it and ask you to test it when it will be ready.

Regards

**Comment by danielnavarrogeo** [comment]
Dear @kkoistinen 

The issue has been addressed and deployed in [staging](http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp).

Could you please check it and give feedback about the implemented fix?

Regards

**Comment by kkoistinen** [comment]
Thanks, I tested it and it works fine now!

I would find it useful to have these valid conformity title strings collected to some single webpage. Maybe INSPIRE Registry would be the right place for maintaining these?

**Comment by danielnavarrogeo** [comment]
Thank you @kkoistinen for your feedback.

We will leave the issue open until is deployed in production with the next release.

The valid titles of the Commission Regulation (EU) No 1089/2010 can be found for every EU official language in the site https://op.europa.eu/en/publication-detail/-/publication/6c9b0d4b-831f-47fe-b551-ac13604d9797/language-fi and in the following one http://inspire.ec.europa.eu/schemas/common/1.0/enums/

Regards
