### ISSUE TITLE
MD common req C.5:  Language Code and MD datasets-and_series 1.6:Resource Language

### ISSUE THREAD

**Issue by idevisser** [INSPIRE-MIF/helpdesk-validator#239]
TG Requirement C.5: metadata/2.0/req/common/metadata-language-code
The language of the provided metadata content shall be given. It shall be encoded using gmd:MD_Metadata/gmd:language/gmd:LanguageCode element pointing to one of the three-letter language codes of the ISO 639-2/B code list19;

test failed;
expected behavior to accept also the HTTPS version https://www.loc.gov/standards/iso639-2/

tested in staging environment;
http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/v2/TestRuns/EID838ceb8e-e878-4533-9b77-fef13e7f1329.html

test xml;
[TEST_EU_Metadata_Dataset_2019.zip](https://github.com/inspire-eu-validation/community/files/4287449/TEST_EU_Metadata_Dataset_2019.zip)

**Comment by iuriemaxim** [comment]
Hi,

Language codeList should start with http:// and not with https://

<gmd:LanguageCode codeList="**http**://www.loc.gov/standards/iso639-2/" codeListValue="dut">Dutch</gmd:LanguageCode>

I do not think that the validator should allow both versions:
codeList="[http://www.loc.gov/standards/iso639-2/](http://www.loc.gov/standards/iso639-2/)" 
codeList="[https://www.loc.gov/standards/iso639-2/](https://www.loc.gov/standards/iso639-2/)" 

taking into consideration the Metadata TG version 2.0:

![image](https://user-images.githubusercontent.com/20813598/75898072-3ea3dc00-5e42-11ea-9c7f-d55ad019eefc.png)

But indeed the ISO639-2 can be accessed also securely.

Hope it helps,
Iurie

**Comment by idevisser** [comment]
Hi,
It is true that only the location of the unsecured url is included in the footnote, but I expect the validator to handle this more flexibly, because many organizations proceed to create and use only secured urls, 
That is the reason i was asking  to accept also the secured ones.

**Comment by fabiovin** [comment]
Also in my opinion the test should be relaxed in order to accept also the https url.

**Comment by danielnavarrogeo** [comment]
Dear @idevisser 

We will update the test in order to accept https url and let you know when it is ready.

Regards

**Comment by danielnavarrogeo** [comment]
Dear @idevisser 

The test now accepts https urls in the CodeList for requirements C.5 and 1.6.

Could you please check it in [staging instance](http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/) and provide us feedback?

Regards

**Comment by idevisser** [comment]
Dear @danielnavarrogeo 

thanx, it works like expected

best regards Ine

**Comment by danielnavarrogeo** [comment]
Dear @idevisser 

Thank you very much for your feedback.

We will keep the issue open to tracking it properly.

Regards
