### ISSUE TITLE
SOS authentification issues

### ISSUE THREAD

**Issue by danielnavarrogeo** [INSPIRE-MIF/helpdesk-validator#244]
After working on issue #81, we have realized the same issue occurs for other services that require authentification.

We are developing a solution for it that it will be available for testing soon.

Regards

**Comment by danielnavarrogeo** [comment]
A solution has been developed for this issue and it is available for testing in [staging](http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/).

Regards

**Comment by MarcoMinghini** [comment]
Since the solution to this issue is the very same solution already implemented and approved for WMS in #81, we also mark this issue as _solved_.
