### ISSUE TITLE
As ISO changed the location of ISO_19139 schemas (ITTF), many XSD schemas that are needed for INSPIRE implementation can't be used anymore

### ISSUE THREAD

**Issue by iuriemaxim** [INSPIRE-MIF/helpdesk-validator#246]
This is not a bug of the validator itself, but it has a major impact on the INSPIRE Infrastructure. Most probably the validator still works because these schemas are cached in the validator.

But metadata files are not anymore valid in any XML validator, including Notepad++.

Some of important schemas used in INSPIRE are not available anymore at https://standards.iso.org/ittf/PubliclyAvailableStandards/ISO_19139_Schemas/.

Some examples include GMD, GMX, APISO:

https://standards.iso.org/ittf/PubliclyAvailableStandards/ISO_19139_Schemas/gmd/gmd.xsd
https://standards.iso.org/ittf/PubliclyAvailableStandards/ISO_19139_Schemas/gmd/gmx.xsd
https://standards.iso.org/ittf/PubliclyAvailableStandards/ISO_19139_Schemas/gmd/metadataApplication.xsd
http://schemas.opengis.net/csw/2.0.2/profiles/apiso/1.0.0/apiso.xsd (as it is loading also http://standards.iso.org/ittf/PubliclyAvailableStandards/ISO_19139_Schemas/gmd/gmd.xsd and http://standards.iso.org/ittf/PubliclyAvailableStandards/ISO_19139_Schemas/gmx/gmx.xsd)

![image](https://user-images.githubusercontent.com/20813598/76100732-d84fc280-5fd5-11ea-9085-5e4269861cae.png)

Is there any other location for APISO schema that does not include schemas from http://standards.iso.org/ittf/PubliclyAvailableStandards/ISO_19139_Schemas/ ?

**Comment by iuriemaxim** [comment]
Error that appears now due to the fact that ISO removed the schema from their site:

![image](https://user-images.githubusercontent.com/20813598/76194385-b715ee80-61ee-11ea-81ba-8bf43d418cd8.png)

It would not be enough to cache the schemas, they will need also to be modified to change the links that are not anymore valid (at least for APISO).

It would be quite strange to use 
http://inspire.meteoromania,ro/csw/2.0.2/profiles/apiso/1.0.0/apiso.xsd
instead of 
http://schemas.opengis.net/csw/2.0.2/profiles/apiso/1.0.0/apiso.xsd

Also:

![image](https://user-images.githubusercontent.com/20813598/76195524-28ef3780-61f1-11ea-91bd-0c6650a9e6bd.png)

I am not a legal expert and don't know how to cope with it.

Probably solution is to use http://schemas.opengis.net/iso/19139/20070417/....

**Comment by danielnavarrogeo** [comment]
Dear @iuriemaxim 

Thank you for raising this issue. We are analyzing the best approach to manage this.

Regards

**Comment by iuriemaxim** [comment]
@danielnavarrogeo 

Metadata files (version 2.0) will pass the ETF validator and XML files will be also validated against an XML validator if all ISO links will be changed and if the header would be changed into:

<gmd:MD_Metadata xmlns:gmd="http://www.isotc211.org/2005/gmd" xmlns:gco="http://www.isotc211.org/2005/gco" xmlns:gmx="http://www.isotc211.org/2005/gmx" xmlns:srv="http://www.isotc211.org/2005/srv" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:gml="http://www.opengis.net/gml/3.2" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:xs="http://www.w3.org/2001/XMLSchema" xsi:schemaLocation="http://www.isotc211.org/2005/gmd http://schemas.opengis.net/iso/19139/20070417/gmd/gmd.xsd http://www.isotc211.org/2005/gmx http://schemas.opengis.net/iso/19139/20070417/gmx/gmx.xsd http://www.isotc211.org/2005/srv http://schemas.opengis.net/iso/19139/20070417/srv/1.0/srv.xsd http://www.isotc211.org/2005/gco http://schemas.opengis.net/iso/19139/20070417/gco/gco.xsd">

Validator is not looking at the links.
For example if:
<gmd:CI_DateTypeCode codeList="http://schemas.opengis.net/iso/19139/20070417/resources/codelist/gmxCodelists.xml#CI_DateTypeCode" codeListValue="publication">publication</gmd:CI_DateTypeCode>

would be

<gmd:CI_DateTypeCode codeList="https://standards.iso.org/ittf/PubliclyAvailableStandards/ISO_19139_Schemas/resources/codelist/gmxCodelists.xml#CI_DateTypeCode" codeListValue="publication">publication</gmd:CI_DateTypeCode>

then the validator will not trigger an error even if the link does not exist anymore.

It will pass even if it will look like this:

<gmd:CI_DateTypeCode codeList="https://zzz" codeListValue="publication">publication</gmd:CI_DateTypeCode>

APISO schema however cant be used anymore.

Metadata files made according to TG version 1.3 will not pass the validator.

**Comment by iuriemaxim** [comment]
This issue can be closed if necessary, if the issue https://github.com/inspire-eu-validation/community/issues/245 will remain to be fixed.

**Comment by sMorrone** [comment]
@danielnavarrogeo 
you correctly say that the APISO schema can't be used anymore.
Since the examples in the TG v2.0 are both referring to this schema (and therefore not validating against any XML editor validation) I suggest they are changed in order to provide a correct example.

It is an important aspect to deal with also regarding the ETF validation.
My personal view is that it would be quite odd that the ETF validates successfully an XML file that is not validating in any other  XML editor... 
What do you think?

**Comment by iuriemaxim** [comment]
Hi Stefania,

I said that APISO schema cant be used anymore, not Daniel. I agree that an invalid XML file (even if it is invalid due to ISO changing the location of some schema) should not be valid.

I also think that the validator should provide an error message if content similar to the one below would be found:

<gmd:CI_DateTypeCode codeList="https://zzz" codeListValue="publication">publication</gmd:CI_DateTypeCode>

Indeed is not a simple simple implementation as the data providers are now able to cache schemas. I raised this issue here https://github.com/inspire-eu-validation/community/issues/191

Also as I see, I can declare my own APISO schema, even if it is not reachable by internet http://inspire.meteoromania.ro/csw/2.0.2/profiles/apiso/1.0.0/apiso.xsd
and the XML file will pass the ETF validator, while the XML file vil be valid (locally)

Personally I would not allow data providers to use cached schemas that are not reachable by Internet, as it was allowed while addressing the issue https://github.com/inspire-eu-validation/community/issues/191. Probably this issue will be reconsidered.

Iurie

**Comment by danielnavarrogeo** [comment]
Dear @sMorrone and @iuriemaxim 

There could be a metadata file that does not validate using other software but it does with the INSPIRE Validator. This is due to, from the INSPIRE perspective, the metadata 2.0 shall be valid against at least one of a set of fixed schemas. You can see them in ATS (https://github.com/inspire-eu-validation/metadata/blob/2.0/common/xml-schema.md) which are defined in the TG.

Therefore, the user could use any schema in the schemaLocation, cached or not, but it shall be valid against at least one of the mentioned schemas in the ATS. It is worth mentioning that schemaLocation is not mandatory to be provided and some data providers, in fact, do not provide it.

Regarding ISO schemas that have been moved. We are looking for the best approach to solve this.

Finally, regarding the codeList checks, it was decided to not check them in 2017.4 meeting 2019-07-17 (https://github.com/inspire-eu-validation/community/issues/69#issuecomment-512823945).

Regards

**Comment by ronaldtse** [comment]
I write as a member of the ISO/TC 211 community. In https://github.com/ISO-TC211/schemas/issues/24#issuecomment-598168786 it was mentioned that the OpenGIS repository is now used, but thought nonetheless this could be useful.

The 19139 schemas (previously located at https://standards.iso.org/ittf/PubliclyAvailableStandards/ISO_19139_Schemas/) are now available at https://schemas.isotc211.org/19139/-/  , and will be maintained here.

e.g. https://schemas.isotc211.org/19139/-/gmd/1.0/gmd.xsd

You can use the schema browser at https://schemas.isotc211.org/schemas/19139/ to find the actual paths of schema files.

**Comment by iuriemaxim** [comment]
@ronaldtse thank you for the valuable information. 

However we still have a problem as the APISO schema http://schemas.opengis.net/csw/2.0.2/profiles/apiso/1.0.0/apiso.xsd 
is pointing to old location of the gmd and gmx schema.

@MarcoMinghini There is any solution for APISO schema as well? Can it be changed by opengis.net? Or there is an APISO schema that works now?

**Comment by danielnavarrogeo** [comment]
Dear all,

First, thank you to all the participants for all the comments pointing to this issue.

We have created "our" modified version to overcome the redirection problem and to solve also the problem related to the unavailability of the imported schemas. Please note that we consider http://inspire.ec.europa.eu/draft-schemas/inspire-md-schemas-temp/apiso-inspire/apiso-inspire.xsd and http://schemas.opengis.net/csw/2.0.2/profiles/apiso/1.0.0/apiso.xsd equivalent schemas.

Given that schema validation in MD TG 2.0 is performed against a set of predefined schemas (see https://github.com/inspire-eu-validation/metadata/blob/2.0/common/xml-schema.md), the schema declared in the schemaLocation attribute has no influence at all.

Considering also that the codelists are not checked, as mention in previous comment https://github.com/inspire-eu-validation/community/issues/246#issuecomment-597584884, MD TG 2.0 works correctly now.

Please do not hesitate about opening a new issue if you find one.

Regards

**Comment by ghost** [comment]
Hi @ronaldtse  @iuriemaxim @MarcoMinghini   ,

it seems that ogc-apiso schema could be updated. Discussion can be followed here:
https://github.com/opengeospatial/ets-19139/issues/20

**Comment by fabiovin** [comment]
Dear @DeordD,
thank you for the information. 

The apiso.xsd (http://schemas.opengis.net/csw/2.0.2/profiles/apiso/1.0.0/apiso.xsd) has been updated, so it can be now used for validating INSPIRE metadata.
