### ISSUE TITLE
Failed validation if the SpatialDataServiceCategory is provided with https:// on staging

### ISSUE THREAD

**Issue by iuriemaxim** [INSPIRE-MIF/helpdesk-validator#249]
When testing a metadata file of a service against conformance class 3, the test will fail on the staging environment but will pass on the production environment if the SpatialDataServiceCategory link is provided securely.

**These will pass only in production, but will fail on staging:**

<gmx:Anchor xlink:href="https://inspire.ec.europa.eu/metadata-codelist/SpatialDataServiceCategory/infoFeatureAccessService">infoFeatureAccessService</gmx:Anchor>

<gmx:Anchor xlink:href="https://inspire.ec.europa.eu/metadata-codelist/SpatialDataServiceCategory/infoMapAccessService">infoMapAccessService</gmx:Anchor>

If the link is provided with http:// will pass both on staging and in production.

![image](https://user-images.githubusercontent.com/20813598/76233588-1c8acf00-6231-11ea-99de-9185a3ca5f5b.png)

Regards,

**Comment by danielnavarrogeo** [comment]
Dear @iuriemaxim 

We are analyzing this issue and come back to you with our findings.

Regards

**Comment by danielnavarrogeo** [comment]
Dear @iuriemaxim 

A new version of the Validator has been released recently.

Could you please check if the issue remains in production and/or staging?

Regards

**Comment by alitka** [comment]
Dear @danielnavarrogeo,
Please see issue #319 - the issue is still in the staging AND production-instance.
Regards.

**Comment by iuriemaxim** [comment]
@danielnavarrogeo This issue can be closed as it was covered by https://github.com/inspire-eu-validation/community/issues/319

**Comment by MarcoMinghini** [comment]
Thanks for the comment, we assume the issue was solved together with #319.
