### ISSUE TITLE
INSPIRE Validator is down

### ISSUE THREAD

**Issue by JohannaOtt** [INSPIRE-MIF/helpdesk-validator#25]
I tried to use the INSPIRE Sandbox Validator (using http://inspire-sandbox.jrc.ec.europa.eu/etf-webapp/) yesterday and today but it seems to be down. I never saw that happen for more than a few hours so far. Has it been moved to a different URL or is there maintenance work going on these days?

All the best

Johanna

**Comment by inakidiazdecerio** [comment]
Dear @JohannaOtt,

Thank you for reporting this issue, we are aware of the problem. We will come back to you as soon the INSPIRE Validator is up and running again.

Sorry for the inconvenience caused,

Iñaki

**Comment by inakidiazdecerio** [comment]
Dear @JohannaOtt,

INSPIRE Validator is up and running again.

Sorry for the inconvenience,

Iñaki
