### ISSUE TITLE
WMS 1.3 beta has error in transparent test

### ISSUE THREAD

**Issue by nmtoken** [INSPIRE-MIF/helpdesk-validator#250]
In the Executable Test Suites WMS test there is a test **at58-getmap-transparent-parameter** that tests _that the service accepts the optional parameter TRANSPARENT_

The test fails if the service sends an exception response to a GetMap request like 

> https://maps3.sgu.se/geoserver/inspire/ows?BBOX=11.2075310914546%2C55.3671957158819%2C24.1035511519344%2C68.9681779468207&CRS=CRS%3A84&FORMAT=image%2Fpng&HEIGHT=500&LAYERS=MR.SGU.MineralResources&REQUEST=GetMap&SERVICE=WMS&STYLES=&TRANSPARENT=true&VERSION=1.3.0&WIDTH=500

The thing to note here is **TRANSPARENT=true&**

That's incorrect, the specification tells us that:

>  parameter names shall not be case sensitive, but parameter values shall be.

The correct values for transparent are **TRUE|FALSE**.   So TRANSPARENT=true& is incorrect and should/could result in an exception, depending on whether the server decides it's a duplication of the default traNsparent=FALSE, or a plain error.

**Comment by danielnavarrogeo** [comment]
Dear @nmtoken 

Thank you for opening this issue. We agree with you that the correct values are TRUE or FALSE.

We will fix it and let you know when a solution is ready.

Regards

**Comment by danielnavarrogeo** [comment]
Dear @nmtoken 

The values for TRANSPARENT parameter have been changed to uppercase.

Could you check the changes in [staging instance](http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp) and provide us feedback?

Regards

**Comment by danielnavarrogeo** [comment]
Dear @nmtoken 

Could you please check the fix deployed in [staging instance](http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/) and provide us feedback?

Regards

**Comment by nmtoken** [comment]
Still reporting lowercase (**TRANSPARENT=true&**) in the test (http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/v2/TestRuns/EIDa269faad-d5b3-4324-a37f-c47aeb283346.html)

> https://maps3.sgu.se/geoserver/inspire/ows?BBOX=11.2075310914546%2C55.3671957158819%2C24.1035511519344%2C68.9681779468207&CRS=CRS%3A84&FORMAT=image%2Fpng&HEIGHT=500&LAYERS=MR.SGU.MineralResources&REQUEST=GetMap&SERVICE=WMS&STYLES=&TRANSPARENT=true&VERSION=1.3.0&WIDTH=500

**Comment by danielnavarrogeo** [comment]
Dear @nmtoken 

We have just reloaded the staging instance. Would you mind check it again and provide us feedback?

Regards

**Comment by nmtoken** [comment]
Yes, works for me now `TRANSPARENT=TRUE&` and `TRANSPARENT=FALSE&` are sent

**Comment by danielnavarrogeo** [comment]
Thank you @nmtoken for your feedback.
