### ISSUE TITLE
is the test for ETRS89 still appropriate 

### ISSUE THREAD

**Issue by nmtoken** [INSPIRE-MIF/helpdesk-validator#251]
In **at40-getcapabilities-layer-crs** there's a test that `a supported CRS is provided based on ETRS89 for continental Europe and on ITRS outside continental Europe`.

But in the alternative encoding guidance a non ETRS89 projection is allowed ~ CRS:84

Should the at40-getcapabilities-layer-crs test be removed?

**Comment by iuriemaxim** [comment]
CRS:84 is required by WMS 1.3.0 standard (as the coordinates in the <EX_GeographicBoundingBox> element are in CRS:84), so I don't think that it can be removed from an INSPIRE compliant WMS, even if the CRS:84 is not required by INSPIRE.
See also https://inspire.ec.europa.eu/id/document/tg/rs

![image](https://user-images.githubusercontent.com/20813598/76295518-6faa6380-62bd-11ea-87da-4cdf16d9bae9.png)

**Comment by iuriemaxim** [comment]
Probably it is possible to automate the test at40-getcapabilities-layer-crs in order to provide an error if none of the INSPIRE CRSs are provided in the GetCapabilities document of a WMS service..

**Comment by nmtoken** [comment]
> CRS:84 is required by WMS 1.3.0 standard

It's required to be supported by the software, but a service doesn't have to provide it as an allowable CRS in a published service, just like a provider can choose which other CRS to support; the issue I'm raising isn't though whether CRS:84 is one of the listed CRS, it's if the there are no ETRS-89 CRS listed but CRS:84 is listed. That should still pass the test, as indeed should EPSG:4326, and indeed any CRS that uses the World Geodetic System 1984 (WGS 84) datum, as long as the data provider doesn't see it as problematic...

This comes about because of the specification of Alternative Encoding guidelines.

ref: https://github.com/INSPIRE-MIF/2017.2/blob/master/GeoJSON/geojson-encoding-rule.md

> Coordinate Reference Systems
As per the requirements of the GeoJSON - IETF RFC 7946 specification, the default CRS for any data set delivered using this encoding rule is a geographic coordinate reference system, using the World Geodetic System 1984 (WGS 84) datum, with longitude and latitude units of decimal degrees, unless there is prior arrangement. This is equivalent to the coordinate reference system identified by the Open Geospatial Consortium (OGC) URN urn:ogc:def:crs:OGC::CRS84.

> NOTE As INSPIRE mandates the use of the European Terrestrial Reference System 1989 (ETRS89, see Requirement 1) for the areas within the geographical scope of ETRS89 and both CRS84 and ETRS89 use the GRS 80 ellipsoid (although with minor enhancements), we shall assume CRS84 to be equivalent to ETRS89. If, for any dataset, this assumption would be problematic, then GeoJSON cannot serve as an alternative encoding rule for that dataset.

**Comment by iuriemaxim** [comment]
GeoJSON would be part of a download service, not of a view service (WMS). I suppose that if dataset would be provided as GeoJSON, than this would not change the way the dataset would be delivered as GML, nor as that dataset would be viewed in a WMS service.

The fact that GeoJSON is imposing in the standard to store data in CRS:84 dates from 2016.

Till 2016 in GeoJSON data was in any CRS. We are still using GeoJSON files in Google Web Mercator Projection for ensuring performance in web based applications and the decision to impose a certain CRS in GeoJSON have a significant impact on resources used and rendering time in the browser or in apps.

**Comment by nmtoken** [comment]
This isn't a dig at GeoJSON; I know the draft specification allowed a crs member to specify any other CRS, but GeoJSON the standard only allows one which is CRS:84 and there is no crs member to allow you to specify another CRS in a standardised fashion (only by some prior arrangement).

This question is about the implications of allowing data providers to decide whether CRS:84 is good enough for their data, within the confines of the INSPIRE regulations.  If it applies to GeoJSON in a download service, why not other services? and other formats?

Bear in mind that vector tiles are a WMS offering, not WFS, so it's not impossible for a WMS to give a GeoJSON-VT response.

**Comment by MarcoMinghini** [comment]
Dear @nmtoken,
although I understand the overall logic, I would suggest not to mix things. The CRS84 requirement is specific to the INSPIRE-to-UML GeoJSON encoding, as it is a requirement inherited by the GeoJSON spec. In addition, that encoding is not (yet) an INSPIRE good practice. Perhaps @alexanderkotsev who has closely followed that work can provide more input.

For the time being the test should consistently reflect the requirement of the INSPIRE TG. A possibility might be to propose a revision of the TG (or even better a good practice on vector tiles).

**Comment by nmtoken** [comment]
@MarcoMinghini either it is legal to have a non-ETRS89 CRS or it's not legal.  The legislation doesn't mention any encoding.  The interpretation of the Alternative Encoding team was in certain situations it's possible, so it should apply everywhere.

Nonetheless, even if we say that for some odd reason it only applies to GeoJSON in some special circumstances, if the circumstance is the offing of a vector tile in a WMS, then this test will be invalid.

Perhaps, the test could also look for offered encodings?

The TG are after all just one interpretation of the legislation

**Comment by danielnavarrogeo** [comment]
Dear @nmtoken 

After some tests have been done, the test does not fail if CRS:84 is provided. The user should however perform a manual check and make sure that the scope is 'outside continantal Europe' if CRS:84 is used.

We will leave this issue open as discussion in case any other user wants to participate.

Regards

**Comment by dperezBM** [comment]
Dear all,

Thank you all for your feedback. We hope that the answer you were given would have helped you. In case you have any other questions or problems, please feel free to open a new issue.

Best regards.
