### ISSUE TITLE
WMS 1.3 beta test CRS/BoundingBox issue

### ISSUE THREAD

**Issue by nmtoken** [INSPIRE-MIF/helpdesk-validator#252]
In the WMS 1.3 test **at36-getcapabilities-layer-bounding-box**  I'm getting an error `A BoundingBox is provided for non existing CRS either in the layer itself nor in a parent layer.`

The root layer for the service reports 20 CRS.

    <CRS>CRS:84</CRS>
    <CRS>EPSG:2400</CRS>
    <CRS>EPSG:3006</CRS>
    <CRS>EPSG:3007</CRS>
    <CRS>EPSG:3008</CRS>
    <CRS>EPSG:3009</CRS>
    <CRS>EPSG:3010</CRS>
    <CRS>EPSG:3011</CRS>
    <CRS>EPSG:3012</CRS>
    <CRS>EPSG:3013</CRS>
    <CRS>EPSG:3014</CRS>
    <CRS>EPSG:3015</CRS>
    <CRS>EPSG:3016</CRS>
    <CRS>EPSG:3017</CRS>
    <CRS>EPSG:3018</CRS>
    <CRS>EPSG:3021</CRS>
    <CRS>EPSG:3857</CRS>
    <CRS>EPSG:4258</CRS>
    <CRS>EPSG:4326</CRS>
    <CRS>EPSG:900913</CRS>

and the layers report 20 (the same 20 CRS but in a different order) bounding boxes like:

    <BoundingBox CRS="EPSG:2400" minx="6137390.6797204185" miny="1208297.4237487656" maxx="7675562.557708611" maxy="2025251.7699124748"/>
    <BoundingBox CRS="EPSG:3006" minx="6135770.452929046" miny="259684.0050077687" maxx="7677837.391538707" maxy="1076143.5974246587"/>
    <BoundingBox CRS="EPSG:3007" minx="6138395.009631221" miny="99751.39456478368" maxx="7701645.20487165" maxy="915411.7167689488"/>
    <BoundingBox CRS="EPSG:3008" minx="6138118.403613457" miny="4651.968066317902" maxx="7690546.184811202" maxy="820978.3164638255"/>
    <BoundingBox CRS="EPSG:3009" minx="6138225.743226336" miny="-90412.15985617373" maxx="7680909.755440882" maxy="726374.147083492"/>
    <BoundingBox CRS="EPSG:3010" minx="6138558.7508550035" miny="-185417.6649788171" maxx="7672737.569950899" maxy="631625.1457019188"/>
    <BoundingBox CRS="EPSG:3011" minx="6138163.097969501" miny="-280340.88585896493" maxx="7668929.117860458" maxy="536756.4346571134"/>
    <BoundingBox CRS="EPSG:3012" minx="6138124.080493759" miny="-42885.9596441286" maxx="7685545.035969097" maxy="773695.9361468436"/>
    <BoundingBox CRS="EPSG:3013" minx="6138136.137185056" miny="-137923.70963645558" maxx="7676640.540384196" maxy="679016.1627480525"/>
    <BoundingBox CRS="EPSG:3014" minx="6138183.956004276" miny="-232891.05662195355" maxx="7669201.00587983" maxy="584204.2118458112"/>
    <BoundingBox CRS="EPSG:3015" minx="6138615.728403173" miny="-327764.1203374828" maxx="7672435.834097797" maxy="489284.849413655"/>
    <BoundingBox CRS="EPSG:3016" minx="6138199.286045368" miny="-422518.4821062682" maxx="7680548.3625816945" maxy="394282.23013459955"/>
    <BoundingBox CRS="EPSG:3017" minx="6138128.0635218965" miny="-517129.04988239426" maxx="7690125.19601949" maxy="299220.03201897285"/>
    <BoundingBox CRS="EPSG:3018" minx="6138440.787800478" miny="-611569.9224352842" maxx="7701164.693364408" maxy="204121.59041181763"/>
    <BoundingBox CRS="EPSG:3021" minx="6137390.6797204185" miny="1208297.4237487656" maxx="7675562.557708611" maxy="2025251.7699124748"/>
    <BoundingBox CRS="EPSG:3857" minx="1247616.6541505074" miny="7433459.945171671" maxx="2683195.04054296" maxy="1.0740908824518066E7"/>
    <BoundingBox CRS="EPSG:4326" minx="55.3671957158819" miny="11.2075310914546" maxx="68.9681779468207" maxy="24.1035511519344"/>
    <BoundingBox CRS="EPSG:4258" minx="55.3671957158819" miny="11.2075310914546" maxx="68.9681779468207" maxy="24.1035511519344"/>
    <BoundingBox CRS="EPSG:900913" minx="1247616.6541505074" miny="7433459.945171671" maxx="2683195.04054296" maxy="1.0740908824518066E7"/>
    <BoundingBox CRS="CRS:84" minx="11.2075310914546" miny="55.3671957158819" maxx="24.1035511519344" maxy="68.9681779468207"/>

See:

https://resource.sgu.se/service/wms/inspire/MR-Mineralresurser?service=WMS&request=GetCapabilities&

Test report:

http://inspire.ec.europa.eu/validator/v2/TestRuns/EID73125b81-205a-47bd-b904-5705e5f8672f.html?lang=en#EIDbfd363bb-0170-1000-4062-b5981a5abce6

**Comment by danielnavarrogeo** [comment]
Dear @nmtoken 

The problem seems to be with the layer 'Byggråmaterial (Building raw materials, dimension stones)'.

That layer has a BoundingBox which CRS attribute is "EPSG:3034". However, that CRS is not defined.

Regards

**Comment by nmtoken** [comment]
Thanks for the spot, will pass on to service provider for a fix.  Would be useful to report the missing CRS in the error report.

**Comment by danielnavarrogeo** [comment]
I think that is a good idea. We will provide the missing CRS in the error report.

We will leave the issue open to track the enhancement.

Regards

**Comment by danielnavarrogeo** [comment]
Dear @nmtoken 

A solution has been developed and it is ready for testing in [staging instance](http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/).

Could you please check it and provide us feedback?

Regards

**Comment by carlospzurita** [comment]
Dear @nmtoken 

Did you check the fix published in the [staging instance](http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/) ?

Thank you

**Comment by josemasensio** [comment]
Thanks @nmtoken for your feedback.
Please let us know if you have any other issue.
Best regards.
