### ISSUE TITLE
View Service validation: test on harmonised layer names Species Distribution (SD) incorrect

### ISSUE THREAD

**Issue by thijsbrentjens** [INSPIRE-MIF/helpdesk-validator#254]
When testing a View Service with data of SD conforming to the data specifications, the validator fails the test at-39-getcapabilites-layer-name even if layer names starting with `SD.` are provided, but I think it should not fail. (This is reported by a third party to us)

- [x] a description of the steps to reproduce your issue: 

1. View Service validation with WMS
2. Service URL: https://geodata.nationaalgeoregister.nl/rvo/invasieve-exoten/wms/v1_0?REQUEST=GetCapabilities&service=WMS
3. see test at-39-getcapabilites-layer-name

- [x] the browser and version used: n/a
- [x] the name of the Test that failed or better: change the `Level of Detail`
in the Report by clicking on `All Details`, then scroll down to the failed test
and copy the Link on the right-hand side of the `Assertion URI`
- [x] the URL of your service / the file you have uploaded or referenced (as
an attachment).
https://geodata.nationaalgeoregister.nl/rvo/invasieve-exoten/wms/v1_0?REQUEST=GetCapabilities&service=wms 

According to the TG, section 11 Portrayal of SD, the layer names must follow a format:
`SD.<CodeListValue>`

There is no fixed list of layers provided. More specs are not available. My proposal is to change the test and accept any layer names starting with `SD.` as being valid.

For ACMF a similar solution seems to be implemented: https://github.com/inspire-eu-validation/community/issues/227

**Comment by danielnavarrogeo** [comment]
Dear @thijsbrentjens 

Yes, this is related with #227 but for a different data specification.

We will provide a fix and let you know when ready for testing.

Regards

**Comment by danielnavarrogeo** [comment]
Dear @thijsbrentjens 

A fix has been developed and it is available for testing in [staging instance](http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/).

Could you please check it and provide us feedback?

Regards

**Comment by thijsbrentjens** [comment]
tested and works fine now. Thanks
