### ISSUE TITLE
Validator issue in at38-getcapabilities-layer-authority-url

### ISSUE THREAD

**Issue by nmtoken** [INSPIRE-MIF/helpdesk-validator#255]
In the WMS 1.3 beta test at38-getcapabilities-layer-authority-url l that tests _Test that AuthorityURL and Identifier elements are used._  I get an error **A layer's Identifier has a non unique value for its authority.**

The service has an AuthorityURL in the root layer like:

    <AuthorityURL name="SGU">
        <OnlineResource xlink:type="simple" xlink:href="https://resource.sgu.se"/>
    </AuthorityURL>

and Identifiers in layers like:

    <Identifier authority="SGU">bdbe49c1-626b-4cdb-b9d3-5e13a0c643e4</Identifier>

Why is this an error?

Ref:

http://inspire.ec.europa.eu/validator/v2/TestRuns/EID73125b81-205a-47bd-b904-5705e5f8672f.html?lang=en#EIDbfd363bb-0170-1000-4062-b5981a5abce6

**Comment by iuriemaxim** [comment]
We had the same issue when two or more layers had the same Id (GUID).

It is in relation with the issue of the Linkage Checker that expect all layers to have the same Id with the Id of the dataset:

https://ies-svn.jrc.ec.europa.eu/issues/3818

**Comment by danielnavarrogeo** [comment]
Dear @nmtoken 

The problem with your capabilities is that the layer's identifiers are repeated. The same identifier 'bdbe49c1-626b-4cdb-b9d3-5e13a0c643e4' is used 16 times.

The Identifier of the layers shall be unique for its authority. We made a test changing them so every layer has distinct identifiers and the test at38 passes successfully.

Regards

**Comment by nmtoken** [comment]
Not my capabilities, but the issue is that the data set is the same, across the layers.  Each layer is just a different representation, so the same identifier here is correct.   One data set  = one identifier.  It is unfortunate that a WMS deals in layers and not data sets.

**Comment by iuriemaxim** [comment]
@nmtoken 
As I remember it this was discoused many years ago.

In INSPIRE one dataset = one or more layers (see for example hydrography where there are multiple
layers: rivers, lakes, but only one dataset in which there is a network with features in topology).

Itbis possible also to make datasets with features and layers from different data themes.

In order to implement services for multiple datasets, there should be different endpoints that can be ensured with some software by using multiple instances!!!

I found this old topic, maybe it helps to understand requirement 52 and tehnical issues that exist: 

https://inspire.ec.europa.eu/forum/discussion/view/88206/it-seems-that-there-is-only-one-fully-compliant-solution-to-serve-multiple-harmonised-datasets-trough-wfs-20

**Comment by iuriemaxim** [comment]
If what you call representation is actualy a style, than styles need to be used. Name of the layer would be the same but same layer can be viewed with different styles. Styles can also filter the data.

**Comment by nmtoken** [comment]
Style is one way to deal with different representations from a set of data, but it's not always appropriate, for example if you want to put out different attributes as well, or different relationships. 

When you have a complex feature data set, and start flattening it to give lots of different views (or layers/simple feature types) then style alone is not going to be appropriate.

The one set of data per service endpoint is an INSPIRE WFS solution, not sure though if it applies either to WMS or WCS.

**Comment by iuriemaxim** [comment]
As far as I remember there are no provisions for attributes in WMS in INSPIRE. A data provider may provide them, but there is no obligation. Therefore most probably in the case that a data provider wants to serve more than is required by INSPIRE, it should consider the option to declare that service being an Spatial Data Service, not a Network Service. Then it can validate metadata against Conformance Classes 5/6/7 and should not perform any validation against any view and download service conformance classes, as those services will not be anymore declared as being Network Services. TGs are describing in Portrayal section how the datasets should be rendered by default for Network Services only. I think that any extra could be either another style or an SDS. That WMS can be declared  trough its service metadata as being an SDS.

Hope it helps

**Comment by nmtoken** [comment]
> As far as I remember there are no provisions for attributes in WMS in INSPIRE

Well it's correct that the view (portrayal) service provision is a bit muddled in most TG, with the emphasis on download services that has complicated things, but I'm not sure it's correct to say there are no provisions for attributes.  Attributes are the 'thing' that are styled, they must exist, the IR has:

> IR Requirement
> Article 14
> Portrayal
> 3. For spatial object types whose objects can be further classified using a code list-valued attribute, several layers may be defined. Each of these layers shall include the spatial objects
corresponding to one specific code list value. In the definition of such sets of layers in Annexes
II-IV,
> (a) the placeholder <CodeListValue> shall represent the values of the relevant code list, with the
first letter in upper case,
> (b) the placeholder <human-readable name> shall represent the human-readable name of the
code list values;
> (c) the spatial object type shall include the relevant attribute and code list, in parentheses;

I can't see how that fits with no provisions 

> TGs are describing in Portrayal section how the datasets should be rendered by default for Network Services only.

I'm not sure what is meant by a default network service as opposed a non-default service?  Default styling?

TG's  often don't say how a dataset should be rendered, they say what layers should exist, and what those layers **MUST** be called if they exist (also in the IR which makes things complicated), but the applied styling is often just recommended (there is no default).

Guidance elsewhere (something Micheal Lutz posted) is that you shouldn't be needing to have an INSPIRE service and a non-INSPIRE service to provide additional/optional data, just one service, so the validator will need to allow for this I think.

**Comment by danielnavarrogeo** [comment]
Dear @nmtoken 

After some internal discussions, we have agreed with you that the identifiers might be repeated in different layers if they refer to the same dataset.

We will update the test accordingly and let you know when it will be ready for testing.

Regards

**Comment by danielnavarrogeo** [comment]
Dear @nmtoken 

We have addressed this issue and it can be tested in [staging instance](http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/).

Could you please check the fix and provide us feedback?

Regards

**Comment by carlospzurita** [comment]
Dear @nmtoken 

Did you check the fix published in the [staging instance](http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/)

Thank you

**Comment by josemasensio** [comment]
Dear @nmtoken,
Glad to hear that! We will mark this issue as solved.
Please let us know if you have any other issue.
Best regards.

**Comment by iuriemaxim** [comment]
@MarcoMinghini @fabiovin 
This relaxation of the test will ensure less harmonisarion/interoperability within INSPIRE.
Please add a label “relaxed test” to all issues that are not issues, but just relaxed tests.
All of them should be analised to see their impact on the scope of INSPIRE as less and less interoperability and harmonisation is ensured within INSPIRE.

For all these relaxed tests, would be important to list the corresponding Requirement and the TG in order to decide if those requirements should become recomendations.

If those requirements will not become recommendations, then the relaxed tests should be reverted to initial solution.

What kind of validations will be made for harmonised services according to ISDSS IR?
