### ISSUE TITLE
INSPIRE-Validator API: Control test runs - report ready for download?

### ISSUE THREAD

**Issue by ghost** [INSPIRE-MIF/helpdesk-validator#256]
Hi all,

I have one question regarding INSPIRE-Validator API. 

There is a possibility to get progress of test run using [GET Method](http://inspire.ec.europa.eu/validator/swagger-ui.html#!/4._Manage_Test_Runs/progressLogUsingGET).

One example of test run progress:

```
{
  "log": "[ \"Test Run started\", \"Assertion X failed\"]",
  "max": "103",
  "val": "39"
}
```
`log`  - log message
`max` - estimated total number of Test Steps 
`val`   - the number of already executed Test Steps

Is it possible to query this test-run-progress-JSON-response in order to check if complete report (HTML, JSON und XML) is ready for download from INSPIRE-Validator?

Kind regrads.

**Comment by danielnavarrogeo** [comment]
Dear @DeordD 

In principle, it is not possible to make such a request. You can check the available requests in http://inspire.ec.europa.eu/validator/swagger-ui.html

I assign @carlospzurita who will provide you more feedback about the API.

Regards

**Comment by ghost** [comment]
Dear @danielnavarrogeo ,

thanks for the information.

It seems that if `max eq val` - report in HTML format can be downloaded _shortly_ after.  I didn't check it for JSON and XML format.

I am looking forward to hear from @carlospzurita. 

Kind regards.

**Comment by ghost** [comment]
Dear @danielnavarrogeo 

After some testing I can verify that criteria is working.

Documentation for Web-API can be found [here](http://docs.etf-validator.net/v2.0/Developer_manuals/WEB-API.html).

This issue can be closed.

**Comment by danielnavarrogeo** [comment]
Thank you @DeordD for your feedback. We will then close the issue.
