### ISSUE TITLE
Metadata 2.0- double error: Limitation on public access with two <gmd:otherConstraints>/<gmx:Anchor>  instances causes an error + this (inexistent) error is incorrectly referred to the Conditions applying to access and use 

### ISSUE THREAD

**Issue by sMorrone** [INSPIRE-MIF/helpdesk-validator#258]
While validating a dataset metadata 2.0 XML file (here uploaded for you to test)
[TEST237ee8ff-2c10-4773-8c2e-2d3bbe9e75d1.zip](https://github.com/inspire-eu-validation/community/files/4374885/TEST237ee8ff-2c10-4773-8c2e-2d3bbe9e75d1.zip)
I noticed that:
a metadata element 'Limitations on public access' having two gmd:otherConstraints/gmx:Anchor instances (therefore correct)  causes an error on the element 'Conditions applying to access and use'.
**NOTE:**
It is worth highlighting that If I delete one of the gmd:otherConstraints/gmx:Anchor element my metadata files validates successfully.
The **ETF error message** is referred to the md common req C.18: Conditions for Access and use and is the following:
” System error in the Executable Test Suite. Please contact a system administrator. Error information:
[err:XPTY0004] Item expected, sequence found: (element gmx:Anchor {...}, ...).  (1441/240)”

Below the **“faulty” code snippet**:
```
<!-- Limitations on public access -->		 
    <gmd:resourceConstraints>
     <gmd:MD_LegalConstraints>
        <gmd:accessConstraints>
          <gmd:MD_RestrictionCode codeListValue="otherRestrictions"  codeList="http://standards.iso.org/iso/19139/resources/gmxCodelists.xml#MD_RestrictionCode"/>
        </gmd:accessConstraints>
        <gmd:otherConstraints>
<gmx:Anchor xlink:href="http://inspire.ec.europa.eu/metadata-codelist/LimitationsOnPublicAccess/INSPIRE_Directive_Article13_1a">Public access to spatial data sets and services would adversely affect the confidentiality of the proceedings of public authorities, where such confidentiality is provided for by law.</gmx:Anchor>
        </gmd:otherConstraints>
        <gmd:otherConstraints>
<gmx:Anchor xlink:href="http://inspire.ec.europa.eu/metadata-codelist/LimitationsOnPublicAccess/INSPIRE_Directive_Article13_1e">Public access to spatial data sets and services would adversely affect intellectual property rights.
</gmx:Anchor>
        </gmd:otherConstraints>	
</gmd:MD_LegalConstraints>
 </gmd:resourceConstraints>
			  
<!-- Conditions applying to access and use -->			  
  <gmd:resourceConstraints>
    <gmd:MD_LegalConstraints>
     <gmd:useConstraints>
       <gmd:MD_RestrictionCode codeList="http://standards.iso.org/iso/19139/resources/gmxCodelists.xml#MD_RestrictionCode" codeListValue="otherRestrictions"/>
     </gmd:useConstraints>
     <gmd:otherConstraints>
       <gmx:Anchor xlink:href="https://creativecommons.org/licenses/by-nc-nd/4.0/legalcode">Attribution-NonCommercial-NoDerivatives 4.0 International</gmx:Anchor>
     </gmd:otherConstraints>
   </gmd:MD_LegalConstraints>
  </gmd:resourceConstraints>
```

It seems to me that the above piece of code is respecting the TG req. C.17:
•	Limitations on public access shall be described using exactly one gmd:resourceConstraints/gmd:MD_LegalConstraints element. 
•	the gmd:resourceConstraints/gmd:MD_LegalConstraints element shall include a combination of 
-	one instance of gmd:accessConstraints/gmd:MD_RestrictionCode element with code list value "otherRestrictions"
-	at least one instance of gmd:otherConstraints/gmx:Anchor pointing to one of the values from the code list for LimitationsOnPublicAccess.

and TG  req. C.18:
•	Conditions for access and use shall be described using exactly one gmd:resourceConstraints/gmd:MD_LegalConstraints element. 
•	the gmd:resourceConstraints/gmd:MD_LegalConstraints element shall be encoded as follows
-	One instance of either gmd:accessConstraints or gmd:useConstraints element shall be given. In both cases this element shall contain a gmd:MD_RestrictionCode element with code list value "otherRestrictions”
-	at least one instance of gmd:otherConstraints describing the actual conditions

Could you have a look into this?
Thank you
Stefania

**Comment by danielnavarrogeo** [comment]
Dear @sMorrone 

Thank you for opening this issue. We are analyzing it and we will keep you posted.

Regards

**Comment by danielnavarrogeo** [comment]
Dear @sMorrone 

You are right. The metadata you have provided should pass the test.

We will fix it and ask you to test it when ready.

Regards

**Comment by danielnavarrogeo** [comment]
Dear @sMorrone 

A fix has been developed and it is available for testing in [staging instance](http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp).

Could you please check it and provide us feedback?

Regards

**Comment by sMorrone** [comment]
I just tested and it works correctly now.

Thank you
Stefania

**Comment by danielnavarrogeo** [comment]
Thank you very much @sMorrone for your feedback.

**Comment by stephyritz** [comment]
Dear @danielnavarrogeo,
Same problem as @sMorrone since the release of the validator. But now it works for me in stagging instance. Was it linked to a multiple presence of <gmd:otherConstraints> ?
Anyway thank you both for highlighting and resolving this issue.

**Comment by MarcoMinghini** [comment]
Dear @stephyritz,
this fix is only implemented in the staging instance. It will also be included in production instance starting from the next release of the validator.

**Comment by stephyritz** [comment]
Yes, no problem. I can wait for the 15/06 to see all my test reports in green fot datasets and series ; )
