### ISSUE TITLE
Metadata MD SDS 3.6:Coupled Resource

### ISSUE THREAD

**Issue by idevisser** [INSPIRE-MIF/helpdesk-validator#259]
I got an unexpected error with this test.

error message;
XML document 'hh_n_ATOM_2006_aangepast.xml', record 'wt-3730-e750-485a-9c0c-39bf9bt72cf9': The metadata record has a linkage property, but it references a resource at 'http://nationaalgeoregister.nl/geonetwork/srv/en/csw?service=CSW&version=2.0.2&request=GetRecordById&outputschema=http://www.isotc211.org/2005/gmd&elementsetname=full&id=wt-3730-e750-485a-9c0c-39bf9be72cf9#MD_DataIdentification' that is not an HTTP or HTTPS URL.

This url is pointing to an XML document that contains a gmd:MD_DataIdentification object, with a reference to the gmd:MD_DataIdentification element.

expected behaviour is pass the test

the used XML;
[hh_n_ATOM_2006_aangepast.zip](https://github.com/inspire-eu-validation/community/files/4380069/hh_n_ATOM_2006_aangepast.zip)

Best regards Ine

**Comment by danielnavarrogeo** [comment]
Dear @idevisser 

Thank you for opening this issue. We will analyze it and keep you posted.

Regards

**Comment by josemasensio** [comment]
Dear @idevisser,

Thank you for your message. After some internal research, we were not able to reproduce the issue that you have reported to us (check [validator test](http://inspire.ec.europa.eu/validator/v2/TestRuns/EIDef3b112f-1672-4d3f-ab8d-32c4a39b9fc1.html)). 
Please, could you confirm to us if this is still happening to you?

Thank you and best regards.

**Comment by idevisser** [comment]
Dear @josemasensio,

I have checked the issue, it seems it does'nt occur anymore.
Issue can be closed.

Best regards Ine
