### ISSUE TITLE
Metadata 1.3: Conformity - error on gmd:pass element reporting the value "not evaluated"

### ISSUE THREAD

**Issue by AntoRot** [INSPIRE-MIF/helpdesk-validator#260]
By testing a dataset metadata record based on TG v. 1.3, an error is raised when the declaration of the degree of conformity refers to the value ‘not evaluated’, corresponding to an empty `gmd:pass` element with a nil reason attribute with value "unknown" in XML file, i.e.:

`<gmd:pass gco:nilReason="unknown"/>`

As this is a value included in the domain defined in Part D.5 in the Regulation (EC) 1205/2008 (together to ‘conformant’ and ‘not conformant’), no specific requirement is defined in the MD TG 1.3 to force the use of only ‘conformant’ or ‘not conformant’ (i.e. true or false). 

This is also pointed in the notes in the related ATS: https://github.com/inspire-eu-validation/metadata/blob/1.3/iso-19115-19119/ds-conformity.md. But the ETS doesn't cover this aspect: see rows 275-276 in https://github.com/inspire-eu-validation/ets-repository/blob/master/metadata/1.3/iso/ets-md-iso-bsxets.xml.

Furthermore, the possibility to use also the value ‘not evaluated’ is kept in the TG 2.0 (see TG Req. C.22). Indeed this error is not raised in the validation against the v. 2.0. 

Consequently, no error should be raised.

**Comment by danielnavarrogeo** [comment]
Dear @AntoRot 

Thank you for opening this issue. We will fix it and ask you to test it when ready.

Regards

**Comment by danielnavarrogeo** [comment]
Dear @AntoRot 

A fix has been developed. Could you check in [staging instance](http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/) and provide us feedback?

Regards

**Comment by AntoRot** [comment]
Dear @danielnavarrogeo,

I tested several metadata records and the solution works fine now.

Thank you very much!

**Comment by danielnavarrogeo** [comment]
Thank you @AntoRot for your feedback.
