### ISSUE TITLE
New Release of the Validator for Monitoring 2019

### ISSUE THREAD

**Issue by MarcoMinghini** [INSPIRE-MIF/helpdesk-validator#263]
Dear all,

we are exceptionally planning to release a new version of the INSPIRE Reference Validator today (27/3). This version will be used within the Monitoring 2019 process, in particular for the calculation of indicators MDi1.1 and MDi1.2 based on the validation of metadata published by EU Member States on December 16, 2019.

This new release will build on the latest release ([v.2020.1](https://github.com/inspire-eu-validation/community/releases/tag/v2020.1), released last week) but incorporates some additional feedback received by EU Member States. More information is available [here](https://github.com/inspire-eu-validation/community/releases/tag/v2020.1.1).

For this reason, the Validator will be unavailable today during the deployment of the new release.

**Comment by carlospzurita** [comment]
The validator was successfully updated and is available on http://inspire.ec.europa.eu/validator
