### ISSUE TITLE
GeoTIFF and INSPIRE media types register

### ISSUE THREAD

**Issue by heidivanparys** [INSPIRE-MIF/helpdesk-validator#265]
OGC published the [OGC GeoTIFF standard](http://docs.opengeospatial.org/is/19-008r4/19-008r4.html) last september.

It includes a section on the media type that should be used: `image/tiff; application=geotiff`, 
see 
[Media Types for GeoTIFF data encoding](http://docs.opengeospatial.org/is/19-008r4/19-008r4.html#_media_types_for_geotiff_data_encoding)

The validator should take this into account. GeoTIFF still follows [RFC 3302](https://www.rfc-editor.org/info/rfc3302), as the application parameter is defined there.

I don't know whether GeoTIFF should be added the INSPIRE media types register as a separate entry, or whether the tests should be updated so that `image/tiff; application=geotiff` is allowed as well, although the registry only contains `image/tiff`.

**Comment by danielnavarrogeo** [comment]
Dear @heidivanparys 

We will analyze it and we will keep you posted.

Regards

**Comment by danielnavarrogeo** [comment]
Dear @heidivanparys 

Which Conformance Classes/ETS do you mean?

Regards

**Comment by heidivanparys** [comment]
The INSPIRE media types registry is referred to in this test: https://github.com/inspire-eu-validation/download-service/blob/master/atom-pre-defined/dataset-feed-link-media-type.md

**Comment by fabiovin** [comment]
I think GeoTIFF should not be added to the INSPIRE media types register as a separate entry because of the `image/tiff` application parameter is optional (see https://www.iana.org/assignments/media-types/image/tiff).

In any case, although the registry only contains `image/tiff`, I think the value `image/tiff; application=geotiff` should be allowed as well.
The validator should check only the media type value, allowing the presence of the application parameter without check it.

@danielnavarrogeo could you please check the related ETS?

**Comment by carlospzurita** [comment]
This issue was marked as discussion some time ago but due to it was left behind. We are relabeling as "Under analysis" and will address it.

**Comment by carlospzurita** [comment]
Dear @heidivanparys and @fabiovin 

We have added on the staging instance the additional checks for the media types. Can you please check again the test?

**Comment by carlospzurita** [comment]
Dear @heidivanparys  

Did you have the opportunity to test the solution for this issue?

**Comment by heidivanparys** [comment]
@carlospzurita I don't have a test data set for this issue, so I cannot really test this issue. I tried to review the changes done to https://github.com/inspire-eu-validation/ets-repository/blob/issue-265/service/ds-atom-pre-defined-soapui-project.xml, but that is quite hard to read, and opening the file in SoapUI does not help.

So I trust the issue has been solved.

**Comment by carlospzurita** [comment]
Dear @heidivanparys 

Thank you for your comment, we are moving it into production instance.

Kind regards.
