### ISSUE TITLE
Failed to read schema document for Soil draft schema

### ISSUE THREAD

**Issue by JohannaOtt** [INSPIRE-MIF/helpdesk-validator#269]
I get the error "XML document 'testExport.gml': https://inspire.ec.europa.eu/draft-schemas/so/4.0/Soil.xsd, 5:145: schema_reference.4: Failed to read schema document 'http://inspire.ec.europa.eu/schemas/base/3.3/BaseTypes.xsd', because 1) could not find the document; 2) the document could not be read; 3) the root element of the document is not <xsd:schema>."
I checked and all schemas mentioned here are available online.
I tested several Soil datasets using the soil draft schema (this is necessary because of missing links to OM_Observation in the v4.0 schema) during the last week and never ran into this error.

- I used the 4 'basic' GML conformance classes
- screenshot: 
![grafik](https://user-images.githubusercontent.com/34163838/78141822-54e68d00-742c-11ea-8695-f6c5b210cad0.png)
- Uploading the test report is not supported but here is the link to the log http://inspire.ec.europa.eu/validator/v2/TestRuns/EID1406164f-4bb2-49cd-a7d2-0242ee1088ad/log
- The issue occurs in the test with Test ID EID0eaac0f2-9ab3-44ab-9f02-4ee0a1587d14
- In case the source data is needed to analyze this issue, I need to contact the customer, the dataset belongs to and clarify if that is possible.

**Comment by danielnavarrogeo** [comment]
Dear @JohannaOtt 

Thank you for opening this issue. We will analyze it and keep you posted.

Regards

**Comment by danielnavarrogeo** [comment]
Dear @JohannaOtt 

We have identified an issue with the reverse proxy which is already solved.

Would you mind testing it again and provide us feedback?

Regards

**Comment by JohannaOtt** [comment]
I just checked and it looks good to me. Thank you for the quick solution!

**Comment by danielnavarrogeo** [comment]
Thank you @JohannaOtt
