### ISSUE TITLE
Metadata TG 1.3 schema validation

### ISSUE THREAD

**Issue by fabiovin** [INSPIRE-MIF/helpdesk-validator#270]
In order to avoid further issues related to the schema validation of MD TG 1.3, due, for instance, to the missing schemaLocation attribute or to the recent unavailability of some schemas (e.g. https://standards.iso.org/ittf/PubliclyAvailableStandards/ISO_19139_Schemas), we propose to validate the metadata following the sequence:

- First validation against the schema "https://inspire.ec.europa.eu/draft-schemas/inspire-md-schemas-temp/apiso-inspire/apiso-inspire.xsd".
- If fails, validation against schema "https://inspire.ec.europa.eu/draft-schemas/inspire-md-schemas-temp/iso_19139_20060504/iso_19139_20060504_wrapper.xsd".
- If fails, validation against schema(s) declared in schemaLocation attribute.

The first schema is a modified version of the original apiso schema (http://schemas.opengis.net/csw/2.0.2/profiles/apiso/1.0.0/apiso.xsd), created to bypass the http/https redirect problem. This schema refers to GML 3.2.1 version (namespase = xmlns:gml="http://www.opengis.net/gml/3.2")

The second schema was created as wrapper of the schemas (gmd, gmx and srv) which refer to GML 3.2.0 version (namespase = xmlns:gml="http://www.opengis.net/gml").

This solution should manage all cases and avoid further schema validation errors.

**Comment by danielnavarrogeo** [comment]
Dear @fabiovin 

Thank you for your proposal. We will update the schema validation in MD TG 1.3 accordingly.

Regards

**Comment by danielnavarrogeo** [comment]
Dear @fabiovin 

A fix has been developed and it is ready for testing in [staging instance](http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/).

Could you please check it and provide us feedback?

Regards

**Comment by fabiovin** [comment]
Dear @danielnavarrogeo,

I tested it and it works fine.

Thanks

**Comment by danielnavarrogeo** [comment]
Thank you @fabiovin
