### ISSUE TITLE
 INSPIRE THEME KEYWORD and datasetconformity errors

### ISSUE THREAD

**Issue by mcaletrio** [INSPIRE-MIF/helpdesk-validator#271]
Dear colleagues, since yesterday INSPIRE validator returns two new errors in metadata that validate days before. You can confirm it with your metadata example v 2,0  https://github.com/inspire-eu-validation/community/blob/master/examples/Dataset_metadata_2.0_example 

 I send you the validator report of your metadata example . 
http://inspire.ec.europa.eu/validator/v2/TestRuns/EIDb0627335-174c-4816-b740-417fcae590e6.html  

the error are related to:  
- Md datasets-and-series 1,4: INSPIRE THEME KEYWORD 
System error in the Executable Test Suite. Please contact a system administrator. Error information:
Code list http://inspire.ec.europa.eu/theme cannot be accessed.

- And Dataset conformity error

Thank you. Regards

**Comment by danielnavarrogeo** [comment]
Dear @mcaletrio 

Thank you for openning this issue. We will analyze it and keep you posted.

Regards

**Comment by danielnavarrogeo** [comment]
Dear @mcaletrio 

We have identified an issue with the reverse proxy which is already solved.

Would you mind testing it again and provide us feedback?

Regards

**Comment by mcaletrio** [comment]
Dear colleagues, thank you. The problem it’s solved.

I take this opportunity to tell you that I have problems when I write  
the title of the specification 1089/2010 in Spanish. It doesn’t  
recognize title and date. To avoid problems I have written it in  
English but it should be writen in the metadata language.

gmd:report>/ <gmd:DQ_DomainConsistency>/ <gmd:result>/  
<gmd:DQ_ConformanceResult>/ <gmd:specification>/ <gmd:CI_Citation>/   
<gmd:title>

https://eur-lex.europa.eu/legal-content/ES/TXT/PDF/?uri=CELEX:02010R1089-20141231&qid=1585838305320&from=en
Title: REGLAMENTO (UE) No 1089/2010 DE LA COMISIÓN de 23 de noviembre  
de 2010 por el que se aplica la Directiva 2007/2/CE del Parlamento  
Europeo y del Consejo en lo que se refiere a la interoperabilidad de  
los conjuntos y los servicios de datos espaciales

Regards

**Comment by danielnavarrogeo** [comment]
Dear @mcaletrio 

Thank you for testing the issue.

Regarding the title specification in Spanish, you should provide the following one:

> REGLAMENTO (UE) N o 1089/2010 DE LA COMISIÓN de 23 de noviembre de 2010 por el que se aplica la Directiva 2007/2/CE del Parlamento Europeo y del Consejo en lo que se refiere a la interoperabilidad de los conjuntos y los servicios de datos espaciales

Notice that the only difference with yours is that a space is missing between 'N' and 'o'.

You can find the valid titles of the Commission Regulation (EU) No 1089/2010 for every EU official language in http://inspire.ec.europa.eu/schemas/common/1.0/enums/

Regards

**Comment by mcaletrio** [comment]
Muchas gracias. Thank you very much and congratulations for your work.
Regards

**Comment by danielnavarrogeo** [comment]
Thank you @mcaletrio for your support.
