### ISSUE TITLE
New tests for Metadata 2.0 for Monitoring purpose

### ISSUE THREAD

**Issue by MarcoMinghini** [INSPIRE-MIF/helpdesk-validator#272]
Dear all,
as mentioned in [the presentation](https://webgate.ec.europa.eu/fpfis/wikis/display/InspireMIG/61st+MIG-T+meeting+2020-03-05?preview=/455051596/461181787/INSPIRE_Reference_Validator.pptx) given at the last MIG-T meeting on March 5, we are currently finalizing some new tests on metadata useful for Monitoring purposes, in particular for:

* testing that the spatial scope of the data set or data set series is provided in the metadata;
* testing that keyword(s) for priority data sets are provided in the metadata.

These tests will be included in a new Conformance Class for MD TG v.2.0 (although they are not officially included in the TG).

The ATS and ETS for these new tests are currently under finalization and in the next days they will be ready for testing in the staging instance.

**Comment by danielnavarrogeo** [comment]
Dear all,

The new tests for Metadata 2.0 for Monitoring purposes has been released.

The ATS can be found in the following link: https://github.com/inspire-eu-validation/metadata/blob/monitoring_metadata/monitoring/README.md

And the ETS is ready for testing in [staging instace](http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/) with the name: **Conformance Class 2b: INSPIRE data sets and data set series metadata for Monitoring**

Regards

**Comment by ghost** [comment]
Dear @danielnavarrogeo,

thanks a lot for providing the CC for Priority data set and Spatial scope.

Which languages are supported for thesaurus title and keyword? 

Kind regards.

**Comment by manilly** [comment]
Hi, the validator shows an error when defining the thesaurus name (for spatial scope and priority dataset) in gmx:anchor as following:

`<gmx:Anchor xlink:href="http://inspire.ec.europa.eu/metadata-codelist/PriorityDataset#">INSPIRE priority data set</gmx:Anchor>`

So the only difference to the test suite is the trailing hash ("#") at the end. imo that shouldn't be displayed as error, especially as GeoNetwork adds the thesaurus link like this.

Can you soften the test to accept the trailing hash?

**Comment by ghost** [comment]
Dear @danielnavarrogeo ,

any [news](https://github.com/inspire-eu-validation/community/issues/272#issuecomment-610794222) regarding supported languages for thesaurus title and keyword?

Kind regards

**Comment by alitka** [comment]
Dear @MarcoMinghini and @danielnavarrogeo,

Thanks for releasing the new tests for Metadata 2.0 for Monitoring purposes! @DeordD and I did a couple of test related to the entry of `spatial scope` in data set or data set series. Attachend you will find our results.

- [x] a description of the steps to reproduce your issue
1. go to http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp and select "Conformance Class 2b: INSPIRE data sets and data set series metadata for Monitoring" (plus the test suites "Common Requirements for ISO/TC 19139:2007 based INSPIRE metadata records." and Conformance Class 1: 'Baseline metadata for data sets and data set series')
2. start the test with different xml-files & 3. the error messages returned for the test "Monitoring requirements > "M.1: Spatial scope keyword" 

_case 1_ > **german** keyword as **gmx:Anchor**
- example 1: codeListValue: Europäisch, title: Räumlicher Anwendungsbereich; Expected: PASSED | [Report] : PASSED
- example 2:codeListValue: Europäisch, title: Räumlicher Anwendungsbereich, date: 2030-01-01; Expected: FAILED | [Report]: FAILED
- example 3: codeListValue: National, title: Räumlicher Anwendungsbereich, date: 2030-01-01, codeList: http://my.local.spatial-scope/national/; Expected: FAILED | [Report]: PASSED, MANUAL TEST

_case 2_ > **english** keyword as **gmx:Anchor**
- example 4: codeListValue: European, title: Spatial Scope; Expected: PASSED | [Report]: PASSED
- example 5: codeListValue: European, title: Spatial Scope, date: 2030-01-01; Expected: FAILED | [Report]: FAILED
- example 6: codeListValue: European, title: Spatial Scope, date: 2030-01-01, codeList: http://my.local.spatial-scope/national/; Expected: FAILED | [Report]: PASSED, MANUAL TEST

_case 3_ > **german** keyword as **gco:CharacterString**
- example 7: codeListValue: Europäisch, title: Räumlicher Anwendungsbereich; Expected: PASSED | [Report]: FAILED
- example 8: codeListValue: Europäisch, title: Räumlicher Anwendungsbereich, date: 2030-01-01; Expected: FAILED | [Report]: FAILED with non-expected message
- example 9: codeListValue: National, title: Räumlicher Anwendungsbereich, date: 2030-01-01, codeList: http://my.local.spatial-scope/national/; Expected: FAILED | [Report]: PASSED, MANUAL TEST

_case 4_ > **english** keyword as **gco:CharacterString**
- example 10: codeListValue: European, title: Spatial Scope; Expected: PASSED | [Report]: PASSED
- example 11: codeListValue: European, title: Spatial Scope, date: 2030-01-01; Expected: FAILED | [Report]: FAILED
- example 12: codeListValue: European, title: Spatial Scope, date: 2030-01-01, codeList: http://my.local.spatial-scope/national/; Expected: FAILED | [Report]: PASSED, MANUAL TEST

- [x] the Test Report (attachment to the issue)
case 1 to 4: [DE_spatialScopeReports_case1-4.zip](https://github.com/inspire-eu-validation/community/files/4586874/DE_spatialScopeReports_case1-4.zip)

- [x] the name of the Test that failed or better: change the `Level of Detail`
http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/v2/TestRuns/EID12b92b45-ade3-4323-a00d-a077739aaa2f.html?lang=de#EID104909a3-df60-49e0-ad35-274b711a7385
- [x] the uploaded files: [DE_spatialScopeExamples_case1-4.zip](https://github.com/inspire-eu-validation/community/files/4586877/DE_spatialScopeExamples_case1-4.zip)

Related to the ATS description (https://github.com/inspire-eu-validation/metadata/blob/2.0/monitoring/spatial-scope.md) the results for some examples are not proper.

Could you check this and maybe adjust the testing method please?
Thanks & regards.

**Comment by danielnavarrogeo** [comment]
Dear @DeordD and @alitka 

@DeordD only English is supported currently, but we are adding support for more languages. Once implemented we will add a comment here.

@alitka thank you for sharing the results of your tests. We are going to analyze the related issues.

Regards

**Comment by danielnavarrogeo** [comment]
Dear @DeordD and @alitka,

We have added support for all the languages available in the corresponding INSPIRE registry.

@alitka this fix then solves the issue of example 7, where a german keyword is used with a gco:CharacterString element.

Regarding examples 3, 6, 9, and 12 the test considers, based on the thesaurus, that the keywords are not for 'spatial scope' but for something else. Therefore, the test result is PASSED_MANUAL because it is only mandatory in the case the metadata refers to a 'National' or 'Regional' scope, which cannot be known a priori.

https://github.com/inspire-eu-validation/metadata/blob/2.0/monitoring/spatial-scope.md

Regards

**Comment by manilly** [comment]
Dear @danielnavarrogeo,
any news or suggestions about my issue with trailing hash in thesaurusname?

![image](https://user-images.githubusercontent.com/45065613/82012730-fcd0b680-9678-11ea-9cdd-ac6880d8b327.png)

**Comment by MarcoMinghini** [comment]
Dear @manilly,
this is a GeoNetwork-specific feature and my suggestion is that this is changed in GeoNetwork rather than in the INSPIRE Validator. I am tagging @pvgenuchten to get his input here (thanks in advance!)

**Comment by danielnavarrogeo** [comment]
Dear @DeordD and @alitka,

Could you please check the support for the different languages and provide us feedback?

It is available in [staging instance](http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/).

Regards

**Comment by alitka** [comment]
Dear @danielnavarrogeo,

Thanks for the update. Based on the already provided examples, I have tested all cases again. Attached you will find my latest results after your adjustments:

_case 1_ > **german** keyword as **gmx:Anchor**
* example 2: codeListValue: Europäisch, title: Räumlicher Anwendungsbereich, date: 2030-01-01; Expected: FAILED | [Report]: PASSED, MANUAL TEST (`warning message: The date provided must be 2019-05-22`) 
* example 3: codeListValue: National, title: Räumlicher Anwendungsbereich, date: 2030-01-01, codeList: http://my.local.spatial-scope/national/; Expected: FAILED | [Report]: PASSED, MANUAL TEST (`warning message: Check manually that a spatial scope keyword is provided if the data set or data set series scope is 'National' or 'Regional'.`)

_case 2_ > **english** keyword as **gmx:Anchor**
* example 5: codeListValue: European, title: Spatial scope, date: 2030-01-01; Expected: FAILED | [Report]: PASSED, MANUAL TEST (`warning message: The date provided must be 2019-05-22`)

* example 6: codeListValue: European, title: Spatial scope, date: 2030-01-01, codeList: http://my.local.spatial-scope/national/; Expected: FAILED | [Report]: PASSED, MANUAL TEST (`warning message: Check manually that a spatial scope keyword is provided if the data set or data set series scope is 'National' or 'Regional'.`)

_case 3_ > **german** keyword as **gco:CharacterString**
* example 8: codeListValue: Europäisch, title: Räumlicher Anwendungsbereich, date: 2030-01-01; Expected: FAILED | [Report]: PASSED, MANUAL TEST (`warning message: The date provided must be 2019-05-22`)
* example 9: codeListValue: National, title: Räumlicher Anwendungsbereich, date: 2030-01-01, codeList: http://my.local.spatial-scope/national/; Expected: FAILED | [Report]: PASSED, MANUAL TEST (`warning message: Check manually that a spatial scope keyword is provided if the data set or data set series scope is 'National' or 'Regional'.`)

_case 4_ > **english** keyword as **gco:CharacterString**
* example 11: codeListValue: European, title: Spatial scope, date: 2030-01-01; Expected: FAILED | [Report]: PASSED, MANUAL TEST (`warning message: The date provided must be 2019-05-22`)
* example 12: codeListValue: European, title: Spatial scope, date: 2030-01-01, codeList: http://my.local.spatial-scope/national/; Expected: FAILED | [Report]: PASSED, MANUAL TEST (`warning message: Check manually that a spatial scope keyword is provided if the data set or data set series scope is 'National' or 'Regional'.`)

According to my, the examples 2, 5, 8 and 11 should be **`FAILED`** due wrong entry for "date", regardless of the mandatory entry, that the metadata refers to a 'National' or 'Regional' scope. And the examples 3, 6, 9 and 12 should also be **`FAILED`** due wrong entry for "date" and "codeList".

Therefore, could you check this and adjust the testing method again, please?
Thanks & regards.

**Comment by danielnavarrogeo** [comment]
Dear @alitka 

Thank you for your feedback. We have just tested examples 2, 5, 8 and 11 and they all fail correctly.

Here is an example of one of them: http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/v2/TestRuns/EID5c5c1eb1-208c-487d-8b34-0e02afe4470f.html

Regarding examples 3, 6, 9 and 12 the validator considers that the provided keywords does not belong to the spatial scope thesaurus because the codelist is wrong. So it assumes that the keywords belong to a different thesaurus, which can be any, and then the date is not tested.

Therefore, we consider that for all the metioned examples (2, 5, 8, 11, 3, 6, 9 and 12) the validator behaves properly.

Regards

**Comment by pvgenuchten** [comment]
Hi @MarcoMinghini, I've heard about the issue of adding '#' before. I've not been able to identify yet where it comes from, it's somewhere in the RDF library we're using.  From web perspective a url with or without '#' is still the same url. But I will give it another look. Thanx for the notification.

**Comment by pvgenuchten** [comment]
If you're able to review https://github.com/geonetwork/core-geonetwork/pull/4703, that would be helpfull

**Comment by danielnavarrogeo** [comment]
Dear @pvgenuchten 

Changes look fine to me. Thank you very much for your collaborative attitude in solving this issue.

I think this is a nice example of cross-project collaboration.

Regards
