### ISSUE TITLE
Opening validator fails with 502

### ISSUE THREAD

**Issue by JohannaOtt** [INSPIRE-MIF/helpdesk-validator#273]
The validator at http://inspire.ec.europa.eu/validator/ cannot be reached with this error message:
Proxy Error

The proxy server received an invalid response from an upstream server.
The proxy server could not handle the request GET /validator/.

Reason: Error reading from remote server

The staging instance is still working.

**Comment by carlospzurita** [comment]
Dear @JohannaOtt 
We are investigating what happened on the validator instance, and keep you posted with any news.
Thanks.

**Comment by carlospzurita** [comment]
Validator is running again. Thank you for your patience.

**Comment by JohannaOtt** [comment]
LGTM
