### ISSUE TITLE
md sds 3.6: Coupled Resource (various error messages)

### ISSUE THREAD

**Issue by alitka** [INSPIRE-MIF/helpdesk-validator#275]
Testing a service metadata record causes various error messages concerning the Coupled Resource
(Issue related to #259)

- [x] description of the steps to reproduce the issue
1. go to http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp and select "Conformance Class 3: 'INSPIRE Spatial Data Service baseline metadata.'" (include the test suites "Common Requirements for ISO/TC 19139:2007 based INSPIRE metadata records."
2. start the test with different URLs & 3. the error messages returned for the test "Identification > md sds 3.6: Coupled Resource" & 4. screenshot illustrating the problem

**case 1** with URL: https://gdk.gdi-de.org/gdi-de/srv/api/records/12e18fac-5107-35d1-943d-969bff50f555/formatters/xml

`The metadata record set has 1 record(s) with errors for this assertion.
XML document 'xml.xml', record '12e18fac-5107-35d1-943d-969bff50f555': The metadata record has a linkage property, but it references a resource at 'https://registry.gdi-de.org/id/de.be.csw/c08ca8b7-0a86-3256-86f7-91a5d143ad34' that cannot be accessed. An exception occured when accessing the resource. Error message: "http://registry.gdi-de.org/id/de.be.csw/c08ca8b7-0a86-3256-86f7-91a5d143ad34" (Line 1): Premature end of file.`

![grafik](https://user-images.githubusercontent.com/29542183/78898443-1bd59a80-7a74-11ea-83ee-5ebb3492b5d9.png)

**case 2** with URL: https://gdk.gdi-de.org/gdi-de/srv/api/records/A6388F0D-E484-407A-A0EB-330F5D9409D8/formatters/xml

`The metadata record set has 1 record(s) with errors for this assertion.
XML document 'xml.xml', record 'A6388F0D-E484-407A-A0EB-330F5D9409D8': The metadata record has a linkage property, but it references a resource at 'https://registry.gdi-de.org/id/de.hh/05c6e639-2d2e-4530-83fa-5a2eb9aa3a3f' that cannot be accessed. An exception occured when accessing the resource. Error message: "http://registry.gdi-de.org/id/de.hh/05c6e639-2d2e-4530-83fa-5a2eb9aa3a3f" (Line 1): White spaces are required between publicId and systemId.`

![grafik](https://user-images.githubusercontent.com/29542183/78899281-702d4a00-7a75-11ea-8611-42dbb1d34413.png)

case 3 with URL: https://gdk.gdi-de.org/gdi-de/srv/api/records/C6DE8618-DC87-4A66-831F-EB0DC1254814/formatters/xml

`The metadata record set has 1 record(s) with errors for this assertion.
XML document 'xml.xml', record 'C6DE8618-DC87-4A66-831F-EB0DC1254814': The service metadata record has an 'operatesOn' property in its service identification. The value is referenced via an xlink:href that references: 'https://registry.gdi-de.org/id/de.bund.bkg.csw/DEBKG00M00000101'. The referenced value must be a dataset or series metadata record, but it is not. Found: ''.`

![grafik](https://user-images.githubusercontent.com/29542183/78899895-5a6c5480-7a76-11ea-9941-a7450d528ff7.png)

- [x] the Test Reports (attachment to the issue)
case 1 to 3: [DE_coupledResource_case1-3.zip](https://github.com/inspire-eu-validation/community/files/4456398/DE_coupledResource_case1-3.zip)

- [x] the name of the Test that failed or better: change the Level of Detail
http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/v2/TestRuns/EID5795639a-ef2a-4582-ae3a-55e25a2514d5.html#EID44d7ded3-524e-45f7-afee-73fd6a4bccd7

The test claims different error messages concerning the response of the entry in the operatesOn-element.
**case 1:** - operatesOn entry: <srv:operatesOn xlink:href="https://registry.gdi-de.org/id/de.be.csw/c08ca8b7-0a86-3256-86f7-91a5d143ad34"/>` 
- redirect to `https://fbinter.stadt-berlin.de/fb/csw/?service=CSW&version=2.0.2&request=GetRecords&namespace=xmlns(csw=http://www.opengis.net/cat/csw/2.0.2),xmlns(gmd=http://www.isotc211.org/2005/gmd)&resultType=results&outputFormat=application/xml&outputSchema=http://www.isotc211.org/2005/gmd&startPosition=1&maxRecords=1&typeNames=csw:Record&elementSetName=full&constraintLanguage=CQL_TEXT&constraint_language_version=1.1.0&constraint=csw:ResourceIdentifier%3D%27c08ca8b7-0a86-3256-86f7-91a5d143ad34%27`
- response: dataset metadata record (hierarchyLevel = dataset)
- possible error: "wrong" codeList for hierarchyLevel/MD_ScopeCode

**case 2** - operatesOn entry: `<srv:operatesOn uuidref="9CDFCF6B-59E1-40B6-B3BC-BF1B4B2A5D22" xlink:href="https://registry.gdi-de.org/id/de.hh/05c6e639-2d2e-4530-83fa-5a2eb9aa3a3f"/>`
- redirect to `https://metaver.de/csw/partner/hh?service=CSW&version=2.0.2&request=GetRecords&resultType=results&namespace=xmlns(csw=http://www.opengis.net/cat/csw/2.0.2),xmlns(gmd=http://www.isotc211.org/2005/gmd),xmlns(ogc=http://www.opengis.net/ogc),xmlns(apiso=http://www.opengis.net/cat/csw/apiso/1.0)&outputFormat=application/xml&outputSchema=http://www.isotc211.org/2005/gmd&startPosition=1&maxRecords=1&typeNames=csw:Record&elementSetName=full&CONSTRAINTLANGUAGE=Filter&constraint_language_version=1.1.0&constraint=%3Cogc:Filter+xmlns%3Aogc%3D%22http%3A%2F%2Fwww.opengis.net%2Fogc%22%3E%3Cogc%3APropertyIsEqualTo%3E%3Cogc%3APropertyName%3Eapiso%3AResourceIdentifier%3C%2Fogc%3APropertyName%3E%3Cogc%3ALiteral%3E05c6e639-2d2e-4530-83fa-5a2eb9aa3a3f%3C%2Fogc%3ALiteral%3E%3C%2Fogc%3APropertyIsEqualTo%3E%3C%2Fogc%3AFilter%3E`
- response: dataset metadata record (hierarchyLevel = dataset)
- possible error: white spaces in filter request

**case 3** - operatesOn entry: `<srv:operatesOn uuidref="8590d4a1-5ffe-49c0-91e9-0da44bf72de7" xlink:href="https://registry.gdi-de.org/id/de.bund.bkg.csw/DEBKG00M00000101"/>`
- redirect to: http://gdk.gdi-de.org/inspire/srv/eng/csw?REQUEST=GetRecords&SERVICE=CSW&VERSION=2.0.2&OUTPUTSCHEMA=http://www.isotc211.org/2005/gmd&constraintLanguage=CQL_TEXT&constraint=ResourceIdentifier%20like%20%27https://registry.gdi-de.org/id/de.bund.bkg.csw/DEBKG00M00000101%27&constraint_language_version=1.1.0&typenames=csw:Record&resulttype=results&elementsetname=full#xpointer%28//gmd:identificationInfo[1]/gmd:MD_DataIdentification%29
- possible error: unknown

Related to the TG Requirement 3.6: metadata/2.0/req/sds/coupled-resource, all three cases contain a URI pointing to the gmd:MD_DataIdentification element of the metadata record of the provided the data set or data set series.

How can we avoid this errors? Could you check this for us, please?
Thanks & regards.

**Comment by danielnavarrogeo** [comment]
Dear @alitka 

We are analyzing this issue and we will keep you posted.

Regards

**Comment by alitka** [comment]
Dear @danielnavarrogeo 
> We are analyzing this issue and we will keep you posted.

Are there any news regarding this topic?
Thanks and best regards.

**Comment by danielnavarrogeo** [comment]
Dear @alitka 

We are developing and testing the fix.

We will let you know when available for testing.

Regards

**Comment by danielnavarrogeo** [comment]
Dear @alitka 

We have addressed this issue and it can be tested in [staging instance](http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/).

Could you please check the fix and provide us feedback?

Regards

**Comment by alitka** [comment]
Dear @danielnavarrogeo,

Sorry for my late response. I have tested all three cases again, plus some additional service records with uploading a xml-file and everything is working properly.

Thanks and best regards!

**Comment by danielnavarrogeo** [comment]
Dear @alitka 

Thank you for your feedback.

Regards
