### ISSUE TITLE
Migration to OpenJDK

### ISSUE THREAD

**Issue by DLList** [INSPIRE-MIF/helpdesk-validator#276]
Within the development of a tool for the transformation to INSPIRE data we use the ETF Validator. 
Since we switch the Java version to openJDK, the question arises whether ETF Validator is currently running with openJDK or only with Oracle Java?

**Comment by carlospzurita** [comment]
The cloud instances for the INSPIRE validator are in fact running over OpenJDK 1.8.0_66, so you should be able to perform the change without any issue.

**Comment by DLList** [comment]
Dear @carlospzurita ,
thank you for the answer.
