### ISSUE TITLE
MD 2.0 - Strange test report with 'system error' error message for all tests

### ISSUE THREAD

**Issue by MarcoMinghini** [INSPIRE-MIF/helpdesk-validator#277]
When validating some metadata (TG 2.0), I get a strange test report where all the single test assertions fail with the same error message mentioning a `System error in the Executable Test Suite`.

Attached you can find 2 metadata records, one for datasets and one for services, validated against the conformance classes _Common Requirements_ and _Conformance Class 1_.

In the former case (datasets), the error message is 

`System error in the Executable Test Suite. Please contact a system administrator. Error information:
[err:XPTY0004] Item expected, sequence found: (attribute codeListValue {"datas.... 
 (189/14)`

while in the latter case (services), the error message is

`System error in the Executable Test Suite. Please contact a system administrator. Error information:
[err:XPTY0004] Item expected, sequence found: (attribute codeListValue {"servi.... 
 (189/14)`

This is basically the same error and should be due to something very specific that is included in these metadata and is not correctly managed by the ETS. 

Note that the same happens when the same metadata are validated against MD TG 1.3 conformance classes.

[system_error_MD.zip](https://github.com/inspire-eu-validation/community/files/4461029/system_error_MD.zip)

**Comment by danielnavarrogeo** [comment]
Dear @MarcoMinghini 

Thank you for opennig this issue. We will provide fix for this issue and ask you to test it when ready.

Regards

**Comment by danielnavarrogeo** [comment]
Dear @MarcoMinghini 

This issue has been addressed and it is available in staging instance.

Could you check the implemented solution and provide us feedback?

Regards

**Comment by MarcoMinghini** [comment]
Dear @danielnavarrogeo, thanks for the fix.
I confirm that the strange error message does not happen anymore, and the two metadata attached are validated regularly (they have errors, but these are correctly reported and explained).

**Comment by danielnavarrogeo** [comment]
Thank you @MarcoMinghini for your feedback.
