### ISSUE TITLE
MD TG 2.0 - Incorrect error message on test C.18

### ISSUE THREAD

**Issue by MarcoMinghini** [INSPIRE-MIF/helpdesk-validator#278]
When validating the attached metadata record against conformance class _Common Requirements for ISO/TC 19139:2007 based INSPIRE metadata records_ (MD TG 2.0), test on Requirement C.18 _Conditions for Access and Use_ fails with the following error message:

`The metadata record set has 1 record(s) with errors for this assertion.
XML document '3.iso19139.xml', record 'ES_SDGC_BU': No resource constraint conditions is provided for this record. If "http(s)://inspire.ec.europa.eu/metadata-codelist/ConditionsApplyingToAccessAndUse/" link is provided, please check if this is pointing to"noConditionsApply" or to "conditionsUnknown".`

This error message is not correct, because the condition is provided and the metadata correctly includes  the codelist `http(s)://inspire.ec.europa.eu/metadata-codelist/ConditionsApplyingToAccessAndUse/` with value `noConditionsApply`.

The reason of the fact that the test fails is rather the wrong codelist value for the codelist `http://standards.iso.org/iso/19139/resources/gmxCodelists.xml#MD_RestrictionCode` in the element `gmd:MD_RestrictionCode`. According to Requirement C.18, the only allowed value is `otherRestrictions`, but the metadata has a value `copyright`.

If this codelist value is changed to `otherRestrictions`, the metadata correctly passes validation, which means that the test is implemented correctly but the error message is not, and should be changed.

[3.iso19139.xml.zip](https://github.com/inspire-eu-validation/community/files/4461117/3.iso19139.xml.zip)

**Comment by danielnavarrogeo** [comment]
Dear @MarcoMinghini 

Thank you for opening this issue.

We will change the error message and let you know when ready for testing.

Regards

**Comment by danielnavarrogeo** [comment]
Dear @MarcoMinghini 

The issue has been addressed and it is ready for testing in [staging instance](http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/).

Could you please check it and provide us feedback?

Regards

**Comment by MarcoMinghini** [comment]
Dear @danielnavarrogeo,
I tested the metadata and the error message is now better. To help users locate the error and change the metadata, I would suggest if possible to add the codelist value that was found in the metadata instead of the expected one, for example in this case "... must include "otherRestrictions" as CodeListValue, but it was found "copyright" ".

In other tests, the value found in the metadata is provided in the error message so I assume this can be done here as well. Thank you.

**Comment by danielnavarrogeo** [comment]
Dear @MarcoMinghini 

Thank you for your feedback. We will provide the value found in the error message and let you know when it is ready for testing.

Regards

**Comment by danielnavarrogeo** [comment]
Dear @MarcoMinghini 

We have added the found value in the error message.

Could you check it in [staging instance](http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/) and provide us feedback?

Regards

**Comment by MarcoMinghini** [comment]
I confirmed that the error message is now more comprehensive and useful for the user to fix the metadata. Thanks for changing it.

**Comment by danielnavarrogeo** [comment]
Thank you @MarcoMinghini for your feedback.

Regards
