### ISSUE TITLE
TG 2.0 batch validation in Validatior UI: unique resource identifier checked?

### ISSUE THREAD

**Issue by ghost** [INSPIRE-MIF/helpdesk-validator#279]
Hi everyone,

In [Datest UID ATS](https://github.com/inspire-eu-validation/metadata/blob/2.0/datasets-and-series/dataset-uid.md) is stated: 

> Test that every dataset or dataset series has an Unique Resource Identifier.

I have imported two exactly the same [metadata records](https://github.com/inspire-eu-validation/community/files/4475846/Dataset.UID.zip) in the UI and performed validation on production and staging instance against TG 2.0. 

The report for production instance can be found [here](http://inspire.ec.europa.eu/validator/v2/TestRuns/EIDf16b7d36-a668-4d05-953a-eafcb5300cd6.html). [Dataset UID Test](http://inspire.ec.europa.eu/validator/v2/TestRuns/EIDf16b7d36-a668-4d05-953a-eafcb5300cd6.html?lang=de#EIDd0303dc3-c189-4394-bf9e-8e67dcf638c1) is PASSED. 

Imported metadata record are downloaded from this [location](https://github.com/inspire-eu-validation/community/blob/master/examples/Dataset_metadata_2.0_example). 

Both records have following resource identifier:
http://www.my-organisation.eu/so/lu/land-use-map

Does the validator check if resource identifiers (`gco:CharacterString` and `gmx:Anchor` encoding) of bulk imported metadata records in the UI are unique?

Thanks in advance.

**Comment by danielnavarrogeo** [comment]
Dear @DeordD 

The Validator does not check the resource identifier between different files. Every file is validated independently.

Regards

**Comment by ghost** [comment]
Dear @danielnavarrogeo ,

thanks a lot for your feedback. 

My interpretation of ATS was not correct in this case.

Like you said, the validator only checks if resource identifier (http://www.my-organisation.eu/so/lu/land-use-map) is unique within the same metadata record and throws message in validator if this is not the case:
https://github.com/inspire-eu-validation/ets-repository/blob/9125ed7b3e4c5ac5eb7bd6cd489cdc28415506a2/metadata/2.0/datasets-and-series/ets-md-datasets-and-series-bsxets.xml#L175

In my opinion this issue can be closed.

Kind regards.

**Comment by ghost** [comment]
P.S:
I have just validated one metadata record with two gmd:identifier blocks with the same value in gmx:Anchor. Following message is displayed in the validator:

![grafik](https://user-images.githubusercontent.com/38787131/79243263-aef84100-7e75-11ea-9992-dba5c995996c.png)

Part of the message 
> is used by more than one metadata record as the identifier. 

is little bit misleading but in my opinion it doesn't have to be changed because it is not very likely that multiple gmd:identifier occur in the same metadata record.

**Comment by danielnavarrogeo** [comment]
Thank you very much @DeordD. We will then close the issue.

**Comment by ghost** [comment]
Hi @danielnavarrogeo ,

could you please reopen this issue becuse new findings are documented in the following [issue](https://github.com/inspire-eu-validation/community/issues/318#issuecomment-633898168).

It seems that validator checks if resource identifier is unique within multiple metadata records.

In my opinion this is a nice feature in order to really check if resource identifier is unique or not in one metadata catalogue or within several metadata files.

Thanks in advance.

**Comment by ghost** [comment]
Hi @danielnavarrogeo ,

the problem from this issue is also solved after fix in the [issue](https://github.com/inspire-eu-validation/community/issues/318#issuecomment-635951696).

![datasetUID](https://user-images.githubusercontent.com/38787131/83262175-cfc5ed00-a1bc-11ea-8a1a-71b86b63dfe1.jpg)

This issue doesn't have to be reopened. 

Kind regards.

**Comment by danielnavarrogeo** [comment]
Thank you @DeordD for your feedback.

Regards
