### ISSUE TITLE
About the etf directory

### ISSUE THREAD

**Issue by apfelnymous** [INSPIRE-MIF/helpdesk-validator#280]
The documentation says: 

> The application will start and initially create the ETF directory structure in the directory %ALLUSERSPROFILE% (default: C:\ProgramData)

But how do you change that default path ? If I change the base path: etf.dir in the config it will expect an prebuild directory there, but not generate it from scratch, any way to do that ?

**Comment by carlospzurita** [comment]
To modify the etf directory, you can create a new environment variable ETF_DIR and set to the path you would like to use as a data directory for the ETF. The webapp will handle the creation of the initial data structure using this path.

**Comment by dperezBM** [comment]
Dear all,

Since this issue had no interaction time ago, we decided to close it. Please feel free to open a new one if needed.

Thank you and best regards.
