### ISSUE TITLE
Maintenance for new release

### ISSUE THREAD

**Issue by carlospzurita** [INSPIRE-MIF/helpdesk-validator#281]
The validator instance will be down until the deployment of the new release.

**Comment by ghost** [comment]
Thanks for the information.

Production or staging?

Which ets-repository will be deployed?

Can new release be found [here](https://github.com/inspire-eu-validation/community/releases)?

Kind regards.

**Comment by MarcoMinghini** [comment]
@DeordD this will be an exceptional release of the production instance (not foreseen in our [release plan](https://github.com/inspire-eu-validation/community/tree/master/release%20strategy)) that only includes a couple of further changes we made while validating Member States metadata for the 2019 Monitoring. In other words, this is the same instance of the Validator we used for testing Member States metadata.

It will be v.2020.1.2 and yes, it will be available [here](https://github.com/inspire-eu-validation/community/releases).

**Comment by ghost** [comment]
@MarcoMinghini thanks a lot for the information und short explanation.

I asked this question becaues we are using INSPIRE CCs in our own validator and want to be in sync with INSPIRE-Validator.

Kind regards.

**Comment by jenriquesoriano** [comment]
The validator was successfully updated. 
Release v2020.1.2 is available [here.](https://github.com/inspire-eu-validation/community/releases "INSPIRE Reference Validator Releases")
It has been deployed in the Production environment at: http://inspire.ec.europa.eu/validator
