### ISSUE TITLE
Future support for Conformance Class 'XML encoding of ISO 19115/19119 metadata'

### ISSUE THREAD

**Issue by ghost** [INSPIRE-MIF/helpdesk-validator#282]
Hi all,

I would like to discuss future support of [Conformance Class 'XML encoding of ISO 19115/19119 metadata](https://github.com/inspire-eu-validation/metadata/tree/1.3/xml-encoding) (see "Basic tests" section in INSPIRE-Validator).

**Current situation**

1. TG 1.3

Validation against this conformance class was automatically executed when validating against [CCs in Metadata (TG version 1.3)](https://github.com/inspire-eu-validation/metadata/blob/1.3/xml-encoding/schema-validation.md). 

Q1: Does ATS documentation have to be updated?

2. TG 2.0

ISO 19115/19119 requirements for TG 2.0 are validated directly in Conformance Class [Common Requirements for ISO/TC 19139:2007 based INSPIRE metadata records](https://github.com/inspire-eu-validation/metadata/blob/2.0/common/xml-schema.md) without using any other dependant CCs.

Q2: Does ATS documentation have to be updated?

3. XML Validation TG 1.3 vs TG 2.0

In this moment TestAssertions expressions (XQuery script) are slightly different.

- [TG 1.3 XML-Validation](https://github.com/inspire-eu-validation/ets-repository/blob/650ded1dd21b8e9a6b5bcd20dd8f92174da746df/metadata/1.3/xml/ets-md-xml-bsxets.xml#L70)

- [TG 2.0 XML-Validation](https://github.com/inspire-eu-validation/ets-repository/blob/650ded1dd21b8e9a6b5bcd20dd8f92174da746df/metadata/2.0/common/ets-md-common-bsxets.xml#L67)

_Left side-TG 2.0_
_Right side-TG 1.3_
![grafik](https://user-images.githubusercontent.com/38787131/79473275-31fbd180-8005-11ea-9a92-975fcb93f051.png)

Q3: Are validation results for both of them the same given the same metadata records?

**Future plans**
Conformance Class 'XML encoding of ISO 19115/19119 metadata could be used in future as basic test to check ISO Requirements without checking INSPIRE requirements. 
 
Q4: Is it planned to have support for Conformance Class 'XML encoding of ISO 19115/19119 metadata after support for TG 1.3 is finished? If yes it would be really nice to have identical XQuery expression for both XML-Validations. 

P.S.
In order to avoid maintanence of two identical TestAssertions for ISO requirements this conformance class could be made dependant to TG 2.0 CCs. This would provide more transparent results in the validation report to the user.

On the other hand, several modifications were done for XML-Validation in ets-repository (HTTPS redirects problem, dead links to ISO Repository, ...). Maybe it would be good to seperate validation results for INSPIRE and ISO requirements because it is not clear [what happens with apiso.xsd maintaned by OGC](https://github.com/inspire-eu-validation/community/issues/246#issuecomment-604904018). 

Kind regards.

**Comment by danielnavarrogeo** [comment]
Dear @DeordD ,

This is an interesting discussion. There is a slightly different approach to schema validation for metadata 1.3 and 2.0.

In both cases, the schema validation is done against fixed schemas (https://inspire.ec.europa.eu/draft-schemas/inspire-md-schemas-temp/apiso-inspire/apiso-inspire.xsd and https://inspire.ec.europa.eu/draft-schemas/inspire-md-schemas-temp/iso_19139_20060504/iso_19139_20060504_wrapper.xsd) If any of them pass, the validation is successful.

In 2.0 it also validates against http://www.isotc211.org/2005/gmd/gmd.xsd and http://schemas.opengis.net/iso/19139/20070417/gmd/gmd.xsd

Additionally, only in 1.3 and if the previous schema validation fails, it is done against defined in the schemaLocation attribute.

The reason for that is the TG Requirement C.1 from MD TG 2.0 which stands that the metadata shall be valid against at least one of a set of predefined schemas.

So, answering to your questions Q1 and Q2, we will review the ATS to check if any change is needed.

The answer to Q3 I mentioned before, it depends. If it validates against one of the fixed schemas, then the result is the same. Otherwise, the result might differ.

Finally, regarding Q4, as you correctly mention, 'XML encoding of ISO 19115/19119' is used in metadata 1.3. So the support will finish with it. In metadata 2.0 the schema validation is done as part of Conformance Class Common Requirements.

I hope this answer your questions.

Regards

**Comment by ghost** [comment]
Hi @danielnavarrogeo ,

thanks a lot for very detailed answers. One aspect is not completely clear.

> Finally, regarding Q4, as you correctly mention, 'XML encoding of ISO 19115/19119' is used in metadata 1.3. So the support will finish with it. In metadata 2.0 the schema validation is done as part of Conformance Class Common Requirements.

If I understood well there is no intention to provide standalone ISO schema validation in basic tests and make it dependant to TG 2.0 conformance classes? 

This approach would mean that validation for TG 2.0 **is not done** as part of Conformance Class Common Requirements, but using the standalone schema validation in basic tests. (same approach like in TG 1.3)

**Comment by ghost** [comment]
P.S.
Some benefits of this approach are:

- provide more transparent results in the validation report to the user
        - additional test module in the report clarifies the importance of schema valid metadata records
        - after report is opened it is clear that schema validation failed (no need to filter)
- less confusion for testers because of FAILED result against TG 2.0 because schema validation is currently changed very often
        - use knows that native INSPIRE requirements are OK (validation against official apiso.xsd maintained from OGC is currently not possible)
- provide possibility to test only ISO requirements without waiting the results of TG 2.0 validation
        - important for custom metadata profiles which are using this validation as dependant test to check ISO req.
        - easier evaluation using INSPIRE-Validator API in order to present the results of the validation against TG 2.0 (no need to parse or query XML)
- ensure coherent approach for checking application schemas and encoding rules in the validator
      - schemas for all conformance classes except schema validation for TG 2.0 are executed as dependant tests (GML Encoding, Application Schemas for Annex I, ...)

**Comment by danielnavarrogeo** [comment]
Dear @DeordD 

Currently, there is no plan to separate the schema validation performed in TG 2.0 Common Requirements to a different Conformance Class.

Let us discuss internally about your proposal. It may be interesting to do so.

Regards

**Comment by danielnavarrogeo** [comment]
Dear @DeordD 

We have discussed your proposal and we do not think any change is needed.

The ATS and ETS for MD 2.0 follow the structure and content of the [TG MD](https://inspire.ec.europa.eu/sites/default/files/documents/metadata/inspire-tg-metadata-iso19139-2.0.1.pdf). 

As you can see in the TG, the schema validation is the first requirement in the 'Common Requirements' Conformance Class, which has 22 requirements in total.

Therefore, we consider that the schema validation shall belong to the 'Common Requirements' CC and it shall not be separated in a different one, which may produce even more confusion.

Anyway, thank you for your proposal and we will leave this discussion open in case anyone else wants to participate.

Regards

**Comment by ghost** [comment]
Dear @danielnavarrogeo ,

thanks a lot for taking the proposal in consideration. 

You have just said that ATS for 2.0 follows the structure of 2.0.1
> The ATS and ETS for MD 2.0 follow the structure and content of the TG MD.

If I take a look in the validator TG 2.0 is referenced:
![grafik](https://user-images.githubusercontent.com/38787131/79982764-1a11cb00-84a7-11ea-9f15-1074e81576cb.png)

I find it little bit confusing. Can you please clarify this?

Regards.

**Comment by danielnavarrogeo** [comment]
Dear @DeordD 

The Conformance Classes 1 and 2 refer to metadata for data set and data set series. While CC 3, 4, 5, 6 and 7 are related with metadata for services.

Then, Common Requirements are a set of requirements that apply to both metadata for data set and data set series and metadata for services. The first requirement of this CC is the schema validation.

You might find helpful the following diagram from the TG which shows the dependencies between the conformance classes.

![imagen](https://user-images.githubusercontent.com/45062523/80006800-acc16280-84c5-11ea-81f3-8d5256b9c6ea.png)

Regards

**Comment by ghost** [comment]
Thanks @danielnavarrogeo ,

I am aware of the concept to group the requirements which are the same for dataset/series and services in one chapter. This is very nice approach.

I was only confused that ATS for MD 2.0 doesn't point to TG 2.0 but in contrary to TG 2.0.1. (two different versions)

I assume this is ok, because the requirements in two version are almost the same. Only difference beetwen them should be like given here:
https://inspire.ec.europa.eu/sites/default/files/inspire-tg-metadata-iso19139-2.0.1-release-notes.txt 

Thanks a lot for answering my questions!

Regards
