### ISSUE TITLE
Validator versions and auto-update

### ISSUE THREAD

**Issue by hwbllmnn** [INSPIRE-MIF/helpdesk-validator#284]
Hi all,

we're trying to re-package version 1.0.8 of the INSPIRE validator into a docker image and I'm running into a couple of issues. This is basically how we're doing it:

* we start with a bare tomcat image
* we unpack the `etf-webapp.war` into tomcat's webapps folder, downloaded and unpacked from https://github.com/inspire-eu-validation/community/releases/download/v1.0.8/etf-release-v1.0.8.zip
* we unpack the scripts into the ETF projects folder, downloaded and unpacked from https://github.com/inspire-eu-validation/community/releases/download/v1.0.8/ets-repository-v1.0.8.zip

This leads to a projects folder with just `ets-repository-1.0.8` as contents.

After a while the validator downloads newer versions of the scripts, leading to the following contents:

`etf-2020-04-21.0  etf-2020-04-21.0.zip	ets-repository-1.0.8`

This seems to lead to conflicts and we end up with an unusable ETF instance. After the update only the OGC WFS 2.0 test suite is available.

Is there a way to prevent this update from happening? We want to be able to pin the INSPIRE validator to a specific version and make controlled updates as they become available.

Thanks, Andreas

**Comment by carlospzurita** [comment]
Dear @hwbllmnn 

We would advise you to use the Dockerfile and resources contained in the release for the release 1.0.8, and use it as a baseline for your modifications. In the Dockerfile you can find a way to download an specific version of the ETS repository, and even substitute the repository for your own fork.

Kind regards,

Carlos.

**Comment by hwbllmnn** [comment]
Hi Carlos,

looks like going with this there are no updates downloaded so far, so I'm going to go with your solution. Thanks for getting back to me so quickly!

Best regards, Andreas
