### ISSUE TITLE
README v2020.1.2 15/04/2020 holds non-working instructions

### ISSUE THREAD

**Issue by arbakker** [INSPIRE-MIF/helpdesk-validator#286]
README in `inspire-validator-2020.1.2.zip`  in  release [v2020.1.2 15/04/2020](https://github.com/inspire-eu-validation/community/releases/tag/v2020.1.2) has instructions that do not work:

```
docker run --name etf -d -p 80:8080 -v ~/etf:/etf iide/etf-webapp:latest
```
[iide/etf-webapp](https://hub.docker.com/r/iide/etf-webapp/) does not exist on Docker hub. Is there another way of acquiring the iide/etf-webapp image?

**Comment by carlospzurita** [comment]
Dear @arbakker 
This information inside the .zip file was outdated and have been corrected on the release.
The official docker image for the INSPIRE validator is the one listed at the instructions on the [release page](https://github.com/inspire-eu-validation/community/releases/tag/v2020.1.2)
`
docker run --name inspire-validator -d -p 8080:8080 -v ~/etf:/etf docker.pkg.github.com/inspire-eu-validation/community/inspire-validator:2020.1.2`

Thank you for the heads up.
