### ISSUE TITLE
Support for View services in downloadable set of executable tests

### ISSUE THREAD

**Issue by MichaelOstling** [INSPIRE-MIF/helpdesk-validator#288]
I have an issue when running the ETF-validator locally, maybe  this is already documented somewhere but I can't find any info on it

In the central site
http://inspire.ec.europa.eu/validator/about/

It exists Executable tests for Metadata, WMS, WFS and ATOM

But when you setup the validator on your own site (installing in local Tomcat). 
The executable tests are at
https://github.com/inspire-eu-validation/ets-repository/archive/master.zip

And are described at
https://github.com/inspire-eu-validation/community/wiki

This set of tests do not include tests for View-services
Are these stored at other site ?

Anyone knows more on this ?

Kind regards
Michael  Östling

**Comment by carlospzurita** [comment]
Dear @MichaelOstling 

Can you tell us what build of the validator are you using? The preferred option is using the Docker deployment as we have listed on the [latest release](https://github.com/inspire-eu-validation/community/releases/tag/v2020.1.2) under the deployment instructions. Anyway, if you want an alternative deployment, you can use the inspire-validator-2020.1.2.zip file under the assets of said release, where you can find the .war file to use it with Tomcat.

**Comment by MichaelOstling** [comment]
Hi, 

I have deployed in Tomcat on a windows machine.
When reading the documentation it does not say Docker is the preferreed way. 
It just say its the easiest way.
Do mean we should avoid deploying directly in Tomcat?

I see now that on the actual Inspire production site 
http://inspire.ec.europa.eu/validator/about/
It has a link to download software that points to 
http://etf-validator.net/ 
which in turn have a link to GitRepo 
https://github.com/etf-validator/etf-webapp/releases/tag/2.0.0

I think it would be better if that link pointed to
https://github.com/inspire-eu-validation/community/releases/tag/v2020.1.2

I  not so obvious  there where two different repositories. But now I got it !

I dont have much experience in docker so I prefer running in Tomcat for a while.

Let me test with updated ETS.

/Michael

**Comment by MichaelOstling** [comment]
I have installed using the updated war and new tests:; now I get the WMS tests available.

But I get some issues showing 
![image](https://user-images.githubusercontent.com/6397818/80222032-7e1ec580-8646-11ea-825e-4bed3558f3c7.png)

I only validate a single metadata record.
In logfiles I then get 

```
2020-04-24 16:09:24.542 [http-nio-8080-exec-3] INFO  o.t.TemplateEngine - [THYMELEAF] TEMPLATE ENGINE INITIALIZED
2020-04-24 16:10:00.268 [http-nio-8080-exec-6] ERROR d.i.e.w.d.ApiError - EXID-1587737400264: An exception occurred while trying to invoke "http://localhost:8080/etf-webapp/v2/TestRuns"
org.springframework.web.util.NestedServletException: Handler dispatch failed; nested exception is de.interactive_instruments.etf.webapp.controller.LocalizableApiError
```

From previous support issues I have seen this is because of lacking system resources.
Java in Tomcat have though 8GB assigned.

The issue in localized API. Can that be the problem ?

I also see that folder http_uploads are deleted when I start tomcat so I have to manually add that to avoid errors.

When I check the contents of 
http://localhost:8080/etf-webapp/v2/TestRuns
It has 0 records.

**Comment by carlospzurita** [comment]
Dear @MichaelOstling 

Do you have enough disk space free to use by the ETF filesystem? You can check it on http://localhost:8080/etf-webap/v2/status, under the `freeSpace` section. You should give it about 10GB of space, for the validator to run without problems.

About the links to the software download, we will review them and update them accordingly.

**Comment by MichaelOstling** [comment]
Thanks, I thought 5 GB was needed for diskspace. 
I will also in parallell check the docker-package

**Comment by MarcoMinghini** [comment]
Dear @MichaelOstling, 

> In the central site
> http://inspire.ec.europa.eu/validator/about/
>
> It exists Executable tests for Metadata, WMS, WFS and ATOM

Thanks for noticing that the information was outdated. We updated the wiki page https://github.com/inspire-eu-validation/community/wiki with the current list of ATS and ETS available.

We will shortly update also the page http://inspire.ec.europa.eu/validator/about.

**Comment by MarcoMinghini** [comment]
Tha page http://inspire.ec.europa.eu/validator/about has been also updated.

**Comment by danielnavarrogeo** [comment]
Thank you @MarcoMinghini for the updates.

Regards

**Comment by danielnavarrogeo** [comment]
We will update also the link in the validator of the 'help' button.

**Comment by carlospzurita** [comment]
Help link modified in [staging instance](http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/) pointing to the wiki of the community space.

**Comment by danielnavarrogeo** [comment]
Dear all,

The original topic of this issue has been already discussed.

We add the label 'ready for testing' because of the link that has been updated. This change will be included in the next release.

Regards
