### ISSUE TITLE
Error possibly related to relocation of ISO codelist

### ISSUE THREAD

**Issue by enricoboldrini** [INSPIRE-MIF/helpdesk-validator#291]
Hello,

I'm validating a metadata document that previously worked fine: https://www.seadatanet.org/content/download/4534/file/CDI_ISO19139_full_example_12.2.0.xml

The problem is on the metadata for interoperability conformance class, in particular md-iop.a.5 and md-iop.a.6. Error given:

System error in the Executable Test Suite. Please contact a system administrator. Error information:
[err:FODC0002] "https://standards.iso.org/ittf/PubliclyAvailableStandards/ISO_19139_Schemas/resources/codelist/ML_gmxCodelists.xml" (Line 1): Premature end of file. 
 (522/29)

It seems an online codelist from ISO is missing. Maybe it will be sufficient to update the reference in the test to: https://www.isotc211.org/2005/resources/Codelist/gmxCodelists.xml

Thank you,
Enrico

**Comment by danielnavarrogeo** [comment]
Dear @enricoboldrini 

The reason for this error is that ISO schemas have been moved. You can see related issues #245 and #246.

Please note that MD TG 1.3 is not supported anymore. Therefore, this issue will not be addressed.

We encourage you to migrate from TG 1.3 to TG 2.0.

Regards

**Comment by enricoboldrini** [comment]
Dear @danielnavarrogeo,

actually we are already using MD TG 2.0. We are using the CSW2 AP ISO XML schema, that is the first of the three options listed in TG Requirement C.1 (document version 2.0.1, page 7). (OGC version 2006-05-04 of the gmd namespace).
I think it will suffice to update the schema URLs inside the two tests because of ISO schema relocation. The issue is limited only to two tests of the metadata for interoperability conformance class:
1) character encoding (md-iop.a.5)
2) spatial representation type (md-iop.a.6)
All the other pass fine.

Thank you in advance for the fix or for any other info,
Enrico

**Comment by danielnavarrogeo** [comment]
Dear @enricoboldrini 

md-io.a.5 and md-iop.a.6 belongs to Conformance Class "Metadata for interoperability" which is MD TG 1.3.

If you are using already a metadata 2.0 you should validate against Conformance Classes for MD TG 2.0. 

![imagen](https://user-images.githubusercontent.com/45062523/80703150-89f50680-8ae2-11ea-8dbe-a11ed8869d36.png)

Regards

**Comment by danielnavarrogeo** [comment]
Thanks to you @enricoboldrini
