### ISSUE TITLE
DS Protected Sites: Can EPSG:25832 be used to pass rs.a.1 requirement?

### ISSUE THREAD

**Issue by ghost** [INSPIRE-MIF/helpdesk-validator#294]
One of our data providers is currently using http://www.opengis.net/def/crs/EPSG/0/25832 as standard spatial reference system (SRS) for providing interoperable data sets when calling WFS 2.0 GetFeature request. Several other SRS (e.g. EPSG:4258) are also supported but they have to be explicitly defined in the request using srsName parameter.

Validation against [following](http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/#start-tests?ids=EID4c53a8c7-7cac-4531-982b-d03eb48ffa77,EID7831c8b4-f666-4534-838a-137b30bfecbe,EIDb529e8fa-b9f8-4758-acea-1d2af744599f,EID828410c1-53f2-4683-bded-481ad9d4d3e9) CCs leads to following error message:

> A spatial geometry uses an unexpected coordinate reference system 'http://www.opengis.net/def/crs/EPSG/0/25832'. Please refer to table 2 of the data specification for the list of expected coordinate reference systems.

Our provider points out that in INSPIRE_DataSpecification_PS_v3.2.pdf S. 26 and IR Requirement Annex II Section 1.3 is stated that "Plane coordinates using the ETRS89 Transverse Mercator coordinate reference system" is supported as basic spatial reference system.

Definition of EPSG:25832:
https://spatialreference.org/ref/epsg/etrs89-utm-zone-32n/ogcwkt/

Q1: Is EPSG 25832 allowed as SRS for DS Protected Sites?

**Comment by danielnavarrogeo** [comment]
Dear @DeordD 

We will analyze it and keep you posted.

Regards

**Comment by danielnavarrogeo** [comment]
Dear @DeordD 

EPSG:25832 is not allowed.

You can see the valid SRS's in [TG DS Template ](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&ved=2ahUKEwjNj-me14_pAhWSAGMBHaSIDMgQFjAAegQIARAB&url=https%3A%2F%2Finspire.ec.europa.eu%2Ffile%2F1390%2Fdownload%3Ftoken%3Db3BlD8K2&usg=AOvVaw3vexhmHskK5Y2RIiDRtHrM) table 2 "http URIs for the default coordinate reference systems".

Regards

**Comment by carlospzurita** [comment]
Dear @DeordD 

We are cleaning up old issues on the helpdesk. Were you able to check the response for the valids SRS?

**Comment by ghost** [comment]
@carlospzurita Our data provider didn't have follow-up questions on this. This issue can be closed.

**Comment by heidivanparys** [comment]
EPSG:25832 is indeed not in the list of CRS's in the TG DS Template, but it can definitely be argued that EPSG:25832 fulfills the requirements of the implementing rules. See https://github.com/INSPIRE-MIF/helpdesk-registry/issues/80 for more information.
