### ISSUE TITLE
Test "Request and check externalServiceMetadata" in Conformance Class: Download Service - Pre-defined WFS

### ISSUE THREAD

**Issue by laers** [INSPIRE-MIF/helpdesk-validator#295]
I ran the ETS "Conformance Class: Download Service - Pre-defined WFS" for my service-endpoint =http://services.kortforsyningen.dk/af_inspire?SERVICE=WFS&REQUEST=GetCapabilities&VERSION=2.0.0

The resultat is two fails - the first is related to Capabilities and Service Metadata. The test uses the MetadataUrl from the ExtendedCapabilities to request the ServiceMetadata and it says that **no xsi:schemaLocation attribute exist in root element**. 

I can not recognize that service metadata does not have the xsi:schemaLocation attribute. Here is the link to the service metadata and as far as I can see there is the attribute in the header:
https://geodata-info.dk/srv/dan/csw?service=CSW&version=2.0.2&request=GetRecordById&id=10de3681-76cc-4148-8d07-e5d3b45e02bc&outputschema=http://www.isotc211.org/2005/gmd&elementsetname=full&resulttype=results

Attached is the test report.
[Test run on 09_12 - 30.04.2020 with test suite Conformance Class_ Download Service - Pre-defined WFS.html.zip](https://github.com/inspire-eu-validation/community/files/4557063/Test.run.on.09_12.-.30.04.2020.with.test.suite.Conformance.Class_.Download.Service.-.Pre-defined.WFS.html.zip)

**Comment by danielnavarrogeo** [comment]
Dear @laers 

We will analyze it and we will keep you posted.

Regards

**Comment by danielnavarrogeo** [comment]
Dear @laers 

We have addressed this issue and it can be tested in [staging instance](http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/).

Could you please check the fix and provide us feedback?

Regards

**Comment by carlospzurita** [comment]
Dear @laers 

Did you have the opportunity to test the solution published in the [staging instance](http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/) ?

**Comment by carlospzurita** [comment]
Dear @laers 

Were you able to check the solution deployed for this issue?

**Comment by carlospzurita** [comment]
We are marking this issue as solved and deploying it on the production instance
