### ISSUE TITLE
nilReason doesn't accept https URI

### ISSUE THREAD

**Issue by kkoistinen** [INSPIRE-MIF/helpdesk-validator#299]
Dear Validator team,

Link to validation report:

https://inspire.ec.europa.eu/validator/v2/TestRuns/EIDfcacf3a1-0281-4dc6-911e-4af0c3ba62a2.html

Validated GML file:

[EF_EnvironmentalMonitoringFacilities_FIWDA_GW1_GW1_2010-15_3035.zip](https://github.com/inspire-eu-validation/community/files/4573920/EF_EnvironmentalMonitoringFacilities_FIWDA_GW1_GW1_2010-15_3035.zip)

In this example we try to validate a GML file from EF theme. Validator gives error on nilReason URI. We have https URI in our GML but validator doesn't accept it. When nilReason URIs are changed to http URIs it passes the validation.

Is it a validator bug that https URIs as nilReason are not accepted at the moment?

**Comment by danielnavarrogeo** [comment]
Dear @kkoistinen 

We will analyze it and keep you posted.

Regards

**Comment by carlospzurita** [comment]
Dear @kkoistinen 

As discussed on [this comment](https://github.com/inspire-eu-validation/community/issues/319#issuecomment-635220388) on issue #319 , references to the INSPIRE registry should be made using HTTP URI. In this case, the service that you posted fails correctly the validation.

Kind regards.

**Comment by kkoistinen** [comment]
Ok, thanks! I will share this info to our data providers.
