### ISSUE TITLE
Separated Conformance Classes groups for Metadata validation

### ISSUE THREAD

**Issue by carlospzurita** [INSPIRE-MIF/helpdesk-validator#3]
It is proposed to separate the Conformance Classes of "Data Sets and Series" from the "Spatial Data Services" in the validator, with the Common Requirements appearing in both of them. Below is a mockup of the proposal

![imagen](https://user-images.githubusercontent.com/10537778/47714699-e4877b00-dc3d-11e8-8763-5f3cb75112f9.png)

We tried to create two separate tags for each category, but when referencing both of them on the Common Requirements, it would concatenate them and create a new category (as shown below)

![imagen](https://user-images.githubusercontent.com/10537778/47714989-b0608a00-dc3e-11e8-817b-13480824abec.png)
![imagen](https://user-images.githubusercontent.com/10537778/47714994-b35b7a80-dc3e-11e8-9ca6-d7aa49a512bf.png)

The other Conformance Classes are shown just fine.

We propose to change this behaviour on the validator codebase.

**Comment by dperezBM** [comment]
This enhancement is applied with the new INSPIRE-Validator interface.
