### ISSUE TITLE
Valid certificate not found for the resource

### ISSUE THREAD

**Issue by fabiovin** [INSPIRE-MIF/helpdesk-validator#302]
Trying to validate some services (WMS and ATOM) I receive the following error message:

![2020-05-07 (1)](https://user-images.githubusercontent.com/46569952/81389709-8aad1e80-911a-11ea-82b9-a77f31217ef5.png)

The tested services are:
WMS: https://wms.mapama.gob.es/sig/agua/PHC/MasasAguaSub2021/wms.aspx?request=getcapabilities
ATOM: https://www.mapama.gob.es/ide/inspire/atom/downloadservice.xml

Could you please verify?

Thanks

**Comment by danielnavarrogeo** [comment]
Dear @fabiovin 

Thank you for openning this issue. We will analyze it.

Regards
