### ISSUE TITLE
Pre-defined WFS test - use of prefixes in xpath expressions

### ISSUE THREAD

**Issue by VeronikaKusova** [INSPIRE-MIF/helpdesk-validator#304]
I ran ETS "**Conformance Class: Download Service - Pre-defined WFS**" for our service: http://services.cuzk.cz/wfs/inspire-AU-wfs.asp?service=WFS&request=getCapabilities. 

The Capabilities test module fails with the error on **Provide Default Language**. There is a problem in the test assertions “**Abstract from previous response equals Abstract in this response**” and “**Title from previous response equals Title in this response**”. Both of them use prefixes in their xpath expressions (see the picture below). But in our capabilities there is “http://www.opengis.net/wfs/2.0” as a default namespace, therefore prefix "wfs" is not used. So, this xpath doesn’t work, although I think our capabilities are correct from this point of view.
![github_wfs_error](https://user-images.githubusercontent.com/33151159/81545451-318ef600-9379-11ea-8105-cd95665c0e94.png)

May be a better way to define these xpaths is something like this: `/*:WFS_Capabilities[namespace-uri()='http://www.opengis.net/wfs/2.0']/*:ServiceIdentification[namespace-uri()='http://www.opengis.net/ows/1.1']/*:Abstract[namespace-uri()='http://www.opengis.net/ows/1.1']`

Test report: http://inspire.ec.europa.eu/validator/v2/TestRuns/EIDfa1ea1db-9048-45d2-baa3-06fa4ba75d43.html#EID02873f79-0172-1000-7f51-1bc4e1442f29
(Attached test report: 
[Test run on 08_58 - 11.05.2020 with test suite Conformance Class_ Download Service - Pre-defined WFS.html.zip](https://github.com/inspire-eu-validation/community/files/4608714/Test.run.on.08_58.-.11.05.2020.with.test.suite.Conformance.Class_.Download.Service.-.Pre-defined.WFS.html.zip))

Thank you.
Veronika

**Comment by danielnavarrogeo** [comment]
Dear @VeronikaKusova 

We will analyze the issue and keep you posted.

Regards

**Comment by josemasensio** [comment]
Dear @VeronikaKusova,

We noticed that the service has changed. 
Please, could you provide us with the service again? 
If you prefer, you can provide us the service as a file and we will deploy this on our local environment.

Thank you and best regards.

**Comment by VeronikaKusova** [comment]
Dear @josemasensio,
I am sorry for that change. I had wanted to keep you posted about it but I forgot. But I saved former GetCapabilities response: [capabilities_AU_old.zip](https://github.com/inspire-eu-validation/community/files/4666701/capabilities_AU_old.zip)

As I mentioned in the last comment in #164, we provide other services with the same issues. So wfs prefix is also not used in their capabilities:
http://services.cuzk.cz/wfs/inspire-CP-wfs.asp?service=WFS&request=getCapabilities
http://services.cuzk.cz/wfs/inspire-BU-wfs.asp?service=WFS&request=getCapabilities

But for these services, the problem from #164 is not solved - there is a comment on the first position in capabilities, so at first they fail with an error on Analyze WFS Capabilities.

What do you mean by provide the service as a file?

Sorry for the inconvenience and best regards.

**Comment by josemasensio** [comment]
Dear @VeronikaKusova,

Thank you for your response. We will continue working on this issue and on issue #164. By providing the service as a file I was referring to capabilities_AU_old.zip file, apologies for my bad explanation. 

Thank you and best regards.

**Comment by danielnavarrogeo** [comment]
Dear @VeronikaKusova 

A fix has been developed and it is ready for testing in [staging instance](http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/).

Could you please check it and provide us feedback?

Regards

**Comment by VeronikaKusova** [comment]
Dear @danielnavarrogeo and @josemasensio,

could you please provide me the ETS for Pre-defined WFS, which is in the staging instance? It would be easier and faster for me to test it using SOAPUI. Otherwise I would have to change some service. But if it is not possible, I will change some service. 

Thank you and regards.

**Comment by VeronikaKusova** [comment]
Dear all,
thank you. I have tested it and it seems it works properly. 

Veronika
