### ISSUE TITLE
New document on the helpdesk management workflow of the INSPIRE Reference Validator

### ISSUE THREAD

**Issue by MarcoMinghini** [INSPIRE-MIF/helpdesk-validator#305]
Dear all,
this is to inform you that we have just published a 'Helpdesk management workflow' document: https://github.com/inspire-eu-validation/community/tree/master/helpdesk%20management

The purpose of this document is to illustrate and make it as clear as possible how the [helpdesk ](https://github.com/inspire-eu-validation/community/issues)for the INSPIRE Reference Validator is organized and what is the workflow we use to manage and process each issue opened, including what are the tasks of the INSPIRE Validation team and what are the tasks expected from the users.

Also, the document describes the GitHub artifacts we are using within this workflow: [labels](https://github.com/inspire-eu-validation/community/labels), [milestones ](https://github.com/inspire-eu-validation/community/milestones)and the [project board](https://github.com/inspire-eu-validation/community/projects/1).

We hope this document is useful to the INSPIRE validation community, and we are open for any feedback and suggestion.

**Comment by ghost** [comment]
Dear @MarcoMinghini ,

very transparent explanation of helpdesk management workflow! Real world workflow and this document are in most cases the same.

I hope this will help the non-GitHub INSPIRE community to understand how GitHub-based Helpdesks work and enable easier participation and communication. 

If still didn't happen one could post it to INSPIRE Community Forum.
