### ISSUE TITLE
gmi:acquisitionInformation

### ISSUE THREAD

**Issue by bernd61** [INSPIRE-MIF/helpdesk-validator#306]
Hi,
I want to allow catalogues to search for the instrument and thought I'll add this (acquisition information from ISO 19136:2005):

_<gmd:MD_Metadata xmlns:gmi="http://www.isotc211.org/2005/gmi">
 <gmi:acquisitionInformation objectType="gmi:MI_AcquisitionInformation">
  <gmi:platform objectType="gmi:MI_Platform">
   <gmi:identifier gmd:code="ENV" gmd:codeSpace="http://www.esa.int/" objectType="gmd:RS_Identifier"/>
   <gmi:description gco:characterString="My satellite"/>
   <gmi:instrument objectType="gmi:MI_Instrument">
    <gmi:identifier gmd:code="My instrument" gmd:codeSpace="http://www.esa.int/" objectType="gmd:RS_Identifier"/>
   </gmi:instrument>
  </gmi:platform>
 </gmi:acquisitionInformation>_

But the validator complains in "Common Requirements for ISO/TC 19139:2007" when selecting the baseline metadata test.
What's wrong or is there another way to add the instrument or platform into the metadata ?

**Comment by danielnavarrogeo** [comment]
Dear @bernd61 

We will analyze the issue and keep you posted.

Regards

**Comment by danielnavarrogeo** [comment]
Dear @bernd61 

Could you please share with us the metadata you are using for validation?

Regards

**Comment by bernd61** [comment]
Dear @danielnavarrogeo 
here is the metadata.
[FDR_dataset_V0.9.xml.zip](https://github.com/inspire-eu-validation/community/files/4668631/FDR_dataset_V0.9.xml.zip)

Regards, Bernd

**Comment by fabiovin** [comment]
Dear @bernd61,
I had a look at your metadata and the error reported by validator is correct because you cannot use the _gmi:acquisitionInformation_ element under the _gmd:MD_Metadata_ root.

The _gmi:acquisitionInformation_ element requires the use of the _gmi:MI_Metadata_ root.
This root is used by the new version of the ISO 19115 standard but it is out of scope for the TG 2.0.

Regards,
Fabio

**Comment by bernd61** [comment]
Dear Fabio,

thank you!
So does this mean MI_Metadata is currently not compliant at all with INSPIRE?
but may be perhaps in the future?

Regards,
Bernd
