### ISSUE TITLE
EPSG codes in Azores

### ISSUE THREAD

**Issue by MartaMedeiros** [INSPIRE-MIF/helpdesk-validator#307]
Hello, 
In the archipelago of the azores (atlantic islands) we use the EPSG: 5014, 5015 and 5013 but are not currently being accepted by the validator. Portugal in 2017 reported the situation to the EC and, apparently the situation was resolved. You can see the discussion at the INSPIRE Community Forum at the following link: 
https://inspire.ec.europa.eu/forum/discussion/view/92458/crs-in-atlantic-islands-eg-azores-and-madeira
However, validations of GMLfiles with these EPSG are giving error in the conformance class: Reference systems, general requirements. Can the EPSG codes: 5014, 5015 and 5013 be included in a next version of the validator?

Regards

**Comment by danielnavarrogeo** [comment]
Dear @MartaMedeiros 

We will analyze the issue and keep you posted.

Regards

**Comment by danielnavarrogeo** [comment]
Dear @MartaMedeiros, 

As specified in the [issue template](https://github.com/inspire-eu-validation/community/issues/new?template=problem.md), could you please, at least: identify the test your comment refers to, attach a test report, and send us the GML file you are validating? We need this information to reproduce the issue.

We have not seen, in the link you provided, a specific reference to the decision taken by the MIG-T. Do you know in which meeting it was decided or a link pointing to the minutes of the meeting?

Regards

**Comment by MartaMedeiros** [comment]
Dear all

Thank you for your feedback.

This is the link of the test report:
https://inspire.ec.europa.eu/validator/v2/TestRuns/EID4a586ff5-8d3f-4ccb-9b85-89d8e96c195b.html

The GML file, with the EPSG code 5013, is also attached.
[inspire_el_5013.zip](https://github.com/inspire-eu-validation/community/files/4667511/inspire_el_5013.zip

I think it makes sense that the mentioned codes (5015, 5014, 5013) are accepted, because, according to the data specifications on the Coordinate Reference Systems it is said: “For the three-dimensional and two-dimensional coordinate reference systems and the horizontal component of compound coordinate reference systems used for making available the INSPIRE spatial data sets available, the datum shall be the datum of the European Terrestrial Reference System 1989 (ETRS89) in areas within its geographical scope, **or the datum of the International Terrestrial Reference System (ITRS) or other geodetic coordinate reference systems compliant with ITRS in areas that are outside the geographical scope of ETRS89.”**

I don´t know in which meeting this was talked about, it was some years ago but I can try to find out.

Regards

Marta

**Comment by carlospzurita** [comment]
Dear @MartaMedeiros 

We are advancing with this issue and include the EPSG codes in the allowed list for the ETS. We will get back to you whenever this is deployed on the staging instance.

Best.

**Comment by carlospzurita** [comment]
We have published a fix on the [staging instance](staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/) to include this EPSG codes. Please let us know if everything is in order.

**Comment by MartaMedeiros** [comment]
Yes, everything is in order 👍 
Thank you all
