### ISSUE TITLE
md dataset-and-series 1.4: http://inspire.ec.europa.eu/theme redirected to HTTPS?

### ISSUE THREAD

**Issue by ghost** [INSPIRE-MIF/helpdesk-validator#309]
Hi,

we are using v2020.1.2 branch in our environment to check metadata requirements. The test "md dataset-and-series 1.4: INSPIRE Theme Keyword" fails because it is stated that http://inspire.ec.europa.eu/theme cannot be accessed:
![grafik](https://user-images.githubusercontent.com/38787131/81949071-b17bc100-9602-11ea-9336-502eac1bc001.png)

It seems that resource has been redirected to https. 

The same test passes in INSPIRE Validator production instance (resources cached?).

Any advice what could be the problem here?

Thanks in advance.

**Comment by danielnavarrogeo** [comment]
The same applies here https://github.com/INSPIRE-MIF/helpdesk-validator/issues/311#issuecomment-629077729

**Comment by carlospzurita** [comment]
Check https://github.com/INSPIRE-MIF/helpdesk-validator/issues/311#issuecomment-630058599 for more information on this issue and deployment options.

**Comment by DeordD** [comment]
See #311 (comment).

**Comment by ghost** [comment]
See https://github.com/INSPIRE-MIF/helpdesk-validator/issues/311#issuecomment-634575614.

**Comment by dperezBM** [comment]
This issue continues its discussion in [issue 311](https://github.com/INSPIRE-MIF/helpdesk-validator/issues/311).
