### ISSUE TITLE
md dataset-and-series 1.10: http://inspire.ec.europa.eu/schemas/common/1.0/enums/enum_bul.xsd redirected to HTTPS?

### ISSUE THREAD

**Issue by ghost** [INSPIRE-MIF/helpdesk-validator#310]
Hi,

we are using v2020.1.2 branch in our environment to check metadata requirements. The test "md dataset-and-series 1.10: Dataset conformity" fails because of the following error:
![grafik](https://user-images.githubusercontent.com/38787131/81950675-898d5d00-9604-11ea-9ccf-2a56aa75b2a7.png)

It seems that resource http://inspire.ec.europa.eu/schemas/common/1.0/enums/enum_bul.xsd has been redirected to https.

The same test passes in INSPIRE Validator production instance (resources cached?).

Any advice what could be the problem here?

Thanks in advance.

**Comment by danielnavarrogeo** [comment]
The same applies here https://github.com/inspire-eu-validation/community/issues/311#issuecomment-629077729

**Comment by carlospzurita** [comment]
There was an error on the registry side for the publication of schemas under HTTPS. This should be accessible now. See also https://github.com/inspire-eu-validation/community/issues/311#issuecomment-630058599 for more details on the HTTPS redirection and deployment options.

**Comment by ghost** [comment]
See https://github.com/inspire-eu-validation/community/issues/311#issuecomment-634575614.

**Comment by MarcoMinghini** [comment]
This issue with the schemas was not related to the http-https redirection of the Registry resources (see #319). The schemas were moved by mistake to https, and were immediately moved back to http.
