### ISSUE TITLE
Support for GML geometry types - Curve and Surface

### ISSUE THREAD

**Issue by calhanson** [INSPIRE-MIF/helpdesk-validator#314]
Hi!

When running the **Conformance Class: Download Service - Direct WFS** - test suite there seem to be a problem parsing certain geometry types in the following group of tests:

**WFS 2.0 (OGC 09-025r2/ISO 19142) Conformance Test Suite - Spatial filter - org.opengis.cite.iso19142.basic.filter.spatial.BBOXTests**

Here is a link to the result of the first test in the group:

https://inspire.ec.europa.eu/validator/v2/TestRuns/EIDbca1937b-3170-418b-917a-8d9850e1a827.html?lang=en#EID25e6d3c0-0172-1000-bb6a-eaf019aa297d

Running the tests locally, we have located a line in `DataSampler.java` calling `Extents.calculateEnvelope(geomNodes)` that throws for features with the following geometry types:

`Curve`
`Surface`

The feature types, that are using these geometry types, are based on `LinkType` and `NetworkAreaType` defined in http://inspire.ec.europa.eu/schemas/net/3.2/Network.xsd.

Should the Test Suite handle these types?

Regards

**Comment by danielnavarrogeo** [comment]
Dear @calhanson 

We will analyze it and we will keep you posted.

Regards

**Comment by carlospzurita** [comment]
Dear @calhanson 

We have opened an [issue](https://github.com/opengeospatial/ets-gml32/issues/55) on the OGC site for this problem, seeing that this problem is related to their TEAM engine.

Will keep you posted with any update.

**Comment by iuriemaxim** [comment]
It is the same as this https://github.com/inspire-eu-validation/community/issues/209 issue, which was already raised, isn't it?

**Comment by calhanson** [comment]
Perhaps there are similarities when it comes to not handling certain geometry types. It looks like SpatialJoinTests.java does not yet test the response other than verifying preconditions. The tests in BBOXTests.java has been implemented to validate that a response from a request with a BBOX filter only returns features matching that filter. However, the utility method Extents.calculateEnvelope(geomNodes) used in DataSampler.java throws an exception if geomNodes includes an unsupported geometry type. Support for geometry types Curve and Surface seem to be missing in that utility.

**Comment by iuriemaxim** [comment]
Have a look here:

https://github.com/opengeospatial/ets-wfs20/issues/164#

The test is indicating that the spatial join should be made manually.

However the validator triggers an error.

**Comment by calhanson** [comment]
I think this is another issue. And can not find any note that the BBOXTests should be validated manually. The test seem to be able to calculate an envelope for certain geometry types but fails for `Curve` and `Surface` geometries.

**Comment by carlospzurita** [comment]
Dear @iuriemaxim @calhanson 
We have been checking both issues, and, even if they seem to stem from a similar place, they are being treated differently on the OGC side.

**Comment by ghobona** [comment]
We have identified the source of the problem and are implementing a fix for it with the PR https://github.com/opengeospatial/geomatics-geotk/pull/4

As the geomatics-geotk library is used by several test suites, it will take sometime before the Beta and Production TEAM Engine instances are updated with the fix.

Cc: @MarcoMinghini @dstenger

**Comment by ghobona** [comment]
@carlospzurita 

The [geomatics-geotk](https://github.com/opengeospatial/geomatics-geotk) library has been updated on the Beta TEAM Engine. This included PR https://github.com/opengeospatial/geomatics-geotk/pull/4 which fixes this issue.

**Comment by iuriemaxim** [comment]
@ghobona The issue https://github.com/inspire-eu-validation/community/issues/209 was solved as well with this update.

**Comment by iuriemaxim** [comment]
@carlospzurita Even it is marked as an external dependency, shouldnt this be closed as the OGC solved the issue?
Now this is still open even if was solved more than one month ago.

**Comment by fabiovinci** [comment]
Dear all,
since all the issues opened in the external repositories and linked to this issue are closed, we close also this one.
Please feel free to reopen the issue or to open a new one if the problem persists.
