### ISSUE TITLE
Metadata point of contact - multiple electronicMailAddress for Metadata point of contact

### ISSUE THREAD

**Issue by VeronikaKusova** [INSPIRE-MIF/helpdesk-validator#316]
Hi all,
I ran ETS “**Common Requirements for ISO/TC 19139:2007 based INSPIRE metadata records**”. And it failed with an error in the “**md common req C.6: Metadata Point of Contact**” assertion. The problem is there is more than 1 electronicMailAddress element in the part Metadata point of contact. 

If I understand it correctly, according to the Technical guideline (p. 119)  there can be more than 1 electronicMailAddress.
![image](https://user-images.githubusercontent.com/33151159/82218302-fc0b7f00-991b-11ea-9037-fb5007b079b2.png)

A similar issue was solved for C.10 Responsible organisation and point of contact for the described resource (a part of this issue: #148 ).

The tested metadata file: 
[CZ-CUZK-WFS-HY.zip](https://github.com/inspire-eu-validation/community/files/4644356/CZ-CUZK-WFS-HY.zip)
Test report:
[Test run on 14_47 - 18.05.2020 with test suite Conformance Class 4_ INSPIRE Network Services metadata..html.zip](https://github.com/inspire-eu-validation/community/files/4644391/Test.run.on.14_47.-.18.05.2020.with.test.suite.Conformance.Class.4_.INSPIRE.Network.Services.metadata.html.zip)

Thank you.
Veronika

**Comment by danielnavarrogeo** [comment]
Dear @VeronikaKusova 

We will analyze it and we will keep you posted.

Regards

**Comment by danielnavarrogeo** [comment]
Dear @VeronikaKusova 

We are developing a solution to provide more than one electronicMailAddress.

We will ask you to test it when ready.

Regards

**Comment by danielnavarrogeo** [comment]
Dear @VeronikaKusova 

A solution has been developed and it is ready for testing in [staging instance](http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/).

Could you please check it and provide us feedback?

Regards

**Comment by VeronikaKusova** [comment]
Dear @danielnavarrogeo,

I have tested it (http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/v2/TestRuns/EID5e3c538a-15fa-4614-98a1-26e0174f7eb7.html ) and it seems ok - it works correctly. Thank you for the fast change.

Regards.

**Comment by danielnavarrogeo** [comment]
Thank you @VeronikaKusova for your feedback.

Regards
