### ISSUE TITLE
Issues on WFS - Pre-defined test run

### ISSUE THREAD

**Issue by carlospzurita** [INSPIRE-MIF/helpdesk-validator#317]
Dear INSPIRE users,

We have noticed that there is a problem with some test runs over the endpoint https://servisi.apprrr.hr/NIPP/wfs?ACCEPTVERSIONS=2.0.0&request=GetCapabilities&service=WFS&VERSION=2.0.0 . There is an error accessing the schema files declared in the Capabilities, and this makes the TestRun to be stuck forever. If they are replicated, they occupy all the free slots until no other TestRun can be created.

We are investigating the issue. Please, if you have any information on this, let us know as any feedback would be very much appreciated.

**Comment by iuriemaxim** [comment]
@carlospzurita 

Difficult to say where is the problem, but there are prefixes that are wrong

xmlns:NIPP="http://prod.nipp.hr"

Most probably the validator should trigger an error if the files have unexpected prefixes and not even to initialise the test if unexpected prefixes are found. But as we know the validator is not looking in this section at all and just start the test.

We raised an issue in relation to the fact that the links that are present in the header of the metadata should be publicly available online and the content of the cached XSD file to be the same with the one that is official.

I will try to find that issue that we raised in relation this.

Of course that none of the three prefixes would pass the test.

Iurie

**Comment by iuriemaxim** [comment]
This is the issue #191 that we raised and this is why data providers can now write anything in the XML header, impacting also the validator, not only the interoperability (@MarcoMinghini).

You may read some of my last posts related to the issue #191 why I was against implementing that change.

**Comment by carlospzurita** [comment]
Dear @iuriemaxim 
Thanks for the investigation on your side, it is very much appreciated. The issue with executing previous schema validations before a Test Run is being investigated on the ETF validator software that serves as a base for the INSPIRE validator (see https://github.com/etf-validator/governance/issues/93 for example). As you said, non-existent schemas should trigger an error on the pre-processing of the XML files.

However, we're still not really sure if this is the origin of the problem. We will update this issue with new information.

**Comment by iuriemaxim** [comment]
I tested

https://servisi.apprrr.hr/NIPP/wfs?request=zzz

https://servisi.apprrr.hr/NIPP/wfs?zzz

The WFS endpoint is not triggering an exception, neither is providing a response. 

Any request on WFS endpoint except https://servisi.apprrr.hr/NIPP/wfs?request=GetCapabilities will not work. However such request should trigger an exception
<ows:Exception exceptionCode="MissingParameterValue" locator="service">
<ows:ExceptionText>Could not determine service</ows:ExceptionText>

Of course that https://servisi.apprrr.hr/NIPP/wfs?request=GetCapabilities&ZZZZZZZZZZZZ will work as well, where ZZZZZZZ cound be any characters, including those indicated in the link to be tested

https://servisi.apprrr.hr/NIPP/wfs?ACCEPTVERSIONS=2.0.0&request=GetCapabilities&service=WFS&VERSION=2.0.0 . 

As no exception is triggered if parameters are missing, most probably there are some redirects wrongly implemented (ie in NGNIX).

However requests on WMS endpoint are handled correctly and respond with errors if the parameters are not provided:

https://servisi.apprrr.hr/NIPP/wms?zzz

As most probably the validator tries to make requests to the WFS endpoint (probably even for each feature type - and there are 21 of them declared) ... 

Probably would be good first to test that the endpoint is triggering errors by making a request such as https://servisi.apprrr.hr/NIPP/wfs?zzzz. If nothing is happening just stop as the endpoint is not a WFS.

Behavior could most probably be replicated by using NGINX without any WMS/WFS service, but just a file (GetCapabilities file) and a link to an URL that would take ages to respond and will not close the request after a certain time.

**Comment by fabiovinci** [comment]
Dear all,

I am closing the issue because it seems that the service that caused problems in the validator is no longer available.
