### ISSUE TITLE
Metadata validation - dataset identifiers during multiple files testing

### ISSUE THREAD

**Issue by VeronikaKusova** [INSPIRE-MIF/helpdesk-validator#318]
Hi all,
I have tested our metadata and it seems there is a problem with dataset identifiers during multiple files testing. 

The issue is connected to “**md datasets-and-series 1.3: Dataset UID**” assertion in ETS “**Conformance Class 1: INSPIRE data sets and data set series baseline metadata**” (assertion uri: https://inspire.ec.europa.eu/validator/v2/TestRuns/EID558041a9-84a7-46e1-9c58-05b1129db283.html?lang=cs#EID02b51641-3c85-4063-ab70-abfaa73abcc1). You can see the error message in the picture below:
![image](https://user-images.githubusercontent.com/33151159/82333345-e911b100-99e6-11ea-8edd-49109aecc242.png)

According to the message there are same dataset identifiers, but you can see form the attached metadata files there aren't.
When I test these metadata separately, it is ok. But when I test all of them in one session, there is this issue. In the metadata record “MET20_CZ-CUZK-EL” there are two dataset identifiers: `https://cuzk.cz/CZ-00025712-CUZK_EL` and `64113`. So, I tried to delete one of them, but the result was still the same. 

I have attached examples of tested metadata records. 
[metadata_identifier_issue.zip](https://github.com/inspire-eu-validation/community/files/4650796/metadata_identifier_issue.zip)
Test report: 
[Test run on 15_30 - 19.05.2020 with test suite Conformance Class 2_ INSPIRE data sets and data set series interoperability metadata..html.zip](https://github.com/inspire-eu-validation/community/files/4650797/Test.run.on.15_30.-.19.05.2020.with.test.suite.Conformance.Class.2_.INSPIRE.data.sets.and.data.set.series.interoperability.metadata.html.zip)

Thank you.
Veronika

**Comment by danielnavarrogeo** [comment]
Dear @VeronikaKusova

We will analyze it and we will keep you posted.

Regards

**Comment by danielnavarrogeo** [comment]
Dear @VeronikaKusova 

We have identified the issue and we are developing a solution for it.

Regards

**Comment by danielnavarrogeo** [comment]
Dear @VeronikaKusova 

A fix has been developed and it is ready for testing in [staging instance](http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/).

Could you please check it and provide us feedback?

Regards

**Comment by VeronikaKusova** [comment]
Dear @danielnavarrogeo, 

 thank you for good news, I have tested it and it works properly. 
Test report: http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/v2/TestRuns/EIDd64952b6-b0e4-450a-83b7-2683bbbd5b76.html 

Thank you and regards.
