### ISSUE TITLE
Metadatatest with GetRecordByID Request doesn't work.

### ISSUE THREAD

**Issue by Michael-81** [INSPIRE-MIF/helpdesk-validator#32]
Ticket: #96 and #209

Metadatatest doesn't work: "Es wurden keine Dateinen mit der Endung GML / XML gefunden!"

https://mdi-sh.org/nokis/servants/de/disy/preludio2/service/cat/csw/v_2_0_2/GetRecordByIdServant$Get?Service=CSW&Request=GetRecordById&Version=2.0.2&outputSchema=http://www.isotc211.org/2005/gmd&element=full&id=c6716a2e-8573-492b-91cb-0d144e6daef3

The GetRecord Request of Metadatatest doesn't work.

A GetGecordByID Request has no .xml ending in it's encoding!

**Comment by inakidiazdecerio** [comment]
Dear @Michael-81,

Thanks for reporting the issue. We understand that the ETF doesn't work when you are trying to validate the metadata with the URL. We are investigating the reason for this issue.

To validate the metadata, you can save the file as XML document and validate in the ETF with the option "File upload".

Regards.

**Comment by Michael-81** [comment]
Thanks.
But it's inefficent to save requests for testing the metadata.
The test need to support the CSW 2.0.2 standards, even when it's an optional ISO topic.

**Comment by cportele** [comment]
I can see two issues, one with the URL, one with the server:

* The "$" is not percent encoded. "$" is a reserved character in URIs and must be encoded as "%24", if it is used in the path. A curl request with the "$" in the path returns a 404. If the "$" is replaced by "%24" the XML document is returned.
* However, that response does not include a `Content-Type` header (try "curl -i <url>"), therefore the receiving system has no idea about the media type of the content. The HTTP specification recommends to treat such responses as "application/octet-stream".

Each issue alone could be the cause for the behaviour, the second one requires a fix to the server.

**Comment by Michael-81** [comment]
Thanks Clemens for your analyse.
The first Issue doesn't work by editing the URL in the validator.
Replacing characters can be done by programming a parsers in the validator, so that the correct format will be validate.

**Comment by cportele** [comment]
> The first Issue doesn't work by editing the URL in the validator.

Michael, in that case I suspect it is the second issue (not following the HTTP rules, RFC 2616). Using GetRecordById-URLs works with other servers that return Content-Type headers.

On 'replacing' characters (not following the URI rules, RFC 3986): URIs in INSPIRE documents should be valid URIs. Do not expect that receiving software should or will try to fix your URIs; the "$" might also be there for the intended reason. Avoid reserved characters like "$" in URIs. If that is not possible, URIs with "$"s should be properly encoded.

**Comment by jenriquesoriano** [comment]
It seems that the correct course of action is to modify the server on the reporter side, both by encoding correctly the URL of the service, and adding the correct Content-Type header to the response.

Following the error code on the log files, we found that the validator is unable to detect if the response contains the Content Type header with any of the following values: "application/xml", "application/gml+xml" or"application/atom+xml", or if the requested URL ends in ".xml" or ".gml". The response of the service doesn't have this header, and the URL has no format extension included.
