### ISSUE TITLE
ETF error message: Access to URL's of code lists 

### ISSUE THREAD

**Issue by DLList** [INSPIRE-MIF/helpdesk-validator#321]
Hello,

I have a problem with the ETF-Validator that I'd like to solve here.

I am currently busy developing a tool for transforming Annex III data into INSPIRE structures. I have created several INSPIRE Features and tested them with the Validator. For some time now I have been getting several error messages related to the resolution of URLs of code lists.

**My approach for creating INSPIRE-Data**
Standard generation of INSPIRE data based on the INSPIRE structures

**Testing the DataSet with the Validator**
During the tests of the created data local I get error messages that I didn't get when testing the same data online. The error messages refer to the access to URLs of code lists.

For example 

**gmlas.e.1**:
![grafik](https://user-images.githubusercontent.com/49745407/82781047-1df38d00-9e59-11ea-9980-ff2b17631a2d.png)

**gmlas.e.2**:
![grafik](https://user-images.githubusercontent.com/49745407/82782055-b4c14900-9e5b-11ea-9605-6435d1558cf2.png)

...

**Question**
The error message says: "Please contact a system administrator".
My question is: do you have any idea what could be the reason for these error messages?

Best regards,
Dawid

**Comment by carlospzurita** [comment]
Dear @DLList ,

Sorry for this inconveniences. Are you using a local deployment in your own premises, or are you getting this from the INSPIRE cloud deployments?

**Comment by DLList** [comment]
Dear @carlospzurita ,

we use the local deployment in our own premises.

**Comment by carlospzurita** [comment]
Dear @DLList 

Please refer to the latest comment in issue #319 where you can find a summary of the situation with the access to INSPIRE codelists.

**Comment by DLList** [comment]
Dear @carlospzurita 

Thank you for the answer. As far as I know, the problem is with INSPIRE-URIs, which should start with _http_, and not _https_.

My last question is, should we change all _https_ to _http_ to make our data INSPIRE compliant?
Or should an automatic redirection be integrated?

**Comment by MarcoMinghini** [comment]
Please refer to [my comment](https://github.com/inspire-eu-validation/community/issues/319#issuecomment-635220388) in #319. The difference is explained between the use of code lists as  identifiers (here you shall keep the http URIs) and the use of code lists when you need to look them up (here you shall handle the redirection).

**Comment by dperezBM** [comment]
Dear all,

Thank you very much for your contributions, we hope that everything is clear, as mentioned in [issue 319](https://github.com/INSPIRE-MIF/helpdesk-validator/issues/319).
Please, if you have any other questions or problems, do not hesitate to open another issue.

Best regards
