### ISSUE TITLE
Testing services running on a local machine

### ISSUE THREAD

**Issue by pandzel-zz** [INSPIRE-MIF/helpdesk-validator#323]
I am running validator through Docker to test WMS and CSW services. It works perfectly fine when given URL refers to the service publicly available. However, when I submit URL to the service running on my laptop I am getting errors:

> Check the availability of the server. The URL could not be processed due to a server error: Returned HTTP status code was '503' (Service Unavailable )

or

> Access to the private subnet was rejected by a configuration setting!

depending whether I use host name or IP address. I was experimenting with different Docker command line options (--dns, --network) but without a luck so far.

Do you have any advise or recommendation how one could test local services?

**Comment by carlospzurita** [comment]
Dear @pandzel 
The default mode for Docker networking is "bridge". This creates a new network interface for the container on startup, and this is mapped inside the docker container. If you check the output for `ip a` in your **host machine** with the container running, you will get something like this

![imagen](https://user-images.githubusercontent.com/10537778/84003844-ead9ef00-a96a-11ea-867e-8d0698493438.png)

You can use this address (172.17.0.1 in the case above) **within the container** to connect to your localhost, and point this way to the service running in the host machine. As the address that you insert in the validator form when starting the test run is processed inside the Docker container, it will use the bridge interface.

Please, if you have any doubts or comments, please let us know.
