### ISSUE TITLE
View Service - WMS: different behaviour of at38-getcapabilities-layer-authority-url in cases no Authority URL is used

### ISSUE THREAD

**Issue by hogredan** [INSPIRE-MIF/helpdesk-validator#324]
I tested two different View Services against CC View Service - WMS. In both cases no Authority URL is used. 

Service 1: https://geodienste.sachsen.de/iwms_gsz_geologie_gk400/guest?request=GetCapabilities&service=WMS&VERSION=1.3.0
Service 2: https://geodienste.sachsen.de/iwms_gsz_mineralische-bodenschaetze/guest?Request=GetCapabilities&SERVICE=WMS&VERSION=1.3.0

At service 1 test case [at38-getcapabilities-layer-authority-url](https://inspire.ec.europa.eu/validator/v2/TestRuns/EID0c300c84-b625-40a4-a975-86865e58834f.html?lang=de#EID923732b0-0172-1000-e665-00f69ae69d69) failed as expected, at service 2 test case [at38-gecapabilities-layer-authority-url](https://inspire.ec.europa.eu/validator/v2/TestRuns/EID0c300c84-b625-40a4-a975-86865e58834f.html?lang=de#EID923732b0-0172-1000-e665-00f69ae69d69) passed (expected: fail).

I wonder why service 2 did not fail (like service 1 did)? The two test reports are attached ([reports.zip](https://github.com/inspire-eu-validation/community/files/4744093/reports.zip)).

**Comment by carlospzurita** [comment]
Dear @hogredan 

After checking your services, we have refined the WMS test to check the uniqueness AuthorityURL in all the subsidiary Layers. We have deployed this in the [staging instance](http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/)

However, in this specific case, your service is indeed correct. Referring to the TG for View Services, we have the requirement

![image_2020_07_10T08_54_13_838Z](https://user-images.githubusercontent.com/10537778/87144850-b7abb800-c2a8-11ea-977f-198e6cbb07fa.png)

Following this, all subsidiary Layers can inherit the AutorityURL from their parent. In this case, both of the layers in the second service inherit the AuthorityURL declared at the top.

**Comment by hogredan** [comment]
Dear @carlospzurita 

thanks for your feedback and refining the WMS test. It looks fine now. 

In the meanwhile the services have changed (now they both use the AuthorityURL correctly). Therefore the original issue is no longer reproducible.

From my perspective, we can close the issue.

**Comment by hogredan** [comment]
Dear @carlospzurita 

I am sorry, but I have to "reopen" the issue. I have been notified of two other services that do not use an Authority URL. Both services pass the test case at38-getcapabilities-layer-authority-url although in our opinion the test case should fail. I have tested both services in staging instance. Test reports are attached.

Services end points:

- https://geodienste.sachsen.de/iwms_geosn_adressen/guest?REQUEST=GetCapabilities&SERVICE=WMS&VERSION=1.3.0

- https://geodienste.sachsen.de/iwms_geosn_verwaltungseinheiten/guest?Request=GetCapabilities&Service=WMS&Version=1.3.0 

[reports2.zip](https://github.com/inspire-eu-validation/community/files/4946308/reports2.zip)

**Comment by hogredan** [comment]
Dear @carlospzurita 

after checking the deployment in staging instance a bit more deeper I would like to add another comment on test case at38-getcapabilities-layer-authority-url. 

In cases where the service has more than one child layer inherit the (same) AuthorityURL from the parent layer, the test case failed: "A layer's Identifier mention an authority not defined in an available AuthorityURL element."

Examples:

- https://geodienste.sachsen.de/iwms_gsz_verteilung_der_arten/guest?Request=GetCapabilities&Service=WMS&Version=1.3.0

- https://geodienste.sachsen.de/iwms_gsz_geologie_gk400/guest?request=GetCapabilities&service=WMS&VERSION=1.3.0

From my point of view the services are correct, the Authority URL is defined in the parent layer and all child layers inherit the AuthorityURL from the parent layer.

Please check the test case again.

**Comment by carlospzurita** [comment]
Dear @hogredan 

Sorry for the delay, we are checking again this services to get some insight into this issue.

Kind regards.

**Comment by carlospzurita** [comment]
Dear @hogredan 

We have updated this requirement on the staging instance, reflecting the latest feedback that you provided. Please tell us if you are ok with the changes.

**Comment by hogredan** [comment]
Dear @carlospzurita 

thank you for the update. The issue mentioned above no longer occurs, but from my point of view there is another issue in the test. It seems to me that the test doesn't accept identifiers that are used for more than one layer. In my opinion req. 38 only states that identifiers are not inherited by subsidiary layers, but not that they have to be unique for each layer. This issue was already discussed in #255 Could you please check this again?

**Comment by carlospzurita** [comment]
Dear @hogredan 

Do you have an instance of this issue? The fix from #255 is preserved in this solution, so the Authority identifier uniqueness is not being checked.

**Comment by hogredan** [comment]
Dear @carlospzurita 

I have checked the issue on staging instance using this service end point:
https://geodienste.sachsen.de/iwms_gsz_verteilung_der_arten/guest?Request=GetCapabilities&Service=WMS&Version=1.3.0

Test run report: http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp//v2/TestRuns/EID81059fc3-17d5-4b9d-9bed-c6c6bd54ee69.html

**Comment by carlospzurita** [comment]
Dear @hogredan 

We have updated the staging instances to fix the issue for the authority URLs and preserve the solution from #255. There was a missing part on the validation script that wasn't taken into account during the development of this fix.

Can you check it out on the [staging instance](http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/) and test the solution? Thank you.

**Comment by hogredan** [comment]
Dear @carlospzurita 

thanks for the update. I have tested the solution and it looks fine now.
