### ISSUE TITLE
Unable to upload gml-file

### ISSUE THREAD

**Issue by krdasmhi** [INSPIRE-MIF/helpdesk-validator#325]
Hello,
I have a problem uploading my gml-file (330 mb) when performing test
![image](https://user-images.githubusercontent.com/65911842/84122208-62c21b00-aa38-11ea-9a12-ca7b066a18a0.png)

Error message:
![image](https://user-images.githubusercontent.com/65911842/84122093-360e0380-aa38-11ea-9428-96e04a89fe15.png)

I use google crome Version 83.0.4103.97 (Officiell version) (64 bitar)

And here I can't upload it either. It has to be smaller thean 10mb(!)

Best regards
Kristina Danielsson

**Comment by carlospzurita** [comment]
Dear @krdasmhi 

Thank you for your report. Could you please tell what is the validator instance you are using? Is it [production](https://inspire.ec.europa.eu/validator/) or [staging](staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/) ?

Also, please check out #322 , as there is an open discussion related to your problem.

**Comment by krdasmhi** [comment]
Dear Carlos,

I am using the production version.
If the limit is 20MB as it says in the GitHub discussion it explains why I am having trouble with my 350MB files.

Kind regards

Kristina Danielsson

GIS-utvecklare

SMHI / Swedish Meteorological and Hydrological Institute
Avdelningen för Samhälle och säkerhet och enheten för Information och statistik
SE - 601 76 NORRKÖPING
www.smhi.se<http://www.smhi.se/>

E-post: Kristina.Danielsson@smhi.se<mailto:Kristina.Danielsson@smhi.se>
Tel vx: +46 (0)11 495 80 00
Mobiltelefon: +46 (0)11 495 8673
Besöksadress: Folkborgsvägen 17




Från: Carlos Palma Zurita [mailto:notifications@github.com]
Skickat: den 9 juni 2020 14:15
Till: inspire-eu-validation/community
Kopia: Danielsson Kristina; Mention
Ämne: Re: [inspire-eu-validation/community] Unable to upload gml-file (#325)


Dear @krdasmhi<https://github.com/krdasmhi>

Thank you for your report. Could you please tell what is the validator instance you are using? Is it production<https://inspire.ec.europa.eu/validator/> or staging<staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/> ?

Also, please check out #322<https://github.com/inspire-eu-validation/community/issues/322> , as there is an open discussion related to your problem.

**Comment by carlospzurita** [comment]
Dear @krdasmhi 

We have increased the upload size limit to 200MB on the [staging](http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/) instance. After an internal discussion, we decided that a much higher limit was needed. We will keep this change for now on staging until the new release, to check if this causes any issue.

We have also updated the tooltip on the "Start Test Run" dialog.

**Comment by carlospzurita** [comment]
We have also increased the limit on the [production instance](https://inspire.ec.europa.eu/validator/) to 50MB.

**Comment by carlospzurita** [comment]
Dear @krdasmhi 

Did you try to validate your files using the new file size limit?

**Comment by krdasmhi** [comment]
Yes I did.
And since my file is 110 MB it can unfortunately still not be uploaded.

Best regards

Kristina Danielsson

GIS-utvecklare

SMHI / Swedish Meteorological and Hydrological Institute
Avdelningen för Samhälle och säkerhet och enheten för Information och statistik
SE - 601 76 NORRKÖPING
www.smhi.se<http://www.smhi.se/>

E-post: Kristina.Danielsson@smhi.se<mailto:Kristina.Danielsson@smhi.se>
Tel vx: +46 (0)11 495 80 00
Mobiltelefon: +46 (0)11 495 8673
Besöksadress: Folkborgsvägen 17




Från: Carlos Palma Zurita [mailto:notifications@github.com]
Skickat: den 14 september 2020 14:51
Till: inspire-eu-validation/community
Kopia: Danielsson Kristina; Mention
Ämne: Re: [inspire-eu-validation/community] Unable to upload gml-file (#325)


Dear @krdasmhi<https://github.com/krdasmhi>

Did you try to validate your files using the new file size limit?

**Comment by carlospzurita** [comment]
Dear @krdasmhi 

We're sorry that you are unable to upload your datasets into the production instance, but the limit needs to be set somewhere in order to preserve the performance. If you still need to, and you can't generate separated files for a complete dataset, you can always use the [staging instance](staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/), that has a higher threshold (200 MB)

Anyway, if the problem still is present, you can also deploy your own instance using the [latest release](https://github.com/inspire-eu-validation/community/releases/tag/v2020.3), where you can configure the size limit to meet your needs.

**Comment by carlospzurita** [comment]
Dear @krdasmhi 

Do you have further feedback on this issue? We can try to analyze other options for your validations. If not, we will proceed to close the issue.

Best

**Comment by krdasmhi** [comment]
Hello,

I manage so far by uploading small portions of my gml-file.

Best regards


Kristina Danielsson

GIS-utvecklare

SMHI / Swedish Meteorological and Hydrological Institute
Avdelningen för Samhälle och säkerhet och enheten för Information och statistik
SE - 601 76 NORRKÖPING
www.smhi.se<http://www.smhi.se/>

E-post: Kristina.Danielsson@smhi.se<mailto:Kristina.Danielsson@smhi.se>
Tel vx: +46 (0)11 495 80 00
Mobiltelefon: +46 (0)11 495 8673
Besöksadress: Folkborgsvägen 17



Från: Carlos Palma Zurita <notifications@github.com>
Skickat: den 13 november 2020 14:12
Till: inspire-eu-validation/community <community@noreply.github.com>
Kopia: Danielsson Kristina <kristina.danielsson@smhi.se>; Mention <mention@noreply.github.com>
Ämne: Re: [inspire-eu-validation/community] Unable to upload gml-file (#325)


Dear @krdasmhi<https://github.com/krdasmhi>

Do you have further feedback on this issue? We can try to analyze other options for your validations. If not, we will proceed to close the issue.

Best

**Comment by carlospzurita** [comment]
Dear @krdasmhi 

We are closing this issue for now then. Thank you for your feedback. If you have any problem again, please feel free to open a new issue in this space.

Best.
