### ISSUE TITLE
Validator will not validate when Norwegian is metadata language

### ISSUE THREAD

**Issue by larsingea** [INSPIRE-MIF/helpdesk-validator#327]
Test run on 11:07 - 10.06.2020 with test suite Conformance Class 1: INSPIRE data sets and data set series baseline metadata.
(https://inspire.ec.europa.eu/validator/v2/TestRuns/EID9f5debb3-4323-484c-ba9a-c3e3bec4cf74.html)

Uploaded metadata: https://www.geonorge.no/geonetworkbeta/srv/nor/xml_iso19139?uuid=c6896f24-71f9-4203-9b6f-faf3bfe1f5ed

Validator fails validating metadata because language code is **"nor"** :

Error message:
The metadata record set has 1 record(s) with errors for this assertion.
XML document 'xml_iso19139.xml', record 'c6896f24-71f9-4203-9b6f-faf3bfe1f5ed': A dataset (series) metadata record must have a gmd:Language code with a valid 3-letter language code (one of the values of enumeration type languageISO6392B in http://inspire.ec.europa.eu/schemas/common/1.0/common.xsd) within its gmd:identificationInfo. The metadata record has a gmd:LanguageCode within its gmd:identificationInfo, but the code value is not one of the allowed values. Found: **nor**.

The same problem appears with Icelandic (ice) as metadata language.

(For the old validator we had to make xsd files for norwegian language,. You can find them here: https://inspire-geoportal.ec.europa.eu/schemas/inspire/common/1.0/enums/enum_nor.xsd)

Best regards
Lars-Inge Arnevik
Norwegian Mapping Authority

**Comment by juanpelegrina** [comment]
Dear @larsingea
 
In this case, the validator test that a resource language is given pointing to one of the official languages of the Community expressed in conformity with ISO 639-2. "Ice" and "nor" are not included in the list of the 24.

You can find more details on the [ATS](https://github.com/inspire-eu-validation/metadata/blob/2.0/common/metadata-language-code.md) for this Test. There is more information on the [Technical Guide](https://inspire.ec.europa.eu/sites/default/files/documents/metadata/inspire-tg-metadata-iso19139-2.0.1.pdf) page 127

![image](https://user-images.githubusercontent.com/20069079/84375732-4bbe2d00-abe0-11ea-9e6f-54be2b9a9be0.png)

Please let us know if you have any other question.

Regards
Juan

**Comment by larsingea** [comment]
Thank you for your quick answer. The validator is obviously consistent with the IR,. Unfortunately this is a huge problem for us. It should, of course, not be a problem for us to use our native language in the metadata like the other countries.  We do also deliver all Free Text Elements in English as well. But I understand that we have to take this fight on another arena?
Best regards 
Lars-Inge Arnevik

**Comment by dperezBM** [comment]
Dear @larsingea,

Thank you very much for your contribution. Related to your question about where to take this topic, you can create an issue in the repository of the [INSPIRE helpdesk](https://github.com/INSPIRE-MIF/helpdesk), where the topics related to INSPIRE are discussed.

Please feel free to open another issue if needed.

Best regards.

**Comment by fabiovin** [comment]
Dear all,

since the addition of the Norwegian language was endorsed by MIG, we introduced the change in the validator ([see related pull request](https://github.com/inspire-eu-validation/ets-repository/pull/690)) and it will be available for test in the staging instance in the coming days.

**Comment by fabiovin** [comment]
Dear @larsingea,

the solution is available in staging and ready for testing.

**Comment by larsingea** [comment]
Very good! We have tested metadata for services, datasets and spatial data services and every thing seems to be OK! All of them validated with Norwegian as main language. Thank you very much!  😊
