### ISSUE TITLE
Handle data themes currently not implemented ? Please share your experience

### ISSUE THREAD

**Issue by apfelnymous** [INSPIRE-MIF/helpdesk-validator#33]
Hello, I need to check a Habitats & Biotopes gml file against Inspire conformity, there are currently no test suites given for that data theme on the inspire validator (http://inspire-sandbox.jrc.ec.europa.eu/etf-webapp/). 
Anyone gathered some experience with a locally deployed and self extended Test environment ?
While manually using the searching tool in notepad++ to check the whole gml file for missing mandatory attributes, I first thought about writing a python or c++ application to do that, now I first want to check if it would be smarter to install and extend the Test environment?! (someone not familiar with the test engines), though regarding "checking mandatory attributes" - I didnt see an implementation for the relevant abstract test suite: A. 1.4 Attributes/associations completeness test - in the test cases for the already given data themes ?! Did I miss something or was this not implemented yet ? Kind regards

**Comment by fabiovin** [comment]
Dear @apfelnymous,
the ATSs/ETSs for the Annex II & III data themes are under development.

In the meanwhile, you can use the 4 generic conformance classes available under the group "Interoperable data sets in GML (Guidelines for the Encoding of Spatial Data version 3.3)", to validate the common requirements and then you can check the theme-specific ones by hand.

For HB the only Theme-specific Requirement (_COMMISSION REGULATION (EU) No 1253/2013_) is: 

> **17.5. Theme-specific Requirements**
> (1) It is mandatory to make available at least one habitat type according to a (pan-european) referenceHabitatTypeScheme listed in the ReferenceHabitatTypeSchemeValue code list. This encoding is intended to allow for queries on habitat types on a pan-European harmonized level.

Please remember to add the following pair of values "http://www.opengis.net/gml/3.2 http://schemas.opengis.net/gml/3.2.1/gml.xsd" in the _xsi:schemaLocation_ attribute of your gml file, in addition to the pair of values related to the INSPIRE application schema.

Fabio

**Comment by fabiovin** [comment]
Dear @apfelnymous,
the tests for HB are now available on the [Staging instance](http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/).

Any feedback is more than welcome.

Regards,
Fabio

**Comment by dperezBM** [comment]
Dear @apfelnymous,

The HB theme is now available in the [production instance](https://inspire.ec.europa.eu/validator/). Please feel free to test it and open an issue if you find any problems. Also mention that we are updating [issue 336](https://github.com/INSPIRE-MIF/helpdesk-validator/issues/336) as we develop the new themes. 

We are closing this issue, but please feel free to open another one in case you need it.

Best regards.
