### ISSUE TITLE
Conformity to ISO 8601:2004 for all the relevant TG v2.0 requirements

### ISSUE THREAD

**Issue by dartasensi** [INSPIRE-MIF/helpdesk-validator#331]
Recently I got access to the ISO 8601:2004 specification document, and I found some discrepancies between the involved ETS tests and the ISO standard.

Plus, on the TG v2.0 there is a clear constraint to apply a specific version (2004) of the standard 8601, even though it is no more valid (in this case, ISO withdrawn the 2004 in favor of the 2019:1|2 version).

With a _quick and superficial_ search (ie. a partial text matching of "8601") in the TG v2.0 doc, I found these requirements as potentially involved:

- c.7 *metadata date*
- c.11 *date of creation*
- c.14 *temporal extent*
- c.21 *conformity specification*

In particular, I concentrated my test efforts on c.11.

In the related ETS ([permalink to the exact line here](https://github.com/inspire-eu-validation/ets-repository/blob/650ded1dd21b8e9a6b5bcd20dd8f92174da746df/metadata/2.0/common/ets-md-common-bsxets.xml#L435)), I found the following portion of code:

````
let $regexDate := '(^(\d{4})(-?)(0[1-9]|1[0-2])(-?)(0[1-9]|[12]\d|3[01])$)|(^(\d{4})(-?)([0-3][0-9][0-9])$)|(^(\d{4})(-?)(0[1-9]|1[0-2])$)|(^(\d{4})$)'
let $regexDateTime := '(^(\d{4})(-?)(0[1-9]|1[0-2])(-?)(0[1-9]|[12]\d|3[01])T([01]\d|2[0-3])(:?)([0-5]\d)(:?)([0-5]\d)(.?)([0-9]+)([+\-][0-9]{2}:[0-9]{2}|Z)$)|(^(\d{4})(-?)(0[1-9]|1[0-2])(-?)(0[1-9]|[12]\d|3[01])T([01]\d|2[0-3])(:?)([0-5]\d)(:?)([0-5]\d)([+\-][0-9]{2}:[0-9]{2}|[Z]?)$)|(^(\d{4})(-?)(0[1-9]|1[0-2])(-?)(0[1-9]|[12]\d|3[01])T([01]\d|2[0-3])(:?)([0-5]\d)([+\-][0-9]{2}:[0-9]{2}|Z)$)'
````

When applying the ISO specifications to these two patterns, it turns out that:

- as date, dash char must be always present for this format: `YYYY-MM`
- as date, it's missing the ISO week [W] format specification
- as datetime, when using the timezone specification, one pattern portion includes the slash `\` char, that is not admitted. Only these `[+-]` should to be checked in the input string
- as datetime, it should not be possible to have both the [Z] (UTC time) and an explicit timezone (+/-HH) specified

Moreover, while looking for similar regex patterns inside `ets-md-common-bsxets.xml`, I found **quite different variations of the same ISO datetime pattern**. Once the proper regex patterns are finalized and compliant with the standard, I suggest to apply these on all the valid sections of all the involved ETS tests.

In order to speed up this process, I'm currently preparing my potential suggestion, that I will post here as soon as possible.

Regards,
Davide

**Comment by juanpelegrina** [comment]
Thanks for stating this issue, we have analysed it and we are aligned with your comments. We will process your potential suggestion as soon as possible.

**Comment by dartasensi** [comment]
While analysing the potential solution together with @fabiovin, we know that there's an initial validation, made through the schema and its data types.
As indicated in the TG document, dates and datetimes are expressed with elements as `gco:Date` or `gco:DateTime`.
In fact, these two elements are composed by schema types that implement a specific version of the ISO 8601 (eg. spanning from 1988 to 2000 version, see ref. https://www.w3.org/TR/xmlschema-2/#ISO8601), disaligned with the one required by INSPIRE TG (ie. 8601:2004).

**Comment by dartasensi** [comment]
Here's below my revision of the `date` regex. Let me know your opinion about.
The regex (expressed in the `regexDate` variable) could recognize only calendar date and ordinal date but not week date. Plus, it still recognize this invalid format as correct: `YYYYMM`. The 2004 version specifies for that representation only one format (with dashes, ie. `YYYY-MM`), in order to discard the older ambiguous format (YYMMDD) and avoid any confusion.

My hands-on suggestion:
`'(^(\d{4})(-?)(0[1-9]|1[0-2])(-?)(0[1-9]|[12]\d|3[01])$)|(^(\d{4})(-?)(00[1-9])|(0[1-9]\d)|([1-2]\d\d)|(3[0-5]\d)|(36[0-6])$)|(^(\d{4})(-?)W(0[1-9]|[1-4]\d|5[0-3])(-?)([1-7])$)|(^(\d{4})(-?)W(0[1-9]|[1-4]\d|5[0-3])$)|(^(\d{4})(-)(0[1-9]|1[0-2])$)|(^(\d{4})$)|(^(\d{2})$)'`

Rationale:
`(^(\d{4})(-?)(0[1-9]|1[0-2])(-?)(0[1-9]|[12]\d|3[01])$)` // YYYY(-)MM(-)DD
`|`
`(^(\d{4})(-?)(00[1-9])|(0[1-9]\d)|([1-2]\d\d)|(3[0-5]\d)|(36[0-6])$)` // YYYY(-)DDD
`|`
`(^(\d{4})(-?)W(0[1-9]|[1-4]\d|5[0-3])(-?)([1-7])$)` // YYYY(-)Www(-)D
`|`
`(^(\d{4})(-?)W(0[1-9]|[1-4]\d|5[0-3])$)`  // YYYY(-)Www
`|`
`(^(\d{4})(-)(0[1-9]|1[0-2])$)` // YYYY-MM
`|`
`(^(\d{4})$)` // YYYY
`|`
`(^(\d{2})$)` // CC (centuries, as reduced accuracy expression for calendar years)

**Comment by dartasensi** [comment]
And here's the revision for the `dateTime` regex.
In this case, there's an additional effort to match all the possible combinations with the `date` regex.
Based on the standard, for a date and time representation you can use one complete expression for the date part, and a reduced accuracy for the time part.

My hands-on suggestion:
`^((\d{4})(-?)(0[1-9]|1[0-2])(-?)(0[1-9]|[12]\d|3[01])|(\d{4})(-?)(00[1-9])|(0[1-9]\d)|([1-2]\d\d)|(3[0-5]\d)|(36[0-6])|(\d{4})(-?)W(0[1-9]|[1-4]\d|5[0-3])(-?)([1-7]))T(([01]\d|2[0-3])(:?)([0-5]\d)(:?)([0-5]\d)(([,.]\d+)?([+-]([01]\d|2[0-3])(:[0-5]\d)?|Z)?)|([01]\d|2[0-3])(:?)([0-5]\d)(([,.]\d+)?([+-]([01]\d|2[0-3])(:[0-5]\d)?|Z)?)|([01]\d|2[0-3])(([,.]\d+)?([+-]([01]\d|2[0-3])(:[0-5]\d)?|Z)?))$`

Rationale:
`^`
`((\d{4})(-?)(0[1-9]|1[0-2])(-?)(0[1-9]|[12]\d|3[01])` // calendary day
`|`
`(\d{4})(-?)(00[1-9])|(0[1-9]\d)|([1-2]\d\d)|(3[0-5]\d)|(36[0-6])` // ordinal date
`|`
`(\d{4})(-?)W(0[1-9]|[1-4]\d|5[0-3])(-?)([1-7]))` // week date
`T` // time designator
`(`
`([01]\d|2[0-3])(:?)([0-5]\d)(:?)([0-5]\d)(([,.]\d+)?([+-]([01]\d|2[0-3])(:[0-5]\d)?|Z)?)`
`|`
`([01]\d|2[0-3])(:?)([0-5]\d)(([,.]\d+)?([+-]([01]\d|2[0-3])(:[0-5]\d)?|Z)?)`
`|`
`([01]\d|2[0-3])(([,.]\d+)?([+-]([01]\d|2[0-3])(:[0-5]\d)?|Z)?)`
`)`
`$`

**Comment by dartasensi** [comment]
I should also mention that these regexes are only syntatic checks. It doesn't account for leap years, impossible calendar day, or extreme timezones,

**Comment by vnotay** [comment]
Would it not be easier to use the `xs:date`,  `xs:time` and `fn:dateTime` [XQuery functions/operators](https://www.w3.org/TR/xpath-functions/#dates-times) instead of regular expressions? It would:
* make the code easier to maintain and read, and
* catch invalid dates such as 29th February in non-leap years.

One would of course still need to trap the error caused by parsing invalid dates and also separate the date and time parts for constructing `xs:dateTime`.

**Comment by dartasensi** [comment]
You're right, and I worked only on the regexes, since I don't know exactly if and how XQuery exceptions are properly catched in the Validator engine.

You says "instead", but in my opinion, the two approaches are not mutually exclusive: you can/should use both, since also the XQuery (based on which version implementation is available) could implement a different version of the 8601 standard (as we already discovered within the XML schema).
I guess we can quickly rearrange the regex group operators `( )` to extract informations, and then in the XQuery code use them to build a new temp XQuery object from it, handling any eventual exceptions.

**Comment by dartasensi** [comment]
Or are we saying the same thing? 👍 
> One would of course still need to trap the error caused by parsing invalid dates and also **separate the date and time parts for constructing `xs:dateTime`**.

**Comment by vnotay** [comment]
I believe that we are saying the same thing. What I meant was that you have to provide an `xs:date` and an `xs:time` instance for creating the `xs:dateTime` using the `fn:dateTime` function (at which point creating an `xs:dateTime` instance is unnecessary, as I later realised).

> [...] since also the XQuery (based on which version implementation is available) could implement a different version of the 8601 standard [...]

Okay, I get that now. The [documentation for XPath](https://www.w3.org/TR/xpath-functions-30/#date-time-duration-conformance) states explicitly:
> For a number of the above datatypes [XML Schema Part 2: Datatypes Second Edition] extends the basic [ISO 8601] lexical representations, such as YYYY-MM-DDThh:mm:ss.s for dateTime, by allowing a preceding minus sign, more than four digits to represent the year field — no maximum is specified — and an unlimited number of digits for fractional seconds. Leap seconds are not supported.


> You're right, and I worked only on the regexes, since I don't know exactly if and how XQuery exceptions are properly catched in the Validator engine.
> 
>[...]

I too am not an expert in XQuery, so I had to research a bit as well. But I found [a solution](https://www.w3.org/TR/xpath-31/#id-errors-and-opt) that could work: `if (not ($some_date castable as xs:date)) ...`

By the way, can the test for calendar date not be replaced with:
```regex
\d{4}-?(0[1-9]|1[0-2])-?([012]\d|3[01])
```

**Comment by dartasensi** [comment]
Well, I would keep the `( )` around the year, but you cannot use `[012]\d` since it permits this calendar day `00`
> By the way, can the test for calendar date not be replaced with:
> 
> ```regexp
> \d{4}-?(0[1-9]|1[0-2])-?([012]\d|3[01])
> ```

**Comment by juanpelegrina** [comment]
Thanks @dartasensi for your comments and input.

Starting from your original REGEX, we have added more valid formats according to ISO8601:2004. 
With this new REGEX, dates are syntactically and also semantically validated.

We have implemented the REGEX on [staging](http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/), so could you test the proposed solution? Please let us know what you think.

The proposed REGEX validates the following formats:

| | |
|-|-|
|Format|Example|
|YY|20|
|YYYY|2019|
|YYYY-MM|2019-04|
|YYYY-MM-DD|2019-04-16|
|YYYYMMDD|20190416|
|YYYY-DDD|2019-105|
|YYYYDDD|2019105|
|YYYY-Www|2019-W16|
|YYYYWww|2019W16|
|YYYY-Www-d|2019-W16-2|
|YYYYWwwd|2019W162|
|YYYY-MM-DDThh:mm:ssZ|2019-04-16T08:54:31Z|
|YYYYMMDDThhmmssZ|20200416T085431Z|
|YYYY-MM-DDThh:mm:ss+/-hh:mm|2019-04-16T10:54:31+02:00|
|YYYYMMDDThhmmss+/-hhmm|20190416T105431+0200|
|YYYY-MM-DDThh:mm:ss+/-hh|2019-04-16T10:54:31+02|
|YYYYMMDDThhmmss+/-hh|20190416T105431+02|
|YYYY-MM-DDThh:mm:ss|2019-04-16T08:54:31|
|YYYYMMDDThhmmss|20190416T085431|

**Comment by dartasensi** [comment]
Thanks for your effort. It seems correct, at the moment.
