### ISSUE TITLE
http vs https in CI_Citation or add INSPIRE TGs and Regulations to the Registry

### ISSUE THREAD

**Issue by iuriemaxim** [INSPIRE-MIF/helpdesk-validator#334]
Following this issue https://github.com/inspire-eu-validation/community/issues/319 all URIs from the INSPIRE registry should start with http, even if the registry is redirecting any http requests to https URLs.

However there are also other URIs under the control of INSPIRE for which the validaor will not triger an error if they are starting with https.

Such an URL is used as CI_Citation title for indicating that the network service is conformant with Technical Guidance for the implementation of INSPIRE Download Services (version 3.1):

https://inspire.ec.europa.eu/documents/technical-guidance-implementation-inspire-download-services

First question is, should the validator trigger an error if such URIs would be provided with https instead of http?

Second question is if it should not be better to have all the IRs and TGs as part of the Registry in order to be able to clearly specify to which document the service/dataset/metadata comply.

Same question is if Conformance Classes that are used in the validator should not be also part of the Registry as well?

Iurie

**Comment by fabiovin** [comment]
Dear @iuriemaxim,

thank you for starting this discussion on whether to add INSPIRE relevant documents (Technical Guidelines, Conformance classes, etc.) to the Registry.
As for the Regulations, they already have a unique identifier, such as "http://data.europa.eu/eli/reg/2010/1089" for COMMISSION REGULATION (EU) No 1089/2010, and this value is recommended by the MD TG.

For the time being, any URL (http or https) can be used to refer to other INSPIRE documents not present in a register, since these URLs are not considered "unique identifiers".

**Comment by o2idev** [comment]
Hi there,
please fix this because the docker image solution is a costly, bad and troublesome workaround :-(
See e.g. #351 and #346 especially, if there is a typical company HTTP(S) proxy involved.

kind regards
Andreas :)

**Comment by iuriemaxim** [comment]
@o2idev I do not think is something to be fixed in relation to this thread. 

Something can be changed in relation to the decision made in relation to http/https use.

This thread is not about a bug, but a discussion. 

Therefore your input is highly apreciated as we faced simmilar issues.

This thread was opened for other users to know which changes were made regading https / http in the INSPIRE Registry and to know that any other URIs that are not in the INSPIRE registry but still under INSPIRE/JRC/EC control could be refered with both https / http.

I agree that this change created a lot of problems and I sugest that all URLs in the INSPIRE Registry should be refered with https even if the decision was to keep them with http. Unfortunately the decision is not appropriate for real implementations.

Maybe it will be reconsidered the decision regarding use of http when the URLs are actually with https, to meet tehnical requirements.

The decision to keep https was most probably taken to keep it inline with the TGs, but this creates technical problems that nobody envisaged when the decision was made.

Iurie

**Comment by o2idev** [comment]
Please have a look at this because we have to release our product and this is a critical blocker :-(
#351 is just a workaround that does not work for us, but a decission to allow HTTP for codelists etc. seems the straight forward and logical step.
thanks
