### ISSUE TITLE
ETF cannot retrieve info from INSPIRE Registry

### ISSUE THREAD

**Issue by jmrubio82** [INSPIRE-MIF/helpdesk-validator#335]
It seems that there is a problem with the validator and its connection with the registry. When running the validation of a metadata file (TG2.0 Conformance Class 1), I get the following message:

System error in the Executable Test Suite. Please contact a system administrator. Error information:
Code list http://inspire.ec.europa.eu/theme cannot be accessed.

![image](https://user-images.githubusercontent.com/46571286/85269239-e4be3500-b477-11ea-9e30-8a36a6e3d5fa.png)

I did not get this type of error before on the same file, so it must be on the ETF side.

**Comment by carlospzurita** [comment]
Dear @jmrubio82 

We are investigating the issue and will get back to you with an answer. It seems that this could be an issue with the validator connection to the registry.

Kind regards.

**Comment by carlospzurita** [comment]
Dear @jmrubio82 

The issue is solved, there was a problem with the reverse proxy for caching schemas and the request weren't getting through.

Kind regards,

Carlos.

**Comment by jmrubio82** [comment]
Thank you, and apologies - I just realised I should have closed this issue some time ago :)
