### ISSUE TITLE
Temporal filter errors in Conformance Class: Download Service - Direct WFS 

### ISSUE THREAD

**Issue by Kate-Lyndegaard** [INSPIRE-MIF/helpdesk-validator#338]
Hi,
I have a question about several temporal filter errors which I had hoped would be resolved in the INSPIRE validator with the latest fixes in the OGC CITE [WFS 2.0 revision 1.33](https://cite.opengeospatial.org/te2/), fix [#157](https://github.com/opengeospatial/ets-wfs20/issues/157).

Direct WFS Conformance class: Temporal filters
org.opengis.cite.iso19142.basic.filter.temporal.AfterTests
org.opengis.cite.iso19142.basic.filter.temporal.BeforeTests
org.opengis.cite.iso19142.basic.filter.temporal.DuringTests

All of the errors appear to indicate that the property `validTo` is tested, however `validTo` is a nillable property with 0 cardinality in the INSPIRE Planned Land Use schema and it does not occur in my dataset. 

**Test WFS**: https://test.haleconnect.de/ows/services/org.315.2d4db8c9-1736-406c-9b54-fc0ca527e2a3_wfs/org.315.ed014538-597a-4254-8844-60ee149fcfe0?SERVICE=WFS&REQUEST=GetCapabilities&VERSION=2.0.0

Screenshot:
![grafik](https://user-images.githubusercontent.com/36956461/85735511-ffa1db00-b6fd-11ea-9168-cc4069e54d15.png)

I would really appreciate any insight on these errors and why they are occurring.

Thank you!

Kind regards,
Kate

**Comment by carlospzurita** [comment]
Dear @Kate-Lyndegaard 

We have checked your error [directly](https://cite.opengeospatial.org/te2/rest/suites/wfs20/run?wfs=https%3A%2F%2Ftest.haleconnect.de%2Fows%2Fservices%2Forg.315.2d4db8c9-1736-406c-9b54-fc0ca527e2a3_wfs%2Forg.315.ed014538-597a-4254-8844-60ee149fcfe0%3FACCEPTVERSIONS%3D2.0.0%26REQUEST%3DGetCapabilities%26SERVICE%3DWFS%26VERSION%3D2.0.0) with the TEAM Engine and this error was indeed corrected and no reference . However, the fix published is under the beta version of the test engine, yet the INSPIRE validator uses the production release of the TEAM Engine.

Whenever the OGC would roll out this update, the validator will use it.

**Comment by Kate-Lyndegaard** [comment]
Dear @carlospzurita,

That's great news:-) Thank you very much for the clarification. We will await the roll out.

Kind regards,
Kate
