### ISSUE TITLE
ETS extension for national md profile needs

### ISSUE THREAD

**Issue by klimeto** [INSPIRE-MIF/helpdesk-validator#34]
Dear devs & users,

We'd like to use the reference validator to validate resources in our national SDI where the metadata has some further extensions over TG201. Is there any how-to describing steps needed to extend e.g. ETS for MD TG2 that we can use in order to deploy a customised ETS?
Thank you,
Tomáš

**Comment by MarcoMinghini** [comment]
Dear @klimeto,
thanks for your message. As also announced in another issue (https://github.com/inspire-eu-validation/community/issues/20) we are planning to organize a workshop on the ETF Validator especially targeting developers and national implementers who want to use/extend the Validator for their purposes.
The workshop might be organized after summer 2019, depending on the feedback we receive in terms of interest from national INSPIRE implementers.
Please let us know if you have - in addition to the request on the ETS for MD TG 2.0 - specific requests or suggestions on what should be covered in the workshop. Feel free to reply also under issue https://github.com/inspire-eu-validation/community/issues/20.

**Comment by klimeto** [comment]
Dear @MarcoMinghini,

Workshop is a great idea Indeed!

In addition to a ETS customisations and extensions, I would like to suggest maybe a short session dealing with the ETF API usage, which is quite complex. I'm implementing SW Which should validate metadata using ETF API and found quite difficult to extract a flat validation report from JSON returned by ETF for a test case. That JSON is too hierarchical and large maybe a specific flatter version containing Test assertion name, result, time and message would be easier to be parsed by API consumer. What do you think? Thanks

**Comment by MarcoMinghini** [comment]
Dear @klimeto ,
thanks for your feedback. Can you include the same comments/ideas in https://github.com/inspire-eu-validation/community/issues/20? We will discuss about the possible workshop (and related content) during the next sub-group meeting on May 22.
Thank you!

**Comment by MarcoMinghini** [comment]
Dear @klimeto,
we have scheduled the workshop on the INSPIRE Reference Validator. It will take place at the JRC in Ispra on October 1-2, 2019.

The workshop will cover two full days: on the first day it will address users of the validator, on the second day it will address developers working with the Validator (the latter should be relevant for you).

At this preparatory stage, we would like to know how many people are interested to attend each workshop day and what are the topics they are most interested in.

For this reason, we setup a survey where you can express interest to attend the workshop and indicate your preference about the day(s) to attend and the topics to be covered: https://ec.europa.eu/eusurvey/runner/Validator-Workshop

Feel free to circulate this message to other people who are working with the Validator, either as users or developers, and may be interested in attending. The deadline for providing the expressions of interest is July 31, 2019.

Thank you.
