### ISSUE TITLE
Test C.18 - New corner case

### ISSUE THREAD

**Issue by juanpelegrina** [INSPIRE-MIF/helpdesk-validator#343]
@fabiovin has stated a new corner case for C.18, if there are multiple occurrences of the element "gmd:otherConstraints" for both metadata elements, c.18 and c.17, the metadata fails.

attaches metadata:

md_2.0_datasets_example.xml: there are two occurrences of the element "gmd:otherConstraints" for both metadata elements --> It should pass but fails (https://inspire.ec.europa.eu/validator/v2/TestRuns/EID5e337ee4-5dc9-4088-b99f-9410dd6769bf.html)

md_2.0_datasets_example_1otherC.xml: there is only one occurrence of the element "gmd:otherConstraints" for both metadata elements --> It correctly pass (https://inspire.ec.europa.eu/validator/v2/TestRuns/EIDabc60bec-5e46-4127-b1eb-db9d9b37410c.html)

This issue has been opened to keep track of the solution proposed.

**Comment by carlospzurita** [comment]
A fix has been developed and it is available on the [staging instance](staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/).

**Comment by fabiovin** [comment]
Thank you for the fix.
I tested it and it works fine.
