### ISSUE TITLE
docker image access requires basic authentication

### ISSUE THREAD

**Issue by DLList** [INSPIRE-MIF/helpdesk-validator#346]
Dear INSPIRE Validator team,

we would like to apply the ugly, annoying and of course politically driven HTTPS fix of your **docker image**:  
 [https://github.com/inspire-eu-validation/community/issues/311#issuecomment-630058599](https://github.com/inspire-eu-validation/community/issues/311#issuecomment-630058599)

**The problem is, that obviously we need basic authentication credentials to do this which we do not know.
Or is some auth bug on your or Github’s end?**

We tried both documented version for the latest and previous releases without success:

[https://github.com/inspire-eu-validation/community/releases](https://github.com/inspire-eu-validation/community/releases)

`sudo docker run --name inspire-validator -d -p 8080:8080 -v ~/etf:/etf docker.pkg.github.com/inspire-eu-validation/community/inspire-validator:2020.2`

`Unable to find image 'docker.pkg.github.com/inspire-eu-validation/community/inspire-validator:2020.2' locally
docker: Error response from daemon: Get https://docker.pkg.github.com/v2/inspire-eu-validation/community/inspire-validator/manifests/2020.2: no basic auth credentials.`

[https://github.com/inspire-eu-validation/community/packages/149175#start-of-content](https://github.com/inspire-eu-validation/community/packages/149175#start-of-content)

`sudo docker pull docker.pkg.github.com/inspire-eu-validation/community/inspire-validator:2020.2`

`Error response from daemon: Get https://docker.pkg.github.com/v2/inspire-eu-validation/community/inspire-validator/manifests/2020.2: no basic auth credentials`

(We use Ubuntu 16.04 LTS, set up the proxy for docker client and daemon successfully also running the docker hello-world sample)

Thanks a lot for your help and your work! 😊
Andreas

**Comment by carlospzurita** [comment]
To execute the Docker image hosted in Github, you need to provide Github credentials to the Docker daemon. This can be achieved executing

`docker login docker.pkg.github.com`

before executing the `docker pull` command.

We are going to improve the documentation making this more explicit in the release notes.

**Comment by DLList** [comment]
> 
> 
> Dear INSPIRE Validator team,
> 
> we would like to apply the ugly, annoying and of course politically driven HTTPS fix of your **docker image**:
> [#311 (comment)](https://github.com/inspire-eu-validation/community/issues/311#issuecomment-630058599)
> 
> **The problem is, that obviously we need basic authentication credentials to do this which we do not know. Or is some auth bug on your or Github’s end?**
> 
> We tried both documented version for the latest and previous releases without success:
> 
> https://github.com/inspire-eu-validation/community/releases
> 
> `sudo docker run --name inspire-validator -d -p 8080:8080 -v ~/etf:/etf docker.pkg.github.com/inspire-eu-validation/community/inspire-validator:2020.2`
> 
> `Unable to find image 'docker.pkg.github.com/inspire-eu-validation/community/inspire-validator:2020.2' locally docker: Error response from daemon: Get https://docker.pkg.github.com/v2/inspire-eu-validation/community/inspire-validator/manifests/2020.2: no basic auth credentials.`
> 
> https://github.com/inspire-eu-validation/community/packages/149175#start-of-content
> 
> `sudo docker pull docker.pkg.github.com/inspire-eu-validation/community/inspire-validator:2020.2`
> 
> `Error response from daemon: Get https://docker.pkg.github.com/v2/inspire-eu-validation/community/inspire-validator/manifests/2020.2: no basic auth credentials`
> 
> (We use Ubuntu 16.04 LTS, set up the proxy for docker client and daemon successfully also running the docker hello-world sample)
> 
> Thanks a lot for your help and your work! 😊
> Andreas

Supplementary:

Maybe this is a known Github problem. It would be nice, if you could update your description with the info that one has to have an Github account and how to properly configure it to make Docker work.

https://github.community/t/docker-pull-from-public-github-package-registry-fail-with-no-basic-auth-credentials-error/16358

I’ll try this out, but waiting since 1 day for the confirmation mail for my Github account. :-/ (I write not from my account)

**Comment by carlospzurita** [comment]
We added more information on the deployment instructions in the release to make people aware of the need to login to the Github repository from Docker. You can check it out here https://github.com/inspire-eu-validation/community/releases/tag/v2020.2

**Comment by carlospzurita** [comment]
Dear @DLList 

Did you have the opportunity to review the deployment instructions for the Docker image? We are working on improving them for the next release, but your input would be highly appreciated

**Comment by o2idev** [comment]
Hi Carlos,

the DLList account is an individuals account in our team. We now try to use this one for communication here.
Thanks for updating the instructions and so far you know where our problems currently reside :) (#351 / HTTPS problems)

Have a nice week

**Comment by joppekoers** [comment]
The GitHub package registry now supports pulling images without logging in
@DLList has the wrong domain:
The original:
```
sudo docker pull docker.pkg.github.com/inspire-eu-validation/community/inspire-validator:2020.2
```
Should be:
```
sudo docker pull ghcr.io/inspire-eu-validation/community/inspire-validator:2020.2
```
