### ISSUE TITLE
RelatedParty string attributes are not checked for PT_FreeText

### ISSUE THREAD

**Issue by JohannaOtt** [INSPIRE-MIF/helpdesk-validator#349]
I tested some Soil data including a RelatedParty object (in its observations in Process.responsibleParty):
`<ompr:responsibleParty>
        <base2:RelatedParty>
          <base2:individualName>
            <gco:CharacterString>NameOfPerson</gco:CharacterString>
          </base2:individualName>
          <base2:organisationName>
            <gco:CharacterString>NameOfOrganisation</gco:CharacterString>
          </base2:organisationName>
          <base2:positionName>
            <gco:CharacterString>official in charge</gco:CharacterString>
          </base2:positionName>
          <base2:contact>
            <base2:Contact>
              <base2:address>
                <ad:AddressRepresentation>
                  <ad:adminUnit>
                    <gn:GeographicalName>
                      <gn:language>deu</gn:language>
                      <gn:nativeness nilReason="other:unpopulated" xsi:nil="true"></gn:nativeness>
                      <gn:nameStatus nilReason="other:unpopulated" xsi:nil="true"></gn:nameStatus>
                      <gn:sourceOfName nilReason="other:unpopulated" xsi:nil="true"></gn:sourceOfName>
                      <gn:pronunciation nilReason="other:unpopulated" xsi:nil="true"></gn:pronunciation>
                      <gn:spelling>
                        <gn:SpellingOfName>
                          <gn:text>City</gn:text>
                          <gn:script>Latn</gn:script>
                        </gn:SpellingOfName>
                      </gn:spelling>
                    </gn:GeographicalName>
                  </ad:adminUnit>
                  <ad:locatorDesignator>26</ad:locatorDesignator>
                  <ad:postCode>00000</ad:postCode>
                  <ad:thoroughfare>
                    <gn:GeographicalName>
                      <gn:language>deu</gn:language>
                      <gn:nativeness nilReason="other:unpopulated" xsi:nil="true"></gn:nativeness>
                      <gn:nameStatus nilReason="other:unpopulated" xsi:nil="true"></gn:nameStatus>
                      <gn:sourceOfName nilReason="other:unpopulated" xsi:nil="true"></gn:sourceOfName>
                      <gn:pronunciation nilReason="other:unpopulated" xsi:nil="true"></gn:pronunciation>
                      <gn:spelling>
                        <gn:SpellingOfName>
                          <gn:text>Street</gn:text>
                          <gn:script>Latn</gn:script>
                        </gn:SpellingOfName>
                      </gn:spelling>
                    </gn:GeographicalName>
                  </ad:thoroughfare>
                </ad:AddressRepresentation>
              </base2:address>
              <base2:electronicMailAddress>email@email.de</base2:electronicMailAddress>
              <base2:telephoneFacsimile>00000</base2:telephoneFacsimile>
              <base2:telephoneVoice>00000</base2:telephoneVoice>
              <base2:website>https://website.de</base2:website>
            </base2:Contact>
          </base2:contact>
          <base2:role xlink:href="http://inspire.ec.europa.eu/codelist/RelatedPartyRoleValue/authority"></base2:role>
        </base2:RelatedParty>
      </ompr:responsibleParty>`

The validator did not return an error for this dataset although RelatedParty.individualName, RelatedParty.organisationName and relatedParty.positionName should be of type PT_FreeText according to the [IR](https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:02010R1089-20141231&qid=1594976083725&from=DE):
![grafik](https://user-images.githubusercontent.com/34163838/87768206-14185580-c81c-11ea-9d22-87c1316d904f.png)

IMHO using PT_FreeText here is not appropriate (see also[ this thread in the Thematic Cluster](https://wayback.archive-it.org/12090/20210123111050/https://inspire.ec.europa.eu/forum/discussion/view/266659/strings-in-processresponsiblepartyrelatedparty)), but theoretically this should lead to a validation error.

Is it expected that the validator will be adapted accordingly or will using CharacterString instead of PT_FreeText rather be officialy declared as legal?

Thanks and all the best

Johanna

**Comment by carlospzurita** [comment]
Dear @JohannaOtt 

We need to discuss this internally, given that this may have implications in several test implementations. We are going to mark this as a discussion for now, and get back to you with an official response.

Thank you.

**Comment by JohannaOtt** [comment]
@carlospzurita Are there already any news on this?

**Comment by JohannaOtt** [comment]
@carlospzurita Did you already have the chance to discuss this internally?

**Comment by carlospzurita** [comment]
Dear @JohannaOtt 

We did not have the opportunity to tackle this issue, let us revisit it and will come back to you with more feedback. We are modifying the label to "Under Analysis" as this doesn't need any discussion from the community.

**Comment by fabiovinci** [comment]
Dear @JohannaOtt,

before starting the development of the specific checks for the data type `PT_FreeText`, since now there is in place a governance mechanism for the update of the TGs, a change proposal could be made.

What do you think?

**Comment by JohannaOtt** [comment]
@fabiovinci I created [this change proposal](https://github.com/INSPIRE-MIF/application-schemas/issues/69) for the issue described here. I agree, that it would be a lot more useful to change the IR so that both are allowed instead of changing the behavior of the validator in this case.

**Comment by fabiovinci** [comment]
Dear @JohannaOtt,
the decision related to your change proposal was that there is "no need to change XSD, no need to change UML".
The issue was closed and the related content is summarised and made available as an "[Implementation example](https://github.com/INSPIRE-MIF/helpdesk/discussions/135)" in the Discussions tab of the generic helpdesk.

According to these results, no changes are required in the validator and this issue can be closed.
