### ISSUE TITLE
Metadata models in json schema

### ISSUE THREAD

**Issue by klimeto** [INSPIRE-MIF/helpdesk-validator#35]
Dear community,

Do you know if there are any json schema documents publicly available, e.g. for TG20?

Many thanks,
Tomáš

**Comment by dperezBM** [comment]
Dear @klimeto,

Thank you very much for your contribution. However, this question can be answered in the [INSPIRE helpdesk](https://github.com/INSPIRE-MIF/helpdesk). Feel free to open an issue here with your question.

Best regards.
