### ISSUE TITLE
md common req C.11: Temporal Reference

### ISSUE THREAD

**Issue by alitka** [INSPIRE-MIF/helpdesk-validator#350]
Please reopen issue https://github.com/inspire-eu-validation/community/issues/175 and if necessary https://github.com/inspire-eu-validation/community/issues/202 too! Also related to issue https://github.com/inspire-eu-validation/community/issues/331

- [x]  description of the steps to reproduce the issue
1. go to http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp and select "Common Requirements for ISO/TC 19139:2007 based INSPIRE metadata records"
2. start the test and upload an externale xml-file
case 1 with codeListValue to "creation": [dataset_DE_temporalReferenceCreation.zip](https://github.com/inspire-eu-validation/community/files/4108950/dataset_DE_temporalReferenceCreation.zip)
case 2 with codeListValue to "revision": [dataset_DE_temporalReferenceRevision.zip](https://github.com/inspire-eu-validation/community/files/4108951/dataset_DE_temporalReferenceRevision.zip)
case 3 with codeListValue "publication": [dataset_DE_temporalReferencePublication.zip](https://github.com/inspire-eu-validation/community/files/4937532/dataset_DE_temporalReferencePublication.zip)

- [x] used browser and version: Firefox Browser 72.0 (64-Bit)
- [x] a screenshot illustrating the problem
case 1 to 3: ![grafik](https://user-images.githubusercontent.com/29542183/87782871-9fe9ac00-c833-11ea-8e8c-351cd745329b.png)

- [x] the Test Report
case 1 to 3: [report_DE_temporalReferenceCase1-3.zip](https://github.com/inspire-eu-validation/community/files/4937597/report_DE_temporalReferenceCase1-3.zip)

- [x] the name of the Test that failed: 
case 1 to 3: md common req C.11: Temporal Reference

This issue was already fixed/solved and has been reversed by [merge pull request #474 from inspire-eu-validation/issue-331](https://github.com/inspire-eu-validation/ets-repository/commit/189f32065e1a5fe1c4ad745c55d937fbfdf6989b#diff-41cefbb242a3cc381d35d4974fc54a29) on June 23, 2020. Could you check the changes and correct them if necessary, please?

Thanks & regards.

**Comment by juanpelegrina** [comment]
Dear @alitka, thanks for opening the issue, 

we are working on it. We have located the last changes applied and we are discussing if they are aligned with the ISO8601.

Regards
Juan

**Comment by alitka** [comment]
Dear @juanpelegrina 

> we are working on it. We have located the last changes applied and we are discussing if they are aligned with the ISO8601.

Are there any news regarding this topic?
Thanks and best regards.

**Comment by carlospzurita** [comment]
Dear @alitka 

We are modifying the requirement from the ETS in order to include decimal values contemplated in the ISO8601. We will get back to you whenever it is deployed on the staging instance to be tested.

**Comment by carlospzurita** [comment]
Dear @alitka 
A fix has been published on the [staging instance](http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/) for this issue. Please let us know if everything is in order.
Kind regards.

**Comment by alitka** [comment]
Dear @carlospzurita,
I have tested all three cases again, plus some additional dataset records and everything is working properly.
Thanks and best regards!

**Comment by alitka** [comment]
Dear @carlospzurita 
This issue was already fixed/solved - see my comment on August 20th, 2020 and has been reversed by another merge pull request. Nevertheless, if you take the initial provided test material the test "md common req C.11: Temporal Reference" failes again. Could you check the latest changes and correct them if necessary, please?
Thanks and best regards!

**Comment by carlospzurita** [comment]
Dear @alitka 

We were solving some issues on the configuration on the staging instance, and you were seeing outdated test reports. You can check that all three resources provided pass the validations in these links [1](http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/v2/TestRuns/EID3bb891be-8125-45d4-aee6-c3b964ebeb78.html) [2](http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/v2/TestRuns/EID4a0f28a0-acb4-4526-8b1b-f266ffe4d848.html) [3](http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/v2/TestRuns/EID3e078ee1-8190-4849-97ae-1cf71119d524.html)
