### ISSUE TITLE
Unable to start test of metadata for Invocable spatial data Service

### ISSUE THREAD

**Issue by radochudy** [INSPIRE-MIF/helpdesk-validator#352]
Hi, I tried to setup test for Incablle spatial data service metadata >

![image](https://user-images.githubusercontent.com/6662421/87930717-d835f800-ca88-11ea-96be-9f176d9e33f7.png)

But after Start it shows only this window with no way to proceed:

![image](https://user-images.githubusercontent.com/6662421/87930841-0b788700-ca89-11ea-9572-3ac85e15b766.png)

Please can you check it? Thanks.

**Comment by juanpelegrina** [comment]
Dear @radochudy

In order to reproduce the error, could you provide us with the URL of the service you are trying to test?

Regards
Juan

**Comment by radochudy** [comment]
Hi,

I'm trying to validate metadata xml files... and due to reported error I was enable to upload it  so I think, you don't need any input from me, but here is xml file...

[invoke.zip](https://github.com/inspire-eu-validation/community/files/4947343/invoke.zip)

**Comment by juanpelegrina** [comment]
Thanks @radochudy

We are sorry but we are not able to reproduce the error, we can run the [test](https://inspire.ec.europa.eu/validator//v2/TestRuns/EID5b18fe80-02d9-415a-bdda-d233c210d799.html)

What browser are you using? 
Have you tried with another browser?
Could you delete the cache of the browser?
Could you try with another Conformance Class? is it also happening? 
Could you also try on staging?


Regards
Juan

**Comment by radochudy** [comment]
Ok. Problem was cache of browser...
