### ISSUE TITLE
Incorrect GML schema validation?

### ISSUE THREAD

**Issue by mattenp** [INSPIRE-MIF/helpdesk-validator#353]
Hi, after GML validation test, I get "Cannot find the declaration of element 'gml:FeatureCollection'." (http://inspire.ec.europa.eu/id/ats/data/master/schemas/schema-validation ), but XML-Spy, etc, validation was successful. I suppose it's a bug.

s. https://inspire.ec.europa.eu/validator/v2/TestRuns/EID4d599b47-294a-4dc2-80ad-9bfd9350925c.html or attachment

[INSPIRE_EL-V.zip](https://github.com/inspire-eu-validation/data/files/4954172/INSPIRE_EL-V.zip)

Best regards,

matthias

**Comment by jenriquesoriano** [comment]
Dear @mattenp,

this issue has been transferred to the [community space](https://github.com/inspire-eu-validation/community/), where it will be addressed by the INSPIRE Reference Validator team.
Please note that issues under inspire-eu-validation/data repository are no longer monitored ([inspire-eu-validation/data/#40](https://github.com/inspire-eu-validation/data/issues/40)).

Best regards,

**Comment by fabiovin** [comment]
Dear @mattenp,
the validator is not able to retrieve the declaration of element 'gml:FeatureCollection' from the INSPIRE application schemas, even though these last ones import the 'gml.xsd'.

So, you need to add the following pair of values "http://www.opengis.net/gml/3.2 http://schemas.opengis.net/gml/3.2.1/gml.xsd" in the xsi:schemaLocation attribute, in addition to the pair of values related to the INSPIRE application schema.

Fabio

**Comment by mattenp** [comment]
Thanks a lot, now it works. You can close the issue.

Best regards,
Matthias
