### ISSUE TITLE
Validator not working

### ISSUE THREAD

**Issue by radochudy** [INSPIRE-MIF/helpdesk-validator#354]
Since this morning, I'm not able to run metadata validation. Upload of file seems to be slow and I'm not able to run any metadata test at all . It stucks on start page>
![image](https://user-images.githubusercontent.com/6662421/88274050-63a6c780-ccdb-11ea-9d0a-eebbe68840cd.png)

**Comment by jenriquesoriano** [comment]
Dear @radochudy , 

thanks for pointing out the issue, we have experienced a heavy use of the validator during the morning which has finally led to the unavailability of the service.
We are currently working to solve it as soon as possible, please see [Maintenance works #355](https://github.com/inspire-eu-validation/community/issues/355) 

Best regards,

**Comment by jenriquesoriano** [comment]
Dear @radochudy , 

maintenance is over. 
The INSPIRE Reference Validator has returned to normal operation.
Thanks for your contribution.

Best regards,
