### ISSUE TITLE
Validator doesn't work properly

### ISSUE THREAD

**Issue by ghost** [INSPIRE-MIF/helpdesk-validator#356]
Validation of [the dataset](https://github.com/inspire-eu-validation/community/files/4986232/Data.zip) couldn't be performed in the validator.

Different problems occured while trying to validate metadata record several times.

Directly when uploading:
![upload-problem](https://user-images.githubusercontent.com/38787131/88624442-41c88e80-d0a7-11ea-86e5-57addc93477f.png)

If upload successful, when trying to open report:
![timeout](https://user-images.githubusercontent.com/38787131/88624525-6c1a4c00-d0a7-11ea-8e4a-c9e56822296a.png)

The message "Could not fetch test object" appears on different actions in the validator:
- when opening main page
- when opening report page

![error-message](https://user-images.githubusercontent.com/38787131/88624666-ab489d00-d0a7-11ea-803a-da1dec9b6908.png)

**Comment by jenriquesoriano** [comment]
Dear  @DeordD,

thanks for pointing the issue, we are monitoring and collecting data to determine the cause of the issue.
It seems to be related to performance issues as there are other tests which are running correctly.
Nevertheless, we are actively working to solve the reported behaviour.
We will keep you posted.

Best,

**Comment by jenriquesoriano** [comment]
Dear @DeordD ,

maintenance is over.
The INSPIRE Reference Validator has returned to normal operation.
We have succesfully tested it using your data, please see:
https://inspire.ec.europa.eu/validator/v2/TestRuns/EID231b6496-066e-4463-8b4c-9ebb9b2860ed.html 

Thanks for your contribution.

Best regards,
