### ISSUE TITLE
CORS request did not succeed

### ISSUE THREAD

**Issue by reinij** [INSPIRE-MIF/helpdesk-validator#359]
Hi,

inspire-validator-2020.2 has static https links (e.g.  https://xx.xx.xx.xx/validator/js/lib/require.min.js) in landing page, which generates "Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource" in case if validator is installed using http.

As a consequence only blank page appears. Works "ok" on localhost, but I only have lynx as a browser in my server :-).

Regards,
Jari

**Comment by jenriquesoriano** [comment]
Dear @reinij

thank you for reporting this issue.
We will proceed to analyze it and keep you informed of the next steps in the process.

Best,

**Comment by carlospzurita** [comment]
Dear @reinij 

We would need some more feedback on this. Are you using the Docker image as it is? Or did you set up the instance on a production server, with a specific domain?

**Comment by reinij** [comment]
I've used Docker image as is.

docker login docker.pkg.github.com
docker run --name inspire-validator -d -p 80:8080 -v ~/etf:/etf docker.pkg.github.com/inspire-eu-validation/community/inspire-validator:2020.2

You may try it from here http://193.167.189.42/validator/

**Comment by carlospzurita** [comment]
Dear @reinij 

The image from Github is preparted to be served on localhost, for local testing. It is not intended to be used as it is on a production environment.

To access the validator on another IP, it needs to be configured on the .war file in the [release page](https://github.com/inspire-eu-validation/community/releases/tag/v2020.2) contained in the inspire-validator file, following the README.md file, and then build the docker image.

**Comment by carlospzurita** [comment]
Dear @reinij 

Did you have any feedback on the progress of the validator deployment in your premises?

**Comment by reinij** [comment]
Dear @carlospzurita 

As Docker instance is not anymore supporting IP-addresses (like in previous releases) without digging into war-file and compiling the source, I decided to give up.
