### ISSUE TITLE
Problem with code lists (input of URL)

### ISSUE THREAD

**Issue by DLList** [INSPIRE-MIF/helpdesk-validator#36]
Hello,

I have a problem with the ETF-Validator that I'd like to solve here.

I am currently busy developing a tool for transforming street data into INSPIRE Transport Network Structures. I have created several INSPIRE Features and tested them with the validator.

**My approach for creating INSPIRE-Data**

For example the FeatureType: _TransportNetwork_ . Transport Network has the attribute "_typeOfTransport_". According to the INSPIRE directive for this Attribute was created a CodeList. This means that I created an attribute named "_typeOfTransport.xlink_href_" and inserted the following entries (URL) there:
- "http://inspire.ec.europa.eu/enumeration/TransportTypeValue/air"
- "http://inspire.ec.europa.eu/enumeration/TransportTypeValue/cable"
- "http://inspire.ec.europa.eu/enumeration/TransportTypeValue/rail"
- "http://inspire.ec.europa.eu/enumeration/TransportTypeValue/road"
- "http://inspire.ec.europa.eu/enumeration/TransportTypeValue/water"

**Testing the DataSet with the Validator** 

The following error occurs when testing the data set with the validator:
_"**<<tn:typeOfTransport_xlink:href="http://inspire[...]/road"/>>** not allowed
cvc-type.3.1.1: Element 'tn:typeOfTransport' is a simple type, so it cannot have attributes, excepting those whose namespace name is identical to 'http://www.w3.org/2001/XMLSchema-instance&#39; and whose [local name] is one of 'type', 'nil', 'schemaLocation' or 'noNamespaceSchemaLocation'. However, the attribute, 'xlink:href' was found."_

**Alternative**

Instead, the following value can be entered as a Character for the attribute _typeOfTransport_ : **<<tn:typeOfTransport>>road</tn:typeOfTransport>** . The Validator allows this, but it's not INSPIRE compliant, is it?!
The same problem exists with attributes such as "_functionalClass_" (FunctionalRoadClass) or "_speedLimitMinMaxType_" (SpeedLimit)

**Question**

My question is: Is the error message when using URL's for codelists an error of Validator or should these attributes really be filled differently according to INSPIRE?

Best regards,
Dawid

**Comment by inakidiazdecerio** [comment]
Dear @DLList,

Thank you for your message. Please, could you attach the dataset that you have executed in the validator? We would need the file to test the error in the ETF.

Another question, could you tell us what test assertion you have executed in the ETF?

Regards.

**Comment by fabiovin** [comment]
Dear @DLList,

you are referring to an "enumeration" and not to a "codelist", so in this case, the allowed values for the attribute "`typeOfTransport`" are included in the xsd application schema. The values are therefore validated during the schema validation.
The correct encoding for this type of attribute is: `<tn:typeOfTransport>road</tn:typeOfTransport>`

Regards,
Fabio
