### ISSUE TITLE
Question in relation to WCS and the October 2020 milestone

### ISSUE THREAD

**Issue by iuriemaxim** [INSPIRE-MIF/helpdesk-validator#363]
Is it possible for a (raster/coverage) dataset provided via WCS to be tested and found compliant against the October 2020 milestone requirements? What data specification tests should be passed by the dataset served trough WCS?

**Comment by carlospzurita** [comment]
Dear @iuriemaxim 

As for now, the planned development for this release in relation to datasets is focused in GML format. No other format will be included on the next release of the validator. The only ETS related to WCS are the tests published for the service specification.

This question may also be worth posting on the INSPIRE forums about new requirements for the directive.

Kind regards.

**Comment by fabiovin** [comment]
Dear @iuriemaxim ,

it should be possible to test a dataset compliant to a coverage data theme and served by a WCS.
After selecting the relevant Conformance class, the option "Remote file (URL)" can be used to provide the relevant dataset.
For instance, at the moment, the conformance class for the "Gridded Existing Land Use" application schema is available in the [staging instance](http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/).

**Comment by iuriemaxim** [comment]
@carlospzurita Thank you for input. WCS is also providing data in GML format, not only in image format. However I do not think that a GML provided by WCS would comply with XSD files that were designed for GML served by a WFS. Most probably other XSD files would need to be designed for GML served by a WCS.
So probably a more detailed answer could be that the current tests are for GML files provided by a WFS, not for GML files provided by a WCS, but please confirm. Therefore most probably it is not yet possible to create a harmonised dataset served by a WCS in GML format untill new XSD schemas will be developed for datasets served trough WCS. In annex 2 and 3 there are some datasets that should be delivered by October 2020 (as coverage) and my questions are in relation with these deadlines that are aproaching, in order to know what we should do and what we can do, as we are required to do.

**Comment by iuriemaxim** [comment]
@fabiovin Thank you for valuable input. Can you please indicate the location of the XSD schema for the “gridded existing land use” and check that it was not designed for a WFS, but for a WCS by looking if the root element should not be wfs:FeatureCollection.

**Comment by dperezBM** [comment]
Dear all,

Since this issue had no interaction time ago, we decided to close it. Please feel free to open a new one if needed.

Thank you and best regards.
