### ISSUE TITLE
Conformance Class 'View Service WMS not working

### ISSUE THREAD

**Issue by pmendive** [INSPIRE-MIF/helpdesk-validator#364]
Hello

 Conformance Class View Service WMS is not working today?

I enter de service URL and initialization failure appears.

thanks

**Comment by carlospzurita** [comment]
Dear @pmendive 

We are working on restoring the service. We have setup a pinned [issue](https://github.com/inspire-eu-validation/community/issues/365) to reflect this and will be updated whenever it is solved.

In the meantime, we suggest that you use the [staging instance](http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/) for your tests.

**Comment by carlospzurita** [comment]
The validator is available again, and the WMS tests can be performed.

**Comment by pmendive** [comment]
solved and running ok

many thanks
