### ISSUE TITLE
Pre-defined WFS - Predefined stored query - base:SpatialDataSet in response

### ISSUE THREAD

**Issue by VeronikaKusova** [INSPIRE-MIF/helpdesk-validator#366]
Hi all,
 I have tested our WFS through Pre-defined WFS test and I have a question/issue related to Predefined Stored Query test case. There is an assertion “_Root element is **wfs:FeatureCollection**_” in the “_Invoke Stored Query with CRS, Language, SpatialDataSetIdentifier_” test step. 
But INSPIRE data set can be also served as a **base:SpatialDataSet**. I have read somewhere that this option is deprecated, but still valid. Could it be possible to change this assertion to check if the root element is wfs:FeatureCollection or base:SpatialDataSet?

Tested WFS service: https://services.cuzk.cz/wfs/inspire-AU-wfs.asp?service=WFS&request=getCapabilities 
Test report (from staging instance): 
[Test run on 16_24 - 03.08.2020 with test suite Conformance Class_ Download Service - Pre-defined WFS.html.zip](https://github.com/inspire-eu-validation/community/files/5016557/Test.run.on.16_24.-.03.08.2020.with.test.suite.Conformance.Class_.Download.Service.-.Pre-defined.WFS.html.zip)

Thank you.
Regards.

**Comment by carlospzurita** [comment]
Dear @VeronikaKusova 

Thank you for your suggestion. We are having an internal discussion about this topic and will get back to you with a decision if we are going to keep legacy support of this deprecated option.

**Comment by fabiovin** [comment]
Dear @VeronikaKusova,

sorry for the late reply.

I'm trying to replicate the error but the "Predefined Stored Query" test is now skipped because there are other failed/skipped tests.

Could you please verify?

Thanks,
Fabio

**Comment by dperezBM** [comment]
Dear @VeronikaKusova,

Could you please verify Fabio's comment and give us feedback?
Thanks in advance.

Best regards.

**Comment by dperezBM** [comment]
Dear all,

Since this issue had no interaction time ago, we decided to close it. Please feel free to open a new one if needed.

Thank you and best regards.
