### ISSUE TITLE
Possible invalid test in Conformance Class 7: 'INSPIRE Harmonised Spatial Data Services metadata

### ISSUE THREAD

**Issue by pandzel-zz** [INSPIRE-MIF/helpdesk-validator#367]
Attached metadata file fails validation of 'Conformance Class 7: 'INSPIRE Harmonised Spatial Data Services metadata' test suite at 'md sds-harmonised 7.1: Invocation Metadata' test with the message: 'srv:connectPoint/gmd:CI_OnlineResource/gmd:URL must be the same as Access Point url (req. 5.2)' 

Attached metadata has both URL's set to 'http://localhost' so it fulfills the requirement. When one of that URL's is changed to something else so they are different, then it passes validation.

I am using latest 2020.2 version of the test. I thing somewhere there the condition might be wrong, or the error message is misleading or I am wrong regarding the requirement. Could you clarify?
[{819B8811-14E1-41D5-B658-B022072AFCC3} (9).zip](https://github.com/inspire-eu-validation/community/files/5017488/819B8811-14E1-41D5-B658-B022072AFCC3.9.zip)

**Comment by carlospzurita** [comment]
Dear @pandzel 

Thank you for your issue and for providing your metadata.

We checked this issue and there was an error in the logical condition that was being tested on this requirement. We are changing this accordingly.

**Comment by carlospzurita** [comment]
We have published a fix for this issue on the [staging instance](staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/). Please let us know if everything is in order.

**Comment by pandzel-zz** [comment]
Everything looks correct now. Thank you.
