### ISSUE TITLE
New error in INSPIRE validator sinds this week

### ISSUE THREAD

**Issue by matthygr** [INSPIRE-MIF/helpdesk-validator#368]
subject: error indicated in INSPIRE validator contains text which isn't in the uploaded gml

- I generated a protectedsites gml (sample with 124 objects)
- this gml was loaded into the validator
- the report is  generated and shows this error:

> The dataset has 1 file(s) with errors for this assertion.
> XML document 'aanduidingsobj_sample_geharmoniseerd_20200806_1115.gml': The file has 2 schema validation error(s).
> XML document 'aanduidingsobj_sample_geharmoniseerd_20200806_1115.gml': http://inspire.ec.europa.eu/https-schemas/, 1:55: White spaces are required between publicId and systemId.
> XML document 'aanduidingsobj_sample_geharmoniseerd_20200806_1115.gml': http://inspire.ec.europa.eu/https-schemas/, 1:55: White spaces are required between publicId and systemId.

-the text 'http://inspire.ec.europa.eu/https-schemas/' can not be found in the validated gml
- this is de link to the test report https://inspire.ec.europa.eu/validator/v2/TestRuns/EIDe0227bd7-6c21-43e8-930e-b446c0f3ec8b.html

the gml I validated is 
[aanduidingsobj_sample_geharmoniseerd_20200806_1115.zip](https://github.com/inspire-eu-validation/community/files/5033909/aanduidingsobj_sample_geharmoniseerd_20200806_1115.zip)

Last week we had this gml validated: 
[geharm_selectie_aanduidobj_08_2020.zip](https://github.com/inspire-eu-validation/community/files/5034004/geharm_selectie_aanduidobj_08_2020.zip)
this was the report: https://inspire.ec.europa.eu/validator/v2/TestRuns/EID3e8d431c-325a-4828-9082-671819fe6958.html
if we rerun the validation of the same file now, this is the report https://inspire.ec.europa.eu/validator/v2/TestRuns/EID35be67b0-2dc3-41a6-9af1-9344c40c1b19.html

same kind of error occurs 

> The dataset has 1 file(s) with errors for this assertion.
> XML document 'geharm_selectie_aanduidobj_08_2020.gml': The file has 2 schema validation error(s).
> XML document 'geharm_selectie_aanduidobj_08_2020.gml': http://inspire.ec.europa.eu/https-schemas/, 1:55: White spaces are required between publicId and systemId.
> XML document 'geharm_selectie_aanduidobj_08_2020.gml': http://inspire.ec.europa.eu/https-schemas/, 1:55: White spaces are required between publicId and systemId.
>

**Comment by carlospzurita** [comment]
Dear @matthygr 

Thank you for your report and for providing all the attachments. We are aware of this problem related to the location of INSPIRE schemas, and we are working on a solution. As soon as it is ready, we will get back to you.

**Comment by MarcoMinghini** [comment]
Dear @matthygr, 
the problem should be solved now, can you please check and confirm?

Thank you.

**Comment by matthygr** [comment]
Dear @MarcoMinghini,

I reran the validaton and the file validated without errors.
Thanks a lot for the quick solution!
