### ISSUE TITLE
Validation of servicetype of Spatial data services in Dutch

### ISSUE THREAD

**Issue by bcosyn** [INSPIRE-MIF/helpdesk-validator#369]
Validation of a spatial data service fails due to the XML value "Raadpleegdienst"
Below the error of the validator with the recordset in attachment:
The metadata record set has 1 record(s) with errors for this assertion. 
XML document 'Test124.xml', record '9d075d6f-a85a-18fa-1f51-ced8-ef7c-5bce-a91eee54': Every service metadata record must have a service type that is one of the codes from the code list at http://inspire.ec.europa.eu/metadata-codelist/SpatialDataServiceType. Found: Raadpleegdienst. 
"Raadpleegdienst" is the Dutch value for view services
https://inspire.ec.europa.eu/metadata-codelist/SpatialDataServiceType/SpatialDataServiceType.nl.iso19135xml

[9d075d6f-a85a-18fa-1f51-ced8-ef7c-5bce-a91eee54.zip](https://github.com/inspire-eu-validation/community/files/5034423/9d075d6f-a85a-18fa-1f51-ced8-ef7c-5bce-a91eee54.zip)

**Comment by carlospzurita** [comment]
Dear @bcosyn 

Thank you for raising this issue. We need to check the multilingual support for the Conformance Class 3 in Metadata 2.0, and how the comparison to the values in the registry is performed. We will get back to you with more infomation.

Regards.

**Comment by carlospzurita** [comment]
Dear @bcosyn 

We have been discussing this issue, and by the [technical guidance](https://inspire.ec.europa.eu/sites/default/files/documents/metadata/inspire-tg-metadata-iso19139-2.0.1.pdf) for Metadata, the element SpatialDataServiceType values should be in English. You can check it out in section 4.2 for Network Services, and 4.3 for Invocable Spatial Data Services.

In this case, the metadata provided is erroneous and would no pass the validation. The text value should be set to the English version.
