### ISSUE TITLE
md-xml.a.1: Validate XML documents - Premature end of file

### ISSUE THREAD

**Issue by felnne** [INSPIRE-MIF/helpdesk-validator#37]
Attempting to validate [this file](https://gist.github.com/felnne/fd411703ce25ffa2ea4c42b6dab27fc0) as test run [EIDb2a1c772-465e-4d00-a1c9-24dca42ea0a1](http://inspire-sandbox.jrc.ec.europa.eu/etf-webapp//v2/TestRuns/EIDb2a1c772-465e-4d00-a1c9-24dca42ea0a1.html) fails the *XML encoding of ISO 19115/19119 metadata* Conformance Class, specifically test: [md-xml.a.1: Validate XML documents](http://inspire-sandbox.jrc.ec.europa.eu/etf-webapp//v2/TestRuns/EIDb2a1c772-465e-4d00-a1c9-24dca42ea0a1.html?lang=en#EID089adfa8-98d2-4c2c-bdce-bb6df34d10f9).

The validation error is:

```
The dataset has 1 file(s) with errors for this assertion.
XML document 'uk-pdc-test-record-iso-19115-inspire-gemini.xml': The file has 2 schema validation error(s).
XML document 'uk-pdc-test-record-iso-19115-inspire-gemini.xml': -1:-1: Premature end of file.
XML document 'uk-pdc-test-record-iso-19115-inspire-gemini.xml': -1:-1: Premature end of file.
```

The expression is:

```
(: TODO BaseX validation is incomplete and needs to be replaced by a custom validation module, see 'known limitations' :)
let $errors := (
	if ($validationErrors) then
		for $error in $validationErrors
		return local:addMessage('TR.validationError', map { 'text': $error })
	else
		for $file in $db
		  return 
			 if ($file/element()/@xsi:schemaLocation) then 
				let $start := prof:current-ms()
				let $infos := validate:xsd-info($file)
				let $duration := prof:current-ms()-$start
				let $logentry := local:log('Validating file ' || local:filename($file) || ': ' || $duration || ' ms')
				let $errors := count($infos)
				return
				  if ($errors>0) then
					 (local:addMessage('TR.invalidSchema', map { 'filename': local:filename($file), 'count': string($errors) }),
					  for $info in $infos return local:addMessage('TR.xmlSchemaError', map { 'filename': local:filename($file), 'error': $info }))
				  else ()
			 else
				for $record in $records[db:path(.)=db:path($file/element())]
				  let $id := $record/gmd:fileIdentifier/gco:CharacterString/text()
				  let $infos := validate:xsd-info($record)
				  let $errors := count($infos)
				  return
					 if ($errors>0) then
						(local:addMessage('TR.invalidSchemaRecord', map { 'filename': local:filename($record), 'id': $id, 'count': string($errors) }),
						for $info in $infos return local:addMessage('TR.xmlSchemaErrorRecord', map { 'filename': local:filename($record), 'id': $id, 'error': $info }))
					 else ())[position() le $limitErrors]
return
(if ($errors) then 'FAILED' else 'PASSED',
 local:error-statistics('TR.filesWithErrors', count($errors[@ref eq 'TR.invalidSchema'])),
 local:error-statistics('TR.recordsWithErrors', count($errors[@ref eq 'TR.invalidSchemaRecord'])),
 $errors[position() le $limitErrors])
```

Based on the *INSPIRE Profile based on EN ISO 19115 and EN ISO 19119* Conformance Class succeeding, I think this record is valid and should not fail *md-xml.a.1* for the reason given.

**Comment by josemasensio** [comment]
Dear @felnne,

Thank you for your comments. 

We're investigating the reason for the validation error in test " md-xml.a.1: Validate XML documents".

We think that the issue is in the formation of the XML file. It seems that the "validate:xsd-info" method returns errors. We are comparing with other totally compliant XML files with INSPIRE to detect where the error is.

We will come back to you with the possible solution.

Best regards.

**Comment by josemasensio** [comment]
Dear @felnne,

We have checked the issue and there is a problem with the schema location.
The metadata schema location is throwing some errors because of HTTP/HTTPS conversion. As a temporal fix for this error we recommend to modify the schema location to "http://www.isotc211.org/2005/gmd https://inspire.ec.europa.eu/draft-schemas/inspire-md-schemas-temp/apiso-inspire/apiso-inspire.xsd".

Pleae, try to modify it and run again the validation.

Regards.

**Comment by felnne** [comment]
Hi @bilbomaticaue,

Thanks for taking a look at this - I've rerun the test using that schema location but got the same result.

http://inspire.ec.europa.eu/validator/v2/TestRuns/EID41f3389d-db5b-48cb-aebf-597870263da3.html

The error reported is the same as before:

```
The dataset has 1 file(s) with errors for this assertion.
XML document 'uk-pdc-test-record-iso-19115-inspire-gemini.xml': The file has 2 schema validation error(s).
XML document 'uk-pdc-test-record-iso-19115-inspire-gemini.xml': -1:-1: Premature end of file.
XML document 'uk-pdc-test-record-iso-19115-inspire-gemini.xml': -1:-1: Premature end of file.
```

The expression is also the same:

```
(: TODO BaseX validation is incomplete and needs to be replaced by a custom validation module, see 'known limitations' :)
let $errors := (
	if ($validationErrors) then
		for $error in $validationErrors
		return local:addMessage('TR.validationError', map { 'text': $error })
	else
		for $file in $db
		  return 
			 if ($file/element()/@xsi:schemaLocation) then 
				let $start := prof:current-ms()
				let $infos := validate:xsd-info($file)
				let $duration := prof:current-ms()-$start
				let $logentry := local:log('Validating file ' || local:filename($file) || ': ' || $duration || ' ms')
				let $errors := count($infos)
				return
				  if ($errors>0) then
					 (local:addMessage('TR.invalidSchema', map { 'filename': local:filename($file), 'count': string($errors) }),
					  for $info in $infos return local:addMessage('TR.xmlSchemaError', map { 'filename': local:filename($file), 'error': $info }))
				  else ()
			 else
				for $record in $records[db:path(.)=db:path($file/element())]
				  let $id := $record/gmd:fileIdentifier/gco:CharacterString/text()
				  let $infos := validate:xsd-info($record)
				  let $errors := count($infos)
				  return
					 if ($errors>0) then
						(local:addMessage('TR.invalidSchemaRecord', map { 'filename': local:filename($record), 'id': $id, 'count': string($errors) }),
						for $info in $infos return local:addMessage('TR.xmlSchemaErrorRecord', map { 'filename': local:filename($record), 'id': $id, 'error': $info }))
					 else ())[position() le $limitErrors]
return
(if ($errors) then 'FAILED' else 'PASSED',
 local:error-statistics('TR.filesWithErrors', count($errors[@ref eq 'TR.invalidSchema'])),
 local:error-statistics('TR.recordsWithErrors', count($errors[@ref eq 'TR.invalidSchemaRecord'])),
 $errors[position() le $limitErrors])
```

**Comment by josemasensio** [comment]
Dear @felnne,

I see that you have more xsi:schemaLocation than mentioned yesterday. If you run
[the file as I menioned](https://github.com/inspire-eu-validation/community/files/3421955/uk-pdc-test-record-iso-19115-inspire-gemini.txt) you will not receive the error mentioned above. Please change the format to .xml, Github does not allow this format so I had have to convert to .txt.

Hope this helps.

Regards.

**Comment by fabiovin** [comment]
Dear @felnne,

I had a look at your xml and suggest you first try to validate the xml with an XML editor (e.g. XMLSpy) because there are several schema errors (e.g. incorrect values, elements in a wrong position). I think this can speed up your validation process with the INSPIRE Validator.

Best,
Fabio

![Screenshot (62)](https://user-images.githubusercontent.com/46569952/61713228-56699c80-ad58-11e9-9f4d-0748c4ae529c.png)

**Comment by felnne** [comment]
@bilbomaticaue, ah sorry I didn't realise you meant to remove the other schema locations as well.

@fabiovin - thanks, yes I noticed those and realised that test record is quite out of date and some of those issues have already been resolved.

I've updated the record and reapplied the schema location fix. That gave 3 validation errors related to element ordering.

http://inspire.ec.europa.eu/validator/v2/TestRuns/EIDfad7cc51-4379-4262-9877-edec4a83f8a1.html

I've fixed those and the record now validated successfully.

https://gist.githubusercontent.com/felnne/fd411703ce25ffa2ea4c42b6dab27fc0/raw/2f71ffb5d8517c81093cf4370e7806d83a828e14/uk-pdc-test-record-iso-19115-inspire-gemini.xml

In terms of the schema location element, I retested using my original value, but with just the location for `http://www.isotc211.org/2005/gmd` - `http://standards.iso.org/ittf/PubliclyAvailableStandards/ISO_19139_Schemas/gmd/gmd.xsd` - which failed with the premature end of file error.

http://inspire.ec.europa.eu/validator/v2/TestRuns/EID768d2c89-6f98-412f-84ab-ecf3305392ce.html

Form the guidance for that test it states:

> Validate each document against the schema(s) specified in the xsi:schemaLocation attribute using strict XML schema validation.
>
> Official XML schemas are currently found in two separate locations:
>
> * ISO repository for publicly available standards. The ISO 19139 schemas can be found at http://standards.iso.org/ittf/PubliclyAvailableStandards/ISO_19139_Schemas/.
> * OGC Schema repository. The ISO 19139 schemas are located at http://schemas.opengis.net/iso/19139/20070417/ and http://schemas.opengis.net/iso/19139/20060504/. The difference in the schemas is the GML version. The version dated "2007-04-17" uses GML 3.2.1, the version dated "2006-06-04" use GML 3.2.0, which was never approved or published by OGC. The major difference is that GML 3.2.0 schemas are defined in the namespace http://www.opengis.net/gml whereas GML 3.2.1 schemas are defined in the namespace http://www.opengis.net/gml/3.2.
The ISO AP schemas are located at http://schemas.opengis.net/csw/2.0.2/profiles/apiso/. The ISO AP schemas are bound to the ISO 19139 schemas dated "2006-06-04".
The schemas located in the ISO repository for publicly available standards are the same as the ISO 19139 schemas dated "2007-04-17".

Form what I tell using `http://standards.iso.org/ittf/PubliclyAvailableStandards/ISO_19139_Schemas/gmd/gmd.xsd` should work, as it's in the first path mentioned. Am I misunderstanding that?

I also tried to use my original schema location element, but with the Inspire version of GMD, that also failed.

http://inspire.ec.europa.eu/validator/v2/TestRuns/EIDfe1ee68e-9a2e-4798-9398-b9503b8f8590.html

More generally, does the validator support multiple entries in the schema location? As far as I can tell this is valid in XML ([e.g.](https://lists.w3.org/Archives/Public/www-xml-schema-comments/2000JulSep/0235.html)). We need to use an element with multiple values for other validators we use.

Thanks for all your help so far.

**Comment by fabiovin** [comment]
Dear @felnne,

the issue is related to the inability of the validator to handle an https redirection. So, the schemas available at the ISO (_http://standards.iso.org/ittf/PubliclyAvailableStandards/ISO_19139_Schemas/_) repository are no longer supported because of the address is automatically redirect from http to https.
Also the schema _http://schemas.opengis.net/csw/2.0.2/profiles/apiso/1.0.0/apiso.xsd_ is not supported because it imports schemas (gmd and gmx) from ISO repository.
For this reason, we created a slightly modified version (_https://inspire.ec.europa.eu/draft-schemas/inspire-md-schemas-temp/apiso-inspire/apiso-inspire.xsd_) which imports the same schemas (gmd and gmx) but from the OPENGIS repository.

In any case, the validator supports multiple entries in the schema location attribute.
So, instead of use the apiso-inspire.xsd schema, which imports all necessary schemas, you can declare them singularly in the schama location attribute (http://schemas.opengis.net/iso/19139/20070417/gmd/gmd.xsd, http://schemas.opengis.net/iso/19139/20070417/srv/1.0/srv.xsd, http://schemas.opengis.net/iso/19139/20070417/gmx/gmx.xsd).

**Comment by felnne** [comment]
Hi @fabiovin,

Ah ok - thanks for explaining that, makes sense.

Is it possible to amend the guidance on the *md-xml.a.1: Validate XML documents* test to mention that, as it currently mentions http://standards.iso.org/ittf/PubliclyAvailableStandards/ISO_19139_Schemas/ can be used.

Otherwise I'm happy to close this issue.

**Comment by fabiovin** [comment]
Hi @felnne,

thank you for your suggestion, we will consider rephrasing the "_md-xml.a.1: Validate XML documents_" test description.

In any case, please take into consideration that the transitional period for the migration from version 1.3 to version 2.0 will end on 19 December 2019.
So, probably after this date, the Metadata (TG version 1.3) validation will be no longer maintained/updated.
