### ISSUE TITLE
Problem with redirect to GEMET Spatial themes

### ISSUE THREAD

**Issue by MichaelOstling** [INSPIRE-MIF/helpdesk-validator#375]
When running our own instance of  reference validator I get an error message that the validator can not reach 
`http://inspire.ec.europa.eu/theme`

I understand the registry now runs on https so it should be 
`https://inspire.ec.europa.eu/theme`

I understand that code should automatically handle the redirect from server when it tries to call on http
but I know older http-clients did not handle this redirect.
I made an update in the rules
`\ets-repository-2020.2\metadata\2.0\datasets-and-series\ets-md-datasets-and-series-bsxets.xml`
and changed it to https
`let $inspireThemesCodeListURL := 'https://inspire.ec.europa.eu/theme'
`
And now the error message is not there anymore.

The question is:
Should this URL be changed to https in etf-repository 
or
can it be something wrong in our own setup of etf-validator ?

The same error do not show up when I validate at 
`http://inspire.ec.europa.eu/validator/about/`

Our own validator still runs on http: Maybe that could be an issue
`http://etf.geodatavalidering.se/etf-webapp`

![gemet](https://user-images.githubusercontent.com/6397818/90606417-1b0dfb80-e200-11ea-8c5e-e7c8e6e2b0b8.png)

**Comment by carlospzurita** [comment]
Dear @MichaelOstling 

How are you deploying this instance? Are you using the Docker image from the release, or are you using the .war file directly in an application server like Tomcat?

**Comment by MichaelOstling** [comment]
I'm deploying the WAR into a Tomcat instance

**Comment by carlospzurita** [comment]
The redirection from http://inspire.ec.europa.eu is handled automatically in the docker image. In case you want to use Tomcat directly on your host machine, you need to set up the redirection system. You can check the stack that is being used on the Dockerfile that accompanies the .war file.

For now, the ETS are not planned to be updated, but we intend to revisit this issue in the future.

**Comment by MichaelOstling** [comment]
I have changed URL in repository code and now it worls fine
