### ISSUE TITLE
Logic for defining if metadata corrensponds to TG 1.3 or TG.20

### ISSUE THREAD

**Issue by MichaelOstling** [INSPIRE-MIF/helpdesk-validator#381]
Workflow for estimation of MD TG version during monitoring is currently

1. classification (1.3 vs. 2.0) based on the same <gmd:useLimitation> filter
2. validation against the corresponding Conformance Class(es)
3. if the test is passed, the MD record is classified as initially determined
4. if the test is NOT passed, the test against the Conformance Class(es)
of the other TG is run
5. if this second test is passed, the MD record is classified as compiled
according to the TG tested later
6. if this second test is NOT passed, the MD record is classified back as
initially determined by the filter

I think this is not correct handling of this.
One of the main reasons for working on TG 2.0 was to correct the misuse of ISO 19115 in TG 1.3 UseLimitation was used 
for other purposes than it was originally aimed for.
By still reserving this element for usage in TG 1.3 blocks it from being used in TG 2.0

You can argue that IF all metadata is correct then it will validate according to TG 2.0 anyhow.
But if fails on just a single element it will instead validate on TG 1.3 (if useLimitation is used)

I think the element UseLimitations must be possible to use for its intended use, to report on technical limitation in metadata

I would suggest using a different element 
IF record has an 
`gmd:accessConstraints`
with an 
`gmd:otherConstraints`
that has an anchor that starts with 
`http://inspire.ec.europa.eu/metadata-codelist/LimitationsOnPublicAccess`

Then it must be TG 2.0

Right now it is impossible to validate properly metadata according to TG 2.0 if you want to use UseLimitations
It is only when it validates correctly that it will be validated according to TG 2.0
In all other cases it will be validated according to TG 1.3. That makes it useless for finding errors if you want to use UseLimitations in TG 2.0

Or might I have misunderstood the rules ?

Kind Regards
Michael Östling (SE)

**Comment by MarcoMinghini** [comment]
Dear @MichaelOstling, 
we appreciate your suggestion on the way MD TG 1.3 and 2.0 can be identified automatically, however this discussion is no longer relevant.

As agreed already some months ago, starting from the Monitoring and Reporting 2020, only MD TG 2.0 will be considered. This means that all metadata harvested from national catalogues will be (only) validated against the conformance classes of MD TG 2.0.

Together with the next release of the Validator (see the [release plan](https://github.com/inspire-eu-validation/community/tree/master/release%20strategy)), in mid-September we will also release an updated version of the [bulk validation tool](https://github.com/inspire-eu-validation/monitoring-bulk-validation-tool), which will only validate metadata against the conformance classes of MD TG 2.0.

**Comment by MichaelOstling** [comment]
OK fine,
It was actually the validation in **Bulk-validator** that was my main concern.
Then we wait for the new release of that 
Meanwhile we will erase all information on UseLimitations in the harvesting node.

/MIchael
