### ISSUE TITLE
at42-getcapabilities-layer-default-style missing required styles

### ISSUE THREAD

**Issue by Kate-Lyndegaard** [INSPIRE-MIF/helpdesk-validator#382]
Hi,

Could you please add `HH.HealthDeterminantMeasure.Default` and `US.EnvironmentalManagementSite.Default` to the list of tested default layer style names? 

We are also serving numerous "recommended styles". Have you given any thought to including the layer style names of "recommended styles" in the test? I can provide a list if that would be helpful.

Kind regards,
Kate

**Comment by carlospzurita** [comment]
Dear @Kate-Lyndegaard ,

We are looking into the WMS ETS to check what we need to modify. In the meatime, could you share with us an example endpoint to test the changes?

Also, if you can provide the list of layer styles it would be very much appreciated and we can have a discussion over them.

Thank you

**Comment by Kate-Lyndegaard** [comment]
Dear @carlospzurita,

I will check with our customer to determine whether I can share an endpoint. 

Here is a non-exhaustive list of recommended styles, extracted from various INSPIRE data specifications that we work with:

`CP.CadastralParcel.LabelOnReferencePoint`
`CP.CadastralParcel.ReferencePointOnly`
`CP.CadastralParcel.BoundariesOnly`
`EL.ContourLine.Master`
`EL.ContourLine.Ordinary`
`EL.ContourLine.Auxiliary`
`GE.GeologicUnit.Lithology` 
`GE.GeologicUnit.AgeOfRocks` 
`GE.GeologicFault` 
`GE.GeologicFold` 
`GE.GeomorphologicFeature.Natural` 
`GE.GeomorphologicFeature.Anthropogenic` 
`GE.Borehole` 
`GE.Aquifer.Type` 
`GE.Aquifer.MediaType` 
`GE.Aquiclude.ConstitutionOfAquiclude` 
`GE.Aquitard.ConstitutionOfAquitard` 
`GE.AquiferSystem.ConstitutionOfAquiferSystem` 
`GE.GroundWaterBody` 
`GE.ActiveWell` 
`HY.PhysicalWaters.Waterbodies.Persistence` 
`HY.PhysicalWaters.Waterbodies.Man.Made` 
`NZ.RiskZone` 
`NZ.HazardArea` 
`NZ.ObservedEvent - type of hazard` 
`NZ.ExposedElement` 

Kind regards,
Kate

**Comment by iuriemaxim** [comment]
It is quite clear that the layer names were not exhaustively checked as I noticed also this issue in the past.

I think that Portrayal sections in the TGs for all data themes should be read. looking only at HH and US:

According to [TG ](https://inspire.ec.europa.eu/id/document/tg/hh) the Layer names for HH are listed at page 89:

![image](https://user-images.githubusercontent.com/20813598/93320703-11d17800-f81a-11ea-9edd-f1a1180cbc3d.png)

According to [TG](https://inspire.ec.europa.eu/id/document/tg/us) the Layer names for US are listed at pages 120 & 121:

![image](https://user-images.githubusercontent.com/20813598/93321732-324e0200-f81b-11ea-82d9-474be6dd186b.png)

The full list of codelist values (such as that PoliceService)  are provided in Annex C at page 167, where first letter should be made in uppercase. There are quite many. Some are listed below:

![image](https://user-images.githubusercontent.com/20813598/93323333-23684f00-f81d-11ea-9100-bb94af5d7b80.png)

Iurie

**Comment by carlospzurita** [comment]
Dear @Kate-Lyndegaard 

We are modifying the ETS to cover the layer names with their default style included.

As for the recommended styles, for now it is not planned to include them in the validator. This styles are collected in the data specification for each theme, and it would rather complex to keeping them updated.

Also, is noteworthy the TG section on this topic

![imagen](https://user-images.githubusercontent.com/10537778/93333369-82c95d80-f823-11ea-8f01-762361d4a321.png)

As it is a recommendation, we are not checking it on the validator.

**Comment by Kate-Lyndegaard** [comment]
Dear @carlospzurita,

That sounds great. As we invest a lot of effort in maintaining the recommended styles, it would've been nice to have them recognized, however I understand your point:-)

I'm glad that the default styles can be added.

Kind regards,
Kate

**Comment by iuriemaxim** [comment]
PS.ProtectedSitesArchaeological, PS.ProtectedSitesCultural, PS.ProtectedSitesLandscape and many others related to Protected Sites should be also added. Please see https://github.com/INSPIRE-MIF/helpdesk-validator/issues/491

**Comment by iuriemaxim** [comment]
This is the list of harmonised layer names that are missing for Protected Sites Data Theme:

Based on https://inspire.ec.europa.eu/codelist/Natura2000DesignationValue:
PS.ProtectedSitesSpecialAreaOfConservation
PS.ProtectedSitesSpecialProtectionArea
PS.ProtectedSitesSiteOfCommunityImportance
PS.ProtectedSitesProposedSpecialProtectionArea
PS.ProtectedSitesProposedSiteOfCommunityImportance

Based on https://inspire.ec.europa.eu/codelist/IUCNDesignationValue:
PS.ProtectedSitesStrictNatureReserve
PS.ProtectedSitesHabitatSpeciesManagementArea
PS.ProtectedSitesManagedResourceProtectedArea
PS.ProtectedSitesNationalPark
PS.ProtectedSitesNaturalMonument
PS.ProtectedSitesProtectedLandscapeOrSeascape
PS.ProtectedSitesWildernessArea

Based on https://inspire.ec.europa.eu/codelist/DesignationSchemeValue:
PS.ProtectedSitesIUCN
PS.ProtectedSitesNatura2000
PS.ProtectedSitesRamsar
PS.ProtectedSitesNationalMonumentsRecord
PS.ProtectedSitesUNESCOManAndBiosphereProgramme
PS.ProtectedSitesUNESCOWorldHeritage
PS.ProtectedSitesEmeraldNetwork

Based on https://inspire.ec.europa.eu/enumeration/ProtectionClassificationValue:
PS.ProtectedSitesNatureConservation
PS.ProtectedSitesArcheaological
PS.ProtectedSitesCultural
PS.ProtectedSitesEcological
PS.ProtectedSitesLandscape
PS.ProtectedSitesEnvironment
PS.ProtectedSitesGeological

**Comment by fabiovin** [comment]
Dear all,

we relaxed the related test, so now if the WMS contains only harmonised layer names the test passes otherwise it passes with a manual check. This change is already implemented in the [staging instance]( http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/#start-tests). 

You can also see my comment here https://github.com/INSPIRE-MIF/helpdesk-validator/issues/39#issuecomment-789260465.

At the moment, the validator considers only the layers defined by IR and available in the INSPIRE Registry.
The additional layers defined in the TGs are not checked but could be used by data providers.

Please note that in some TGs the additional layers are listed together with the “official” ones - as for HH for which the TG defines an additional layer “HH.Event” to those defined by IR - and this could be lead to consider them as “official”.

I hope this clarifies.

**Comment by fredper-lm** [comment]
Dear all,

On request from Marco we provide feedback from Sweden on this discusson in addition to our mail response also here.

We (Sweden) are of the strong opinion that a view service ALSO could contain additional layers. 

From our point of view we agree on your examples: “e.g. those recommended by TGs or layers related to a not-harmonized dataset”, but in addition there is also another case where it already exists layers in the service as children to the harmonized layer. In that case we would like to provide the harmonized layer as a group layer.

It is important that the way of how these additional layers should be implemented is clearly defined so that there are obvious if there exists any limitations.

Kind Regards

Fredrik Persäter and Michael Östling

**Comment by nmtoken** [comment]
We discussed layer naming on the thematic clusters as below link, and decided that group layering was the way to go:

https://wayback.archive-it.org/12090/20161216055008/https://themes.jrc.ec.europa.eu/discussion/view/13952/layer-naming

**Comment by fabiovin** [comment]
Dear @nmtoken,
thank you for sharing this discussion, I think that the solution that we are going to implement (https://github.com/INSPIRE-MIF/helpdesk-validator/issues/39#issuecomment-797640000) is in line with what has been discussed.

**Comment by iuriemaxim** [comment]
@fabiovin even in the link provided by @nmtoken the layers have names are starting with the prefix of the data theme, such as for example "GE" followed by a dot "."

But to make an implementation that is allowing layer names such as "cbsprovincies"
and styles such as "cbsprovincies:ziekenhuisopnamen_dag_per_10000_inwoners"
if at least one harmonised layer name exist in the WMS, it is quite a big difference and not sustained by any text, neither by the INSPIRE Directive.

Therefore I cant really understand why you are so keen to implement the solution as proposed here https://github.com/INSPIRE-MIF/helpdesk-validator/issues/39#issuecomment-797640000 without looking at the text of the Directive as explained in the https://github.com/INSPIRE-MIF/helpdesk-validator/issues/39

**Comment by arantzaetxebarria** [comment]
Dear all

The style **HH.HealthDeterminantMeasure.Default** has been added to the list, in [Staging environment](http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/home/index.html), could you please verify? Thanks

Regards

**Comment by Kate-Lyndegaard** [comment]
Hi @arantzaetxebarria,

Thank you for adding the style. 

I tested using this service: https://haleconnect.com/ows/services/org.292.504afbe6-0069-411b-b69b-2aae3728f735_wms?SERVICE=WMS&REQUEST=GetCapabilities&VERSION=1.3.0

The layer at42-getcapabilities-layer-default-style test passes, however at39-getcapabilities-layer-name fails with a null pointer error and I don't know why that would be as the layer name is valid.

[Test run on 08 31 - 18.04.2023 with test suite Conformance Class View Service WMS.zip](https://github.com/INSPIRE-MIF/helpdesk-validator/files/11258769/Test.run.on.08.31.-.18.04.2023.with.test.suite.Conformance.Class.View.Service.WMS.zip)


Kind regards,
Kate

**Comment by arantzaetxebarria** [comment]
Dear @Kate-Lyndegaard 

Thank you for your feedback. It is a strange behaviour, we will analyse it in the next few days.

Regards

**Comment by arantzaetxebarria** [comment]
Dear @Kate-Lyndegaard 

Could you please try again? We have done some re-configurations in order to solve a redirection issue.
Excuse the inconvenience.

Regards

**Comment by Kate-Lyndegaard** [comment]
Hi @arantzaetxebarria,

I can confirm that the layer name error is no longer occurring.

Test: 
[Test run on 08 20 - 20.04.2023 with test suite Conformance Class View Service WMS.zip](https://github.com/INSPIRE-MIF/helpdesk-validator/files/11280513/Test.run.on.08.20.-.20.04.2023.with.test.suite.Conformance.Class.View.Service.WMS.zip)

Kind regards,
Kate
