### ISSUE TITLE
Difference in running Reference validator compare to latest classes in ETF on Git-hub

### ISSUE THREAD

**Issue by MichaelOstling** [INSPIRE-MIF/helpdesk-validator#383]
We are validating a ATOM-feed with the  reference validator 
`http://gis-services.metria.se/raafeed/PS.UNESCOWorldHeritage-topfeed.xml`

It has a dataset subfeed
`http://gis-services.metria.se/raafeed/PS.UNESCOWorldHeritage-subfeed.xml`

when validating this at 
https://inspire.ec.europa.eu/validator
we get no errors

But when we validate this in our own instance of validator where we deployed the latest ETF in a Tomcat-instance
http://etf.geodatavalidering.se/etf-webapp

We get errors reported on media types
Below two rules failes
Use INSPIRE media-types only
Get Inspire media subtype

It also reports file can not be accessed Root element "feed" exists
`Expected a XML response but the service returned a HTML page. Verify that the used endpoint URL is correct and accessible from outside your organization. If the service requires authentication and returned an authentication page, then check that the correct credentials are used by the validator or verify that upstream firewalls/proxy servers do not prevent access.
`

Can this be related to missmatching HTTP/HTTPS  in some way.

We also wonder if there are some instructions on how you can can copy the XQUERY-code from "test-instructions" and load it into Oxygen to better being able to debug the XQuery to understand whats failing in the validation.
There are some references in code that seems to be tightly coupled to the environment where the ETF is executed.
like
import de.interactive_instruments.xtf.*;   
SOAPUI_I.init(log,context,testRunner);   
import de.interactive_instruments.UriUtils;

Kind regards
Michael Östling (SE)

**Comment by carlospzurita** [comment]
Dear @MichaelOstling 

Thank you for raising this issue. We are investigating it to find out where the difference resides. 

Could you please share with us the Test Report generated by your instance on this service? We would also ask you to share the ETS version that you are deploying, along with the ETF version that you are using.

Kind regards.

**Comment by carlospzurita** [comment]
Dear @MichaelOstling 

In order to advance with this issue, we would need the Test Report generated by your instance, and the ETS version that you are deploying. Can you please provide us with this items?

Best.

**Comment by carlospzurita** [comment]
Dear @MichaelOstling 

Is this issue persisting on your side? We would like to have the Test Report generated by your instance, and the release version of the validator that you are using to perform the tests.

**Comment by carlospzurita** [comment]
Dear @MichaelOstling 

Did you have the opportunity to test this issue again on your premises with the new release? We would like to check the Test Report generated and see if the differences persisted.

**Comment by carlospzurita** [comment]
Dear @MichaelOstling 

Did you have the opportunity to test this issue again on your premises with the latest release?

**Comment by fabiovinci** [comment]
Since there is no iteration/response, the issue will be closed.
Please reopen the issue or open a new one if the problem persists.
