### ISSUE TITLE
To strict test on protocol for gmx:Anchor of Classification of spatial data services thesaurus

### ISSUE THREAD

**Issue by cirbgustaaf** [INSPIRE-MIF/helpdesk-validator#385]
I have not followed the proposed template, because it is about a small issue and it will be clear after reading my comment about the issue.

When using https and not http in the gmd:keyword/gmx:Anchor/@xlink:href attribute to define a keyword out of the Classification of spatial data services thesaurus  for a service metadata record, the validator throws next error:

![image](https://user-images.githubusercontent.com/2735892/92620955-8a3cb400-f2c3-11ea-888a-2517428caf0b.png)

Here you can find the xml snippet about the keyword:
`         <gmd:descriptiveKeywords>
            <gmd:MD_Keywords>
               <gmd:keyword>
                  <gmx:Anchor xlink:href="https://inspire.ec.europa.eu/metadata-codelist/SpatialDataServiceCategory/infoMapAccessService">Dienst kaarttoegang</gmx:Anchor>
               </gmd:keyword>
               <gmd:thesaurusName>
                  <gmd:CI_Citation>
                     <gmd:title>
                        <gmx:Anchor xlink:href="http://data.europa.eu/eli/reg/2008/1205">Verordening (EG) nr. 1205/2008 van de Commissie van 3 december 2008 ter uitvoering van Richtlijn 2007/2/EG van het Europees Parlement en de Raad betreffende metagegevens</gmx:Anchor>
                     </gmd:title>
                     <gmd:date>
                        <gmd:CI_Date>
                           <gmd:date>
                              <gco:Date>2008-12-03</gco:Date>
                           </gmd:date>
                           <gmd:dateType>
                              <gmd:CI_DateTypeCode codeListValue="publication"
                                                   codeList="https://standards.iso.org/iso/19139/resources/gmxCodelists.xml#CI_DateTypeCode">publication</gmd:CI_DateTypeCode>
                           </gmd:dateType>
                        </gmd:CI_Date>
                     </gmd:date>
                  </gmd:CI_Citation>
               </gmd:thesaurusName>
            </gmd:MD_Keywords>
         </gmd:descriptiveKeywords>`

When changing the protocol of the xlink:href to the http url, the error is not thrown anymore.

This is the url to the report with the error:

https://inspire.ec.europa.eu/validator//v2/TestRuns/EID58eba1c6-1e71-49a6-95a5-579528fbb563.html

Why the check is strict on the protocol and will the check be changed to support both protocols?
When executing for example http://inspire.ec.europa.eu/metadata-codelist/SpatialDataServiceCategory/infoMapAccessService (the url mentioned in the xlink:href) in the browser, it is forwarded to the https url.  So I don't understand why the https protocol is not supported in the check of the validator.

**Comment by MarcoMinghini** [comment]
Dear @cirbgustaaf,
the answer to your question is included in [this comment](https://github.com/inspire-eu-validation/community/issues/319#issuecomment-634107256) and more in general in the whole discussion you can find there. I hope this clarifies the situation.

However, although in this case you spotted the cause of the error, I think the error message is not sufficiently clear and should be changed to reflect the fact that http URIs should be used. @juanpelegrina can we add the same sentence we are currently adding in the dataset tests? Thank you.

**Comment by juanpelegrina** [comment]
Dear @cirbgustaaf 

As @MarcoMinghini suggested we have modified the error message to reflect that a HTTP URIs should be used. We have deployed the solution on [staging instance ](http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/). 

@cirbgustaaf, after reading the [discussion](https://github.com/inspire-eu-validation/community/issues/319#issuecomment-634107256) on issue 319 and the message we have added, could you tell us if more clarifications are needed? 

Regards
Juan

**Comment by cirbgustaaf** [comment]
@juanpelegrina For the message you have added, there are no more clarifications needed and accept the proposal, but I still promote to accept https URI's too.
