### ISSUE TITLE
Application schema - PLU - errors

### ISSUE THREAD

**Issue by apfelnymous** [INSPIRE-MIF/helpdesk-validator#389]
[filewithtest.zip](https://github.com/inspire-eu-validation/community/files/5224083/filewithtest.zip)

Hello I am experiencing the following errors regarding Application schema - PLU - codelist values:

XML document 'inspire_gml.gml', SpatialPlan 'GML_idm45916836918000': The property 'hilucsLandUse' shall be provided.
XML document 'inspire_gml.gml', SpatialPlan 'GML_idm45916836918000': The property 'regulationNature' shall be provided.

But neither of those properties belongs to the spatialplan feature, hows that happening ?

Any other error is legit to me and can be ignored here.
See my attached files please.

**Comment by fabiovin** [comment]
Dear @apfelnymous,
thank you for pointing out this.
You are right, the elements hilucsLandUse and regulationNature belong to the ZoningElement feature type.
There was an error in the XPaths in the [ATS](https://github.com/inspire-eu-validation/data-lu/blob/master/lu-plu-as/code-list-values.md), I correct them.

Dear @carlospzurita ,
could you please update them also in the ETS.
Thank you.

Fabio

**Comment by juanpelegrina** [comment]
Dear @apfelnymous 

we have implemented and deploy the solution on [staging](http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/). Could try and validate the solution?

Regards
Juan

**Comment by apfelnymous** [comment]
@juanpelegrina I run the test again, seems solved. Thank you.
[PLU_LEP.zip](https://github.com/inspire-eu-validation/community/files/5276686/PLU_LEP.zip)
