### ISSUE TITLE
The gmx:Anchor of thesaurus title is not used in the test on existence of one GEMET - INSPIRE theme

### ISSUE THREAD

**Issue by cirbgustaaf** [INSPIRE-MIF/helpdesk-validator#393]
When I look into the tests visible in the report generated by ETF when the radio button "All detail" is checked in the right upper corner, I am a little bit disappointed the gmx:Anchor/@xlink:href is not used for validation.

We are investing time in migrating next snippet:
`
               <gmd:keyword>
                  <gco:CharacterString>Landgebruik</gco:CharacterString>
               </gmd:keyword>
`
into the snippet:
`
               <gmd:keyword>
                  <gmx:Anchor xlink:href="http://inspire.ec.europa.eu/theme/lc">Landgebruik</gmx:Anchor>
               </gmd:keyword>
`
and most interesting next snippet:
`
               <gmd:thesaurusName>
                  <gmd:CI_Citation>
                     <gmd:title>
                        <gco:CharacterString>GEMET - INSPIRE themes, version 1.0</gco:CharacterString>
                     </gmd:title>
                     ...
                  </gmd:CI_Citation>
               </gmd:thesaurusName>
`
into the snippet:
`
               <gmd:thesaurusName>
                  <gmd:CI_Citation>
                     <gmd:title>
                        <gmx:Anchor xlink:href="http://inspire.ec.europa.eu/theme">GEMET - INSPIRE themes, version 1.0</gmx:Anchor>
                     </gmd:title>
                     ...
                  </gmd:CI_Citation>
               </gmd:thesaurusName>
`
Why nothing of the gmx:Anchor elements is used in the test?  Isn't it the reason to use URI's for the keyword so you don't need to check against all different languages for each keyword?  I understand we must be backward compatible, but we must have the possibility too, **to define the thesaurus title in another language like in dutch "GEMET - INSPIRE thema's, versie 1.0"**.  When we do this, the test fails now, because the title of the thesaurus is the main condition in the test.  My proposal is to test on gmx:Anchor first and if the gmx:Anchor is correct don't test on the thesaurus title anymore.  Also for the keyword, test first on the gmx:Anchor and when it is not available test on the gco:CharacterString.

Hereunder you can found the test done for the INSPIRE themes thesaurus:

let $levels := ('dataset', 'series')
let $THEMES_TITLE := '**GEMET - INSPIRE themes, version 1.0**'
let $messages :=
	(try{
		let $officialLanguages := ('bg','cs','da','de','et','el','en','es','fr','hr','it','lv','lt','hu','mt','nl','pl','pt','ro','sk','sl','fi','sv')
		let $inspireThemesCodeListURL := 'http://inspire.ec.europa.eu/theme'
		let $codeTitles := local:get-code-titles($inspireThemesCodeListURL,$officialLanguages)
		let $codeValues := local:get-code-list-values($inspireThemesCodeListURL)
		let $codes := ($codeTitles,$codeValues)
		for $record in $records
			let $rid := $record/gmd:fileIdentifier/*/text()
			let $relevantDescriptiveKeywordsBlocks := $record/gmd:identificationInfo[1]/gmd:MD_DataIdentification/gmd:descriptiveKeywords/gmd:MD_Keywords[gmd:thesaurusName/gmd:CI_Citation/gmd:title/*/text() = **$THEMES_TITLE**]
			return
			if (count($relevantDescriptiveKeywordsBlocks) = 0) then
				local:addMessage('TR.wrongKeywordFromINSPIREThemesTitle', map { 'filename': local:filename($record), 'id': $rid })
			else
				if ($relevantDescriptiveKeywordsBlocks[not(some $keyword in ./gmd:keyword/*/text() satisfies $keyword = $codes) ]) then
					local:addMessage('TR.noKeywordFromINSPIREThemes',  map { 'filename': local:filename($record), 'id': $rid, 'url': $inspireThemesCodeListURL, 'keywords': fn:string-join($relevantDescriptiveKeywordsBlocks/gmd:keyword/*/text(),'; ') })
				else ()
	} catch * {       						
		local:addMessage('TR.systemError',  map { 'text': $err:description }) 				
	}
	)[position() le $limitErrors]
return
(if ($messages) then 'FAILED' else 'PASSED',
 local:error-statistics('TR.recordsWithErrors', count(fn:distinct-values($messages//etf:argument[@token='id']/text()))),
 $messages)

**Comment by juanpelegrina** [comment]
@cirbgustaaf thanks for opening this issue

we are analyzing your proposal, could you confirm us that the Conformance Class you are testing is CC1 assertion 4: Inspire Theme Keyword? 

Regards
Juan

**Comment by cirbgustaaf** [comment]
@juanpelegrina 
I have used the Conformance Class 2b: INSPIRE data sets and data set series metadata for Monitoring.  I have not used Conformance Class 1: 'Baseline metadata for data sets and data set series', but hopefully the test against the existence of the Inspire Theme Keyword is the same to avoid different tests?

**Comment by juanpelegrina** [comment]
Hi @cirbgustaaf,
could you send us the metadata that you are testing?
Thanks
Juan

**Comment by cirbgustaaf** [comment]
@juanpelegrina 
This is the report when we use the correct thesaurus title:
https://inspire.ec.europa.eu/validator/v2/TestRuns/EIDe32f0ce2-f897-4b70-acac-24499ebdee2c.html
This is the report when we use a Dutch thesaurus title, but still the same gmx:Anchor
https://inspire.ec.europa.eu/validator/v2/TestRuns/EID59a6897d-fb1b-4f9a-b072-7c2b49b9a30a.html
The metadata I have used for the tests is in attachment.
[metadata.zip](https://github.com/inspire-eu-validation/community/files/5254726/metadata.zip)
Hopefully you can understand better the issue now, by looking to the only difference (the thesaurus title in Dutch), so no support for only gmx:Anchor?

**Comment by juanpelegrina** [comment]
Dear @cirbgustaaf

thanks for the suggestion, we have been having a close look at the Technical Guidance and states that the element shall contain the value "GEMET - INSPIRE themes, version 1.0", hence the [ATS](https://github.com/inspire-eu-validation/metadata/blob/2.0/datasets-and-series/inspire-theme-keyword.md) and the Validator behaves as expected.

We will keep your comment in mind for future changes, 

![image](https://user-images.githubusercontent.com/20069079/93978347-2662c280-fd7c-11ea-86e7-a74b2e197f69.png)

**Comment by cirbgustaaf** [comment]
@juanpelegrina Thanks for the snippet from the the TG, but the close look I had already done and I knew already that the validation is following the TG, but hopefully my issue is moving something in the TG the next time for supporting both, or a correct title when the gco:CharacterString is used, or a correct gmx:Anchor on the other hand, ohterwhise the gmx:Anchor is missing his goal for better and easier validation.

**Comment by AntoRot** [comment]
This is an issue already discussed in the 2017.4 MIG sub-group. There it was agreed that the title shall be "GEMET - INSPIRE themes, version 1.0" (as indicated in the TG Requirement 1.4) as that is the official name of the thesaurus (see the footer of https://www.eionet.europa.eu/gemet/en/inspire-themes/) expressed only in English without any other translation in other languages.

**Comment by cirbgustaaf** [comment]
@AntoRot Thanks for the feedback.  We will see what will happen in the next MIG sub-group discussions.  May be for the next TG.
