### ISSUE TITLE
Error 503 when trying to upload a file or start the test passing URL to the validated network resource

### ISSUE THREAD

**Issue by marcingrudzien** [INSPIRE-MIF/helpdesk-validator#394]
Hello,

I have deployed INSPIRE validator 2020.3 on Ubuntu 20.4 virtual machine with 8 GB RAM and 2 cores using Docker image following manual at https://github.com/inspire-eu-validation/community/releases/tag/v2020.3.

I admit that I am new to Docker and INSPIRE validator deployment.

The application starts without any issues. However, every time if I want to upload any file for testing (metadata or data) I receive 503 error and a message _"Upload failed
The system has currently insufficient resources to process this request. Please wait a few minutes and try again. If the problem persists, please contact the ETF system administrator of the server."_ Detailed servers response attached in response_metadata.txt file. 
[response_metadata.txt](https://github.com/inspire-eu-validation/community/files/5266441/response_metadata.txt)

Of course, there is no any test running on a validator machine.

Similarly, when I start to a test passing URL to the validated resource (e.g. endpoint of network service) immediately I receive an error _"Test Run initialization failure
The system has currently insufficient resources to process this request. Please wait a few minutes and try again. If the problem persists, please contact the ETF system administrator of the server."_ Detailed servers response attached in response_network.txt file. 
[response_network.txt](https://github.com/inspire-eu-validation/community/files/5266442/response_network.txt)

I have been in communications with our IT guys. They say that there no issues in the network layer, no traffic is being blocked and most likely is application or server issue.

Best regards,
Marcin

**Comment by juanpelegrina** [comment]
Dear @marty1357 

Thanks for opening the issue, we will analyze it and come back to you with a possible solution.

Regards
Juan

**Comment by marcingrudzien** [comment]
Just to inform you I've increased hardware resources on the machine to 16 GB RAM and 4 CPU cores, but it didn't solve the issue.

**Comment by carlospzurita** [comment]
Dear @marty1357 

This issue may be motivated by insufficient disk space available to the validator. Can you please access to the page `/validator/v2/status` on your validator host, and share the statistics that appear there?

**Comment by marcingrudzien** [comment]
{"name":"INSPIRE Reference Validator","status":"MAJOR","heartbeat":"1601382815112","willExpireAt":"1601382855112","version":"2.0.0-b191118T1324","uptime":"359690","allocatedMemory":"425211320","presumableFreeMemory":"14184335944","totalSpace":"1023303680","freeSpace":"789856256","cpuLoad":"0.004632","messages":["Less then 5 GB disk space available"]}

**Comment by marcingrudzien** [comment]
df -f command returns
Filesystem                               Size  Used Avail Use% Mounted on
udev                                     7.8G     0  7.8G   0% /dev
tmpfs                                    1.6G  1.3M  1.6G   1% /run
/dev/mapper/ubuntu--vg-ubuntu--lv--root  3.9G  2.6G  1.1G  71% /
tmpfs                                    7.9G     0  7.9G   0% /dev/shm
tmpfs                                    5.0M     0  5.0M   0% /run/lock
tmpfs                                    7.9G     0  7.9G   0% /sys/fs/cgroup
/dev/mapper/ubuntu--vg-ubuntu--lv--home  976M  223M  687M  25% /home
/dev/sda2                                976M  197M  713M  22% /boot
/dev/mapper/ubuntu--vg-ubuntu--lv--var   2.0G  1.7G  197M  90% /var
/dev/mapper/ubuntu--vg-ubuntu--lv--log   976M  183M  726M  21% /var/log
/dev/loop1                                31M   31M     0 100% /snap/snapd/9279
/dev/loop0                                71M   71M     0 100% /snap/lxd/16922
/dev/loop3                                55M   55M     0 100% /snap/core18/1880
/dev/loop2                                56M   56M     0 100% /snap/core18/1885
/dev/loop4                                72M   72M     0 100% /snap/lxd/16099
/dev/loop5                                30M   30M     0 100% /snap/snapd/8790
tmpfs                                    1.6G     0  1.6G   0% /run/user/1002

**Comment by carlospzurita** [comment]
You would need to provide more disk space for this machine. None of the partitions present there have enough space. The ETF needs at least 5 GB to store all test objects and test run's related files. The insuficient resources would persist until enough space is provided.

**Comment by marcingrudzien** [comment]
Thank you for your support. 
Does a specific partition (e.g. /var) should have more disk space available or it doesn't matter which one?

**Comment by carlospzurita** [comment]
I would recommend to extend the partition for `/home`, and ensure that the location `~/etf` from the command `docker run --name inspire-validator -d -p 8080:8080 -v ~/etf:/etf docker.pkg.github.com/inspire-eu-validation/community/inspire-validator:2020.3` is under the home directory.

**Comment by marcingrudzien** [comment]
Extending /home partition did the trick.
Once again thank you for your support.
