### ISSUE TITLE
https://inspire.ec.europa.eu/validator/#monitor-test-run?id=EID075d4942-ec5a-4847-ba7e-36a87c19391c

### ISSUE THREAD

**Issue by krimar58** [INSPIRE-MIF/helpdesk-validator#395]
Hallo!

I have a problem with one of my GML-files. It uploads and the monitor shows the validation running. When the tests are done the monitor informs us that the test job is done, but no report is given:
![image](https://user-images.githubusercontent.com/23475606/93997470-b9f3bd80-fd93-11ea-99ae-cd563559ab8a.png)

I'm attaching the file. It is from the schema ge_gp
[ge_gp50st_4258.zip](https://github.com/inspire-eu-validation/community/files/5267261/ge_gp50st_4258.zip)

Best regards 
Kristina Martinelle

Swedish Geology Service
kristina.martinelle@sgu.se

**Comment by juanpelegrina** [comment]
Dear @krimar58, 

Could you tell us what Conformance Class are you testing against? we are trying to reproduce the issue. 

Thanks
Juan

**Comment by krimar58** [comment]
Thanks fpr your rapid resopnse. <br/>
I'm running all GML-file Conformance Classes:<br/>
![image](https://user-images.githubusercontent.com/23475606/94015710-845bce00-fdad-11ea-9424-ea21fc54b10b.png)

**Comment by carlospzurita** [comment]
Dear @krimar58 

We have made a test in our staging instance and you are right that the test report is not generated automatically once the test stops. However, after a while the report appears in the Test Reports section of the validator. We are still checking why is taking so long, but at least the validation is not lost.

**Comment by krimar58** [comment]
Greate! Approximately how long did you have to wait?

**Comment by carlospzurita** [comment]
We waited between 5 and 10 minutes, but we are not 100% sure of the exact time mark for the test report to be available. 

We are doing some tests with your GML file to check where the problem comes from. One possible explanation may be the length of feature's geometries, that the Test Driver takes too long to process them, but we are still checking this.

**Comment by krimar58** [comment]
We have not been able to get at report yet. Are you able to send us one it would be great.

**Comment by carlospzurita** [comment]
Dear @krimar58 

We have been trying to generate again the report but it seems now that it is impossible to do so. We got once the HTML, but never again.

The test however is finished and marked as FAILED, looking into the internal files of the validator. The rendering of the TestReport is the one causing problems. This may be attributed to the large features that is contained in the file. There is no error in the validator overall, is just that the reques gets a timeout.

Can you generate a sample file, following your same procedure, but with a much more small feature? To prove that at least there is nothing inherently wrong with the file syntax.

**Comment by krimar58** [comment]
Hello @carlospzurita 
Sorry for the delay of my response. We have had a big deadline to work towards :) I've tried again to validate my old file and the file I'm sending you now, with the same result as earlier. Both files have been successfully  validated in Oxygen.

Best regards 
Kicki Martinellle
[GE_Geophysics_SGU_epsg4258_samle_every200.zip](https://github.com/inspire-eu-validation/community/files/5545707/GE_Geophysics_SGU_epsg4258_samle_every200.zip)

**Comment by fabiovinci** [comment]
Dear @krimar58,

do you still have the reported errors?

**Comment by fabiovinci** [comment]
Dear @krimar58,

since there are no interactions, I will close the issue.

Please reopen it or open a new one if the error persists.
