### ISSUE TITLE
Natural Risk Zones - Validation Error - Conformance Class 'Application Schema, Natural Risk Zones'

### ISSUE THREAD

**Issue by robblis** [INSPIRE-MIF/helpdesk-validator#397]
We are looking for some help to resolve a validation error we are getting with our Natural Risk Zones model.

We see the following error dealing with the Risk zone theme-specific requirements.

_Check that if a RiskZone is associated with a HazardArea, the RiskZone and the HazardArea shall overlap.
Messages
XML document 'service.xml', RiskZone 'nzRiskZoneS.801': The constraint 'RiskZone and the HazardArea shall overlap' is violated._ 

When looking at the expression we believe that the following part of the expression is failing...

_else if (exists($feature/nz-core:source/@xlink:href) and not(substring($feature/nz-core:source/@xlink:href, 2) = $features_hazard)) then
				local:addMessage('TR.constraintViolation', map { 'filename': local:filename($feature), 'featureType': local-name($feature), 'gmlid': string($feature/@*:id), 'constraint': 'RiskZone and the HazardArea shall overlap', 'additionalInfo':''})_

Here is the nz-core:source node xml snippet from our GML

_<nz-core:source xlink:href="http://myserver.com/arcgis/rest/services/NZTest/MapServer/exts/InspireFeatureDownload/service?SERVICE=WFS&VERSION=2.0.0&REQUEST=GetFeature&STOREDQUERY_ID=urn:ogc:def:query:OGC-WFS::GetFeatureById&id=nzHazardAreaS.701"/>_

We're not sure what the Validator is looking for in this case. Thanks for any help.

**Comment by carlospzurita** [comment]
Dear @robblis 

Thanks for opening the issue, we are having more detailed look to the Conformance Class. In the meantime, could you provide us with the GML you are validating?

Kind regards

**Comment by robblis** [comment]
Dear @carlospzurita 

I've attached the GML we are trying to validate.

Thank you for your help,
Robert
[NZ_RiskZones.zip](https://github.com/inspire-eu-validation/community/files/5294036/NZ_RiskZones.zip)

**Comment by carlospzurita** [comment]
Dear @robblis 

A fix for this issue has been published on the [staging instance](http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/). Please, check it out and test if everything is corect.

**Comment by robblis** [comment]
Hi @carlospzurita 

We just tested the NZ RiskZone on the staging validator and the test was successful.

Thanks for fixing the issue.

Robert
