### ISSUE TITLE
ETF Status page

### ISSUE THREAD

**Issue by MarcoMinghini** [INSPIRE-MIF/helpdesk-validator#4]
Currently, the Status page is more relevant for ETF admin users than for common ETF users.

Thus, the page may be edited so that the displayed information is more relevant for the ETF users and in particular can inform them about the status of the disk space (and thus, the chance that their test will be successfully performed). Some alternative messages can be displayed, such as:
- Low work load, service ready for use
- Heavy work load, tests run will be queued (in case of low memory or threads availables)
- Performing data clean up, service disabled (in case of low disk space)

In addition, the _Loaded components_ may also not be displayed.

It is also worth monitoring the actual use of the Status page.

What are your views, comments and suggestions about this potential improvement? What messages regarding the resources consumption that might be more useful for the users?

**Comment by thijsbrentjens** [comment]
As said in the webconf: as far as I know the status page is not used a lot. Maybe it is useful to know how busy the server is, I can imagine that. But his could also be a small text block somewhere on the page to start tests (instead of a separate status page).

**Comment by MarcoMinghini** [comment]
[2017.4 meeting 2018-11-15] this improvement proposal is of minor importance and low priority - the _Status page_ is only rarely checked by users.

**Comment by AntoRot** [comment]
I agree too. I never used the status page and  I think too that it is little used.

**Comment by IGNCNIG** [comment]
We never used this page, it is a page for Admin user, it is not useful for user.

**Comment by MarcoMinghini** [comment]
The Status page includes also the information about tests currently running but not yet completed (when this happens), see for example this screenshot:

![status_page_runningtests](https://user-images.githubusercontent.com/14758434/53575269-7dd58800-3b71-11e9-967b-0a6138a66b34.png)

In the hypothesis of removing the Status page, it may be useful to keep this information available for the ETF users. Actually, this information is already available also in the Test reports page, where the test(s) currently running but not yet completed are included in the list (ordered according to the time they were started) and written in black font, see this screenshot:

![status_page_runningtests_current](https://user-images.githubusercontent.com/14758434/53575462-e15fb580-3b71-11e9-9a5a-afc765df9bd5.png)

A proposal to make this information more visible is to move the test(s) currently running but not yet completed **at the top of the list**, by also preserving the text "Running (XX%)" in front of it.

What are your comments on this?

**Comment by alitka** [comment]
Implementation or realisation of a "status notification" of a running test in the German GDI-DE Testsuite:
![ETF_StatusCode_1](https://user-images.githubusercontent.com/29542183/61352551-fb263e80-a86d-11e9-8e73-86f9e89dfe41.PNG)
![ETF_StatusCode_2](https://user-images.githubusercontent.com/29542183/61352563-05483d00-a86e-11e9-9a47-933299c38557.PNG)

**Comment by MarcoMinghini** [comment]
In the new Validator UI, which has been recently included in the [staging instance](http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/), the Status page was disabled.

Thank you for your contribution to this discussion.
