### ISSUE TITLE
INSPIRE-View-Service check-layer-default-style

### ISSUE THREAD

**Issue by mattenp** [INSPIRE-MIF/helpdesk-validator#400]
Hi,

I think that some styles have not been considered which are also missing in the TC, e.g. Transport Networks - Technical Guidelines.

What about

TN.WaterTransportNetwork.TrafficSeparationSchemeSeparator.Default, TN.WaterTransportNetwork.TrafficSeparationSchemeCrossing.Default
TN.WaterTransportNetwork.TrafficSeparationSchemeLane.Default
TN.WaterTransportNetwork.Buoy.Default
TN.WaterTransportNetwork.PortNode.Default  ?

I can't use styles from the CommonTransportNetwork for such features.

Best regards,

Matthias

**Comment by carlospzurita** [comment]
Dear @mattenp 

Thank you for raising this issue. We are aware of these problems in the View Service tests, and we are working on the review and inclusion of all missing styles from the specifications of each theme. You can follow the discussion on #382 .

**Comment by mattenp** [comment]
Dear carlospzuritaok, 

thanks a lot.

Best regards,
Matthias

**Comment by fabiovin** [comment]
Dear @mattenp,

it seems you are proposing some additional styles not present in the Technical Guidance, so they cannot be added in the Validator, but require a modification of the TG.

For this reason, I suggest you open a discussion in the [INSPIRE Community Forum](https://inspire.ec.europa.eu/forum/).

Regards,
Fabio
