### ISSUE TITLE
Code list http://inspire.ec.europa.eu/theme cannot be accessed

### ISSUE THREAD

**Issue by moeidu** [INSPIRE-MIF/helpdesk-validator#401]
I know, this error was discussed in other threads and is already closed (problem of the reverse proxy) but I still get the error:

![grafik](https://user-images.githubusercontent.com/72134044/94675958-dc00b900-031a-11eb-8ce0-a0a575e8e803.png)

**Comment by carlospzurita** [comment]
Dear @moeidu 

Are you getting this from a local deployment using Docker, or have you deployed the validator in a server on your own?

**Comment by moeidu** [comment]
Hallo Carlos, thanks for the quick reply. I use the german 'GDI - Testsuite' (https://testsuite.gdi-de.org/#/quicktest). In my case I did a quicktest by uploading a file without login.

**Comment by carlospzurita** [comment]
Dear @moeidu 

It seems that this is a customized version of the INSPIRE validator. We need to know the technical details of the deployment of this instance, how it has been created, to be able to assist you with the proxy issue.

**Comment by g-weber** [comment]
Hi all, the issue is already reported in #311 where also all technical details about the installation are provided but a solution proposal is still pending.
