### ISSUE TITLE
Can't get test results for Download Service WFS 2.0 test. 

### ISSUE THREAD

**Issue by fhoubie** [INSPIRE-MIF/helpdesk-validator#403]
Since beginning of afternoon, I can't get a results for a Download Service WFS 2.0 test. 

> 02.10.2020 13:57:24 - Releasing resources
> 02.10.2020 13:57:25 - Project Properties: 
> 02.10.2020 13:57:25 - testRunTags -  
> 02.10.2020 13:57:25 - endpt.GetCapabilities.Get -  
> 02.10.2020 13:57:25 - serviceEndpoint - http://sdidemo.intergraph.pl/WFS_INSPIRE/Service.svc/get?ACCEPTVERSIONS=2.0.0&request=GetCapabilities&service=WFS&VERSION=2.0.0 
> 02.10.2020 13:57:25 - username -  
> 02.10.2020 13:57:25 - authUser -  
> 02.10.2020 13:57:25 - authMethod - basic 
> 02.10.2020 13:57:25 - TestRunTask initialized
> 
> Connection to test runner lost. The test could have been canceled without generating  a report or the internet connection to the web application has been lost!

If it starts, I get this message above with those messages in the web console
![image](https://user-images.githubusercontent.com/3958446/94931996-c3360600-04c8-11eb-97b7-ef7a98022f2d.png)

Or it does not even start.
Any idea ? I've tried with Firefox and Edge.

**Comment by carlospzurita** [comment]
Dear @fhoubie 

It seems that test runs that are newly created are unable to start and they are holding the queue, resulting in this messages. We are going to look into what is preventing this Test Runs to progress.

**Comment by carlospzurita** [comment]
We are reloading the validator instance to restore the service

**Comment by carlospzurita** [comment]
We have restored the service. Can you try to submit your test runs and see if you get the results?

**Comment by fhoubie** [comment]
Dear @carlospzurita, the service is working now. Thanks
