### ISSUE TITLE
codelist vs codeList (similar to http vs https)

### ISSUE THREAD

**Issue by iuriemaxim** [INSPIRE-MIF/helpdesk-validator#407]
After the http vs https issue https://github.com/inspire-eu-validation/community/issues/319 & https://github.com/inspire-eu-validation/community/issues/334, while testing the ETF for EF https://github.com/inspire-eu-validation/community/issues/399 I found that in the TGs, both cases are found to point to the INSPIRE registry:
- http://inspire.ec.europa.eu/codelist (lowercase)
- http://inspire.ec.europa.eu/codeList (camelCase)

However both URLs are suggesting that the correct version is the lowercase one, even if there are two words "code" and "list"

![image](https://user-images.githubusercontent.com/20813598/95245405-c0664880-081b-11eb-9bd5-1c9cd4d555d4.png)

The webserver is case sensitive, as http://inspire.ec.europa.eu/Codelist will indicate that no page was found, so it is clear that  both codelist and codeList are currently accepted by the INSPIRE Registry for a certain reason.

The "codelist" word does not exist, so there are two words: "code" and "list", which suggest that the camelCase version should be the correct version: codeList.

![image](https://user-images.githubusercontent.com/20813598/95248664-4a181500-0820-11eb-90cf-ee0c68c455e7.png)

My questions are:

1. Are both http://inspire.ec.europa.eu/codelist and http://inspire.ec.europa.eu/codeList accepted to be provided in a dataset for any INSPIRE registry record (as the INSPIRE Registry accept both) or is case by case or only the lowercase is correct or only the camelCase is correct?

2. More specific, as in Annex C from the EF TG is used the camelCase, should be interpreted as an error and the lowercase should be used, or the camelCase is the correct one, or both versions are correct?
![image](https://user-images.githubusercontent.com/20813598/95245669-176c1d80-081c-11eb-94d1-62c4487927f6.png)

3. How the ETF should cope with codelist vs codeList:
- case by case to accept either codelist or codeList depending on the TG
- only codelist to be considered correct
- the correct version is codeList as there are two words, code and list
- or both camelCase and codelist to be accepted

**Comment by df-git** [comment]
Dear @iuriemaxim,
Thank you for your message.
The URL in camel case is an old and wrong URL that was available when the INSPIRE registry was firstly released.
It has then been corrected to the lowercase one. The camel case version has been kept in order to guarantee the backward compatibility.

The URIs to be considered as correct are always indicated in the "ID" field of the INSPIRE Registry website.

![image](https://user-images.githubusercontent.com/29379252/95314296-686a2900-0891-11eb-8360-b4567fae0b19.png)

**Comment by iuriemaxim** [comment]
@df-git Thank you for clarifications. Probably a better implementation would be to redirect requests with code list being written in camelCase to URLs written in lower case. In such way at least will be less ambiguous.

@carlospzurita This can be marked as discussion, as other users may face the same problem and dilema.

**Comment by iuriemaxim** [comment]
@df-git I arrived to this issue with codelist vs codeList while testing the EF data theme in the validator (https://github.com/inspire-eu-validation/community/issues/399)

But with this occasion I found that the INSPIRE registry responds with an average of 3.7 seconds per request which is 25 times slower than another codelist, as can be seen in the images below. Can this time response be improved?

26' 44 seconds for 434 INSPIRE Registry URLs (3.7 second/URL)
3' 31 seconds for 1449 URLs from other sites (0.14 seconds/URL)

![image](https://user-images.githubusercontent.com/20813598/95350961-61f7a380-08c9-11eb-9909-a65db5c25ff9.png)

![image](https://user-images.githubusercontent.com/20813598/95351497-f530d900-08c9-11eb-957f-e5285ad59b4b.png)

Also, by checking the INSPIRE registry URL several times, continuously, the server is not always responding in due time as can be seen in the image below from the INSPIRE validator that is indicating that the URL cannot be retrieved, even if it was retrieved many times, but slow. So I guess that in average there are 3.7 seconds, but sometimes there are more than 5 seconds and the INSPIRE validator is interpreting this as it cant retrieve the URL.

![image](https://user-images.githubusercontent.com/20813598/95371727-46999200-08e3-11eb-9409-4e29ec04533b.png)

**Comment by df-git** [comment]
Dear @iuriemaxim,
Thank you for your message.
The performance issues related to the INSPIRE registry will be solved once the new version of the service will be deployed (probably in late spring 2021).

Best regards,
Daniele on behalf of the INSPIRE support team
