### ISSUE TITLE
md sds-invocable 5.1 Spatial Data Service Type

### ISSUE THREAD

**Issue by mattenp** [INSPIRE-MIF/helpdesk-validator#409]
Hi,

I can't understand TG Requirement 5.1 concerning to TG Requirement 3.5.
Could you please show me an example?

Best regards,

Matthias

**Comment by fabiovin** [comment]
Dear @mattenp,
the TG Requirement 3.5 is a common requirement and specifies how the Spatial Data Service type shall be encoded, i.e. using the metadata element _srv:serviceType/gco:LocalName_.
Then the requirements 4.1 and 5.1 specify the values that shall be used for Network Services and Invocable Spatial Data Services respectively.

Regarding the examples, we will provide one for Invocable Spatial Data Services asap.

Regards,
Fabio

**Comment by mattenp** [comment]
> 
> 
> Dear @mattenp,
> the TG Requirement 3.5 is a common requirement and specifies how the Spatial Data Service type shall be encoded, i.e. using the metadata element _srv:serviceType/gco:LocalName_.
> Then the requirements 4.1 and 5.1 specify the values that shall be used for Network Services and Invocable Spatial Data Services respectively.
> 
> Regarding the examples, we will provide one for Invocable Spatial Data Services asap.
> 
> Regard

**Comment by mattenp** [comment]
Hi @fabiovin ,

thanks for your help.


Best regards,

Matthias

**Comment by aytacaraz** [comment]
First off all, I should understand what is exactly different with;

• Not invocable SDS 
• Invocable SDS
• Interoperable SDS
• Harmonised SDS 
• Network services 

than we can speak about, validation tests... 
if somebody have a proper documentation, i will be very thankfull..

Best Regards

**Comment by fabiovin** [comment]
Hi @mattenp,
you can find an example of metadata for Invocable Spatial Data Services [here](https://github.com/inspire-eu-validation/community/blob/master/examples/Invocable_SDS_metadata_2.0_example.xml).

Regards,
Fabio

**Comment by mattenp** [comment]
Thanks a lot @fabiovin !

Best regards,
Matthias
