### ISSUE TITLE
View Service WMS validation fails schemalocation test, while required schema is mentioned

### ISSUE THREAD

**Issue by thijsbrentjens** [INSPIRE-MIF/helpdesk-validator#41]
See this Capabilities document https://geodata.nationaalgeoregister.nl/natura2000/wms?&request=GetCapabilities&service=WMS
The xsi:schemaLocation contains a reference to the schema for the INSPIRE vS namespace:
```
http://inspire.ec.europa.eu/schemas/inspire_vs/1.0  http://inspire.ec.europa.eu/schemas/inspire_vs/1.0/inspire_vs.xsd
```
Note that there are 2 whitespaces in the declaration between the namespace and schema location URI. Maybe this fails the test. I tried to find out if W3C has a required format (e.g. only one whitespace), but didn't find it directly. I _think_ the reference to the schema is okay.

Could the test be changed to account for this?

Even if the declaration in xsi:schemaLocation is not correct, failing this check should _not_ stop the rest of the tests to be ran. The xsi:schemaLocation attribute is a hint according to the W3C. Making it a blocking requirement is too strict in my opinion. Or is there another reason why the tests are stopped?

- [x] a description of the steps to reproduce your issue
1. go to http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/
1. select View Service - WMS tests
1. enter this URL: https://geodata.nationaalgeoregister.nl/natura2000/wms?&request=GetCapabilities&service=WMS1. run the test
1. tests are stopped, because schema validation fails

- [x] the name of the Test that failed or better: change the `Level of Detail`
in the Report by clicking on `All Details`, then scroll down to the failed test
and copy the Link on the right-hand side of the `Assertion URI`
http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/v2/TestRuns/EID3a27b99b-c43b-4d6b-84d6-168c75909fb4.html?lang=nl#EID5442dea7-016a-1000-cd84-e63d8f9e40b4

- [x] the URL of your service / the file you have uploaded or referenced (as
an attachment). 
https://geodata.nationaalgeoregister.nl/natura2000/wms?&request=GetCapabilities&service=WMS

**Comment by inakidiazdecerio** [comment]
Dear @thijsbrentjens,

Thank you for your explanations. We have included this issue for discussion during next subgroup meeting.

Regards.

**Comment by MarcoMinghini** [comment]
Dear @thijsbrentjens,
we are investigating the issue to check if the reason why validation stops is actually due to the 2 whitespaces, or if there is another problem (I agree that the validation should not stop).

**Comment by danielnavarrogeo** [comment]
Dear @thijsbrentjens,

Thank you for your comments. We have solved the error related with the two spaces.

The reason why the test actually stops is because the server answer a 500 http error code when a request is done without the service parameter:
https://geodata.nationaalgeoregister.nl/natura2000/wms?&request=GetCapabilities

The correct behaviour shall be to returned an exception like in the following case:
http://ovc.catastro.meh.es/cartografia/INSPIRE/spadgcwms.aspx?REQUEST=GetCapabilities

We are working on the best way to handle this situation.

Regards.

**Comment by josemasensio** [comment]
The two whitespaces issue is solved. The service parameters issue is related to [40](https://github.com/inspire-eu-validation/community/issues/40). We mark this issue as solved.
