### ISSUE TITLE
Download Service fails on Spatial filter tests due to an addition filter

### ISSUE THREAD

**Issue by fhoubie** [INSPIRE-MIF/helpdesk-validator#411]
Validator raises an exception for an additional Geospatial filter supported in our Download Service.

**ERROR**: OGC TEAM Engine reported a failed test: No enum constant org.opengis.cite.geomatics.SpatialOperator.EXTENSION:GMOVERLAPS

**URL of Service** :http://sdidemo.intergraph.pl/WFS_INSPIRE/service.svc/get?request=GetCapabilities&service=WFS
**Test Step URI** : https://inspire.ec.europa.eu/validator//v2/TestRuns/EIDf2f92718-47b8-43fb-b8d1-5ab97ed3aa5f.html?lang=fr#EID0236cbf8-0175-1000-b6a3-8257f2495a89

The validator shall check against mandatory filters only.

**Comment by carlospzurita** [comment]
Dear @fhoubie 

This error is raised on the TEAM engine at https://cite.opengeospatial.org/teamengine/rest/suites/wfs20/1.34/ . The validator only acts as a intermediary between the API from the OGC and the Test Report.

We would kindly ask you to post this issue on their [issue tracker](https://github.com/opengeospatial/teamengine) and put a reference to this one on the community space.

**Comment by fhoubie** [comment]
Thanks @carlospzurita, will do.

**Comment by fabiovinci** [comment]
Dear @fhoubie,

did you open an issue in the OGC repository? If yes, could you please verify if it was solved?
In any case, do you still have this error?

**Comment by fabiovinci** [comment]
Dear @fhoubie,
since there was no reply, I will close the issue.
Please reopen it or open a new issue if the error persists.
