### ISSUE TITLE
INSPIRE Validator production instance down?

### ISSUE THREAD

**Issue by ghost** [INSPIRE-MIF/helpdesk-validator#413]
Hi,

INSPIRE Validator production instance down?

Response:
504 Gateway Time-out.

Kind regards,
Dejan

**Comment by MarcoMinghini** [comment]
Dear @DeordD,
yes, it is. Please use the staging instance for the time being, we will restore the production instance as soon as possible.

**Comment by carlospzurita** [comment]
The validator is running as usual. We are investigating what caused to be out of service yesterday. In the meantime, we are closing this issue.
