### ISSUE TITLE
Direct WFS validator does not seem to use the correct endpoint.

### ISSUE THREAD

**Issue by fhoubie** [INSPIRE-MIF/helpdesk-validator#414]
Test service : http://sdidemo.intergraph.pl/WFS_INSPIRE/service.svc/get?request=GetCapabilities&service=WFS

Our service receives SOAP requests on our POST endpoint.

Here is our DCP declaration:

```XML
<ows:DCP>
	<ows:HTTP>
		<ows:Get xlink:href="http://sdidemo.intergraph.pl/WFS_INSPIRE/service.svc/get?">
			<ows:Constraint name="GetEncoding">
				<ows:AllowedValues>
					<ows:Value>KVP</ows:Value>
				</ows:AllowedValues>
			</ows:Constraint>
		</ows:Get>
		<ows:Post xlink:href="http://sdidemo.intergraph.pl/WFS_INSPIRE/service.svc/post">
			<ows:Constraint name="PostEncoding">
				<ows:AllowedValues>
					<ows:Value>XML</ows:Value>
				</ows:AllowedValues>
			</ows:Constraint>
		</ows:Post>
		<ows:Post xlink:href="http://sdidemo.intergraph.pl/WFS_INSPIRE/service.svc/soap">
			<ows:Constraint name="PostEncoding">
				<ows:AllowedValues>
					<ows:Value>SOAP</ows:Value>
				</ows:AllowedValues>
			</ows:Constraint>
		</ows:Post>
	</ows:HTTP>
</ows:DCP>
`
We have a specific endpoint for SOAP but requests are received on POST endpoint. 

Other question, we do receive a full SOAP Binary request. 

Intergraph.GeoMedia.Web.SDI.Common.SDIProFacadeInterface.MessageAnalyzers.XmlBodyMessageAnalyzerBase [(null)] - <Binary>PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiPz48c29hcDpFbnZlbG9wZSB4bWxuczpzb2FwPSJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy9zb2FwL2VudmVsb3BlLyI+PHNvYXA6Qm9keT48d2ZzOkdldENhcGFiaWxpdGllcyB4bWxuczp3ZnM9Imh0dHA6Ly93d3cub3Blbmdpcy5uZXQvd2ZzLzIuMCIgeG1sbnM6b3dzPSJodHRwOi8vd3d3Lm9wZW5naXMubmV0L293cy8xLjEiIHNlcnZpY2U9IldGUyI+CiAgPG93czpBY2NlcHRWZXJzaW9ucz4KICAgIDxvd3M6VmVyc2lvbj4xMC4wLjA8L293czpWZXJzaW9uPgogICAgPG93czpWZXJzaW9uPjIuMC4wPC9vd3M6VmVyc2lvbj4KICAgIDxvd3M6VmVyc2lvbj4xLjEuMDwvb3dzOlZlcnNpb24+CiAgPC9vd3M6QWNjZXB0VmVyc2lvbnM+Cjwvd2ZzOkdldENhcGFiaWxpdGllcz48L3NvYXA6Qm9keT48L3NvYXA6RW52ZWxvcGU+</Binary>

I'm not sure this is OGC compliant?

Thanks
Frédéric

**Comment by carlospzurita** [comment]
Dear @fhoubie 

We are testing the service endpoint with the WFS Direct Conformance Class, looking into the Test Run logs and also the requests made from the server. We will get back to you with feedback as soon as we can.

**Comment by iuriemaxim** [comment]
@carlospzurita This is the same issue at OGC: https://github.com/opengeospatial/teamengine/issues/438,
Conclusion is:
<<The request is submitted as SOAP binding with POST endpoint and media type as application/soap+xml. The server is not supporting this media type and it returns 400 status code.>>

**Comment by iuriemaxim** [comment]
@carlospzurita This can be closed as according to OCG there is no bug in the INSPIRE/OGC validators. The service implementation should be fixed.

**Comment by carlospzurita** [comment]
Dear @iuriemaxim and @fhoubie 

Thank you for your investigation on the service. You are right that this is not an issue related to the validator

The operations declared on the service capabilities need to be fixed as they are being recognized as POST endpoints. Please, @fhoubie make the appropriate modifications on the service and apply the tests again yo check if the issue is solved.

**Comment by dperezBM** [comment]
Dear all,

Since this issue had no interaction time ago, we decided to close it. Please feel free to open a new one if needed.

Thank you and best regards.
