### ISSUE TITLE
New UI of the INSPIRE Reference Validator ready for testing

### ISSUE THREAD

**Issue by MarcoMinghini** [INSPIRE-MIF/helpdesk-validator#417]
Dear all,
on behalf of the JRC INSPIRE Team, I am happy to inform you that a prototype of the new UI of the INSPIRE Reference Validator is now ready for testing.

This new UI is aligned to the visual identity of the European Commission and addresses the complexity of choosing the 'right' conformance classes to test, especially for novel/non-experienced users, as discussed in issue https://github.com/inspire-eu-validation/community/issues/10).

The new UI offers:
- a more intuitive process for selecting the resources to be tested: users have just to select the type of resource and not the conformance classes (which, however, are still available for more expert users from the 'Advanced options' menu);
- improved filtering capabilities to search for test reports in the test reports page.

The prototype is open for testing and feedback until **November 15**. Afterwards, we will fix/improve the prototype based on the relevant feedback received and we will finally replace the current UI of the Validator (in both the staging and production instances) with this new one. 

Testing is open to any user of the Validator. We kindly ask you to test the new UI and report bugs, provide feedback and suggestions for improvement using this helpdesk (please be sure to mention in the issue title/description that the issue is related to the new UI). To access the new instance, please send an e-mail to JRC-INSPIRE-SUPPORT _AT_ ec.europa.eu to get your access credentials.

Thank you for your support and best regards.

**Comment by ghost** [comment]
Hi @MarcoMinghini ,

thanks a lot for the provision of new UI!

Does it make sense to create issue template in community repository for this which would have some hints what could/should be tested? Maybe it would help the users to communicate the feedback in a better way and also understand a bit which UI components can be tested.
![grafik](https://user-images.githubusercontent.com/38787131/95955318-ef248600-0dfc-11eb-8a83-954924fd1819.png)

It would be also good to integrate new UI in the validator after INSPIRE Monitoring Deadline as community may also need to update to a new validator in order to have the same version like the one used for the Monitoring. 

Thanks a lot in advance!

**Comment by MarcoMinghini** [comment]
Dear @DeordD, 
I see your point about a new issue template, but I think the current templates are already ok for this exercise. Since this will become the future UI of the INSPIRE Reference Validator, everything can be tested and not only bug reports, but also general feedback (especially from users who find the current UI too difficult) is welcome.

**Comment by ghost** [comment]
Dear @MarcoMinghini ,

I understand you point. Thanks for the feedback!

**Comment by iuriemaxim** [comment]
@MarcoMinghini Please include in the post the URL of the new UI as it is not available at https://inspire.ec.europa.eu/validator/about/, nor in the news section of the https://inspire.ec.europa.eu/ and it cant be found by using search engines.

**Comment by hogredan** [comment]
@iuriemaxim you will get the URL and your access credentials by sending an e-mail to JRC-INSPIRE-SUPPORT AT ec.europa.eu. The new UI is not published yet.

**Comment by iuriemaxim** [comment]
@MarcoMinghini 
An UI/UX review of the New UI interface can be found at #423 

Related to @DeordD sugestion, maybe would be good to reference each UI review here too by inserting a comment followed by # and the number of the issue/thread and or to refer this thread in the UI review by including there the text #417

**Comment by MarcoMinghini** [comment]
Dear all,
just a reminder that the testing period for the new UI of the INSPIRE Reference Validator will last until **November 15**, i.e. the end of this week.

We would be happy to receive your feedback, together with any suggestion and improvement proposal, in this helpdesk. You can just reply to this issue or [create another issue](https://github.com/inspire-eu-validation/community/issues/new/choose).

Also, a reminder that in order to access the new UI, you have to request access credentials by sending an e-mail to JRC-INSPIRE-SUPPORT _AT_ ec.europa.eu.

Thank you for your support and best regards.

**Comment by MarcoMinghini** [comment]
Dear all,
after several months of development and internal testing, I am happy to inform you that the new UI has been deployed in the [staging instance](http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp) of the INSPIRE Reference Validator. 

Thanks to all the people who tested it in October/November and provided valuable feedback that we took into consideration for further improving the prototype.

The plan is to substitute the old UI **also** in the production instance with the next release foreseen for June 2021.
