### ISSUE TITLE
New UI Interface - first impressions

### ISSUE THREAD

**Issue by iuriemaxim** [INSPIRE-MIF/helpdesk-validator#423]
Following #417, below can be found first impressions regarding to the New UI interface.

Please to not interpret this as a bad review, but as normal UI/UX report that was done quite in a hurry. Functionalities were not tested, but only the UI/UX was analysed.

The new UI of the validator does not allow a user to provide only the URLs or the files of the metadata for dataset, view and download services in order to allow the validator to perform all the checks, including if the services are properly linked to the metadata files and vice versa. 

This was a useful functionality that existed in the linkage checker and in the INSPIRE Geoportal. This is actually the easiest way for normal users to perform a test. The current UI, even if is organizing the tests in a simpler form does not solve the issue of users to know what to insert in the white box that sometime is named ”Remote file”, sometimes is named ”Service URL”, but actually is the request to the service (i.e. WMS, ATOM. WFS, WCS, SOS, CSW etc.).
 
![image](https://user-images.githubusercontent.com/20813598/96277028-682e0400-0fdc-11eb-8f7b-8a015d21b353.png)

Examples of requests that users should know how to formulate for a WFS
https://inspire-staging.meteoromania.ro/WIGOS/WFS?service=wfs&version=2.0.0&request=GetFeature&typeNames=ef:EnvironmentalMonitoringFacility
and
https://inspire-staging.meteoromania.ro/WIGOS/WFS?service=wfs&version=2.0.0&request=GetFeature&typeNames=ef:EnvironmentalMonitoringNetwork

or the the "Service URL" version, where it can be seen that the explanatory text is not changed based on context, so users may be confused that the text is indicating the user that it has as option to upload a ZIP file in order to test a service such as for example a WMS. Still the user is not provided with the relevant information in order to know what to type in the white free text box, but even it tells him that the request should retrieve "one or more records/features", instead of indicating that a GetCapabilities request is expected:

![image](https://user-images.githubusercontent.com/20813598/96548496-a8c89e80-12b6-11eb-8ec9-81651cce2b11.png)
 
In the current/old version of the validator it is quite clear when to upload a file and when to provide the URL with the request to the service and it is also  provided an example of the request for testing the services, which all are missing in the New UI:

![image](https://user-images.githubusercontent.com/20813598/96548616-df9eb480-12b6-11eb-8fea-bc8e3ab17daf.png)

Most users are not familiar how to write network service requests, so most of them are experiencing this issue. There are two many tests and to many requests that they need to know how to formulate, so many give up, while few are asking for an intensive training and then are forgetting what to do in order to perform the tests of their own services.

The simplest way to validate all the resources in only one screen is by providing only three URLs or the content of the metadata files, as it is in this interface:

![image](https://user-images.githubusercontent.com/20813598/96277142-8c89e080-0fdc-11eb-9152-e74752fe8a15.png)

 
Till now this is the simplest way for a user to perform a test. It was even better if the users would had also the option to upload the metadata files as well. The disadvantage of this interface is that is not possible to perform a test unless all three URLs or content of the metadata files are provided, but this most probably can be changed. This is the simplest UI that most users would understand and find it easy to be used. More advanced options could be selected once the metadata file/files are loaded and analysed automatically by the tool (i.e. to understand if the download service refered in the metadata is a WFS, if the view service is a WMTS, etc). So the user should not press ”Check resources”, but ”Next”. Than it should see the advanced options and be advised to perform a full test, unless he wants to perform a partial test for a specific purpose.

Taking into consideration that INSPIRE cant work without metadata, any service or dataset should have a metadata file by default, and can be tested based on its metadata even if the metadata file would have some errors.

For those users that would like to test a service or a dataset without having a metadata file, it should exist a third choice (besides ”URL to INSPIRE metadata” and ”INSPIRE metadata XML content”) to allow the user to indicate the GetCapabilities of the service (or the corresponding request). Most would appreciate simplicity and as few as possible interaction. If the users would provide the GetCapabilities request to a Download service, than the system would be able also to retrieve and test the dataset in conformity with the data specification(s) that are advertised in the GetCapabilities trough the prefixes of the feature types that can be retrieved (ex: ps:ProtectedSite -> PS data theme)

Coming back to the New UI, for example a user should know to what data themes correspond a data set in order to validate a dataset in the new UI as the UI is asking him to check the specific boxes. He even should know to which annex that dataset correspond (which I see useless now, as they were just used for some deadlines which are gone).
 
![image](https://user-images.githubusercontent.com/20813598/96277184-9b709300-0fdc-11eb-9239-f6da6760c236.png)

But why a user should select the data themes as far as they can be determined both from the metadata of the dataset and from the GetCapabilities document of the service or even by parsing the GML document. Neither to say that the text is not indicating to the user that it should either upload a GML or a compressed GML in zip format. The user would simply think that any zip file that contains lets say a shapefile or KMZ or a even a picture would be fine. At least the current/old validator is more explicit as can be seen in the images below

![image](https://user-images.githubusercontent.com/20813598/96277219-a4f9fb00-0fdc-11eb-964d-0bb9cd742424.png)

And

![image](https://user-images.githubusercontent.com/20813598/96277239-a9261880-0fdc-11eb-859e-f311f2de8474.png)
 
But coming back, I see no reason why somebody should indicate data themes as the validator could determine this alone.

Nor even if minor changes would be made, why the data themes should reside in three separate drop down lists, and a novice user should check all drop down lists in order to find a data theme in one of them. Few are familiar with numbers of the annexes of the INSPIRE Directive, and they are not anymore relevant.

The advanced options are most probably a nightmare for a novice user

![image](https://user-images.githubusercontent.com/20813598/96277271-b0e5bd00-0fdc-11eb-9b56-4b358cf6ab46.png)

 
Why to check some, or what to check or to uncheck, would be a problem for most users. No information is provided to them for example to let all these checked for a full test or to check only some of them if they would like a partial test only.

The therm "Advanced Options" indicate to users that this section can be left untouched for testing. Supposing then that most users will not open the advanced options there are some which will pose problems as the user will need to chose one or another option, but still he is not receiving any information why to check one or another. So in the following cases the advanced options are not actually advanced options as the user should make a choice and is not by default that he can let the advanced options untouched. If a user is novice, he most probably will not open the advanced options, or if he will open then he will not know what to do.

![image](https://user-images.githubusercontent.com/20813598/96277277-b8a56180-0fdc-11eb-8793-0fb247768830.png)

In this case actually it is missing a forth selection to allow the user to chose what type of SDS is his service for which he produced metadata: harmonised, interoperable or just invocable. But similar as for the annexes, why a user should check one or another as far as the validator could read the content of the metadata and find if it corresponds to a invocable, interoperable or harmonised SDS as this is advertised in a metadata element. Of course that the validator could even determine for each metadata file if it correspond to a dataset or service and even to what type of service it correspond. If these elements would be missing an error message could be triggered.

But to come back, for this one:
![image](https://user-images.githubusercontent.com/20813598/96277295-be9b4280-0fdc-11eb-8313-0c8545c73925.png)

 
The user is not receiving any information when to chose 2 and when to chose 2b. I do not either understand why this difference is needed. If those elements that are required by 2b are present, then they should be tested. If they are not present then they should not be tested. A user is for sure confused even today with the current/old validator as no information is provided when to test 2 and when to test 2b. And if it is 2b, where it is 2a?

Even if there is a red star there is no explanation what it means. Of course it is understandable, but still if present, it should be explained that those marked with star are mandatory.
![image](https://user-images.githubusercontent.com/20813598/96277318-c529ba00-0fdc-11eb-81b5-e069a9a36546.png)
 
As the Version 1.3 of the Metadata TG is not anymore in place, this should disappear or at least information should be provided that this is not anymore in place from December 2019 and there were three years of transition to version 2.0.

When testing a WFS the user should chose Direct WFS or Pre-defined WFS. However in the tests for the Direct WFS should exist by default also the tests of the Pre-defined WFS as all tests. We have a Direct WFS that is passing the Pre-defined WFS tests as well. I see no reason why a Direct WFS should not be tested against the Pre-defined WFS tests as well.

![image](https://user-images.githubusercontent.com/20813598/96277335-c955d780-0fdc-11eb-95ab-589c47175725.png)

Users are confused when they see a text like ”Select the input type” and then in the drop down list with only one choice. Text referring to the files and zip files is misleading for sure as the user will not find a button to be pressed for uploading those files in whatever format.

![image](https://user-images.githubusercontent.com/20813598/96277356-d07ce580-0fdc-11eb-8177-5676fa960c75.png)

Regarding design of the Test reports, which looks better?

![image](https://user-images.githubusercontent.com/20813598/96299907-6a548a80-0ffd-11eb-8ea1-3cba64228e56.png)

or

![image](https://user-images.githubusercontent.com/20813598/96299775-38432880-0ffd-11eb-8fda-653e1b3406ab.png)

Don't think that users will understand what the raised hand means.
The status is also not clear PASSED_MANUAL (raised hand) vs PASSED (checked) 

There are also some issues while resizing the window of the browser for the tests reports:

widest:
![image](https://user-images.githubusercontent.com/20813598/96300279-f070d100-0ffd-11eb-9e57-bb2169ac6dba.png)

middle has some issues:
![image](https://user-images.githubusercontent.com/20813598/96300538-578e8580-0ffe-11eb-8ec4-85e0a1011b0a.png)

narrowest:
![image](https://user-images.githubusercontent.com/20813598/96300378-1bf3bb80-0ffe-11eb-8614-d88aa5424651.png)

After the test is performed there is a plus sign that does not collapse the content below and the Search and filter part in the right is misleading even if a user cant interact with it (so why it is there. A user would than think that he can enable the content of the filtering from the left by clicking on the Show all test reports, but actually this will load another page.

![image](https://user-images.githubusercontent.com/20813598/96302186-03d16b80-1001-11eb-8432-f3f99f8cfa7c.png)

The report shown is less intuitive. The user should click on "See report" while in the old/current validator the user should not click any button as he already see the results.

When the user clicks on the "See report" the report is opened in a new window of the browser (this is not fine) and the entire design is changed as the old/current UI/UX is displayed. Design should be aligned across entire UI/UX. Because a new window is opened in the browser many users will be confused and some will have problems, such as for example to run a new test.

There is no logo for the new UI/UX, while the old/current one has:

![image](https://user-images.githubusercontent.com/20813598/96304280-81e34180-1004-11eb-8693-6dc25d88854e.png)

If a user clicks on "See report", then goes back to to the window in which he clicked "See report" and clicks on "Download report" quite strangely the browser is switching the focus to the old/current UI/UX that was previously opened. So the user should switch again the tab of the browser.

Tags disappeared in the new UI, if were previously used:
![image](https://user-images.githubusercontent.com/20813598/96309328-c0312e80-100d-11eb-80d7-dc94fd2bc95f.png)

Credentials and optional parameters seems that cant be set anymore, if were previously used:
![image](https://user-images.githubusercontent.com/20813598/96309648-6c731500-100e-11eb-8e62-61bbf0d050eb.png)

This design:
![image](https://user-images.githubusercontent.com/20813598/96305694-f4edb780-1006-11eb-919a-cb65ea37ff2c.png)

should be compared with this design:

![image](https://user-images.githubusercontent.com/20813598/96305760-0fc02c00-1007-11eb-898c-21a1fc47cf39.png)

It is quite different and the blue ribbon is huge, It takes a lot of useful space.

Neither other pages with the new EC design are not consuming so much space

![image](https://user-images.githubusercontent.com/20813598/96306824-19e32a00-1009-11eb-86a6-b9dfe4eefac5.png)

And the DG Environment and JRC are not using this new design

![image](https://user-images.githubusercontent.com/20813598/96307665-ac37fd80-100a-11eb-8ade-7f23c2d8a4b2.png)

Same for the footer, this one can be compared:

![image](https://user-images.githubusercontent.com/20813598/96306134-c15f5d00-1007-11eb-9de1-74b942ea8801.png)

with this one new huge footer design inspired from the EC main website (https://ec.europa.eu/info/strategy/reporting_en):
![image](https://user-images.githubusercontent.com/20813598/96306194-e18f1c00-1007-11eb-94b6-2f3b9f5b5122.png)

The menu looks strange including that is on blue color and huge size and spacing
![image](https://user-images.githubusercontent.com/20813598/96307115-b7d6f480-1009-11eb-87bf-72fc831af77a.png)
 
compared to this
![image](https://user-images.githubusercontent.com/20813598/96309041-2c5f6280-100d-11eb-8ea9-87a8df5b1615.png)

**Comment by iuriemaxim** [comment]
few updates were made to the text.

**Comment by MarcoMinghini** [comment]
Dear @iuriemaxim,
as you might have already noticed, the new UI has been recently included in the [staging instance](http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/) of the INSPIRE Reference Validator. Starting with the next release scheduled for mid-June (see the release plan [here](https://github.com/INSPIRE-MIF/helpdesk-validator/tree/master/release%20strategy)), the new UI will be also included in the [production instance](https://inspire.ec.europa.eu/validator/).

On behalf of the INSPIRE validation team, I would like to thank you for testing the new UI and providing us with useful feedback and suggestions. As you can see, your comments were highly considered to improve the UI.

I close this issue, but please do not hesitate to open other issues to provide additional feedback, should this be needed.
