### ISSUE TITLE
Bulk Validation Tool - Error initializing UserDefinedJavaClass

### ISSUE THREAD

**Issue by laers** [INSPIRE-MIF/helpdesk-validator#428]
I have installed the Monotoring Bulk Validation Tool as described in the step-by-step guide in https://github.com/inspire-eu-validation/monitoring-bulk-validation-tool 

When executing "validation.bat" the tool is starting but it run into errors: Here is a screen dump:
![image](https://user-images.githubusercontent.com/34093019/96971656-b6c82a80-1515-11eb-95fa-f753661e7a85.png)

I am using this PDI version: pdi-ce-9.0.0.0-423

JAVA_HOME is "...\AdoptOpenJDK\x64_jdk8u265-b01"

I have also tried the alternative way described in the guide and run the Spoon.bat 
But error message is returned:
![image](https://user-images.githubusercontent.com/34093019/96972170-6ef5d300-1516-11eb-8578-772378ee407c.png)

It seems to be a Java issue or ? Thanks in advanced.
Lars

**Comment by ukiz** [comment]
Dear Lars,

Please make sure to copy the _inspire-validator.jar_ to your PDI _lib_ folder. Also, please check that the .jar file is not corrupted, i.e. it can be opened as a .zip archive.  There was a similar issue: #371 

Regarding the problem with running Spoon.bat, it seems to be a Java environment issue. We have not tested OpenJDK.

Kind regards,

Lukasz Ziemba

**Comment by laers** [comment]
Dear Lukasz,

Thanks for the very quick reply - and yes, as #371 the error was reletad to the .jar-file.

br
Lars
