### ISSUE TITLE
Conformance Class: Download Service - Direct WFS: Problem with Curve geometry with srsName in HTTP URI format

### ISSUE THREAD

**Issue by calhanson** [INSPIRE-MIF/helpdesk-validator#429]
Hi!

After issue #314 has been solved ([ets-wfs20 issue](https://github.com/opengeospatial/ets-wfs20/issues/170)) we have been able to run the tests locally (the online validator skips the Spatial Filter - BBOX tests for unknown reason) and the Spatial Filter tests now passes for both `Curve` and `Surface` geometry types. However, when testing a service with `srsName` in HTTP URI format the tests fails for `Curve` geometries with error:

Test:
`org.opengis.cite.iso19142.basic.filter.spatial.BBOXTests.bboxWithDefaultExtent`

Error:
`Failed to create JTS geometry from GML geometry: [MultiCurveType]`
`id:geometry.RoadLink.SAMPLE_tn-ro_RoadLink_1`
`Cause: Illegal argument: ‘code’=http://www.opengis.net/def/crs/EPSG/0/3034`

After some debugging it looks like a `MultiCurve` element created has an `srsName` attribute as do the aggregated `Curve` element, one of these is updated with a value in to urn format (in the `Extents.calculateEnvelope` method). The lingering HTTP URI breaks the conversion to a JTS geometry.

Geometry type `Surface` does not seem to have this problem. Perhaps because of a new `Polygon` element being created, without an explicit `srsName`, and then added to a `MultiSurface` with the only `srsName` attribute in the combined geometry?!

The tested service is available here:
http://192.71.92.21/MapService/wfs.axd/InspireTest?service=WFS&version=2.0.0&request=GetCapabilities

Please verify that the service is currently using the HTTP URI format for `srsName`:
http://192.71.92.21/MapService/wfs.axd/InspireTest?service=WFS&version=2.0.0&request=GetFeature&typenames=RoadLink

Regards

**Comment by carlospzurita** [comment]
Dear @calhanson 

Thank you for opening this issue and performing some investigation on your side. However, we would kindly ask you to move this one to the OGC repository, linking the [previous issue](https://github.com/opengeospatial/ets-wfs20/issues/170) there. 

The INSPIRE validator just serves the service as they are to the TEAM Engine, and doesn't create any geometry object on its side.

**Comment by calhanson** [comment]
Moved issue here: https://github.com/opengeospatial/ets-wfs20/issues/180
