### ISSUE TITLE
MineralOccurrence.form: Different validation results for same XML syntax with different notation

### ISSUE THREAD

**Issue by JohannaOtt** [INSPIRE-MIF/helpdesk-validator#431]
When validating a MineralResource file containing this Category element for MineralOccurrence.form, the validation fails depending on which notation is used with errors in Test ID | EID0eaac0f2-9ab3-44ab-9f02-4ee0a1587d14:

The dataset has 1 file(s) with errors for this assertion.
XML document [...]: The file has 5 schema validation error(s).
XML document [...]: http://schemas.geosciml.org/cgiutilities/3.0/cgiUtilities.xsd, 2:35: s4s-elt-character: Non-whitespace characters are not allowed in schema elements other than 'xs:appinfo' and 'xs:documentation'. Saw '301 Moved Permanently'.
XML document [...]: http://schemas.geosciml.org/cgiutilities/3.0/cgiUtilities.xsd, 4:34: s4s-elt-character: Non-whitespace characters are not allowed in schema elements other than 'xs:appinfo' and 'xs:documentation'. Saw '301 Moved Permanently'.
XML document [...]: http://schemas.geosciml.org/cgiutilities/3.0/cgiUtilities.xsd, 5:18: s4s-elt-character: Non-whitespace characters are not allowed in schema elements other than 'xs:appinfo' and 'xs:documentation'. Saw 'nginx'.
XML document [...]: http://schemas.geosciml.org/cgiutilities/3.0/cgiUtilities.xsd, 6:3: The element type "hr" must be terminated by the matching end-tag "</hr>".
XML document [...]: http://schemas.geosciml.org/cgiutilities/3.0/cgiUtilities.xsd, 6:3: The element type "hr" must be terminated by the matching end-tag "</hr>".

There are validation errors when using
        <mr-core:form>
            <swe:Category>
              <swe:codeSpace xlink:href="http://cgi.vocabs.ga.gov.au/object?uri=http://resource.geosciml.org/classifier/cgi/earth-resource-form"**></swe:codeSpace>**
              <swe:value>http://resource.geosciml.org/classifier/cgi/earth-resource-form/discordant</swe:value>
            </swe:Category>
          </mr-core:form>

There are no validation errors when using 
        <mr-core:form>
            <swe:Category>
              <swe:codeSpace xlink:href="http://cgi.vocabs.ga.gov.au/object?uri=http://resource.geosciml.org/classifier/cgi/earth-resource-form"**/>**
              <swe:value>http://resource.geosciml.org/classifier/cgi/earth-resource-form/discordant</swe:value>
            </swe:Category>
          </mr-core:form>

This is unexpected to me as this is the same syntactically in XML.

This is the test report for the failing version: 
[Test.zip](https://github.com/inspire-eu-validation/community/files/5457717/Test.zip)

This is an example file: 
[subset_testExportMR.zip](https://github.com/inspire-eu-validation/community/files/5457749/subset_testExportMR.zip)

There is also this [discussion in the cluster](https://inspire.ec.europa.eu/forum/discussion/view/269514/how-to-correctly-use-swecategory-for-mineraloccurrenceform) on the issue.

**Comment by carlospzurita** [comment]
Dear @JohannaOtt 

We are looking into this issue, but we found that the TestReport attached seems to be referring to a different GML file, and the error is different on the production instance. Can you confirm that this is the relevant GML file?

Thanks

**Comment by JohannaOtt** [comment]
Dear @carlospzurita 

Thanks you for your quick reply. I repeated the test with the GML file I provided and downloaded the report again. I always have a hard time to determine which of the test reports are mine, but I think, this one should definitely fit: 
[Test(1).zip](https://github.com/inspire-eu-validation/community/files/5463612/Test.1.zip)

All the best

Johanna

**Comment by fabiovinci** [comment]
Dear @JohannaOtt,

I tested your sample data using the following encoding:

```xml
          <mr-core:form>
            <swe:Category>
              <swe:codeSpace
                xlink:href="http://cgi.vocabs.ga.gov.au/object?uri=http://resource.geosciml.org/classifier/cgi/earth-resource-form"></swe:codeSpace>
              <swe:value>http://resource.geosciml.org/classifier/cgi/earth-resource-form/discordant</swe:value>
            </swe:Category>
          </mr-core:form>
```

and there are no errors on this element, see the [report](https://inspire.ec.europa.eu/validator/test-run/details.html?id=EIDc449f714-60ed-4dc5-8737-5219f6554e79).

Could you please check and confirm?

**Comment by JohannaOtt** [comment]
@fabiovinci I can confirm that I do not get errors any longer when using the notation that used to cause validation errors. So this issue can be closed from my point of view.

**Comment by fabiovinci** [comment]
@JohannaOtt, thank you for your quick reaction, I’m closing this issue for now since the error is no more present.
