### ISSUE TITLE
Wrong value of Quality Of Service Criteria codelist

### ISSUE THREAD

**Issue by radochudy** [INSPIRE-MIF/helpdesk-validator#432]
During testing of metadata according requirements for interoperable and harmonized spatial data service I Found out, that Validator use wrong values to Registry items for checking:
Right values are:
http://inspire.ec.europa.eu/metadata-codelist/QualityOfServiceCriteria/availability
http://inspire.ec.europa.eu/metadata-codelist/QualityOfServiceCriteria/performance
http://inspire.ec.europa.eu/metadata-codelist/QualityOfServiceCriteria/capacity

But validator check for occurrence of values:
http://inspire.ec.europa.eu/metadata-codelist/QualityOfServiceCriteria**Code**/availability
http://inspire.ec.europa.eu/metadata-codelist/QualityOfServiceCriteria**Code**/performance
http://inspire.ec.europa.eu/metadata-codelist/QualityOfServiceCriteria**Code**/capacity 

`
let $messages :=  
	(for $record in $records
		let $rid := $record/gmd:fileIdentifier/*/text()
		let $results := $record/gmd:dataQualityInfo/gmd:DQ_DataQuality/gmd:report/gmd:DQ_ConceptualConsistency

		return 	 
		if (count($results) < 3) then
			local:addMessage('TR.wrongQualityCriteriaMultiplicity', map { 'filename': local:filename($record), 'id': $rid,  'count': count($results)})
		else 	
			for $result in $results
				let $measureName := $result/gmd:nameOfMeasure
				let $measureNameAnchor := $result/gmd:nameOfMeasure/gmx:Anchor/@xlink:href
				let $validation1 := $result[(./gmd:nameOfMeasure/gmx:Anchor/@xlink:href = 'http://inspire.ec.europa.eu/metadata-codelist/QualityOfServiceCriteriaCode/availability') and (./gmd:result/gmd:DQ_QuantitativeResult/gmd:value/gco:Record/@xsi:type = ('xs:double','xsi:double')) and (data(./gmd:result/gmd:DQ_QuantitativeResult/gmd:value/gco:Record) >= 0) and (data(./gmd:result/gmd:DQ_QuantitativeResult/gmd:value/gco:Record) <= 100) and (./gmd:result/gmd:DQ_QuantitativeResult/gmd:valueUnit/@xlink:href = 'urn:ogc:def:uom:OGC::percent')]
				let $validation2 := $result[(./gmd:nameOfMeasure/gmx:Anchor/@xlink:href = 'http://inspire.ec.europa.eu/metadata-codelist/QualityOfServiceCriteriaCode/performance') and (./gmd:result/gmd:DQ_QuantitativeResult/gmd:value/gco:Record/@xsi:type = ('xs:double','xsi:double')) and (./gmd:result/gmd:DQ_QuantitativeResult/gmd:valueUnit/@xlink:href = 'http://www.opengis.net/def/uom/SI/second')]
				let $validation3 := $result[(./gmd:nameOfMeasure/gmx:Anchor/@xlink:href = 'http://inspire.ec.europa.eu/metadata-codelist/QualityOfServiceCriteriaCode/capacity') and (./gmd:result/gmd:DQ_QuantitativeResult/gmd:value/gco:Record/@xsi:type = ('xs:integer','xsi:integer')) and (./gmd:result/gmd:DQ_QuantitativeResult/gmd:valueUnit/@xlink:href = 'http://www.opengis.net/def/uom/OGC/1.0/unity')]

				let $measureDescription := $result/gmd:measureDescription

				let $quantitativeResult := $result/gmd:result/gmd:DQ_QuantitativeResult

				let $valueUnit := $result/gmd:result/gmd:DQ_QuantitativeResult/gmd:valueUnit/@xlink:href
				let $valueRecord := $result/gmd:result/gmd:DQ_QuantitativeResult/gmd:value/gco:Record/@xsi:type

				return
				if (not($measureName)) then
					local:addMessage('TR.noMeasureName', map { 'filename': local:filename($record), 'id': $rid })
				else if (not($measureNameAnchor)) then
					local:addMessage('TR.noMeasureNameAnchor', map { 'filename': local:filename($record), 'id': $rid })
				else if (not(($validation1) or ($validation2) or ($validation3))) then
					local:addMessage('TR.invalidQualityCriteria', map { 'filename': local:filename($record), 'id': $rid })
                else if (not($measureDescription) or not(string-length($measureDescription/gco:CharacterString/text()) != 0 or string-length($measureDescription/gmx:Anchor/text()) != 0)) then
					local:addMessage('TR.noMeasureDescription', map { 'filename': local:filename($record), 'id': $rid })
				else if (not($quantitativeResult)) then
					local:addMessage('TR.noQuantitativeResult', map { 'filename': local:filename($record), 'id': $rid })
				else if (not($valueUnit)) then
					local:addMessage('TR.noValueUnit', map { 'filename': local:filename($record), 'id': $rid })
				else if (not($valueRecord)) then
					local:addMessage('TR.noValueRecord', map { 'filename': local:filename($record), 'id': $rid })	
				else () 		
	)[position() le $limitErrors] 
return
(if ($messages) then 'FAILED' else 'PASSED',
 local:error-statistics('TR.recordsWithErrors', count(fn:distinct-values($messages//etf:argument[@token='id']/text()))),
 $messages)`

**Comment by carlospzurita** [comment]
Dear @radochudy 

We checked this requirement on the Technical Guidance for Metadata 2.0 and it seems that the tests is aligned what is stated in there
![imagen](https://user-images.githubusercontent.com/10537778/97713858-a9d0ab80-1ac0-11eb-875b-26d91c0387bf.png)

Following the footnote 80 remarked in there, the URI shall include the `Code` part.

However, it is true that on the registry this URI can't be resolved.

We are going to check internally and get back to you with an answer.

**Comment by fabiovin** [comment]
Dear all,

we discussed internally and decided we can consider, at the moment, that the right URL is [http://inspire.ec.europa.eu/metadata-codelist/QualityOfServiceCriteria](http://inspire.ec.europa.eu/metadata-codelist/QualityOfServiceCriteria).
This URL is also present in the Annex D.3 of the Technical Guidance for Metadata 2.0.
A future revision of the TG will clarify if the URL present in the footnote is the right one.

@carlospzurita Could you please update the ETS with the right URL?

Thanks,
Fabio

**Comment by carlospzurita** [comment]
The ETS has been updated with the correct values for this assertion. You can check it out on the [staging instance](staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/)

**Comment by carlospzurita** [comment]
Dear @radochudy 

Did you have the opportunity to test the fix? Please let us know if everything is OK to include it on the next release next week.

Kind regards.

**Comment by carlospzurita** [comment]
Dear @radochudy 

Can we consider this issue fixed and include it on the next release of the INSPIRE validator scheduled for 15/06/2021 ?

**Comment by carlospzurita** [comment]
Dear @radochudy  

Did you have the opportunity to test the solution for this issue?

**Comment by fabiovin** [comment]
Dear @carlospzurita,

I tested it using sample metadata and it works fine.

I think you can consider this issue fixed and include it in the next release.

Thanks,
Fabio
