### ISSUE TITLE
validator on staging instance is down

### ISSUE THREAD

**Issue by iuriemaxim** [INSPIRE-MIF/helpdesk-validator#433]
![image](https://user-images.githubusercontent.com/20813598/98080767-a05b9080-1e7e-11eb-8f7b-d7843dd42f3f.png)

**Comment by carlospzurita** [comment]
Staging is available again, we were testing some modifications and the instance was unstable. You can use it again

**Comment by iuriemaxim** [comment]
No, it is not working

**Comment by iuriemaxim** [comment]
![image](https://user-images.githubusercontent.com/20813598/98085061-778ac980-1e85-11eb-8585-8eeb4aa7e439.png)

**Comment by carlospzurita** [comment]
I have just entered the site and it works prefectly. Please follow the link http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/
