### ISSUE TITLE
validator on staging instance still down

### ISSUE THREAD

**Issue by iuriemaxim** [INSPIRE-MIF/helpdesk-validator#434]
now, another error:

![image](https://user-images.githubusercontent.com/20813598/98085440-01d32d80-1e86-11eb-8190-c0a7441694fd.png)

**Comment by carlospzurita** [comment]
As commented on issue #433, the site is working and is accessible

**Comment by iuriemaxim** [comment]
Unfortunately it does not work and the error message was changed from issue 443. Only the validator on production environment works. Maybe you are in the local network or have a VPN to where it resides. If so, then you can test with [Tor](https://www.torproject.org/) or from a mobile phone connected to 3G/4G.

**Comment by carlospzurita** [comment]
We have tested the access from different locations, in different networks without any VPN, and the site is still accessible. Enter the site on private mode to avoid any cache issues, and maybe check your network for any problem.

**Comment by iuriemaxim** [comment]
Indeed now it works. I made no changes.
