### ISSUE TITLE
MD 1.4 INSPIRE Theme Keyword test throws system error

### ISSUE THREAD

**Issue by tilmanb** [INSPIRE-MIF/helpdesk-validator#435]
The test Conformance class 1 for Metadata -> 1.4 INSPIRE theme keyword throws a system error:

Test run: https://inspire.ec.europa.eu/validator/v2/TestRuns/EIDd615401d-1521-4d0b-b2f6-6d5b99ed24e9.html

`System error in the Executable Test Suite. Please contact a system administrator. Error information:
Code list http://inspire.ec.europa.eu/theme cannot be accessed.`

**Comment by carlospzurita** [comment]
We are checking the status of the production instance, and it seems that the filesystem to cache schemas like the ones on the INSPIRE registry is corrupted. We are going to execute a restart of the service to restore it. In the meantime, please use the [staging instance](http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/).

Sorry for the inconveniences.

**Comment by carlospzurita** [comment]
Service is restored, and requriement 1.4 is working again. You can test it on https://inspire.ec.europa.eu/validator

**Comment by tilmanb** [comment]
No, it still does not work completely.

Test run just now:
https://inspire.ec.europa.eu/validator/v2/TestRuns/EIDd6acc858-96fa-4b83-8c6a-bdd30da03b05.html

System errors in tests a.5 and a.6:
`System error in the Executable Test Suite. Please contact a system administrator. Error information:
[err:FODC0002] "https://standards.iso.org/ittf/PubliclyAvailableStandards/ISO_19139_Schemas/resources/codelist/ML_gmxCodelists.xml" (Line 1): Premature end of file. 
 (552/29)`
and
`System error in the Executable Test Suite. Please contact a system administrator. Error information:
[err:FODC0002] "https://standards.iso.org/ittf/PubliclyAvailableStandards/ISO_19139_Schemas/resources/codelist/gmxCodelists.xml" (Line 1): Premature end of file. 
 (607/29)
`

**Comment by tilmanb** [comment]
Same error on staging instance:
http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/v2/TestRuns/EID56334591-4b83-4970-9196-ad96b8c79eeb.html

**Comment by tilmanb** [comment]
From what i can find out the URL changed to https://standards.iso.org/iso/19139/resources/ML_gmxCodelists.xml , at least under that URL I can find a XML document.

**Comment by carlospzurita** [comment]
Dear @tilmanb 

This new issue that you are referring is on Metadata 1.3, as opposed to the first one that was on metadata 2.0.

This issue is, as you correctly pointed out on your last comment, that the URL for the ISO resource has changed. However, we are not supporting anymore Metadata 1.3, as the deadline for switch from MD TG 1.3 to metadata TG 2.0 has expired in December 2019. The next Monitoring and Reporting will only take into account Metadata 2.0 tests.

No action if going to be taken to solve this issue. Please, from now on, switch your validations to Metadata 2.0

**Comment by tilmanb** [comment]
Please then remove the 1.3 MD tests. Having known obsolete (and broken!) tests on your validator is very much misleading.

**Comment by tilmanb** [comment]
OK, so we close this as resolved and I open another for the 1.3 test removal.
