### ISSUE TITLE
Question about test result

### ISSUE THREAD

**Issue by nppozar** [INSPIRE-MIF/helpdesk-validator#437]
For the first time, we encountered the following error validating metadata for a service:
![image](https://user-images.githubusercontent.com/45449924/98100673-7d86a780-1e91-11eb-8fee-5af5bcd8c14a.png)

According to the message, we don’t know how to take action. I am attaching xml of metadata and html of test result and kindly ask you for help.
[xml&etf_test_report.zip](https://github.com/inspire-eu-validation/community/files/5487255/xml.etf_test_report.zip)

If you need anything else please write to me.

Thank you very much for your help.

**Comment by carlospzurita** [comment]
Dear @nppozar 

This issue was related to the issue on #435. Due to a corruption in the caching system on the validator, the external schemas were not accessible. It has now been solved. You can test it on https://inspire.ec.europa.eu/validator

**Comment by nppozar** [comment]
Thank you very much, now everything is ok!
