### ISSUE TITLE
1.3 Metadata tests throw system errors

### ISSUE THREAD

**Issue by tilmanb** [INSPIRE-MIF/helpdesk-validator#439]
The Metadata 1.3 tests are broken, they throw system errors because a URL has changed.

How to reproduce: Choose Metadata 1.3 tests. Choose https://nibis.lbeg.de/geonetwork/srv/api/records/24c2d910-6456-4d98-a08d-0a111ac40ab2/formatters/xml as document. Run them.

Expected behaviour: Tests are executed and pass or fail depending on content.

Actual behaviour: System errors, see https://inspire.ec.europa.eu/validator/v2/TestRuns/EIDd6acc858-96fa-4b83-8c6a-bdd30da03b05.html, in tests a.5 and a.6.

a.5: https://inspire.ec.europa.eu/validator//v2/TestRuns/EIDd6acc858-96fa-4b83-8c6a-bdd30da03b05.html?lang=de#EIDa0f58364-c211-4b9e-928b-3d93e6232702

a.6: https://inspire.ec.europa.eu/validator//v2/TestRuns/EIDd6acc858-96fa-4b83-8c6a-bdd30da03b05.html?lang=de#EID5b5cefce-97b0-400b-b481-929cf043d3e4

Also Metadata 1.3 was deprecated in Dec 2019, as per a comment of @carlospzurita ( https://github.com/inspire-eu-validation/community/issues/435#issuecomment-722296892 ).

I propose to either remove the Metadata 1.3 tests or fix them. Having known broken and obsolete tests available confuses the users.

**Comment by carlospzurita** [comment]
Dear @tilmanb 

Thank you for raising this topic in a new issue. We are going to mark it as discussion for now, and we are going to check it internally.

**Comment by tilmanb** [comment]
I see you marked the 1.3 MD test cases as "DEPRECATED", and I think that is a good interim solution. Thanks!

**Comment by carlospzurita** [comment]
Thank you @tilmanb for your comments. We are closing this issue for now, but may reopen it in case it is decided to move forward with the 1.3 situation.
