### ISSUE TITLE
LU - Test ExistingLandUseSample returns Empty Spatial Dataset when selu:dataset node is populated

### ISSUE THREAD

**Issue by robblis** [INSPIRE-MIF/helpdesk-validator#440]
When testing the Sampled Existing Land Use for the LU theme, the GML Application schemas, Land Use test is chosen also and  returns the following validation error for the Land Use feature in dataset.

The XML documents representing the spatial data set do not contain a feature of any of the spatial object types in the application schemas of the data theme 'Land Use'. Therefore, the spatial data set cannot conform to this conformance class. If you have expected to find spatial objects from the application schemas in the data set, please consult the statistics information to see the spatial object types that have been found.

However, in the returned XML the selu:datset contains an href link to the SampledExistingLUDataSet as shown below.

<selu:dataset xlink:href="http://agsinspire1.esri.com/arcgis/rest/services/LUTest/MapServer/exts/InspireFeatureDownload/service?SERVICE=WFS&VERSION=2.0.0&REQUEST=GetFeature&STOREDQUERY_ID=urn:ogc:def:query:OGC-WFS::GetFeatureById&id=sluSampledExistingLUDataSet.201"/>
</selu:ExistingLandUseSample>

Is this correct or is this returning the wrong data?

I've attached the returned XML

[LU_SampleExistingLandUse_XML.zip](https://github.com/inspire-eu-validation/community/files/5497902/LU_SampleExistingLandUse_XML.zip)

**Comment by carlospzurita** [comment]
Dear @robblis 

The [line](https://github.com/inspire-eu-validation/ets-repository/blob/6fa5898f51e9d05bb9c833fcc85ecf401a133d63/data-lu/lu-gml/ets-lu-gml-bsxets.xml#L69) on the ETS that checks that requirement states that the recognizable features are

`[ExistingLandUseDataSet, ExistingLandUseGrid, SpatialPlan, SampledExistingLandUseDataSet]`

None of this appear in the file `LU_ExistingLandUseSample.xml`. We are going to check if the dataset can be linked like that, or it should appear in the file being tested.

**Comment by robblis** [comment]
Dear @carlospzurita ,

Just an additional comment...

The SampledExistingLandUse.xsd shows that there are no further node elements listed past the selu:dataset element, so as far as I can see, I am unable to map past that element.

**Comment by fabiovin** [comment]
Dear @robblis,

we assumed the _SampledExistingLandUseDataset_ as the main feature type for a dataset compliant with the _Sampled Land Use_ application schema since it contains some general attributes and the link (through the _member_ association) to all the related _ExistingLandUseSample_ elements.


![image](https://user-images.githubusercontent.com/46569952/119643668-4f13ee00-be1c-11eb-9a2b-b67b60af9b82.png)

For this reason, the [basic test](https://github.com/inspire-eu-validation/data-lu/blob/master/lu-gml/basic.md) is looking for the SampledExistingLandUseDataSet to be present.
Therefore the two feature types should be present in the same dataset.

What do you think about this approach?

In your case, you have separated the feature types by providing them in two different files.

**Comment by robblis** [comment]
Hi @fabiovin ,

Thank you for your response.

If I use SampledExistingLandUseDataSet as the main feature type, I don't have any errors returned.

http://agsinspire1.esri.com/arcgis/rest/services/LUTest/MapServer/exts/InspireFeatureDownload/service?REQUEST=GetFeature&SERVICE=WFS&VERSION=2.0.0&TYPENAMES=selu:SampledExistingLandUseDataSet&namespaces=xmlns(selu,http://inspire.ec.europa.eu/schemas/selu/4.0)


If I use ExistingLandUseSample as the main feature type, I get the errors indicated in this issue. We have the following service available for testing.

http://agsinspire1.esri.com/arcgis/rest/services/LUTest/MapServer/exts/InspireFeatureDownload/service?REQUEST=GetFeature&SERVICE=WFS&VERSION=2.0.0&TYPENAMES=selu:ExistingLandUseSample&namespaces=xmlns(selu,http://inspire.ec.europa.eu/schemas/selu/4.0)


I have been testing each callable feature type from each theme available to test in the Validator.

Please let me know what your thoughts are on this and if we are not supposed to test some of the feature types through the Validator.

Thanks,
Robert

**Comment by fabiovin** [comment]
Dear @robblis,

I revised the ATS and I think we can consider your implementation as correct.

The ExistingLandUseSample feature types are linked to the relevant SampledExistingLandUseDataSet feature type through the "dataset" association.
I just would suggest you also link the SampledExistingLandUseDataSet feature types with the relevant ExistingLandUseSample feature types through the "member" association.

@carlospzurita, I updated the ATS, could you please update the relevant ETS?

Thanks,
Fabio

**Comment by robblis** [comment]
Hi @fabiovin ,

I updated our ETS and I now see the member element linked to the relevant ExistingLandUseSample feature types. 

I re-ran the validator tests with the same requests as in my previous posts. I'm still getting the same error in the Validator. If the changes have not made it to the staging validator site, then please let me know when that will be and I will test at that point.

I've attached the returned XML from both requests and the Validation report. The services are still online if you need to test.

Thanks,
Robert

[LU_ExistingLandUseSample_ValidationTestResults.zip](https://github.com/INSPIRE-MIF/helpdesk-validator/files/6673523/LU_ExistingLandUseSample_ValidationTestResults.zip)

**Comment by fabiovin** [comment]
Hi @robblis,

the changes are not yet available in the staging instance, we will notify you when they are.

Fabio

**Comment by arantzaetxebarria** [comment]
Dear @robblis 

The ETS has been updated with a fix for this issue on the staging instance. Could you please test again and verify?

Thanks.

**Comment by robblis** [comment]
Hi @arantzaetxebarria ,

I just did a re-test and I don't see the error anymore.

Thanks for the fix,
Robert

**Comment by arantzaetxebarria** [comment]
Dear @robblis

Thank you for your comment, we are moving it into production instance.

Kind regards.
