### ISSUE TITLE
Error uploading XML metadata generated using ArcGIS Pro 2.6.2

### ISSUE THREAD

**Issue by joey-geoloog** [INSPIRE-MIF/helpdesk-validator#441]
When uploading an INSPIRE-compliant metadata file from ArcGIS Pro 2.6.2, the validator rejects the upload with the response "Upload failed, unknown error"

Steps to Reproduce Issue:

1. Export XML metadata file from ArcGIS Pro 2.6.2
2. Choose assessment class: Metadata (TG version 1.3) – Conformance class: INSPIRE Profile based on EN ISO 19115 and EN ISO 19119 *or* Metadata (TG version 2.0) – Common Requirements for ISO/TC 19139:2007 based INSPIRE metadata records 
3. Upload to INSPIRE validator
4. Upload fails

n.b. Changing title, populating tags, and altering Test Suite Parameters to *.xml did not work. Zipping metadata and uploading as a zip file also failed.

Browser details:
Google Chrome - Version 86.0.4240.183 (Official Build) (64-bit)
Running on Windows 10 Education build 19041.572 version 2004

Data / Screenshots
- Metadata file as sent to JRC INSPIRE SUPPORT at 02/11/2020 09:34 CET [GMT+1] (contains project confidential information)
- Screenshot of error:

![validatorerror](https://user-images.githubusercontent.com/70319311/98341414-13940c80-200f-11eb-9940-ce632d4994e6.png)

**Comment by carlospzurita** [comment]
Dear @joey4247 

We as a helpdesk team have not access to that mail account. If the information is confidential and can't be shared in here, can you please send us a sample metadata to the mail carlospalma@guadaltel.com? That way we can look into it with detail.

Thank you.

**Comment by joey-geoloog** [comment]
Dear @carlospzurita 
Sure thing, no problem. I have sent all of the files that I attempted to validate, which all failed with the same error.
Thanks

**Comment by fabiovinci** [comment]
Dear @joey4247,

do you still have errors uploading metadata?

**Comment by joey-geoloog** [comment]
@fabiovinci - Thanks for the update! I had almost forgotten about it.
Yes, files upload successfully now. Thanks for fixing this.
