### ISSUE TITLE
AM Theme Direct WFS GetProperty Request Fails with Generated Request

### ISSUE THREAD

**Issue by robblis** [INSPIRE-MIF/helpdesk-validator#442]
We're running a Direct WFS Test against the AM theme.

If fails with the following:
OGC TEAM Engine reported a failed test: Node has unexpected [local name] value. expected [ValueCollection] but found [ExceptionReport]

The following is the request that was generated. 

service=WFS&version=2.0.0&request=GetPropertyValue&count=100&typenames=ns67:ManagementRestrictionOrRegulationZone&namespaces=xmlns(xml,http://www.w3.org/XML/1998/namespace),xmlns(gml,http://www.opengis.net/gml/3.2),xmlns(ns67,http://inspire.ec.europa.eu/schemas/am/4.0),xmlns(wfs,http://www.opengis.net/wfs/2.0)&valuereference=@gml:id      

However, if I add the namespace and feature in front of the "@gml:id" I do get a returned valueCollection as shown below.

service=WFS&version=2.0.0&request=GetPropertyValue&count=100&typenames=ns67:ManagementRestrictionOrRegulationZone&namespaces=xmlns(xml,http://www.w3.org/XML/1998/namespace),xmlns(gml,http://www.opengis.net/gml/3.2),xmlns(ns67,http://inspire.ec.europa.eu/schemas/am/4.0),xmlns(wfs,http://www.opengis.net/wfs/2.0)&valuereference=**ns67:ManagementRestrictionOrRegulationZone**@gml:id

We're not sure what is the solution for this.

I've attached the GetCapabilities xml file.

Thanks for any help provided.

[AM_GetCapabilities.zip](https://github.com/inspire-eu-validation/community/files/5513751/AM_GetCapabilities.zip)

**Comment by carlospzurita** [comment]
Dear @robblis 

This issue is related to the OGC TEAM Engine implementation, for which the INSPIRE validator acts as an intermediary. We would kindly ask you to move this issue to their repository at https://github.com/opengeospatial/teamengine.

Thank you

**Comment by robblis** [comment]
Hi @carlospzurita 

I moved the issue to the OGC Team.

Thank you.

**Comment by iuriemaxim** [comment]
**@robblis Not sure if usefull, but have a look at this** https://mapserver.org/development/rfc/ms-rfc-105.html

![image](https://user-images.githubusercontent.com/20813598/101810088-0c39b480-3b21-11eb-95df-47f5284c98d2.png)

**And you may have a look at this too:**
https://gis.stackexchange.com/questions/292145/how-to-select-featuremember-by-gmlid-in-wfs-2-0

![image](https://user-images.githubusercontent.com/20813598/101810357-60449900-3b21-11eb-95b2-1bc994021a59.png)

**Comment by iuriemaxim** [comment]
@robblis can you please indicate where was this moved to the OGC team?

You may see section "10.2.4.3 valueReference parameter" of the WFS 2.0 standard
https://docs.opengeospatial.org/is/09-025r2/09-025r2.html#164

and section ”7.4.4 XPath expressions” of the FES 2.0 standard
https://docs.opengeospatial.org/is/09-026r2/09-026r2.html#37

By implementing stored querries I found that for complex features, relative XPath must be provided.

**Comment by robblis** [comment]
Hi @iuriemaxim ,

Sorry, just saw this when reviewing open issues.

This was moved to the OGC team in the following issue.
https://github.com/opengeospatial/ets-wfs20/issues/186

The issue has been fixed.

Thanks,
Robert
