### ISSUE TITLE
New UI of the INSPIRE Reference Validator: feedback

### ISSUE THREAD

**Issue by alitka** [INSPIRE-MIF/helpdesk-validator#445]
Related to issue #417 + additional remarks to #423 + #443 .

- [x] used browser and version: Firefox Browser 82.0.3 (64-Bit)
- [x] description of the steps to reproduce
- [x] screenshots illustrating the problem

1. Configure your test > Select the type of metadata record(s) to be tested:
- an accasional or novice user doesn't know the difference between "Network Service" and "Spatial Data Service" (see issue #410 ) > recommendation to rename: "Service"
- an accasional or novice user doesn't know that under "Advanced options" the selection of the Conformance Classes can be found > recommendation to rename: "Select additional conformance classes to be assessed" 
2. Provide the resource to test
- option "Remote file" > recommendation to rename: e.g. "web address (URL)" or "Service URL"
- uploading ZIP files only available for the INSPIRE resources "Metadata" and "Data set" > recommendation to rename: "You can upload a compressed ZIP file (only possible for the INSPIRE resources "Metadata" and "Data set") or enter a service operation with requests to one or more records/features."
- button "start test" > recommendation: color of basic setting "grey"; only if the user upload a valide file or provide an URL the "color" change to "yellow"
3. Start test
- sometimes very long loading & running times or after a couple of minutes an error message is showing, for an occasional or inexperienced user the termination of the running test is not visible or comprehensible, sometime a restart of the test is necessary
- no information about the current status of "test run steps", only the rotating hourglass > recoomendation: show the "monitor test run" (as in the current validator), e.g. as a pop-up window

4. See report 
- incorrect link > "back button" is leading to the current INSPIRE validator page of "[test reports](https://inspire.ec.europa.eu/validator//#test-reports)"
![newGUI_referenceValidator_backButton](https://user-images.githubusercontent.com/29542183/99074861-c983cb80-25b8-11eb-8314-38f5130a41f9.PNG)

5. Search results "test reports"
- "search option" > explanation (e.g. tooltip) of the different "status" (Failed, Passed, Running, Passed-manual, Warning, Info, Skipped, Not applicable, Undefined) 
- "searched term" > if an user provide a label for the test report, it's not possible to filter the test reports according to this label 

![newGUI_referenceValidator_label](https://user-images.githubusercontent.com/29542183/99043239-56655f80-258e-11eb-9716-bc51116a4527.PNG)
![newGUI_referenceValidator_label1](https://user-images.githubusercontent.com/29542183/99043251-5bc2aa00-258e-11eb-9943-2fad1946b385.PNG)
![newGUI_referenceValidator_label2](https://user-images.githubusercontent.com/29542183/99043257-5e250400-258e-11eb-9c42-c596d29b5a00.PNG)

**Comment by MarcoMinghini** [comment]
Dear @alitka,
as you might have already noticed, the new UI has been recently included in the [staging instance](http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/) of the INSPIRE Reference Validator. Starting with the next release scheduled for mid-June (see the release plan [here](https://github.com/INSPIRE-MIF/helpdesk-validator/tree/master/release%20strategy)), the new UI will be also included in the [production instance](https://inspire.ec.europa.eu/validator/).

On behalf of the INSPIRE validation team, I would like to thank you for testing the new UI and providing us with useful feedback and suggestions. As you can see, your comments were highly considered to improve the UI.

I close this issue, but please do not hesitate to open other issues to provide additional feedback, should this be needed.
