### ISSUE TITLE
 New UI of the INSPIRE Reference Validator - feedback

### ISSUE THREAD

**Issue by AntoRot** [INSPIRE-MIF/helpdesk-validator#446]
Please find below my comments concerning #417, in addition to #423, #443 and #445.

**1. Homepage**

- The page heading should be "INSPIRE Validator" and not "INSPIRE Validator - About", as a specific "[About](https://inspire-sandbox.jrc.ec.europa.eu/validator-testbed/about/index.html)" page exists;
- the current item in the breadcrumb is "Test selection" (i.e. _European Commission > INSPIRE > Validator > **Test selection**_). It shoud be either "Validator" (i.e. _European Commission > INSPIRE > Validator_) or "Homepage" (i.e. _European Commission > INSPIRE > Validator > **Home**_);
- also the title inside the head section is "INSPIRE Validator - Test selection". It should be "INSPIRE Validator - Home";
- when clicking on the menu items "Get support" or "More on the INSPIRE Validator" an INSPIRE registry page appears with a different layout and an error message. An information page should instead appear with descriptive details on how to get support (in case of the former menu item) or on additional elements (in case of the latter menu item).

**2. Test selection (or Start test) page**

- the menu item name (i.e. "Start test") should be consistent with the page heading (i.e. "Test selection"). I think that "Start test" is ok for the button, but the menu item name should be "Test selection";
- in case of view services, as the conformance class is only one both for WMS and for WMTS, no need to show the advanced options as the user can't perform any action. However, as it is important to keep the links to the details on the conformance classes in the github repository, those links could be moved in line with the View Service type to be selected. I.e.

   **Select the View Service type***
    - [ ] Web Map Service (WMS) ([more info on the related CC](https://github.com/inspire-eu-validation/view-service/tree/review-ats-tg_3.11/iso-19128))
   - [ ] Web Map Tile Service (WMTS) ([more info on the related CC](https://github.com/inspire-eu-validation/view-service/tree/review-ats-tg_3.11/wmts-1.0.0))

 What above is also applicable for: discovery services, pre-defined Atom, Sensor Observation Service (SOS), Web Coverage Service (WCS).

- in case of download services, once pre-defined WFS is selected, if an user clicks on the only option in the advanced options the conformance classes related to direct WFS appear (see image below).

![immagine](https://user-images.githubusercontent.com/7059416/99190154-4653a880-2765-11eb-8602-341060417476.png)

**Comment by MarcoMinghini** [comment]
Dear @AntoRot,
as you might have already noticed, the new UI has been recently included in the [staging instance](http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/) of the INSPIRE Reference Validator. Starting with the next release scheduled for mid-June (see the release plan [here](https://github.com/INSPIRE-MIF/helpdesk-validator/tree/master/release%20strategy)), the new UI will be also included in the [production instance](https://inspire.ec.europa.eu/validator/).

On behalf of the INSPIRE validation team, I would like to thank you for testing the new UI and providing us with useful feedback and suggestions. As you can see, your comments were highly considered to improve the UI.

I close this issue, but please do not hesitate to open other issues to provide additional feedback, should this be needed.
