### ISSUE TITLE
SDS Metadata ATS "Spatial Resolution": XPath reference correct?

### ISSUE THREAD

**Issue by ghost** [INSPIRE-MIF/helpdesk-validator#449]
Hi everyone,

could someone please confirm that Contextual XPath Reference for "Spatial Resolution" Metadata ATS is correct?

ATS can be found here:
https://github.com/inspire-eu-validation/metadata/blob/2.0/sds/spatial-resolution.md#spatialResolution

Thanks in advance!

**Comment by carlospzurita** [comment]
Dear @DeordD 

Thank your for raising this issue, we are going to check the Metadata TG and get back with a response.

Best.

**Comment by carlospzurita** [comment]
Dear @DeordD 

Sorry for the late response. We checked the TG and the contextual path on the ATS, and it seems correct for us. In your opinion, what is the problem on that requirement?

**Comment by ghost** [comment]
Dear @carlospzurita ,

thanks a lot for the reponse. 

I think that following sentence is bit misleading:

> For services with restriction on the spatial resolution, for each Spatial Resolution element,

because 
1. XPath expression `gmd:identificationInfo[1]/*/gmd:abstract` is not relevant for spatial resolution. This is special case in TG 2.0 because gmd:abstract is used to encode two different requirements.  
2. according to Xpath gmd:abstract could be also encoded in gmd:MD_DataIdentification, which doesn't make any sense for services.
3. "for each" part in requirement is also bit misleading, because multiplicity for gmd:abstract is one: https://github.com/inspire-eu-validation/metadata/blob/2.0/common/resource-abstract.md#abstract. From [this requirement](https://github.com/inspire-eu-validation/metadata/blob/2.0/sds/spatial-resolution.md#spatialResolution) it seems that gmd:identificationInfo multiplicity is one to many. 

I am aware that spatial resolution can't be encoded with current 19139 XML Schema for services.

Hopefully I am reading this requirement correct. I am also aware that this is manual check anyways. In my opinion brief clarification in this issue is sufficient to me and ATS doesn't have to be changed.

**Comment by arbakker** [comment]
Just ran into this issue myself as well, so here is a "me too".

**Comment by fabiovinci** [comment]
Dear @arbakker,

thank you for your feedback, it seems the issue does not require a change in the validator but only a better formulation of the ATS.

I improved the [ATS](https://github.com/inspire-eu-validation/metadata/blob/813ce54da78c31814168fe33f832bb944971a062/sds/spatial-resolution.md) by changing the test method description and specifying better the XPath expression.

Could you please have a look and provide your feedback?
Thanks

**Comment by fabiovinci** [comment]
We integrated the proposed changes in the ATS.
We will close the issue, please reopen it if the changes are not clear.
