### ISSUE TITLE
Validation of metadata document of ISO 19115 profile (SeaDataNet profile)

### ISSUE THREAD

**Issue by enricoboldrini** [INSPIRE-MIF/helpdesk-validator#45]
I'm validating a SeaDataNet XML document, that is a community profile of ISO 19115 metadata (https://www.seadatanet.org/Standards/Metadata-formats/CDI), drafted according to official ISO 19115 rules.
I've found some specific issues executing the metadata related tests, so I opened the following sub-issues:
https://github.com/inspire-eu-validation/ets-repository/issues/183
https://github.com/inspire-eu-validation/ets-repository/issues/184
https://github.com/inspire-eu-validation/ets-repository/issues/185

I've been glad to see that the issues have been lately tagged as "planned". Please let me know if more information/action is needed or could be useful from our side and if an expected schedule for the fix is available. Thanks.

**Comment by inakidiazdecerio** [comment]
Dear @enricoboldrini,

Thank you for your explanations. 

Regarding issue inspire-eu-validation/ets-repository#183, the error disappears if you add the namespace and schema location URI of 'gmd' in the attribute xsi:schemaLocation (see the attached image). For issues inspire-eu-validation/ets-repository#184 and inspire-eu-validation/ets-repository#185, we have been working in a possible solution. We included these two issues for discussion during next subgroup meeting where we will prioritize next developments.

We will come back to you when we have any news.

Regards.

![image](https://user-images.githubusercontent.com/36446028/57079783-5d50b800-6cf1-11e9-9922-e0e9863af74e.PNG)

**Comment by josemasensio** [comment]
Dear @enricoboldrini,

We are happy to announce that the solution for this issue has been implemented in the INSPIRE Validator. The solution passed our quality controls, but we will appreciate if you could test it and give us some feedback. You can test the solution in the staging environment:

http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/

Thanks in advance for your help.

**Comment by enricoboldrini** [comment]
Thank you very much for having advanced the support for community profiles!
Here is the updated situation after some tests:

inspire-eu-validation/ets-repository#183
Error still present, I can't change the schema location, as the schemata used to validate the document are a super set of ISO 19139. Changing the schema location to ISO 19139 schemata only, it will not validate any more community extensions.

inspire-eu-validation/ets-repository#184
The CRS code is now correctly tested. However EPSG:4326 seems not to be supported. Are there any plans to support it?

inspire-eu-validation/ets-repository#185
Solved!

Thank you for the effort, I hope the remaining issues will be closed soon.

**Comment by josemasensio** [comment]
@enricoboldrini thank you for your feedback. About the issues:

inspire-eu-validation/ets-repository#183
If the XML doesn't have the namespace and the schema location URI of 'gmd' in xsi:schemaLocation attribute, the error will not be solved.

inspire-eu-validation/ets-repository#184
The test checks that the CRS code has one of the following values:
'http://www.opengis.net/def/crs/EPSG/0/4936', 'http://www.opengis.net/def/crs/EPSG/0/4937', 'http://www.opengis.net/def/crs/EPSG/0/4258', 'http://www.opengis.net/def/crs/EPSG/0/3035', 'http://www.opengis.net/def/crs/EPSG/0/3034', 'http://www.opengis.net/def/crs/EPSG/0/3038', 'http://www.opengis.net/def/crs/EPSG/0/3039', 'http://www.opengis.net/def/crs/EPSG/0/3040', 'http://www.opengis.net/def/crs/EPSG/0/3041', 'http://www.opengis.net/def/crs/EPSG/0/3042', 'http://www.opengis.net/def/crs/EPSG/0/3043', 'http://www.opengis.net/def/crs/EPSG/0/3044', 'http://www.opengis.net/def/crs/EPSG/0/3045', 'http://www.opengis.net/def/crs/EPSG/0/3046', 'http://www.opengis.net/def/crs/EPSG/0/3047', 'http://www.opengis.net/def/crs/EPSG/0/3048', 'http://www.opengis.net/def/crs/EPSG/0/3049', 'http://www.opengis.net/def/crs/EPSG/0/3050', 'http://www.opengis.net/def/crs/EPSG/0/3051', 'http://www.opengis.net/def/crs/EPSG/0/5730', 'http://www.opengis.net/def/crs/EPSG/0/7409'
In your XML file the CRS code has the value 'World Geodetic System 84', this is why the test fails. @MarcoMinghini the test will support other values in the CRS code for a SeaDataNet XML document?

Thank you and best regards.

**Comment by enricoboldrini** [comment]
Thank you for the follow-up.

About inspire-eu-validation/ets-repository#183 I've changed the schema location to:  xsi:schemaLocation="http://www.seadatanet.org http://schemas.seadatanet.org/Standards-Software/Metadata-formats/SDN2_CDI_ISO19139_11.0.0.xsd http://www.isotc211.org/2005/gmd http://schemas.opengis.net/iso/19139/20060504/gmd/gmd.xsd" and both passed the test and validated against community schemas, so this might be a viable workaround!

Please note that if the schemas are reversed in order the workaround will not work (this seems a bug in the validator). Example given, the following will not pass the test:
 xsi:schemaLocation="http://www.isotc211.org/2005/gmd http://schemas.opengis.net/iso/19139/20060504/gmd/gmd.xsd http://www.seadatanet.org http://schemas.seadatanet.org/Standards-Software/Metadata-formats/SDN2_CDI_ISO19139_11.0.0.xsd">

However, it still seems strange to mandate http://schemas.opengis.net/iso/19139/20060504/gmd/gmd.xsd schema directly in the schema location (because that schema is being already imported by http://schemas.seadatanet.org/Standards-Software/Metadata-formats/SDN2_CDI_ISO19139_11.0.0.xsd). Let me know if you are willing to consider the resolution of imports in the near future, otherwise we will have to proceed with the suggested workaround.

Thank you very much for the productive discussion.

**Comment by josemasensio** [comment]
@enricoboldrini the suggested solution looks fine to me.

Thank you and regards.

**Comment by MarcoMinghini** [comment]
**2017.4 meeting 2019-05-22**

After the meeting and the discussion that followed, this is the summary:

- [#183](https://github.com/inspire-eu-validation/ets-repository/issues/183): solved
- [#184](https://github.com/inspire-eu-validation/ets-repository/issues/184): we keep the discussion open on whether the test should be relaxed (to allow not only gco:CharacterString or gmx:Anchor as child elements of the Code element)
- [#185](https://github.com/inspire-eu-validation/ets-repository/issues/185): solved

**Comment by enricoboldrini** [comment]
Great job, thanks. Could you provide some approximate date or steps needed for the resolution of issue https://github.com/inspire-eu-validation/ets-repository/issues/184 ? Thank you very much,
Enrico

**Comment by bilbomaticaue** [comment]
Dear @enricoboldrini,

I think that the possible solution should be discussed at the next subgroup meeting. 

On the other hand, just remember you that the changes for issues [#184](https://github.com/inspire-eu-validation/ets-repository/issues/184) and [#185](https://github.com/inspire-eu-validation/ets-repository/issues/185) are ready for testing in staging. We have added them in the community changelog.

Best regards.

**Comment by josemasensio** [comment]
Dear @enricoboldrini,

The changes to solve the issue [#184](https://github.com/inspire-eu-validation/ets-repository/issues/184) are ready. You can test the solution in the staging environment:

http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/

Some feedback from you will be very appreciated.

Thank you and best regards.

**Comment by enricoboldrini** [comment]
I confirm that change worked fine. Thank you very much! When the changes will be available in the official environment? (a rough estimate will be helpful as well)

**Comment by enricoboldrini** [comment]
I have tested an additional metadata profile in use by the SeaDataNet community, called CSR. In this case the validator gives error during the upload file phase just at the beginning, preventing the actual tests to be executed. The cause could be that this profile uses as well the second part of ISO 19115 (ISO19115-2, gmi package). I'm attaching the file raising the issue.
[inspire.zip](https://github.com/inspire-eu-validation/community/files/3265899/inspire.zip)

**Comment by josemasensio** [comment]
@enricoboldrini could you open a new issue explaining the file upload problem?

@MarcoMinghini can we mark this issue and the [#184](https://github.com/inspire-eu-validation/ets-repository/issues/184) as solved?

**Comment by MarcoMinghini** [comment]
Yes, I suggest to mark this issue as solved and I ask @enricoboldrini open a separate one for the new problem. Thank you.

**Comment by enricoboldrini** [comment]
Sure, I've opened https://github.com/inspire-eu-validation/community/issues/65
Thank you again for the effort in solving the above issues.
