### ISSUE TITLE
Flag the issues concerning the deployment of INSPIRE Validator

### ISSUE THREAD

**Issue by ghost** [INSPIRE-MIF/helpdesk-validator#450]
Hi everyone,

is there a possibility to flag all isses (opened and closed) concernig discussion on INSPIRE Validator deployment?

Some examples are:
- https://github.com/inspire-eu-validation/community/issues/311 
- https://github.com/inspire-eu-validation/community/issues/418
- https://github.com/inspire-eu-validation/community/issues/401

It is pretty hard to filter for those issues in the validator.

Thanks a lot in advance!

**Comment by carlospzurita** [comment]
Dear @DeordD 

Thank you for your suggestion on the improvement of the community space. We are going to check internally to see if we can apply this modification in the helpdesk management.

Best.

**Comment by carlospzurita** [comment]
The label "deployment" has been created for this purpose. We are closing this issue as a result.

Kind regards.
