### ISSUE TITLE
What is the strategy for the validator to cope with the http to https forwarding of all schema requests as of march 2021?

### ISSUE THREAD

**Issue by o2idev** [INSPIRE-MIF/helpdesk-validator#451]
Hi there,

we had quite some unsolved trouble with the redirects for codelists already (#351 closed for now since we and our customers treat the errors as ignorable warnings right now).
Will it be implemented in the docker image's request interceptor architecture?

See https://inspire.ec.europa.eu/forum/discussion/view/269804/migration-of-inspire-schemas-from-http-to-https for details on the planned forwarding.

Thanks a lot
Andreas :)

**Comment by carlospzurita** [comment]
Dear @o2idev 

The expected scenario in March 2021, as described in the link that you posted, is that the HTTP availability of INSPIRE schemas will be brought down, and every HTTP reference will be redirected to HTTPS, as it is happening with the rest of INSPIRE resources right now.

The validator is now working under the assumption of this scenario, so all HTTP requests to the schemas (and all other INSPIRE resources) are intercepted and sent to HTTPS on the Docker image, as shown in the [diagram](https://github.com/inspire-eu-validation/community/issues/311#issuecomment-721706970) posted on issue #311.

The organizations that develop tools for INSPIRE shall take into account that these redirections are happening for the INSPIRE registry, and will happen in March 2021 for the schemas, so they need to provide support for this redirection.

**Comment by MarcoMinghini** [comment]
As planned, the automatic redirection of schemas from http to https has become effective as of March 1, 2021. We therefore close this issue - in case of problems on this, please feel free to open a new issue in the [general helpdesk](https://github.com/INSPIRE-MIF/helpdesk).
