### ISSUE TITLE
Validation against new version of apiso.xsd (v1.0.2 Update ISO 19139 schemaLocation)

### ISSUE THREAD

**Issue by ghost** [INSPIRE-MIF/helpdesk-validator#453]
Hi everyone,

apiso.xsd (http://schemas.opengis.net/csw/2.0.2/profiles/apiso/1.0.0/apiso.xsd) has been updated in order to solve problem in https://github.com/inspire-eu-validation/community/issues/246. 
![grafik](https://user-images.githubusercontent.com/38787131/99782601-a9548f00-2b19-11eb-9688-9c7bfff5d157.png)

Information regarding update can be found [here](https://github.com/opengeospatial/ets-19139/issues/20#issuecomment-730795456).

Could someone please check if updated [apiso.xsd](http://schemas.opengis.net/csw/2.0.2/profiles/apiso/1.0.0/apiso.xsd) can be used for TG 2.0 metadata validation ([XML-Schema](https://github.com/inspire-eu-validation/metadata/blob/2.0/common/xml-schema.md) validation)?

Kind regards,
Dejan

**Comment by fabiovin** [comment]
Dear @DeordD,
thank you for the information.

It works for metadata validation using desktop tools (I tested it with oXygen).
We will test it in the validator instead of our [temp version](http://inspire.ec.europa.eu/draft-schemas/inspire-md-schemas-temp/apiso-inspire/apiso-inspire.xsd).

Regards,
Fabio

**Comment by arantzaetxebarria** [comment]
Dear @DeordD 

The update of metadata 2.0 xml schema validation is in [staging](http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/test-selection/index.html) instance, pointing to the apiso.xsd. Could you please verify?
Thanks

**Comment by ghost** [comment]
I can confirm that metadata 2.0 xml schema validation ("md common req. C1: XML Schema") in staging instance is pointing to the apiso.xsd.
![image](https://user-images.githubusercontent.com/38787131/116505149-7679a880-a8ba-11eb-8ca1-c0f73fd7a718.png)

Metadata record has been succesfully validated against the schema. 

`"29.04.2021 05:08:27 - "Test Assertion 'md common req C.1: XML Schema': PASSED - 28591 ms"`

Maybe it would be good to update ATS. It seems that the change hasn't been documented [here](https://github.com/inspire-eu-validation/metadata/blob/2.0/common/xml-schema.md).

**Comment by dperezBM** [comment]
Dear @DeordD,

Thank you for your feedback. We updated the corresponding ATS. 

Best regards.
