### ISSUE TITLE
WFS 2.0 Conformance Test: Different test results for the same resource

### ISSUE THREAD

**Issue by Kate-Lyndegaard** [INSPIRE-MIF/helpdesk-validator#455]
Hi,
I am currently having difficulties testing the following WFS: https://haleconnect.com/ows/services/org.918.cc100895-4a04-4602-a94f-8b955d136893_wfs?SERVICE=WFS&REQUEST=GetCapabilities&VERSION=2.0.0

I have tested the same service several times in the production instance of the validator, and I have noticed several different behaviours:

1. There is a timeout reported before any test result appears
2. I receive test results which indicate the test suite was not executed: https://inspire.ec.europa.eu/validator/v2/TestRuns/EID96ec2f99-b4a3-4698-b3db-4907d543d57b.html
![grafik](https://user-images.githubusercontent.com/36956461/99977900-89390000-2da5-11eb-9d68-f0ea857327da.png)
3. I receive test results which do not subsequently appear in the list of reports

I understand that the staging instance is using the API. In the staging instance, I receive the following:
1. http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp//v2/TestRuns/EID6af00392-227b-4031-a069-4e5f09fea553.html

Where do you recommend that I test the resource? Any insight would be greatly appreciated.
Thank you again.

Kind regards,
Kate

**Comment by carlospzurita** [comment]
Dear @Kate-Lyndegaard 

As you can see on the Test Report, this test is executed on the TEAM engine instance from the OGC. The ETF is just acting as a client for their API. The difference between staging and production is that they are using different endpoints for the TEAM engine: one is their official release, and the other one is the beta instance.

We are going to check directly on the OGC site and try to validate your service, to check if there is a problem in the communication between the validator and this service.

**Comment by fabiovinci** [comment]
Dear @Kate-Lyndegaard,

is the issue still present?

**Comment by Kate-Lyndegaard** [comment]
@fabiovinci This issue can be closed. Thank you!
