### ISSUE TITLE
How to speed up the tests?

### ISSUE THREAD

**Issue by axel584** [INSPIRE-MIF/helpdesk-validator#456]
We have 120,000 xml files to validate and I made a batch to be able to execute them one after the other. It needs 30 seconds to 1 minute for each validation. Which makes, according to my estimate, 20 days to validate all the files.
Do you have any advice for me to speed up treatment?
I tried multithreading but it doesn't seem to change the total time.
Thanks for your help,
Axel Rousseau

**Comment by carlospzurita** [comment]
Dear @axel584 

Are you using a local instance, or are you sing the reference validator at inspire.ec.europa.eu/validator/ ?

And are you aware of the [bulk validation tool](https://github.com/inspire-eu-validation/monitoring-bulk-validation-tool/commits/master) released by the JRC? This was the tool used for the Monitoring and Reporting activity, and it can be configured to point to a local deployment. This make use of a multi-threaded approach, and sends validations up to the limit of concurrent Test Runs the validator instance supports.

**Comment by axel584** [comment]
I use a local instance (in a docker container)
I'll try the bulk validation tool.
Thank you,
Axel

**Comment by dperezBM** [comment]
Dear @axel584,

Thank you for your feedback. We hope that the answer you were given would have helped you. In case you have any other questions or problems, please feel free to open a new issue.

Best regards.
