### ISSUE TITLE
gmlas.b.2: validate XML documents - Error for gml:ReferenceTypes

### ISSUE THREAD

**Issue by CarmentaVilliam** [INSPIRE-MIF/helpdesk-validator#459]
Before reporting an issue with the INSPIRE validator deployed at JRC, please check the [list of known limitations](https://github.com/inspire-eu-validation/community/wiki/Known-limitations).

I've implemented the Adminstrative Units 4.0 schema and when I'm validating I encounter a error which does not make sense to me. In the XSD definition for _nationalLevel_ the _type="gml:ReferenceType"_.

![image](https://user-images.githubusercontent.com/49949050/100240045-67b94f00-2f32-11eb-9ea8-cafe14ed7218.png)

My output gives me,

![image](https://user-images.githubusercontent.com/49949050/100240308-b666e900-2f32-11eb-94eb-346e2596bdff.png)

yet the validator gives me,

 cvc-type.3.1.1: Element 'au:nationalLevel' is a simple type, so it cannot have attributes, excepting those whose namespace name is identical to 'http://www.w3.org/2001/XMLSchema-instance' and whose [local name] is one of 'type', 'nil', 'schemaLocation' or 'noNamespaceSchemaLocation'. However, the attribute, 'xlink:href' was found.

To me this seems like an incorrect error message or is the validator not compliant with 4.0 schemas?

To help us investigate the issue, you may want to include:

- [x] a description of the steps to reproduce your issue
- [x] the browser and version used
    - Firefox 83.0
- [x] a screenshot illustrating the problem
- [ ] the Test Report (ideally as an attachment to the issue)
- [x] the name of the Test that failed or better: change the `Level of Detail`
in the Report by clicking on `All Details`, then scroll down to the failed test
and copy the Link on the right-hand side of the `Assertion URI`
    - https://inspire.ec.europa.eu/validator//v2/TestRuns/EIDc874db13-bfb0-4c4d-9f82-46c88e7868a7.html?lang=en#EID5310c9bd-990b-4ac9-801b-fd824db7dd0f
- [x] the URL of your service / the file you have uploaded or referenced (as
an attachment).
    - Can provide if needed

If your service is protected or you have confidential data that you cannot
upload here, you can request an email address to which you can send URLs / files.
Please note that issues cannot be investigated for services/datasets that we cannot
access.

**Comment by carlospzurita** [comment]
Dear @CarmentaVilliam 

Thank you for raising this issue. We are analyzing the schema validation for your dataset. We will come back to you with more feedback after the investigation.

Best regards.

**Comment by carlospzurita** [comment]
Dear @CarmentaVilliam 

It seems that the error of the referenceType can be solved adding on the schemaLocation at the top the XSD for the schema `http://inspire.ec.europa.eu/schemas/au/4.0/AdministrativeUnits.xsd` after the `http://inspire.ec.europa.eu/schemas/au/4.0/` string. We made a test using your dataset and the message disappeared.

**Comment by CarmentaVilliam** [comment]
Why didn't I think of that... :D It works very well the way you suggested. Given how I don't control the creation of the _wfs:featurecollection_ response I cant add it to the _xsi:schemaLocation_ attribute. But i also realized that the response from the describe feature was not returning the correct AdministrativeUnit definition. I fixed that on my end and when it returned the definition from the AdministrativeUnit.xsd the validator stopped complaining.

Thank you for all the help!

edit: you can close this issue.

//Villiam
