### ISSUE TITLE
Validation error for TM_Period <gml:endPosition indeterminatePosition="unknown"/>

### ISSUE THREAD

**Issue by percursoaleatorio** [INSPIRE-MIF/helpdesk-validator#46]
The use of 

     <gml:endPosition indeterminatePosition="unknown"/>`
	 
returns a validation error

	The following properties of the feature have an empty value: endPosition. While this is valid against the XML schema, this is not valid according to the GML model. Please correct the process that generates the GML documents.

The validation error appears to be incorrect because:

- The GML elements for describing time positions (beginPosition and endPosition) include the indeterminatePosition attribute that can have values of before, after, now, and unknown. This attribute can be used with a time value to express uncertain times (see [link](https://wiki.earthdata.nasa.gov/display/NASAISO/Dates)).

- This option is explicitly described in the [AreaManagementRestrictionRegulationZone](http://inspire.ec.europa.eu/schemas/am/4.0/AreaManagementRestrictionRegulationZone.xsd) schema. See documentation for the designationPeriod element.

- The encoding is currently used in the EU Air Quality reporting (see [page 73](https://www.eionet.europa.eu/aqportal/doc/UserGuide2_AQD_XML_v3.4.1.pdf)).

Therefore, a time period with uncertain end can be encoded as  <gml:endPosition indeterminatePosition="unknown"/> and one wouldn't expect a validation error.

The test GML file and test results are in file attached: [endPeriod.zip](https://github.com/inspire-eu-validation/community/files/3147266/endPeriod.zip)

Could you help us understand what the issue is, and how to correct it?

**Comment by josemasensio** [comment]
Dear @percursoaleatorio,

Thank you for your message.

We have been reviewing the issue. The problem is not the indeterminatePosition attribute, the validation error appears because the gml:endPosition element is empty. 

If you add text to the element (see the attached image) the error is solved.

Best regards.

![endposition](https://user-images.githubusercontent.com/50206416/57221047-e459a500-6ffd-11e9-8cf1-bf172109c354.PNG)

**Comment by percursoaleatorio** [comment]
Hi, thanks for the quick reply and the workaround :-)

Indeed, the following examples now pass the validation:

- `<gml:endPosition indeterminatePosition="unknown">unknown</gml:endPosition>`
- `<gml:endPosition indeterminatePosition="unknown">It looks like any text can go here</gml:endPosition>`

The flexibility is welcome, but seems to contradict the type documentation in http://schemas.opengis.net/gml/3.2.1/base/temporal.xsd

```
<simpleType name="TimeIndeterminateValueType">
<annotation>
<documentation>
	These values are interpreted as follows: 
	-	"unknown" indicates that no specific value for temporal position is provided. 
	-	"now" indicates that the specified value shall be replaced with the current temporal position whenever the value is accessed. 
	-	"before" indicates that the actual temporal position is unknown, but it is known to be before the specified value. 
	-	"after" indicates that the actual temporal position is unknown, but it is known to be after the specified value. 
	A value for indeterminatePosition may -	be used either alone, or -	qualify a specific value for temporal position.
</documentation>
</annotation>
<restriction base="string">
<enumeration value="after"/>
<enumeration value="before"/>
<enumeration value="now"/>
<enumeration value="unknown"/>
</restriction>
</simpleType>
```

It also doesn't match the example in page 32 of the “D2.8.III.11 INSPIRE Data Specification on Area Management/Restriction/Regulation Zones and Reporting Units – Technical Guidelines” version 3.0

```
<am:designationPeriod>
  <gml:TimePeriod gml:id="UK0039_TP">
    <gml:beginPosition>2011-10-01</gml:beginPosition>
    <gml:endPosition indeterminatePosition="unknown"/>
  </gml:TimePeriod>
</am:designationPeriod>
```

So this is a bit confusing...
Could you please clarify if the example in the AM 3.0 specification is formally wrong? (i.e. if it it would never validate against the GML schema)

Many thanks, n.

**Comment by josemasensio** [comment]
I wouldn't say that the example of the AM 3.0 specification is wrong.

The attribute 'indeterminatePosition' on element 'gml:endPosition' should be after, before, now or unknown. If this attribute has another value, the test fails and the validator displays the message with the error.

However, the ATS of [GML model](https://github.com/inspire-eu-validation/data/blob/master/schemas/gml-model.md) says that 'Inspect each property element and verify that it either carries a URI reference to an object (@xlink:href), contains one or more object elements as child elements or contains a non-empty text node'. 

As the node is empty, the test fails. 

Best regards.

**Comment by percursoaleatorio** [comment]
Hi again, thanks for the clarification, I see your point 

So, if the example in the AM 3.0 specification is not wrong, then the problem appears to be the test specification of [emptyValue](https://github.com/inspire-eu-validation/data/blob/master/schemas/gml-model.md#emptyValue) :

> Inspect each property element and verify that it either carries a URI reference to an object (@xlink:href), contains one or more object elements as child elements or contains a non-empty text node (whitespace is trimmed before checking for empty text). Otherwise report emptyValue.

If I understand correctly, <gml:endPosition indeterminatePosition="unknown"/> gets flagged as an "emptyValue" error, because the indeterminatePosition attribute is not taken into account.

Do you foresee that this situation will be corrected?
(i.e., that the test will include an exemption for TM instants with indeterminatePosition="unknown" or indeterminatePosition="now" )
Many thanks, n.

**Comment by josemasensio** [comment]
@percursoaleatorio we are going to discuss the solution in the next subgroup meeting and see if the test should be corrected.

Best regards.

**Comment by MarieLambois** [comment]
The content of endPosition is of type gml:TimePositionType, which extends gml:TimePositionUnion, defined as :
`<simpleType name="TimePositionUnion">
<annotation>
<documentation>The simple type gml:TimePositionUnion is a union of XML Schema simple types which instantiate the subtypes for temporal position described in ISO 19108.An ordinal era may be referenced via URI. A decimal value may be used to indicate the distance from the scale origin . time is used for a position that recurs daily (see ISO 19108:2002 5.4.4.2).Finally, calendar and clock forms that support the representation of time in systems based on years, months, days, hours, minutes and seconds, in a notation following ISO 8601, are assembled by gml:CalDate</documentation>
</annotation>
<union memberTypes="gml:CalDate time dateTime anyURI decimal"/>
</simpleType>
`
So I am not sure that any text should be allowed. 

Maybe the test empty value should not be applied to endPosition.

**Comment by josemasensio** [comment]
Dear @percursoaleatorio,

We are happy to announce that the solution for this issue has been implemented in the INSPIRE Validator. The solution passed our quality controls, but we will appreciate if you could test it and give us some feedback. You can test the solution in the staging environment:

http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/

Thanks in advance for your help.

**Comment by MarcoMinghini** [comment]
**2017.4 meeting 2019-05-22**

It is agreed that, if the value of the `indeterminatePosition` attribute is `unknown `or `now`, the test should not check the presence of the empty value.

**Comment by inakidiazdecerio** [comment]
@MarcoMinghini should the test only check the 'unknown' and 'now' values? We have modified the ETS to validate the following values:

- unknown
- now
- after
- before

Please see the comment https://github.com/inspire-eu-validation/community/issues/46#issuecomment-489714364, reference to the four values (previously listed) of an enumeration element.

**Comment by josemasensio** [comment]
@MarcoMinghini should the test only check the 'unknown' and 'now' values? We have modified the ETS to validate the following values:

- unknown
- now
- after
- before

Please see the comment https://github.com/inspire-eu-validation/community/issues/46#issuecomment-489714364, reference to the four values (previously listed) of an enumeration element.

**Comment by MarcoMinghini** [comment]
From the previous discussion and the discussion at the meeting last week, I understand that:

- the test should check that the attribute `indeterminatePosition` on element `gml:endPosition` is `after`, `before`, `now `or `unknown`. If this attribute has another value, the test fails. This is already implemented and is correct.
- if the values are `after` or `before`, there must be a value specified (i.e. the date before/after which the temporal position is known to be). So, the test should check that this value is non-empty.
- if the values are `now` or `unknown`, then it makes no sense to specify a date (because either the date is now, or the date is unknown). This is where the test should be relaxed, as proposed by @percursoaleatorio.

**Comment by josemasensio** [comment]
Ok @MarcoMinghini. We are going to modify the test (in staging) to validate only 'now' and 'unknown' values.

Regards.

**Comment by josemasensio** [comment]
Dear @percursoaleatorio, did you have a chance to test the solution? Some feedback from you will be very appreciated. Thanks!

**Comment by percursoaleatorio** [comment]
Hello, 
I run some tests in the staging environment.

- With a correct GML file using <gml:endPosition indeterminatePosition="unknown"/> 
  No error was flagged in the [results](http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/v2/TestRuns/EIDcc42cbf6-2277-4970-a2f1-fb0e9422031a.html) .

- With a GML with minor changes (see below).  No error was flagged in the [results](http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/v2/TestRuns/EIDfe45df72-32e3-4c2f-8fc9-9e47d981251f.html) .
  test1. <gml:endPosition indeterminatePosition="unknown"></gml:endPosition>
  test2. <gml:endPosition indeterminatePosition="now"/> 
  test3. <gml:endPosition indeterminatePosition="unknown">bla-bla-bla</gml:endPosition>

So, for the scope of the present ticket, I think that the issue is solved and the solution can be deployed to production.

Many thanks for solving this, n. :-)

P.S. your staging environment is not allowing file uploads.
P.P.S: with regard to test3 above, and taking into consideration the concern raised by @MarieLambois, 
you might what to clarify if indeed text should be allowed.

**Comment by josemasensio** [comment]
@percursoaleatorio thank you for your feedback.

We will investigate why the staging environment is not allowing file uploads.
