### ISSUE TITLE
Coupled Resource error

### ISSUE THREAD

**Issue by marcingrudzien** [INSPIRE-MIF/helpdesk-validator#462]
Dear Colleagues,
 
I validate network service metadata http://mapy.geoportal.gov.pl/wss/service/CSWINSP/guest/CSWStartup?SERVICE=CSW&REQUEST=GetRecordById&VERSION=2.0.2&ID=91710ff0-bad2-11e1-afa6-0800200c9a66&OUTPUTFORMAT=application/xml&OUTPUTSCHEMA=http://www.isotc211.org/2005/gmd&ELEMENTSETNAME=full
Using INSPIRE validator https://inspire.ec.europa.eu/validator/
 
It returns an error
![error](https://user-images.githubusercontent.com/25637709/100600997-57262180-3302-11eb-8791-be7042af3945.PNG)

When I analysed the error I noticed that the error description is not correct. According to the description, the media type returned by metadata catalogue is application/octet-stream whereas, in reality, it is application/xml.
 
Additionally, when I validate the same metadata record on the version of validator 2020.03 installed in our premises such error is not reported.

For testing, I use Google Chrome 86.0.4240.198.
 
Can you investigate the issue and let us know whether the tested metadata record is correct? Or if the error is valid please explain what has to be corrected.

Please find attached test reports from public inspire validator and the version of validator installed in our premisses.
[Reports.zip](https://github.com/inspire-eu-validation/community/files/5615531/Reports.zip)

Best regards,
Marcin

**Comment by carlospzurita** [comment]
Dear @marty1357 

Thank you for raising this issue. We are checking the result on the Conformance Class 3 for Metadata both in staging and in a local instance, to compare it to the one that you got on production. We will get back to you with more feedback as soon as we find out anything else for this issue.

**Comment by carlospzurita** [comment]
Dear @marty1357 

We have checked in several different instances, at different premises, and all of them returned the same error as in production. We do not know what could be the origin of this issue.

Is your instance deployed behind a proxy, or in any particular network configuration? That could explain the differences.

**Comment by marcingrudzien** [comment]
Dear @carlospzurita

I also installed the 2020.3.1 version of the validator, and the situation is exactly the same. Local instance returns no errors. The validator is installed locally on Ubuntu 20.04.1 LTS release. Other than that it is difficult for me to find what else I should be looking for. We have many machines like this on our premises, and they are not causing similar errors.

I think that reporting the error, in this case, is not correct. The media type of the [http://mapy.geoportal.gov.pl/wss/service/CSWINSP/guest/CSWStartup?SERVICE=CSW&REQUEST=GetRecordById&VERSION=2.0.2&ID=576c3269-2ba4-49af-bc97-8abf932bba32&OUTPUTFORMAT=application/xml&OUTPUTSCHEMA=http://www.isotc211.org/2005/gmd&ELEMENTSETNAME=full#PL.PZGiK.204.PRNG.GN](http://mapy.geoportal.gov.pl/wss/service/CSWINSP/guest/CSWStartup?SERVICE=CSW&REQUEST=GetRecordById&VERSION=2.0.2&ID=576c3269-2ba4-49af-bc97-8abf932bba32&OUTPUTFORMAT=application/xml&OUTPUTSCHEMA=http://www.isotc211.org/2005/gmd&ELEMENTSETNAME=full#PL.PZGiK.204.PRNG.GN) response returns in Header
Content-Type: application/xml;charset=UTF-8

The issue has been reported to me by many organisations in Poland creating INSPIRE metadata. Please take a look at it because this error significantly reduces our 2020 monitoring results.

Thank you in the advance.

Marcin

**Comment by carlospzurita** [comment]
Dear @marty1357 

Thank you for your feedback. We understand that this issue greatly affects the results from Monitoring and Reporting, and we will prioritize our work on this matter. We will get back to you with more feedback.

**Comment by carlospzurita** [comment]
Dear @marty1357 

We have been debugging this issue, and we got to separately log all response headers that the validator is getting. In the image below you can get an extract of this log

![imagen](https://user-images.githubusercontent.com/10537778/105496957-7ae06500-5cbe-11eb-961a-456f31bdf2be.png)

It seems that the header Content-Type is not available for the test, even though we have checked that the response from the service have them indeed. Because of this, the Content-Type is default to application/octet-stream.

We are not really sure what could be the cause for this behaviour. The most strange thing is that this have worked on your premises, even using the same version of the ETS.

We will keep pushing on and try to discover anything else.

Kind regards.

**Comment by carlospzurita** [comment]
Dear @marty1357 

The monitoring process has been repeated again with some modifications on the frequency of request to the CSW for the Polish metadata, and the results are the same. The reports have been reviewed, and there are some other cases of errors in requirement 3.6. We are checking what are the cases and try to breakdown each type of error that leads to this requirement to fail.

**Comment by marcingrudzien** [comment]
Dear @carlospzurita

Thank you for your work and feedback. Please let me know If there is anything we can do or check on our premises to better diagnose the issue.

**Comment by ukiz** [comment]
Dear @marty1357, @carlospzurita,


To assess the possible impact of this issue on Poland's M&R results I looked at the 207 validation reports with "md sds 3.6 Coupled Resource" error. I found 6 different cases of the error listed in the table below with corresponding counts of affected metadata.

| case | count| description
| --|----- | -----------
| 1 | 87   | HTTP status code 401 Unauthorized
| 2 | 64   | wrong media type
| 3 | 38   | HTTP status code 404 Not Found
| 4 | 12   | not an HTTP or HTTPS URL
| 5 | 5    | certification path problem
| 6 | 1    | 'operatesOn' property

Cases 1 and 3 appear to be reported correctly as I confirmed a few with manual checks. Case 2 - the one reported here by Marcin - is currently under investigation. Cases 4, 5 and 6 need further investigation.

Kind regards,

Lukasz

**Comment by carlospzurita** [comment]
Dear @marty1357 

We are still looking into your issue, but we are meeting many dead ends on this, as we are unable to reproduce the same situation.

We are sending you a modified test file to include in your instance, as a way to get the CSW responses on your instance. If you can, please place the file inside this [attached zip](https://github.com/INSPIRE-MIF/helpdesk-validator/files/5875072/testquery-md.zip) in the path `~/etf/projects/inspire-ets-repository/ets-repository-2021.0/testquery-md.xq`

The `etf` folder is the one that you are setting on the docker run command 

`docker run --name inspire-validator -d -p 8080:8080 -v ~/etf:/etf docker.pkg.github.com/inspire-mif/helpdesk-validator/inspire-validator:2021.0`

After it has been included, please run again the test with the metadata that is causing this issue, and share with us the log of the Conformance Class 3.

If you have any problem, please let us know and we can arrange a meeting and guide you through the process.

Kind regards.

**Comment by marcingrudzien** [comment]
Dear @carlospzurita 

I would be grateful if we can do it together. I am not a Docker expert, and it will save me a lot of time.
Currently, we have another vision of the validator (2020.3.1) installed on our premises. I am not sure whether this will not cause any issues.
If necessary, I can arrange a Zoom meeting.

Best regards,
Marcin

**Comment by marcingrudzien** [comment]
Dear @carlospzurita

I managed to install and run the validator. Where can I find the Conformance Class 3 log?

Regards,
Marcin

**Comment by carlospzurita** [comment]
Dear @marty1357 

If you select "All details" in the test report, you would find a tab at the top of the report named "Log Path: Conformance Class 3", just as shown in the image. Click in it and you it would display the log contents for that conformance class

![imagen](https://user-images.githubusercontent.com/10537778/106010604-ec9f2100-60b9-11eb-8c18-e23713d273b5.png)

If you still have some troubles with this, we can arrange a meeting tomorrow via zoom and check your instance.

**Comment by marcingrudzien** [comment]
Her it is

_Testing 1 records
Executing Test Suite: /etf/projects/inspire-ets-repository/ets-repository-2021.0/metadata/2.0/sds/ets-md-sds-bsxets.xml
Statistics table: 0 ms
Test Suite 'Conformance Class 3: INSPIRE Spatial Data Service baseline metadata.' started
Test Case 'General Metadata' started
Test Assertion 'md sds 3.1: Resource Type': PASSED - 0 ms
Test Case 'General Metadata' finished: PASSED
Test Case 'Identification' started
Test Assertion 'md sds 3.2: Service Identification Element': PASSED - 0 ms
Test Assertion 'md sds 3.3: Spatial Resolution': PASSED_MANUAL - 1 ms
Test Assertion 'md sds 3.4: Spatial Data Service Category': PASSED - 10 ms
Test Assertion 'md sds 3.5: Spatial Data Service Type': PASSED - 0 ms
Checking URL: 'http://mapy.geoportal.gov.pl/wss/service/CSWINSP/guest/CSWStartup?SERVICE=CSW&REQUEST=GetRecordById&VERSION=2.0.2&ID=02799338-da67-4e2f-8606-4f24ffb20402&OUTPUTFORMAT=application/xml&OUTPUTSCHEMA=http://www.isotc211.org/2005/gmd&ELEMENTSETNAME=full#PL.PZGiK.200.PRG.AU'
Checking URL: 'http://mapy.geoportal.gov.pl/wss/service/CSWINSP/guest/CSWStartup?SERVICE=CSW&REQUEST=GetRecordById&VERSION=2.0.2&ID=02799338-da67-4e2f-8606-4f24ffb20402&OUTPUTFORMAT=application/xml&OUTPUTSCHEMA=http://www.isotc211.org/2005/gmd&ELEMENTSETNAME=full#PL.PZGiK.200.PRG.AU'
Final URL: 'http://mapy.geoportal.gov.pl/wss/service/CSWINSP/guest/CSWStartup?SERVICE=CSW&REQUEST=GetRecordById&VERSION=2.0.2&ID=02799338-da67-4e2f-8606-4f24ffb20402&OUTPUTFORMAT=application/xml&OUTPUTSCHEMA=http://www.isotc211.org/2005/gmd&ELEMENTSETNAME=full#PL.PZGiK.200.PRG.AU'
Test Assertion 'md sds 3.6: Coupled Resource': PASSED - 444 ms
Test Case 'Identification' finished: PASSED_MANUAL
Test Case 'Distribution' started
Test Assertion 'md sds 3.7: Resource Locator': PASSED - 1 ms
Test Case 'Distribution' finished: PASSED
Test Case 'Data Quality' started
Test Assertion 'md sds 3.8: Only One Data Quality Element': PASSED - 0 ms
Test Case 'Data Quality' finished: PASSED
Test Suite 'Conformance Class 3: INSPIRE Spatial Data Service baseline metadata.' finished: PASSED_MANUAL_

Testing the same metadata record using public metadata instance [https://inspire.ec.europa.eu/validator/v2/TestRuns/EIDccf541f6-2295-4092-8c1e-09c8f0d47363.html](https://inspire.ec.europa.eu/validator/v2/TestRuns/EIDccf541f6-2295-4092-8c1e-09c8f0d47363.html) returns Couple Resource error.

**Comment by carlospzurita** [comment]
Did you included the file as instructed in the last comment? It should show additional information about the responses the validator is getting from the service

> We are sending you a modified test file to include in your instance, as a way to get the CSW responses on your instance. If you can, please place the file inside this [attached zip](https://github.com/INSPIRE-MIF/helpdesk-validator/files/5875072/testquery-md.zip) in the path `~/etf/projects/inspire-ets-repository/ets-repository-2021.0/testquery-md.xq`
> 
> The `etf` folder is the one that you are setting on the docker run command
>

**Comment by marcingrudzien** [comment]
Yes, I included the file as instructed. 
![Przechwytywanie](https://user-images.githubusercontent.com/25637709/106023789-6ab5f480-60c7-11eb-91d0-66f0ada7d509.PNG)

**Comment by carlospzurita** [comment]
Dear @marty1357 

Can we arrange a meeting today? Please contact us at carlospalma@guadaltel.com and try to schedule it.

Kind regards.

**Comment by carlospzurita** [comment]
Dear @marty1357 

We have continued the investigation on this issue, but we are not getting so much advances on the validator side. Would you kindly do an additional test for us to have a clear picture? We understand that the local instance of the validator you have been using is located under the network of your organization. Is it possible for you to set up a deployment within a network completely separated from your organization network (a domestic network, or an instance in a cloud provider), and check the results there?

Kind regards.

**Comment by marcingrudzien** [comment]
Dear @carlospzurita 

It would be difficult for me from the organisational point of view. I would have to rent a VPS and it would be not easy and first of all time consuming to arrange relevant payments. 

Best regards,
Marcin

**Comment by carlospzurita** [comment]
Dear @marty1357 

Based on our experiments, it seems that the problem may reside on the local network of the organizations that serve the problematic coupled resource - given that it seems impossible for us to replicate the issue from a separated network. It may be due to some firewall configuration on the network of those servers, or some reverse proxy configuration on the organizations that may send different responses to external agents.

We don't see a clear way to keep advancing on this issue without any more insight from inside the network.

**Comment by ukiz** [comment]
Dear @marty1357

I did further investigation about the 64 metadata records with coupled resources "media type" error. It turns out that there are:
- 59 with media type 'application/octet-stream' at 'http://mapy.geoportal.gov.pl/'
- 5 with media type 'text/plain' at 'http://geo.stat.gov.pl/'

Moreover, there are 16 service metadata that passed validation and they DO NOT contain coupled resources in the above two domains. This suggests that the issue may be related to coupled resources located at specific domains.

Kind regards,

Lukasz

**Comment by marcingrudzien** [comment]
Dear @carlospzurita
I will forward the issue to our IT team for further investigation and let you know if they find something.

**Comment by marcingrudzien** [comment]
Dear @carlospzurita 
Our IT guys ask for the IP address used by the validator to send GetRecordById request to our CSW service. Could you provide it?

Marcin

**Comment by carlospzurita** [comment]
The IP for the production instance right now is 54.228.217.96. Take into account that this IP is dynamic and may change from reloading the instance on the cloud provider platform.

**Comment by marcingrudzien** [comment]
Thank you. Just in case if possible can you send entire IP range that may be used in the future.

**Comment by carlospzurita** [comment]
Unfortunately, right now we don't have the feature to restrict the public IP to a range. The only solution for this is to check the IP prefix associated to the region "eu-west-1" and the service "EC2" in the public JSON file of [AWS IP ranges](https://ip-ranges.amazonaws.com/ip-ranges.json), but that doesn't narrow it very much.

**Comment by marcingrudzien** [comment]
After investigating the issue, it has turned out that our firewall was blocking INSPIRE validator. The issue is solved now. Thank you for your support.

**Comment by carlospzurita** [comment]
Dear @marcingrudzien 

We are very happy to hear that the issue has been sorted out. If you encounter any other issues, please let us know.
