### ISSUE TITLE
ATS/ETS for data specifications annex II and III available at production instance in January?

### ISSUE THREAD

**Issue by hogredan** [INSPIRE-MIF/helpdesk-validator#468]
In preparation of re-using the upcoming release 2021.0 in our national validator I was wondering whether ATS/ETS for data specifications annex II and III (those that can already be tested in the staging instance) will be moved to the production instance. According to the release plan available at https://github.com/inspire-eu-validation/community/milestone/8 this is foreseen, isn't it?

**Comment by carlospzurita** [comment]
Dear @hogredan 

Sorry for the delay in the response. All the themes available on staging that has been already been tested by the community will be added to the new release of the validator. You can check the list on https://github.com/inspire-eu-validation/community/issues/336

**Comment by hogredan** [comment]
Dear @carlospzurita 

thank you for the clarification on this point.
