### ISSUE TITLE
AU 4.0 Invalid content for Baseline feature type

### ISSUE THREAD

**Issue by CarmentaVilliam** [INSPIRE-MIF/helpdesk-validator#469]
Before reporting an issue with the INSPIRE validator deployed at JRC, please check the [list of known limitations](https://github.com/inspire-eu-validation/community/wiki/Known-limitations).

I'm running tests on the Baseline feature type for MaritimeUnit inside the AU 4.0 theme. Using the validator I'm getting an _invalid content_ error message (see link to error). I'm having troubles  figuring out from where and why this error appears,  the output is the same as the one for other feature types in the application schema for which there are no errors. 

To help us investigate the issue, you may want to include:

- [X] a description of the steps to reproduce your issue
    - Re-run the test for Baseline
- [X] the browser and version used
    - Firefox 83.0 64bit 
- [X] a screenshot illustrating the problem
    - 
![image](https://user-images.githubusercontent.com/49949050/101764285-2f903f80-3ae0-11eb-8ddf-4bc69e4fb819.png)
![image](https://user-images.githubusercontent.com/49949050/101764330-3c149800-3ae0-11eb-99e2-7c5911ab7eee.png)

- [X] the Test Report (ideally as an attachment to the issue)
    - https://inspire.ec.europa.eu/validator//v2/TestRuns/EIDfa8f4db9-7a08-4e6a-8b92-1369c4180b8d.html?lang=en
- [X] the name of the Test that failed or better: change the `Level of Detail` in the Report by clicking on `All Details`, then scroll down to the failed test and copy the Link on the right-hand side of the `Assertion URI`
    - https://inspire.ec.europa.eu/validator//v2/TestRuns/EIDfa8f4db9-7a08-4e6a-8b92-1369c4180b8d.html?lang=en#EIDcc1e4591-e756-4f5a-bdd2-2914480b9430
- [ ] the URL of your service / the file you have uploaded or referenced (as
an attachment).
    - Can be provided if needed

If your service is protected or you have confidential data that you cannot
upload here, you can request an email address to which you can send URLs / files.
Please note that issues cannot be investigated for services/datasets that we cannot
access.

**Comment by carlospzurita** [comment]
Dear @CarmentaVilliam 

Thank you for raising this issue. Could it be possible to have a sample response of your service with a FeatureCollection? We think that the problem may be in the schema declaration.

If you can provide it, please send it to inspire-helpdesk@bilbomatica.es and we will have a look.

Best.

**Comment by CarmentaVilliam** [comment]
Did you receive the file? I never got a response back on the mail I sent with the file attached.

**Comment by carlospzurita** [comment]
Dear @CarmentaVilliam 

Sorry for the delay on the response. We received indeed the file attached, however we can't use it ass it contains references to localhost, which would not resolve on our premises. Please, we would kindly ask you to send us a new one so we can reproduce the issue.

**Comment by carlospzurita** [comment]
Dear @CarmentaVilliam 

Did you have the opportunity to check our last comment on this issue?

**Comment by CarmentaVilliam** [comment]
Hi @carlospzurita 

At the moment im no longer working on the project and dont have access to the environment in which I ran the tests back then. I would say its safe to close this for now 😃
