### ISSUE TITLE
INSPIRE validator doesn`t recognize SDI Digital certificate- SPAIN

### ISSUE THREAD

**Issue by MarisolGomezAndres** [INSPIRE-MIF/helpdesk-validator#471]
There is some problem  in recognising our SDI certificate from FNMyT as a valid Authorisation Entity and that´s the reason by our metadata and services are not validated. Therefore, if the FNMyT Certification Authorities shoud be  included as a valid Authorisation Entity. We have analysed the validation errors and discover that both the validator and the linnkChecker don´t recognise our certificate.   The same error has happened in the past and you solved it by recognising the Authorisation Entity that we use to securize our SDI,  FNMyT,  as a valid entity in your platform. 

Atacched you can find two  examples URL to  test it:

Watwerbody  PHC 2015-2021: https://wms.mapama.gob.es/sig/agua/PHC/MasasAguaSub2021/wms.aspx?request=getcapabilities
 ATOM download service MAPA/MITECO: https://www.mapama.gob.es/ide/inspire/atom/downloadservice.xml
 

behaviour.

To help us investigate the issue, you may want to include:

- [ ] a description of the steps to reproduce your issue
- [ ] the browser and version used
- [ ] a screenshot illustrating the problem
- [ ] the Test Report (ideally as an attachment to the issue)
- [ ] the name of the Test that failed or better: change the `Level of Detail`
in the Report by clicking on `All Details`, then scroll down to the failed test
and copy the Link on the right-hand side of the `Assertion URI`
- [ ] the URL of your service / the file you have uploaded or referenced (as
an attachment).

If your service is protected or you have confidential data that you cannot
upload here, you can request an email address to which you can send URLs / files.
Please note that issues cannot be investigated for services/datasets that we cannot
access.

**Comment by carlospzurita** [comment]
Dear @MarisolGomezAndres 

Thank you for opening this issue. We are investigating the origin of this issue, if it is necessary to add the authority entity as valid. We will get back to you with some more feedback.

**Comment by carlospzurita** [comment]
Dear @MarisolGomezAndres 

We have updated the [staging instance](http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp) with the certificates from the services. You are able to test them there.

**Comment by MarisolGomezAndres** [comment]
Bad news! We have made test with the validator (https://inspire.ec.europa.eu/validator/) and the  LinkChecker (https://inspire-geoportal.ec.europa.eu/linkagechecker.html) and the same error ocurred.



[Error validator and linkchecker.docx](https://github.com/inspire-eu-validation/community/files/5715330/Error.validator.and.linkchecker.docx)

**Comment by MarcoMinghini** [comment]
Dear @MarisolGomezAndres,
the change has been deployed in the [staging instance](http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/), not yet in the production instance.

According to the [release schedule](https://github.com/inspire-eu-validation/community/tree/master/release%20strategy), it will be deployed in production in the next release, happening in January.

**Comment by MarisolGomezAndres** [comment]
Hello,

I am looking for the state of the issue #471- INSPIRE validator doesn`t recognize SDI Digital certificate- SPAIN and I can´t find it in the new Github platform. Could you let me know if it is solved or in other case how I can find the state of it?

Un saludo.

María Soledad Gómez Andrés
Jefa de Área de Servicios SIG y Web
SG de Tecnologías de la Información y Comunicaciones
Ministerio de Agricultura, Pesca y Alimentación

De: Carlos Palma Zurita [mailto:notifications@github.com]
Enviado el: jueves, 17 de diciembre de 2020 17:12
Para: inspire-eu-validation/community <community@noreply.github.com>
CC: Gómez Andrés, Soledad <msgomez@mapa.es>; Assign <assign@noreply.github.com>
Asunto: Re: [inspire-eu-validation/community] INSPIRE validator doesn`t recognize SDI Digital certificate- SPAIN (#471)


Assigned #471<https://github.com/inspire-eu-validation/community/issues/471> to @MarisolGomezAndres<https://github.com/MarisolGomezAndres>.

**Comment by carlospzurita** [comment]
Dear @MarisolGomezAndres 

The issue was solved in the [staging instance](http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/). It is deployed there before moving it to production, for the user to test the solution and check that everything is okay. So please, we would kindly ask you to execute the tests on the [staging instance](http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/) and let us know if everything is ok.

Pleas also make sure to check the [release strategy](https://github.com/INSPIRE-MIF/helpdesk-validator/tree/master/release%20strategy) and the [helpdesk management](https://github.com/INSPIRE-MIF/helpdesk-validator/tree/master/helpdesk%20management) to have a comprehensive explanation of the workflow of the issues opened in the helpdesk, and when the fixes are moved to the [reference validator](https://inspire.ec.europa.eu/validator/)

**Comment by MarisolGomezAndres** [comment]
We have made test in the staging instance and it Works fine. Please le tus know when the changes are moved to the production instancee.

Marisol Gómez Andrés
Paseo Infanta Isabel 1 – 28014 Madrid  - Spain
Information Technology and Communication Department
Web and Gis Services Manager

De: Carlos Palma Zurita [mailto:notifications@github.com]
Enviado el: lunes, 8 de febrero de 2021 9:37
Para: INSPIRE-MIF/helpdesk-validator <helpdesk-validator@noreply.github.com>
CC: Gómez Andrés, Soledad <msgomez@mapa.es>; Mention <mention@noreply.github.com>
Asunto: Re: [INSPIRE-MIF/helpdesk-validator] INSPIRE validator doesn`t recognize SDI Digital certificate- SPAIN (#471)


Dear @MarisolGomezAndres<https://github.com/MarisolGomezAndres>

The issue was solved in the staging instance<http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/>. It is deployed there before moving it to production, for the user to test the solution and check that everything is okay. So please, we would kindly ask you to execute the tests on the staging instance<http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/> and let us know if everything is ok.

**Comment by MarcoMinghini** [comment]
Dear @MarisolGomezAndres,

as you were already answered above, the release schedule of the Validator is explained [here](url). The next release is foreseen for mid-March.

Also, if possible please answer directly from [GitHub](https://github.com/INSPIRE-MIF/helpdesk-validator/issues/471) and not via e-mail, because a lot of unnecessary text is automatically added.

Thank you.
