### ISSUE TITLE
The default style name for layer AM.WaterBodyForWFD for view service should be AM.WaterBodyForWFD.Default

### ISSUE THREAD

**Issue by zguo** [INSPIRE-MIF/helpdesk-validator#473]
Currently the validator seems to be using AM.WaterBodyForWFD, 

Please see page 82 of the spec for AM

**Comment by carlospzurita** [comment]
Dear @zguo 

Thank you for opening this issue. We are reviewing the definition of the ETS for AM.

**Comment by carlospzurita** [comment]
Dear @zguo 

We have added the default style for the WaterBodyForWFD layer. Can you please check it out again?

**Comment by igea-jure** [comment]
I can confirm the test works on beta INSPIRE validator.

It seems this fix has not been published in release v2021.2. Will it be included in v2021.3?

**Comment by zguo** [comment]
yes looks like it is using the correct style now, my service passed the test now, the service is using stylename AM.WaterBodyForWFD.Default

the service is at http://agsinspire1.esri.com/arcgis/rest/services/amc/MapServer/exts/InspireView/service?request=getcapabilities&service=wms

Thanks,

**Comment by dperezBM** [comment]
Dear @zguo,

Sorry for our late reply. Thank you for validating the issue. We will mark it as solved. If you have any other problem, do not hesitate on opening a new issue.

Best regards
