### ISSUE TITLE
WFS Direct Access Test dissapeared from the Validator

### ISSUE THREAD

**Issue by iuriemaxim** [INSPIRE-MIF/helpdesk-validator#474]
While trying to replicate the issue https://github.com/inspire-eu-validation/community/issues/408
I discovered that the **WFS Direct Access Test** dissapeared from the validator.

The corresponding ATS is https://github.com/inspire-eu-validation/download-wfs/tree/3.1/wfs-direct and there were some issues reported for this test, all of them being fixed by OGC, including:
https://github.com/inspire-eu-validation/community/issues/219
https://github.com/inspire-eu-validation/community/issues/209
https://github.com/inspire-eu-validation/community/issues/208
https://github.com/inspire-eu-validation/community/issues/210
https://github.com/inspire-eu-validation/community/issues/338

Discutions were held as well in relation with this test:
https://github.com/inspire-eu-validation/community/issues/216

**The test dissapeared from both the staging and the production validator.**

Did this test was removed for the 2020 December Reporting Round, in order to have less services reported as failed or it was removed by mistake?

**Comment by iuriemaxim** [comment]
Now it looks like this:

![image](https://user-images.githubusercontent.com/20813598/102284306-a001eb00-3f3c-11eb-81d6-2611b279d049.png)

And few days ago looked like this:

![image](https://user-images.githubusercontent.com/20813598/102329375-ff89e600-3f90-11eb-8897-f101365257f9.png)

In the New UI of the validator (accessible at https://inspire-sandbox.jrc.ec.europa.eu/validator-testbed/test-selection/index.html) there are both conformance classes even if in the Validator the Direct Access WFS Conformance Class dissapeared:
![image](https://user-images.githubusercontent.com/20813598/102286021-10f6d200-3f40-11eb-94ec-0e47a2493a21.png)

This Conformance Class does not exist anymore:
![image](https://user-images.githubusercontent.com/20813598/102285393-e48e8600-3f3e-11eb-8012-df2ac891c597.png)

All these tests vanished:

![image](https://user-images.githubusercontent.com/20813598/102284510-f2dba280-3f3c-11eb-9573-84ea4a265edd.png)

**Comment by carlospzurita** [comment]
Please check my comment at https://github.com/INSPIRE-MIF/helpdesk-validator/issues/408#issuecomment-745862761

**Comment by iuriemaxim** [comment]
@carlospzurita Indded I see now that in the production environment the Direct WFS Conformance Class is present, missing only in the staging environment. Yesterday I did not seen it in the production environment, but maybe I did not looked carefully.

**Comment by carlospzurita** [comment]
We have updated the [staging instance](http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp) and now the test appears again. It seems that there was an error on the HTTPS access to the TEAM engine, and the test driver was unable to load the Test Suites. You can test your services again.

**Comment by iuriemaxim** [comment]
@carlospzurita Thank you for the quik fix. It can be closed.

**Comment by iuriemaxim** [comment]
@carlospzurita As it was not already closed after more than one month: it can be closed.
