### ISSUE TITLE
Direct WFS Conformance Class is not checking if the WFS conforms also with the Pre-Defined WFS Conformance Class

### ISSUE THREAD

**Issue by iuriemaxim** [INSPIRE-MIF/helpdesk-validator#476]
TG for Download Services states:

![image](https://user-images.githubusercontent.com/20813598/102360312-869f8400-3fba-11eb-8b1f-cc0cb26285c1.png)

And to be more clear, the IR for Download services https://eur-lex.europa.eu/legal-content/EN/TXT/HTML/?uri=CELEX:32010R1088&from=EN defines

“Direct Access Download” means a Download Service which provides access to the Spatial Objects in Spatial Data Sets based upon a query.’

And is specifying three operations of the download services:

**A - Download Operations**
In order to be in conformity with Article 11(1)(c) of Directive 2007/2/EC, the Download Service shall at least provide the operations listed in Table 1 of this Annex....
5.1.1.   Link Download Service request parameter
The Link Download Service request parameter shall provide all information about the Public Authority’s or Third Party’s Download Service compliant with this Regulation, enabling the Member State Download Service to provide access to Spatial Data Sets **and, where practicable, to Spatial Objects** from the Public Authority’s or Third Party’s Download Service.

**B - Direct Access Download Operations**
**C - Search Criteria for the Get Spatial Object Operation**

**Coming back to the Validator, this means that if a user is checking if the WFS conforms to the ”Download Service: WFS - Direct” Conformance Class, than that WFS should also comply with the ”Download Service: Pre-defined WFS” Conformance class.**

However the ”Download Service: Pre-defined WFS” Conformance class. is not listed as a pre-requisite of the ”Download Service: WFS - Direct” Conformance Class.

I know that someone could argue that part A of the IR could be implemented trough Atom and if so, than  ”Download Service: Pre-defined Atom” Conformance class should be a pre-requisite. However this could be quite odd as the WFS already has all the functionalities listed in part A, just that the stored querries should be configured. In any case by looking at the linked metadata of the dataset and services it can be easily spoted by a machine if the download operations listed in part A of the IR where implemented trough WFS or ATOM.

In any case  I did not heard of any implementation of a WFS Direct Access implementation that is using ATOM for Pre-defined access to the dataset instead of WFS Pre-defined access.

**Comment by carlospzurita** [comment]
Dear @iuriemaxim 

Thank you for opening this issue. This is something that it is very interesting. We need to check and discuss internally, as these tests are quite old. We will get back yo you with some more feedback.

**Comment by carlospzurita** [comment]
We marked this issue as discussion, given that this topic is an enhancement with big repercussion and need more feedback. We have been checking the Implementing Rules and the Technical Guidelines, and it certainly implies that a download service must comply with the pre-defined operations before checking the direct operations. However, this can apply also to ATOM services, and we need to check what it the best course of action for both type of services and the implications for the current implementation in the validator.

**Comment by iuriemaxim** [comment]
@carlospzurita The "discussion" tag is not a correct one. There is no discution in this thread. Is just a bug that needs a fix. It is not an enhancement, but is a bug. The fact that the bug has big reoercurssion is true. Ussually such bugs are marked as critical. The fact that may be a dificult one to fix, does not mean that the bug become a discussion. Please provide a correct label to this issue and remove the "discusion" label that is confusing.

Labeling this as a "discution" could be interpreted that somebody (Who?) should provide some feedback. But no more feedback is needed as the TG is clear as also stated in the previous post.

In issues tracker, such issues are ussualy marked as "critical".

**Comment by fabiovin** [comment]
Dear @iuriemaxim,

we implemented this dependency in the new UI, available in the production instance since the last release.
Therefore, if you validate a "Direct WFS" the "_Conformance Class 'Pre-defined WFS'_" is automatically selected and is not deselectable.

![image](https://user-images.githubusercontent.com/46569952/123774514-c6321b80-d8cd-11eb-8574-d13e08c5b092.png)

**Comment by iuriemaxim** [comment]
@fabiovin Thank you for implementation.
