### ISSUE TITLE
Validation error on grouping keywords originating from no controlled vocabulary

### ISSUE THREAD

**Issue by AntoRot** [INSPIRE-MIF/helpdesk-validator#48]
I'm testing a metadata 2.0 XML file and an error returned on the grouping of keywords originating by the same controlled vocabulary (TG requirement C.16), although in the file there is only a keyword for INSPIRE data themes originating by GEMET INSPIRE themes controlled vocabulary included in a specific Keywords element and two keywords originating from no controlled vocabulary grouped into another Keywords element.
No error should be returned since the keywords are correctly grouped.

- [x] a description of the steps to reproduce your issue

1. go to http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp;
2. select "Common requirements for ISO/TC 19139:2007 based INSPIRE metadata records";
3. Select "Conformance Class 1: INSPIRE data sets and data sets series baseline metadata". (NOTE: When I select this, the conformance class referred to in point 2. is automatically unselected and I need to select it again);
4. Select "Conformance Class 2: INSPIRE data sets and data sets series interoperability metadata". (NOTE: When I select this, the conformance classes referred to in points 2. and 3.  are automatically unselected and I need to select them again);
5. start the test and enter the file attached;
6. the error message returned for the test Group Keywords by CV (referred to TG req C.16): "The metadata record set has 1 record(s) with errors for this assertion. XML document 'esempio_liguria_2.0.xml', record 'r_liguri:D.1595.2014-01-13': The keywords defined in the same source controlled vocabulary are not grouped into the same Keywords element."

- [X] the Test Report (ideally as an attachment to the issue)
http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/v2/TestRuns/EID301e8a9c-0161-40bc-adbd-1472838cdf61.html

- [X] the name of the Test that failed or better: change the `Level of Detail`
in the Report by clicking on `All Details`, then scroll down to the failed test
and copy the Link on the right-hand side of the `Assertion URI` 
Assertion URI: http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/v2/TestRuns/EID301e8a9c-0161-40bc-adbd-1472838cdf61.html?lang=it#EID31fb4a1c-3e06-432b-9a98-e3afe772a5dd 

- [X] the URL of your service / the file you have uploaded or referenced (as
an attachment).
[esempio_liguria_2.0.zip](https://github.com/inspire-eu-validation/community/files/3172522/esempio_liguria_2.0.zip)

**Comment by josemasensio** [comment]
Dear @AntoRot,

Thank you for your message.

We are investigating the error. Maybe the test or the ATS/TG should be modified.

We will come back to you with the possible solution.

Best regards.

**Comment by josemasensio** [comment]
Dear @AntoRot,

We are happy to announce that the solution for this issue has been implemented in the INSPIRE Validator, the test has been modified. The solution passed our quality controls, but we will appreciate if you could test it and give us some feedback. You can test the solution in the staging environment.

Thanks in advance for your help.

**Comment by AntoRot** [comment]
The XML file is validated properly now.
Thank you.
