### ISSUE TITLE
MD Common req C.14: Temporal Extent - beginPosition with both indeterminatePosition & value

### ISSUE THREAD

**Issue by PeterParslow** [INSPIRE-MIF/helpdesk-validator#480]
My hand made record fails with:

If 'indeterminatePosition' attribute is provided, its value for beginPosition element must be 'unknown' and for endPosition must be 'unknown' or 'now'.

This requirement seems to be undocumented; it's not mentioned at https://github.com/inspire-eu-validation/metadata/blob/2.0/common/temporal-extent.md or in the INSPIRE Metadata TG

I have 

<gml:beginPosition indeterminatePosition="before">2000</gml:beginPosition>

& can't see anything wrong with that as a GML encoded beginPosition.

But reading on in TG Requirement C.14, it does say 

"In case the time period is open-ended with either the start or the end date unknown, the elements gml:startPosition or gml:endPosition may be used with an empty value and the attribute indeterminatePosition with value "unknown".

In spite of the use of "may", it could be argued that INSPIRE is restricting the range of expression of GML time periods, and that the validator is correct - but could provide a better error message.

However, TG Requirement C.14 does include three "shall" requirements before this permission, so it seems to me that the validator should not throw out metadata instances that provide a value for the gml:beginPosition element in these cases.

**Comment by carlospzurita** [comment]
Dear @PeterParslow 

We are checking the requirement in the TG for this element. In the meantime, can you please provide us with some metadata you are using to test this issue?

Kind regards.

**Comment by PeterParslow** [comment]
I'm not certain it's the one I tested, but here's one with the same approach: https://www.ordnancesurvey.co.uk/xml/products/AddressBasePremium.xml

**Comment by iuriemaxim** [comment]
Quite a simmilar issue was this one: https://github.com/INSPIRE-MIF/helpdesk-validator/issues/188

**Comment by carlospzurita** [comment]
Dear @PeterParslow 

A fix for this issue has been published on the [staging instance](http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/). We have relaxed the test so it admits the values `before`, `now` and `after` are admitted to the attribute `indeterminatePosition`.  Please, check check the fix and let us know if everything is in order.

**Comment by iuriemaxim** [comment]
@carlospzurita, can you please confirm that the relaxed test was implemented for all these Conformance Classes as there are different pieces of code ?

Conformance Class 2 (Dataset), - Includes Common + Conformance Class 1
Conformance Class 4 (Network Services), includes Common + Conformance Class 3
Conformance Class 7 (Spatial Data Services), Includes Common +Conformance Class 5 and Conformance Class 6.

**Comment by PeterParslow** [comment]
I can confirm that that record no longer fails for this reason, when I run the test using the staging instance.
(There are other problems with this particular record, for me to fix; and one for me to ask about separately)

**Comment by carlospzurita** [comment]
Dear @iuriemaxim 

The Common Requirements ETS is always checked along with CC2, CC4 and CC7; and so this relaxation will also be present for validations for those Conformance Classes.
