### ISSUE TITLE
Staging Validator - Not able to run any tests.

### ISSUE THREAD

**Issue by robblis** [INSPIRE-MIF/helpdesk-validator#481]
Hi Validator Community,

I've been attempting to run validation tests, but every test returns a Test Run Initialization Failure.

Can someone check on this?

Thanks,
Robert

**Comment by carlospzurita** [comment]
Dear @robblis 

We have reloaded the staging instance and the problem seems to have been solved. Please check it out and tell us if everything is ok.

**Comment by robblis** [comment]
The Validator is working. 

Thanks.
