### ISSUE TITLE
Problem with links certificates in validation process

### ISSUE THREAD

**Issue by javi1983** [INSPIRE-MIF/helpdesk-validator#482]
Hello, I'm trying to validate metadata with inspire validation services, and I have an  issue with metadata links site certificate.  The provided error is:

The metadata record set has 1 record(s) with errors for this assertion.
XML document 'file.xml', record 'spaAYTCALPseriePGOUopmanz2020': The metadata record has a linkage property, but it references a resource at 'http://geoportal.calp.es/' that cannot be accessed. An exception occured when accessing the resource. Error message: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
XML document 'file.xml', record 'spaAYTCALPseriePGOUopmanz2020': The metadata record has a linkage property, but it references a resource at 'https://mapservice.geonet.es/ayto_calp/wms?' that cannot be accessed. An exception occured when accessing the resource. Error message: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
XML document 'file.xml', record 'spaAYTCALPseriePGOUopmanz2020': The metadata record has a linkage property, but it references a resource at 'https://geoportal.calp.es/ide-resources/op_suelo_manz.zip' that cannot be accessed. An exception occured when accessing the resource. Error message: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target  

The links base url are:

https://mapservice.geonet.es (certificate issued by digicert)

and

https://geoportal.calp.es (certificate issued by accv)

Before post this issue, I tried in stagin instance
http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/

with the same error :(

Can you add the certs chain  into server, in order to validate the metadata ?

Thanks in advance !

**Comment by carlospzurita** [comment]
Dear @javi1983 

We are going to take a look on this. We have encountered this error in the past (see #302). We will get back to you with some more feedback.

Kind regards.

**Comment by carlospzurita** [comment]
Dear @javi1983 

We have added the certificates on the [staging instance](http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/). Can you please check it out?

Kind regards.

**Comment by carlospzurita** [comment]
Since this issue has no repercussion on the relaxation or restriction of requirements, we are moving it into the release.
