### ISSUE TITLE
Download Service - OGC SensorThings API Validator

### ISSUE THREAD

**Issue by pbaumard** [INSPIRE-MIF/helpdesk-validator#485]
Is there any plan to implement an OGC SensorThings API Validator?

Please refer to the INSPIRE endorsed good practice [OGC SensorThings API as an INSPIRE download service](https://inspire.ec.europa.eu/good-practice/ogc-sensorthings-api-inspire-download-service):

> Executable tests and validation of OGC SensorThings API instances are also not covered in this good practice as they will be dealt with within the context of the work on the [INSPIRE Reference validator](https://inspire.ec.europa.eu/validator/about/).

**Comment by MarcoMinghini** [comment]
Dear @pbaumard,
yes, as a follow-up action of the Good Practice endorsement, there is a plan to develop ETS for OGC SensorThings API as an INSPIRE Download Service in 2021.

**Comment by dperezBM** [comment]
Dear @pbaumard,

Thank you for your feedback. We hope that the answer you were given would have helped you. In case you have any other questions or problems, please feel free to open a new issue.

Best regards.
