### ISSUE TITLE
2021.0 Release

### ISSUE THREAD

**Issue by carlospzurita** [INSPIRE-MIF/helpdesk-validator#486]
Dear all,

The new release for the INSPIRE validator is going to take place on 18th of January. Please, make sure to check the releases page after the deployment to have more info on the fixes and enhancements included in it.

Also, please take into account that Test Reports will be deleted to have a fresh instance, so make sure to save any Test Run that you would like to keep.

Kind regards.

**Comment by carlospzurita** [comment]
The validator will be down now for the release of the new version. We will update once it is ready and tested.

Kind regards

**Comment by carlospzurita** [comment]
The release for 2021.0 is ready and available at  https://inspire.ec.europa.eu/validator/. Please make sure to check the release notes.

We would like to kindly remind you that this space will be moved to a different organization (check #466 ). This means that the files for this release and the Docker image, along with all the current issues, will be relocated to https://github.com/INSPIRE-MIF/ . After this migration is complete, you will find them under that organization.

**Comment by ghost** [comment]
Hi @carlospzurita,

first of all I would like to say that I like the idea of centralizing helpdesks for all INSPIRE central components. 

According to this [message](https://github.com/inspire-eu-validation/community) migration is now complete:
![grafik](https://user-images.githubusercontent.com/38787131/105483502-3e0a7300-5caa-11eb-8e79-dcb8ef5d2179.png)

Where can I find all releases for INSPIRE Validator?

Kind regards,
Dejan

**Comment by alitka** [comment]
> Where can I find all releases for INSPIRE Validator?

@DeordD - Maybe you are looking for this overview: https://github.com/INSPIRE-MIF/helpdesk-validator/releases ...

**Comment by ghost** [comment]
> 
> 
> > Where can I find all releases for INSPIRE Validator?
> 
> @DeordD - Maybe you are looking for this overview: https://github.com/INSPIRE-MIF/helpdesk-validator/releases ...

@alitka - Thanks for the information. 

I also think this should be the right place for the releases. I just wanted to get confirmation from @carlospzurita that this is the right place (because helpdesk is migrated) in order to get the right version of the validator! 

This could also mean that helpdesk is also place for sharing source code of the applications, which could also be the case with other INSPIRE central components. :)

**Comment by carlospzurita** [comment]
Dear @DeordD 

As @alitka, the releases are located at https://github.com/INSPIRE-MIF/helpdesk-validator/releases. You can find it in the main page of the repository 
![imagen](https://user-images.githubusercontent.com/10537778/105507604-af0e5280-5ccb-11eb-9b26-9e60d590ed2d.png)

Kind regards.

**Comment by ghost** [comment]
Thanks @carlospzurita!

**Comment by carlospzurita** [comment]
Closing this issue as release is completed.
