### ISSUE TITLE
PT - INSPIRE validator and Resource linkages checker tool doesn´t recognize Digital Certificate

### ISSUE THREAD

**Issue by dfurtado-dgt** [INSPIRE-MIF/helpdesk-validator#488]
Dear INSPIRE Team,

There are some problem in INSPIRE validator and Resource linkages checker tool in recognizing GEANT Vereniging certificate from DGT.
The validator gives the following message:
Test Run initialization failure unable to find valid certification path to requested target

The service is:
https://cartografia.dgterritorio.gov.pt/wms/ortos2018?service=wms&request=getcapabilities

Tanks

**Comment by carlospzurita** [comment]
Dear @dfurtado-dgt 

Thank you for opening this issue. We are adding this certificates along with the ones from #482 

Kind regards

**Comment by carlospzurita** [comment]
Dear @dfurtado-dgt  

We have added the certificates on the [staging instance](http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/). Can you please check it out?

Kind regards.

**Comment by dfurtado-dgt** [comment]
Dear Carlos and INSPIRE team,

The staging instance of the INSPIRE validator already recognizes the DGT 
certificate.

Thank you for the support.
Best regards.
Danilo Furtado
