### ISSUE TITLE
Test am-as.a.1 fails when using https instead of http

### ISSUE THREAD

**Issue by danicgc** [INSPIRE-MIF/helpdesk-validator#489]
Dear team,
When testing an Area management GML, if I use https://inspire.ec.europa.eu/codelist/EnvironmentalDomain/naturalResources instead of http://inspire.ec.europa.eu/codelist/EnvironmentalDomain/naturalResources, the am-as.a.1 test (EnvironmentalDomain code list value) fails. Maybe it should accept also https?
Thanks

**Comment by carlospzurita** [comment]
Dear @danicgc 

As published on [this message](https://inspire.ec.europa.eu/news/inspire-re3gistry-software-and-inspire-registry-service-update) for the INSPIRE registry, all references to codelists must be done using HTTP, and so the test will fail if HTTPS is used.

**Comment by danicgc** [comment]
Dear @carlospzurita
I understand that all (not only registered codelists) is being migrated or redirecting to HTTPS. This is why I proposed, as a possible improvement, the acceptance of HTTPS besides HTTP.

**Comment by iuriemaxim** [comment]
@danicgc As http vs https is a long story.

You may try to read the thread #319 - Change https INSPIRE URIs into http URIs (from March 2020) -> changes needed in the validator
by taking into consideration the Migration issue https://github.com/INSPIRE-MIF/helpdesk-validator/issues/492 

Other related threads that cope with http vs https that are interesting to read to understand the issue are:
https://github.com/INSPIRE-MIF/helpdesk-validator/issues/451 - What is the strategy for the validator to cope with the http to https forwarding of all schema requests as of march 2021?

https://github.com/INSPIRE-MIF/helpdesk-validator/issues/407 - codelist vs codeList (similar to http vs https)

https://github.com/INSPIRE-MIF/helpdesk-validator/issues/334 - http vs https in CI_Citation or add INSPIRE TGs and Regulations to the Registry

https://github.com/INSPIRE-MIF/helpdesk-validator/issues/309 - md dataset-and-series 1.4: http://inspire.ec.europa.eu/theme redirected to HTTPS?

Hope it helps.

**Comment by arantzaetxebarria** [comment]
Dear @danicgc 

We proceed to close this issue. Do not hesitate to reopen the issue if you have more questions.
Thanks
