### ISSUE TITLE
Doubt with test am-as.b.2 (Constraint for competenAuthority)

### ISSUE THREAD

**Issue by danicgc** [INSPIRE-MIF/helpdesk-validator#490]
Dear team,
I have created an Area management GML and the test am-as.b.2 (Constraint for competenAuthority) fails with the message "The constraint 'At least one am:competentAuthority with role authority (http://inspire.ec.europa.eu/codelist/RelatedPartyRoleValue/authority) shall be provided.' is violated." although this tag is included in the GML created. Maybe I did not do it properly?
The GML: https://datacloud.ide.cat/geodades/inspire-zones-subjectes-ordenacio/inspire-forests-etrs89-geo.gml
Thank you so much

**Comment by carlospzurita** [comment]
Dear @danicgc 

Can you provide another source for your GML? The link you have posted is returning a 404 error, and so we can't reproduce the issue.

Kind regards.

**Comment by danicgc** [comment]
Dear @carlospzurita
Sorry for the mistake. I have updated the URL on the first message.
Thank you

**Comment by carlospzurita** [comment]
Dear @danicgc 

We have checked your GML, and there is an error on the tag competentAuthority. The content of the role that is set there is

`<base2:role xlink:type="simple" xlink:href="http://inspire.ec.europa.eu/codeList/RelatedPartyRoleValue/authority"/>`

The reference in the href should point to http://inspire.ec.europa.eu/codelist/RelatedPartyRoleValue/authority, not codeList with capital L.

We are marking this issue as user-to-fix

**Comment by danicgc** [comment]
Dear @carlospzurita
Indeed, lowercase does not fail.
Thank you very much for checking our GML.
Best regards,
