### ISSUE TITLE
Migration issue

### ISSUE THREAD

**Issue by iuriemaxim** [INSPIRE-MIF/helpdesk-validator#492]
During the migration to the new Github repository all links were broken.

For example this is a link reffered in a thread

https://github.com/inspire-eu-validation/community/issues/334

Now if accessing the link, the user will see the following:

![image](https://user-images.githubusercontent.com/20813598/105357788-fb8b5c80-5bfd-11eb-8e0a-2f9e7b143b2d.png)

Now the content that was available at
https://github.com/inspire-eu-validation/community/issues/334
is available at https://github.com/INSPIRE-MIF/helpdesk-validator/issues/319.
It may be easily seen that the content of  https://github.com/INSPIRE-MIF/helpdesk-validator/issues/319 is hard to almost impossible to clearly understand due to broken links.

Even if this is not an issue related to the validator, most of the threads are now affected and in many cases it is impossible to figure which was the problem described initially, as now the links are broken. Of course that suplementary, the issues are not anymore related one to another.

Most probably this will be marked as a discussion, but the problem remains.

**Comment by carlospzurita** [comment]
Dear @iuriemaxim 

Sorry for this inconvenience. We are aware that any links on the issues that are an absolute path to the repository are not working anymore. We will be editing any issue we review that contains referecences to the older repository, but it will be a long process.

We are marking this issue 'for-information' and leave it open for other users to be aware of the situation.

Kind regards.
