### ISSUE TITLE
GEMET API availability

### ISSUE THREAD

**Issue by mhogeweg** [INSPIRE-MIF/helpdesk-validator#494]
we are running into an issue frequently that the GEMET API are unavailable.

example:
https://www.eionet.europa.eu/gemet/getConceptsMatchingRegexByThesaurus?thesaurus_uri=http%3A%2F%2Fwww.eionet.europa.eu%2Fgemet%2Fconcept%2F&language=en&regex=water&jsonp=dojo_request_script_callbacks.dojo_request_script1

is this the right place to report such issues?

**Comment by carlospzurita** [comment]
Dear @mhogeweg 

This space is dedicated to the issues in the INSPIRE Reference Validator. The issue you opened on the general helpdesk is the correct one, and will be reviewed and redirected to the relevant part. We are closing this one.

Kind regards.
