### ISSUE TITLE
Downloading docker image of validator

### ISSUE THREAD

**Issue by bcosyn** [INSPIRE-MIF/helpdesk-validator#495]
I tried to dowload the docker image of the inspire-validator using Docker desktop for windows. When executing the pull request docker pull docker.pkg.github.com/inspire-mif/helpdesk-validator/inspire-validator:2021.0  for the image I received

Error response from daemon: Head https://docker.pkg.github.com/v2/inspire-mif/helpdesk-validator/inspire-validator/manifests/2020.2: no basic auth credentials

I am able with my config to download other images from Github. All discussions on google on this issue are confusing.

**Comment by bcosyn** [comment]
In addition I also tried to create an azure container and got a similar issue
![image](https://user-images.githubusercontent.com/13509656/105630484-d0954880-5e49-11eb-88da-71b0ed89dd59.png)
Looks like the image is not public.

**Comment by carlospzurita** [comment]
Dear @bcosyn 

As stated on the section "Deploy instructions" in the [release page](https://github.com/INSPIRE-MIF/helpdesk-validator/releases/tag/v2021.0), you need first to login into Github to download the docker image

```docker login docker.pkg.github.com 
#Provide Github credentials
docker run --name inspire-validator -d -p 8080:8080 -v ~/etf:/etf docker.pkg.github.com/inspire-mif/helpdesk-validator/inspire-validator:2021.0
#Launches a container with the image, exposing it port 8080 through the same port in the host machine, and uses a volume in the local file system, on the directory ~/etf
```

If the problem persist, please let us know.

Kind regards

**Comment by bcosyn** [comment]
Thx.
I was able now to pull the image in Docker desktop using an accesstoken. Username password, as i was using before, seems to be deprecated.
