### ISSUE TITLE
404 page not found

### ISSUE THREAD

**Issue by axel584** [INSPIRE-MIF/helpdesk-validator#497]
Hi,
From the page : http://etf-validator.net/ when I click on "Install from docker hub", I go to : 
https://hub.docker.com/r/iide/etf-webapp
And I've got an error 404.
Who can fix the http://etf-validator.net/ page ?
Thank you,
Axel

**Comment by carlospzurita** [comment]
Dear @axel584 

The official INSPIRE validator Docker image can be found through the [relase page](https://github.com/INSPIRE-MIF/helpdesk-validator/releases/tag/v2021.0). You need to download the image docker.pkg.github.com/inspire-mif/helpdesk-validator/inspire-validator:2021.0.

Check my ohter comment at #498

**Comment by dperezBM** [comment]
Dear @axel584 

We proceed to close this issue. Do not hesitate to reopen the issue if you have more questions.

Best regards.
