### ISSUE TITLE
Wrong link on the homepage

### ISSUE THREAD

**Issue by axel584** [INSPIRE-MIF/helpdesk-validator#502]
Hi,
When I go to :  https://inspire.ec.europa.eu/validator/about/ and click on the button "Get the software", I go to : https://github.com/inspire-eu-validation/community/releases
Who can fix the link ? Who I should contact to fix the link ?

Thank you,

Axel Rousseau

**Comment by df-git** [comment]
Dear @axel584,
Thank you for your feedback. We fixed the wrong links.
Best regards,
Daniele on behalf of the INSPIRE Support Team
