### ISSUE TITLE
Security hole

### ISSUE THREAD

**Issue by axel584** [INSPIRE-MIF/helpdesk-validator#504]
Hi,
When I launch a test, I see in the UI the path of my files. It's a huge security hole : 
![image](https://user-images.githubusercontent.com/1334088/106635985-bf52e700-6581-11eb-8e73-b5404262b628.png)

Could you remove it ? (it's ok to have the information in the log file, but not on the public website)

Thank you,

Axel Rousseau

**Comment by carlospzurita** [comment]
Dear @axel584 

This behaviour is intended on the software of the validator. It is not considered a security hole, as it is just showing internal information of the validator instance. The file you are seeing is source code of the validator. Confidential files and information about data being tested is not shown in the log of the validator.

Anyway, if you would like to share your concerns on this and propose a fix, you can open an issue on the software framework the validator uses as a backend https://github.com/etf-validator/etf-webapp

Kind regards.

**Comment by jonherrmann** [comment]
Hi @axel584 , @carlospzurita ,

I share Carlos view that this is not a security hole. Nevertheless, the output could be removed from the [INSPIRE Executable Test Suites](https://github.com/inspire-eu-validation/ets-repository/blob/650ded1dd21b8e9a6b5bcd20dd8f92174da746df/inspire-bsxets.xq#L339) easily.

Security vulnerabilities in ETF whose cause are not the INSPIRE Executable Test Suites or the public Deployment can be reported here: https://github.com/etf-validator/etf-webapp/security/policy#reporting-a-vulnerability . 

Best regards
Jon

**Comment by dperezBM** [comment]
Dear all,

Since this issue had no interaction time ago, we decided to close it. Please feel free to open a new one if needed.

Thank you and best regards.
