### ISSUE TITLE
Where are the source code ?

### ISSUE THREAD

**Issue by axel584** [INSPIRE-MIF/helpdesk-validator#505]
Hi,
I'm looking the source code of the validator. I find the repository : https://github.com/inspire-eu-validation/ets-repository
But the last commit was the April 15, 2020. 
Where can I found more recent source of the validator ?

Thank you,

Axel Rousseau

**Comment by axel584** [comment]
And I found this repository from 2019 : https://github.com/etf-validator/etf-webapp

**Comment by carlospzurita** [comment]
Dear @axel584 

The source code for tests in the validator can be found in the ETS repository, as you have linked. We are resolving pull request to the master branch to be up to date for the latest release, but in the meantime the latest version of the reference validator can be found at the branch [next](https://github.com/inspire-eu-validation/ets-repository/tree/next)

The validator has as a backend the ETF, an open source testing framework. The main code for this software is located at https://github.com/etf-validator/etf-webapp, where you can get the generic software to run Executable Test Suites as the ones developed on the ets-repository from INSPIRE.

All of this is wrapped in the release version that you can find at https://github.com/INSPIRE-MIF/helpdesk-validator/releases/tag/v2021.0. The ETS are integrated with the INSPIRE configured ETF on a Docker image to quickly deploy a version on your instance.

You can get more information on the [training materials](https://github.com/INSPIRE-MIF/helpdesk-validator/releases/tag/v2021.0)

**Comment by carlospzurita** [comment]
The pull request has been resolved and the source code is available at the master branch of https://github.com/inspire-eu-validation/ets-repository/

**Comment by carlospzurita** [comment]
We are closing this issue as no furhter feedback was required from user.
