### ISSUE TITLE
Expose version of image inside api

### ISSUE THREAD

**Issue by botenvouwer** [INSPIRE-MIF/helpdesk-validator#506]
We run the validations automatically, and we want to know which version of the etf validator was used in the automated test.

Is it possible to expose the version of the image trough an api endpoint.

**Comment by carlospzurita** [comment]
Dear @botenvouwer 

The INSPIRE validator is using the ETF v2.0.0 as a backend. You can check the version in the following API call 

https://inspire.ec.europa.eu/validator/v2/status

![imagen](https://user-images.githubusercontent.com/10537778/106931046-76806700-6716-11eb-945f-e4c7c79abd19.png)

**Comment by MarcoMinghini** [comment]
Dear @botenvouwer, I am not sure about your final goal but please note that the production instance of the INSPIRE Reference Validator should not be used for massive tests using the API.

If you need to run such massive tests (e.g. for bulk validation of several metadata or datasets), please deploy a local instance of the Validator (instructions are included in each release, e.g. the [last one](https://github.com/INSPIRE-MIF/helpdesk-validator/releases/tag/v2021.0)). We also released a [bulk validation tool](https://github.com/inspire-eu-validation/monitoring-bulk-validation-tool) that you can use to configure and run massive validation of metadata on any endpoint.

**Comment by dperezBM** [comment]
Dear @botenvouwer ,

Thank you for your feedback. We hope that the answer you were given would have helped you. In case you have any other questions or problems, please feel free to open a new issue.

Best regards.
