### ISSUE TITLE
Species Distribution - Validation Fails with multiple DistributionInfo elements

### ISSUE THREAD

**Issue by robblis** [INSPIRE-MIF/helpdesk-validator#518]
Hi Validator Team,

We are working on testing and fixing our Species Distribution returned XML.

We are getting the following Validation Errors due to more than one sd:distributionInfo element.

_XML document 'service.xml', SpeciesDistributionUnit 'SpeciesDistributionUnitS.3001': The multiplicity of sd:countingMethod shall be 1. Found: '2'..
XML document 'service.xml', SpeciesDistributionUnit 'SpeciesDistributionUnitS.3001': The multiplicity of GeneralCountingUnitValue or Article17CountingUnitValue shall be 1. Found: '2'.
XML document 'service.xml', SpeciesDistributionUnit 'SpeciesDistributionUnitS.3001': The multiplicity of OccurrenceCategoryValue shall be 1. Found: '2'.
XML document 'service.xml', SpeciesDistributionUnit 'SpeciesDistributionUnitS.3001': The multiplicity of PopulationTypeValue shall be 1. Found: '2'.
XML document 'service.xml', SpeciesDistributionUnit 'SpeciesDistributionUnitS.3001': The multiplicity of ResidencyStatusValue shall be 1. Found: '2'._

In the schema, the sd:distributionInfo element has a 0-many cardinality. 

We're unsure why the validator is throwing these errors. We've attached the Species Distribution XML.

We also are seeing the same issue with Geology when testing ge:Fold.

_XML document 'service.xml', Fold 'geFold.3': The multiplicity of ThematicClassValue shall be 1. Found: '2'.
XML document 'service.xml', Fold 'geFold.4': The multiplicity of ThematicClassValue shall be 1. Found: '2'._

In the schema, the ge:themeClass has a 0-many cardinality. We've attached the GE Fold XML.

Can someone assist?

Thanks,
Robert

[SpeciesDistributionUnit.zip](https://github.com/INSPIRE-MIF/helpdesk-validator/files/6045095/SpeciesDistributionUnit.zip)
 
[Geology_Fold.zip](https://github.com/INSPIRE-MIF/helpdesk-validator/files/6051944/Geology_Fold.zip)

**Comment by carlospzurita** [comment]
Dear @robblis 

We are checking the multiplicity of this elements in the TG and in the ETS developed and will get back to you with more feedback if a fix is needed on the validator.

Kind regards.

**Comment by carlospzurita** [comment]
Dear @robblis 

We are modifying the multiplicity checks for this test. Whenever we have the fix ready we will get back to you.

Kind regards.

**Comment by carlospzurita** [comment]
Dear @robblis 

We have published a fix for this issue on the [staging instance](http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/). Could you please check it out and give us some feedback?

Thank you

**Comment by robblis** [comment]
Dear @carlospzurita,

We've re-ran the tests against Species Distribution and we don't see the multiplicity error being reported.

Thanks for getting this fixed,
Robert
