### ISSUE TITLE
Attribute 'uom' with unknown areas

### ISSUE THREAD

**Issue by danicgc** [INSPIRE-MIF/helpdesk-validator#522]
Hi,
I have implemented the following Habitat GML and the test gmlas.b.2 throws the error "Attribute 'uom' must appear on element 'hb:areaCovered'", although the elements it refers are declared as unknown (nilReason):
https://datacloud.ide.cat/geodades/inspire-habitats/inspire-habitats-etrs89-geo.gml

**Comment by apfelnymous** [comment]
Hello @danicgc , mandatory attributes are not nilable, the validator wont accept a nilReason for those. I remember I always had to fill the uom attribute.

If you cant find out the unit of measurement you could just ignore the parent attribute, which is mostly not mandatory.

Kind regards

**Comment by danicgc** [comment]
Thanks @apfelnymous. I solved it as you say. Best regards,
