### ISSUE TITLE
Wiki Page for known limitations is not up to date

### ISSUE THREAD

**Issue by ghost** [INSPIRE-MIF/helpdesk-validator#524]
Wiki page [Known limitations](https://github.com/INSPIRE-MIF/helpdesk-validator/wiki/Known-limitations) is not up to date. 

[Link](http://docs.etf-validator.net/v2.0/index.html#_administrator_manuals) to detailed instructions for deployment refers to ETF-Validator and not INSPIRE Validator.

**Comment by carlospzurita** [comment]
Dear @DeordD 

Thank your for noticing this, we are updating the wiki

Kind regards.

**Comment by dperezBM** [comment]
Dear @DeordD 

We proceed to close this issue. Do not hesitate to reopen the issue if you have more questions.

Best regards.

**Comment by MarcoMinghini** [comment]
Dear @DeordD, 
the wiki (all pages) is now updated.
