### ISSUE TITLE
System Error in Executable Test Suite due to redirection system to the INSPIRE registry

### ISSUE THREAD

**Issue by ghost** [INSPIRE-MIF/helpdesk-validator#525]
It seems that the problem stated [here](https://github.com/INSPIRE-MIF/helpdesk-validator/issues/435) concernig "System Error in Executable Test Suite" occurs again:
![grafik](https://user-images.githubusercontent.com/38787131/110924760-b7c1f300-8322-11eb-8345-825a6ded28d3.png)

One example from Test Report section on production instance:
https://inspire.ec.europa.eu/validator/v2/TestRuns/EID1095387a-ba6e-401f-a00e-e3861b3249f5.html

Could you please investigate this?

Kind regards,
Dejan

**Comment by carlospzurita** [comment]
Dear @DeordD 

This error may be due to a temporary unavailability of the caching system. The INSPIRE Keywords are accessible now on the production instance.

Kind regards,

Carlos.

**Comment by ghost** [comment]
Hi @carlospzurita,

this problem is solved for now. Thanks for the fixing!

This problem has occured several times so far. Can we expect a stable solution for this issue?

Kind regards,
Dejan

**Comment by JohannaOtt** [comment]
I just ran into this issue on the production system again.

**Comment by carlospzurita** [comment]
The test should be executed again correctly. We are checking the redirection system to the INSPIRE registry to see how to avoid this unavailability.

**Comment by ghost** [comment]
@carlospzurita Does it make sense to fix following lines

- https://github.com/inspire-eu-validation/ets-repository/blob/d3d47c3fc32ed678ed51e3e83c295afbe2cfaa6b/metadata/2.0/datasets-and-series/ets-md-monitoring-bsxets.xml#L79 
- https://github.com/inspire-eu-validation/ets-repository/blob/d3d47c3fc32ed678ed51e3e83c295afbe2cfaa6b/metadata/2.0/datasets-and-series/ets-md-monitoring-bsxets.xml#L211
- https://github.com/inspire-eu-validation/ets-repository/blob/d3d47c3fc32ed678ed51e3e83c295afbe2cfaa6b/metadata/2.0/datasets-and-series/ets-md-datasets-and-series-bsxets.xml#L210

in order to provide quick and efficient solution for metadata records?

Thanks in advance!

**Comment by ghost** [comment]
It seems that this problem occured again:
![grafik](https://user-images.githubusercontent.com/38787131/113842733-40ea0f80-9793-11eb-8225-fc410021136f.png)

Could you please give a feedback concernig my questions [here](https://github.com/INSPIRE-MIF/helpdesk-validator/issues/525#issuecomment-805843955)?

**Comment by JohannaOtt** [comment]
The issue occurred again right now.

**Comment by carlospzurita** [comment]
The cache of the system has been restarted and the error has disappeared. We are looking into fixing this permanently.

**Comment by JohannaOtt** [comment]
@carlospzurita I am getting a similar error for INSPIRE codelists right now 
![grafik](https://user-images.githubusercontent.com/34163838/120321080-28096080-c2e3-11eb-9a16-440d96ba4ab9.png)
Is that related?

**Comment by ghost** [comment]
@carlospzurita Is this problem solved in the new release? If yes, does it mean that organisations which are deploying the validator don't have this problem anymore?

Thanks in advance!

**Comment by ghost** [comment]
@carlospzurita The same problem [here](https://github.com/INSPIRE-MIF/helpdesk-validator/issues/588)?

**Comment by ghost** [comment]
@carlospzurita Has this problem been solved with the new release of the validator?

**Comment by fabiovinci** [comment]
Dear all,

the issue is due to the temporary unavailability of the INSPIRE Registry and it should be solved with the new release (version 2) of the INSPIRE Registry (which should be released soon).
