### ISSUE TITLE
Habitats and Biotopes - Validator fails with when there is multiple instances of hb:referenceSpeciesId

### ISSUE THREAD

**Issue by robblis** [INSPIRE-MIF/helpdesk-validator#526]
Hi Validator Team,

We are testing our Habitats and Biotopes GML output.

We are getting the following error when running the Conformance Class 'Application Schema, Habitats and Biotopes' test.

The multiplicity of referenceSpeciesId shall be 1. Found: '3'.

Looking at the schema for hb:HabitatSpecies, the cardinality is 0 to many. 

Can someone assist and see if there's an issue with the test?

We've attached the xml output and the test report.

Thanks,
Robert

[HabitatAndBiotopes_Test.zip](https://github.com/INSPIRE-MIF/helpdesk-validator/files/6133538/HabitatAndBiotopes_Test.zip)

**Comment by carlospzurita** [comment]
Dear @robblis 

Thank you for opening the issue, we are checking the HB ETS for the multiplicity of this element.

Kind regards.

**Comment by arantzaetxebarria** [comment]
Dear @robblis 

We have published a fix for this issue on the [staging ](http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/home/index.html)instance. Could you please check it out?
Thanks

**Comment by robblis** [comment]
Hi @arantzaetxebarria 

We re-tested this theme and the test was successful.

Thanks for the fix,
Robert

**Comment by dperezBM** [comment]
Dear @robblis,

Thank you for your feedback. We are going to keep the issue open in order to get tracked until the next release.

Best regards.
