### ISSUE TITLE
http://portele.de/ShapeChangeAppinfo.xsd?

### ISSUE THREAD

**Issue by danicgc** [INSPIRE-MIF/helpdesk-validator#527]
Dear team,
Today I have tried to validate a pair of GML, corresponding to 2 different themes (land cover and area management), and test gmlas.b.2 has thrown the following error message: "... http://portele.de/ShapeChangeAppinfo.xsd, 1:50: White spaces are required between publicId and systemId."
Can it be something out of my GML what is failing?
GML example: https://datacloud.ide.cat/geodades/inspire-zones-subjectes-ordenacio/2021-inspire-forests-etrs89-geo.gml
Thanks

**Comment by fabiovin** [comment]
Dear @danicgc,

the issue is related to the unavailability of the schema http://portele.de/ShapeChangeAppinfo.xsd, the INSPIRE schemas importing this schema are not valid at the moment.

@cportele, could you take a look at this?

Thank you.

**Comment by carlospzurita** [comment]
Dear @danicgc 

The GML provided is not available anymore, can you provide a new URL for it? 

Kind regards.

**Comment by danicgc** [comment]
Sorry, now it is https://datacloud.ide.cat/geodades/inspire-zones-subjectes-ordenacio/inspire-forests-etrs89-geo.gml
Thanks,

**Comment by fabiovin** [comment]
Dear @danicgc,
the xsd file has been restored (see issue: https://github.com/INSPIRE-MIF/helpdesk/issues/17), but it seems that the Validator isn't able to handle the redirection.

I proposed to temporarily remove the redirection.

We are waiting for a feedback.

**Comment by fabiovin** [comment]
Dear @danicgc,
the issue has been solved.
I tested your gml file and the issue is no more present.

**Comment by danicgc** [comment]
Thank you very much.
