### ISSUE TITLE
Geology - Looking for href for specification element

### ISSUE THREAD

**Issue by robblis** [INSPIRE-MIF/helpdesk-validator#530]
Hi Validator Team,

We are seeing the following errors when running the ge:MappedFeature request through the Conformance Class 'Information accessibility', Geology test.

_XML document 'service.xml', MappedFeature 'geFaultL.3': The attribute 'xlink:href' of the element 'specification' shall be provided.
XML document 'service.xml', MappedFeature 'geFaultL.4': The attribute 'xlink:href' of the element 'specification' shall be provided.
XML document 'service.xml', MappedFeature 'geFoldL.5': The attribute 'xlink:href' of the element 'specification' shall be provided.
XML document 'service.xml', MappedFeature 'geFoldL.6': The attribute 'xlink:href' of the element 'specification' shall be provided.
XML document 'service.xml', MappedFeature 'geGeoMorphL.7': The attribute 'xlink:href' of the element 'specification' shall be provided.
XML document 'service.xml', MappedFeature 'geGeoMorphL.8': The attribute 'xlink:href' of the element 'specification' shall be provided.
XML document 'service.xml', MappedFeature 'geGeoMorphP.9': The attribute 'xlink:href' of the element 'specification' shall be provided.
XML document 'service.xml', MappedFeature 'geUnitL.15': The attribute 'xlink:href' of the element 'specification' shall be provided.
XML document 'service.xml', MappedFeature 'geUnitL.16': The attribute 'xlink:href' of the element 'specification' shall be provided.
XML document 'service.xml', MappedFeature 'geMappedInterval.14': The attribute 'xlink:href' of the element 'specification' shall be provided.
XML document 'service.xml', MappedFeature 'hgAquicludeS.6001': The attribute 'xlink:href' of the element 'specification' shall be provided._

We see that the Validator is looking for an href link to the 'specification' element. However, we actually embed the information directly in the returned XML. We admit this might be a little unusual but feel this should be valid. One reason we do this is to provide functionality to return this information in our View Service when we call a GetFeatureInfo request.

Can we get someone to review this and see if this is addressable?

I've attached the service XML and the Validator Report.

Thanks,
Robert

[GE_MappedFeature_TestArtifacts.zip](https://github.com/INSPIRE-MIF/helpdesk-validator/files/6174433/GE_MappedFeature_TestArtifacts.zip)

**Comment by carlospzurita** [comment]
Dear @robblis

Thank you for opening the issue. We are reviewing the Data Specification for this theme and will get back to you with an answer.

Kind regards.

**Comment by fabiovin** [comment]
Dear @robblis,

it is correct, the embedded encoding for the attribute 'specification' is a possible option.

This encoding option increase a lot the number of XPaths to be checked by validator, in any case, we will add them to the ATS and to the ETS.

We’ll let you know when the validator is updated.

**Comment by carlospzurita** [comment]
Dear @robblis and @fabiovin 

We have updated the ETS with the relevant paths. Can you please test it again?

**Comment by carlospzurita** [comment]
Dear @robblis 

Did you have the opportunity to test the solution for this issue?

**Comment by robblis** [comment]
Hi @carlospzurita ,

Just re-tested GE MappedFeature and there were no errors.

Thank you for the fix,
Robert

**Comment by carlospzurita** [comment]
Dear @robblis 

Thank you for your comment, we are moving it into production instance.

Kind regards.
