### ISSUE TITLE
Geology - Empty UOM Value Error

### ISSUE THREAD

**Issue by robblis** [INSPIRE-MIF/helpdesk-validator#531]
Hi Validator Team,

We are in the process of validating our Geology theme.

We are getting the following issue when requesting the ge:Borehole feature in the Conformance Class 'INSPIRE GML application schemas'

XML document 'service.xml', Borehole 'geBorehole.1': The following properties of the feature have an empty value: uom. While this is valid against the XML schema, this is not valid according to the GML model. Please correct the process that generates the GML documents.

We feel that this may be an issue with the validator.

The attached XML returns the following XML
ge:boreholeLength
swe:Quantity
<swe:uom code="meters"/>
swe:value0.000000</swe:value>
</swe:Quantity>
</ge:boreholeLength>

However, the test wants to see the uom value either in an xlink:href attribute, which is not logical, or in the swe:uom element value itself. However, being in the node value itself causes the following schema error when running through the Xpath Assertion test.
The content of complex type definition 'swe:UnitReference' is 'empty'. This forbids any content for element swe:uom.

The test should check that no property of the feature is empty. But swe:uom is not a property of the feature.
The relevant property in this case is ge:boreholeLength, which is not empty. But it seems the test recursively checks all nested element, which maybe it should not do.

I've attached our returned XML file and the HTML Report.

Thanks for your help,
Robert

[GE_BoreHole_TestArtifacts.zip](https://github.com/INSPIRE-MIF/helpdesk-validator/files/6174453/GE_BoreHole_TestArtifacts.zip)

**Comment by carlospzurita** [comment]
Dear @robblis 

Thank you for opening this issue. We are checking the ETS and the results on the validator.

Kind regards.

**Comment by JohannaOtt** [comment]
Might be related to https://github.com/inspire-eu-validation/ets-repository/issues/223

**Comment by fabiovin** [comment]
Dear @robblis,
you are right, the "swe:uom" element cannot have a value.

So, we need to add an exception for this element in the Conformance Class 'INSPIRE GML application schemas'.

@carlospzurita, since there are other similar cases, (e.g. https://github.com/inspire-eu-validation/ets-repository/issues/223, this issue was opened in another repository but it seems solved, could you please verify?) it could be possible to add a generic exception, like *:uom?

Thank you @JohannaOtt for having linked a similar issue.

**Comment by iuriemaxim** [comment]
We had a simmilar issue with UoM, but on OMOP, not on SWE. The incident that was fixed can be consulted here https://github.com/INSPIRE-MIF/helpdesk-validator/issues/206


While testing with these URLs, the test is passed:

https://inspire.meteoromania.ro/observedProperty/BUFR301
https://inspire.meteoromania.ro/observedProperty/GRIB650
https://inspire.meteoromania.ro/observedProperty/BUFR0-12-023
https://inspire.meteoromania.ro/observedProperty/BUFR0-12-023SF3PT24H
https://inspire.meteoromania.ro/observedProperty/BUFR0-13-003
https://inspire.meteoromania.ro/observedProperty/BUFR0-11-001SF32PT10M

I hope that these URLs to still pass the tests if any fix to this incident will be depolyed.

**Comment by arantzaetxebarria** [comment]
Dear @robblis 

The ETS has been updated with a fix for this issue on the [staging](http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/home/index.html) instance. Could you please test again and verify?
Thanks

**Comment by robblis** [comment]
Hi @arantzaetxebarria,

We've retested against the fix in the staging instance. The test was successful.

Thanks,
Robert

**Comment by dperezBM** [comment]
Dear @robblis,

Thank you for your feedback. We are going to keep the issue open in order to get tracked until the next release.

Best regards.
