### ISSUE TITLE
Validator reports response language issue for WCS service

### ISSUE THREAD

**Issue by marcingrudzien** [INSPIRE-MIF/helpdesk-validator#532]
Validation of WCS service http://mapy.geoportal.gov.pl/wss/service/PZGIK/ORTO/WCS/StandardResolution?Request=GetCapabilities&service=WCS using WCS Core conformance class reports at09 response language issue. I have verified the service following testing steps from https://github.com/inspire-eu-validation/download-wcs/blob/1.0/wcs-core/at09-response-language.md The behaviour of the service seems to be ok.
1. Request without AcceptLanguages parameter returns capabilities in Polish (default capabilities language)
2. Request with invalid AcceptLanguages parameter (http://mapy.geoportal.gov.pl/wss/service/PZGIK/ORTO/WCS/StandardResolution?Request=GetCapabilities&service=WCS&AcceptLanguages=invalidparametervalue) returns capabilities in the default language 
3. Request with AcceptLanguages parameter set to Polish (http://mapy.geoportal.gov.pl/wss/service/PZGIK/ORTO/WCS/StandardResolution?Request=GetCapabilities&service=WCS&AcceptLanguages=pol) returns capabilities in the default language 
4. Request with AcceptLanguages parameter set to English (http://mapy.geoportal.gov.pl/wss/service/PZGIK/ORTO/WCS/StandardResolution?Request=GetCapabilities&service=WCS&AcceptLanguages=eng) returns capabilities in English

Please let me know whether I should improve the WCS service or this is a validator issue.

Best regards,
Marcin

**Comment by carlospzurita** [comment]
Dear @marcingrudzien 

Thank you for opening the issue. We are checking the GetCapabilities from your service and looking on the TG for Coverage Services.

**Comment by dperezBM** [comment]
Dear @marcingrudzien,

We deployed a correction on our [staging instance](http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/home/index.html). Could you please check if this is valid for you?

Thank you and best regards.
David.

**Comment by marcingrudzien** [comment]
Thank you for the update. The error concerning Accept Languages has been solved. 
However, I noticed new error concerning at04-xml-schema-validation. For the same WCS service the validator returns an error 
`Schema not valid: [org.xml.sax.SAXException: Fatal error: org.xml.sax.SAXParseException; systemId: http://inspire.ec.europa.eu/schemas/inspire_dls/1.0/inspire_dls.xsd; lineNumber: 1; columnNumber: 1; Premature end of file. Response did not validate against schema 'http://www.opengis.net/wcs/2.0 http://schemas.opengis.net/wcs/2.0/wcsAll.xsd http://inspire.ec.europa.eu/schemas/inspire_dls/1.0 http://inspire.ec.europa.eu/schemas/inspire_dls/1.0/inspire_dls.xsd'.]`

When I validate the service GetCapablities response in the independent XML schema validator - Altova XMLSpy, there are no errors.

**Comment by fabiovin** [comment]
Dear @marcingrudzien,

thank you for the test.

Regarding the new error, it should be due to the redirection error from HTTP to HTTPS of the schema http://inspire.ec.europa.eu/schemas/inspire_dls/1.0/inspire_dls.xsd, which makes the schema unavailable.

We will analyze it and give you feedback.

**Comment by carlospzurita** [comment]
Dear @marcingrudzien 

We have applied a fix on the redirection system, and now the error is gone from the Test Report.

Kind regards.

**Comment by marcingrudzien** [comment]
Dear @carlospzurita 

I confirm that everything works fine now. Thank you for your support.

Best regards

**Comment by fabiovin** [comment]
Dear @marcingrudzien,

thank you for the test.

We will include the fix in the next release.
