### ISSUE TITLE
Conformance Class 'Direct WFS' fails on INSPIRE http schema locations

### ISSUE THREAD

**Issue by Kate-Lyndegaard** [INSPIRE-MIF/helpdesk-validator#533]
Hi,

I have created two WFS services based on the same source data. The only difference between the two services, is that one service uses http INSPIRE schema locations and the other uses https INSPIRE schema locations.

The Conformance Class 'Direct WFS' fails for the following service, which uses http INSPIRE schema locations:

WFS: https://test.haleconnect.de/ows/services/org.396.239874b6-e668-4e25-8425-eeed9ae37c48_wfs?SERVICE=WFS&REQUEST=GetCapabilities&VERSION=2.0.0

GetFeature request: https://test.haleconnect.de/ows/services/org.396.239874b6-e668-4e25-8425-eeed9ae37c48_wfs?SERVICE=WFS&VERSION=2.0.0&REQUEST=GetFeature&NAMESPACES=xmlns%28elu%2Chttp%3A%2F%2Finspire.ec.europa.eu%2Fschemas%2Felu%2F4.0%29&TYPENAMES=elu%3AExistingLandUseObject

Validator test:
[LU_Testing.zip](https://github.com/INSPIRE-MIF/helpdesk-validator/files/6200658/LU_Testing.zip)

The Conformance Class 'Direct WFS' does not fail for the following service, which uses https INSPIRE schema locations:

WFS: https://test.haleconnect.de/ows/services/org.396.27a22ca8-949e-411e-ab07-3d1fb6832f88_wfs?SERVICE=WFS&REQUEST=GetCapabilities&VERSION=2.0.0

GetFeature request: https://test.haleconnect.de/ows/services/org.396.27a22ca8-949e-411e-ab07-3d1fb6832f88_wfs?SERVICE=WFS&VERSION=2.0.0&REQUEST=GetFeature&NAMESPACES=xmlns%28elu%2Chttp%3A%2F%2Finspire.ec.europa.eu%2Fschemas%2Felu%2F4.0%29&TYPENAMES=elu%3AExistingLandUseObject

Validator test:
[LU.zip](https://github.com/INSPIRE-MIF/helpdesk-validator/files/6200672/LU.zip)

It would be great if you could take a look at this and provide feedback.

Kind regards,
Kate

**Comment by MetaGIS** [comment]
We have also the same issue.  All direct WFS-services are  now failing .
It seems related to problems requesting external resources both from OGC and Inspire registry.
An example service is
http://geo-inspire.trafikverket.se/mapservice/wfs.axd/TN_WaterTransportNetwork?
(but maybe this service has errors beacuse of not updated local schemafiles.

But we anyhow get this error i validiator

![image](https://user-images.githubusercontent.com/71434590/112797481-bf480280-906b-11eb-909a-8c279a2f7a85.png)

**Comment by carlospzurita** [comment]
Dear @Kate-Lyndegaard and @MetaGIS 

Thank you for opening the issue and providing more info on it. We are trying to reproduce the error with the resources you have sent, and try to debug what is happening in the Direct WFS ETS.

Kind regards.

**Comment by iuriemaxim** [comment]
I confirm as well that the WFS services that previously passed, now are failing, as the INSPIRE schemas were moved from http to https.

Service to test: https://inspire-staging.meteoromania.ro/WIGOS/WFS?Service=WFS&version=2.0.0&request=GetCapabilities

Conformance class to test: Direct WFS

Test result https://inspire.ec.europa.eu/validator/v2/TestRuns/EIDff1d477a-7fbf-426a-b7ff-759a7d53b43f.html

![image](https://user-images.githubusercontent.com/20813598/114361970-7a4dc100-9b7f-11eb-8542-3b93cb212be3.png)

@carlospzurita Should we change ths declarations of the schemas from http to https?

**Comment by carlospzurita** [comment]
Dear @Kate-Lyndegaard and @iuriemaxim

This issue was solved alongside issue #536 , the schemas are accessible again on the production instance.

**Comment by Kate-Lyndegaard** [comment]
Dear @carlospzurita 

Thank you very much!
