### ISSUE TITLE
Certification path errors with WMS services with the URL .bayern.de

### ISSUE THREAD

**Issue by gdi-by** [INSPIRE-MIF/helpdesk-validator#535]
Dear INSPIRE Team,

I'm trying to test some services with the INSPIRE Validator, but there seems to be a problem with the domain .bayern.de.
Here are some WMS services from Bavaria I tried to test with the "Conformance Class: View Service - WMS":
https://geoservices.bayern.de/wms/v1/ogc_feka.cgi?
https://gdiserv.bayern.de/srv1970/services/alpenplan-wms?
https://www.lfu.bayern.de/gdi/wms/natur/biotopkartierung?
I always get the same error: "Test run initialization failure. unable to find valid certification path to requested target."
I used the Firefox Browser Version 87.0 (64-Bit).
I found some other Issues with simliar problems, like this one: https://github.com/INSPIRE-MIF/helpdesk-validator/issues/488
Maybe it's the same problem here?

Thank you very much in advance for your help.

Kind regards
Robin Küspert

**Comment by carlospzurita** [comment]
Dear @gdi-by 

We need to add the certificate of your service into the Java installation of the instance. We are adding it on the staging instance, and will notify you once this is available for you to test.

**Comment by gdi-by** [comment]
Dear carlospzurita,

thank you for your help. Our certificate is available here: https://www.pki.bayern.de/mam/pki/vpki/bayern-root-ca-2019_base64.cer

**Comment by carlospzurita** [comment]
Dear @gdi-by 

The certificates have been added on the [staging instance](staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/). Could you please check it out and test your services? 

Kind regards.

**Comment by gdi-by** [comment]
Dear carlospzurita,

now I can test our services with the Validator. Thank you very much for your help.

Kind regards.
