### ISSUE TITLE
Keywords - details

### ISSUE THREAD

**Issue by IMGWMichal** [INSPIRE-MIF/helpdesk-validator#537]
[result of the test.txt](https://github.com/INSPIRE-MIF/helpdesk-validator/files/6284492/result.of.the.test.txt)

Good morning,

I ran a metadata file test and got an error message regarding keywords.
The content of the message is as follows:
System error in the Executable Test Suite. Please contact a system administrator. Error information:
Code list http://inspire.ec.europa.eu/theme cannot be accessed.

The same file was validated last year and everything was ok.

[scren of raports.docx](https://github.com/INSPIRE-MIF/helpdesk-validator/files/6284572/scren.of.raports.docx)

I use GoogleChrome and Firefox

Please could you help to explain my problem.

Best Regards
Michał Iwaniak
Instytut of Meteorology and Water Management
National Research Instytute

**Comment by ghost** [comment]
Hi @IMGWMichal, 

more information on this problem can be found [here](https://github.com/INSPIRE-MIF/helpdesk-validator/issues/525).

Kind regards

**Comment by iuriemaxim** [comment]
@IMGWMichal the incident was solved as can be seen here: https://github.com/INSPIRE-MIF/helpdesk-validator/issues/536

**Comment by carlospzurita** [comment]
Dear @IMGWMichal 

This issue was indeed solved on #536 and can be closed

**Comment by IMGWMichal** [comment]
Thank you very much for your help.

Sincerely
Michał Iwaniak
________________________________
Od: Carlos Palma Zurita ***@***.***>
Wysłane: wtorek, 13 kwietnia 2021 08:54
Do: INSPIRE-MIF/helpdesk-validator ***@***.***>
DW: Michał Iwaniak ***@***.***>; Mention ***@***.***>
Temat: Re: [INSPIRE-MIF/helpdesk-validator] Keywords - details (#537)


Dear @IMGWMichal<https://github.com/IMGWMichal>

This issue was indeed solved on #536<https://github.com/INSPIRE-MIF/helpdesk-validator/issues/536> and can be closed
