### ISSUE TITLE
WFS Direct Access Test not available on staging

### ISSUE THREAD

**Issue by Kate-Lyndegaard** [INSPIRE-MIF/helpdesk-validator#538]
Hi,
I can no longer access the direct WFS conformance class on the staging instance of the validator. Could you please take a look at this?

![grafik](https://user-images.githubusercontent.com/36956461/114536484-6d010700-9c51-11eb-87e6-d081137e7fb4.png)

Kind regards,
Kate

**Comment by carlospzurita** [comment]
Dear @Kate-Lyndegaard 

Thank you for opening the issue, we are having a look into this to check what is happening.

Kind regards.

**Comment by iuriemaxim** [comment]
This happened also in December 2020. See incident https://github.com/INSPIRE-MIF/helpdesk-validator/issues/474

**Comment by carlospzurita** [comment]
Dear @Kate-Lyndegaard 

There is currently an issue with the beta instance of the TEAM engine which is making unable to execute any test through the INSPIRE validator. This test is used as a dependency for the Direct WFS, and if it is not able to load them, the ETS is not listed on the validator. We have opened an [issue](https://github.com/opengeospatial/teamengine/issues/469) on the TEAM engine repository and we are waiting for their response.

Kind regards.

**Comment by Kate-Lyndegaard** [comment]
Hi @carlospzurita,

Great, thank you:-)

Kind regards,
Kate

**Comment by bcosyn** [comment]
In addition. We face the same issue on our own docker container wich we downloaded from https://github.com/INSPIRE-MIF/helpdesk-validator/packages/149175.
So also there the Direct WFS test dissappeared since last restart today. 

![image](https://user-images.githubusercontent.com/13509656/115585305-c5787a00-a2cb-11eb-9721-396b97bde1ac.png)

**Comment by MichaelOstling** [comment]
We have found that Direct WFS is not available in validator when Team-engine service is not available.
So if reference-validator is started when team-engine is not accessible then this test dissappears in validator.

When we last restarted our national instance of the validator it seems Teamengine WAS running.
http://etf.geodatavalidering.se/etf-webapp

But when we try to run a direct WFS validation we always have to wait for 20 mins timeout (waiting for teamengine to respond).

**Comment by carlospzurita** [comment]
The TEAM engine service deployed by the OGC has undergone some changes on the service which we are trying to adapt for the validator, and checking that the TEAM engine is receiving correctly the WFS endpoint and executing the validation.

**Comment by MetaGIS** [comment]
Ok fine, I now restarted our national validator once again and now the Direct WFS disappeared again.

**Comment by carlospzurita** [comment]
Dear all,

We have been collaborating with the TEAM engine developers on [this issue](https://github.com/opengeospatial/teamengine/issues/469) in their repository. We have offered feedback to them and they are addressing it.

Once it is ready and they roll out the update, we will adapt the validator to their fix.

**Comment by carlospzurita** [comment]
Dear @Kate-Lyndegaard 

We have published a fix for the WFS direct load issue on the staging instance. Please, go to http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/home/index.html and test the integration. We would like to have your feedback to solve this issue.

Kind regards.

**Comment by Kate-Lyndegaard** [comment]
Dear @carlospzurita,

In the new interface, I can access the Direct WFS test however using the following selection which selects only the Direct WFS conformance class, the Pre-defined WFS conformance class is also executed:

![grafik](https://user-images.githubusercontent.com/36956461/135412074-2db40439-c0ed-43c4-9c2f-fc4b3a5ed47f.png)
![grafik](https://user-images.githubusercontent.com/36956461/135412171-3cb4d8d7-86d0-4187-b109-08eb7ab95251.png)

Is this expected?

Kind regards,
Kate

**Comment by fabiovin** [comment]
Dear @Kate-Lyndegaard,

we added the dependency to the Pre-defined WFS conformance class because the test included in it shall also be verified for a "Direct WFS".

See issue #476 for reference.

**Comment by Kate-Lyndegaard** [comment]
Thank you, @fabiovin.
