### ISSUE TITLE
Using the Conformance Class: Download Service - WCS Core (Version 0.1.9) results in WMS error

### ISSUE THREAD

**Issue by nmtoken** [INSPIRE-MIF/helpdesk-validator#54]
- [ ] a description of the steps to reproduce your issue

- Went to http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/

- Selected Conformance Class: Download Service -WCS Core

- Added service end point for WCS 

- Get Error:

`The Test Objekt Type 'OGC Web Map Service 1.3' is not one of the expected types that can be tested in this test run.`

- [ ] the browser and version used

Opera 

Version:60.0.3255.95

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36 OPR/60.0.3255.95

- [ ] a screenshot illustrating the problem
- [ ] the Test Report (ideally as an attachment to the issue)

Test run on 17:35 - 22.05.2019 with test suite Conformance Class: Download Service - WCS Core

- [ ] the name of the Test that failed or better: change the `Level of Detail`
in the Report by clicking on `All Details`, then scroll down to the failed test
and copy the Link on the right-hand side of the `Assertion URI`

Don't have anything like this; fails before a report is created

- [ ] the URL of your service / the file you have uploaded or referenced (as
an attachment).

http://ogc2.bgs.ac.uk/cgi-bin/GEMAS/ows?

If your service is protected or you have confidential data that you cannot
upload here, you can request an email address to which you can send URLs / files.
Please note that issues cannot be investigated for services/datasets that we cannot
access.

**Comment by nmtoken** [comment]
I was just following the URL example in the help which shows an example like **http://example-service/wfs**  which I assumed was an endpoint, i.e the URL to which all request params are added.

Browsing to that URL on it's own gives a warning like: `No query information to decode. QUERY_STRING is set, but empty. `  So the validator must be adding the wrong parameters to get a `OGC Web Map Service 1.3` message (oddly it seems that even that is an issue as there is no WMS 1.3 version, version must be 1.3.0)...

**Comment by michellutz** [comment]
I tried with http://ogc2.bgs.ac.uk/cgi-bin/GEMAS/ows?request=GetCapabilities&service=wcs and that worked fine. Indeed the validator seems to be adding some wrong request parameters to the base URL to request the Capabilities.

**Comment by josemasensio** [comment]
We are reviewing the community issues and this issue is related to [40](https://github.com/inspire-eu-validation/community/issues/40). We close this issue.
