### ISSUE TITLE
inspire-validator-2021.1 - Test Run initialization failure

### ISSUE THREAD

**Issue by reinij** [INSPIRE-MIF/helpdesk-validator#540]
Hi,

In 2021.1 I get a following message when configuring a test run and added metadata URL , no errors in a log file. Any ideas?

"Test Run initialization failure
The system has currently insufficient resources to process this request. Please wait a few minutes and try again. If the problem persists, please contact the ETF system administrator of the server."

BR,
Jari

**Comment by carlospzurita** [comment]
Dear @reinij 

Thank you for raising the issue, we are taking a look into it. Is this happening in the production instance on https://inspire.ec.europa.eu/validator ?

Kind regards.

**Comment by reinij** [comment]
Dear @carlospzurita,

No, it is my own Docker instance. I haven't faced this kind of problem earlier. http://193.167.189.42/validator/

**Comment by carlospzurita** [comment]
Please check the status page http://193.167.189.42/validator/v2/status and see the result under totalSpace and freeSpace keys. It may be that the disk space available where the `~/etf` folder is located is insuficcient.

**Comment by reinij** [comment]
Thanks. Disk space was indeed the reason.
