### ISSUE TITLE
Null pointer exception when validation WMS-services

### ISSUE THREAD

**Issue by MichaelOstling** [INSPIRE-MIF/helpdesk-validator#542]
We are having problems making the validator work properly with following service
**https://geodata.naturvardsverket.se/geoserver/BIOGEO/wms?REQUEST=GetCapabilities&SERVICE=WMS&VERSION=1.3.0**
Result is here
https://inspire.ec.europa.eu/validator/v2/TestRuns/EIDa9c69a0c-a61e-4731-9df4-500d27c2af11.html

The validator generates  a number of NullPointerException. and the validation is not completed properly
21.04.2021 10:18:59 - TestRunTask initialized
21.04.2021 10:19:19 ERROR Exception occurred in Test Step: java.lang.NullPointerException
21.04.2021 10:19:19 ERROR Exception occurred in Test Step: java.lang.NullPointerException
21.04.2021 10:19:19 ERROR Exception occurred in Test Step: java.lang.NullPointerException
21.04.2021 10:19:19 ERROR Exception occurred in Test Step: java.lang.NullPointerException

We have tested to place a identical capabilities file on separate website 
**https://gis-services.metria.se/nvfeed/capabilities/wms/BIOGEO_130.xml**

In this case we do not get these errors. The capabilities-files content  are identifical.

Some minor differences that have been seen is that content-type is text/xml instead of application/xml
Also that the content-encoding is gzip.
But when these are changed we still see no difference.

We are stucked in finding the cause of this.
Is there a way to set debug-level as DEBUG or INFO  on our national instance of validator so we can possible trace what steps are generating java.lang.NullPointerException

/MIchael

**Comment by carlospzurita** [comment]
Dear @MichaelOstling 

Thank you for raising the issue and providing the endpoints for the services. We are reproducing the error on our environments and will get back to you with some feedback.

Unfortunately right now we don't have the support to modify the debug level through the properties files but we will take note of this and explore the option to let users further configure their deployment

Kind regards.

**Comment by milanSch** [comment]
Hello, 
please, how did you solve this problem? 

I see that your service do not throw 
'ERROR Exception occurred in Test Step: java.lang.NullPointerException' 
any more.

I have two very similar WMS services on two different servers (IIS+ArcGIS), one of them is OK (possible to validate), but second throw errors:

08.12.2021 16:55:39 - TestRunTask initialized
08.12.2021 16:56:02 ERROR Exception occurred in Test Step: java.lang.NullPointerException
08.12.2021 16:56:02 ERROR Exception occurred in Test Step: java.lang.NullPointerException
08.12.2021 16:56:02 ERROR Exception occurred in Test Step: java.lang.NullPointerException
08.12.2021 16:56:02 ERROR Exception occurred in Test Step: java.lang.NullPointerException
08.12.2021 16:56:02 ERROR Exception occurred in Test Step: java.lang.NullPointerException
08.12.2021 16:56:02 ERROR Exception occurred in Test Step: java.lang.NullPointerException
08.12.2021 16:56:02 ERROR Exception occurred in Test Step: java.lang.NullPointerException
08.12.2021 16:56:02 ERROR Exception occurred in Test Step: java.lang.NullPointerException
08.12.2021 16:56:02 ERROR Assertion failed with error 'TR.getMapSupportedFormat'
08.12.2021 16:56:02 ERROR Exception occurred in Test Step: java.lang.NullPointerException
08.12.2021 16:56:02 ERROR Exception occurred in Test Step: java.lang.NullPointerException
08.12.2021 16:56:10 - Releasing resources
08.12.2021 16:56:10 - Changed state from INITIALIZED to RUNNING

Validator result of problematic WMS service is here: 
https://inspire.ec.europa.eu/validator/test-run/index.html?id=EIDf087dc2e-e1f8-430d-81b0-f45d8ca60b94

thank you
milan

**Comment by fabiovinci** [comment]
Dear @MichaelOstling,

do you still have the problem?
Have you tried the latest version?

**Comment by milanSch** [comment]
Hello, 
it is OK for me. 
I have moved from ArcGIS Server (we didn't have INSPIRE extension) to Geoserver (with INSPIRE extension) and validator works.
Thank you.
milan
