### ISSUE TITLE
Problem with links certificates in validation process. CNIG (Spain)

### ISSUE THREAD

**Issue by LauraAlemany** [INSPIRE-MIF/helpdesk-validator#543]
Hello, 

We are trying to validate service metadata files, and we have an issue with metadata links site certificate.
I think is the same issue as #488. 
Can you add the certs chain into server, in order to validate the metadata ?

An example is this service metadata file: 
http://www.idee.es/csw-codsi-idee/srv/spa/csw?SERVICE=CSW&VERSION=2.0.2&REQUEST=GetRecordById&outputSchema=http://www.isotc211.org/2005/gmd&ElementSetName=full&ID=spaignwms_unidades_administrativas

The provided error is:

The metadata record set has 1 record(s) with errors for this assertion.
XML document 'spaignwms_unidades_administrativas.xml', record 'spaignwms_unidades_administrativas': The metadata record has a linkage property, but it references a resource at 'https://www.idee.es/csw-inspire-idee/srv/spa/csw?SERVICE=CSW&VERSION=2.0.2&REQUEST=GetRecordById&outputSchema=http://www.isotc211.org/2005/gmd&ElementSetName=full&ID=spaignLLM#bdlje_limites_adm' that cannot be accessed. An exception occured when accessing the resource. Error message: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

The links base url are the following (issued by **CNIG**)
https://www.idee.es/csw-inspire-idee/srv/spa/csw
https://www.idee.es/csw-codsi-idee/srv/spa/csw
https://servicios.idee.es/wms-inspire/transportes

Thank you in advance!

Laura Alemany

**Comment by carlospzurita** [comment]
Dear @LauraAlemany,

It is indeed the same issue that on #488 . We are adding the certificates for those services as well in the staging deployment. We will notify you whenever is ready.

Kind regards.

**Comment by LauraAlemany** [comment]
Hello @carlospzurita, 

Here I  send you some more information about our certificates: 
We use certificates  from "GEANT OV RSA CA 4”, which in turn is authorised by “USERTrust RSA Certification Authority". Both of them are public authorities accepted by all the latest browsers.

The "GEANT OV RSA CA 4” certificate is relatively recent (18th of February, 2020). If the validator is using a new version of Java, there won't be any problem. 

Nevertheless, if the system is using an older version of Java, it won't have these certificates as authorised. In this case, you could bring up to date the version of Java or you can fix it by importing the certificate I attach with the following code: 
[geant.zip](https://github.com/INSPIRE-MIF/helpdesk-validator/files/6389846/geant.zip)
keytool -import -alias geantovrsaca4 -keystore $JAVA_HOME/jre/lib/security/cacerts -file geant.pem

Thank you. 

Best regards,
Laura

**Comment by carlospzurita** [comment]
Dear @LauraAlemany 

Thank you for your feedback. We are indeed using and older distribution of Java, and so this installation may not recognize the signing authority for this certificate. We are including it on the staging deployment and come back to you with an update.

Kind regards.

**Comment by LauraAlemany** [comment]
Hello @carlospzurita, 

You're wellcome. I hope this will work. Tell us when it is ready so that we can try again. 

Kind regards.

**Comment by carlospzurita** [comment]
Dear @LauraAlemany 

The certificate has been added on the [staging instance](staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/). Could you please check it out and test your metadata again?

Kind regards.

**Comment by LauraAlemany** [comment]
Hello @carlospzurita,

I have already check it out in the [staging instance](http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/test-selection/index.html) and it is working. We don't have this issue anymore.

Thank you. 

Kind regards.

**Comment by dperezBM** [comment]
Dear @LauraAlemany,

Thank you for your feedback. We will mark this issue as solved then.
Please, feel free to open a new issue if you have any other questions or problems.

Best regards.
