### ISSUE TITLE
Running a validation fails 

### ISSUE THREAD

**Issue by JohannaOtt** [INSPIRE-MIF/helpdesk-validator#548]
- I uploaded a dataset to the production instance - upload was successful but test run could not be started 
![grafik](https://user-images.githubusercontent.com/34163838/118804602-2ed8b200-b8a5-11eb-8c66-0125e97caee1.png)

- I am using Firefox 78.10.1esr on Windows
- I tried to test against Hydrography conformance classes

**Comment by JohannaOtt** [comment]
The same is true when trying to run a Direct WFS test.

**Comment by JohannaOtt** [comment]
Test runs work again today.
The WFS test does return a 504 though 
![grafik](https://user-images.githubusercontent.com/34163838/118967845-7c1f5700-b96b-11eb-93b8-600f44b5b37c.png)
I tested with https://haleconnect.com/ows/services/org.789.f5f15dcd-b11a-491e-a37c-bec458c8c1b6_wfs?SERVICE=WFS&REQUEST=GetCapabilities&VERSION=2.0.0
Validating the same services worked a few days ago.

**Comment by carlospzurita** [comment]
Dear @JohannaOtt 


We have published a fix for the WFS direct load issue on the staging instance. Please, go to http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/home/index.html and test the integration. We would like to have your feedback to solve this issue.

Kind regards.

**Comment by JohannaOtt** [comment]
I can confirm that the WFS OGC test does not run into a HTTP 504 any longer.

**Comment by dperezBM** [comment]
Dear @JohannaOtt,

Thank you for your feedback. We will mark this issue as solved.

Best regards.
