### ISSUE TITLE
hasObservation/ObservingCapability test for EMF does not work correctly

### ISSUE THREAD

**Issue by JohannaOtt** [INSPIRE-MIF/helpdesk-validator#555]
- When validating an EMF dataset with no observations attached to the EnvironmentalMonitoringFacility objects and no values for EnvironmentalMonitoringFacility.observingCapability, the validator states `XML document [...], EnvironmentalMonitoringFacility [...]: The constraint 'Check that if observation(s) are attached to an EnvironmentalMonitoringFacility or an EnvironmentalMonitoringNetwork feature type this shall have an ObservingCapability attached to it' is violated. ` for all EnvironmentalMonitoringFacility objects. As no observation(s) are attached, no ObservingCapability element should be expected.

- ![grafik](https://user-images.githubusercontent.com/34163838/121021263-803bd900-c7a1-11eb-9245-2abf90759552.png)

- this is the test report 
[Test.zip](https://github.com/INSPIRE-MIF/helpdesk-validator/files/6609073/Test.zip)

- Test ID is EID7a856198-d010-4b4f-a3be-cdc4ce474f7f

- this is the file tested 
[testExport.zip](https://github.com/INSPIRE-MIF/helpdesk-validator/files/6609081/testExport.zip)

**Comment by carlospzurita** [comment]
Dear @JohannaOtt 

We are checking the EF ETS with your data, and also taking a look into de ATS for this case. We will get back to you with some more feedback.

Kind regards.

**Comment by arantzaetxebarria** [comment]
Dear @JohannaOtt 

We have updated the ETS with a fix. Could you please test it again in the [staging](http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/home/index.html) instance? Thanks.

Regards.

**Comment by JohannaOtt** [comment]
LGTM

**Comment by dperezBM** [comment]
Dear Johanna,

Thank you very much for your message. We are going to leave the issue open. We will close it when we make a new release.
If you have any other problem, please do not hesitate to open another issue.

Best regards.
