### ISSUE TITLE
Self-intersection not found

### ISSUE THREAD

**Issue by danicgc** [INSPIRE-MIF/helpdesk-validator#560]
Dear team,

The test gmlas.d.10 (Validate geometries 1) throws an error (self-intersection) that I can not find in the specified feature (ID.PS.natura2000.548.zec.ES0000020.zepa.ES0000020). Previously it found the same error in some other features and I could repair them, but I can not see the problem in the mentioned feature.

The report is https://inspire.ec.europa.eu/validator/v2/TestRuns/EID292a31ae-88ec-455b-a42f-33da62176349.html and the data tested, corresponding to the Protected Sites theme, is https://datacloud.ide.cat/geodades/inspire-llocs-protegits/inspire-natura2000-etrs89-geo.gml

Could you help me, please?

Thank you so much.

**Comment by fabiovin** [comment]
Dear @danicgc,

I think the error detected by the validator is right.

I had a quick look at your GML file using QGIS and performing a geometry check detects a self-intersection.

I hope this helps you.

![image](https://user-images.githubusercontent.com/46569952/122892842-0a5d7300-d346-11eb-8ddf-19a18023d3da.png)

**Comment by danicgc** [comment]
Dear @fabiovin,
Thank you so much for the clues. I have found an error while transforming data into GML.
Best regards,
