### ISSUE TITLE
INSPIRE Validator v2021.2: Beta label in the UI

### ISSUE THREAD

**Issue by ghost** [INSPIRE-MIF/helpdesk-validator#562]
Hi,

thanks a lot for providing us the new version of the validator. 

Could someone please answer following question: 
The validator has "BETA" label on the production instance. Is the system still fully functional? 
![grafik](https://user-images.githubusercontent.com/38787131/122164650-62dcce00-ce77-11eb-84df-5192651e48f9.png)

Kind regards.

**Comment by MarcoMinghini** [comment]
Dear @DeordD,
we have also noticed this and have already a plan to remove the label. I confirm that the production instance is not a beta version but is fully functional.

**Comment by MarcoMinghini** [comment]
The BETA label was removed from both instances. Thanks again for reporting it.
