### ISSUE TITLE
Validator 2021.2 docker deploy

### ISSUE THREAD

**Issue by manilly** [INSPIRE-MIF/helpdesk-validator#563]
Hi,
I tried to install the new validator on our own server using self-built docker image. But it seems, the Image i get when building the docker file gets the old UI?
Our instance is running on https://inspire.agrarforschung.at/validator/

The dockerfile is pointing to the new version: 
`ENV COMPONENT=ETF`
`ARG ETF_VERSION_INSTALL=2021.2`
`ENV ETF_VERSION=${ETF_VERSION_INSTALL}`
`ENV ETF_DOWNLOAD=https://github.com/INSPIRE-MIF/helpdesk-validator/releases/download/v${ETF_VERSION}/inspire-validator-${ETF_VERSION}.zip`
`ENV ETS_DOWNLOAD=https://github.com/INSPIRE-MIF/helpdesk-validator/releases/download/v${ETF_VERSION}/ets-repository-${ETF_VERSION}.zip`
`ENV ETF_BASE_DATA_DIR=/etf`
`ENV ETF_DATA_DIR=${ETF_BASE_DATA_DIR}`
`ENV TC_USER=donked`
`ENV TC_GROUP=tomcat`

Do you have an idea why i get the old version?

Thanks, Manuel

**Comment by carlospzurita** [comment]
Dear @manilly 

What port are you exposing for the Docker container? Please take into account that the deployment instructions for this release have changed and the instruction to run the image is now

`docker run --name inspire-validator -d -p 8090:8090 -v ~/etf:/etf [IMAGE_NAME]:[VERSION]`

Kind regards

**Comment by manilly** [comment]
Hi,
im using Port 443 cause of security reasons (as on previous docker deploys)
Here my run command: `docker run -d --restart always -p 443:8443 --name tomcat-etf tomcat-etf:2021.2`

**Comment by fabiovinci** [comment]
Dear @manilly,

do you still have this kind of issue with new releases?

**Comment by manilly** [comment]
Hi @fabiovinci ,
no, the issue is solved. I'll close this one.
