### ISSUE TITLE
Unable to Validate Transportation Networks tn-c:CablewayLinkSet

### ISSUE THREAD

**Issue by robblis** [INSPIRE-MIF/helpdesk-validator#566]
I've been attempting to run the following request to Validate the Transportation Networks tn-c:CablewayLinkSet.

http://agsinspire1.esri.com/arcgis/rest/services/tnc/MapServer/exts/InspireFeatureDownload/service?VERSION=2.0.0&SERVICE=WFS&REQUEST=GetFeature&LANGUAGE=&TYPENAMES=tn-c:CablewayLinkSet&namespaces=xmlns(tn-c,http://inspire.ec.europa.eu/schemas/tn-c/4.0)&MAXFEATURES=&COUNT=&f=image

I keep seeing the "An error has occurred" box in the lower corner.

Thanks for any help with this,
Robert

**Comment by fabiovin** [comment]
Dear @robblis,

we detected an error in the new UI that prevents the correct selection of the tests related to the Cable application schema, so the API call fails.

We are working on this and a solution will be available soon.

**Comment by fabiovin** [comment]
Dear @robblis,

the fix is available in [staging](http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/home/index.html), now you can upload your file.

Could you test it?

Thanks,
Fabio

**Comment by robblis** [comment]
Hi @fabiovin 

We've ran the test again. We did not experience the "Error has occurred" box in the lower corner.

Thank you for the fix.

Robert
