### ISSUE TITLE
TN - tn-ro:RoadSurfaceCategory fails Transport Network feature in dataset

### ISSUE THREAD

**Issue by robblis** [INSPIRE-MIF/helpdesk-validator#569]
Hi Validator Team,

While testing Transportation Networks, I ran into a failure for the tn-ro:RoadSurfaceCategory feature test.

I get the following error in the Conformance class: GML application schemas, Transport Networks -> Basic test -> Transport Network feature in dataset.

_The XML documents representing the spatial data set do not contain a feature of any of the spatial object types in the 'Transport Networks' application schemas. Therefore, the spatial data set cannot conform to this conformance class. If you have expected to find spatial objects from the application schema in the data set, please consult the statistics information to see the spatial object types that have been found._

I don't see the RoadSurfaceCategory listed in the test criteria.

Can I get some help on why this particular feature is failing this test?

Here is the serivce URL:
http://agsinspire1.esri.com/arcgis/rest/services/tnc/MapServer/exts/InspireFeatureDownload/service?VERSION=2.0.0&SERVICE=WFS&REQUEST=GetFeature&LANGUAGE=&TYPENAMES=tn-ro%3ARoadSurfaceCategory&MAXFEATURES=&COUNT=100&f=image

I've attached the returned XML if needed.

Thanks,
Robert

[RoadSurfaceCategory.zip](https://github.com/INSPIRE-MIF/helpdesk-validator/files/6703713/RoadSurfaceCategory.zip)

**Comment by robblis** [comment]
Hi @fabiovin ,

I just wanted to check if there's any progress on this issue. We're working on validation fixes preparing for a new release of our application and saw that this issue is still pending.

I made sure the service was online if you need to run some tests.

Thanks,
Robert

**Comment by fabiovinci** [comment]
Dear @robblis,

sorry for the late reply.

There was a typo in the ATS and in the ETS, there is the value "`tn-ro:RoadServiceCategory"` instead of "`tn-ro:RoadSurfaceCategory`".

We will update them and implement the fix in the staging instance.

@dperezBM, I have updated the [ATS](https://github.com/inspire-eu-validation/data-tn/blob/master/tn-gml/basic.md) and created a PR for the [ETS](https://github.com/inspire-eu-validation/ets-repository/blob/master/data-tn/tn-gml/ets-tn-gml-bsxets.xml), could you please check if there are other occurrences of the wrong value?

**Comment by arantzaetxebarria** [comment]
Dear @robblis 

The fix has been updated into [staging ](http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/home/index.html)environment, could you please verify that your issue now is correct? Thanks

Regards

**Comment by robblis** [comment]
Hi @arantzaetxebarria 

I've re-tested the service using the staging validator, and the test came back successful for the Conformance class: GML application schemas, Transport Networks.

Thanks for the fix,
Robert
