### ISSUE TITLE
Overall duration of a test executed in ETF via API

### ISSUE THREAD

**Issue by klimeto** [INSPIRE-MIF/helpdesk-validator#57]
Dears,

Is anybody from our community using ETF API to execute the INSPIRE tests on their resources?

I have been working on an integration of ETS provided by ETF API and tested mainly the ETSs for INSPIRE dataset metadata ETS TG2.0 including 3 tests for a metadata record:
1. Common ISO19139 requirements [EID59692c11-df86-49ad-be7f-94a1e1ddd8da]
2. Conformance class 1 INSPIRE datasets and series baseline metadata [EIDe4a95862-9cc9-436b-9fdd-a0115d342350]
3. Conformance class 2 INSPIRE datasets and series interoperability metadata [EID2be1480a-fe42-40b2-9420-eb0e69385c80]

In total the ETF executed 37 tests per a metadata record and I measured also overall duration for a single run average execution time of 38.87 seconds collected from about 4000 executed tests.

I also did a manual test via ETF GUI and received similar time between test start and report visualization about 37 seconds.

I would like to ask you whether this performance values are expected and whether it can be improved?

We would like to integrate the ETF validation via its API also to our new MD Editor interface which we will shortly start to develop, but we fear the users will not be very happy to wait almost 40 seconds for a single metadata validation job.

ETF endpoint used: 

```url
http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/v2/
```   

Thank you for your feedback and other experiences with the performance and usage of ETF API.

**Comment by klimeto** [comment]
@inakidiazdecerio @MarcoMinghini 

I would like to share with you the performance data we have collected since 16 July with you.

[etf_api_performace.zip](https://github.com/inspire-eu-validation/community/files/3581130/etf_api_performace.zip)

The JSON contains ETS UUIDs, Execution time and timestamp.

The average execution time we measured is 55.31s / Test Run.

Do you have any suggestions how to improve the execution time for a single DS/DSS/ND metadata validation?

Many thanks,
Tomas

**Comment by josemasensio** [comment]
Dear @klimeto,

After some test and performance check, we observed that the ETF API is slow because of the external dependencies like the schemas. The validator has to download all of them and once these are downloaded, this will run the test. 

For now, there is no way to improve the test speed via API, but we are looking at alternative methods to improve the response time in the future.

Best regards.

**Comment by klimeto** [comment]
@josemasensio 

Thanks for answer.

What schemas do mean? 

Aren't the schemas for the same tests as e.g. dataset and network service metadata validation always the same?

Is the validator downloading them for each Tested Object?

Thanks,

**Comment by josemasensio** [comment]
Dear @klimeto ,

By schema we mean the schema location that the metadata files have in the header like http://schemas.opengis.net/csw/2.0.2/profiles/apiso/1.0.0/apiso.xsd. One of the first validations is that the file is compliant with the schema referred in the header, to do that ETF validator has to make a request to that url and sometimes those external urls were not responding as fast as they should. Please check it again and if you still have problems let us know.

Best Regards,
Jose

**Comment by klimeto** [comment]
@josemasensio mentioned this in first message: we are looking at alternative methods to improve the response time in the future.

Should we keep updates on these improvements here or you want to create another issue?

Thanks,

**Comment by dperezBM** [comment]
Dear @klimeto,

Since the last interaction, the validator has had different modifications and changes in terms of its execution process. Therefore, in case you need a follow-up, we see the need to open a new issue. 

Please feel free to open an issue if necessary.

Best regards
