### ISSUE TITLE
INSPIRE validator v2021.2 15/06/2021 - do not working

### ISSUE THREAD

**Issue by masle45** [INSPIRE-MIF/helpdesk-validator#570]
Hi,

could you please help us with our problem with validator v2021.2 15/06/2021.

Previous version of validator was working correctly, but we have problem with latest version.
First problem is: 
If i try upload file to validator, validator say " An error has occured uploading file (code: 0 - )

Second problem is: 
When user try start validate of metadata record on server. Validator says " An error has occured".

Our validator is on this address: inspire.cenia.cz/validator/
It is running via Docker. 

Thank you for help.

**Comment by jenriquesoriano** [comment]
Dear  @masle45 

we have analysed your case and it seems that there is an incorrect request that may be caused by the deployment configuration, since the upload action results in a request to http://localhost:8090/validator/rest/TestObjects?action=upload , which cannot be reached from a local client.

Could you access to INSPIRE-Validator-UI/js/config.js and provide us with the values assigned to:
- var serverURL 
- var serverRealURL 
- var serverCaptchaURL 

Thank you in advance

Best regards,

**Comment by dperezBM** [comment]
Dear @kad-schipr,

Have you been able to solve the problem?

Best regards.

**Comment by kad-schipr** [comment]
Hello @dperezBM,

I had another problem (#582) which has now been resolved, but I didn't have the problem of this issue.

Thanks.

**Comment by fabiovin** [comment]
Dear @masle45,

looking at the configuration of your instance (https://inspire.cenia.cz/validator/js/config.js) it seems you are using local addresses (i.e. http://localhost:8090/).

Could you try replacing them with the main address?

**Comment by masle45** [comment]
Hi, sorry for delay. I was on vacation.

here are values from config.js
// PROD
//var serverURL = "
https://inspire-sandbox.jrc.ec.europa.eu/validator-testbed/rest/";
//var serverRealURL = "https://inspire.ec.europa.eu/validator/v2/";
//var serverCaptchaURL = "
https://inspire-sandbox.jrc.ec.europa.eu/validator-testbed/captcha/verify.php
";
// SANDBOX
var serverURL = "http://localhost:8090/validator/rest/";
var serverRealURL = "http://localhost:8090/validator/v2/";
var serverCaptchaURL = "https://localhost:8090/validator/captcha/verify.php
";
// STAGING
//var serverURL = "
http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/validator/v2/
";
//var serverRealURL = "
http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/validator/v2/
";
//var serverCaptchaURL = "
http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/validator/captcha/verify.php
";
// PROD CONTRACTOR
// var serverURL = "
http://inspire-validator.eu-west-1.elasticbeanstalk.com/validator/v2/";
// var serverRealURL = "
http://inspire-validator.eu-west-1.elasticbeanstalk.com/validator/v2/";
// var serverCaptchaURL = "
http://inspire-validator.eu-west-1.elasticbeanstalk.com/validator/captcha/verify.php
";

Kind regards
Marek

pá 2. 7. 2021 v 14:08 odesílatel jenriquesoriano ***@***.***>
napsal:

**Comment by fabiovin** [comment]
Hi @masle45,

no problem!

Meanwhile, I had recovered the configuration parameters from your server (https://inspire.cenia.cz/validator/js/config.js).

Could you try to use the full address instead of the localhost one?

_var serverURL = "https://inspire.cenia.cz/validator/rest/";
var serverRealURL = "https://inspire.cenia.cz/validator/v2/";
var serverCaptchaURL = "https://inspire.cenia.cz/validator/captcha/verify.php_

**Comment by masle45** [comment]
Hi,

i have changed these rows and validator still do not work. It says same
error, i have tried instead of full-address use hostname and it didn't help.

Kind Regards
Marek

st 1. 9. 2021 v 16:03 odesílatel Fabio Vinci ***@***.***>
napsal:

**Comment by fabiovin** [comment]
Dear @masle45,

thank you for the test.

We’ll take a look and give you feedback.

**Comment by dhdeangelis** [comment]
I wonder if there is anything new related to this issue. I am experiencing a similar problem with a docker image of 2021.2 while trying to validate a local file:

**An error has occured uploading file (Code: 404 - Not Found)**

Could this be a permissions issue?

The content of _~/etf/validator/js/config.js_ is

var captchaEnabled = false;
var betaBanner = false;
var labelStaging = false;
// PROD
//var serverURL = "https://inspire-sandbox.jrc.ec.europa.eu/validator-testbed/rest/";
//var serverRealURL = "https://inspire.ec.europa.eu/validator/v2/";
//var serverCaptchaURL = "https://inspire-sandbox.jrc.ec.europa.eu/validator-testbed/captcha/verify.php";
// SANDBOX
var serverURL = "http://localhost:8090/validator/rest/";
var serverRealURL = "http://localhost:8090/validator/v2/";
var serverCaptchaURL = "https://localhost:8090/validator/captcha/verify.php";
// STAGING
//var serverURL = "http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/validator/v2/";
//var serverRealURL = "http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/validator/v2/";
//var serverCaptchaURL = "http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/validator/captcha/verify.php";
// PROD CONTRACTOR
// var serverURL = "http://inspire-validator.eu-west-1.elasticbeanstalk.com/validator/v2/";
// var serverRealURL = "http://inspire-validator.eu-west-1.elasticbeanstalk.com/validator/v2/";
// var serverCaptchaURL = "http://inspire-validator.eu-west-1.elasticbeanstalk.com/validator/captcha/verify.php";

Running in Linux (openSUSE Tumbleweed).

Thanks in advance

**Comment by masle45** [comment]
Hi,
i haven't got any new info from JRC. Is there any progress?

Thank you for answer.

**Comment by masle45** [comment]
Hi, i found a solution to my previous problem. Problem was in config.js file, after i eddited correctly these three lines:
 // var serverURL =
// var serverRealURL =
// var serverCaptchaURL =
Validator runs fine, but i have additional problem.
After i restart docker container, value of these three lines in config.js file are default. 
Could you please tell me where i can find and change setting that do this?

Thank you

**Comment by fabiovinci** [comment]
Dear @masle45,

do you still have this kind of issue?

**Comment by fabiovinci** [comment]
Dear @masle45,
since there was no reply, I will close the issue.
Please reopen it or open a new issue if the error persists.
