### ISSUE TITLE
Swager UI documentation can't be reached

### ISSUE THREAD

**Issue by ghost** [INSPIRE-MIF/helpdesk-validator#571]
Hi,

[Swager-UI](https://inspire.ec.europa.eu/validator/swagger-ui.html) documentation can not be reached on production and test instance:

![grafik](https://user-images.githubusercontent.com/38787131/123374843-120c5a00-d588-11eb-9d25-2bc554b5f3a2.png)

Could you please check this?

Thanks in advance!

**Comment by jenriquesoriano** [comment]
Dear @deord, 

thanks for pointing the issue, we are aware of this behaviour.
We have experienced issues in the swagger deployment.
We will keep you posted as soon as it is solved.

Best,

**Comment by jenriquesoriano** [comment]
Dear @DeordD , 

we have solved this swagger issue in the staging instance, so you can access to it (http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/validator/swagger-ui.html)
We continue working to solve this issue in the production environment.

Best

**Comment by carlospzurita** [comment]
Dear @DeordD 

We have published a fix on the production instance and made the Swagger page available again. You can check it at https://inspire.ec.europa.eu/validator/swagger-ui.html
