### ISSUE TITLE
Download service, Conformance Class Pre-defined Atom, test issues

### ISSUE THREAD

**Issue by ChristianEliassonLM** [INSPIRE-MIF/helpdesk-validator#572]
Greetings,
I noticed some issues while running tests against one of our atom feeds, endpoint https://api-ver.lantmateriet.se/byggnad/atom/v1.1/inspire/bu

The problems, that I believe are bugs in the test itself, seems to be in the "Dataset feed > User INSPIRE media-types only"-part of the test.

1. Syntax error on line 3128 in the file "ds-atom-pre-defined-soapui-project.xml". I did a fix on a local copy to get past this error, but then encountered the next issue.
2. When the test is trying to get a list of acceptable media types, from url https://inspire.ec.europa.eu/media-types/application, the test expects an xml response, but is in fact receiving an html page. I tried doing the same request with the header "Accept:application/atom+xml" using postman/curl and I'm getting the expected xml response.

Link to a recently run test: 
https://inspire.ec.europa.eu/validator/test-run/index.html?id=EID497aa157-e770-44e5-be7f-6351bf8f9872

There are more errors reported in the test, but those are most likely on our side.

**Comment by dperezBM** [comment]
Dear @ChristianEliassonLM,

We deployed a correction on our [staging instance](http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/home/index.html). Could you please check if this is valid for you?

Thank you and best regards.
David.

**Comment by ChristianEliassonLM** [comment]
Hello @dperezBM,

It looks like the first issue is fixed.

The second issue seems to still be present in staging.
The validator attempts to get INSPIRE media subtypes from "https://inspire.ec.europa.eu/media-types/application", with header "Accept: application/atom+xml", but for some reason a html response is received.
I have tested to make the same request manually and I get the correct response(xml), could you verify that the correct accept header is applied when the validator makes the request?
Test report http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/test-run/details.html?id=EIDfd0e80e8-47cb-4595-89db-6fe19fc590e5

**Comment by fabiovin** [comment]
Dear @ChristianEliassonLM,

I tested in staging your ATOM (http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/test-run/details.html?id=EID39a0e6cb-27ad-41bb-83dc-53dab419b628) and regarding the first error "Get Service Feed from Resource Locator" the results are:

- In your service (https://api-ver.lantmateriet.se/byggnad/atom/v1.1/inspire/bu) there is the following element
`<link href="https://www.geodata.se/geodataportalen/srv/swe/csw-inspire?request=GetRecordById&service=CSW&version=2.0.2&elementSetName=full&id=0cb3aab8-2f1c-47d8-abec-8b49d7686a3e&outputSchema=csw:IsoRecord" rel="describedby" type="application/xml" hreflang="sv" title="Metadata, nedladdningstjänst för Inspire Byggnad"/>`

- The validator requests the document from the Resource Locator of the metadata but finds a **different** URL https://api.lantmateriet.se/byggnad/atom/v1.1/inspire/bu

- When the validator checks the document finds the following element:
`<link href="https://www.geodata.se/geodataportalen/srv/swe/csw-inspire?request=GetRecordById&service=CSW&version=2.0.2&elementSetName=full&id=0cb3aab8-2f1c-47d8-abec-8b49d7686a3e&outputSchema=csw:IsoRecord" rel="describedby" type="application/vnd.iso.19139+xml" hreflang="sv" title="Metadata, nedladdningstjänst för Inspire Byggnad"/>`

- So comparing the two elements the _href_ link is the same but the **_type_ is different**


Could you verify that, please?

**Comment by ChristianEliassonLM** [comment]
@fabiovin

Yes that looks correct.
Now things are starting to clear up on my side.
From your explanation the I gather that the flow is roughly.
We start the validation on our verification environment service, and follow a link that leads to our production metadata, which in turn has a link to the production environment for the service.

So when we get to the part where the ETF validator is trying to get inspire media sub-types, we are operating on data from the production environment of the service.

Then it seems like the second part of this issue is not a bug and is in fact working as intended.

Thank you for all the help.

**Comment by fabiovin** [comment]
Hi @ChristianEliassonLM,

I am pleased to hear that the functioning is clearer now.

Thank you for reporting the issue, we will include the related fix in the next release.
