### ISSUE TITLE
ExtendedCapabilities ResourceType is present, validator does not see it

### ISSUE THREAD

**Issue by MichalMed** [INSPIRE-MIF/helpdesk-validator#573]
Before reporting an issue with the INSPIRE validator deployed at JRC, please check the [list of known limitations](https://github.com/INSPIRE-MIF/helpdesk-validator/wiki/Known-limitations).

I'm validating following CSW service http://62.159.72.87:8080/geonetwork/srv/eng/csw?SERVICE=CSW&VERSION=2.0.2&REQUEST=GetCapabilities

I'm getting an error:
`Exactly one 'ExtendedCapabilities/ResourceType' element shall be provided. It was found 0 or more than 1.`

Anyway, resourceType is present exactly once.

**Comment by alitka** [comment]
Just a guess @MichalMed : If you remove the <ows:ExtendedCapabilities>-tags, the test should be pass.

Also I would recommend, to change http://localhost:8080/geonetwork/srv/eng/csw to http://62.159.72.87:8080/geonetwork/srv/eng/csw

**Comment by alitka** [comment]
Also I would recommend, to change http://localhost:8080/geonetwork/srv/eng/csw to http://62.159.72.87:8080/geonetwork/srv/eng/csw

**Comment by arantzaetxebarria** [comment]
Dear @MichalMed 

We have verified that alitka's proposal is correct. @alitka thanks a lot for your contribution.
@MichalMed, could you please make the suggested changes? Thanks.

Best regards.

**Comment by MichalMed** [comment]
I have made the changes, anyway, I am not able to confirm, becuase the validator does not show the results. 

https://inspire.ec.europa.eu/validator/test-run/details.html?id=EIDa6bf4b8d-e8cd-4f84-91b1-495ea593fdd6

Anyway, why is it not acceptable to have ows:ExtendedCapabilities element in GC? It is perfectly valid in XSD validation and it was also valid in the previous versions of INSPIRE validator.

**Comment by MichalMed** [comment]
Also to the localhost and IP issue, this is not a crucial thing due to the fact this version is for test purposes only and the production version will not run at localhost. Geonetwork is generating it this way, which is unlucky, but not wrong.

**Comment by MichalMed** [comment]
Validator works, I confirm it works.
