### ISSUE TITLE
Validator sees a language which is not from ISO

### ISSUE THREAD

**Issue by MichalMed** [INSPIRE-MIF/helpdesk-validator#574]
Validation of a service http://62.159.72.87:8080/geonetwork/srv/eng/csw?SERVICE=CSW&VERSION=2.0.2&REQUEST=GetCapabilities throws the following error:

`check-language-parameter-iso: The following language(s) is(are) not ISO 639-2/B alpha 3 valid: ,`

Anyway, only languages used in the capabilites document are 'ger' and 'eng', both ISO valid.

**Comment by alitka** [comment]
Just a guess @MichalMed : If you remove the <ows:ExtendedCapabilities>-tags, the test should be pass.

Also I would recommend, to change http://localhost:8080/geonetwork/srv/eng/csw to http://62.159.72.87:8080/geonetwork/srv/eng/csw

**Comment by arantzaetxebarria** [comment]
Dear @MichalMed 

We have verified that alitka's proposals are correct. @alitka thanks a lot for your contribution.
@MichalMed, could you please make the suggested changes? Thanks.

Best regards.

**Comment by MichalMed** [comment]
same as #573

**Comment by MichalMed** [comment]
Working
