### ISSUE TITLE
Default language cardinality fails

### ISSUE THREAD

**Issue by MichalMed** [INSPIRE-MIF/helpdesk-validator#575]
I'm validating this service: http://62.159.72.87:8080/geonetwork/srv/eng/csw?SERVICE=CSW&VERSION=2.0.2&REQUEST=GetCapabilities

I get the following error: `check-language-cardinality: Exactly one 'DefaultLanguage' element shall be provided. It was found 0 or more than 1.`

There is exactly one Default language element in the capabilities document.

**Comment by alitka** [comment]
Just a guess @MichalMed : If you remove the <ows:ExtendedCapabilities>-tags, the test should be pass.

Also I would recommend, to change http://localhost:8080/geonetwork/srv/eng/csw to http://62.159.72.87:8080/geonetwork/srv/eng/csw

**Comment by arantzaetxebarria** [comment]
Dear @MichalMed

We have verified that alitka's proposals are correct. @alitka thanks a lot for your contribution.
@MichalMed, could you please make the suggested changes? Thanks.

Best regards.

**Comment by MichalMed** [comment]
same as #573

**Comment by MichalMed** [comment]
Working
