### ISSUE TITLE
"Try the API" not working

### ISSUE THREAD

**Issue by MarieLambois** [INSPIRE-MIF/helpdesk-validator#577]
In the landing page the link with "Try the API" is not working: https://inspire.ec.europa.eu/validator/swagger-ui.html
Click here:
![image](https://user-images.githubusercontent.com/12797943/124273977-fb926f80-db40-11eb-9f09-c9b713502a5c.png)
To reproduce the issue.

**Comment by MarcoMinghini** [comment]
Dear @MarieLambois,
thanks for noticing this. This was already reported in https://github.com/INSPIRE-MIF/helpdesk-validator/issues/571 so I'm closing this issue and point you there to follow the discussion.
