### ISSUE TITLE
SOS Test - Hint for the expected SOS service URL

### ISSUE THREAD

**Issue by CarstenHollmann** [INSPIRE-MIF/helpdesk-validator#58]
If you start the SOS-Test the pop-up window "Konfiguriere Testlauf" ("Configure test run") appears. There you find the "Service URL" field but without any information which specific URL is expected.

At first we entered the URL of the SOS instance but that did not work. After that we tried the SOS KVP GetCapabilities request URL and that worked. Thus, a hint that the URL for the capabilities document should be entered would be very helpful

**Comment by josemasensio** [comment]
Dear @CarstenHollmann,

Thank you for your comments.

There is a proposal to add a placeholder inside the text box, indicating the necessary information that the URL needs. The improvement is planned, we will be changing the issue labels with the progress of the development.

Best regards.

**Comment by carlospzurita** [comment]
Dear @CarstenHollmann 

We added a placeholder for services validation on the staging to be tested by the community. You can check it on http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp

**Comment by CarstenHollmann** [comment]
Thanks, that helps to define the users to enter the correct URL
