### ISSUE TITLE
TN - Validator Reports Error for Missing Codelist

### ISSUE THREAD

**Issue by robblis** [INSPIRE-MIF/helpdesk-validator#580]
Hi Validator Team,

We are seeing the following errors while validating TN CableWayLinkSet feature on the Staging Validator.

_Conformance Class 'INSPIRE GML application schemas', General Requirement > Code list values in basic data types > GrammaticalNumber attributes

System error in the Executable Test Suite. Please contact a system administrator. Error information:Code list http://inspire.ec.europa.eu/codelist/GrammaticalNumberValue cannot be accessed._

So for the GrammaticalNumberValue element we have it set to a Nil Reason. 
<gn:grammaticalNumber xsi:nil="true" nilReason="other:unpopulated"/>

This seems to be allowed in the Schema. 

Not sure why this is reporting as an error.

Other elements are being reported with similar errors about codelists. We're also seeing it in other Annex I themes, (e.g. Address). Again, we see this only on the Staging Validator. 

Also, the error mentions something about Annex II in the following sentence, which seems out of place since this is Annex I.
"When an attribute has a code list as its type, verify that the values comply with the definitions and include the values set out in Annex II of the regulation. "

I've attached the XML file and report.

Here's the URL to the rest request used for the test.
http://agsinspire1.esri.com/arcgis/rest/services/tnc/MapServer/exts/InspireFeatureDownload/service?VERSION=2.0.0&SERVICE=WFS&REQUEST=GetFeature&LANGUAGE=&TYPENAMES=tn-c:CablewayLinkSet&namespaces=xmlns(tn-c,http://inspire.ec.europa.eu/schemas/tn-c/4.0)&MAXFEATURES=&COUNT=&f=image

Thanks for any help,
Robert

[TN_CableWayLinkSet_ValidationTests.zip](https://github.com/INSPIRE-MIF/helpdesk-validator/files/6772663/TN_CableWayLinkSet_ValidationTests.zip)

**Comment by fabiovin** [comment]
Dear @robblis,

sorry for the late reply.

We’re analysing the issue, and we’ll let you know when the solution is available.

Thanks,
Fabio

**Comment by fabiovinci** [comment]
Dear @robblis,

the error you reported is no more present (see results [here](https://inspire.ec.europa.eu/validator/test-run/details.html?id=EID85263678-9d7f-4e0b-9f90-2b9bc8eb1d72)).

Could you please verify and confirm?

Thanks

**Comment by robblis** [comment]
Hi @fabiovin ,

We re-tested validation for TN Cableway, and we don't see that reported error.

Thank you for the fix.

Robert
