### ISSUE TITLE
The default style names for layer SU.StatisticalGridCell and AF.AquacultureHolding for view service are wrong?

### ISSUE THREAD

**Issue by kad-schipr** [INSPIRE-MIF/helpdesk-validator#582]
Hello,

Currently the validator seems to be using SU.StatisticalGridCell and AF.AquacultureHolding, instead of SU.StatisticalGridCell.Default and AF.AquacultureHolding.Default

This issue is similar to https://github.com/INSPIRE-MIF/helpdesk-validator/issues/473

Thanks!

**Comment by fabiovin** [comment]
Dear @kad-schipr,

thank you for opening this issue.

We will review the related ETSs and let you know when the solution is available.

**Comment by dperezBM** [comment]
Dear @kad-schipr 

We have published a fix for this issue on the [staging instance](http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/test-selection/index.html). Could you please check it out?
Thanks

**Comment by dperezBM** [comment]
Dear @kad-schipr,

Have you been able to test the correction on [staging instance](http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/test-selection/index.html)? Has this fixed the issue?

Thank you.

**Comment by kad-schipr** [comment]
Hello @dperezBM,

Thanks for your patience. I've tested a View Service (WMS) with the staging instance and would like to report that this issue has been resolved.

Thanks!
