### ISSUE TITLE
problem with validator v2021.2 13/07/2021

### ISSUE THREAD

**Issue by sofiaribeiro-apa** [INSPIRE-MIF/helpdesk-validator#583]
Hello,
could you please help us with our problem with validator v2021.2 15/06/2021.
Previous version of validator was working correctly, but we have problem with latest version.
First problem is:
If i try upload file to validator, validator say " An error has occured uploading file (code: 0 - )
Second problem is:
When user try start validate a dataset gml (zip or not zip) Validator says " An error has occured".

Could you answer to sofia.ribeiro@apambiente.pt
Thank you for help.
Sofia Cunha

**Comment by fabiovinci** [comment]
Dear @sofiaribeiro-apa,

do you still have this kind of issue?

**Comment by sofiaribeiro-apa** [comment]
Heelo Fabio,
Yes i still have this mesage in the new interface:
***@***.***Best regards

**Comment by fabiovinci** [comment]
Dear @sofiaribeiro-apa,

are you using your local version or the public production instance?

Could you provide the resource you are testing?

**Comment by sofiaribeiro-apa** [comment]
Dear Fabio,
I am using local version, and try to test the bathing water facilities dataset.We don´t have gml at our public production.
I am sending you the gml tested, it will give the spatial reference error but is intentional, it passed already in previous tests done with the previous testing validator.
Just tell me if you can test it.
Best regards
Sofia

**Comment by sofiaribeiro-apa** [comment]
Hello
I cannot use the reference validator online: https://inspire.ec.europa.eu/validator/home/index.html
I can upload the file but than it gives me an error 
HTTP ERROR 406
Problem accessing /validator/v2/TestRuns/EIDa43e5c08-61da-414f-a9b3-b7a0ca0b0eb9.html. Reason:
    Not Acceptable
So i cannot validate my dataset.
Can you help me please
Br
[lamas2.zip](https://github.com/INSPIRE-MIF/helpdesk-validator/files/9113966/lamas2.zip)

Sofia Cunha

**Comment by sofiaribeiro-apa** [comment]
Hi,
I cannot validate a gml at inspire validator.
I get the message
HTTP ERROR 406
Problem accessing /validator/v2/TestRuns/EIDa43e5c08-61da-414f-a9b3-b7a0ca0b0eb9.html. Reason:
    Not Acceptable
Can you help me please
best regards
Sofia Cunha

**Comment by fabiovinci** [comment]
Dear @sofiaribeiro-apa,

could you provide the resource you are testing?
It was not attached to previous messages.
Thanks.

**Comment by sofiaribeiro-apa** [comment]
I have this problem even with files that were already submitted and that area ok.
I will send you an example from environmental facilities bathing water.
Best regards
Sofia

**Comment by fabiovinci** [comment]
Since there were no further interactions we will close the issue.
Please reopen the issue or open a new one if the error persists.
