### ISSUE TITLE
Assert ServiceExceptionReport too strict

### ISSUE THREAD

**Issue by copierrj** [INSPIRE-MIF/helpdesk-validator#584]
Test at56-getmap-width-height-parameter asserts (Assertion ID: EIDb00066eb-18c7-4134-af8d-da9345975503) that omitting width and height results in a ServiceExceptionReport. Unfortunately it only recognizes reports with exactly one ServiceException. According to the XML schema (http://schemas.opengis.net/wms/1.3.0/exceptions_1_3_0.xsd) it is actually allowed to include multiple instances of ServiceException.

Rejected exception report:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<ServiceExceptionReport version="1.3.0" xmlns="http://www.opengis.net/ogc" xsi="http://www.w3.org/2001/XMLSchema-instance" schemaLocation="http://www.opengis.net/ogc http://schemas.opengis.net/wms/1.3.0/exceptions_1_3_0.xsd">
 <ServiceException code="MissingParameterValue" locator="WIDTH">Missing key: WIDTH</ServiceException>
 <ServiceException code="MissingParameterValue" locator="HEIGHT">Missing key: HEIGHT</ServiceException>
</ServiceExceptionReport>
```

**Comment by fabiovin** [comment]
Dear @copierrj,

we are analyzing the issue, in the meantime could you please send us the resource you tested, in order to reproduce and verify the issue.

Thanks,
Fabio

**Comment by dperezBM** [comment]
Dear @copierrj,

Please, in order to reproduce the issue, could you send us the resource?

Thank you.

**Comment by dperezBM** [comment]
Dear @copierrj,

We are still trying to fix the issue that you reported to us. Please, in order to reproduce the issue, could you send us the resource?

Best regards.

**Comment by dperezBM** [comment]
Dear @copierrj,

We are closing this issue due to the inactivity on this thread. Please feel free to open a new issue if needed.

Best regards.
