### ISSUE TITLE
http for ISO 19139 and https for ISO 19115 in WMS metadata example

### ISSUE THREAD

**Issue by Kate-Lyndegaard** [INSPIRE-MIF/helpdesk-validator#585]
Hi,

The example of [WMS service metadata](https://github.com/INSPIRE-MIF/helpdesk-validator/blob/3ca47955d6ab9e024ae14f85c880b7a95e0ebcf4/examples/NetworkService_WMS_metadata_2.0_example.xml) seems to use http for ISO 19139 codelists and https for ISO 19115 codelists. I am just wondering if there is any particular reason for this.

I am aware of the decision made in the former MIWP 2017.4, [meeting #11 2019-07-17](https://webgate.ec.europa.eu/fpfis/wikis/display/InspireMIG/2017.4+meeting+%2311+2019-07-17). It would be great to have a recommendation of which URIs to use.

Kind regards,
Kate

**Comment by fabiovin** [comment]
Dear @Kate-Lyndegaard,

there are no particular reasons for this.

The only restriction is for the values of the INSPIRE Registry, for which the **_http_** link is required to be used as **URI**.

**Comment by dperezBM** [comment]
Dear all,

Since this issue had no interaction time ago, we decided to close it. Please feel free to open a new one if needed.

Thank you and best regards.
