### ISSUE TITLE
Land Use - Testing ExistingLandUseSample reports 'LandUseClassificationValue' shall be provided

### ISSUE THREAD

**Issue by robblis** [INSPIRE-MIF/helpdesk-validator#586]
Hi Validator Team,

We're running the ExistingLandUseSample feature type through the validator.

We're seeing the following error being reported...

Conformance class: Information accessibility, Land Use > Code list > LandUseClassificationValue(specificValue)
XML document 'service.xml', SpecificPercentage '': The attribute 'xlink:href' of the element 'LandUseClassificationValue' shall be provided.

However, the returned xml contains elements and values for the xlink:href attribute for the SpecificPercentage/lunom:specificValue element.
```
<lunom:SpecificPercentage>
    <lunom:specificValue xlink:title="sp_per_specificValue_3" xlink:href="http://inspire.ec.europa.eu/codelist/LandUseClassificationValue"/>
```

Can someone help assess what could be wrong?

I've attached the returned xml and the validator report.

The service url is: http://agsinspire1.esri.com/arcgis/rest/services/luc/MapServer/exts/InspireFeatureDownload/service?REQUEST=GetFeature&SERVICE=WFS&VERSION=2.0.0&TYPENAMES=selu:ExistingLandUseSample&namespaces=xmlns(selu,http://inspire.ec.europa.eu/schemas/selu/4.0)

Thanks,
Robert 

[ExistingLandUseSample_Test.zip](https://github.com/INSPIRE-MIF/helpdesk-validator/files/6824928/ExistingLandUseSample_Test.zip)

**Comment by arantzaetxebarria** [comment]
Dear @robblis 

We have checked your example "ExistingLandUseSample_Result.xml" and at the end of it, there are two empty <lunom:specificValue/> without the attribute. Could you please verify? Thanks.

Regards

**Comment by robblis** [comment]
Hi @arantzaetxebarria 

We checked the data and results on our side and we discovered that the issue seems to be on our side. I'll go ahead and close the issue.

Thanks for the help,
Robert

**Comment by robblis** [comment]
Hi @arantzaetxebarria ,

Meant to click the close with comment button.

Closing now.
