### ISSUE TITLE
at36-getcapabilities-layer-bounding-box: check-layer-bounding-box

### ISSUE THREAD

**Issue by alitka** [INSPIRE-MIF/helpdesk-validator#587]
- [x] a description of the steps to reproduce the issue
1. go to https://inspire.ec.europa.eu/validator/test-selection/index.html and select `View Service` AND `Web Map Service (WMS)`
2. start the test and enter Service URL: https://inspire.brandenburg.de/services/au_bdlm_wms?request=GetCapabilities&service=WMS&version=1.3.0
- [x] used browser and version: Firefox Browser Extended Support Release 78.11.0esr (64-bit)
- [x] screenshot of the problem
![grafik](https://user-images.githubusercontent.com/29542183/125928753-c6405e96-d576-4d0a-aa17-8db617d2d723.png)
- [x] Test Report: [de_wms_at36-error.zip](https://github.com/INSPIRE-MIF/helpdesk-validator/files/6829727/de_wms_at36-error.zip)
- [x] name of the failed Test: at36-getcapabilities-layer-bounding-box: check-layer-bounding-box (Layer Geographic Bounding Box); [Test Step URI](https://inspire.ec.europa.eu/validator/v2/TestRuns/EIDaa7a7d17-eab2-4509-a311-52a1e63cb37a.html?lang=de#EIDaeb9410c-017a-1000-e249-b2c57a0c473d)
- [x] URL of the service: https://inspire.brandenburg.de/services/au_bdlm_wms?request=GetCapabilities&service=WMS&version=1.3.0

The test claims, that the 'Layer/BoundingBox'-element is missing, but it should inherit from the parent layer as described in the ATS: 
> For each named Layer element:
> - Check that at least one BoundingBox element exists in the layer itself or it is inherited from parent layers.
> - For each BoundingBox in the layer, 
>   - Check that the attribute 'CRS' of BoundingBox is defined in a CRS element of the layer itself or in a parent layer.

To avoid this error, we have to copy the BoundingBox-entries to each layer, but this couldn't be the solution! Therefore, could you please check the inheritance from the parent/root layer level to the existing layers?

Thanks & regards.

**Comment by dperezBM** [comment]
Dear @alitka,

We deployed a correction on our [staging instance](http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/home/index.html). Could you please check if this is valid for you?

Thank you and best regards.
David.

**Comment by hogredan** [comment]
Dear @dperezBM ,

on behalf of @alitka I can confirm that the fix on staging instance is fine for us.

Thanks and best regards!

**Comment by fabiovin** [comment]
Dear @hogredan,

thank you for the confirmation.
We will include this fix in the next release.
