### ISSUE TITLE
Problems with metadata validator

### ISSUE THREAD

**Issue by IsotoCedex** [INSPIRE-MIF/helpdesk-validator#588]
Before reporting an issue with the INSPIRE validator deployed at JRC, please check the [list of known limitations](https://github.com/INSPIRE-MIF/helpdesk-validator/wiki/Known-limitations).

Please replace these lines with a brief summary of your issue and the expected
behaviour.

To help us investigate the issue, you may want to include:

- [ tray to validate a metadata dataset in https://inspire.ec.europa.eu/validator/test-selection/index.html] a description of the steps to reproduce your issue
- [google and edge. latest versions ] the browser and version used
- [
![metadata](https://user-images.githubusercontent.com/87642224/126133270-14a6a526-2e72-48f9-b249-253ad54f1f56.png)
 ] a screenshot illustrating the problem
- [https://inspire.ec.europa.eu/validator/test-run/details.html?id=EID68a62307-0383-4ffd-9bdf-89916f9bda42 ] the Test Report (ideally as an attachment to the issue)
- [ https://inspire.ec.europa.eu/validator/v2/TestRuns/EID68a62307-0383-4ffd-9bdf-89916f9bda42.xml] the name of the Test that failed or better: change the `Level of Detail`
in the Report by clicking on `All Details`, then scroll down to the failed test
and copy the Link on the right-hand side of the `Assertion URI`
- [ ] the URL of your service / the file you have uploaded or referenced (as
an attachment).

If your service is protected or you have confidential data that you cannot
upload here, you can request an email address to which you can send URLs / files.
Please note that issues cannot be investigated for services/datasets that we cannot
access.

**Comment by fabiovin** [comment]
Dear @IsotoCedex,

we’re analysing the issue, and we’ll let you know when the solution is available.

Thanks,
Fabio

**Comment by IsotoCedex** [comment]
Dear Fabio,

By now Inspire Validator is working.

It seems to me that this problem happens several times.

Probably due to changes in the backend of the web.

Thanks so much.

Ignacio Soto Molina
Contratado I+D+i / Área de Ruido Ambiental
Centro de Estudios de Técnicas Aplicadas (CETA)

Tel. 91 335 72 68
Ext. 7268
Email: ***@***.***

    [LOGOTIPO_CORREO_ELECTRONICO]

De: Fabio Vinci ***@***.***
Enviado el: miércoles, 28 de julio de 2021 9:53
Para: INSPIRE-MIF/helpdesk-validator ***@***.***>
CC: Ignacio Soto Molina ***@***.***>; Mention ***@***.***>
Asunto: Re: [INSPIRE-MIF/helpdesk-validator] Problems with metadata validator (#588)


Dear @IsotoCedex<https://github.com/IsotoCedex>,

we’re analysing the issue, and we’ll let you know when the solution is available.

Thanks,
Fabio

**Comment by dperezBM** [comment]
Dear @IsotoCedex,

Thank you for your reply. We will proceed to close this issue. 
If the problem appears again, please let us know with a comment on issue #580.

Thank you and best regards.
