### ISSUE TITLE
Upload of data not possible

### ISSUE THREAD

**Issue by JohannaOtt** [INSPIRE-MIF/helpdesk-validator#589]
I just tried to validate an AM dataset in the validator. 
When trying to upload, it does not work. I see this error message in the console 
![grafik](https://user-images.githubusercontent.com/34163838/126159778-cbdd0336-e17f-4d2d-a9ef-45b39e978889.png)

The behavior is the same on the staging instance.

Is there anything going on currently?

**Comment by fabiovin** [comment]
Dear @JohannaOtt,

I'm currently able to upload/[validate ](https://inspire.ec.europa.eu/validator/test-run/details.html?id=EID40d7a541-5b13-437a-a82b-b37139a0d27c)an AM gml file, could you please provide more info on the resource you are trying to validate?

Thanks,
Fabio

**Comment by JohannaOtt** [comment]
I was able to upload one as well right now.
