### ISSUE TITLE
Limitations on Public Access -  access and use constraints  vadlidation

### ISSUE THREAD

**Issue by LieGeo** [INSPIRE-MIF/helpdesk-validator#592]
I am trying to validate metadata

The check of the access and use constraints always fails, even if I try to user the xml Code from the INSPIRE Dokumentation.
Is this test working properly? Or do i have an issue with the encoding?
Attachted Metadate-File

  <gmd:resourceConstraints>
		  <gmd:MD_LegalConstraints>
      <gmd:accessConstraints>
           <gmd:MD_RestrictionCode codeList="http://standards.iso.org/iso/19139/resources/gmxCodelists.xml#MD_RestrictionCode" codeListValue="otherRestrictions" />
      </gmd:accessConstraints>
      <gmd:otherConstraints>
           <gmx:Anchor xlink:href="http://inspire.ec.europa.eu/metadata-codelist/ConditionsApplyingToAccessAndUse/noConditionsApply">Keine Zugangs- und Nutzungsbedingungen
           </gmx:Anchor>
      </gmd:otherConstraints>
    </gmd:MD_LegalConstraints>
    </gmd:resourceConstraints>	

 
Metadata-Record here
[xml_iso19139.zip](https://github.com/INSPIRE-MIF/helpdesk-validator/files/6899360/xml_iso19139.zip)

**Comment by alitka** [comment]
Dear @LieGeo ,

1. to pass the test "md_ common req C.17: Limitation on Public Access" you have to entry the following xml-snippet in your metadata record
``<gmd:resourceConstraints>``
``<gmd:MD_LegalConstraints>``
``<gmd:accessConstraints>``
``<gmd:MD_RestrictionCode codeList="http://standards.iso.org/iso/19139/resources/gmxCodelists.xml#MD_RestrictionCode" codeListValue="otherRestrictions"/>``
``</gmd:accessConstraints>``
``<gmd:otherConstraints>``
``<gmx:Anchor xlink:href="http://inspire.ec.europa.eu/metadata-codelist/LimitationsOnPublicAccess/noLimitations">Es gelten keine Zugriffsbeschränkungen</gmx:Anchor>``
``</gmd:otherConstraints>``
``</gmd:MD_LegalConstraints>``
``</gmd:resourceConstraints>``

2. to pass the test "md_ common req C.18: Contitions for Access and Use" you have to entry the following xml-snippet in your metadata record
``<gmd:MD_LegalConstraints>``
``<gmd:useConstraints>``
``<gmd:MD_RestrictionCode codeList="http://standards.iso.org/iso/19139/resources/gmxCodelists.xml#MD_RestrictionCode" codeListValue="otherRestrictions"/>``
``</gmd:useConstraints>``
``<gmd:otherConstraints>``
``<gmx:Anchor xlink:href="http://inspire.ec.europa.eu/metadata-codelist/ConditionsApplyingToAccessAndUse/noConditionsApply">Es gelten keine Bedingungen</gmx:Anchor>``
``</gmd:otherConstraints>``
``</gmd:MD_LegalConstraints>``
``</gmd:resourceConstraints>``

Just a note: in your schemaLocation-attribute I saw some special characters, which in my opinion don't belong in the link: ``&#xA;``

Kind regards.

**Comment by LieGeo** [comment]
Thank you for feedback

do you have a code snippet thats fullfills both tests?

According to the test description, only one gmd:MD_LegalConstraints ist allowed
Regards

**Comment by alitka** [comment]
@LieGeo, you'll find attached the adjusted file ([xml_iso19139_edited.zip](https://github.com/INSPIRE-MIF/helpdesk-validator/files/6905586/xml_iso19139_edited.zip)) , which passes  the following tests:
* Common Requirements for ISO/TC 19139:2007 based INSPIRE metadata records
  * Conformance Class 1: Baseline metadata for data sets and data set series
  * Conformance Class 2: INSPIRE data sets and data set series interoperability metadata
  * Conformance Class 2b: INSPIRE data sets and data set series metadata for Monitoring

In order to show you my adjustments in a transparent and easy to comprehend way, I only commented out your original entries.

**Comment by fabiovin** [comment]
Dear @LieGeo,

you can find some example metadata here: https://github.com/INSPIRE-MIF/helpdesk-validator/tree/master/examples

**Comment by dperezBM** [comment]
Dear all,

Since this issue had no interaction time ago, we decided to close it. Please feel free to open a new one if needed.

Thank you and best regards.
