### ISSUE TITLE
AF Agricultural and Aquacultural Facilites, activity and function checks

### ISSUE THREAD

**Issue by manuelkauder** [INSPIRE-MIF/helpdesk-validator#595]
Dear all,

I hope adressing this here is the correct way and point.

I am working on a GML of the AF theme from Annex III.

Running the EU-Validator gives two errors, one with the activity and one with the function value.

1. activity

![grafik](https://user-images.githubusercontent.com/89637851/131298946-59c1b92f-cc86-41b5-b7e9-c1ae9e3a0dde.png)

So if I am understanding this right, the EU-Validator should check the xlink value, but it expects somehow an item.
The code snippet from one feature in the GML look like this:

<af:Site gml:id="S.A_23054487BFEF452081370EABB34D8670">
	<af:geometry >
		<gml:Point gml:id="S.A_23054487BFEF452081370EABB34D8670-0" srsName="http://www.opengis.net/def/crs/EPSG/0/4258" srsDimension="2">
			<gml:pos>54.306526 8.653756</gml:pos>
		</gml:Point>
	</af:geometry>
	<af:activity xlink:href="http://inspire.ec.europa.eu/codeList/EconomicActivityNACEValue/A.03.22" xlink:title="A.03.22 SÃ¼ÃŸwasseraquakultur"/>
	<af:includesAnimal >
	<af:FarmAnimalSpecies >
		<af:aquaculture nilReason="unknown" xsi:nil="true"/>
	</af:FarmAnimalSpecies>
	</af:includesAnimal>
</af:Site>

This might be an error in the validator and I hope I am not making a fool of myself.

2. function

![grafik](https://user-images.githubusercontent.com/89637851/131300731-01d24632-0259-4469-ad0e-7bc1bb033f98.png)

So in this error I get an data type violation.  What I do not understand here is, that the GML is vaild to the schema. Would an error like this not result in an invalid GML?

Here is also an code snippet from the GML for that error, watch out here the items are not closed at the end:

<gml:featureMember >
<af:Holding gml:id="H.d41d8cd98f00b204e9800998ecf8427e">
			<act-core:inspireId >
				<base:Identifier >
					<base:localId >H.d41d8cd98f00b204e9800998ecf8427e</base:localId>
					<base:namespace >https://registry.gdi-de.org/id/de.sh/</base:namespace>
					<base:versionId nilReason="unknown" xsi:nil="true"/>
				</base:Identifier>
			</act-core:inspireId>
			<act-core:geometry >
				<gml:MultiPoint gml:id="H.d41d8cd98f00b204e9800998ecf8427e-0" srsName="http://www.opengis.net/def/crs/EPSG/0/4258" srsDimension="2">
					<gml:pointMember >
						<gml:Point gml:id="H.d41d8cd98f00b204e9800998ecf8427e-1">
							<gml:pos>54.306526 8.653756</gml:pos>
						</gml:Point>
					</gml:pointMember>
				</gml:MultiPoint>
			</act-core:geometry>
			<act-core:function >
				<act-core:Function >
					<act-core:activity xlink:href="http://inspire.ec.europa.eu/codeList/EconomicActivityNACEValue/A.03.22" xlink:title="A.03.22 Süßwasseraquakultur"/>
				</act-core:Function>
			</act-core:function>

A full link to the report is here, if its still available:
[https://inspire.ec.europa.eu/validator/test-run/details.html?id=EID68176098-3bba-4571-ba3c-801fb7649899](url)

I hope this helps you to improve the validator and to correct the checks.

Kind regards

Manuel

**Comment by dperezBM** [comment]
Dear @manuelkauder,

We are analyzing the issue. 
In the meanwhile, could you please send us the GML file or the URL pointing to the dataset that you are working with, in order to reproduce the issue?

Thank you and best regards.
David

**Comment by manuelkauder** [comment]
You find the gml here: 

[https://github.com/manuelkauder/AF](url)

I have shrinked it down to one feature. It still produces the same errors.

**Comment by arantzaetxebarria** [comment]
Dear @manuelkauder 

We have analysed the issue and this is our conclusion:

The codelist validation is case sensitive so in the 2 cases, the URL instead
http://inspire.ec.europa.eu/**codeList**/EconomicActivityNACEValue/A.01.47 should be http://inspire.ec.europa.eu/**codelist**/EconomicActivityNACEValue/A.01.47

Please test these changes and let us know if all is ok.

Regards
Arantza

**Comment by manuelkauder** [comment]
hey guys,

it works fine with the changed urls.

I was just wondering that both urls point to same website.

And I just found another error in the data set. So the validator works with http and not with https.

Changed that too and it passes the test.

Thanks to all of you.
