### ISSUE TITLE
INSPIRE Profile of WMS 1.3.0 / ISO 19128: Language Parameter bug

### ISSUE THREAD

**Issue by mpleic** [INSPIRE-MIF/helpdesk-validator#599]
Hello,

Our [service](https://geoportal.dgu.hr/services/inspire/orthophoto_2019_2020/wms?service=wms&version=1.3.0&request=GetCapabilities) fails only at the [Language Parameter](http://inspire.ec.europa.eu/id/ats/view-service/review-ats-tg_3.11/iso-19128/at68-language-parameter) test, but it should not, because, as the test describes, service returns a valid XML file and default Title and Abstract elements when a GetCapabilities request with a language parameter is sent ([URL](https://geoportal.dgu.hr/services/inspire/orthophoto_2019_2020/wms?service=wms&version=1.3.0&request=GetCapabilities&language=eng)) - the same elements as without language parameter set.

The test returns error message: "The response to an http request was not a xml document."

We deployed the test suite locally and changed [L5812](https://github.com/inspire-eu-validation/ets-repository/blob/master/service/vs-wms-soapui-project.xml#L5812) from
`for (i in ts.testRequest.response.responseHeaders.get('Content-Type')){`
to
`for (i in ts.testRequest.response.responseHeaders.get('content-type')){`
because, we tried log the responseHeaders to see the content of it
`log.info(ts.testRequest.response.responseHeaders);`
and we got:

_2021-09-07 11:00:10.188 [Thread-39] INFO  g.log - date : Tue, 07 Sep 2021 11:00:09 GMT
transfer-encoding : chunked
content-disposition : inline; filename=getcapabilities_1.3.0.xml
x-frame-options : SAMEORIGIN
content-encoding : gzip
**content-type** : text/xml
#status# : HTTP/1.1 200 
cache-control : max-age=0, must-revalidate_

So, changing the 'Content-Type' property to lower case 'content-type' done the work, and service passed the test. Otherwise it returns NULL, and test fails.

Here are the relevant test reports (failed and passed): [Test suite Conformance Class View Service WMS.html.zip](https://github.com/INSPIRE-MIF/helpdesk-validator/files/7121330/Test.suite.Conformance.Class.View.Service.WMS.html.zip).

Can you please include this fixes in the next validator release (v2021.3 - 15/09/2021)?

Thank you in advance.
Marko Pleić

**Comment by fabiovin** [comment]
Dear @mpleic,

thank you for opening the issue and for proposing and testing a solution.

We’ll analyze it and get back to you.

**Comment by dperezBM** [comment]
Dear @mpleic,

This issue was solved on #558. Could you please check if this is valid for you?

Thank you and best regards

**Comment by mpleic** [comment]
Dear @dperezBM,

We checked our service on your staging instance and it passed the Language Parameter test. Issue reported on #558 solved our problem too. It seems to be the same problem we reported. So, I apologize for not being able to find it because it has already been reported.

However, our service now fails the [GetMap Width and Height Parameter](https://github.com/inspire-eu-validation/view-service/blob/review-ats-tg_3.11/iso-19128/at56-getmap-width-height-parameter.md). The test report is [here](https://github.com/INSPIRE-MIF/helpdesk-validator/files/7403518/Test.run.on.18_33.-.23.10.2021.with.test.suite.Conformance.Class.View.Service.WMS.html.zip). It passes on the official validator version and it passed last time we tested it when we reported this issue. 

The test returns error message: "A GetMap was requested without mandatory parameter 'WIDTH AND HEIGHT' and the service did not throw an exception." But service [returns ](http://geoportal.dgu.hr/services/inspire/orthophoto_2019_2020/ows?BBOX=13.411044339958774%2C42.331527990127356%2C19.120291730531214%2C46.561397447794434&CRS=CRS%3A84&FORMAT=image%2Fpng&LAYERS=OI.OrthoimageCoverage&REQUEST=GetMap&SERVICE=WMS&STYLES=raster&VERSION=1.3.0)ServiceExceptionReport.

So I did a little research. WMS test suite on the staging instance no longer checks ServiceException presence in the service's exception response (Line [L4522](https://github.com/inspire-eu-validation/ets-repository/blob/master/service/vs-wms-soapui-project.xml#L4522) of the WMS test suite is [changed](https://github.com/inspire-eu-validation/ets-repository/commit/a1f4c51230bd8192610db2e2f2670f81e7857fdd)). 

According to the [OGC WMS 1.3.0 Exception XML schema](http://schemas.opengis.net/wms/1.3.0/exceptions_1_3_0.xsd) and the same [schema](https://github.com/geoserver/geoserver/blob/main/src/wms/src/main/resources/schemas/wms/1.3.0/exceptions_1_3_0.xsd) being used in GeoServer implementations, an exception response could contain zero or several ServiceException elements. 

Therefore I propose the following solution, change [L4531](https://github.com/inspire-eu-validation/ets-repository/blob/staging/service/vs-wms-soapui-project.xml#L4531) and other similar code occurences checking an Exception XML content to:
`if (!(xml_root.ServiceException.size() > 0 || xml_root.Exception.size() > 0)){`
I suppose at least one is expected in this cases, but there could be more of those elements.

It should solve the #584 issue as well.

Thank you and best regards.
