### ISSUE TITLE
Show conformance class dependencies to users

### ISSUE THREAD

**Issue by MarcoMinghini** [INSPIRE-MIF/helpdesk-validator#6]
When you run a test by selecting a conformance class that has dependencies with other conformance classes (not selected), tests on these are also run. However, the user is not warned of this until the test begins to run.

Thus, the user interface might be changed so that, when selecting a conformance class with the user flip switch, all the dependent conformance classes should be also automatically selected, e.g. greyed out so that they cannot be individually deselected. In addition, a pop-up window could be shown informing the user that there are dependencies and that these will be executed as well.

Sample mockups to accommodate this improvement are shown below:

1) In the "Start test" tab, the mandatory conformance classes could be automatically selected and disabled if some dependant conformance classes are selected.

![imagen](https://user-images.githubusercontent.com/10537778/47079955-fbbe7580-d206-11e8-8e69-147ab7761998.png)

2) Then, in the "Configure Test Run" window, the information contained under the "Test Suites" could be displayed as a tree, with the possibility of selecting and deselecting tests.

![imagen](https://user-images.githubusercontent.com/10537778/47080015-2c9eaa80-d207-11e8-816f-1b0ada004dbb.png)

What are your views, comments and suggestions about this potential improvement?

**Comment by MarieLambois** [comment]
Indeed the dependencies should be automatically selected. I am not really a big fan of the popup idea as it can rapidly be annoying to have popups.

**Comment by thijsbrentjens** [comment]
Regarding point 1: good idea.
Regarding the tree of 2. : I think it's nice to have, but has a low priority.

**Comment by MarcoMinghini** [comment]
[2017.4 meeting 2018-11-15] the improvement proposal is considered to be useful. The first part (change to the UI when selecting conformance classes) is worth to be implemented with a higher priority; instead, the changes to the _Configure Test Run_ window are considered to have a lower priority for implementation.

**Comment by AntoRot** [comment]
I agree too to assign different priorities for the 2 points (higher the first one) of the improvement proposal.

**Comment by MarcoMinghini** [comment]
@MarieLambois @thijsbrentjens @AntoRot the improvement has been included in the cloud staging instance of the Validator: http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/

You can now test it. Any feedback is welcome!

**Comment by AntoRot** [comment]
I tested it and it works properly.

**Comment by alitka** [comment]
I also tested and everything is working properly. If an user click the "Test Suite"-button, the "Selected Test Suites" and "Direct dependencies" are showing up.
