### ISSUE TITLE
v2021.3 - 15/09/2021: non-breaking changes

### ISSUE THREAD

**Issue by ghost** [INSPIRE-MIF/helpdesk-validator#600]
v2021.3 release is scheduled for 15/09/2021 and only includes non-breaking changes, so that any INSPIRE resource passing the test in the previous release automatically passes the same test in this release. This release is the one used for the end-of-year Monitoring process.

Do you use [these](https://github.com/INSPIRE-MIF/helpdesk-validator/tree/master/examples) examples to check if some feature/fix is breaking or non-breaking for metadata conformance classes?

Thanks in advance!

**Comment by fabiovin** [comment]
Dear @DeordD,

thank you for your question.

For testing purposes, we use a set of resources including the MD examples you mentioned.

You can test your metadata in staging, because, according to the [release strategy](https://github.com/INSPIRE-MIF/helpdesk-validator/tree/master/release%20strategy#v20213---15092021), between June and September in staging there are only non-breaking changes.

**Comment by ghost** [comment]
Dear @fabiovin,

I have validated [Dataset](http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/test-run/index.html?id=EIDf1bed320-8e7d-4050-b031-ab653d40ce2a) and [Network Service](http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/test-run/index.html?id=EIDd5a89bc3-85ac-4a7f-8940-5ff7d8e1c8c8) example and both metadata records are valid.

I have asked this question because of the following problems which could lead to "breaking-changes" even though ETS-Rules haven't changed:
- https://github.com/INSPIRE-MIF/helpdesk-validator/issues/515
- https://github.com/INSPIRE-MIF/helpdesk-validator/issues/588
- https://github.com/INSPIRE-MIF/helpdesk-validator/issues/525

It means that sometimes metadata-oriented tests for non-breaking changes aren't fully sufficient because of external dependencies, network problems, validator infrastructure, ...

@fabiovin Do you think that above mentioned issues could be potential "non-ETS"-breaking-changes?

P.S.
I am aware it is really complicated to check those things in the structured way.

**Comment by ghost** [comment]
Hi,

could someone please answer this question?

> @fabiovin Do you think that above mentioned issues could be potential "non-ETS"-breaking-changes? 

Thanks!
