### ISSUE TITLE
md common req C.21 - Dataset Conformity Specifications: Error message contains typographical error 

### ISSUE THREAD

**Issue by ghost** [INSPIRE-MIF/helpdesk-validator#601]
PR https://github.com/inspire-eu-validation/ets-repository/pull/623/commits/6368a43c06da3a3b8a724e77faba8e7a2b22270b introduced typographical error.

Error message contains "corret" instead of "correct":
_XML document '{filename}', record '{id}': The metadata record contains a reference to a specification, but the codeListValue or date type is not **corret**. The codeListValue or date type should be 'publication'._

Following line should be changed (branch v2021.2)
https://github.com/inspire-eu-validation/ets-repository/blob/2c5924693aca3ec3e7af1ce234cd1e6c3039afa1/include-metadata/TranslationTemplateBundle-EID70a263c0-0ad7-42f2-9d4d-0d8a4ca71b52.xml#L495

Report:
https://inspire.ec.europa.eu/validator/test-run/details.html?id=EID6816bf1c-be98-4542-8c10-768c0e0f1260

Screenshot:
![image](https://user-images.githubusercontent.com/38787131/132513530-fe8dc3ae-d907-42e8-a602-d3a9259e4dbe.png)

Example metadata record:
[Dataset_metadata_2.0_example.zip](https://github.com/INSPIRE-MIF/helpdesk-validator/files/7129005/Dataset_metadata_2.0_example.zip)

**Comment by arantzaetxebarria** [comment]
Dear @DeordD 

Thank you for your feedback. We are going to fix this typo, Once it is ready in staging environment we will get back to you.
Regards,
Arantza

**Comment by dperezBM** [comment]
Dear @DeordD 

The ETS has been updated with a fix for this issue on the staging instance. Could you please test again and verify?

Thanks.

**Comment by ghost** [comment]
@dperezBM 

LGTM.

Screenshot:

![image](https://user-images.githubusercontent.com/38787131/133247966-20796505-9913-4258-8c96-636469f91df5.png)

Report:

http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/test-run/details.html?id=EID75d44606-9daf-4ffa-ae7b-8da2e6c792c2
