### ISSUE TITLE
500 - Server Error

### ISSUE THREAD

**Issue by mat-bach** [INSPIRE-MIF/helpdesk-validator#603]
Hello, I have a problem with INSPIRE Reference Validator - Test selection.

- the problem occurs when I'm trying to upload any XML metadata files
- I use Google Chrome and Mozilla Firefox browsers with newest versions
- 
![image](https://user-images.githubusercontent.com/57730095/132861226-ad8914e3-02d3-44b5-ab14-1c7326928375.png)
- I have got no test report because of problem with uploading any file
Thank you in advance

**Comment by MarcoMinghini** [comment]
Dear @proelokox,
are you using the online Validator (production or staging instance) or your own deployment of the Validator?

I have just tested the upload of metadata XML records and run the validation on the public [production instance](https://inspire.ec.europa.eu/validator/) and [staging instance](http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp) without issues.

**Comment by mat-bach** [comment]
Dear @MarcoMinghini 
I have just realized that the problem occurs because of foreign signs in the file name. 
Now everything works perfect. 
Thank you and best regards.
