### ISSUE TITLE
HTTP redirection - 307 Internal Redirect

### ISSUE THREAD

**Issue by otaviosian** [INSPIRE-MIF/helpdesk-validator#604]
Hello all,

I receive validation errors when running the [web validator](https://inspire.ec.europa.eu/validator/) in:
- md datasets-and-series 1.4: INSPIRE Theme Keyword
- md datasets-and-series 1.10: Dataset Conformity
- M.1: Spatial scope keyword
- M.2: Priority datasets keyword

As reported in issue #536 and others, the problem seems to be related with HTTP redirects (307 Internal Redirect).

![image](https://user-images.githubusercontent.com/10657480/133059733-a4bd0658-9be9-4c8c-b8e2-7a7697acd45b.png)

Thank you for your help.

**Comment by fabiovin** [comment]
Dear @otaviosian,

thank you for reporting the issue, we will analyze it.

In the meanwhile, if you need to validate your resources, you can use the [staging instance](http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/home/index.html).

**Comment by otaviosian** [comment]
Dear @fabiovin,

I confirm that the problem has been resolved.

I also thank you for providing an interim solution.
