### ISSUE TITLE
Problem running docker image: 404 Not Found (2021.2 15/06/21)

### ISSUE THREAD

**Issue by dhdeangelis** [INSPIRE-MIF/helpdesk-validator#605]
I run a local docker image for testing purposes. The application seems to run well and the main page for the validator displays fine. However, on choosing either a local or a remote metadata file the validator complains that it cannot connect:

![image](https://user-images.githubusercontent.com/51515911/133061787-0b3f4e3a-e031-4684-b849-a1c1adca30fd.png)

I use the latest version (2021.2 15/06/21) but I get the same problem if I use the previous one (2021.1).

Exploring the problem using the browser's debugging tool a colleague and I found that the application is issuing a post request to the following address:

http://localhost:8090/validator/rest/TestObjects?action=upload

which does not seem to exist in my installation, see here:

![image](https://user-images.githubusercontent.com/51515911/133062453-a8541a88-c755-4e49-b492-79d72ab40b5d.png)

I have already tested to delete and reinstall the image a couple of times and get the same result.

![image](https://user-images.githubusercontent.com/51515911/133063246-485869d7-2539-42a0-8af0-9af0ad02c994.png)

Am I doing something obviously wrong? Is there another problem? Any hint to a possible solution is appreciated.

Thanks in advance

Hernán

**Comment by dhdeangelis** [comment]
As commented in #608 this problem persists in the new version 2021.3 16/09/2021.

**Comment by carlospzurita** [comment]
Dear @dhdeangelis 

Sorry about your problems with the released packages. We double checked the release and uploaded again the Docker package. Please try again, and make sure that you are using a clean installation of the new Docker image, removing any contents from the `~/etf` directory.

**Comment by dhdeangelis** [comment]
Thank you, @carlospzurita , the new image works fine and I can test local metadata and data without problems.

**Comment by arantzaetxebarria** [comment]
Dear @dhdeangelis 
We close this issue.
Please feel free to open a new issue in case you detect any problem.

Regards
