### ISSUE TITLE
Error response from daemon: Get https://ghcr.io/v2/: denied: denied (2021.3 16/09/2021)

### ISSUE THREAD

**Issue by dhdeangelis** [INSPIRE-MIF/helpdesk-validator#608]
In the latest version of the validator (2021.3 16/09/2021) there is a new address for providing GitHub credentials before downloading the new image.

But my credentials are not accepted after the command `docker login ghcr.io`

`Error response from daemon: Get https://ghcr.io/v2/: denied: denied`

Is there any particular requirement beyond a normal GitHub account to be able to get the new version?

Thanks in advance

Hernán

**Comment by dhdeangelis** [comment]
Apparently this step was not necessary, as I was able to download the new image with the failed login using

`docker run --name inspire-validator -d -p 8090:8090 -v ~/etf:/etf ghcr.io/inspire-mif/helpdesk-validator/inspire-validator:2021.3`

Same problem as in #605 persists though.

**Comment by carlospzurita** [comment]
Dear @dhdeangelis 

Github has perform a change on the package repository system. Right now, both `ghcr.io` and `docker.pkg.github.com` are equivalent as stated on the [package page ](https://github.com/INSPIRE-MIF/helpdesk-validator/pkgs/container/helpdesk-validator%2Finspire-validator/7797166) 

>  Heads up! Containers at docker.pkg.github.com have been migrated to the Container registry and can now be accessed via either ghcr.io or docker.pkg.github.com [Learn more ](https://docs.github.com/en/packages/working-with-a-github-packages-registry/migrating-to-the-container-registry-from-the-docker-registry)

However, we are sticking with the former, `ghcr.io`. As you said, they have removed the login step to be able to pull images from the registry, so we are modifying the release notes.

**Comment by fabiovinci** [comment]
Dear @dhdeangelis,

could you please confirm if you solved the issue?

**Comment by dhdeangelis** [comment]
> Dear @dhdeangelis,
> 
> could you please confirm if you solved the issue?

Yes, @fabiovinci the problem was solved long ago. I see that I responded with a thumbs up then, but missed to give clearer feedback.

**Comment by noviljohnson** [comment]
hi
i am using this command docker pull ghcr.io/nlmatics/nlm-ingestor:latest
i am getting this error
Error response from daemon: Get "https://ghcr.io/v2/": EOF

for this " docker login ghcr.io -u username -p gh_pat "   command also i am getting the  same error

**Comment by Sunny012** [comment]
> hi i am using this command docker pull ghcr.io/nlmatics/nlm-ingestor:latest i am getting this error Error response from daemon: Get "https://ghcr.io/v2/": EOF
> 
> for this " docker login ghcr.io -u username -p gh_pat " command also i am getting the same error

HI bro
i also meet this error info, so how did you resolve this issue?
could you kindly share it with me, thanks
