### ISSUE TITLE
New ETS for themes MR, ER, AC-MF and OF don't work

### ISSUE THREAD

**Issue by hogredan** [INSPIRE-MIF/helpdesk-validator#610]
If I select the (new) data themes MR, ER, AC-MF or OF the related Conformance Classes under the Advanced options section are not displayed. 

When I try to start a test against these data themes I get an error message ('An error has occured').

In the staging enviroment it works fine.

Can you please check this?

[X] a description of the steps to reproduce your issue

1. Select the INSPIRE resource you would like to test: Data set
2. Select the data theme(s) relevant to the data set > Annex III > ... (AC-MF) or ... (ER) or ... (MR) or ... (OF)

[X] the browser and version used

Google Chrome Version 93.0.4577.63

[X] a screenshot illustrating the problem

![image](https://user-images.githubusercontent.com/18457212/133985581-c0126215-e3e5-47ef-b99f-71a500e29e16.png)

**Comment by carlospzurita** [comment]
Dear @hogredan 
Thank you very much for raising this issue, we are checking the UI for this error and provide a fix once we have located it.

Kind regards.

**Comment by carlospzurita** [comment]
Dear @hogredan 

We ahave uploaded a fix for this issue on https://inspire.ec.europa.eu/validator/home/index.html. Could you please check if everything is correct?

Kind regards.

**Comment by hogredan** [comment]
Dear @carlospzurita ,

thanks for the fix, now everything works fine.

**Comment by fabiovin** [comment]
Dear @hogredan,

thank you for the test.

**Comment by g-weber** [comment]
Dear @fabiovin Is this patch also included in the actual deployment package for Release Release v2021.3 ?

**Comment by carlospzurita** [comment]
@g-weber  the package is updated with the themes. If there is any issue please let us know
