### ISSUE TITLE
problem with WMS layername at39-getcapabilities-layer-name

### ISSUE THREAD

**Issue by pdorio** [INSPIRE-MIF/helpdesk-validator#611]
The WMS validator fail on the step: at39-getcapabilities-layer-name with the following message:

The following layers do not have a correct name according with the harmonised layer names given in the INSPIRE collection: 'TN.AirTransportNetwork.AirSpaceArea'.

I checked more times the documentation. The layer name **TN.AirTransportNetwork.AirspaceArea**  is correct!

This is the link to my service:
https://demo-geoservices8.civis.bz.it/geoserver/p_bz-Inspire/ows?service=wms&version=1.3.0&request=GetCapabilities

**Comment by hogredan** [comment]
Dear @pdorio,

the layer name registered in the INSPIRE registry is written with a lowercase 's' in 'Airspace'. Thus, the correct layer name would be TN.AirTransportNetwork.Air**s**paceArea. In your capabilities you use TN.AirTransportNetwork.Air**S**paceArea with an uppercase 'S'.

**Comment by pdorio** [comment]
Thank you @hogredan
