### ISSUE TITLE
LC - LandCoverDataSet reports wrong data type

### ISSUE THREAD

**Issue by robblis** [INSPIRE-MIF/helpdesk-validator#612]
Hi Validator Team,

We ran a test for the LC theme using the LandCoverDataSet feature.

We are receiving the following error:
Conformance Class 'Data consistency', General requirements > Temporal consistency > Valid time plausible
validFrom or validTo are missing or nil or
validTo is not before the value of validFrom.
System error in the Executable Test Suite. Please contact a system administrator. Error information:[err:FORG0001] Wrong xs:dateTime format: '2014-05-08' (try e.g. '2000-12-31T23:59:59.999'). 
 (656/153)

However, in the LandCoverVector.xsd, the data type for validFrom and validTo is type 'date' not 'dateTime'. 
Is this an issue with the validator test?

I've attached the xml file used for the test.

Thanks,
Robert

[LC_LandCoverDataset_Sample.zip](https://github.com/INSPIRE-MIF/helpdesk-validator/files/7206761/LC_LandCoverDataset_Sample.zip)

**Comment by dperezBM** [comment]
Dear @robblis,

Thank you for your report. We will update the corresponding ETS section and we will come back to you once is deployed on our staging instance.

Best regards.

**Comment by j-pallas** [comment]
Hi Validator Team,

I'm validating LandUse Data Set and i have  same error in validFrom- validTo  with type date

![image](https://user-images.githubusercontent.com/91185639/139255931-cda813f4-5e8e-464d-918f-fa859dbebe7c.png)

Thanks,
Jordi

**Comment by dperezBM** [comment]
Dear @robblis, @j-pallas,

We just updated our [staging instance](http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/home/index.html), which contains the modification to fix this issue. Could you please try to validate your data here and provide us feedback?

Thank you and best regards.

**Comment by robblis** [comment]
Hi @dperezBM,

We ran a new test, and the test succeeded. 

Thank you for the fix.

Robert

**Comment by j-pallas** [comment]
Dear @dperezBM 

I execute the validator, but I have the same error  (https://github.com/INSPIRE-MIF/helpdesk-validator/issues/612#issuecomment-953802065) " [err:FORG0001] Wrong xs:dateTime format: '2021-01-01' (try e.g. '2000-12-31T23:59:59.999'). (660/153)"  in Conformance Class 'Data consistency', General requirements > Temporal consistency > Valid time plausible.

I try to change the format type, instead of date to datetime like the example, in this case I return another error "cvc-datatype-valid.1.2.1: '2021-12-31T23:59:59.999' is not a valid value for 'date'."  in Conformance class: INSPIRE GML application schema -> Schema validation -> validate XML documents.
![image](https://user-images.githubusercontent.com/91185639/139324093-ec22d737-ecbe-420b-8c0f-ccd1a5769bc2.png)

I think that exist an incompatible test in the validator for the "validFrom - validTo" dates..

**Comment by dperezBM** [comment]
Dear @j-pallas,

Sorry to hear that. Could you please share with us the metadata that you are testing to have a closer look at what is happening in this case?

Thank you and best regards.

**Comment by j-pallas** [comment]
@dperezBM 
I share a test GML with a data set of Planned Land Use
[luPlanned-selva-etrs89-geo.zip](https://github.com/INSPIRE-MIF/helpdesk-validator/files/7439374/luPlanned-selva-etrs89-geo.zip)

Thanks,
Jordi

**Comment by dperezBM** [comment]
Dear @j-pallas,

Thank you for your metadata. We will analyze it and come back to you with any progress.

Best regards.

**Comment by arantzaetxebarria** [comment]
Dear @j-pallas,

We have updated a fix on the [staging](http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/home/index.html) instance. Could you please test again and verify?

Thanks,
Arantza

**Comment by j-pallas** [comment]
Dear  @arantzaetxebarria 

I run the test successfully.

Thanks for all

Jordi

**Comment by robblis** [comment]
Hi @arantzaetxebarria ,

We re-ran the test again and we see the issue resolved from the test report.

However, the test ends with an INTERNAL_ERROR Status displayed.

<html>
<body>


Started |   | 8:34 AM - 10.11.2021
-- | -- | --
Status |   | INTERNAL_ERROR
Test object |   | http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/validator/v2/TestRuns/EID72d295af-ee30-428f-844c-002f7ea119bc.xml


</body>
</html>

Thanks for the fix,
Robert

**Comment by arantzaetxebarria** [comment]
Dear @robblis 

We have tested your service again in the staging environment and it seems that now the error is not displayed. http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/test-run/details.html?id=EID1a799602-ef33-49bc-a3f2-2a03611feb25

If this error occurs again, do not hesitate to open a new ticket with this new topic. For the moment, we will mark this issue as solved.

Best regards,

Arantza
