### ISSUE TITLE
No layer names defined for some TN feature types

### ISSUE THREAD

**Issue by JohannaOtt** [INSPIRE-MIF/helpdesk-validator#613]
The list of required styles in chapter 11.1 of the TN data specification does not contain layer names for all feature types that can occur in TN data.
There are for example no layers defined for tn-ra:RailwayStationNode, tn-w:Buoy, tn-w:TrafficSeparationSchemeCrossing, tn-w:TrafficSeparationSchemeSeparator, tn-w: Beacon, tn:MarkerPost  (not exhaustive)

As it has a positive outcome for the usability of the WMS, we thought it would make sense to follow the pattern from the data specification using "TN.WaterTransportNetwork.Buoy", "TN.WaterTransportNetwork.TrafficSeparationSchemeCrossing" etc. but that is failling in the validator.

What is the expected way to handle such feature types for which neither a required nor a recommended style exists in the data specifications? Should they just not be displayed in the WMS? Or can everyone come up with their own layer names for them? (If the latter is the case - why is it failing in the validator?)

**Comment by fabiovin** [comment]
Dear @JohannaOtt,

the related change proposal for the View Service TG was discussed and approved in the MIG-T meeting yesterday.

See related issue https://github.com/INSPIRE-MIF/technical-guidelines/issues/2.

A temporary solution was implemented in the staging some time ago (see comment https://github.com/INSPIRE-MIF/helpdesk-validator/issues/39#issuecomment-789260465), so we need to better verify if it is the right one according to the TG change approved yesterday.

In the meanwhile, you can test your WMS in staging.

**Comment by JohannaOtt** [comment]
@fabiovin Thank you for the input. I checked in the staging instance and there is no error on the layer name occurring any longer.

For the sake of completeness, I would like to emphasize that our data is harmonised INSPIRE TN data and I would therefore not consider it falling under the new "as-is" rule described in https://github.com/INSPIRE-MIF/technical-guidelines/issues/2#issuecomment-918047627 
Not sure if it would be expected that harmonised data is handled different than as-is data.

**Comment by fabiovinci** [comment]
Dear @JohannaOtt,

the change proposals to the WMS TG have been released in the [2022.2 TG release](https://github.com/INSPIRE-MIF/technical-guidelines/releases/tag/2022.2).

The related changes have been introduced in the ATSs (see [Abstract Test Suite: INSPIRE View Services Technical Guidance](https://github.com/inspire-eu-validation/view-service/tree/3.2.0)) and they will be implemented in the next release of the Validator.

**Comment by fabiovinci** [comment]
Dear @JohannaOtt,

the solution is available in the staging instance and it will be included in the next release.

**Comment by JohannaOtt** [comment]
I validated this [WMS](https://haleconnect.com/ows/services/org.1136.edcd14f8-69e8-4809-80ab-2fff814a4d46_wms?SERVICE=WMS&REQUEST=GetCapabilities&VERSION=1.3.0) containing some of the layers mentioned in the description on the staging instace and did not run into any validation errors concerning layer names.
So the issue could be closed from my point of view.
