### ISSUE TITLE
Maximum size of the uploaded file is 1 MB only instead of 50 MB allowed up to now

### ISSUE THREAD

**Issue by fantamir** [INSPIRE-MIF/helpdesk-validator#614]
Maximum size of the file which can be currerntly uploaded on INSPIRE validator for testing is 1 MB only, instead of 50MB. Files larger than 1MB are not loaded - error mesage "An error has occured uploading file (Code: 413 - Request Entity Too Large)" appears instead.
Compare loading of two attached GML files.
Please remove this limitation or modify the information "Maximum size is 50 MB" available above the "Choose files" button accordingly at least.

Development version of the validator available at http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/home/index.html allows upload of the large files without any problems (30 MB GML file tested)

[FileSizeMoreThan1MB_UploadTest.zip](https://github.com/INSPIRE-MIF/helpdesk-validator/files/7210895/FileSizeMoreThan1MB_UploadTest.zip)

Best wishes
Miroslav Fanta
CENIA

**Comment by carlospzurita** [comment]
Dear @fantamir 

We have updated the limit on the validator. Please let us know if you still have issues uploading your file.

**Comment by fantamir** [comment]
Dear colleagues,

Thank you for prompt correction. 30 MB file uploaded ant tested without any problems.
