### ISSUE TITLE
Missing ETS in 2021.3 repository zip

### ISSUE THREAD

**Issue by hwbllmnn** [INSPIRE-MIF/helpdesk-validator#615]
It seems the 2021.3 repository release zip is missing the new ETS. When I start up the validator with the repository zip already unpacked, it seems the validator downloads some of the missing ETS but not all, and it is unclear to me how that works. The missing ETS seem not to be merged into the `master` branch of the repository git repo. Shouldn't all the ETS be contained in the repository zip? How does the download mechanism work?

Ideally I'd like to be able to deliver a fully functional validator using the release files.

BTW: the `ETF_DL_TESTPROJECTS_OVERWRITE_EXISTING` env variable from the `Dockerfile` is set to `false`, so I wouldn't even expect any downloads happening (or at least not any modification of my existing project dir).

**Comment by carlospzurita** [comment]
Dear @hwbllmnn 

Thank you for raising this issue, we are re-checking the packages for the release.

About the usage of the env variable, we will take a look on the Dockerfile and check if it is being used correctly.

**Comment by carlospzurita** [comment]
Dear  @hwbllmnn 

We have updated the contents of the [release](https://github.com/INSPIRE-MIF/helpdesk-validator/releases/tag/v2021.3) again with the ETS on the `v2021.3` branch. Could you please check again and tell us if the issue is still present?

Kind regards.

**Comment by hwbllmnn** [comment]
Hi @carlospzurita 

thanks for the quick reply!  However, I think three classes are still missing from the package:
* INSPIRE data  theme - Soil (3.0)
* INSPIRE data theme - Statistical Units Grid (3.0)
* INSPIRE data theme - Statistical Units Vector (3.0)

Thanks

**Comment by g-weber** [comment]
@carlospzurita: Please consider also fix https://github.com/INSPIRE-MIF/helpdesk-validator/issues/610

**Comment by carlospzurita** [comment]
Dear @hwbllmnn 

We have updated again the packages for the release and included the missing Conformance Classes. Please check again if the issue is corrected.

Dear @g-weber 

Issue #610 was already fixed and published as a hotfix. Please, if there is still any issues there, let us know.

**Comment by dperezBM** [comment]
Dear @hwbllmnn,

Could you please provide us feedback if this solution was valid for what you were expecting? 

Thank you and best regards.

**Comment by hwbllmnn** [comment]
Hi @dperezBM,

yes, all expected conformance classes are contained in the latest release.

Thanks!

**Comment by dperezBM** [comment]
Dear @hwbllmnn,

Glad to hear that! We will mark the issue as solved then.

Best regards.

**Comment by hwbllmnn** [comment]
Closing this as this is solved, thanks!
