### ISSUE TITLE
Links referring to the coordinate reference systems requested by INSPIRE Technical Guidance requirements are not valid anymore

### ISSUE THREAD

**Issue by fantamir** [INSPIRE-MIF/helpdesk-validator#617]
Since Friday 24th of September, links referring to the coordinate reference systems used by INSPIRE, e.g. 
o	http://www.opengis.net/def/crs/EPSG/0/4936
o	http://www.opengis.net/def/crs/EPSG/0/4937
o	http://www.opengis.net/def/crs/EPSG/0/4258
etc.
are not valid anymore. The message "503 Service Temporarily Unavailable" appears instead. 
For that reason, harmonised GML files containing such URL (e.g. http://www.opengis.net/def/crs/EPSG/0/4258) are "rejected" by INSPIRE validator.

In our opinion, the "0" character used in the URL could be a placeholder used for the redirection of the URL to the latest version of the specification of given coordinate referernce system (e.g. the URL http://www.opengis.net/def/crs/EPSG/8.5/4258 works well).

Could you please check the situation concerning the validity of the links referring to the coordinate reference systems requested by INSPIRE and modify the appropriate Technical Guidance requirements and / or INSPIRE validator, if necessary?

Thank you

Miroslav Fanta
CENIA, Czech Environmental Information Agency

**Comment by fabiovin** [comment]
Dear @fantamir,

it seems the links of the coordinate reference systems used in INSPIRE work fine.

We will monitor them to verify if the error will appear again.

I'm closing the issue, if the problem persists please reopen it.

Thanks
