### ISSUE TITLE
Example Data set for Planned Land Use wanted

### ISSUE THREAD

**Issue by sylviaobk** [INSPIRE-MIF/helpdesk-validator#619]
Hello,

I would like to test a Data set for Planned Land Use. I am still at the very beginning.
![image](https://user-images.githubusercontent.com/20552367/135399430-b3023bf9-5c55-49b3-b98a-6b4db5c3adae.png)
![image](https://user-images.githubusercontent.com/20552367/135399458-d9d745e4-d944-4256-b982-1b11345432ec.png)

Does anybody have a gml-file which passes this test? A file I could use to upload in this test?
I would like to see an interoperable data schema which is ok. With  uml diagram only I cannot deal.

Thanks in advance!

**Comment by Kate-Lyndegaard** [comment]
Hi,

You can download example planned land use datasets via WFS in the INSPIRE Geoportal Thematic Viewer (Land Use): https://inspire-geoportal.ec.europa.eu/overview.html?view=themeOverview&theme=lu

Germany has a large number of good examples available.

Kind regards,
Kate

**Comment by sylviaobk** [comment]
Hi Kate,
thank you for your help. I get many thousand results. I tried to download some, but did not get a usable download. How can I filter for data set conformity is true? Do you know a specific data set?

**Comment by Kate-Lyndegaard** [comment]
Hi,

Here is an example of a valid INSPIRE-compliant PLU dataset from Germany: 

[03b94b4b-6069-4167-aec7-45e645620171_4258.zip](https://github.com/INSPIRE-MIF/helpdesk-validator/files/7260422/03b94b4b-6069-4167-aec7-45e645620171_4258.zip)

Please be aware that the feature types in the dataset depend on the available source data used in the harmonization project.

If you run it through the validator you may hit the CRS issue that has been recently reported, however should be valid: https://github.com/INSPIRE-MIF/helpdesk-validator/issues/617 


Kind regards,
Kate

**Comment by sylviaobk** [comment]
Hi, I tested your gml - file and get this:
![image](https://user-images.githubusercontent.com/20552367/135482406-cf8cb7e0-9264-4a50-b7bd-7c4fbabbeef8.png)
Did you configure the test like me?

**Comment by sylviaobk** [comment]
Oh, sorry, it was the crs - thing that made the test fail...
Thank you very much, you helped me a lot!
