### ISSUE TITLE
Many NullPointerExceptions when validating WFS on staging instance.

### ISSUE THREAD

**Issue by JohannaOtt** [INSPIRE-MIF/helpdesk-validator#622]
When validating [this WFS](https://transformiraj.nipp.hr/ows/services/org.4.a80b3d00-c60d-4c3c-b677-6216a286469a_wfs?SERVICE=WFS&REQUEST=GetCapabilities&VERSION=2.0.0) on the staging instance, there are a lot of [NullPointerExceptions](http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/test-run/details.html?id=EIDbb8b376e-f69d-4d0b-9434-7423fa4ed51b) in the OGC conformance class.

I already validated other WFSs before and did not run into this issue. Is there anything wrong with the WFS that causes these error messages or is that an issue in the validator or its connection to the OGC validator?

**Comment by dperezBM** [comment]
Dear @JohannaOtt , 

Thank you for your message. We have tested your service directly against [OGC Validator](https://cite.opengeospatial.org/teamengine) and the results are the same that we have with the validator. 


![pastedImage (1)](https://user-images.githubusercontent.com/33548409/136374776-f9af9f40-72d0-468b-b57c-cd6db1a14b70.png)

Maybe you could report this issue directly to the [OGC GitHub repository](https://github.com/opengeospatial/teamengine/issues). 

Best regards.

**Comment by JohannaOtt** [comment]
I created https://github.com/opengeospatial/teamengine/issues/481 for it

**Comment by fabiovinci** [comment]
Dear @JohannaOtt, 

the issue you opened in the OGC repository seems solved, did you test the solution?

Can we close this issue? Thanks.

**Comment by JohannaOtt** [comment]
@fabiovinci Not yet - tried right now but this is not possible due to [this issue](https://github.com/opengeospatial/ets-wfs20/issues/225)
Will test again once that is sovled.

**Comment by fabiovinci** [comment]
Dear @JohannaOtt,
it seems that the relevant OGC issues were closed, so I will close this issue.
Please reopen it if the error persists.

**Comment by JohannaOtt** [comment]
As the respective resource is not available any longer, I cannot check this, but would open a new issue in case I run into it again.
