### ISSUE TITLE
Reference validator not found (404)

### ISSUE THREAD

**Issue by ghost** [INSPIRE-MIF/helpdesk-validator#623]
When starting from the [Validator Homepage](https://inspire.ec.europa.eu/validator/home/index.html) and clicking on the [Test your data, services or metadata](https://inspire.ec.europa.eu/validator/test-selection/index.html) link, you get a 404 not found error.

Info: The link to the stating and beta instance from the menu works.

**Comment by carlospzurita** [comment]
Dear @bhoefling-c2c , as notified on #621, the reference validator service is down for the hotfix release.

**Comment by ghost** [comment]
@carlospzurita: Thanks, so I fell just in this maintenance time slot. A notice on the home page would be nice :-)
