### ISSUE TITLE
Link to helpdesk is outdated

### ISSUE THREAD

**Issue by ghost** [INSPIRE-MIF/helpdesk-validator#624]
The link from the [Validator Homepage](https://inspire.ec.europa.eu/validator/home/index.html) for issues is outdated.

Current link: https://github.com/inspire-eu-validation/community/issues
But it tell you to go here: https://github.com/INSPIRE-MIF/helpdesk-validator

**Comment by MarcoMinghini** [comment]
Dear @bhoefling-c2c,
the current link is correct. Please note that, since about one year, we migrated the helpdesk to https://github.com/INSPIRE-MIF/helpdesk-validator and the old space was dismissed.

**Comment by ghost** [comment]
@MarcoMinghini: Exactly. But the link on the homepage is still the *OLD* one (i.e. inspire-eu-validation). You get redirected to the pull request page and get lost. You need to find yourself the way to the new (helpdesk-validator) issue page.

**Comment by carlospzurita** [comment]
Dear @bhoefling-c2c 

Yes, you are right, the link on the homepage presentation paragraph is still pointing to the old URL. We will modify the validator UI and make the change available.

Kind regards.

**Comment by carlospzurita** [comment]
Dear @bhoefling-c2c 

We have modified the link on the [staging instance](http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/home/index.html). Please let us know if everything is okay.

Kind regards.

**Comment by ghost** [comment]
LGTM,

Thanks for fixing.
