### ISSUE TITLE
Testing Geology data: Error because of missing geophObjectMember & geophObjectSet 

### ISSUE THREAD

**Issue by gdi-by** [INSPIRE-MIF/helpdesk-validator#625]
I was testing a GML with Geology data with test suite Annex II - Geology (GE) and received errors on test "ge-ia.b.2: geophObjectSet" and "ge-ia.b.3: geophObjectMember". The error messages are:
"The property 'geophObjectSet' shall be provided."
"The property 'geophObjectMember' shall be provided."
According to the scheme (https://inspire.ec.europa.eu/schemas/ge-core/4.0/GeologyCore.xsd), both properties are optional.
I have attached the test result.
Is this a bug in the validator?

Thanks for your help.
Robin Küspert

[Test run on 10 15 - 04.10.2021 with test suite Annex II - Geology (GE).zip](https://github.com/INSPIRE-MIF/helpdesk-validator/files/7276798/Test.run.on.10.15.-.04.10.2021.with.test.suite.Annex.II.-.Geology.GE.zip)

**Comment by fabiovin** [comment]
The change for the TG was approved.

I updated the related ATS accordingly, so we will update the ETS and notify you when the change is available.

**Comment by arantzaetxebarria** [comment]
Dear @gdi-by 

The fix for the issue has been solved and now it is in [staging](http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/home/index.html) environment. Could you please verify? Thanks

Regards

**Comment by gdi-by** [comment]
Hello arantzaetxebarria,
i tried to test my test data, but i get an error when in want to upload it:
![grafik](https://user-images.githubusercontent.com/13452857/152761175-247fe6c9-9b63-4310-8e92-d209f8e6fdbb.png)
I have attached my data.

Kind Regards
Robin

[geol_wfs_GeoColl-MapFeat-GeolUn-GeolEv.zip](https://github.com/INSPIRE-MIF/helpdesk-validator/files/8013956/geol_wfs_GeoColl-MapFeat-GeolUn-GeolEv.zip)

**Comment by arantzaetxebarria** [comment]
Dear @gdi-by 

Yes, we have an issue in the staging environment related to the size of the files, as soon as we fix it, we will contact you to test again your issue. Sorry for the inconvenience.

Regards,

Arantza

**Comment by fabiovinci** [comment]
Dear @gdi-by,

while waiting for the file size error to be resolved, you can use the zip file as its size is less than 1 MB.

I used it and it works: http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/test-run/details.html?id=EID201cd09e-7718-46fb-853f-0b926ef9df1b 
It seems there is an error in reading the schema declared in the schemaLocation attribute, so I tried to substitute it with the INSPIRE official one:

`xsi:schemaLocation="http://www.opengis.net/wfs/2.0 http://schemas.opengis.net/wfs/2.0/wfs.xsd http://inspire.ec.europa.eu/schemas/ge-core/4.0 https://inspire.ec.europa.eu/schemas/ge-core/4.0/GeologyCore.xsd"`

and the schema validation error is no longer present.
See the relevant report: http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/test-run/details.html?id=EID357e4de0-87b0-44dc-a40a-1159c567bab4

**Comment by fabiovinci** [comment]
Dear @arantzaetxebarria,
this specific issue should be "solved", in any case, let's wait for feedback from @gdi-by.

The issue related to the file size limit in staging is already present, #697, so I'm updating this issue label accordingly.

**Comment by arantzaetxebarria** [comment]
Dear @gdi-by 

The issue related to the size limit has been solved in the staging environment, so it is possible to test the solution developed for this issue. Could you please verify and give us your feedback? 
Also to comment that a new release is coming in the next few days, so I would appreciate a confirmation before the release. Thanks.

Regards,
Arantza

**Comment by gdi-by** [comment]
Dear Arantza,
sorry for the late response. I no longer get the errors regarding "geophObjectSet" and "geophObjectMember", so I can confirm the solution works.
Thank you very much!
Kind regards,
Robin
