### ISSUE TITLE
Wrong style name expected for Building

### ISSUE THREAD

**Issue by JohannaOtt** [INSPIRE-MIF/helpdesk-validator#626]
When validating a WMS for BU data in the validator and using the style name "BU.Building.default" that is expected according to the Data Specification
![grafik](https://user-images.githubusercontent.com/34163838/135821740-705f81f5-8ec0-404c-b598-98a4315f5cec.png)
the validator returns an error 
![grafik](https://user-images.githubusercontent.com/34163838/135821783-544e16f8-c032-4035-b876-7216a1eef9b4.png)

The validator [is exepecting the value "BU.Building.**D**efault"](https://github.com/inspire-eu-validation/ets-repository/blob/28b66265aab8fc8228672283887475818aade1ab/service/vs-wms-soapui-project.xml#L2330).

This should be changed according to the requirement in the Data Specification (or the Data Specification needs to be adapted).

**Comment by dperezBM** [comment]
Dear @JohannaOtt,

Thank you for your report. We will add the corresponding style name and we will come back to you once is uploaded to our [staging instance](http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/home/index.html).

Best regards.
David

**Comment by fabiovin** [comment]
Dear all,

it seems to be a typo in the TG since all other "Style Name" values use "**D**efault" with the initial capital letter.

So, I would suggest leaving both values in the ETS, for the moment, and opening an issue in the [technical-guidelines repository](https://github.com/INSPIRE-MIF/technical-guidelines/issues).

**Comment by JohannaOtt** [comment]
> So, I would suggest leaving both values in the ETS

Ok for me.


> opening an issue in the technical-guidelines repository.

I created [this issue](https://github.com/INSPIRE-MIF/technical-guidelines/issues/13).

**Comment by dperezBM** [comment]
Dear @JohannaOtt 

The ETS has been updated with a fix for this issue on the [staging instance](http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/home/index.html). Could you please test again and verify?

Thanks.

**Comment by JohannaOtt** [comment]
@dperezBM I tried to test it but the staging instance is running into an error when trying to validate the WMS: 
![grafik](https://user-images.githubusercontent.com/34163838/137293638-49e6028a-965d-4277-ac16-2e18fa613c39.png)

**Comment by dperezBM** [comment]
Dear @JohannaOtt,

Sorry to hear that. We tested a WMS service today and we were not able to reproduce the issue that you mentioned above. Could you please test the WMS service again? If the error persists, could you please share with us the resource that you are using?

Thank you and best regards.

**Comment by JohannaOtt** [comment]
@dperezBM I can still reproduce the issue with [this service](https://test.haleconnect.de/ows/services/org.8.a80e67ec-912d-4c1e-a6d0-4a846abe07ca_wms?SERVICE=WMS&REQUEST=GetCapabilities&VERSION=1.3.0) using BU.Building.default.
I also tested with one other service (using BU.Building.Default) and could not reproduce it. Not sure if this can be caused by the style name, but it is the only difference between the services I am aware of.

**Comment by dperezBM** [comment]
Dear @JohannaOtt,

We have been testing the service that you provided. We reached an error from the ETF which indicates that the Title 'asd' has a 3 character length, and is expecting at least 4 characters length. This is the full message: 
- cvc-minLength-valid: Value 'asd' with length = '3' is not facet-valid with respect to minLength '4' for type '#AnonType_label'.

We are looking for the origin of this message. In the meantime, could you please update the title and test the service?

Thank you and best regards.

**Comment by JohannaOtt** [comment]
@dperezBM I can confirm that the validation is running and is not throwing an error concerning the style name any longer when changing the title.
Would be great if the error message (if it turns out that this really is an error) would be displayed to users as well so that one can adapt the service accordingly.
This issue can be closed from my point of view.

**Comment by dperezBM** [comment]
Dear @JohannaOtt ,

Thank you for your feedback. We will mark the issue as solved, but we will keep it open until the release, then we will close it. Also, we appreciate the enhancement that you propose to us. We will discuss it internally and check if it is possible to be more specific with the error message.

Thank you and best regards.
