### ISSUE TITLE
mistake - validation message

### ISSUE THREAD

**Issue by bfrichet3** [INSPIRE-MIF/helpdesk-validator#631]
Dear,

I am a member of the belgian federal metadata pool. I recieved this validation report from another adminsitration (see attachment).

There is a problem with the way the validator raported and explained the mistake concerning the "data encoding" element. As you may read, it is clerarly written that "The record must have an identificationInfo element.". This is quite unexpected and totally useless in order to identify the problem because the issue concerns a tag included in the distributionInfo element and not in the identificationInfo element. The message is not relevant in that case and should be changed (actually there was an empty gmd:distributionFormat tag which was responsible for that issue).

Could you fix that bug?

Moreover, I would really express that noone but a full time expert can use the reports because their
[valdiation.zip](https://github.com/INSPIRE-MIF/helpdesk-validator/files/7321614/valdiation.zip)
 explanations are so convoluted that they are quite useless for anyone who has not been fully involved in TG 2.0 conformity for several monthes. I would deeply suggest to make that validator messages more understanble for any people.

Regards,

Benoît Fricheteau

**Comment by carlospzurita** [comment]
Dear @bfrichet3 

We will review the ETS and ATS to check the correct paths for this elements and analyze what is the fix for this issue.

Thank you for raising awareness on the topic of more clear explanations. We are going to leave this issue open for discussion for anyone to share the feedback, and we will have an internal discussion on this topic for possible enhancements.

Kind regards

**Comment by MarcoMinghini** [comment]
Dear @bfrichet3,
thanks for opening an issue in the Validator helpdesk. To allow our team to fully understand and address the issues, we invite you to:

* open 2 new issues, one for each problem you experienced. This is the reason why we will now close the issue.

* to make each of the two issues fully reproducible for our team, when opening the issues, please follow the issue template(s) that we defined at https://github.com/INSPIRE-MIF/helpdesk-validator/issues/new/choose. In particular, please attach the resource you validated and point us exactly to the problem you see in the test report.

* regarding the second issue, I am afraid that your message in the current form is not helpful. We invite you to please explain which error message(s) are not clear, and why. Please note that the error messages should be useful for data providers to identify and fix errors (in this case, on metadata), therefore they assume the readers are familiar with the TG specifications.

**Comment by bfrichet3** [comment]
Dear @MarcoMinghini ,

As far as I read my post, I attached the HMTL file getted by the validation process and I pointed to the mistake (in "data encoding" section). I also explained why it is not consistent. I don't know how I could be more understandable. I am afraid that I cannot upload the then-validated ressource because I corrected it and the XML problem is now fixed.

Regards,

**Comment by bfrichet3** [comment]
This is the URI of the identified XML problem (with an unexpected and irrelevant comment in the uploaded HTML file): https://github.com/inspire-eu-validation/metadata/blob/2.0/isdss/data-encoding.md
