### ISSUE TITLE
mistake - TG 2.0

### ISSUE THREAD

**Issue by bfrichet3** [INSPIRE-MIF/helpdesk-validator#632]
Dear,

I noticed a content mistake in the metadata TG 2.0.  At page 44,  in the data quality section info (concerning dataquality of the INSPIRE datasets) the footnote clearly states thaht one should use codeListValue "service" which is a mistake. One should use "dataset" instead.

I don't know if you have an internal mistake registry concerning TG 2.0 but I reported that problem for an eventual 2.01 version.

Regards,

**Comment by carlospzurita** [comment]
Dear @bfrichet3 

Thank you for bringing attention to this issue. We will check the values available in the INSPIRE registry, and what is checked in the ETS.

Kind regards.

**Comment by bfrichet3** [comment]
Dear @carlospzurita ,

I think values with the registry are ok and I assume that ETS perfectly works. This is more a mistake in the pdf than a functional bug.

Regards,

**Comment by MarcoMinghini** [comment]
Dear @bfrichet3,
please note that there is a separate repository to request change proposals to the TG documents: https://github.com/INSPIRE-MIF/technical-guidelines. In my understanding, this issue is not relevant to the Validator and should be instead opened in the TG repository, providing the information requested in the issue template.

**Comment by fabiovin** [comment]
Dear @bfrichet3,

thank you for reporting the error, it is a typo, the right values ("dataset" or "series") are contained in the requirement.

The typo does not affect the related test in the validator.

In any case, it was already approved the removal of all footnotes which include reference to specific codelists (see the related issue (https://github.com/INSPIRE-MIF/technical-guidelines/issues/8).

**Comment by bfrichet3** [comment]
Dear @MarcoMinghini ,

Thank you for your quick answer. I was looking for such a repository but I didi'nt find it, that's w  why I added it here but I agree it was not the best place.

Regards,
