### ISSUE TITLE
metadata validator 2b- wrong message

### ISSUE THREAD

**Issue by bfrichet3** [INSPIRE-MIF/helpdesk-validator#633]
Dear,

I am a member of the belgian federal metadata pool. I recieved this validation report from another adminsitration (see attachment).

There is a problem with the way the validator raported and explained the mistake concerning the "data encoding" test (https://github.com/inspire-eu-validation/metadata/blob/2.0/isdss/data-encoding.md). As you may read in the attachment, it is clerarly written that "The record must have an identificationInfo element."

That message is quite unexpected and totally useless in order to identify the problem because the issue concerns a tag included in the distributionInfo element and not in the identificationInfo element. The message is not relevant in that case and should be changed (actually there was an empty gmd:distributionFormat tag which was responsible for that issue).

I cannot provide a copy of the tested XML as it has been corrected.

Could you fix that bug?

![image](https://user-images.githubusercontent.com/80756452/136821661-2aaf2efc-459c-4108-b137-3a9eeede415f.png)
[valdiation.zip](https://github.com/INSPIRE-MIF/helpdesk-validator/files/7323870/valdiation.zip)

**Comment by fabiovin** [comment]
Dear @bfrichet3,

thank you for reporting the error.

@carlospzurita, could you please substitute the current error message "_The record must have an identificationInfo element_." with the new one:  "_**The record must have a gmd:distributionFormat/gmd:MD_Format element containing the mandatory child elements gmd:name and gmd:version**_"

**Comment by dperezBM** [comment]
Dear @bfrichet3,

We deployed a correction on our [staging instance](http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/home/index.html). Could you please check if this is valid for you?

Thank you and best regards.
David.

**Comment by bfrichet3** [comment]
Dear @dperezBM,

I cannot check anything as the record was corrected long time ago. I suggest you to validate a corrupt record.

Regards,

**Comment by dperezBM** [comment]
Dear @bfrichet3,

Is this new error message correct for you?

![image](https://user-images.githubusercontent.com/33548409/138447639-d09f5389-c217-405a-acfb-f9664e3c4c25.png)

http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/test-run/details.html?id=EID5a363add-725d-4b5f-9579-0f634237fbc8

Best regards.

**Comment by bfrichet3** [comment]
If it's good enough for you, it's good enough for me

**Comment by fabiovin** [comment]
Dear all,

the fix is ok, we can add it to the next release.
