### ISSUE TITLE
Wrong implementation of timeout performance requirement Get Spatial Dataset operation

### ISSUE THREAD

**Issue by arbakker** [INSPIRE-MIF/helpdesk-validator#635]
**Summary:** wrong implementation of timeout performance (response time of initial response) requirement in validation rule for conformance class _Pre-defined Atom_.

- Conformance class: Pre-defined Atom
- Test report: see [Test run on 12 27 - 12.10.2021 with test suite Conformance Class Pre-defined Atom - PDOK.zip](https://github.com/INSPIRE-MIF/helpdesk-validator/files/7331139/Test.run.on.12.27.-.12.10.2021.with.test.suite.Conformance.Class.Pre-defined.Atom.-.PDOK.zip)
- Browser and version: not relevant, issue regarding implementation validation rules.

# Description

While validating the Conformance class: Pre-defined Atom with the following resource: https://service.pdok.nl/hwh/hydrografie/atom/v1_0/index.xml (note we added a XSLT stylesheet to render the ATOM feeds as HTML when viewed in browsers), I ran into the following validation error:

![timeout-error](https://user-images.githubusercontent.com/3216462/136980558-aceed086-39bf-4e8c-9dfc-ec477f344b23.png)

We have seen this validation error occur for for multiple of our services.

Upon investigation I concluded this is caused by the duration of the download of the dataset (https://service.pdok.nl/hwh/hydrografie/atom/v1_0/downloads/hydrografie.zip - 600 MB). This download takes on average about 2 minutes, which is longer than the _30 seconds timeout_ validation rule allows for. So it seems the validation rule is not really testing for _response time of the initial response_ but rather for the full HTTP request to complete. I conclude this based on request analytics made by my browser dev tools networking tab, time to the initial response is about 57 milliseconds:

![issue-timeout-atom](https://user-images.githubusercontent.com/3216462/136980604-6f6c577d-94b8-46bf-a75b-9341b9d1c73b.png)

So I looked at the [Technical Guidance for the implementation of INSPIRE Download Services](https://inspire.ec.europa.eu/documents/Network_Services/Technical_Guidance_Download_Services_v3.1.pdf) and section **8.2.1 Implementation requirements mandated by the Implementing Rule states**:

> For  the  Get  Spatial  Data  Set  operation  and  for  the  Get  Spatial  Object  operation,  and  for  a query consisting exclusively of a bounding box, the response time for sending the initial response shall be maximum 30 seconds in normal situation then,  and still in normal situation, the download service shall  maintain  a  sustained  response  greater  than  0,5  Megabytes  per  second  or  greater  than  500 Spatial Objects per second. 

The following image from the Technical guidance illustrates what is actually meant by _response time for sending the initial response_ (could not find a clearcut definition in the TG though) from TG Download Service section **8.1 General Requirements**:

![t-first](https://user-images.githubusercontent.com/3216462/136980644-ecddef14-bf4e-4b34-bfa3-069445ffd830.png)

So concluding I think that the current implementation of the validation rule _30 seconds timeout_ is incorrect and should be changed so it will actually test for the _response time for sending the initial response_[^1], instead of testing for the time it takes for the complete HTTP request to complete. 

[^1]: The time it takes for the service to send the first byte of the response

**Comment by dperezBM** [comment]
Dear @arbakker,

Thank you for your message. We will analyze your proposal and we will come back to you with more information when a decision is done. 

Best regards.

**Comment by dperezBM** [comment]
Dear @arbakker, 

We are currently working on this issue. We are testing which repercussion will have onto the test functionality if we set the calls directed to a '.zip' extension as HEAD instead of GET. We will come back to you when we collect more information.

Best regards.

**Comment by dperezBM** [comment]
Dear @arbakker,

We have been analysing this issue and unfortunately, this issue looks directly related to the SoapUI itself.

Currently, we changed the request method for 'Get Spatial Dataset' from 'GET' to 'HEAD' to check the response times for the URL without downloading the resource and avoiding the timeout exception. 

The test-run work as expected. The problem is while validating your ATOM, [this queried URL](https://www.nationaalgeoregister.nl/geonetwork/opensearch/dut/download?spatial_dataset_identifier_namespace=http://www.pdok.nl&spatial_dataset_identifier_code=07575774-57a1-4419-bab4-6c88fdeb02b2&crs=https://www.opengis.net/def/crs/EPSG/0/4258&language=nl) is generated, which returns a 301 and redirects to https://service.pdok.nl/hwh/hydrografie/atom/v1_0/downloads/hydrografie.zip. The problem is that the ‘HEAD’ request is done on the first URL, but when the SoapUI tries to access the redirection, it makes a 'GET' request, then we have the timeout. We tried to change this second request type, but we did not find any way to change it.

Best regards.

**Comment by arbakker** [comment]
@dperezBM thanks for your response. Has this change already been deployed to production?:

>Currently, we changed the request method for 'Get Spatial Dataset' from 'GET' to 'HEAD' to check the response times for the URL without downloading the resource and avoiding the timeout exception.

Our OpenSearch implementation is based on [GeoNetwork OpenSource](https://geonetwork-opensource.org/) and I would expect that there are more service providers that implement OpenSearch in this manner. Changing the current OpenSearch implementation to proxy the 'Get Spatial Dataset'  request instead of redirecting is not feasible in our opinion. Proxying instead of redirecting would mean the OpenSearch service needs to handle a lot more traffic, which it is not dimensioned for. 

Maybe you can open an issue in the [soap-ui repo](https://github.com/SmartBear/soapui/issues) to address this issue? I would expect a HEAD request to follow the redirect with a HEAD request. See for instance `curl`:

```shell
 curl -LI -v  "https://www.nationaalgeoregister.nl/geonetwork/opensearch/dut/download?spatial_dataset_identifier_namespace=http://www.pdok.nl&spatial_dataset_identifier_code=07575774-57a1-4419-bab4-6c88fdeb02b2&crs=https://www.opengis.net/def/crs/EPSG/0/4258&language=nl"
 ```

**Comment by arantzaetxebarria** [comment]
Dear @arbakker 

We have opened this issue https://github.com/SmartBear/soapui/issues/645 to see if they can give us more details.

Regards

**Comment by arbakker** [comment]
@arantzaetxebarria I unassigned myself from this issue. I am not in the capacity of resolving this issue, since I am not involved with INSPIRE validator implementation.

**Comment by fabiovinci** [comment]
Dear @arbakker,

I validated your service and it validates without errors (see test report: 
[Test run on 14_31 - 14.07.2023 with test suite Conformance Class Pre-defined Atom - IOS 635.zip](https://github.com/INSPIRE-MIF/helpdesk-validator/files/12050436/Test.run.on.14_31.-.14.07.2023.with.test.suite.Conformance.Class.Pre-defined.Atom.-.IOS.635.zip)).

I will close the issue, please reopen it if the error persists.
