### ISSUE TITLE
Pre-defined Atom 

### ISSUE THREAD

**Issue by LieGeo** [INSPIRE-MIF/helpdesk-validator#636]
I try to validate a Atom based download service.

Except the issues with the opensearch, which is still under development, i get an issue with a dataset feed:

_"Test that the Dataset Feed contains separate entries for each format/CRS combination in which the pre-defined dataset is made available for download."_
Service feed is
https://geodaten.llv.li/atom/8c4b6669-8828-44b7-a888-fd43f9611893.xml

I did not find out what the issue realy is  respectively i do not comprehend the error-message
Do you have a hint?
Regards
Peter

**Comment by dperezBM** [comment]
Dear @LieGeo,

Thank you for your message. We have tested the service and we received the same issue you are reporting. The Dataset Feed suite is referenced by the Download Service Feed suite. Please, check the cause of the problem by checking failed test cases on the Download Service Feed.

If you have any other problems, please feel free to answer this issue.

Best regards.
