### ISSUE TITLE
Describe Spatial Dataset validation rule status "undefined"

### ISSUE THREAD

**Issue by arbakker** [INSPIRE-MIF/helpdesk-validator#637]
**Summary:** validation result of _Describe Spatial Dataset_ rule in Conformance class Pre-defined Atom had value of `undefined`. 

- Conformance class: Pre-defined Atom
- Test report: see [Test run on 08 35 - 13.10.2021 with test suite Conformance Class Pre-defined Atom - PDOK.zip](https://github.com/INSPIRE-MIF/helpdesk-validator/files/7339630/Test.run.on.08.35.-.13.10.2021.with.test.suite.Conformance.Class.Pre-defined.Atom.-.PDOK.zip)
- Browser and version: not relevant, issue regarding implementation validation rules.

# Description

When validating ATOM service https://service.pdok.nl/rvo/schelpdierpercelen/atom/v1_0/index.xml I ran into the following validation result:

![afbeelding](https://user-images.githubusercontent.com/3216462/137167647-308e4567-7bb4-4ddb-8b9e-f8ef10b7dcc7.png)

Which results in the overall validation result `SKIPPED`. 

I would expect the _Describe Spatial Dataset_ validation rule to either pass or fail, and if it fails with an error message that indicates what is exactly failing. 

---
## Encore

The following is not part of the description of the bug, but rather me trying to figure out why the validation fails.

Quick research on the service that is being validated shows that the [Describe Spatial Dataset](https://www.nationaalgeoregister.nl/geonetwork/opensearch/dut/describe?spatial_dataset_identifier_code=3b8a3a2f-dffd-470f-b9bf-4a9c15259ac8&spatial_dataset_identifier_namespace=http://www.pdok.nl&language=nl) response has a content-type of `application/atom+xml`. 

However the underlying [ATOM Dataset feed](https://service.pdok.nl/rvo/schelpdierpercelen/atom/v1_0/schelpdierpercelen.xml) returns a Content-Type of `application/xml; charset=UTF-8`. Might this be causing the problem? Since the TG for download services states:
![afbeelding](https://user-images.githubusercontent.com/3216462/137170422-004c3689-4857-4600-949f-343a28280dc3.png)

And the [RFC 4287](https://datatracker.ietf.org/doc/html/rfc4287#section-7) states:

>  An Atom Document, when serialized as XML 1.0, can be identified with
   the following media type:
>
> MIME media type name:  application
> MIME subtype name:  atom+xml
> Mandatory parameters:  None.

**Comment by dperezBM** [comment]
Dear @arbakker,

As you mention, the ATOM Dataset feed returns a Content-Type of application/xml, which is not what the validator is expecting for this requirement (application/atom+xml). Nevertheless, we will check why the validator is not returning "Failed" status.
We will come back to you with more information.

Best regards.

**Comment by fabiovinci** [comment]
Dear @dperezBM,

I have the same error with the following ATOM: https://sgi3.isprambiente.it/download/BH.atom.TOP.en.xml 
Here there is the report: https://inspire.ec.europa.eu/validator/test-run/details.html?id=EID904b6467-52bc-48b0-91ea-e3b94ccd3e9a

The "Describe Spatial Dataset" test is not executed (Status = Undefined) and consequently the test "Query examples for each dataset"  is skipped since there is a dependency from the previous one.
For this reason, the overall validation result is SKIPPED.

**Comment by JLSchaap** [comment]
Hello @dperezBM,  can you please give a brief update on  "we will check why the validator is not returning "Failed" status." , thanks in advance.

**Comment by fabiovinci** [comment]
Dear all,

it seems the error is no longer present, due to the fix applied for issue #661.

Could you please test it?
Thanks

**Comment by mwjsanders** [comment]
@fabiovinci 

This issue has indeed been resolved. The undefined status does not occur any more on any validation results of PDOK services. This issues can be closed

Kind regards

**Comment by fabiovinci** [comment]
Dear @mwjsanders,

thank you for confirmation, I will close the issue.
