### ISSUE TITLE
Error when validating metadata

### ISSUE THREAD

**Issue by JohannaOtt** [INSPIRE-MIF/helpdesk-validator#640]
- [ ] a description of the steps to reproduce your issue
I tried validating service metadata as Network Service metadata and get an error (Gateway timeout)
- [ ] the browser and version used
Firefox 78.15.0esr
- [ ] a screenshot illustrating the problem
![grafik](https://user-images.githubusercontent.com/34163838/139017476-08922b9d-06a7-488c-bafd-81773c20ec1b.png)
- [ ] the URL of your service / the file you have uploaded or referenced (as
an attachment).
https://haleconnect.com/services/bsp/org.1016.96ca61ed-3706-44fb-a6b6-9adcde0faaf3/md/service/id_direct_download

The test works on the staging instance

**Comment by alitka** [comment]
- [x] used browser and version: Firefox Browser 91.2.0esr (64-Bit)

I did a double check and in my case everything worked fine, please see attached report > [check_md-service.zip](https://github.com/INSPIRE-MIF/helpdesk-validator/files/7439675/check_md-service.zip)

**Comment by JohannaOtt** [comment]
When I checked again right now, the test started for me as well.

**Comment by fabiovin** [comment]
Dear @JohannaOtt,

thank you for opening the issue.

There was a reboot of the instance and now it works fine.
