### ISSUE TITLE
Soil - Not resolving codelist URIs

### ISSUE THREAD

**Issue by robblis** [INSPIRE-MIF/helpdesk-validator#644]
Hi Validator Team,

We're testing the Soil theme and we are seeing the following errors for a few of the elements referencing codelist URIs.

_XML document 'SO_SoilLayer_service.xml', SoilLayer 'soSoilLayer.4004': The property 'layerGenesisProcessState' has a value 'http://inspire.ec.europa.eu/codeList/LayerGenesisProcessStateValue/ongoing' that is not one of the allowed values listed at 'http://inspire.ec.europa.eu/codelist/LayerGenesisProcessStateValue'. Please note that the URIs of all code list values from the INSPIRE Registry shall be referenced using the http protocol._

_XML document 'SO_SoilLayer_service.xml', SoilLayer 'soSoilLayer.4001': The property 'layerType' has a value 'http://inspire.ec.europa.eu/codelist/LayerTypeValue/topsoil' that is not one of the allowed values listed at 'http://inspire.ec.europa.eu/codelist/LayerTypeValue'. Please note that the URIs of all code list values from the INSPIRE Registry shall be referenced using the http protocol._

The returned URIs in the xlink:href values are valid for the specific codelist needed.

We're not sure why we are getting these failures from the validator.

I've uploaded a sample xml and the test report.

Can we get some assistance on this?

Thanks,
Robert

[SO_SoilLayer_Test.zip](https://github.com/INSPIRE-MIF/helpdesk-validator/files/7454967/SO_SoilLayer_Test.zip)

**Comment by arantzaetxebarria** [comment]
Dear @robblis 

We have analysed the issue and we have seen that the sample XML has some typos.
The codelist validation is case sensitive so for the properties layerGenesisProcessState is http://inspire.ec.europa.eu/code**l**ist/LayerGenesisProcessStateValue/ongoing instead http://inspire.ec.europa.eu/code**L**ist/LayerGenesisProcessStateValue/ongoing.
And for the property layerType is
http://inspire.ec.europa.eu/codelist/LayerTypeValue/subSoil instead http://inspire.ec.europa.eu/codelist/LayerTypeValue/subsoil,
http://inspire.ec.europa.eu/codelist/LayerTypeValue/topSoil instead http://inspire.ec.europa.eu/codelist/LayerTypeValue/topsoil and http://inspire.ec.europa.eu/codelist/LayerTypeValue/depthInterval instead http://inspire.ec.europa.eu/codelist/LayerTypeValue/depthinterval

Please check these changes and let us know if all is ok.

Regards,
Arantza

**Comment by robblis** [comment]
Hi @arantzaetxebarria ,

Thank you for your assistance and catching the case issue in the URI.

We've updated our services to use the correct URI and have resolved the validation issues.

Robert
