### ISSUE TITLE
Validator Throws General Error 

### ISSUE THREAD

**Issue by robblis** [INSPIRE-MIF/helpdesk-validator#645]
Hi Validator Team,

We're trying to run some Data set validations. 

However, we see the general error "An error has occured" at the bottom of the page after clicking the Start test button.

Can someone look into this?

Thanks,
Robert

![ValidatorGeneralError](https://user-images.githubusercontent.com/3453448/140178913-fbe1d772-c60e-429d-9cb6-731ebc6eb6b3.PNG)

**Comment by jenriquesoriano** [comment]
Dear @robblis , 
thanks for reporting the issue, the instance has been rebooted and this error is not present anymore.
Could you please verify?

**Comment by robblis** [comment]
Hi @jenriquesoriano,

The Validator is operational.

Thanks,
Robert
