### ISSUE TITLE
Statistical Units - StatisticalTessellation feature type reports missing 'Statistical Units' feature

### ISSUE THREAD

**Issue by robblis** [INSPIRE-MIF/helpdesk-validator#646]
Hi Validator Team,

Upon testing the StatisticalTessellation feature type in the Statistical Unit theme we are getting the following error in the...
Conformance Class 'GML application schemas, Statistical Units' > Basic test > su-gml.a.1: Statistical Units feature in dataset

_The XML documents representing the spatial data set do not contain a feature of any of the spatial object types in the 'Statistical Units' application schemas. Therefore, the spatial data set cannot conform to this conformance class. If you have expected to find spatial objects from the application schema in the data set, please consult the statistics information to see the spatial object types that have been found._

Looking at the test details it seems it is looking for one of the following feature types...
self::su-vector:VectorStatisticalUnit | self::su-vector:AreaStatisticalUnit | self::su-vector:StatisticalTesselation | self::su-vector:Evolution| self::su-grid:StatisticalGridCell | self::su-grid:StatisticalGrid

In our returned XML we have the following element in each of the su-vector:StatisticalTessellation objects...
     <su-vector:units>
	<su-vector:AreaStatisticalUnit gml:id="suVectorStaUnit.101">

Not sure if the test is looking for one of the features type in the root of the su-vector:StatisticalTessellation objects. The schema for su-vector has the su-vector:AreaStatisticalUnit within the su-vector:units element.

One other error that we're seeing, which is only on the Staging validator but not on the official released validator is...
Conformance Class 'Data consistency', General requirements > Temporal consistency > dc.b.1: Valid time plausible

_System error in the Executable Test Suite. Please contact a system administrator. Error information:[err:FORG0001] Wrong xs:dateTime format: '' (try e.g. '2000-12-31T23:59:59.999'). 
 (662/14)_

Not sure which element this is addressing and why it only happens on the Staging validator.

I've uploaded the service XML and the Validation report.

Thanks for your help,
Robert

[SU_StatisticalTessellation_Test.zip](https://github.com/INSPIRE-MIF/helpdesk-validator/files/7470755/SU_StatisticalTessellation_Test.zip)

**Comment by arantzaetxebarria** [comment]
Dear @robblis 

Thank you for your message. We will analyze the issue that you reported to us and we will come back to you as soon as we get any further information.

Regarding the issue in  'General requirements > Temporal consistency > dc.b.1: Valid time plausible' we have ready a fix, that in the next few days we will upload to the staging instance.

Best regards.
Arantza

**Comment by arantzaetxebarria** [comment]
Dear @robblis 

We have done an update in the ETS to solve the issues **Conformance Class 'GML application schemas, Statistical Units' > Basic test > su-gml.a.1: Statistical Units feature in dataset** and **Conformance Class 'Data consistency', General requirements > Temporal consistency > dc.b.1: Valid time plausible**, they are published in staging instance. Could you please test again? thanks.

Regards,

Arantza

**Comment by robblis** [comment]
Hi @arantzaetxebarria ,

The test succeeded for StatisticalTessellation.

Thanks for the fix,
Robert

**Comment by dperezBM** [comment]
Dear @robblis,

Thank you for your feedback. We will mark this issue as solved.

Best regards.
