### ISSUE TITLE
MR - MineralOccurance looking for ge:MappedFeature

### ISSUE THREAD

**Issue by robblis** [INSPIRE-MIF/helpdesk-validator#649]
Hi Validator Team,

We are currently testing our MR theme services.

We see the following error reported from the validator...
Conformance Class 'GML application schemas, Mineral Resources' > Specific requirements > mr-as.b.1: specification
_XML document 'service.xml', MineralOccurrence 'mrMineralOccurrence.101': The geometric properties of the MineralOccurrence feature type are not provided._

Looking at the Expression for the test, it looks like the test is looking for a ge:MappedFeature element. However, the MineralResourcesCore.xsd schema doesn't contain any element for ge:MappedFeature.

Can we get some assistance on this?

I've uploaded the service XML and Validation Report.

Thanks,
Robert

[MR_MineralOccurance_Test.zip](https://github.com/INSPIRE-MIF/helpdesk-validator/files/7488428/MR_MineralOccurance_Test.zip)

**Comment by arantzaetxebarria** [comment]
Hi @robblis 

Thank you for your message. We are going to check the code to solve the problem, we will come back to you once the issue is on our staging instance.

Regards,

Arantza

**Comment by arantzaetxebarria** [comment]
Dear @robblis

We have updated the [staging](http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/home/index.html) environment with a fix in the ETS to solve this issue. Could you please test again and verify?

Thanks,

Arantza

**Comment by robblis** [comment]
Hi @arantzaetxebarria ,

We've re-tested MineralOccurance on the staging validator and the test passed.

Thank you for the fix.
Robert
