### ISSUE TITLE
providing clarification on issue 39

### ISSUE THREAD

**Issue by arbakker** [INSPIRE-MIF/helpdesk-validator#650]
This [issue](https://github.com/INSPIRE-MIF/helpdesk-validator/issues/39) has been closed due to lack of interaction. 

However it would be nice if some clarity can be provided on the current state of affairs (even if the answer is inconclusive). This would save future souls from digging through the extensive but informative discussion to see what the current status is. 

- is the proposed relaxation implemented or not?
- will the proposed relaxation be implemented or not?

I also commented on the issue, but considering is is closed I am opening a new issue for visibility.

**Comment by iuriemaxim** [comment]
@arbakker I think that first the IR and TG should be clarified in relation with the text of the INSPIRE Directive, as the IR and TG should not contradict or should be interpreted in a way that contradicts the INSPIRE Directive.

If the relaxation proposed in incident 39 will be implemented, this will have big legal implications. Probably that its closure means that the proposed relaxation will not be implemented.

**Comment by arbakker** [comment]
@iuriemaxim  I agree with you that the IR and TG should be clarified first with respect to the INSPIRE Directive. 

@dperezBM I think the way forward is to reopen the issue and assign a `external dependency` label awaiting clarification.

**Comment by hogredan** [comment]
@arbakker and @iuriemaxim, a proposed amendment to the TG View Service has been submitted into the [governance process](https://github.com/INSPIRE-MIF/technical-guidelines/blob/main/governance-release-process/process.md), which has already been approved by MIG-T and MIG, see https://github.com/INSPIRE-MIF/technical-guidelines/issues/2. 

In addition, another proposal has been submitted to add a new requirement to the TG for layer names for harmonised datasets, see https://github.com/INSPIRE-MIF/technical-guidelines/issues/12.

Both changes are planned for the release 2022.2 (July 31), see https://github.com/INSPIRE-MIF/technical-guidelines/milestone/2.

Once the TG has been amended, the tests can be updated accordingly. The test related to the IR-ISDSS requirement could be added as a separated conformance class to the ETS for view services (similar to the way that this is being done for the metadata requirements for interoperability based on requirements in the IR-ISDSS).

**Comment by fabiovin** [comment]
Dear @hogredan,

thank you for your very clear explanation of the status of this issue.

I reopened issue 39 and I will copy/paste your comment, in order to continue the discussion in the original issue.
