### ISSUE TITLE
Dealing with "relaxed" implementations of services regarding request parameters - 2

### ISSUE THREAD

**Issue by arbakker** [INSPIRE-MIF/helpdesk-validator#652]
The issue [Dealing with "relaxed" implementations of services regarding request parameters](https://github.com/INSPIRE-MIF/helpdesk-validator/issues/40) has been closed due to lack of interaction. IMO this issue should be solved as proposed by changing the assertion to a warning. 

Is there any chance this will be solved in the near-future?

**Comment by dperezBM** [comment]
Dear @arbakker, 

Thank you for opening this issue. We are analyzing it and we will keep you posted. 

Best regards

**Comment by fabiovinci** [comment]
Dear @arbakker,

since this issue is a duplication of issue 40 and it does not contain the full discussion, I will close it and reopen the old one.
