### ISSUE TITLE
Validator running into an error

### ISSUE THREAD

**Issue by JohannaOtt** [INSPIRE-MIF/helpdesk-validator#653]
When trying to validate resources (an Atom Feed earlier today, a WMS right now), the Validator is running into an error when hitting the "Start test" button 
![grafik](https://user-images.githubusercontent.com/34163838/141311059-cdaff710-87b4-49de-bdec-1d9ecbf82de3.png)

**Comment by dperezBM** [comment]
Dear @JohannaOtt,

Is this issue still occurring to you? If this is the case, could you please share with us the metadata that you are testing?

Thank you and best regards.

**Comment by JohannaOtt** [comment]
I was able to start a test right now. Will create a new ticket in case the issue re-occurs.

**Comment by dperezBM** [comment]
Dear @JohannaOtt,

Thank you for your feedback. We will close this issue then. Please feel free to open a new one if needed.

Best regards.
