### ISSUE TITLE
OWS Exception Report vs Service Exception Report

### ISSUE THREAD

**Issue by JohannaOtt** [INSPIRE-MIF/helpdesk-validator#654]
For WMS requests with missing/wrong parameters, there are two kinds of exception reports that can be returned by the service - OWS exception reports and service expection reports.
[This WMS](https://haleconnect.com/ows/services/org.923.c06ef455-1a6b-4259-a31d-b59bb8c7bf09_wms?SERVICE=WMS&REQUEST=GetCapabilities&VERSION=1.3.0) gets a validation error concerning the exception report thrown for missing width/height parameters on the staging instance (production instance is currently not working): 
![grafik](https://user-images.githubusercontent.com/34163838/141314667-59d6ca36-1dea-46bf-adb1-a5a98c446775.png)

Indeed the service returns a ServiceExceptionReport (no OWS exception report) for the [respective request](https://haleconnect.com/ows/services/org.923.c06ef455-1a6b-4259-a31d-b59bb8c7bf09_wms?BBOX=2684196.93066389%2C4008121.40536396%2C3561465.67930242%2C4702167.69532320&CRS=EPSG%3A3035&FORMAT=image%2Fpng&LAYERS=SD.VitisVinifera&REQUEST=GetMap&SERVICE=WMS&STYLES=SD.SpeciesDistribution.Default&VERSION=1.3.0) 

The issue is that for other requests (for example [missing bounding box](https://haleconnect.com/ows/services/org.923.c06ef455-1a6b-4259-a31d-b59bb8c7bf09_wms?CRS=EPSG%3A3035&FORMAT=image%2Fpng&HEIGHT=500&LAYERS=SD.VitisVinifera&REQUEST=GetMap&SERVICE=WMS&STYLES=SD.SpeciesDistribution.Default&VERSION=1.3.0&WIDTH=500)), the service is also returning a ServiceExceptionReport, but the validator is not complaining in this case:  
![grafik](https://user-images.githubusercontent.com/34163838/141315074-b7b4c43f-5e09-4b6e-860b-079f3ea40e5d.png)

I seem to remember that the exception type was changed because the OWS exception report used to cause errors in the validator - now one of the ServiceExceptionReports does not pass.

Is there a rule, for which wrong requests which type of exception report is expected? Why is it not allowed to return a ServiceExceptionReport for missing height/width parameter but is allowed for missing bbox parameter?

**Comment by arantzaetxebarria** [comment]
Dear @JohannaOtt,

We will analyze this issue and we will come back to you with more information.

Best regards,
Arantza

**Comment by alitka** [comment]
Just a note: In both instance, the test ``at04-getcapabilities-xml-schema-validation`` (check-xml-schema-valid) throw an error: 

> Schema not valid: [org.xml.sax.SAXException: Fatal error: org.xml.sax.SAXParseException; lineNumber: 102; columnNumber: 32; cvc-complex-type.2.4.a: Invalid content was found starting with element 'sld:GetLegendGraphic'. One of '{"http://www.opengis.net/wms":_ExtendedOperation}' is expected. Response did not validate against schema 'http://inspire.ec.europa.eu/schemas/inspire_vs/1.0/inspire_vs.xsd'.]

Therefore, I guess that the other tests are not performed correctly.

**Comment by mpleic** [comment]
The problem occurred in a staging instance after making this [change](https://github.com/inspire-eu-validation/ets-repository/commit/a1f4c51230bd8192610db2e2f2670f81e7857fdd) which is not in accordance to the reported [issue](https://github.com/INSPIRE-MIF/helpdesk-validator/issues/584#issue-945240484).
I analyzed the problem and reported it [here](https://github.com/INSPIRE-MIF/helpdesk-validator/issues/599#issuecomment-950190356) as well as the solution proposal.
The change mentioned above is now reversed but it is not deployed. A [pull request](https://github.com/inspire-eu-validation/ets-repository/pull/686) for it is still open. So after accepting this merge request and deploying staging instace this problem will be solved, but the issue #584 remains unresolved.

**Comment by dperezBM** [comment]
Dear @JohannaOtt,

We have reviewed and updated the current [staging instance](http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/), which had a remaining change for issue #584, as @mpleic mentioned in the comment above. We decided to revert this change.

Please, let us know if this change was valid for you. 

Best regards.

**Comment by JohannaOtt** [comment]
I can confirm that I do not get an issue any longer for the http-request-getmap-no-width-height test case 
![grafik](https://user-images.githubusercontent.com/34163838/145432195-80777138-cf52-4c60-8c3a-55d4e2ac5c5a.png)
Test report 
[Test run on 17 02 - 09.12.2021 with test suite Conformance Class View Service WMS.html.zip](https://github.com/INSPIRE-MIF/helpdesk-validator/files/7686657/Test.run.on.17.02.-.09.12.2021.with.test.suite.Conformance.Class.View.Service.WMS.html.zip)
