### ISSUE TITLE
Reference validator and api is not working

### ISSUE THREAD

**Issue by radochudy** [INSPIRE-MIF/helpdesk-validator#655]
When will be validator stable and will work normally? In the last two weeks, when i want to work, validator is not working at all.... It has  problem to load service endpoint, local file etc...
 Also API is down...

https://inspire.ec.europa.eu/validator/swagger-ui.html
HTTP ERROR: 503
Problem accessing /validator/swagger-ui.html. Reason:

    Service Unavailable

**Comment by carlospzurita** [comment]
Dear @radochudy 

Sorry that you are experiencing this problems and they are interfering in your usage of the validator.

Could you please share with us what type of tests were you trying to create, and how many times did you experience these issues, around what time of day?

Kind regards

**Comment by Ejuc** [comment]
From around 12 hours ago till now the validator API at https://inspire.ec.europa.eu/validator/v2/ is not working (504 or 502 errors). It actually went offline during the test of Conformance of INSPIRE Download Services (Download Service Direct WFS).

`502 Proxy Error

The proxy server received an invalid response from an upstream server.
The proxy server could not handle the request GET /validator/v2/.

Reason: Error reading from remote server`

or 

`504 Gateway Time-out`

**Comment by radochudy** [comment]
Validator is not working again.... View serrvice conformance test.

`label: "Test run on 14:18 - 22.11.2021 with test suite Conformance Class View Service WMS",…}
arguments: {}
executableTestSuiteIds: ["EIDeec9d674-d94b-4d8d-b744-1309c6cae1d2"]
0: "EIDeec9d674-d94b-4d8d-b744-1309c6cae1d2"
label: "Test run on 14:18 - 22.11.2021 with test suite Conformance Class View Service WMS"
testObject: {username: "", password: "", resources: {,…}}
password: ""
resources: {,…}
serviceEndpoint: "http://172.30.5.56:8081/geoserver/ad/ows?service=WMS&version=1.3.0&request=GetCapabilities"
username: ""`

Response
`<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>502 Proxy Error</title>
</head><body>
<h1>Proxy Error</h1>
<p>The proxy server received an invalid
response from an upstream server.<br />
The proxy server could not handle the request <em><a href="/validator/v2/TestRuns">POST&nbsp;/validator/v2/TestRuns</a></em>.<p>
Reason: <strong>Error reading from remote server</strong></p></p>
</body></html>
`

**Comment by carlospzurita** [comment]
Dear @radochudy 
We have recently had problems in the availability of the validator (see #663 ). We are investigating if there is any validation ongoing that is interfering with the normal functioning of the service. We will get back to you with more feedback.

Kind regards.

**Comment by jenriquesoriano** [comment]
Dear @radochudy , 

thanks for pointing the issue.
This issue is solved, could you please verify it?
Keep in contact.

Best,

**Comment by jenriquesoriano** [comment]
The service was restored, so we proceed to close the issue.
Please feel free to open an issue in case this behaviour happens again.
