### ISSUE TITLE
SO Theme - SoilDerivedObject Test Looking for soilDerivedObjectObservation

### ISSUE THREAD

**Issue by robblis** [INSPIRE-MIF/helpdesk-validator#659]
Hi Validator Team,

We are running some tests for the Soil theme. When running a test against the SoilDerivedObject feature type we're seeing the following error reported.

Conformance Class: Information accessibility, Soil > Feature reference > so-ia.b.9: SoilDerivedObject.soilDerivedObjectObservation

XML document 'SO_DerivedObject_service.xml', SoilDerivedObject 'soSoilDerivedObjectP.501': The property 'SoilDerivedObject.soilDerivedObjectObservation' shall be provided.

As far as I can see, the Soil.xsd schema does not contain the "soilDerivedObjectObservation" element under the SoilDerivedObject feature.

Please advise.

I've attached the service xml and the validator report.

Thanks,
Rober
[SO_DerivedObject_Test.zip](https://github.com/INSPIRE-MIF/helpdesk-validator/files/7530076/SO_DerivedObject_Test.zip)
t

**Comment by JohannaOtt** [comment]
Hi Robert,

The associations to observations are planned to be added - see https://github.com/INSPIRE-MIF/application-schemas/issues/8 
They are already available in the draft schema https://inspire.ec.europa.eu/draft-schemas/so/4.0/Soil.xsd


All the best

Johanna

**Comment by arantzaetxebarria** [comment]
Dear @robblis

We are going to analyze the issue, we will come back to you once we have a response.

Regards,

Arantza

**Comment by fabiovin** [comment]
Dear @robblis,

as indicated by JohannaOtt there was an error in the Soil.xsd application schema and it was fixed in the [last schema release](https://github.com/INSPIRE-MIF/application-schemas/releases). 

Now, the official schema (https://inspire.ec.europa.eu/schemas/so/4.0/Soil.xsd) contains the "soilDerivedObjectObservation" element under the SoilDerivedObject feature type and the multiplicity is 1..*, but it is voidable.

So, even if you do not have the related information, you need to insert the element in the dataset.

The related check in the validator is already present because the "soilDerivedObjectObservation" element was already defined in the IR and in the TG.

**Comment by fabiovin** [comment]
Dear @arantzaetxebarria,

according to the schema fix, I update the related ATS (https://github.com/inspire-eu-validation/data-so/commit/2ec874e1c7f86541929b1c906af206c96fec14e1) changing the multiplicity of the "soilDerivedObjectObservation" element from 1 to 1..*.
Could you please update the related ETS accordingly?

Thanks.

**Comment by arantzaetxebarria** [comment]
Dear @fabiovin 

Thanks for the information, we will update the related ETS and we will come back to you once it is on the staging instance.

Regards

**Comment by arantzaetxebarria** [comment]
Dear @robblis, @fabiovin 

The related ETS has been updated and you can test it in the staging instance. The multiplicity of the "soilDerivedObjectObservation" element has been changed from 1 to 1..*.

Regards

**Comment by arantzaetxebarria** [comment]
Dear @robblis 

As we are going to make a new release in the coming days, we need to confirm that the fix for your issue in the staging environment is right. Could you please verify? Thanks.

Regards

**Comment by fabiovinci** [comment]
Dear @arantzaetxebarria,

I testes the solution in staging and it works fine.
We can include the fix in the next release.
Thanks

**Comment by robblis** [comment]
Hi @fabiovinci, just an FYI, we tested the updated Soil.xsd with our service and Validation was successful.
