### ISSUE TITLE
 Proposal to relax content-type requirement for ATOM feed resources

### ISSUE THREAD

**Issue by arbakker** [INSPIRE-MIF/helpdesk-validator#661]
I would like to propose to relax the mime-type requirement for ATOM feed resources to allow for `application/xml` as well (besides `application/atom+xml`). 

The ETF validator currently checks if Describe Spatial Dataset response equals `application/atom+xml`:

![describe-spatial-ds-content-type](https://user-images.githubusercontent.com/3216462/142224498-a0ae612b-802d-4a4f-8ea5-b1d31724727d.png)

As I understand the OpenSearch Describe Spatial Dataset is just a proxy for the ATOM Dataset feed. So the Describe Spatial Dataset response will return the dataset feed for that particular dataset. 

The current requirement makes sense per [ATOM RFC](https://datatracker.ietf.org/doc/html/rfc4287#section-7) and [_TG Requirement 2 / download services_](https://inspire.ec.europa.eu/documents/technical-guidance-implementation-inspire-download-services) (although the wording in the RFC does not seem to indicate it is required): 

![afbeelding](https://user-images.githubusercontent.com/3216462/142226032-37722a94-9985-401b-9c99-8811de7ca702.png)

![afbeelding](https://user-images.githubusercontent.com/3216462/142225142-6df2050e-ff6d-4ef2-9212-bfba9621cb16.png)

The problem I am facing with this requirement is that the mime-type `application/atom+xml` is not recognized as an XML format by most browsers. This is the case for at least Chromium based browsers (Google Chrome, MS Edge and more) and Firefox, which represents a [significant usage share](https://en.wikipedia.org/wiki/Usage_share_of_web_browsers#Summary_tables) of web browsers in use currently. Bug reports on this issue have been open for years, so probably will not be fixed any time soon:

- [Firefox](https://bugzilla.mozilla.org/show_bug.cgi?id=155730#c65) - Opened 20 years ago
- [Chromium](https://bugs.chromium.org/p/chromium/issues/detail?id=104358) Opened 10 years ago

A consequence of browsers failing to recognize the mime-type `application/atom+xml` as an XML based format is that browsers do not render the ATOM feed with XML syntax highlighting. Which reduces the user experience of consuming the ATOM feeds directly in a web browser:

![afbeelding](https://user-images.githubusercontent.com/3216462/142224640-835db96e-08cb-4976-bcee-4a1cb656c5ca.png)

![afbeelding](https://user-images.githubusercontent.com/3216462/142224888-5f576041-2c51-46cf-93a0-4512f55e8dd0.png)

An additional consequence is that the browser [XSLTProcessor API](https://caniuse.com/?search=XSLTProcessor%20API) does not work as well. We use this feature to let the browser render the ATOM XML feeds into a user-friendly HTML output, see for instance [Download Service van BRO Wandonderzoek](https://service.pdok.nl/bzk/brosfrvolledigeset/atom/v1_0/index.xml). This works through including an XSL stylesheet in the ATOM feed:

```
<?xml-stylesheet href="https://service.pdok.nl/atom/style/style.xsl" type="text/xsl" media="screen"?>
```

This way we can direct users directly to our ATOM services, but this only works if the browser thinks it is dealing with a XML based resource. I am aware the ATOM protocol is mostly intended for machine-to-machine consumption, however I want to argue that facilitating human-to-machine consumption for ATOM services will lower the barrier to entry to these services. Therefore I am proposing to allow usage of `application/xml` mime-type for ATOM feed resources. 

Also I wonder whether the [ATOM RFC](https://datatracker.ietf.org/doc/html/rfc4287#section-7) is normative on the usage of the `application/atom+xml` mime-type since it states:

>  An Atom Document, when serialized as XML 1.0, can be identified with
>   the following media type:
>
>  MIME media type name:  application
>  MIME subtype name:  atom+xml

If this is the case , namely `application/atom+xml` is not required per RFC, this relaxation would be in scope of the TG for downloadservices. If not this relaxation would out of scope of the TG, but I would argue reflects current practices in publishing ATOM feeds and stimulates usage of ATOM services.

**Comment by dperezBM** [comment]
Dear @arbakker,

Thank you for opening this issue. We will analyze your proposal and we will come back to you when a decision is taken.

Best regards

**Comment by fabiovin** [comment]
Dear @arbakker,

we analyzed the issue and your proposal (well documented), and our conclusion is that since the mime-type `application/atom+xml` is mentioned in several TG requirements a change in the validator requires first a change in the TG.

Could you please open an issue in the [technical-guidelines repository](https://github.com/INSPIRE-MIF/technical-guidelines)?

Thanks

**Comment by fabiovinci** [comment]
Dear @arbakker,

we can leave the issue open until the related TG issue is addressed, if the proposal is accepted we will handle the changes in the validator through this issue.

**Comment by arbakker** [comment]
I just realized it is common to have a encoding specification in the `application/xml` mimetype like:

```
application/xml;charset=UTF-8
```

Will the validator also accept this? (instead of just only using `application/xml`.

**Comment by fabiovinci** [comment]
Dear @arbakker,

the related change proposal for the WFS TG has been already endorsed, but the changes will be introduced as soon as the WFS TG is available in asciidoc format.

In the meantime, we will start to introduce the endorsed changes in the validator.

Regarding your question, the three proposed values for the mime-types of the ATOM feed resources are documented in the [IANAs media type register](https://www.iana.org/assignments/media-types/media-types.xhtml):

- application/xml
- application/atom+xml
- text/xml

therefore, I think the value you are proposing "application/xml;charset=UTF-8" cannot be considered valid.

**Comment by fabiovinci** [comment]
Dear @dperezBM, @arantzaetxebarria,

I updated the related [ATS](https://github.com/inspire-eu-validation/download-atom/tree/3.2) with changes endorsed for TG Requirements 7, 15 and 42.
The modified tests are available in the 3.2 branch, which corresponds to the next WFS TG version that will be published as soon as it is available in asciidoc format.

Could you please implement the changes in the ETS? Thanks.

**Comment by arbakker** [comment]
@fabiovin the mimetype `application/xml; charset=utf-8` is valid according to [RFC 7303: XML Media Types/section-8.1
](https://www.rfc-editor.org/rfc/rfc7303#section-8.1) (according to [Wikipedia](https://en.wikipedia.org/wiki/XML_and_MIME) the current RFC for XML Media Types). The same is true for `text/xml; charset=utf-8` and any other `charset` parameter value.

**Comment by arbakker** [comment]
To add to my previous comment; considering that the charset parameter is part of XML Media Types spec, it does not need to be added explicitly to the Technical Guidance. But it does need to be implemented in the validator to also allow for XML Media Types with charset params.

**Comment by dperezBM** [comment]
Dear @arbakker 

The solution is available in [staging instance](http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/). You can check if it is correct.

Regards.

@fabiovin Could you also check it?

**Comment by fabiovinci** [comment]
Dear all,

I tested the solution and it works.

@arbakker, regarding the presence of the value "`charset=utf-8`" in the Content-Type response, it is ok since, at the moment, the validator does not check the response value of the xml document.
