### ISSUE TITLE
View service validator marks PS.ProtectedSitesNatureConservation as invalid layer name

### ISSUE THREAD

**Issue by DKKepinski** [INSPIRE-MIF/helpdesk-validator#662]
Hello,

We have a [service](https://geodata.nationaalgeoregister.nl/inspire/ps-natura2000/wms?request=Getcapabilities&service=wms) which has its layer name marked as invalid:
![image](https://user-images.githubusercontent.com/11194319/142412020-48d0ab59-8a5a-4745-9bd0-10602112b7c9.png)

But according to the [technical guidance](https://inspire.ec.europa.eu/id/document/tg/ps), this should be considered a valid layer:
![image](https://user-images.githubusercontent.com/11194319/142412075-acc4f0e7-212c-4ee0-a629-0b027699074f.png)

It seems to us that the validator uses [Inspire layer register](https://inspire.ec.europa.eu/layer), which indeed does not contain PS.ProtectedSitesNatureConservation as a valid option, nonetheless it is valid according to the TG.

**Comment by dperezBM** [comment]
Dear @DKKepinski,

Thank you for your message. This issue is a long-standing one. You can find its progress and history in both issues [#491] and [#650]. Please feel free to post on them. We will close this issue to avoid duplicate threads about the same topic.

Thank you and best regards.
