### ISSUE TITLE
INSPIRE validator API not working

### ISSUE THREAD

**Issue by Ejuc** [INSPIRE-MIF/helpdesk-validator#663]
From around 12 hours ago till now the validator API at https://inspire.ec.europa.eu/validator/v2/ is not working (504 or 502 errors). It actually went offline during the test of Conformance of INSPIRE Download Services (Download Service Direct WFS).

` 502 Proxy Error ` 

The proxy server received an invalid response from an upstream server.
The proxy server could not handle the request GET /validator/v2/.

Reason: Error reading from remote server 

or 

`504 Gateway Time-out`

**Comment by dperezBM** [comment]
Dear @Ejuc 

Thank you for opening this issue. We have tested this morning the API and we do not encounter any problem with it. this may be because the validator is reloaded every night, and this reload may have solved the problem with the API.
Are you still having this problem?

Best regards.

**Comment by Ejuc** [comment]
Indeed the problem is gone now, but it was still not working all Saturday and Sunday and even 2AM today. There were also 502 Bad Gateway errors on test result XML link done previously (that is currently working).

**Comment by carlospzurita** [comment]
We are aware that the problems are recurrent and we are investigating what is the issue, if there is any problematic validation that causes the service to malfunction. We will get back to you with more feedback.

Kind regards.

**Comment by jenriquesoriano** [comment]
Dear @Ejuc ,

thank you for your input and raising the issue.
This issue is currently solved, so we close it accordingly.
In case it is raised again, please, feel free to reopen it or create a new issue.

Best regards,
