### ISSUE TITLE
Can't test dataset

### ISSUE THREAD

**Issue by Ana-SGA** [INSPIRE-MIF/helpdesk-validator#668]
Dear all & @carlospzurita ,

we can't test this dataset which was previously tested without any problem
[Grad_Zagreb_stvarno_koristenje_zemljista_2011_1.zip](https://github.com/INSPIRE-MIF/helpdesk-validator/files/7618158/Grad_Zagreb_stvarno_koristenje_zemljista_2011_1.zip). Testing should be for Land use/Existing Land Use.

Is anything else needed?

**Comment by MarcoMinghini** [comment]
Dear @Ana-SGA,
following the introduction of an API gateway (see the discussion at #594), we have recently modified the UI. Can you please clear any cached files on your browser before using the Validator and/or access the Validator from a private browser (incognito browser) and inform us whether the issue still happens? We are not detecting any issue in the Validator.

**Comment by carlospzurita** [comment]
Dear @Ana-SGA 

Thank you for opening the issue, we are checking what is happening with the upload of your dataset. We reproduce the error and we are investigating it.

We'll get back to you with some updates.

**Comment by Ana-SGA** [comment]
Dear @carlospzurita , 

thanks for helping. I can validate smaller GMLs, are zip or larger files causing the problem?

Dear @MarcoMinghini , yes I have cleared cache and tried in private window, same error 0-.

**Comment by carlospzurita** [comment]
Dear @Ana-SGA 

It is indeed related to the file size of the GML. This may point to a limit imposed by the new API implemented, and we are looking if it a modifiable parameter for the deployment.

Kind regards.

**Comment by JohannaOtt** [comment]
> It is indeed related to the file size of the GML

@carlospzurita I just tried validating a gml file <40 MB, zipped even <10 MB and could not upload them. Where is the limit for gml files now?

**Comment by Ana-SGA** [comment]
Dear @carlospzurita ,
just to add - we also can't test zipped metadata (collective), that also worked fine before. Can you please tell us will there soon be any changes?

**Comment by JohannaOtt** [comment]
I now get a different error message 
![grafik](https://user-images.githubusercontent.com/34163838/145027288-d348bb94-d848-43ed-89d6-492bc2ad56fe.png)
when trying to upload a zipped file <5 MB.

And a third one on staging
![grafik](https://user-images.githubusercontent.com/34163838/145027538-838ac6be-cb4c-4cf8-a9bb-df5fea88ec90.png)

**Comment by Ana-SGA** [comment]
Dear @carlospzurita and @MarcoMinghini ,
will it be possible to validate datasets soon? The same errors, already mentioned, still occur.

**Comment by jenriquesoriano** [comment]
Dear @Ana-SGA , @JohannaOtt ,

we have just reconfigured the API gateway set-up in order to accomodate larger files.
After cleaning the cache, the performed changes should take effect.
Could you please verify if the present issue is still happening?

Kind regards,

**Comment by Ana-SGA** [comment]
Dear @jenriquesoriano ,
I cleared the cache, but it didn't help. Errors still occur when uploading datasets from GML or ZIP - 502 Proxy Error or 504 Gateway Time-out (the files are never uploaded).

**Comment by Ana-SGA** [comment]
Dear @jenriquesoriano , 
at the moment it seems that the files are uploaded but when starting the test there is again an error "An error has occured" without an info code.

**Comment by jenriquesoriano** [comment]
Dear @Ana-SGA, 

thanks for your feedback.
After further modifications in the production instance during the past days, we have tested this issue and it seems to be solved.
We have used as a sample the data you provided, you can see the test report obtained at:
https://inspire.ec.europa.eu/validator/test-run/index.html?id=EIDb37109b2-5d37-4adf-972f-fc97f7c814bf

Could you please verify if the issue is still happening?

**Comment by Ana-SGA** [comment]
Dear @jenriquesoriano and all ,
first of all I wish you a happy New Year! It seems that now it is possible to upload and test datasets. Colors are missing from the report layout (green/red) - is that intentional? They really contribute to the clarity and neatness of the report.

**Comment by jenriquesoriano** [comment]
Dear @Ana-SGA , 

thanks for your feedback and happy new year from all the team.

Maybe it is related to a cache issue, as we haven't implemented any change at this regard and see the test report properly.

Please find it at:
https://inspire.ec.europa.eu/validator/test-run/details.html?id=EID0699d76f-bf93-45d3-aeeb-69c30aa1c477

![imagen](https://user-images.githubusercontent.com/25343632/147933272-b9d26d7b-ec52-424b-b188-0fd554eeaa83.png)


Could you check it by cleaning the cache (ctrl-f5, or incognito browser) and give us some more feedback in case the issue is still present?

Keep in contact.

Best

**Comment by Ana-SGA** [comment]
Dear @jenriquesoriano ,

cleared the cache (several times :)) but that didn't help. But all reports open really slowly - I don't know if it's up to our network maybe & perhaps it's the reason why report display isn't as it should be? Or it has something to do with the size of the dataset? I see the Validator is currently down for maintenance, maybe that could help... will try again later

**Comment by Ana-SGA** [comment]
Dear @jenriquesoriano ,
we can't test datasets again - is there some kind of work in progress hence the error or something else is causing an issue?

**Comment by jenriquesoriano** [comment]
Dear @Ana-SGA , 

thanks for pointing the issue, there was a heavy load on the validator and some services became unavailable.
We have restarted the service and tested the attached file.
Please see: https://inspire.ec.europa.eu/validator/test-run/index.html?id=EIDdae8e30b-3c88-4b5a-9265-09135c026246

Please excuse the inconvenience.
Keep in touch.

Best,

**Comment by Ana-SGA** [comment]
Dear @jenriquesoriano ,

thank you for solving the problem, seems it's working again on datasets.

**Comment by Ana-SGA** [comment]
Dear @jenriquesoriano ,
hahh sorry but it's down again?! Now when I try to upload files there is an error - 502 Bad Gateway?

**Comment by jenriquesoriano** [comment]
Dear @Ana-SGA ,

thanks for raising the issue.
We are dealing with an overload of the Validator.
We are working to have it back in the following minutes.
We have just posted #687 to clarify.

Keep you posted.

Best,

**Comment by Ana-SGA** [comment]
Dear @jenriquesoriano ,
thanks for your feedback. Hm, on a staging instance it is not possible to test datasets for some time now?

**Comment by jenriquesoriano** [comment]
Dear @Ana-SGA ,

validator is back to normal.
Keep you posted.

Best,

**Comment by jenriquesoriano** [comment]
Dear @Ana-SGA , 
we close this issue as the validator is working normally.
Please feel free to open a new issue in case you detect any problem.
Best
