### ISSUE TITLE
Inconsistencies regarding CRSs EPSG:5013, EPSG:5014 and EPSG:5015

### ISSUE THREAD

**Issue by heidivanparys** [INSPIRE-MIF/helpdesk-validator#669]
There is a discrepancy between the different tests regarding the CRSs with EPSG codes 5013, 5014 and 5015.

In commit https://github.com/inspire-eu-validation/ets-repository/commit/b2f37c0ad86ce77b25ee788b1a05d231cdc6dd94, CRSs with EPSG codes 5013, 5014 and 5015 were added to the ETS for checking data, see also https://github.com/INSPIRE-MIF/helpdesk-validator/issues/307. That change was not done in the corresponding abstract test, available at http://inspire.ec.europa.eu/id/ats/data/master/reference-systems/spatial (https://github.com/inspire-eu-validation/data/blob/master/reference-systems/spatial.md).

The CRSs with EPSG codes 5013, 5014 and 5015 are not present either in the tests for metadata, see:

- https://github.com/inspire-eu-validation/ets-repository/blob/master/metadata/2.0/datasets-and-series/ets-md-isdss-bsxets.xml
- http://inspire.ec.europa.eu/id/ats/metadata/2.0/isdss/crs-id
- https://github.com/inspire-eu-validation/ets-repository/blob/master/metadata/2.0/sds/ets-md-sdsinteroperable-bsxets.xml
- http://inspire.ec.europa.eu/id/ats/metadata/2.0/sds-interoperable/crs-http-uris

In addition:

1. Where is the most recent list and authoritative list for the INSPIRE approved CRSs?
2. What is the procedure for adding CRSs for regions outside continental Europe to that list? (which is allowed already today, before the [upcoming amendment](https://ec.europa.eu/info/law/better-regulation/have-your-say/initiatives/13182-Revision-of-INSPIRE-regulations-interoperability-of-spatial-data-sets-and-services_en), according to https://eur-lex.europa.eu/legal-content/EN/TXT/HTML/?uri=CELEX:02010R1089-20141231#tocId136)

**Comment by fabiovin** [comment]
Dear @heidivanparys,

thank you for the issue, we will update all the related ATS and ETS with the new EPSG codes already added for data.

@arantzaetxebarria, @dperezBM, could you please check all ATS/ETS which include tests on CRS and update them with EPSG codes (5013, 5014 and 5015) already added for data check? Thanks.

Regarding your questions:
1. At the moment, there is not an official list and since there are different ATS/ETS that use CRSs, I think the right place would be the INSPIRE registry.
2. There is no defined procedure for that, the inclusion of the EPSG codes 5013, 5014 and 5015 was discussed and approved in a MIG-T meeting.

**Comment by arantzaetxebarria** [comment]
Dear @heidivanparys 

We have updated the ETS with the new EPSG codes, on the staging instance. Could you please test again and verify?

Thanks

**Comment by arantzaetxebarria** [comment]
Dear @heidivanparys 

We have updated the ETS with the new EPSG codes, on the staging instance. Could you please test again and verify?

Thanks

**Comment by arantzaetxebarria** [comment]
Dear @heidivanparys 

As we are going to make a new release in the coming days, we need to confirm that the fix for your issue in the staging environment is right. Could you please verify? Thanks.

Regards

**Comment by heidivanparys** [comment]
I tested with https://github.com/INSPIRE-MIF/helpdesk-validator/blob/master/examples/Dataset_metadata_2.0_example.xml, with the following changes:

```xml
  <gmd:referenceSystemInfo>
    <gmd:MD_ReferenceSystem>
      <gmd:referenceSystemIdentifier>
        <gmd:RS_Identifier>
          <gmd:code>
            <gmx:Anchor xlink:href="http://www.opengis.net/def/crs/EPSG/0/5013">EPSG:5013</gmx:Anchor>
          </gmd:code>
        </gmd:RS_Identifier>
      </gmd:referenceSystemIdentifier>
    </gmd:MD_ReferenceSystem>
  </gmd:referenceSystemInfo>
```
→ passes, as expected.

```xml
  <gmd:referenceSystemInfo>
    <gmd:MD_ReferenceSystem>
      <gmd:referenceSystemIdentifier>
        <gmd:RS_Identifier>
          <gmd:code>
            <gmx:Anchor xlink:href="http://www.opengis.net/def/crs/EPSG/0/5015">EPSG:5015</gmx:Anchor>
          </gmd:code>
          <gmd:codeSpace>
            <gco:CharacterString>WRONG</gco:CharacterString>
          </gmd:codeSpace>
        </gmd:RS_Identifier>
      </gmd:referenceSystemIdentifier>
    </gmd:MD_ReferenceSystem>
  </gmd:referenceSystemInfo>
```
→ fails, as expected.
