### ISSUE TITLE
Internal error in test engine with Conformance Class: INSPIRE Profile based on EN ISO 19115 and EN ISO 19119 test suite

### ISSUE THREAD

**Issue by psysiu** [INSPIRE-MIF/helpdesk-validator#67]
I've been using the INSPIRE Sandbox Validator (http://inspire.ec.europa.eu/validator/) today. After some time "Conformance Class: INSPIRE Profile based on EN ISO 19115 and EN ISO 19119" tests started failing because of "internal error in test engine".

The error message for both "Conformance Class: XML encoding of ISO 19115/19119 metadata" and "Conformance Class: INSPIRE Profile based on EN ISO 19115 and EN ISO 19119" is `Unable to read  "/etf/projects/inspire-ets-repository/ets-repository-master/metadata/inspire-md-bsxets.xq" : file/directory does not exist`

Best regards,
Michał

**Comment by josemasensio** [comment]
@psysiu we will check it and try to fix it as soon as possible.

Best regards.

**Comment by josemasensio** [comment]
Dear @psysiu,

We are happy to announce that the solution for this issue has been implemented. The solution passed our quality controls, but we will appreciate if you could test it and give us some feedback. 

Thanks in advance for your help.
