### ISSUE TITLE
WFS validation running into a OGC Team Engine Timeout

### ISSUE THREAD

**Issue by JohannaOtt** [INSPIRE-MIF/helpdesk-validator#672]
- [ ] The WFS validation is running into a time out (tried two times - behavior is the same)
- [ ] a screenshot illustrating the problem 
![grafik](https://user-images.githubusercontent.com/34163838/145037151-6f6bac46-b473-4f19-840f-fe644f7e87ae.png)
As the feedback is "Please contact the system administrator if the problem persists." I create this ticket now.
Please let me know if I need to contact the OGC Team Engine instead.

**Comment by arantzaetxebarria** [comment]
Dear @JohannaOtt

This error comes directly from the OGC validator. As you have commented, could you please report this issue directly to the OGC? 

Thanks

**Comment by JohannaOtt** [comment]
@arantzaetxebarria I can report it to the OGC once I can reproduce the behavior - this is currently not possible because of https://github.com/INSPIRE-MIF/helpdesk-validator/issues/670

**Comment by JohannaOtt** [comment]
I created https://github.com/opengeospatial/ets-wfs20/issues/217 for it

**Comment by fabiovinci** [comment]
Since the related issue on the OGC repo has been closed because the problem appears to be with the WFS instance, I will close also this issue.
@JohannaOtt, please reopen it or open a new one if necessary.
