### ISSUE TITLE
Failed: HTTP status code 200 is returned

### ISSUE THREAD

**Issue by MxxTxx** [INSPIRE-MIF/helpdesk-validator#674]
**A description of the steps to reproduce your issue**
I would like to validate resource https://gis.nature.cz/inspire/atom/atom.xml, but I repeatedly get errors in the section "HTTP status code 200 is returned". Sometimes this error occurs at https://gis.nature.cz/inspire/atom/atom.xml, sometimes later at https://gis.nature.cz/inspire/atom/osd.xml as shown in the image. The resource remained unchanged.
I have no permission to see the content of "Open saved response".

**The browser and version used**
Chrome 96.0.4664.45 64bit

**Screenshot illustrating the problem**
![Validator01](https://user-images.githubusercontent.com/95758237/145224149-c6acca47-fd1b-4fa4-b109-cc41773d903d.png)

**The Test Report (ideally as an attachment to the issue)**
[Test run on 14_29 - 08.12.2021 with test suite Conformance Class Pre-defined Atom.zip](https://github.com/INSPIRE-MIF/helpdesk-validator/files/7676616/Test.run.on.14_29.-.08.12.2021.with.test.suite.Conformance.Class.Pre-defined.Atom.zip)

**The Test that failed**
https://yzyiqfakm4.execute-api.eu-west-1.amazonaws.com/validator//v2/TestRuns/EID78cbf115-6330-4043-adc2-eccfabbf5878.html?lang=cs#EID9a3c6569-017d-1000-3bdc-479ec8a7c847

**The URL of your service / the file you have uploaded or referenced (as an attachment).**
https://gis.nature.cz/inspire/atom/atom.xml

**Comment by jenriquesoriano** [comment]
Dear @MxxTxx  , 

thanks for pointing the issue. 
We are analyzing it in detail, but the exceptions caused seems to be produced due to exceptions related with the URLs.
![imagen](https://user-images.githubusercontent.com/25343632/151983451-737b0ade-1165-480d-b9d8-304cdac05329.png)

We need to look deeper in the case to provide you with further details.
We will keep you posted.

Best regards.

**Comment by jenriquesoriano** [comment]
Dear @MxxTxx , 

issues with the urls for the provided resources have been checked and seem no longer present.
Thus, we consider this issue to be solved.

Please let us know if you confirm it works fine.

Best regards,

**Comment by fabiovinci** [comment]
Dear @MxxTxx,

it seems the reported error is no longer present, see the related [report](https://github.com/INSPIRE-MIF/helpdesk-validator/files/14438087/Test.run.on.18_29.-.28.02.2024.with.test.suite.Conformance.Class.Pre-defined.Atom.-.IOS.674.html.zip).

We will close the issue, please reopen it or open a new issue if the problem persists.
