### ISSUE TITLE
Are there any restrictions on the number of concurrent tests started in the INSPIRE validator?

### ISSUE THREAD

**Issue by Kate-Lyndegaard** [INSPIRE-MIF/helpdesk-validator#678]
Hi,

I would like to know if there are any restrictions on the number of concurrent tests started, or running, in the INSPIRE validator at one time.

Kind regards,
Kate

**Comment by jenriquesoriano** [comment]
Dear @Kate-Lyndegaard

the maximum number of concurrent tests is 4 in the production instance and 2 in the staging instance.
You can see it in the [list of known limitations](https://github.com/INSPIRE-MIF/helpdesk-validator/wiki/Known-limitations).

Regards,

**Comment by Kate-Lyndegaard** [comment]
Dear @jenriquesoriano,

Thank you very much for your response. I will take a look at the list.

Kind regards,
Kate
