### ISSUE TITLE
File upload not possible

### ISSUE THREAD

**Issue by JohannaOtt** [INSPIRE-MIF/helpdesk-validator#68]
Hi everybody,

Currently, I cannot upload a file to the validator at http://inspire.ec.europa.eu/validator/ - neither zipped (1.2 MB) nor unzipped (5 MB).
Did anything change on maximum size of the file etc. with the latest updates?

Thank you in advance

Johanna

**Comment by carlospzurita** [comment]
Hi @JohannaOtt could you provide the files you are trying to upload? To try and replicate the error. Thank you very much.

**Comment by JohannaOtt** [comment]
Hi @carlospzurita the data is condifential. Could you please indicate an e mail address I can send it to?

**Comment by carlospzurita** [comment]
You can send it to carlospalma@guadaltel.com

**Comment by carlospzurita** [comment]
We have upped the maximum upload size to 20MB on the new production instance, and now the file can be uploaded without any issue. You can check it on http://inspire.ec.europa.eu/validator/

**Comment by JohannaOtt** [comment]
Hi Carlos,
Great, thank you! I tested and could upload the file.
