### ISSUE TITLE
AcceptLanguages Recommendation Mandatory?

### ISSUE THREAD

**Issue by KathiSchleidt** [INSPIRE-MIF/helpdesk-validator#683]
We've finally added all the bells and whistles required by INSPIRE for WCS to rasdaman (<inspire_dls:ExtendedCapabilities> provided in <ows:ExtendedCapabilities>, Elevation Data Model reworked for WCS provision), but get an error when validating the download service based on the lack of support for the ACCEPTLANGUAGES in the GetCapabilities Request.

While the WCS TG provide Recommendations pertaining to Languages, to my understanding Recommendations are not legally binding, thus should not lead to an error. Relevant is the following Recommendation:

TG Recommendation 1 Services **should** support language negotiation of the WCS response through the HTTP header.

This pertains to the following WCS endpoint:

https://coverage-demo.wetransform.eu/rasdaman/ows?SERVICE=WCS&VERSION=2.0.1&REQUEST=GetCapabilities

When ACCEPTLANGUAGES is added to the GetCapabilities request, the server responds with an ExceptionText "Parameter 'acceptlanguages' is not valid in request." - to my understanding a valid response. Pertains to the following request URL:

https://coverage-demo.wetransform.eu/rasdaman/ows?ACCEPTLANGUAGES=eng&ACCEPTVERSIONS=2.0.1%2C2.0.0&REQUEST=GetCapabilities&SERVICE=WCS

The error appear in the validator response section
Conformance Class: Download Service - WCS Core
-> Service_Metadata
-> at03-natural-language-fields
-> manual-check
-> Valid HTTP Status Codes

Especially strange is that while this test claims to check the HTTP Status Code, and the request returns 200, this is still marked as invalid.

So - is Recommendation 1 from the WCS TG actually a requirement, or is the validator confused, or am I confused?

Many thanks!

**Comment by arantzaetxebarria** [comment]
Dear @KathiSchleidt 

We are going to leave the **at03-natural-language-fields** only as a manual check and remove the test step _Valid HTTP Status Codes_. 
Also, the [ATS](https://github.com/inspire-eu-validation/download-wcs/blob/1.0/wcs-core/at03-natural-language-fields.md) related to the requirement has been updated as AcceptLanguages parameter is optional, as indicated in Table 15 of the WCS TG
![image002](https://user-images.githubusercontent.com/64014694/177958053-5f32ba70-a0b4-449c-9f52-7a4105aaecb7.png)

When the changes will be implemented in staging environment, we will back to you.

Regards

**Comment by arantzaetxebarria** [comment]
Dear @KathiSchleidt 

The fix is present in staging environment, could you please test it and confirm us if it is ok? Thanks.

Regards

**Comment by KathiSchleidt** [comment]
Dear @arantzaetxebarria,

Fear we're now ahead of you - as we didn't receive a response on this (and realized that the AcceptLanguages parameter is defined by OWS common (OGC 06-121r9) version 2, and it is the GetCapabilities operation (Clause 7) of this version of OWS common that WCS 2.0 should conform to.), we decided to do things right and implement this within rasdaman.

Thus, to our knowledge, rasdaman WCS is the first product to be validated as an INSPIRE complaint Download Service, fully following the requirements laid down for INSPIRE Download Services.

Details at: https://www.geoconnexion.com/news/rasdaman-validated-as-inspire-compliant-wcs

Many thanks!

**Comment by fabiovinci** [comment]
Dear @KathiSchleidt,

since the AcceptLanguages parameter is optional, we think the change we introduced is needed.

Could you please test the fix in the staging instance and provide your feedback?

Thanks!

**Comment by KathiSchleidt** [comment]
@fabiovinci not sure how I can help you as our [WCS](https://inspire.rasdaman.org/rasdaman/ows?SERVICE=WCS&VERSION=2.0.1&REQUEST=GetCapabilities) validates, don't have the time to deploy an old version for this test.

**Comment by KathiSchleidt** [comment]
@fabiovinci I've gone through the various rasdaman deployments, found one that hasn't been updated yet. The following WCS still shows the AcceptLanguages error under the normal validator (I don't have access to the staging instance you mention):

https://coverage-demo.wetransform.eu/rasdaman/ows?SERVICE=WCS&VERSION=2.0.1&REQUEST=GetCapabilities

**Comment by fabiovinci** [comment]
Dear @KathiSchleidt,

thank you for your feedback.

I validated the "old" WCS in the [staging instance](http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/home/index.html) and there is no error for the _at03-natural-language-fields_ test, [see the report](http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/test-run/details.html?id=EIDc3b0dd3d-c7c3-4d0a-8e86-d37aa9753811).

**Comment by fabiovinci** [comment]
The fix for this issue will be included in the next release.
