### ISSUE TITLE
Certification Path Error

### ISSUE THREAD

**Issue by kevin-wilhelm-lgrb** [INSPIRE-MIF/helpdesk-validator#686]
Test of our Download Services (WFS) provided via remote file i.e.

https://services-test.lgrb-bw.de/m4eu/services/m4eu_v2020.8?REQUEST=GetCapabilities&SERVICE=WFS&VERSION=2.0.0

fail.

Browser:
- Firefox 88.0.1

Configuration of the Validator:
- Download Service
- Version 2.0
- data sets and data set series

JSON response of the validator:
{
	"error": "unable to find valid certification path to requested target",
	"timestamp": "1642059079809",
	"url": "http://inspire-validator.eu-west-1.elasticbeanstalk.com:8080/validator/v2/TestRuns",
	"stacktrace": [
		"sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target",
		"\tat sun.security.provider.certpath.SunCertPathBuilder.build(SunCertPathBuilder.java:146)",
		"\tat sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:131)",
		"\tat java.security.cert.CertPathBuilder.build(CertPathBuilder.java:280)",
		"\tat sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:382)",
		" [wrapped] sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target",
		"\tat sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:387)",
		"\tat sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:292)",
		"\tat sun.security.validator.Validator.validate(Validator.java:260)",
		"\tat sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:324)",
		"\tat sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:229)",
		"\tat sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:124)",
		"\tat sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1491)",
		" [wrapped] javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target",
		"\tat sun.security.ssl.Alerts.getSSLException(Alerts.java:192)",
		"\tat sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1949)",
		"\tat sun.security.ssl.Handshaker.fatalSE(Handshaker.java:302)",
		"\tat sun.security.ssl.Handshaker.fatalSE(Handshaker.java:296)",
		"\tat sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1509)",
		"\tat sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:216)",
		"\tat sun.security.ssl.Handshaker.processLoop(Handshaker.java:979)",
		"\tat sun.security.ssl.Handshaker.process_record(Handshaker.java:914)",
		"\tat sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1062)",
		"\tat sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1375)",
		"\tat sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1403)",
		"\tat sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1387)",
		"\tat sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:559)",
		"\tat sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)",
		"\tat sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1513)",
		"\tat sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1441)",
		"\tat java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)",
		"\tat sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:338)",
		"\tat de.interactive_instruments.UriUtils.followRedirects(UriUtils.java:902)",
		"\tat de.interactive_instruments.UriUtils.openHttpGetConnection(UriUtils.java:876)",
		"\tat de.interactive_instruments.UriUtils.proposeFilename(UriUtils.java:730)",
		"\tat de.interactive_instruments.etf.webapp.dto.SimpleTestObject.toTestObject(SimpleTestObject.java:126)",
		"\tat de.interactive_instruments.etf.webapp.dto.StartTestRunRequest.toTestRun(StartTestRunRequest.java:114)",
		"\tat de.interactive_instruments.etf.webapp.controller.TestRunController.start(TestRunController.java:474)",
		" [wrapped] de.interactive_instruments.etf.webapp.controller.LocalizableApiError: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target",
		"\tat de.interactive_instruments.etf.webapp.controller.TestRunController.start(TestRunController.java:521)",
		"\tat sun.reflect.GeneratedMethodAccessor189.invoke(Unknown Source)",
		"\tat sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)",
		"\tat java.lang.reflect.Method.invoke(Method.java:497)",
		"\tat org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)",
		"\tat org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:133)",
		"\tat org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:97)",
		"\tat org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:827)",
		"\tat org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:738)",
		"\tat org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)",
		"\tat org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:967)",
		" [wrapped] org.springframework.web.util.NestedServletException: Handler dispatch failed; nested exception is de.interactive_instruments.etf.webapp.controller.LocalizableApiError: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target",
		"\tat org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:982)",
		"\tat org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:901)",
		"\tat org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)",
		"\tat org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:872)",
		"\tat javax.servlet.http.HttpServlet.service(HttpServlet.java:707)",
		"\tat org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)",
		"\tat javax.servlet.http.HttpServlet.service(HttpServlet.java:790)",
		"\tat org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:821)",
		"\tat org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1685)",
		"\tat de.interactive_instruments.etf.webapp.filter.ApiFilter.doFilterInternal(ApiFilter.java:89)",
		"\tat org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)",
		"\tat org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:347)",
		"\tat org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:263)",
		"\tat org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1668)",
		"\tat org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:581)",
		"\tat org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)",
		"\tat org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)",
		"\tat org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:226)",
		"\tat org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1158)",
		"\tat org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:511)",
		"\tat org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)",
		"\tat org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1090)",
		"\tat org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)",
		"\tat org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:213)",
		"\tat org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:109)",
		"\tat org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:119)",
		"\tat org.eclipse.jetty.server.Server.handle(Server.java:517)",
		"\tat org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:308)",
		"\tat org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:242)",
		"\tat org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:261)",
		"\tat org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)",
		"\tat org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:75)",
		"\tat org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceAndRun(ExecuteProduceConsume.java:213)",
		"\tat org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:147)",
		"\tat org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:654)",
		"\tat org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:572)",
		"\tat java.lang.Thread.run(Thread.java:745)"
	]
}

**Comment by jenriquesoriano** [comment]
Dear @kevin-wilhelm-lgrb , 

thank you for pointing the issue.
It seems that this issue is caused due to the certificate is not added to the repository.
Could you provide us with your organization certificate in order to add it?
Thank you in advance. 

Best,

**Comment by kevin-wilhelm-lgrb** [comment]
Dear @jenriquesoriano ,
thank you very much for your answer. I uploaded our certificates (one for our test server and one for the productive system) here. I hope this works. Thank you for adding certificates and providing help.
Best regards

[certificates.zip](https://github.com/INSPIRE-MIF/helpdesk-validator/files/8078249/certificates.zip)

**Comment by jenriquesoriano** [comment]
Dear @kevin-wilhelm-lgrb  ,

thanks for providing us with the certificates. 
We start the process to incorporate them to the instances and keep you updeted with the process.

Best,

**Comment by jenriquesoriano** [comment]
Dear @kevin-wilhelm-lgrb 

we have downloaded and installed the following certificatesin the staging environment:
- [cert1] services-lgrb-bw-de.crt
- [cert2] services-test-lgrb-bw-de.crt

Unfortunately, we did not get the wfs service to be run by the Validator, as the certificate issue was still present with the provided certificates.

Then, just for testing purposes, we installed:
- [cert3] the certificate obtained from the wfs service indicated in the issue 

and the service provided for the issue was run by the Validator.

Currently, cert1, cert2 and cert3 are installed in staging.

We would like to know if it is necessary to keep cert1 and cert2, since only cert3 would be needed to run the validation for the service subject of the issue.

Thank you very much.

Best regards,

**Comment by jenriquesoriano** [comment]
Dear @kevin-wilhelm-lgrb , 

did you have the chance to check our last comment?
Please let us know which certificates are actually needed, so we could include them in the Production Instance for the next release (v2022.1) to happen by mid-March.

Best regards

**Comment by kevin-wilhelm-lgrb** [comment]
Dear @jenriquesoriano ,
thank you very much for installing our certificates in the staging environment. For the productive environment please use cert3 as certificate to install. Thank you very much. To whom may I get in touch, concerning validation errors?
Best regards

**Comment by jenriquesoriano** [comment]
Dear @kevin-wilhelm-lgrb , 

well noted, we will include cert3 in the next release.
With regard to validation errors, according to the instructions provided in this repository, please feel free to use the issue tracker (helpdesk) to:
- [report a problem](https://github.com/INSPIRE-MIF/helpdesk-validator/issues/new?template=problem.md) with the INSPIRE validator or test results,
- [propose a new feature or an improvement](https://github.com/INSPIRE-MIF/helpdesk-validator/issues/new?template=improvement-proposal.md) to the existing functionality of the INSPIRE validator, or
- [start a discussion or raise a question](https://github.com/INSPIRE-MIF/helpdesk-validator/issues/new?template=discussion.md)  on the INSPIRE validator

Regards,
