### ISSUE TITLE
Metadata fail for Spatial Data Set Category

### ISSUE THREAD

**Issue by Ana-SGA** [INSPIRE-MIF/helpdesk-validator#694]
Dear all,

metadata for network services which have previously passed the test, now fail for Spatial Data Set Category (xml attached). The same metadata on staging instance passes the test regularly.
[1173.zip](https://github.com/INSPIRE-MIF/helpdesk-validator/files/7939906/1173.zip)

**Comment by arantzaetxebarria** [comment]
Dear @Ana-SGA 

We are going to analyze the issue, we will come back to you once we have a response.

Regards,

Arantza

**Comment by arantzaetxebarria** [comment]
Dear @Ana-SGA 

This issue is currently solved. Could you please verify and confirm for us that all is correct, please?

Best regards,

Arantza

**Comment by Ana-SGA** [comment]
Dear @arantzaetxebarria ,

seems ok now, thanks for solving the problem.

Kind regards,
Ana
