### ISSUE TITLE
Dataset validation is running into an internal server error

### ISSUE THREAD

**Issue by JohannaOtt** [INSPIRE-MIF/helpdesk-validator#695]
When trying to validate a dataset (22 MB, 1 MB zipped), I get an internal server error. The same happened for another dataset (31 MB, 2 MB zipped) before but in the first case, the test eventually started at the first try (still running so I cannot tell if it also finishes).
The second one keeps on running into the error.

- [ ] tried to validate a dataset against TN-RA
- [ ] Firefox 96.0.2 on Windows 10
- [ ] ![grafik](https://user-images.githubusercontent.com/34163838/151137794-8226bf16-7675-4b20-81a6-a317f46ae936.png)
- [ ] ![grafik](https://user-images.githubusercontent.com/34163838/151137732-6af81823-c4ca-4790-a452-99a87a39c045.png)

All the best

Johanna

**Comment by dperezBM** [comment]
Dear @JohannaOtt,

Thank you for your message. We are going to analyze the issue, we will come back to you once we have a response.

Best regards

**Comment by dperezBM** [comment]
Dear @JohannaOtt,

Is it possible to provide us the example you are trying to upload?
Also, could you confirm if you are using the staging or production environment?

Thanks

**Comment by JohannaOtt** [comment]
@dperezBM When not adding any information about the environment, my reports are concerning the production environment (I except that to be the default used).
I cannot reproduce the issue right now so I will close this issue and open a new one if it happens again.
