### ISSUE TITLE
Metadata dataset: Keyword originating CV (C.15)

### ISSUE THREAD

**Issue by idevisser** [INSPIRE-MIF/helpdesk-validator#70]
I got unexpected errors with the md common requirement C.15

Comment;
The dates are provided for the keywords with a CV

The messages 

The metadata record set has 1 record(s) with errors for this assertion.
XML document 'test dataset.xml', record 'C2DFBDBC-5092-11E0-BA8E-B62DE0D72085': The metadata record has keywords which originate from a controlled vocabulary '{thesaurus}', but no date of publication, creation, or revision is provided. The keywords are: {keywords}.
XML document 'test dataset.xml', record 'C2DFBDBC-5092-11E0-BA8E-B62DE0D72085': The codeList attribute is not correct.
XML document 'test dataset.xml', record 'C2DFBDBC-5092-11E0-BA8E-B62DE0D72085': The codeList attribute is not correct.
XML document 'test dataset.xml', record 'C2DFBDBC-5092-11E0-BA8E-B62DE0D72085': The metadata record has keywords which originate from a controlled vocabulary '{thesaurus}', but no date of publication, creation, or revision is provided. The keywords are: {keywords}.

XML sniplet
			<gmd:descriptiveKeywords>
				<gmd:MD_Keywords>
					<gmd:keyword>
					
						<gco:CharacterString>Beschermde gebieden</gco:CharacterString>
					</gmd:keyword>
					<gmd:keyword>
						<gco:CharacterString>Habitats en biotopen</gco:CharacterString>
					</gmd:keyword>
					<gmd:thesaurusName>
					
						<gmd:CI_Citation>
							<gmd:title>
								<gco:CharacterString>GEMET - INSPIRE themes, version 1.0</gco:CharacterString>
							</gmd:title>
							<gmd:date>
								<gmd:CI_Date>
									<gmd:date>
										<gco:Date>2008-06-01</gco:Date>
									</gmd:date>
									<gmd:dateType>
										<gmd:CI_DateTypeCode codeList="http://www.isotc211.org/2005/resources/Codelist/gmxCodelists.xml#CI_DateTypeCode" codeListValue="creation"/>
									</gmd:dateType>
								</gmd:CI_Date>
							</gmd:date>
						</gmd:CI_Citation>
					</gmd:thesaurusName>
				</gmd:MD_Keywords>
				</gmd:descriptiveKeywords>
				
			<gmd:descriptiveKeywords>
				<gmd:MD_Keywords>
					<gmd:keyword>
						<gmx:Anchor xlink:href="http://inspire.ec.europa.eu/metadata-codelist/SpatialScope/national">Nationaal</gmx:Anchor>
					</gmd:keyword>
					<gmd:thesaurusName>
						<gmd:CI_Citation>
							<gmd:title>
								<gmx:Anchor xlink:href="http://inspire.ec.europa.eu/metadata-codelist/SpatialScope">Ruimtelijke dekking</gmx:Anchor>
							</gmd:title>
							<gmd:date>
								<gmd:CI_Date>
									<gmd:date>
										<gco:Date>
											2018-04-04
										</gco:Date>
									</gmd:date>
									<gmd:dateType>
										<gmd:CI_DateTypeCode codeListValue="publication" codeList="http://www.isotc211.org/2005/resources/Codelist/gmxCodelists.xml#CI_DateTypeCode"/>
									</gmd:dateType>
								</gmd:CI_Date>
							</gmd:date>
						</gmd:CI_Citation>
					</gmd:thesaurusName>
				</gmd:MD_Keywords>
			</gmd:descriptiveKeywords>
		
			
			<gmd:descriptiveKeywords>
				<gmd:MD_Keywords>
					<gmd:keyword>
						<gmx:Anchor xlink:href="http://inspire.ec.europa.eu/metadata-codelist/PriorityDataset/HabitatTypesRange-dir-1992-43">Verspreidingsgebied van habitattypen (Habitatrichtlijn)</gmx:Anchor>
					</gmd:keyword>
					<gmd:thesaurusName>
						<gmd:CI_Citation>
							<gmd:title>
								<gmx:Anchor xlink:href="http://inspire.ec.europa.eu/metadata-codelist/PriorityDataset">INSPIRE prioritaire dataset</gmx:Anchor>
							</gmd:title>
							<gmd:date>
								<gmd:CI_Date>
									<gmd:date>
										<gco:Date xmlns:gco="http://www.isotc211.org/2005/gco">
											2018-04-04
										</gco:Date>
									</gmd:date>
									<gmd:dateType>
										<gmd:CI_DateTypeCode codeListValue="publication" codeList="http://www.isotc211.org/2005/resources/Codelist/gmxCodelists.xml#CI_DateTypeCode"/>
									</gmd:dateType>
								</gmd:CI_Date>
							</gmd:date>
						</gmd:CI_Citation>
					</gmd:thesaurusName>
				</gmd:MD_Keywords>
			</gmd:descriptiveKeywords>
			
				<gmd:descriptiveKeywords>
				<gmd:MD_Keywords>
					<gmd:keyword>
						<gco:CharacterString>Trefwoorden uit een andere thesaurus</gco:CharacterString>
					</gmd:keyword>
					<gmd:thesaurusName>
						<gmd:CI_Citation>
							<gmd:title>
								<gco:CharacterString>GEMET </gco:CharacterString>
							</gmd:title>
							<gmd:date>
								<gmd:CI_Date>
									<gmd:date>
										<gco:Date>2000-12-13</gco:Date>
									</gmd:date>
									<gmd:dateType>
										<gmd:CI_DateTypeCode codeList="http://www.isotc211.org/2005/resources/Codelist/gmxCodelists.xml#CI_DateTypeCode" codeListValue="creation"/>
									</gmd:dateType>
								</gmd:CI_Date>
							</gmd:date>
						</gmd:CI_Citation>
					</gmd:thesaurusName>
				</gmd:MD_Keywords>
			</gmd:descriptiveKeywords>
			<gmd:descriptiveKeywords>
				<gmd:MD_Keywords>
					<gmd:keyword>
						<gco:CharacterString>Trefwoord zonder thesaurus</gco:CharacterString>
					</gmd:keyword>
					<gmd:keyword>
						<gco:CharacterString>Tweede trefwoord zonder thesaurus</gco:CharacterString>
					</gmd:keyword>
				</gmd:MD_Keywords>
			</gmd:descriptiveKeywords>

**Comment by josemasensio** [comment]
Hi @idevisser,

Could you provide the file you are testing? To try and replicate the errors. 

Thank you very much.

**Comment by josemasensio** [comment]
@idevisser after reviewing the ATS of [Keyword Originating CV](https://github.com/inspire-eu-validation/metadata/blob/2.0/metadata%20TG%202.0/common/keyword-originating-cv.md) and the [inspire-tg-metadata-iso19139-2.0.1](https://inspire.ec.europa.eu/sites/default/files/documents/metadata/inspire-tg-metadata-iso19139-2.0.1.pdf) (page 41), in both it is said that 'the Date Type element exists and it has an attribute codeList with "http://standards.iso.org/iso/19139/resources/gmxCodelists.xml#CI_DateTypeCode" and an attribute codeListValue with value "publication"'.

So you should change the values of the codeList and codeListValue attributes in gmd:CI_DateTypeCode elements to solve the error.

**Note**: The validator displays a incorrect message "The metadata record has keywords which originate from a controlled vocabulary '{thesaurus}', but no date of publication, creation, or revision is provided", the message must be "The metadata record has keywords which originate from a controlled vocabulary '{thesaurus}', but no date of publication is provided". We will correct this.

Best regards.

**Comment by idevisser** [comment]
Yes that seems to be a better message.
For the discussion about the codelist attribute see #69

**Comment by josemasensio** [comment]
Dear @idevisser, 

We have changed the error message. We will appreciate if you could test it and give us some feedback. You can test this in the staging environment.

Best regards.

**Comment by MarcoMinghini** [comment]
**2017.4 meeting 2019-07-17**

- The solution regarding the ISO code list is the one agreed in #69, i.e. the Validator should only check the value of the `codeListValue `attribute, and not the value of the `codeList `attribute.

**Comment by josemasensio** [comment]
Dear @idevisser,

We relaxed the test so now you will have not problems with the codeList attribute.

Regards.

**Comment by josemasensio** [comment]
Dear @idevisser,

Does this solution worked?

Regards.

**Comment by fxprunayre** [comment]
> We have changed the error message.

Not sure in which branch it has been fixed, but on master, yesterday the `{thesaurus}` placeholder was not replaced. This can be cherry picked from https://github.com/inspire-eu-validation/ets-repository/pull/315/commits/3f2573cbb77be7a2ddc2e52f63a03faf188706b3 (relates to https://github.com/inspire-eu-validation/ets-repository/pull/315)

**Comment by josemasensio** [comment]
Dear @fxprunayre,

We apply the changes on [staying instance](http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/). We fix the issues here and once confirmed that is solved, it will be merged with master on the next update.

Regards.

**Comment by fxprunayre** [comment]
> We apply the changes on [staying instance](http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/)

Great thanks. And where is the source of this instance ? so that we can locally test too.

**Comment by josemasensio** [comment]
Dear @fxprunayre,

You have the source code on the [staging branch](https://github.com/inspire-eu-validation/ets-repository/tree/staging).

Best regards.

**Comment by josemasensio** [comment]
Afert some internal tests, we checked that everything is working fine, so we will mark as solved this issue.

Regards.
