### ISSUE TITLE
Gateway Timeout and Conflict when trying to run LandCover validation

### ISSUE THREAD

**Issue by JohannaOtt** [INSPIRE-MIF/helpdesk-validator#700]
When trying to validate a LandCover dataset (42 MB, 10 MB zipped) against the Land Cover dataset testsuite, I got a GatewayTimeout at the first try and Conflicts at the second and third try:
![grafik](https://user-images.githubusercontent.com/34163838/151314019-eb112626-c3ee-41d9-9ec6-e64615afd8a5.png)

To help us investigate the issue, you may want to include:

- [ ] Firefox 96.0.2 on Windows 10
- [ ] ![grafik](https://user-images.githubusercontent.com/34163838/151314211-3709b526-b002-4e9d-a0af-2fd5a1b2cece.png)

All the best

Johanna

**Comment by jenriquesoriano** [comment]
Dear @JohannaOtt , 

thanks for raising this issue.
As we can see from your screenshots, this issue is happening in the production instance. 
Could we have the uploaded dataset in order to reproduce the behaviour?

Thanks a lot.

Best regards,

**Comment by JohannaOtt** [comment]
@jenriquesoriano Please find the dataset attached
[he_inspire_lcv_alkis_25832-10_10th.zip](https://github.com/INSPIRE-MIF/helpdesk-validator/files/7979995/he_inspire_lcv_alkis_25832-10_10th.zip)

**Comment by arantzaetxebarria** [comment]
Hi @JohannaOtt 

It seems that now the production environment is working correctly, could you please verify and confirm us? Thanks

Regards

**Comment by JohannaOtt** [comment]
I can confirm that the data can be uploaded and the test can be started now but the test won't finish with a Gateway Timeout. It still seems to run according to the UI but for almost two hours now and the network analysis looks like there is an issue. 
![grafik](https://user-images.githubusercontent.com/34163838/153437853-c92d7f7c-e15a-446a-9203-d153e264f853.png)

**Comment by jenriquesoriano** [comment]
Dear @JohannaOtt 

if we are not wrong with the references, it seems that the test you are pointing finally managed to be completed, but it took about half an hour. We maybe wrong, so please let us know if this is the case. Please see:
![imagen](https://user-images.githubusercontent.com/25343632/153553673-711976c0-33c6-454e-94c1-fd0aceafb484.png)


Test report: 
https://inspire.ec.europa.eu/validator/test-reports/details.html?id=EID01a41e0b-3b42-4314-b666-329b3b236d91

Log file:
https://yzyiqfakm4.execute-api.eu-west-1.amazonaws.com/validator/v2/TestRuns/EID01a41e0b-3b42-4314-b666-329b3b236d91/log

Could you confirm it finally worked?

Analyzing your screenshot we would also reccomend to clean the browser cache, as it seems as a posibility that some "old" requests from previous versions of the UI could be made from your client.

Thanks a lot.

Best,

**Comment by JohannaOtt** [comment]
I ran the test again after cleaning the cache and can confirm that it is now finishing. The issue can be closed from my point of view.

**Comment by jenriquesoriano** [comment]
Dear @JohannaOtt , 

thanks a lot for your feedback.
We close the issue accordingly.

Best,
