### ISSUE TITLE
Gateway Timeout for WMS test

### ISSUE THREAD

**Issue by JohannaOtt** [INSPIRE-MIF/helpdesk-validator#701]
When trying to start a test run for a WMS, the validator is running into a Gateway Timeout and an error message is occurring.

- [ ] Using Firefox 96.0.2 on Windows 10
- [ ] 
![grafik](https://user-images.githubusercontent.com/34163838/151532814-fdb13249-1b36-4326-87ed-741c8457ae14.png)

All the best

Johanna

**Comment by jenriquesoriano** [comment]
Dear @JohannaOtt ,

thanks for raising this issue.
As we can see from your screenshots, this issue seems to happen in the production instance.
As we cannot reproduce the issue for a WMS url in general, could we have the WMS url that is causing the problem?

Thanks a lot.

Best regards,

**Comment by JohannaOtt** [comment]
I cannot reproduce the issue right now. I will open a new issue if I run into it again.
