### ISSUE TITLE
View services not fully tested in ETF Validator

### ISSUE THREAD

**Issue by petbod-lm** [INSPIRE-MIF/helpdesk-validator#703]
I am reviewing the ETF Validator reports for several view services published by Sweden.

I see that some WMS services only have the GetCapabilities_Operation test suite run by the ETF validator while another WMS services has 4 test suites run by the ETF validator (GetCapabilities_Operation, GetMap_Operation, LinkViewService_Operation and Language_Requirements).

A: The WMS service that only has the GetCapabilities_Operation suite run is 
https://maps.lantmateriet.se/capabilities/inspire/basemap/wms/v1?request=GetCapabilities&service=WMS&version=1.3.0 
(ETF Validator report: https://inspire.ec.europa.eu/validator/test-run/details.html?id=EIDbb945910-653f-4f69-8187-d8c8276f0ac7)

B: The WMS service that has all 4 test suites run is
http://maps.lantmateriet.se/capabilities/ortofoto/wms/v1.3?request=GetCapabilities&service=WMS&version=1.3.0
(ETF Validator report: https://inspire.ec.europa.eu/validator/test-run/details.html?id=EID0720b596-7d5a-4bf9-9f7d-587e7452b95f)

I have looked at the test suite logs and tests and I cannot see any error or exception that stops WMS service A from having the ETF suites run (GetMap_Operation, LinkViewService_Operation and Language_Requirements) compared to the test logs and results for WMS service B.

What prerequisite are these 3 test suites (GetMap_Operation, LinkViewService_Operation and Language_Requirements) depending on from the GetCapabilities_Operation suite?

Many thanks
/Pete

**Comment by arantzaetxebarria** [comment]
Dear @petbod-lm,

Thank you for your message. We are going to analyze the issue, we will come back to you once we have a response.

Best regards

**Comment by ghost** [comment]
Since moving to Geoserver 2.20.x with got this issue, the validation got to, and failed at, test AT47 (GetLegend) and seemingly stopped at that point.

**Comment by arantzaetxebarria** [comment]
Dear @petbod-lm 

One fix has been made against [618](https://github.com/INSPIRE-MIF/helpdesk-validator/issues/618) and it seems that this issue is also solved. Could you please verify [staging ](http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/home/index.html) environment and let us know if all is correct? Thanks

Regards,

Arantza

**Comment by petbod-lm** [comment]
I can confirm that all 4 test suites are now run for the view service when I test in Staging.
thank you for resolving this issue.
/Pete

**Comment by fabiovinci** [comment]
Dear @petbod-lm,

thank you for the confirmation. We will include this fix in the next release.
