### ISSUE TITLE
Add ICE as official language for the Metadata language element

### ISSUE THREAD

**Issue by fabiovinci** [INSPIRE-MIF/helpdesk-validator#706]
Since the addition of the Icelandic language (ICE), as one of the official languages of the Community, was endorsed by MIG (see the [related issue](https://github.com/INSPIRE-MIF/technical-guidelines/issues/5)), the language shall be included in the validator for test related to the TG Requirement C.5 - Metadata language.

@dperezBM, could you please add 'ice' in the list of the allowed languages for the test "md common req C.5: Language Code".

Thanks

**Comment by arantzaetxebarria** [comment]
Dear @fabiovinci 
The Icelandic language (ICE) has been added for the test "md common req C.5: Language Code", and it is in staging environment, could you please verify? Thanks

Regards,

Arantza

**Comment by fabiovinci** [comment]
Dear @arantzaetxebarria,

thank you for the fix, I tested it and it works fine.
We will include it in the next release.
