### ISSUE TITLE
Is the docker image for v2022.0 available?

### ISSUE THREAD

**Issue by dhdeangelis** [INSPIRE-MIF/helpdesk-validator#707]
Dear,

I have run into problems trying to get a docker image for the new version v2022.0 to be run locally. At the same time, I have no problems getting a new fresh docker image for the previous version. This is just to ask you if everything is ok on the repository or if there is a problem on my side. 

In particular, I am getting this error when trying to get the new image:
```
docker run --name inspire-validator -d -p 8080:8080 -v ~/etf:/etf docker.pkg.github.com/inspire-mif/helpdesk-validator/inspire-validator:2022.0
Unable to find image 'docker.pkg.github.com/inspire-mif/helpdesk-validator/inspire-validator:2022.0' locally
docker: Error response from daemon: manifest unknown.
See 'docker run --help'.
```

However, I do not get this problem if I get a new fresh docker image for the previous version:
```
docker run --name inspire-validator -d -p 8080:8080 -v ~/etf:/etf docker.pkg.github.com/inspire-mif/helpdesk-validator/inspire-validator:2021.3.1
Unable to find image 'docker.pkg.github.com/inspire-mif/helpdesk-validator/inspire-validator:2021.3.1' locally
2021.3.1: Pulling from inspire-mif/helpdesk-validator/inspire-validator
2bb30e6532d8: Pulling fs layer 
4f4fb700ef54: Pull complete 
5d495c685ae9: Pull complete 
a22cd4826027: Pull complete 
.....
```
In which case the image gets downloaded and can be run without problems.

I have logged out and in again to no avail.

Any suggestions?

Thanks in advance

Hernán

**Comment by JohannaOtt** [comment]
I have the same issues.

**Comment by kalxas** [comment]
same issue here, the image seems to be unavailable

**Comment by jenriquesoriano** [comment]
Dear @dhdeangelis , @JohannaOtt , @kalxas 

thanks for your feedback.
As you point, there is an issue in the repository, as the docker image is not available for download.
We will update the repository accordingly and come back to you as soon as it is ready.

Best regards,

**Comment by jenriquesoriano** [comment]
Dear all, 

we have just udated the repository with the corresponding image.
Please notice that we have also corrected the deployment intructions, due to since the incorporation of the INSPIRE Reference Validator new UI, the 8090 is used for the deployment of the interface.

```CMD
docker login docker.pkg.github.com 
#Provide Github credentials
docker run --name inspire-validator -d -p 8090:8090 -v ~/etf:/etf docker.pkg.github.com/inspire-mif/helpdesk-validator/inspire-validator:2022.0
#Launches a container with the image, exposing the UI in port 8090 through the same port in the host machine, and uses a volume in the local file system, on the directory ~/etf
```

Thus, you will have:

- localhost:8090/validator -> INSPIRE Reference Validator UI

Please, let us know if you encounter further issues so we can assist you in the process. 

Best regards,

**Comment by dhdeangelis** [comment]
Thank you, then instructions should read:

... _exposing it in port 80**9**0 through_ ...

**Comment by jenriquesoriano** [comment]
Thanks, noted (and edited accordingly) :)

**Comment by JohannaOtt** [comment]
Works for me now, thanks!

**Comment by jenriquesoriano** [comment]
Dear all, 

according to your positive feedback, we can consider this issue closed.
Thanks for your contribution and please excuse the inconvenience.

Best regards,
