### ISSUE TITLE
Cannot validate remote files bigger than 50 MB

### ISSUE THREAD

**Issue by danicgc** [INSPIRE-MIF/helpdesk-validator#708]
Dear team,

Since a few days I cannot validate **remote files** bigger than 50 MB, neither with Firefox nor Chrome... Past about 30 seconds from clicking the "Start test" button it shows only the message "An error has occured", without further explanation:

![20220209_inspire_validator_error_big_remote_files](https://user-images.githubusercontent.com/60217335/153147456-c937a3ac-0540-4ddc-acf5-c022855878b9.jpg)

The file I want to test is a statistical units vector data set:
https://datacloud.ide.cat/geodades/inspire-unitats-estadistiques/inspire-unitats-estadistiques-seccions-censals-2021-etrs89-geo.gml

Thanks,

**Comment by fabiovinci** [comment]
Dear @danicgc,

the limit (50 MB) should be the same also for the upload through the "Remote file" option.

Since your file exceeds the limit you could zip it and upload it through the "File upload" option.

**Comment by danicgc** [comment]
OK. Thanks
