### ISSUE TITLE
System error in the Executable Test Suite

### ISSUE THREAD

**Issue by StefanCiesilski** [INSPIRE-MIF/helpdesk-validator#712]
Before reporting an issue with the INSPIRE validator deployed at JRC, please check the [list of known limitations](https://github.com/INSPIRE-MIF/helpdesk-validator/wiki/Known-limitations).

Please replace these lines with a brief summary of your issue and the expected
behaviour.

To help us investigate the issue, you may want to include:

System error in the Executable Test Suite. Please contact a system administrator. Error information:[err:XPTY0004] Cannot return item()* as node(): $element_671. 
 (117/33)

- [ ] Validate BU3D 
- [ ] Firefox 91.6.0 esr
- [ ] [a screenshot illustrating the problem](https://yzyiqfakm4.execute-api.eu-west-1.amazonaws.com/validator/v2/TestRuns/EID5445871d-f957-4a1c-98e4-1430d4aa1670.html?lang=de)

- [ ] the name of the Test that failed or better: change the `Level of Detail`
- [ ] https://yzyiqfakm4.execute-api.eu-west-1.amazonaws.com/validator/v2/TestRuns/EID5445871d-f957-4a1c-98e4-1430d4aa1670.html?lang=de#EID6d69bdd5-7449-4dd6-9004-36885920598d

https://yzyiqfakm4.execute-api.eu-west-1.amazonaws.com/validator/v2/TestRuns/EID5445871d-f957-4a1c-98e4-1430d4aa1670.html?lang=de#EID98f89cf3-cdbb-4fff-aa11-9ecfd111f7a0

in the Report by clicking on `All Details`, then scroll down to the failed test
and copy the Link on the right-hand side of the `Assertion URI`
- [ ] the URL of your service / the file you have uploaded or referenced (as
an attachment).

If your service is protected or you have confidential data that you cannot
upload here, you can request an email address to which you can send URLs / files.
Please note that issues cannot be investigate
d for services/datasets that we cannot
access.

Data: 
[BU3D.zip](https://github.com/INSPIRE-MIF/helpdesk-validator/files/8124196/BU3D.zip)

**Comment by StefanCiesilski** [comment]
Data

**Comment by arantzaetxebarria** [comment]
Dear @StefanCiesilski 

After an analysis, we are going to fix this issue (bu-3d-as.a.3 and bu-3d-as.a.4) in the ETS, as soon as we have a solution in the staging environment we will back to you. Thanks

Regards,
Arantza

**Comment by arantzaetxebarria** [comment]
Dear @StefanCiesilski 

The solution for this issue is in [staging](http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/home/index.html) instance, could you please test it and verify? Once done, we would be grateful if you could let us know the result in order to add it to the new release. Thanks

Regards

**Comment by StefanCiesilski** [comment]
@arantzaetxebarria Super. It work.
