### ISSUE TITLE
URL redirection does not work in coupled ressources

### ISSUE THREAD

**Issue by oberseri** [INSPIRE-MIF/helpdesk-validator#713]
It seems that **URL redirection** to dataset metadata does not work properly in coupled ressources.

CR https://data.inspire.gv.at/0046/c901c0c6-4247-459a-b547-02fd134c5d22 causes an error in service 19d8c5af-8228-4b99-be0a-cfcbd382ff98 although correctly linking to dataset metadata.

[Test run on 10_19 - 24.02.2022 with test suite Conformance Class 4_ INSPIRE Network Services metadata.zip](https://github.com/INSPIRE-MIF/helpdesk-validator/files/8131646/Test.run.on.10_19.-.24.02.2022.with.test.suite.Conformance.Class.4_.INSPIRE.Network.Services.metadata.zip)

**Comment by fabiovinci** [comment]
Dear @oberseri,

could you please provide the link to the service metadata you tested, in order to reproduce the error?

Thanks

**Comment by oberseri** [comment]
Dear @fabiovinci,

the link to the service metadata is https://geometadatensuche.inspire.gv.at/metadatensuche/srv/api/records/19d8c5af-8228-4b99-be0a-cfcbd382ff98/formatters/xml, you can find relevant information within the attached validation file (zip).

Thanks, Erik

**Comment by fabiovinci** [comment]
Dear @oberseri,

thanks for the link, I tested it now and it is 100% valid ([see report](https://inspire.ec.europa.eu/validator/test-run/details.html?id=EID1214e14e-1ef1-43f5-812a-35d58c2d83d7)).
Could you please verify?

**Comment by oberseri** [comment]
Dear @fabiovinci,
I just tested 4 service md with URL redirections and they were all OK!
Did you change anything within the validator?
Thanks Fabio

**Comment by fabiovinci** [comment]
Dear @oberseri,

looking at the error message you received in your first validation, it seems the error is due to the temporary unavailability of the resource during the validation.

I confirm that we didn't change anything within the validator.

If you agree I will close the issue, feel free to reopen it if the error persists.

**Comment by oberseri** [comment]
Thanks again Fabio!
Yes please close the issue, I will keep an eye on that in future.
