### ISSUE TITLE
Simple features error 

### ISSUE THREAD

**Issue by ffarr2019** [INSPIRE-MIF/helpdesk-validator#715]
When passing the GML through the validator and i am prompted with a fail due to the simple features - image below.  This is related to "The feature geometry is not a valid GML geometry. Error detected: Invalid polygon. Inner ring of the polygon is counterclockwise within element ManagementRestrictionOrRegulationZone"

any suggestions on how to solve this, please.   If this error is not solved, how would this affect the indicators?

Thanks 

Frank

![simple_feature](https://user-images.githubusercontent.com/32981299/155662872-fc3d77d6-758f-4604-b56a-71f5317b3559.JPG)

**Comment by JohannaOtt** [comment]
If your data is using a left-handed CRS, you might have run into [this issue](https://github.com/inspire-eu-validation/ets-repository/issues/60)

**Comment by ffarr2019** [comment]
Thanks

**Comment by fabiovinci** [comment]
Dear @ffarr2019,

as reported by JohannaOtt, this is an old bug and the solution still needs to be integrated.

You can ignore it, for the moment.
