### ISSUE TITLE
Source code for the webapp

### ISSUE THREAD

**Issue by hwbllmnn** [INSPIRE-MIF/helpdesk-validator#721]
Hi,

I'd like to know where to find the source of the etf-webapp used in the validator (version 2022.0)? I found a fork at https://github.com/guadaltel/etf-webapp , is that the right repo? It seems that it's not the `master` branch that is used (I have a stack trace that doesn't fit the line numbers). I found the branches `latest` and `next`, is it one of these or another branch?

Thanks, Andreas

**Comment by jenriquesoriano** [comment]
Dear @hwbllmnn ,

the source code used for the compilation of the etf-webapp present in the v2022.0 release can be found in this branch:
https://github.com/guadaltel/etf-webapp/tree/ogc-api

Hope it helps.
If you have further questions, please let us know.

Best regards,

**Comment by hwbllmnn** [comment]
Yes that helps, thanks!
