### ISSUE TITLE
File master.zip not found by Docker entrypoint script

### ISSUE THREAD

**Issue by juanluisrp** [INSPIRE-MIF/helpdesk-validator#723]
In the `docker-entrypoint.sh` file of the `ghcr.io/inspire-mif/helpdesk-validator/inspire-validator:2022.0` Docker image, when starting the container this error is displayed:
```
+ rm master.zip
rm: cannot remove ‘master.zip’: No such file or directory
```

This is part of this code:
```bash
  if [ -d "$ETF_DIR"/projects/"$ETF_DL_TESTPROJECTS_DIR_NAME" ]; then
    echo "Using existing Executable Test Suites, skipping download"
  else
  	echo "Downloading Executable Test Suites"
    wget -q "$ETF_DL_TESTPROJECTS_ZIP" -O projects.zip
    mkdir -p "$ETF_DIR"/projects/"$ETF_DL_TESTPROJECTS_DIR_NAME"
    unzip -o projects.zip -d "$ETF_DIR"/projects/"$ETF_DL_TESTPROJECTS_DIR_NAME"
    rm master.zip
  fi
```

I guess that the right file to delete is `projects.zip` and not `master.zip` that actually doesn't exist.

**Comment by jenriquesoriano** [comment]
Dear @juanluisrp 

thank you very much for your contribution and for pointing out this issue in the dockerfile deployment.
As you rightly comment, this deletion refers to the previously unzipped file.
We take note for the next release (coming soon), where we will address this issue.

Regards,

**Comment by jenriquesoriano** [comment]
Dear @juanluisrp 

the docker-entrypoint.sh file has been updated accordingly.
Thanks for your contribution.

Best regards
