### ISSUE TITLE
Error when Uploading XML file to Test selection

### ISSUE THREAD

**Issue by jmbizfac** [INSPIRE-MIF/helpdesk-validator#724]
Hello together,

when i try to upload a file to start a test, i get the a popup with the following error message:

ERROR
An error has occured uploading file (Code: 502 - Bad Gateway)

The console throws following errors

<img width="541" alt="image" src="https://user-images.githubusercontent.com/101200562/157821442-54d406bd-1c59-45a9-9a28-c224fb252f95.png">

Uncaught TypeError: e.target.files.forEach is not a function in ecl-ec-preset-website.js:2

Steps to reproduce:

- I downloaded the .ZIP version 2022.0, and executed the build and run command as described here (https://github.com/INSPIRE-MIF/helpdesk-validator/releases)
- At http://localhost:8090/validator/test-selection/index.html I selected "Metadata -> Version 2.0 -> Data sets and data set series" and tried to upload a .XML file with the size of 68 KB

For any hint or suggestion i am more than thankful 🙏

**Comment by jenriquesoriano** [comment]
Dear @jmbizfac , 

thanks for your feedback.
Could you provide us with the .xml file which is causing the issue, so we can try to reproduce it locally?
Thanks a lot.

Best regards,

**Comment by jmbizfac** [comment]
Dear @jenriquesoriano,

thank you very much for your quick answer. Attached you can find the file i tried, i got it from https://github.com/INSPIRE-MIF/helpdesk-validator/tree/master/training%20material/2019-10-01%2B02%20JRC%20Workshop/Step-by-step%20example%20-%20Webapp

[metadaten_testdata.xml.zip](https://github.com/INSPIRE-MIF/helpdesk-validator/files/8230807/metadaten_testdata.xml.zip)

Thank you very much!

**Comment by jenriquesoriano** [comment]
Dear @jmbizfac 

we have tested the .xml file that is in the training material and it can be executed correctly.
On the other hand, we have verified that the attached metadata file (inside metadaten_testdata.xml.zip) cannot be loaded.
Thus, we recommend to download the [referred file](https://github.com/INSPIRE-MIF/helpdesk-validator/blob/master/training%20material/2019-10-01%2B02%20JRC%20Workshop/Step-by-step%20example%20-%20Webapp/metadata_example.xml) from the [training zone](https://github.com/INSPIRE-MIF/helpdesk-validator/tree/master/training%20material) by sinchronizing the repository, so you can pick-up the file as is in the training material and test it accordingly.

Please let us know if you find further issues with this or any other aspect where we may help you.

Best regards,

**Comment by fabiovinci** [comment]
Dear @jmbizfac,

did you able to solve the issue?

**Comment by fabiovinci** [comment]
Dear @jmbizfac,
since there was no reply from your side, I will close the issue.
Please reopen it or open a new issue if the error persists.
