### ISSUE TITLE
Metadata dataset: Character encoding

### ISSUE THREAD

**Issue by idevisser** [INSPIRE-MIF/helpdesk-validator#73]
I got an unexpected error with the md isdss 2.5  Character encoding

Comment:
providing the utf8 value should not result in an error

The TG INSPIRE  descibes;
This element is mandatory only if an encoding is used that is not based on UTF-8.
It doesn't say it is forbidden to provide the encoding if its UTF-8

Messages:
The metadata record set has 1 record(s) with errors for this assertion.
XML document 'test dataset.xml', record 'C2DFBDBC-5092-11E0-BA8E-B62DE0D72085': The MD_CharacterSetCode element with value 'utf8' shall not be provided when it is the only supported encoding. UTF8 is considered as default when MD_CharacterSetCode is not provided. Otherwise, if more than one encoding is supported and UTF8 is one of them, 'utf8' shall be provided.

In the test XML the Character encoding is provided with the utf8 value.

**Comment by alitka** [comment]
Dear @idevisser,
I also mentioned this in issue #53 

> related to specific comment in line 17-19
> 
> `<!--TG Requirement 2.5: metadata/2.0/req/isdss/character-encoding: The character encoding(s) shall be given for data sets and data sets series which use encodings not based on UTF-8 by using element gmd:characterSet/gmd:MD_CharacterSetCode referring to one of the values of ISO 19139 code list MD_CharacterSetCode. The multiplicity of this element is 0..n. If more than one character encoding is used within the described data set or data sets series, all used character encodings, including UTF-8 (code list value "utf8"), shall be given using this element.-->`
> 
> That's not correct. The focus here is on the used characterSet in the metadata record (ISO 19115 No. 4). However the Requirement 2.5 refers to the characterSet used in the data itself (ISO 19115 No. 40). But for this purpose there is no listing in the example (should be directly above topicCategory), because in case of UFT-8 it's dispensable at this point? You can pass the test without this element, but you got an error (Conformance Class 2: INSPIRE data sets and data sets series interoperability metadata), when you set in above the topicCategory-element.

Best regards.

**Comment by josemasensio** [comment]
Dear @idevisser 

We have review the test code and the error appears because the CharacterSetCode element has some errors:
1.  The codeList URL must be "http://standards.iso.org/iso/19139/resources/gmxCodelists.xml#MD_CharacterSetCode".
2. The codeListValue only has to be "utf8" when we have more than one CharacterSetCode. On this case fails because we only have one CharacterSetCode into gmd:MD_DataIdentification element, so the codeListValue can't be "utf8".

For more information, you can check the [Character Encoding ATS](https://github.com/inspire-eu-validation/metadata/blob/2.0/isdss/character-encoding.md) or the [page 74 of TG](https://inspire.ec.europa.eu/sites/default/files/documents/metadata/inspire-tg-metadata-iso19139-2.0.1.pdf).

Best regards.

**Comment by pvgenuchten** [comment]
TG REQ 2.5 ([p53](https://inspire.ec.europa.eu/sites/default/files/documents/metadata/inspire-tg-metadata-iso19139-2.0.1.pdf)): "The character encoding(s) shall be given for data sets and data sets series which use encodings not based  on  UTF-8  by  using  element gmd:characterSet/gmd:MD_CharacterSetCodereferring  to  one  of the values of ISO 19139 code list MD_CharacterSetCode50"

This does not state: "character encoding must not be given if dataset uses encoding utf8"

**Comment by MarcoMinghini** [comment]
We agree that the test should be less restrictive and should validate positively when utf8 is the only encoding.

The issue on code lists (#69) is more general and will be discussed in the sub-group meeting next week.

**Comment by AntoRot** [comment]
I agree with @marcominghini that the test should be less restrictive.

**Comment by LauraAlemany** [comment]
I agree with Marco, the test should validate positively when utf8 is the only encoding.

**Comment by MarcoMinghini** [comment]
**2017.4 meeting 2019-07-17**

- It is agreed that no error should be thrown when utf-8 is the only encoding.
- [ ] JRC to change the test, accordingly.

**Comment by josemasensio** [comment]
Dear @idevisser,

We modified the test to validate even if there is a single CharacterSetCode with a CodeListValue valued as "UTF-8".

Regards.

**Comment by josemasensio** [comment]
Dear @idevisser,

Does this solution worked?

Regards.

**Comment by fxprunayre** [comment]
> We modified the test to validate even if there is a single CharacterSetCode with a CodeListValue valued as "UTF-8".

Not sure in which branch it is done, but was not working yesterday in master. Here is an option to fix the test https://github.com/inspire-eu-validation/ets-repository/pull/315/commits/7253110dece415b9fba7b174f2ac51fe85f07edd
and also validate a record which contains one valid charset + an extra one
https://github.com/inspire-eu-validation/ets-repository/pull/315/commits/9a8a188e3d771df310ec9e1dcfd3e63a8152e598

Relates to https://github.com/inspire-eu-validation/ets-repository/pull/315

**Comment by josemasensio** [comment]
Dear @fxprunayre,

The issue is fixed on [staging instance](http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/). 

Best regards.

**Comment by josemasensio** [comment]
Afert some internal tests, we checked that everything is working fine, so we will mark as solved this issue.

Regards.

**Comment by pvgenuchten** [comment]
On which branch was the issue fixed? Which branch is used to build the staging instance?

**Comment by fxprunayre** [comment]
> Which branch is used to build the staging instance?

It looks like this is it https://github.com/inspire-eu-validation/ets-repository/tree/staging

**Comment by pvgenuchten** [comment]
Oh sorry, was looking in wrong repo, thanx francois
