### ISSUE TITLE
Metatada validation in production instance failed

### ISSUE THREAD

**Issue by ghost** [INSPIRE-MIF/helpdesk-validator#730]
Hi,

it seems that metadata records can't be validated. By clicking on "Start test" following message is displayed in red box:
```
ERROR
An error has occured
```

Can you please take a look on it?

**Comment by fabiovinci** [comment]
Dear @DeordD,

now it seems to work.

Have you tried to clear the browser cache?

**Comment by ghost** [comment]
Hi @fabiovinci,

now it works. I didn't clear my browser before testing. 
Thanks.

This issue can be closed from my point of view.
