### ISSUE TITLE
403 Forbidden Error

### ISSUE THREAD

**Issue by jelwell93** [INSPIRE-MIF/helpdesk-validator#731]
Apologies if this isn't the correct place for this. 

I'm trying to run a POST request to https://inspire.ec.europa.eu/validator/v2/TestRuns using FME. I've been able to run GET and POST requests to get the status and post the XML metadata, but whenever I try to post a Test Run, I get 403 Forbidden. 

I've followed the guidance here: https://github.com/INSPIRE-MIF/helpdesk-validator/tree/master/training%20material/2019-10-01%2B02%20JRC%20Workshop/Step-by-step%20example%20-%20API

This is my body (the 'Value' attributes are the appropriate EIDs as FME attributes):
`{
    "label": "test",
    "executableTestSuiteIds": ["@Value(_id)"],
    "arguments": {
        "files_to_test": ".*",
        "tests_to_execute": ".*"
    },
    "testObject": {
        "id": "@Value(_testobj)"
    }
}`

I've tried running the same request here: https://reqbin.com/ to rule out FME and get 403 Forbidden. I also get 403 forbidden when running the sample code on the swagger ui page. Any ideas or advice would be most appreciated!

**Comment by fabiovinci** [comment]
Dear @jelwell93,

to use the Validator through the API you need an API key, please refer to [this comment](https://github.com/INSPIRE-MIF/helpdesk-validator/issues/594#issuecomment-919825955) for more info and on how to request it.

**Comment by jelwell93** [comment]
Thanks @fabiovinci!

**Comment by fabiovinci** [comment]
Dear @jelwell93,

another option that I would like to suggest is the installation of the validator on your premises, following the deployment instruction available [here](https://github.com/INSPIRE-MIF/helpdesk-validator/releases/tag/v2022.0), to avoid the restrictions present by using the API key.
