### ISSUE TITLE
Trouble validate file in INSPIRE validator. Only get error-message, no test report. 

### ISSUE THREAD

**Issue by carlansgu** [INSPIRE-MIF/helpdesk-validator#732]
Hi, I'm uploading a file to test in INSPIRE validator: https://inspire.ec.europa.eu/validator/test-selection/index.html

I only get the red box with an error saying "an error has occured" (see picture below). I do not get any log or test report of what went wrong. The uploading of the file is successful.Is it possible to get more information (a test report) of what might be wrong with my file? 
The uploading of the file is successful. But what is wrong with my file?

Can you help me? See attached file that I'm trying to upload. It's a Energy resources vector GML-file (Annex III). 

I'm using google chrome (but get the same result when using edge).

![image](https://user-images.githubusercontent.com/102164515/159502878-e1ddce3d-df00-4c32-bd79-9aeca15ea8c6.png)

![image](https://user-images.githubusercontent.com/102164515/159501824-2d60899c-b9f4-4b98-a7ed-3333b9cf608d.png)

[ER_FossilFuelResource_SGU_epsg4258.zip](https://github.com/INSPIRE-MIF/helpdesk-validator/files/8325041/ER_FossilFuelResource_SGU_epsg4258.zip)

Please let me know if you need any further information. 

/
Carolin

**Comment by fabiovinci** [comment]
Dear @carlansgu,

thank you for reporting the issue, we will investigate it.

In the meantime, you can use the [staging](http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/home/index.html) instance, at the moment the tests are the same.

**Comment by carlansgu** [comment]
No need for now! I found the test report in another place on the web site: https://inspire.ec.europa.eu/validator/test-reports/index.html

So now I Will go there and havre a look myself. Thanks, I dont need help right now.


/Carolin

Skickat från min iPhone

22 mars 2022 kl. 19:00 skrev Fabio Vinci ***@***.***>:

﻿

Dear @carlansgu<https://github.com/carlansgu>,

thank you for reporting the issue, we will investigate it.

In the meantime, you can use the staging<http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/home/index.html> instance, at the moment the tests are the same.
