### ISSUE TITLE
Pre-defined Download Service: Iterate over Media Type entries

### ISSUE THREAD

**Issue by Kate-Lyndegaard** [INSPIRE-MIF/helpdesk-validator#740]
Dear Team,

I would appreciate your insight on the error message I am receiving for the test step _Iterate over Media Type entries_.
![grafik](https://user-images.githubusercontent.com/36956461/161743933-048a561f-b8c3-4274-8043-794109becef1.png)

When I click on Message.1 in the attachments of the test step, the error message states:
![grafik](https://user-images.githubusercontent.com/36956461/161744285-4eae2242-17c1-4818-a29f-f24d934df955.png)

![grafik](https://user-images.githubusercontent.com/36956461/161744192-8487f54b-4ff3-40c9-a16e-0956ff31f6b5.png)

Atom feed: https://ekstest.wetransform.eu/services/bsp/org.469.f40c076a-5407-4d50-98e9-aa1e2d75c0bd/service/atom/id_predefined_dataset

Validator report (official validator instance): 
[Test run on 13_15 - 05.04.2022 with test suite Conformance Class Pre-defined Atom.zip](https://github.com/INSPIRE-MIF/helpdesk-validator/files/8417637/Test.run.on.13_15.-.05.04.2022.with.test.suite.Conformance.Class.Pre-defined.Atom.zip)

Issues appears related to https://github.com/INSPIRE-MIF/helpdesk-validator/issues/383

In addition to the _Iterate over Media Type entries_ error, I receive the same error reported in https://github.com/INSPIRE-MIF/helpdesk-validator/issues/642 which is unexpected for me.

Any support would be greatly appreciated. Thank you for your time.

Kind regards,
Kate

**Comment by milanSch** [comment]
Dear @Kate-Lyndegaard, 
you mentioned issue  https://github.com/INSPIRE-MIF/helpdesk-validator/issues/642 which is connected with https://github.com/INSPIRE-MIF/helpdesk-validator/issues/722

In https://github.com/INSPIRE-MIF/helpdesk-validator/issues/722 there is link to atom download service feed https://geos.sazp.sk/inspire/atom/DownloadServiceFeed.xml where I was able to get a little further in validation process.  Maybe it will help you just as an example to compare.  Your atom feed link seems to be broken - Server not found.

thanks 
milan

**Comment by fabiovinci** [comment]
Dear @Kate-Lyndegaard,

could you please verify your Atom feed since it is now not accessible?

If it is no more available, do you have another Atom with the same error?

**Comment by Kate-Lyndegaard** [comment]
Dear @fabiovinci,

Thank you for your response.

We just underwent a server migration and unfortunately I have lost the feed. I do not have another example with the same issue. I apologize for the confusion. I will create a new issue if I encounter it again.

Kind regards,
Kate

**Comment by fabiovinci** [comment]
Dear @Kate-Lyndegaard,

in the latest release, some fixes related to the ATOM were introduced, so it is possible that the error you received is no more present.

Since your ATOM is no more available, I will close the issue, please reopen it or open a new issue if the error persists.
