### ISSUE TITLE
ERROR org.xml.sax.SAXException in local validator instance

### ISSUE THREAD

**Issue by Dnoack49** [INSPIRE-MIF/helpdesk-validator#743]
Dear All,

our organisation has has deployed a local instance of the validator (latest release [v2022.1 17/03/2022](https://github.com/INSPIRE-MIF/helpdesk-validator/releases/tag/v2022.1)  ; version 2.0.0-b210423T1152).
We can't use a docker image so we run the ETF from a tomcat application server.

We have tested the following WFS:
https://inspire.brandenburg.de/services/am_btf_wfs?request=GetCapabilities&service=WFS&VERSION=2.0.0

Using the ETF Web API, all service tests are passed:  
![grafik](https://user-images.githubusercontent.com/8046960/162403395-ccca81a2-1f70-4c37-8e9c-8f5614f70e5b.png)

However, when carrying out tests with our local instance we receive several schema validation errors regarding **xsi:schemaLocation** within the two conformance classes for direct and pre-defined WFS. The log states the following:

`ERROR org.xml.sax.SAXException: Fatal error: org.xml.sax.SAXParseException; systemId: http://schemas.opengis.net/wfs/2.0/wfs.xsd; lineNumber: 129; columnNumber: 60; src-resolve: Name 'xml:lang' kann nicht als 'attribute declaration'-Komponente aufgelöst werden. Response did not validate against schema 'http://www.opengis.net/wfs/2.0 http://schemas.opengis.net/wfs/2.0/wfs.xsd'.`

I have zipped and attached the log + html-report: [WFS-AM-BTF.zip](https://github.com/INSPIRE-MIF/helpdesk-validator/files/8450316/WFS-AM-BTF.zip)

Furthermore the etf.log-file lists other errors  such as
`2022-04-07 16:15:21.132 [Thread-244] ERROR c.e.s.i.w.t.WsdlGotoTestStep - Error making condition SkipScenario1; java.lang.NullPointerException`

Our question is now why these errors occur and how they can be fixed.

kind regards

**Comment by fabiovinci** [comment]
Dear @Dnoack49,

did you verify if your server is able to reach external resources (e.g. http://schemas.opengis.net/wfs/2.0/wfs.xsd)?

**Comment by Dnoack49** [comment]
Dear @fabiovinci ,
yes and we have put the url on our whitelist.

**Comment by fabiovinci** [comment]
Dear @Dnoack49,

do you still have the issue?

**Comment by Dnoack49** [comment]
Thank you for the reminder. No for now we have shut down our local instance. If we set it up again (this time with a new java version) and receive the error again I will reopen an issue.
Kind regards
