### ISSUE TITLE
Pre-defined Atom High memory usage.

### ISSUE THREAD

**Issue by kad-jagtt** [INSPIRE-MIF/helpdesk-validator#745]
**Atom URL:** 
https://service.pdok.nl/kadaster/cp/atom/v1_0/index.xml

**Server status:**
`{
  "name": "INSPIRE Reference Validator",
  "status": "GOOD",
  "heartbeat": "1650457035422",
  "willExpireAt": "1650457195422",
  "version": "2.0.0-b210423T1152",
  "uptime": "262",
  "allocatedMemory": "747767488",
  "presumableFreeMemory": "628319320384",
  "totalSpace": "43837489152",
  "freeSpace": "17990488064",
  "cpuLoad": "0.000211"
}`

**Version**
Tested with:
* inspire-validator:2022.0
* inspire-validator:2022.1

**Description**
No matter how much memory I assign to my docker container, it will be killed by the OOMKiller or it will reach the MAX of the container. 

`java.lang.OutOfMemoryError: Requested array size exceeds VM limit`

**Comment by fabiovinci** [comment]
Dear @kad-jagtt,

we will investigate the issue and we will let you know, but from a preliminary analisys it seems the OutOfMemory error could be due to the zip file size (it is 1GB).

**Comment by dperezBM** [comment]
Dear @kad-jagtt,

As @fabiovinci has mentioned the atom service probably is downloading a big zip file that is producing this issue. Consequently, the validator can't handle the content of the file in memory and displays the out of memory error. 
A possible workaround to avoid this issue could be use a more simple gml file, so the validator can handle its content, and it will be possible to verify the ATOM service.

Regards

**Comment by fabiovinci** [comment]
Dear @kad-jagtt,

we are implementing a fix for this type of issue, see the [comment in issue 819](https://github.com/INSPIRE-MIF/helpdesk-validator/issues/819#issuecomment-1540120895).

Since this issue duplicates issue 819, referring also to the same ATOM service, I will close it.
Please follow the implementation status and add any comments in issue #819.
