### ISSUE TITLE
Wrong namespace on request parameter in filter

### ISSUE THREAD

**Issue by dahermansson** [INSPIRE-MIF/helpdesk-validator#746]
In tests for Basic WFS (org.opengis.cite.iso10142.basic.filter.PropertyIsLikeOperatorTestes)
we get allot of faild tests and its looks like the validator are creating the filters for some featurtypes with wrong namespace. 

A faild test is reporting this request: [tns:Identifier](https://geo-inspire.trafikverket.se/Mapservice/wfs.axd/TN_RoadTransportNetwork?service=WFS&version=2.0.0&request=GetFeature&count=10&typenames=ns28:RoadLink&namespaces=xmlns(xml,http://www.w3.org/XML/1998/namespace),xmlns(ns28,urn:x-inspire:specification:gmlas:RoadTransportNetwork:3.0),xmlns(wfs,http://www.opengis.net/wfs/2.0)&filter=%3CFilter%20xmlns%3D%22http%3A%2F%2Fwww.opengis.net%2Ffes%2F2.0%22%20xmlns%3Ans28%3D%22urn%3Ax-inspire%3Aspecification%3Agmlas%3ARoadTransportNetwork%3A3.0%22%20xmlns%3Awfs%3D%22http%3A%2F%2Fwww.opengis.net%2Fwfs%2F2.0%22%3E%3CPropertyIsLike%20escapeChar%3D%22%5C%22%20singleChar%3D%22%3F%22%20wildCard%3D%22%2A%22%3E%3CValueReference%20xmlns%3Atns%3D%22http%3A%2F%2Fwww.opengis.net%2Fgml%2F3.2%22%3Etns%3Aidentifier%3C%2FValueReference%3E%3CLiteral%3E%2A00%3A5-1%3C%2FLiteral%3E%3C%2FPropertyIsLike%3E%3C%2FFilter%3E) wich return an error. If i change the type in the filter to [gml:identifier](https://geo-inspire.trafikverket.se/Mapservice/wfs.axd/TN_RoadTransportNetwork?service=WFS&version=2.0.0&request=GetFeature&count=10&typenames=ns28:RoadLink&namespaces=xmlns(xml,http://www.w3.org/XML/1998/namespace),xmlns(ns28,urn:x-inspire:specification:gmlas:RoadTransportNetwork:3.0),xmlns(wfs,http://www.opengis.net/wfs/2.0)&filter=%3CFilter%20xmlns%3D%22http%3A%2F%2Fwww.opengis.net%2Ffes%2F2.0%22%20xmlns%3Ans28%3D%22urn%3Ax-inspire%3Aspecification%3Agmlas%3ARoadTransportNetwork%3A3.0%22%20xmlns%3Awfs%3D%22http%3A%2F%2Fwww.opengis.net%2Fwfs%2F2.0%22%3E%3CPropertyIsLike%20escapeChar%3D%22%5C%22%20singleChar%3D%22%3F%22%20wildCard%3D%22%2A%22%3E%3CValueReference%20xmlns%3Atns%3D%22http%3A%2F%2Fwww.opengis.net%2Fgml%2F3.2%22%3Egml%3Aidentifier%3C%2FValueReference%3E%3CLiteral%3E%2A00%3A5-1%3C%2FLiteral%3E%3C%2FPropertyIsLike%3E%3C%2FFilter%3E) the request givs the correct requested response. Why is it using the namespace TNS? We can't find any referens to that namespace in our services our in Inspire specifications. Some of the test for filter are working correctly and I can't find any difference in them or our metadata to manage the namespace the validator is trying to use for these test/request. 

FYI: @mi-i

**Comment by fabiovinci** [comment]
Dear @dahermansson,

this error is coming from the OGC TEAM engine validator, which is used as a dependency on the Direct WFS ETS.
The Validator only processes the result of the validation through the endpoint in their service and includes it in the Test Report.

You can open the issue in their Github repository https://github.com/opengeospatial/teamengine, and include the validation  result using their own TestReport format through the request: https://cite.opengeospatial.org/teamengine/rest/suites/wfs20/run?wfs=https://geo-inspire.trafikverket.se/Mapservice/wfs.axd/TN_RoadTransportNetwork?service=WFS%26request=GetCapabilities%26version=2.0.0

**Comment by dahermansson** [comment]
Closing this Issue as it's been tracked in [opengeospatial
ets-wfs20 - 227](https://github.com/opengeospatial/ets-wfs20/issues/227)

**Comment by fabiovinci** [comment]
Dear @dahermansson,

thank you for opening the issue in the OGC repository.

We can leave this issue open until the related issue is resolved by OGC, as it may be useful for other users to know about the error.

**Comment by fabiovinci** [comment]
Dear @dahermansson,

it seems the OGC team provides you with a [solution for your error](https://github.com/opengeospatial/ets-wfs20/issues/227#issuecomment-1141872491), were you able to implement it and test it?

**Comment by fabiovinci** [comment]
Dear @dahermansson,

since there was no response we will close the issue, please reopen it if the error persists.
