### ISSUE TITLE
Wrong Feature Type listed in Test Result

### ISSUE THREAD

**Issue by Dnoack49** [INSPIRE-MIF/helpdesk-validator#747]
Dear Community,

- [ ] a description of the steps to reproduce your issue:
 we validated [this Dataset](https://inspire.brandenburg.de/services/pf_bgbetrieb_wfs?service=WFS&version=2.0.0&request=GetFeature&typenames=pf:ProductionFacility&Count=10) against the PF-Data theme using the staging and production instance. In the test report under `Conformance class: GML application schemas, Production and Industrial Facilities` a wrong feature type (**Protected Site**) is listed.

- [ ] a screenshot illustrating the problem:
![grafik](https://user-images.githubusercontent.com/8046960/166419090-fd18acee-0997-4163-bc3e-c1f5c4fb7f84.png)

- [ ] the Test Report (ideally as an attachment to the issue)
[Test run  Production and industrial facilities (PF).zip](https://github.com/INSPIRE-MIF/helpdesk-validator/files/8608939/Test.run.Production.and.industrial.facilities.PF.zip)

- [ ] the name of the Test that failed (`Assertion URI`):
http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/validator//v2/TestRuns/EID6b6e8de9-3c3d-4bf1-a21f-ddbd9805c644.html?lang=de#EID7ea32101-fb23-4134-a2d7-6fc7e62b4c7a

- [ ] the URL of your service / the file you have uploaded or referenced (as
an attachment).
https://inspire.brandenburg.de/services/pf_bgbetrieb_wfs?service=WFS&version=2.0.0&request=GetFeature&typenames=pf:ProductionFacility&Count=10

**Comment by fabiovinci** [comment]
Dear @Dnoack49,

thank you for identifying the typo, we will correct it.

**Comment by arantzaetxebarria** [comment]
Dear @Dnoack49 

The typo has been rectified and now it is in [staging](http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/test-selection/index.html) environment. Could you please confirm that all is correct? Thanks in advance.

Regards

**Comment by Dnoack49** [comment]
Dear @arantzaetxebarria 

yes now it is correct, the issue can be closed.
Thank you.

**Comment by arantzaetxebarria** [comment]
Dear @Dnoack49 

The issue will remain open until the next release 2022.2 when the changes will be put into the production environment.

Regards

**Comment by Dnoack49** [comment]
Ah, I did not know that, sorry!
