### ISSUE TITLE
ATOM test 'Describe Spatial Dataset' results in UNDEFINED

### ISSUE THREAD

**Issue by mwjsanders** [INSPIRE-MIF/helpdesk-validator#748]
When validating the pre defined atom https://service.pdok.nl/cbs/wb2021/atom/v1_0/index.xml, the test step 'Describe Spatial Dataset' results in the status UNDEFINED. As a result the step 'Query examples for each dataset' is skipped.

The validation result is available at:
https://inspire.ec.europa.eu/validator/test-run/details.html?id=EID941e1b0e-32fb-4555-92c1-16d608484602

I expect the test step 'Describe Spatial Dataset' to result in at least a FAILURE or else a SUCCES, but not UNDEFINED 

What else that caught my eye was a nullpointerException in  the log:
```
05.05.2022 12:56:18 - Preparing Test Run Test run on 14:55 - 05.05.2022 with test suite Conformance Class Pre-defined Atom (initiated Thu May 05 12:56:18 UTC 2022)
05.05.2022 12:56:18 - Resolving Executable Test Suite dependencies
05.05.2022 12:56:18 - Preparing 1 Test Task:
05.05.2022 12:56:18 -  TestTask 1 (a5df157d-e39d-420b-9e01-740ff72ec8c5)
05.05.2022 12:56:18 -  will perform tests on Test Object 'index.xml' by using Executable Test Suite 'Conformance Class: Download Service - Pre-defined Atom (EID: 11571c92-3940-4f42-a6cd-5e2b1c6f4d93, V: 1.0.7 )'
05.05.2022 12:56:18 -  with parameters: 
05.05.2022 12:56:18 - etf.testcases = *
05.05.2022 12:56:18 - Test Tasks prepared and ready to be executed. Waiting for the scheduler to start.
05.05.2022 12:56:18 - Setting state to CREATED
05.05.2022 12:56:18 - Changed state from CREATED to INITIALIZING
05.05.2022 12:56:19 - Starting TestRun.941e1b0e-32fb-4555-92c1-16d608484602 at 2022-05-05T12:56:20Z
05.05.2022 12:56:20 - Changed state from INITIALIZING to INITIALIZED
05.05.2022 12:56:20 - Project Properties: 
05.05.2022 12:56:20 - etf.testcases - * 
05.05.2022 12:56:20 - serviceEndpoint - https://service.pdok.nl/cbs/wb2021/atom/v1_0/index.xml 
05.05.2022 12:56:20 - username -  
05.05.2022 12:56:20 - authUser -  
05.05.2022 12:56:20 - authMethod - basic 
05.05.2022 12:56:20 - TestRunTask initialized
05.05.2022 12:59:39 ERROR Exception occurred in Test Step: java.lang.NullPointerException
05.05.2022 13:01:57 - Releasing resources
05.05.2022 13:01:57 - Changed state from INITIALIZED to RUNNING
05.05.2022 13:01:58 - Duration: 5min
05.05.2022 13:01:58 - TestRun finished
05.05.2022 13:01:58 - Changed state from RUNNING to COMPLETED
```
If the cause of this error lies within our atom service, I would at least expect a clear message from the validator stating the cause.

**Comment by fabiovinci** [comment]
Dear @mwjsanders,

thanks for reporting the issue, we will analyze why the test step 'Describe Spatial Dataset' results in the UNDEFINED state.

**Comment by dperezBM** [comment]
Dear @mwjsanders,
The report is no longer available and we couldn't reproduce the issue and find the undefined test
Could you provide us  a zip file of the test report?

Regards.

**Comment by mwjsanders** [comment]
I ran an ETF validation for this service, this time a got a status FAILED (reason is https://github.com/INSPIRE-MIF/helpdesk-validator/issues/635). The status UNDEFINED no longer appears so this issue can be closed.
