### ISSUE TITLE
URL Metadata validation for non-ISO default responses

### ISSUE THREAD

**Issue by jenriquesoriano** [INSPIRE-MIF/helpdesk-validator#749]
Dear all, 

an issue has been detected in the metadata validation via url for those endpoints whose default response is non-ISO metadata.
In these cases, the validation does not behave properly.
Thus, to prevent this issue from occurring, it has been determined that for urls entered in the UI metadata validation, these default parameters and values are needed:
- &outputSchema=http://www.isotc211.org/2005/gmd
- &elementSetName=full 

These parameters are included automatically and transparently to the users through the UI.
If these parameters are already included in the URL, the values entered will be preserved, assuming that they are intentionally included. 
This guarantees that the endpoint returns an ISO metadata to be validated by the corresponding ETS.

This development is available in staging for testing and future incorporation in the v2022.2 release to take place next June.

Best regards,

**Comment by fabiovinci** [comment]
Dear all,

I tested the solution and it seems to work well.
