### ISSUE TITLE
Metadata service: Coupled Resource (MD SDS 3.6)

### ISSUE THREAD

**Issue by idevisser** [INSPIRE-MIF/helpdesk-validator#75]
An unexpected error occured at MD SDS 3.6: Coupled Resource

Comment:
The link should pointing to the online metadata descriptions of data set, not to an INSPIRE network service as suggested by the message. Test seems to be not correct.

Message
XML document 'Voorbeeld_Metadata_Services_2019.xml', record 'C2DFBDBC-5092-11E0-BA8E-B62DE0D72085': The metadata record has a linkage property, which references a resource with media type 'text/html;charset=UTF-8' at 'https://www.nationaalgeoregister.nl/geonetwork/srv/metadata/a7fb2234-f7b4-4a03-b282-f10947f42fb1#MD_DataIdentification' which is not one of the media types indicating an INSPIRE network service. Please review the resource to check that it meets the linkage requirements; specifically, if the resource is a webpage, check that it provides further instructions or a client application that directly accesses the service.

TG Requirement 3.6: metadata/2.0/req/sds/coupled-resource
Links pointing to the online metadata descriptions of data sets provided by the described service shall be given using srv:operatesOn element. The multiplicity of this element is 0..n. This property shall be implemented by reference. The xlink:href attribute of each of the srv:operatesOn elements shall contain a URI pointing to the gmd:MD_DataIdentification element of the metadata record of the provided the data set or data set series.

**Comment by idevisser** [comment]
XML used by the service Metadata issues

[Voorbeeld_Metadata_Services_2019.zip](https://github.com/inspire-eu-validation/community/files/3349985/Voorbeeld_Metadata_Services_2019.zip)

**Comment by josemasensio** [comment]
Dear @idevisser, 

The test validation checks that the media type of the url of srv:operatesOn element is a text/xml or application/xml. The problem is that the url of your xml file is a text/html.

Best regards.

**Comment by idevisser** [comment]
Dear @bilbomaticaue,

Where can i find the requirement  that the media type of the url of srv:operatesOn element is a text/xml or application/xml?

Best regards Ine

**Comment by alitka** [comment]
Dear @idevisser,
I guess it's related to the sentence below the TG Requirement 3.6: metadata/2.0/req/sds/coupled-resource:

`“Implementation by reference” means that the xlink:href attribute is pointing to an XML document that contains a gmd:MD_DataIdentification object.`

Best regards.

**Comment by pvgenuchten** [comment]
what is interesting here, something to discuss for future tg's, a typical uri (to me use of an uri is the most obvious choice here) would respond in application/xml only if you request for that encoding, application/xml is in many cases not the default encoding of web resources, would it be an idea to relax the tg to require to respond in application/xml only if the request is made using an accept:application/xml

See for example:

https://vanilla.geocat.net/geonetwork/srv/api/records/da165110-88fd-11da-a88f-000d939bc5d8

it will respond in html if you open it in a browser, but will respond in xml if you request the resource with an accept header application/xml

**Comment by josemasensio** [comment]
Dear @idevisser, 

Does the solution worked?

Regards.
