### ISSUE TITLE
Opensearch description validation issues for predefined ATOM download in ets-repository

### ISSUE THREAD

**Issue by mwjsanders** [INSPIRE-MIF/helpdesk-validator#751]
While validating different ATOM services using the ETF validator I found several errors (according to my opinion) in the [ets-repository ](https://github.com/inspire-eu-validation/ets-repository) related to validating a describe request on a opensearch description (eg [url](https://ngr.acceptatie.nationaalgeoregister.nl/geonetwork/opensearch/dut/describe?spatial_dataset_identifier_namespace=http://www.pdok.nl&spatial_dataset_identifier_code=e2318c58-b1e6-4621-9c77-33b8a1fd0e76&language=nl)) and the generation of a getSpatialDatasetUrl from the response of a describe request on the opensearch description within the test.

All mentioned issues in this ticket relate to the Conformance Class: Download Service - Pre-defined Atom (https://github.com/inspire-eu-validation/ets-repository/blob/master/service/ds-atom-pre-defined-soapui-project.xml)

related Test

---
- OpenSearch Description
  - Describe Spatial Dataset operation
    - Test Steps
      - Iterate over Describe Spatial Dataset URL

 In this test step ( [in this code line](https://github.com/inspire-eu-validation/ets-repository/blob/28b66265aab8fc8228672283887475818aade1ab/service/ds-atom-pre-defined-soapui-project.xml#L4365) ) describe spatialdataset urls are resolved from the retreived opensearch description from a url where `rel='describedby'`. But also where a the template attribute should contain 'crs'. A crs is not mandatory for a describedby url (see TG requirement 42 of the [Technical_Guidance_Download_Services_v3.1.pdf](https://inspire.ec.europa.eu/documents/Network_Services/Technical_Guidance_Download_Services_v3.1.pdf))

 The condition `contains(@template,'crs')` should be dropped here. Else this results in failure of finding a describedby url.

 ---

- OpenSearch Description
  - Query examples from each dataset
    - Test Steps
      - Iterate over Describe Spatial Dataset URL

Here something similar as in the issue above is wrong. If the intention is to test the describe of the opensearch description then the actual download url template should not be used but instead the describedby template. So in [this code line](https://github.com/inspire-eu-validation/ets-repository/blob/28b66265aab8fc8228672283887475818aade1ab/service/ds-atom-pre-defined-soapui-project.xml#L4622) the describeSpatialDataSetUrlTemplates schould be resolved from the opensearch description from the `URL` element with `rel='describedby'` instead of `rel='result'` and the condition `contains(@template,'crs')` should be dropped.

 ---

- OpenSearch Description
  - Query examples from each dataset
    - Test Steps
      - Iterate over Get Spatial Dataset URL

In the test step the results template url from the opensearch description is called to actualy test if the dataset can be downloaded. instead of looking op this template url from the opensearch description, the template url is resolved from the describe request on the opensearch desription. This cannot work since the describe on a opensearch description will return the atom feed which has no download template urls. So when assigning the xmlHolder in [this code line](https://github.com/inspire-eu-validation/ets-repository/blob/28b66265aab8fc8228672283887475818aade1ab/service/ds-atom-pre-defined-soapui-project.xml#L4750) the result from test step _Get Opensearch Description_ should be used. So the correct code here is: `def xmlHolder = ph.getTestStepResult("Get OpenSearch Description")`

The last issue is also mentioned in https://github.com/INSPIRE-MIF/helpdesk-validator/issues/722

**Comment by arantzaetxebarria** [comment]
Dear @mwjsanders 

Many thanks for your contribution. We are going to implement all your proposals.
The second one is related to issue [642](https://github.com/INSPIRE-MIF/helpdesk-validator/issues/642) and the third, as you have mentioned, is related to [722](https://github.com/INSPIRE-MIF/helpdesk-validator/issues/722), so we hope that these changes will also solve the problems related to these issues.

Regards,

Arantza

**Comment by arantzaetxebarria** [comment]
Dear @mwjsanders 

The changes are in [staging](http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/test-selection/index.html) environment, could you please confirm? Let us know if all is working properly. Thanks

Regards

**Comment by mwjsanders** [comment]
@arantzaetxebarria, I did a test with the fixes on the staging branch and all issues mentioned in this ticket are resolved when using our services.

**Comment by arantzaetxebarria** [comment]
Dear all,

We would like to announce that after some regression tests and issues experimented by some users ([722 ](https://github.com/INSPIRE-MIF/helpdesk-validator/issues/722#issuecomment-1130007971)/ [758 ](https://github.com/INSPIRE-MIF/helpdesk-validator/issues/758#issue-1245165084)/ [642](https://github.com/INSPIRE-MIF/helpdesk-validator/issues/642#issuecomment-1141787391)) in staging environment, we need to carry on analysing the behaviour of the validator, so in order to ensure stability in the production environment, we will label this issue under analysis, furthermore, the solution proposed will not be part of the next release.

Regards

**Comment by mwjsanders** [comment]
@arantzaetxebarria 

After some testing with the latest version (v2022.2) of the ets-repository and reapplying all proposals done in this issue I noticed the Opensearch test could still fail in some situations. This was the case when the datafeed consists of a single download file. In this situation the Get Spatial Dataset url returns directly the download file and not a feed with an index off all downloadable files which is only returned when the download consists of multiple files.

for this the assertion _Root element 'feed' exists_ in the test: 
- OpenSearch Description
  - Query examples from each dataset
    - Test Steps
      - Get Spatial Dataset
does not cover all possible situations. It should test whether a feed is returned or an download file.

**Comment by arantzaetxebarria** [comment]
Dear @mwjsanders 

As you know, we have implemented some changes related to your issue https://github.com/INSPIRE-MIF/helpdesk-validator/issues/819, these changes seem to fix this issue, could you please verify? Many thanks

Best regards

**Comment by mwjsanders** [comment]
@arantzaetxebarria 
Indeed this issue seems to be fixed. I testes with several atom services.
Thanks
