### ISSUE TITLE
validator operable using Java 11?

### ISSUE THREAD

**Issue by Dnoack49** [INSPIRE-MIF/helpdesk-validator#757]
Dear all,

we currently use a local instance of the validator (but no Docker-image) and our machines will switch to java 11 soon. A year after [this question ](https://github.com/INSPIRE-MIF/helpdesk-validator/issues/503) regarding Java 11 was raised, we would like to know if the status is the same or if there are any plans to move it to the new java-version and if it will be runnable using JDK11/Tomcat9?

Kind regards

**Comment by jenriquesoriano** [comment]
Dear @Dnoack49 ,

thank you very much for your question.
We are currently working on the incorporation of a new version of the ETF to the INSPIRE reference validator.  
This version will be compatible with Java 11.
As soon as it is available, a specific instance will be published for testing by the community and the different artifacts will be made available for deployment.
We will keep you informed of the evolution of this process.

Best regards,
