### ISSUE TITLE
Atom feed cannot be tested on staging instance

### ISSUE THREAD

**Issue by Kate-Lyndegaard** [INSPIRE-MIF/helpdesk-validator#758]
Hi,

I am currently trying to test our atom feeds, because there have been improvements introduced on staging. I was hoping to check for the changes implemented for #751. Unfortunately, when I attempt to test my atom feed, I get the following error at upload:
![grafik](https://user-images.githubusercontent.com/36956461/169815282-90f3105c-7b5a-4c56-aef6-d5492589e9cf.png)
The test hangs and does not complete.

I can test the same atom feed in production, and there I receive the skipped Describe Spatial Dataset test as reported in #751.

Test atom feed used on staging and production: https://test.haleconnect.de/services/bsp/org.473.c3005a47-2e0c-4879-ab24-11920d7e40b5/service/atom/id_predefined_dataset

Atom feed test result in production:
[AM_AtomFeed.zip](https://github.com/INSPIRE-MIF/helpdesk-validator/files/8754576/AM_AtomFeed.zip)

Kind regards,
Kate

**Comment by fabiovinci** [comment]
Dear @Kate-Lyndegaard,

thank you for opening the issue, we have noticed the error and we are already working to solve it.

**Comment by arantzaetxebarria** [comment]
Dear @Kate-Lyndegaard 

We have implemented some changes related to the issue https://github.com/INSPIRE-MIF/helpdesk-validator/issues/819, these changes seem to fix this issue, could you please verify? Many thanks

Best regards

**Comment by Kate-Lyndegaard** [comment]
Dear @arantzaetxebarria,

Thank you very much! I re-tested my service and it is working as expected. It's fully valid.

**Comment by arantzaetxebarria** [comment]
Dear @Kate-Lyndegaard 

Thank you for your confirmation. I reopen the issue, once the next release (v2023.2) is made, it will be closed

Regards
