### ISSUE TITLE
MD_identifier in metadata document and service metadata

### ISSUE THREAD

**Issue by Kate-Lyndegaard** [INSPIRE-MIF/helpdesk-validator#771]
Hi,

I am currently receiving an error in the **MD_Identifier exist in the Service Metadata** test. 
The error states: "_The MD_identifier 'haleconnect.com/e4afc341-7a1b-4b94-9e04-728f4edac4f2' is found in the metadata document but does not exist in the service Metadata. The service metadata refers to these identifiers: ''https://test.haleconnect.de/services/bsp/org.473.c5941548-88c4-4533-b65a-1e3e46015edb/md/dataset/dataset1#xpointer%28%2F%2Fgmd%3AidentificationInfo%5B1%5D%2Fgmd%3AMD_DataIdentification%29''. Check the Service Metadata and the Metadata document._"

WFS Service metadata:

`<srv:operatesOn xlink:href="https://test.haleconnect.de/services/bsp/org.473.0027e2ec-3857-400a-a91b-370692c7cfca/md/dataset/dataset1#xpointer%28%2F%2Fgmd%3AidentificationInfo%5B1%5D%2Fgmd%3AMD_DataIdentification%29" uuidref="63648ca4-2f22-4b6e-a02e-de099a6caec8"/>`

Dataset metadata:

`<gmd:MD_Identifier>
    <gmd:code>
        <gco:CharacterString>
            haleconnect.com/e4afc341-7a1b-4b94-9e04-728f4edac4f2
        </gco:CharacterString>
    </gmd:code>
</gmd:MD_Identifier>`

Can I solve this issue by removing the namespace from the MD_Identifier in the dataset metadata, or are there additional issues?

Test WFS: https://test.haleconnect.de/ows/services/org.473.c5941548-88c4-4533-b65a-1e3e46015edb_wfs?SERVICE=WFS&REQUEST=GetCapabilities&VERSION=2.0.0

Test report:
[Test.zip](https://github.com/INSPIRE-MIF/helpdesk-validator/files/8770364/Test.zip)

Thank you.

Kind regards,
Kate

**Comment by fabiovinci** [comment]
Dear @Kate-Lyndegaard,

your implementation seems ok, we will check the related test.

**Comment by dperezBM** [comment]
Dear @Kate-Lyndegaard,

We began analysing your issue. However, today the service https://test.haleconnect.de/ows/services/org.473.c5941548-88c4-4533-b65a-1e3e46015edb_wfs?SERVICE=WFS&REQUEST=GetCapabilities&VERSION=2.0.0 is no longer responding. Would you be able to provide us a similiar service where you experience the same issue?

Sorry for the inconveniences,
David

**Comment by Kate-Lyndegaard** [comment]
Dear David,

I'm sorry, our test instance went down this morning. Here is a new service: https://test.haleconnect.de/ows/services/org.473.c5f8123e-5003-4f01-a7ba-a2fa5d494a04_wfs?SERVICE=WFS&REQUEST=GetCapabilities&VERSION=2.0.0

Kind regards,
Kate

**Comment by dperezBM** [comment]
Thank you, @Kate-Lyndegaard. We will continue analysing the issue.

**Comment by Dnoack49** [comment]
Dear @dperezBM,

We ran into a similar issue.
When validating the following WFS:
https://inspire.brandenburg.de/services/er_wka_wfs?request=GetCapabilities&service=WFS 

We receive the error:
![image](https://user-images.githubusercontent.com/8046960/171631960-7eeff3c1-5571-4718-9b44-a49ae3c40af9.png)

However, in our case  **{id}** and **{datasetIdentifiersList}** are listed in brackets without a specific references.

In the Capabilities, the reference to the Dataset is given:

![image](https://user-images.githubusercontent.com/8046960/171635779-c46c07c5-dc93-4335-84c2-29705eb79834.png)

In the [WFS Service-Metadata](https://metaver.de/csw?REQUEST=GetRecordById&SERVICE=CSW&VERSION=2.0.2&id=329F4B66-ABC2-42F5-B8AA-3E9F5FCF3A4A&iplug=/ingrid-group:ige-iplug-bb&elementSetName=full)  the operatesOn element shows the reference to the dataset:

![image](https://user-images.githubusercontent.com/8046960/171636524-ab383c20-28cb-4249-909a-b20feb6fdd38.png)

An in the [Dataset Metadata](https://metaver.de/csw?REQUEST=GetRecordById&SERVICE=CSW&VERSION=2.0.2&id=BD6A2133-1139-4E96-A988-A4ED1F03EC5B&iplug=/ingrid-group:ige-iplug-bb&elementSetName=full) the following MD_Identifier is given:

![image](https://user-images.githubusercontent.com/8046960/171636938-2e0d7007-fd08-45b5-bec1-0101cbbd0319.png)

Could this be related to the previous issue #638 ?
We ask for an advise how the error can be fixed.

kind regards.

**Comment by fabiovinci** [comment]
Dear all,

we are reviewing the implementation of this test, see [this comment](https://github.com/INSPIRE-MIF/helpdesk-validator/issues/718#issuecomment-1143725592) in a similar issue for more information.

**Comment by fabiovinci** [comment]
Dear @Dnoack49,

as an additional comment on your implementation, if you have encoded the "_Unique Resource Identifier_" of the dataset using the `MD_Identifier` element, you should refer to it in the WFS Capabilities using only the Code element, according to the mapping provided in Table 13 in the WFS TG.

![image](https://user-images.githubusercontent.com/22212406/172129440-7086d038-76a7-48b7-93a0-82b5c347b546.png)

**Comment by fabiovinci** [comment]
Dear all,

we fixed the error according to what was indicated in the mentioned issue (# 780).

The solution is available in the staging instance and it will be included in the next release 2022.2.

**Comment by Dnoack49** [comment]
I can confirm the problem has been fixed.
Thank you!
