### ISSUE TITLE
 Conformance Class 'Direct WFS' - Initialization and basic checks

### ISSUE THREAD

**Issue by Kate-Lyndegaard** [INSPIRE-MIF/helpdesk-validator#772]
Hi,

I would like to know why I am receiving a series of generic server error messages for my service in the Conformance Class 'Direct WFS' - Initialization and basic checks tests.

![grafik](https://user-images.githubusercontent.com/36956461/170249404-c6709c80-ea62-48aa-8971-de35917144b3.png)

Test WFS: https://test.haleconnect.de/ows/services/org.473.c5941548-88c4-4533-b65a-1e3e46015edb_wfs?SERVICE=WFS&REQUEST=GetCapabilities&VERSION=2.0.0

Test report:
[Test.zip](https://github.com/INSPIRE-MIF/helpdesk-validator/files/8770364/Test.zip)

Tested on the staging instance.

Thank you.

Kind regards,
Kate

**Comment by fabiovinci** [comment]
Dear @Kate-Lyndegaard,

could you please try again after introducing the fixes suggested [here](https://github.com/INSPIRE-MIF/helpdesk-validator/issues/774#issuecomment-1140871531)?

Thanks

**Comment by fabiovinci** [comment]
Dear @Kate-Lyndegaard,

the WFS contains the same error reported [here](https://github.com/INSPIRE-MIF/helpdesk-validator/issues/774#issuecomment-1432962497), could you please verify?

**Comment by fabiovinci** [comment]
Dear @Kate-Lyndegaard,

since the connect issue was closed, I assume that also this issue is solved.
I will close it, please reopen the issue if the error persists.
