### ISSUE TITLE
at42-getcapabilities-layer-default-style error for Area Management

### ISSUE THREAD

**Issue by Kate-Lyndegaard** [INSPIRE-MIF/helpdesk-validator#773]
Hi,

I would like to know why I am receiving the following error for my WMS: "_A layer does not provide a valid default style name as specified in its INSPIRE Data Specification._" I am serving all layers in the AM specification and I believe the styles are all named correctly.

WMS: https://test.haleconnect.de/ows/services/org.473.c5941548-88c4-4533-b65a-1e3e46015edb_wms?SERVICE=WMS&REQUEST=GetCapabilities&VERSION=1.3.0

Test report:
[Test run on 13 32 - 25.05.2022 with test suite Conformance Class View Service WMS.html.zip](https://github.com/INSPIRE-MIF/helpdesk-validator/files/8770708/Test.run.on.13.32.-.25.05.2022.with.test.suite.Conformance.Class.View.Service.WMS.html.zip)

Could this be related to the presence of additional "default" layers, and if so, should they be removed?

Tested on staging instance.

Thank you.

Kind regards,
Kate

**Comment by arantzaetxebarria** [comment]
Dear @Kate-Lyndegaard 

We have just tested in production environment your WMS service, and it seems that the status of **at42-getcapabilities-layer-default-style** step is passed.
![image](https://user-images.githubusercontent.com/64014694/170664539-1e23de00-f599-41c9-be38-60f490fad929.png)

You can see the Test Repor here:
[Test run on 10_29 - 27.05.2022 with test suite Conformance Class View Service WMS.zip](https://github.com/INSPIRE-MIF/helpdesk-validator/files/8785216/Test.run.on.10_29.-.27.05.2022.with.test.suite.Conformance.Class.View.Service.WMS.zip)

Perhaps have you changed something in the service in the last few days?

Regards

Arantza

**Comment by Kate-Lyndegaard** [comment]
Hi @arantzaetxebarria,

No, nothing has changed. The service passes the test in production and fails the same test in staging. I would like to know why the service is failing the test in the staging instance.

Kind regards,
Kate

**Comment by dperezBM** [comment]
Dear @Kate-Lyndegaard

We have tested your WMS service both in production and staging. Currently, the status of **at42-getcapabilities-layer-default-style** is passed for both environments.


You can check the Test Reports here:
**Staging**
[Test run on 09_16 - 16.06.2022 with test suite Conformance Class View Service WMS_Staging.zip](https://github.com/INSPIRE-MIF/helpdesk-validator/files/8916572/Test.run.on.09_16.-.16.06.2022.with.test.suite.Conformance.Class.View.Service.WMS_Staging.zip)

**Production**
[Test run on 09_16 - 16.06.2022 with test suite Conformance Class View Service WMS_Production.zip](https://github.com/INSPIRE-MIF/helpdesk-validator/files/8916577/Test.run.on.09_16.-.16.06.2022.with.test.suite.Conformance.Class.View.Service.WMS_Production.zip)

Regards

David

**Comment by Kate-Lyndegaard** [comment]
Dear David,

I just re-tested, and I still receive the error on staging:

WMS: https://test.haleconnect.de/ows/services/org.473.c5941548-88c4-4533-b65a-1e3e46015edb_wms?SERVICE=WMS&REQUEST=GetCapabilities&VERSION=1.3.0

Test report with error: 
[Test run on 09 40 - 20.06.2022 with test suite Conformance Class View Service WMS.html.zip](https://github.com/INSPIRE-MIF/helpdesk-validator/files/8938638/Test.run.on.09.40.-.20.06.2022.with.test.suite.Conformance.Class.View.Service.WMS.html.zip)
 

Kind regards,
Kate

**Comment by fabiovinci** [comment]
Dear @Kate-Lyndegaard,

I also tested it in staging and did not receive the error (see report: http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/test-run/details.html?id=EID1d36e125-d9a5-4d8c-8540-8c10cb5ed0da).

Could you please try again to test it using an "Incognito window" or cleaning your browser cache first?

**Comment by Kate-Lyndegaard** [comment]
Dear @fabiovinci,

Thank you for your support. I no longer receive the reported error, however I am receiving an error in at57-getmap-format-parameter _"Not found image format in capabilities document to perform a GetMap request."_

I will open a new issue for the new error.

Kind regards,
Kate
