### ISSUE TITLE
Validator does not accept my view service URL

### ISSUE THREAD

**Issue by narinco** [INSPIRE-MIF/helpdesk-validator#777]
Hi,

I am trying to validate my view service but it seems like Validator doesn´t accept my service URL. When I paste the URL, I cannot run the test a error pop up window appear "An error has occured." 

I tried some other service validator and there is no problem and I get my result. 

Here is an URL to my view service: 
https://webad.agis.uniba.sk/servertest/services/Gutanova_DP/IPCC2000/MapServer/WMSServer?request=GetCapabilities&service=WMS

Can someone help me with this issue? 
Many thanks in advance.

Alexandra

**Comment by alitka** [comment]
Dear @narinco,
I suspect it might be related to the invalid certificate from webad.agis.uniba.sk, as I get the following error:
``` 
NET::ERR_CERT_DATE_INVALID
Subject: webad.agis.uniba.sk
Issuer: GEANT OV RSA CA 4
Expires on: 29.10.2021
Current date: 31.05.2022
```
Kind regards.

**Comment by fabiovinci** [comment]
Dear @narinco,

we confirm what was indicated by alitka, checking the timestamp of the expired certificate raises an exception, so you cannot proceed with the validation process.

Could you please fix the error and try again?

**Comment by narinco** [comment]
Dear @fabiovinci and @alitka, 

thanks a lot for your help. At the moment I am not sure when the expired certificated will be restored. Therefore, I wanted to ask if there is any other option to validate compliance with the INSPIRE directive at least for the xml document of my service?  

Many thanks.

**Comment by fabiovinci** [comment]
Dear @narinco,

you could save the GetCapabilities response as an XML file and validate it, but all tests requiring a service response will fail.

**Comment by fabiovinci** [comment]
Dear @narinco 
since the fix is on your side, we will close the issue.
