### ISSUE TITLE
WFS - The "Service Metadata" test case (TG Requirement 53) is not well implemented

### ISSUE THREAD

**Issue by fabiovinci** [INSPIRE-MIF/helpdesk-validator#780]
Dear all,

after the analysis of some issues (#718 and #771), we verified that the "Service Metadata" test case in the Download Service - 'Pre-defined WFS' Conformance Class is not well implemented because some checks, required by "TG Requirement 53" are not implemented in the ETS (Highlighted in red in the screenshot below). 

![image](https://user-images.githubusercontent.com/22212406/172343012-1b305441-3ae7-44ea-b813-83fbf18468aa.png)

As for the missing control, it will be implemented as a manual check for the moment and automated at a later stage. The [ATS](https://github.com/inspire-eu-validation/download-wfs/blob/3.1/wfs-pre-defined/service-metadata.md) will be updated accordingly.

On the contrary, in the ETS there are some additional tests not required by "TG Requirement 53" and not described in the ATS (Highlighted in red in the screenshot below).

![image](https://user-images.githubusercontent.com/22212406/172344204-6679e6ea-d318-444f-ae09-0bc5cb916718.png)

The additional tests are related to a check on the linking between dataset and service and they take into consideration some recommendations of the TG MD, for this reason, they will be removed from the "Service Metadata" test case.

**Comment by fabiovinci** [comment]
Dear all,

after a further check, we verified that the checks for the second part of the "TG Requirement 53" are already implemented, therefore if the MetadataURL is not present in the Capabilities document the validator checks that all mandatory metadata elements are provided in accordance to the mapping provided in Table 19 of the WFS TG.

![image](https://user-images.githubusercontent.com/22212406/173339903-b8803d50-83ad-4fe1-8b2a-dbb0a19b2fdf.png)

**Comment by arantzaetxebarria** [comment]
Dear all, 

The change about removing, from the "Service Metadata" test case, the additional tests related to a check on the linking between dataset and service is ready to test in [staging](http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/home/index.html) environment. 

Regards

**Comment by fabiovinci** [comment]
I tested the solution and it is ok.
We can include it in the next release.
