### ISSUE TITLE
Unable to test metadata provided as link to remote file

### ISSUE THREAD

**Issue by danieluct** [INSPIRE-MIF/helpdesk-validator#793]
When testing metadata with the reference validator (at https://inspire.ec.europa.eu/validator/test-selection/index.html ), we are unable to start tests for Metadata provided as a link. The "Start test" button doesn't do anything

![Screenshot 2022-06-22 at 11-37-48 INSPIRE Validator - Test selection](https://user-images.githubusercontent.com/6768817/174984574-59c1fb37-72fe-4484-8c51-281133a54a49.png)

Browser version: Firefox 101.0.1 and Chrome 104.0.51112.14
Link to metadata document used to test: https://inspire.meteoromania.ro/WIGOS/MD-DS
The tests work as expected when using file upload

**Comment by fabiovinci** [comment]
Dear @danieluct,

thanks for opening the issue, we will have a look.

**Comment by jenriquesoriano** [comment]
Dear @danieluct , 

the recommended behavior to introduce a service to be validated is to introduce a url of the type:
_http://example.service.url/context?service=[SERVICE]&request=GetCapabilities_ , as advised in the textbox of the interface.

![imagen](https://user-images.githubusercontent.com/25343632/175033302-15c315eb-32e6-45e6-b312-6df8c6397f80.png)

In this sense, we have implemented an enhancement to add default parameters for outputSchema and elementSetName  default parameters in case they are not provided in the URL (please see #749 ) .
This improvement considers urls formed with a question mark for the separation of the service, so we recommend, at least, to incorporate the ? at the end of the url. In that case, the validation will work without any problem.
Please try: 
https://inspire.meteoromania.ro/WIGOS/MD-DS? 

Additionally, to make the application more resilient, we are working to incorporate a fix to consider URLs without this question mark incorporated that will be released in the short term.

We will keep you informed.

Best regards

**Comment by danieluct** [comment]
@jenriquesoriano Thanks for your answer. Adding the question mark at the end fixes the issue. 

Regarding the recommendation to enter a service, it is unclear which service I should add when validating the metadata for the dataset. Adding the associated WFS Download Service (in this case https://inspire.meteoromania.ro/WIGOS/WFS?service=WFS&version=2.0.0&request=GetCapabilities ) doesn't seem to work. 

On the other hand, it seems it deals fine with CSW requests that returns metadata (such as https://inspire.meteoromania.ro/geonetwork/srv/eng/csw?service=CSW&version=2.0.2&request=GetRecordById&id=b7e35875-272e-416e-bf85-8f3789c48198 ). Maybe the instructions should be made clearer.

**Comment by jenriquesoriano** [comment]
Dear @danieluct ,

we are implementing a new feature in the UI that addresses your issue for CSW and eases the urls to be introduced for testing.
We will keep you posted for any update at this regard.
Thanks for your contribution.

Best,
