### ISSUE TITLE
ia.a.1: CRS accessible via HTTP

### ISSUE THREAD

**Issue by laers** [INSPIRE-MIF/helpdesk-validator#80]
This issues has maybe been discussed and agreed on before - I have just not been able to find it here in the repository.

In our GML file the CRS is giving like this:

plu:geometry
<gml:MultiSurface srsName="http://www.opengis.net/def/crs/EPSG/0/3044" gml:id="dk.plu.planzone.207">
gml:surfaceMember
<gml:Polygon gml:id="LOCAL_ID_120">
...

The ETS "ia.a.1: CRS accessible via HTTP" results in errors for the geometries:
"XML document 'plu260619_valid.gml', ZoningElement 'zoningelementid.206': A spatial or temporal geometry uses an unexpected coordinate reference system with identifier 'http://www.opengis.net/def/crs/EPSG/0/3044' that cannot be retrieved. Every URI must be a HTTP URI in a CRS register that when retrieved with HTTP GET returns a definition of the reference system."

Why is srsName="http://www.opengis.net/def/crs/EPSG/0/3044" an unexpected CRS? Is it listed in https://github.com/inspire-eu-validation/data/blob/3.0rc3/reference-systems/spatial.md as a valid CRS.

**Comment by josemasensio** [comment]
Dear @laers,

Thank you for your message.

We need the GML to test in the validator and replicate the error. Can you send us?

Apart from the above, what is the Conformance Class that you are testing?

Best regards.

**Comment by josemasensio** [comment]
Dear @laers,

We can not help you without the data asked above. We will close this issue instead.

Best regards.

**Comment by josemasensio** [comment]
Dear @laers,

Because of the inactivity on this issue, we decided to close it.
If you have an issue on a future, please open a new issue.

Best regards.
