### ISSUE TITLE
The inspire validator of metadata fails always (error of the test suite)

### ISSUE THREAD

**Issue by pdorio** [INSPIRE-MIF/helpdesk-validator#800]
See the attached error
![2022-06-29_08h30_14](https://user-images.githubusercontent.com/3297563/176367207-0948af3a-a867-41d5-a61c-6853a44a8a44.png)

**Comment by pdorio** [comment]
Today is working!!!

**Comment by fabiovinci** [comment]
Dear @pdorio,

thank you for the notification.
It was due to the temporary unavailability of the INSPIRE Registry.

Please reopen the issue or open a new one if the problem persists.
