### ISSUE TITLE
Dataset validation : Site (AF-Theme)

### ISSUE THREAD

**Issue by Dnoack49** [INSPIRE-MIF/helpdesk-validator#809]
Dear all,

I have validated these two AF-Datasets:

**Holding**
https://inspire.brandenburg.de/services/af_tiere_wfs?service=WFS&version=2.0.0&request=GetFeature&typenames=af:Holding&Count=10 

Site
https://inspire.brandenburg.de/services/af_tiere_wfs?service=WFS&version=2.0.0&request=GetFeature&typenames=af:Site&Count=10 

For the Site-Objects the following error in the conformance class **GML application schemas, Agricultural and Aquaculture** (_Basic test / af-gml.a.1: Agricultural and Aquaculture Facilities feature in dataset_) is thrown:
![grafik](https://user-images.githubusercontent.com/8046960/176650085-9c537305-2a45-4559-b276-835d0f25c172.png)

Here both reports for comparison: 
[test suite Annex III - Agricultural and aquaculture facilities (AF).zip](https://github.com/INSPIRE-MIF/helpdesk-validator/files/9018767/test.suite.Annex.III.-.Agricultural.and.aquaculture.facilities.AF.zip)

This is related to the issue #440 and #798.

Kind Regards

**Comment by fabiovinci** [comment]
The related [ATS](https://github.com/inspire-eu-validation/data-af/blob/master/af-gml/basic.md) has been modified accordingly, and the change will be soon added in staging for the test.

**Comment by arantzaetxebarria** [comment]
Dear @Dnoack49 

The fix for this issue is ready in [staging ](http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/test-selection/index.html) environment, could you please verify?

Regards

**Comment by Dnoack49** [comment]
Dear @arantzaetxebarria ,
I have just tested it and can confirm, that the error does not occur anymore - it works as expected.
Thanks alot.
