### ISSUE TITLE
Problem using ETF INSPIRE Validator with HTTP Basic Authentication

### ISSUE THREAD

**Issue by ghost** [INSPIRE-MIF/helpdesk-validator#81]
When running the ETF INSPIRE Validator (WFS 2.0 Direct and WMS 1.3.0) there seems to be a problem with calling OGC TeamEngine.

Internal problem to generate the report – contact ETF administrator
ERROR Response status code:401 is not in acceptable list of status codes

Steps to reproduce:

1. choosing 'Conformance Class: Download Service -Direct WFS' (same for 'Conformance Class: View Service - WMS')
2. enter 'Service URL'
3. enter 'Credentials'
4. press Start
5. retrieve Results ind 'WFS 2.0 (OGC 09-025r2/ISO 19142) Conformance Test Suite

Getting Error: (see Screenshot)
![tmphttpbasic](https://user-images.githubusercontent.com/38787131/60592550-29514c00-9da1-11e9-905d-6a83b2ec8f7e.jpg)

Expected Behavior:
Results from OGC Team Engine

Seems to be a problem submitting user and password when requested from server?

**Comment by josemasensio** [comment]
Dear @DeordD,

Thank you for your message.

Could you provide us the service that you are testing?

Best regards.

**Comment by josemasensio** [comment]
Dear @DeordD,

Without credentials and the Service URL we can not test and fix this issue. We will close this issue if you not send the necessary data.

Regards.

**Comment by ghost** [comment]
I already forwarded credentials for WFS and WMS on July 5 to idiazdecerio@bilbomatica.es. 

see:
https://github.com/inspire-eu-validation/community/issues/82#issuecomment-508705952

**Comment by josemasensio** [comment]
Dear @DeordD,

Apologise, I got confused and did't remember that we already were looking for a solution for both issues, but the credentials you sent us got expired. 
Please, can you sent us new credentials again?

Best regards.

**Comment by ghost** [comment]
I will inform you regarding credentials at the end of August/beginning of September.

Kind regards.

**Comment by josemasensio** [comment]
Dear @DeordD,

Thank you. We will be waiting your message.

Greetings.

**Comment by ghost** [comment]
Hi,

Credentials are extended until 30.09.2019.

We are looking forward to new information from your side.

Thanks.

**Comment by carlospzurita** [comment]
Dear @DeordD 
We would need you to request the extension of the credentials, as we are still working in solving this issue.

Thanks and sorry for the inconveniences.

**Comment by ghost** [comment]
Hi @carlospzurita

Credentials are extended.

We are looking forward to new information from your side.

Thanks.

**Comment by danielnavarrogeo** [comment]
Dear @DeordD 

We have been working on the WMS authentification issue reported by you. You can now test it in [staging](http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/).

Could you please provide us feedback about the implemented solution?

Regarding WFS authentification, we are still working on it.

Regards

**Comment by ghost** [comment]
Dear @danielnavarrogeo ,

the probem with WMS 1.3.0 authentification is solved.

Thanks a lot for the fix.

Kind regards

**Comment by carlospzurita** [comment]
Dear @DeordD 

We have depoyed a solution for the inclusion of service credentials in OGC TEAM engine validation. You can check it on the [staging instance](http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp)

Kind regards.

**Comment by carlospzurita** [comment]
Dear  @DeordD 

We have uploaded to the [staging instance](http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/) a solution for the authentication in the TEAM engine validation. Please let us know if everything is correct.

Kind regards.

**Comment by carlospzurita** [comment]
Dear @DeordD
Does the solution published in staging solves the authentication issue?

**Comment by ghost** [comment]
Dear @carlospzurita ,

The problem is also solved for WFS 2.0 Direct. 

In my opinion you can close this issue,

Kind regards,

**Comment by danielnavarrogeo** [comment]
Dear @DeordD 

Thank you for your feedback.

Regards
