### ISSUE TITLE
at57-getmap-format-parameter error in WMS

### ISSUE THREAD

**Issue by Kate-Lyndegaard** [INSPIRE-MIF/helpdesk-validator#811]
Hello,

I am receiving an error in at57-getmap-format-parameter for this [WMS](https://test.haleconnect.de/ows/services/org.473.c5941548-88c4-4533-b65a-1e3e46015edb_wms?SERVICE=WMS&REQUEST=GetCapabilities&VERSION=1.3.0) service on the staging instance.

The error message states: "Not found image format in capabilities document to perform a GetMap request."

The WMS GetCapabilities does contain a list of available image formats, however.

Test report:
[Test run on 09 12 - 11.07.2022 with test suite Conformance Class View Service WMS.html.zip](https://github.com/INSPIRE-MIF/helpdesk-validator/files/9081675/Test.run.on.09.12.-.11.07.2022.with.test.suite.Conformance.Class.View.Service.WMS.html.zip)

Could you please tell me why we are receiving this error?

Kind regards,
Kate

**Comment by fabiovinci** [comment]
Dear @Kate-Lyndegaard,

I tested your service in staging and the error is no longer present, see the report: http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/test-run/details.html?id=EID9b5264df-7171-45a0-8e34-54d4ac7eee80

It was probably due to the temporary unavailability of the service since, looking at the report you attached, all the tests under the "GetMap_Operation" test module are in an "Undefined" status. 

Could you please check and confirm?
Thanks

**Comment by Kate-Lyndegaard** [comment]
Dear @fabiovinci,

I can see that the "GetMap_Operation" is no longer returning an error, but the test now contains the error for https://github.com/INSPIRE-MIF/helpdesk-validator/issues/773 again. 

Do you know why that would be?

Kind regards,
Kate

**Comment by fabiovinci** [comment]
Dear @Kate-Lyndegaard,

I tested again your WMS again in both instances and the error in the _at57-getmap-format-parameter_ test is again present, on the contrary, the error for the _at42-getcapabilities-layer-default-style_ test is no longer present.

Attached the latest reports 
[18-07_17-25_42-no_57_yes.zip](https://github.com/INSPIRE-MIF/helpdesk-validator/files/9133309/18-07_17-25_42-no_57_yes.zip)

It is very strange but they appear to exclude each other.

We will investigate further.

**Comment by arantzaetxebarria** [comment]
Dear @Kate-Lyndegaard 

Regarding the error  at42-getcapabilities-layer-default-style we have found that in your [WMS example](https://test.haleconnect.de/ows/services/org.473.c5941548-88c4-4533-b65a-1e3e46015edb_wms?SERVICE=WMS&REQUEST=GetCapabilities&VERSION=1.3.0), one style  is present without the _.Default_
```
<Style>
<Name>AM.WaterBodyForWFD</Name>
<Title>AM.WaterBodyForWFD</Title>
```

We think that if you put _AM.WaterBodyForWFD.Default_  the error will be fixed.
Please, let us know if the change corrects the problem.

Regards, 
Arantza

**Comment by Kate-Lyndegaard** [comment]
Dear @arantzaetxebarria,

Thank you, this is the cause of the error. I apologize for not catching that one.

Kind regards,
Kate
