### ISSUE TITLE
WFS tests not working

### ISSUE THREAD

**Issue by JohannaOtt** [INSPIRE-MIF/helpdesk-validator#812]
When trying to validate a WFS (for example [this one](https://haleconnect.com/ows/services/org.789.ffa9f2a0-54d8-4f18-961c-196230496a0a_wfs?SERVICE=WFS&REQUEST=GetCapabilities&VERSION=2.0.0)) with the validator, the OGC conformance test suite is running into a timeout and other tests report back "The server experienced a several unexpected error. Please, try again later. if the problem persist, please contact with the helpdesk."

To help us investigate the issue, you may want to include:

- [ ] a description of the steps to reproduce your issue: test the WFS linked above against the Direct WFS test in the validator
- [ ] the browser and version used: Firefox 102.0.1 on Windows
- [ ] a screenshot illustrating the problem: 
![grafik](https://user-images.githubusercontent.com/34163838/178213527-093d6d55-d068-47af-b80c-f114a28c7e56.png)
![grafik](https://user-images.githubusercontent.com/34163838/178213675-52c6f07e-d7db-432f-a92e-731cc6475774.png)
- [ ] the Test Report (ideally as an attachment to the issue)
[Uploading Test run on 09 05 - 11.07.2022 with test suite Conformance Class Direct WFS.html.zip…]()
- [ ] the name of the Test that failed: many tests

**Comment by fabiovinci** [comment]
Dear @JohannaOtt,

regarding the OGC conformance test suite, we validated your service with the [OGC validator](https://cite.opengeospatial.org/teamengine/) and we verified it takes a lot of time, but we need to set a timeout (currently 20 minutes) in order not to leave many tests running for a long time.

Regarding the errors raised by the INSPIRE Validator, we are investigating them.

**Comment by JohannaOtt** [comment]
> Regarding the errors raised by the INSPIRE Validator, we are investigating them.

@fabiovinci Are there any news on this?

**Comment by fabiovinci** [comment]
Dear @JohannaOtt,

the issue seems similar to issue 877 ([see my comment](https://github.com/INSPIRE-MIF/helpdesk-validator/issues/877#issuecomment-1323536979)).

Could you please verify why the server, which exposes the WFS, replies with an error when port 443 is added to the URL?

**Comment by fabiovinci** [comment]
Dear @JohannaOtt ,

it seems the error related to port 443 has been identified and solved, please have a look at the latest comments on issue #774.

So, you should remove the explicit port declaration in the URLs in the GetCapabilities document.

**Comment by JohannaOtt** [comment]
@fabiovinci I can confirm that the INSPIRE Validator tests are executed without that many errors by now. So this ticket can be closed IMO.
