### ISSUE TITLE
Error without test report

### ISSUE THREAD

**Issue by ZotZot56** [INSPIRE-MIF/helpdesk-validator#818]
My issue
- I am trying to test a WMS service
- [Browser Edge Versione 103.0.1264.71 (Build ufficiale) (64 bit)
- I attach the screenshot of the error
- There is no test report, this is the problem
- the name of the Test that failed is "Test run on 16:23 - 25.07.2022 with test suite Conformance Class View Service WMS"
- Getcapabilities request: https://inspiretest.gmatics.eu/geoserver?service=wms&request=GetCapabilities

Best regards, Riccardo Zuco
![ErrorMessage](https://user-images.githubusercontent.com/109971966/180801344-d1f7af72-ab95-4af7-a45b-60ec695d1013.JPG)

**Comment by fabiovinci** [comment]
Dear @ZotZot56,

the link you provided seems to redirect to the following: https://inspiretest.gmatics.eu/geoserver/web/ 

Could you please check it to verify that it is a valid GetCapabilities response?

**Comment by ZotZot56** [comment]
Dear Fabio, I created a QGIS project and, using the same link, I succeeded to create a connection and
***@***.***

so I add the test layer

***@***.***


Da: Fabio ***@***.***>
Inviato: lunedì 25 luglio 2022 17:09
A: ***@***.***>
Cc: Riccardo ***@***.***>; ***@***.***>
Oggetto: Re: [INSPIRE-MIF/helpdesk-validator] Error without test report (Issue #818)


Dear @ZotZot56<https://github.com/ZotZot56>,

the link you provided seems to redirect to the following: https://inspiretest.gmatics.eu/geoserver/web/

Could you please check it to verify that it is a valid GetCapabilities response?

**Comment by fabiovinci** [comment]
Dear @ZotZot56,

I tried again using the following URL: https://inspiretest.gmatics.eu/geoserver/ows?service=wms&version=1.3.0&request=GetCapabilities and the response in the browser seems ok and also in QGIS.

In any case, it seems that this issue is caused by the fact that the certificate has not been added to the repository.
Could you provide us with your organization certificate in order to add it?
Thank you in advance.

**Comment by fabiovinci** [comment]
Dear @ZotZot56,

do you still have the issue? It seems that your service is no longer available.

**Comment by fabiovinci** [comment]
Dear @ZotZot56,

since there was no response we will close the issue, please reopen it if the error persists.
