### ISSUE TITLE
Pre-defined ATOM validation does not run to completion

### ISSUE THREAD

**Issue by mwjsanders** [INSPIRE-MIF/helpdesk-validator#819]
When starting the Pre-defined Atom test for https://service.pdok.nl/kadaster/cp/atom/v1_0/index.xml, I expect the test to run to completion with a testresult of at least FAILED. however the test seems to run forever.

I started a _Pre-defined Atom_ test for the atom feed with endpoint https://service.pdok.nl/kadaster/cp/atom/v1_0/index.xml

After starting the test the test seems to be running forever and the browser keeps showing the in progress screen:

![image](https://user-images.githubusercontent.com/22592588/181262750-e254eb85-b595-4b5d-a194-ec350d9e0a66.png)

While monitoring the network traffic in the browser, I see the browser is polling for the test result with request

`https://yzyiqfakm4.execute-api.eu-west-1.amazonaws.com/validator/v2/TestRuns/EID5b91be5e-a0c9-4b91-8f45-3054dab19950.json?_=1658927182621` 

and finally gets an error response:
```
{"error":"TestRunDao: An object with the id \u00225b91be5e-a0c9-4b91-8f45-3054dab19950\u0022 could not be found!","timestamp":"1658927686774","url":"http://inspire-validator.eu-west-1.elasticbeanstalk.com:8080/validator/v2/TestRuns/EID5b91be5e-a0c9-4b91-8f45-3054dab19950.json","stacktrace":["de.interactive_instruments.exceptions.ObjectWithIdNotFoundException: TestRunDao: An object with the id \u00225b91be5e-a0c9-4b91-8f45-3054dab19950\u0022 could not be found!","\tat de.interactive_instruments.etf.dal.dao.basex.AbstractBsxDao.getById(AbstractBsxDao.java:209)","\tat de.interactive_instruments.etf.dal.dao.PreparedDtoResolver.getById(PreparedDtoResolver.java:49)","\tat de.interactive_instruments.etf.webapp.controller.StreamingService.asJson2(StreamingService.java:161)","\tat de.interactive_instruments.etf.webapp.controller.TestResultController.testRunByIdJson(TestResultController.java:381)","\tat sun.reflect.GeneratedMethodAccessor177.invoke(Unknown Source)","\tat sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)","\tat java.lang.reflect.Method.invoke(Method.java:497)","\tat org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)","\tat org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:133)","\tat org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:97)","\tat org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:827)","\tat org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:738)","\tat org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)","\tat org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:967)","\tat org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:901)","\tat org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)","\tat org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:861)","\tat javax.servlet.http.HttpServlet.service(HttpServlet.java:687)","\tat org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)","\tat javax.servlet.http.HttpServlet.service(HttpServlet.java:790)","\tat org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:821)","\tat org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1685)","\tat de.interactive_instruments.etf.webapp.filter.ApiFilter.doFilterInternal(ApiFilter.java:89)","\tat org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)","\tat org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:347)","\tat org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:263)","\tat org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1668)","\tat org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:581)","\tat org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)","\tat org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)","\tat org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:226)","\tat org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1158)","\tat org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:511)","\tat org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)","\tat org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1090)","\tat org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)","\tat org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:213)","\tat org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:109)","\tat org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:119)","\tat org.eclipse.jetty.server.Server.handle(Server.java:517)","\tat org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:308)","\tat org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:242)","\tat org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:261)","\tat org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)","\tat org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:75)","\tat org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceAndRun(ExecuteProduceConsume.java:213)","\tat org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:147)","\tat org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:654)","\tat org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:572)","\tat java.lang.Thread.run(Thread.java:745)"]}
```
It looks like the test get cancelled and removed.

Could you please give some insight why the test for this service fails. There are no test results or logging files available for me to analyse after the test seems to be stuck.
Is this an error in the inspire validator or is something wrong with our Atom feed https://service.pdok.nl/kadaster/cp/atom/v1_0/index.xml

**Comment by fabiovinci** [comment]
Dear @mwjsanders,

you are right, the behaviour is very strange, we will investigate further and let you know.

**Comment by dperezBM** [comment]
Dear @mwjsanders,

It looks that your issue is related with #745 as the service downloads a big size file that the validator can't handle. So the validator gives an out of memory error and the test can't end properly.

**Comment by mwjsanders** [comment]
Thanks @dperezBM for looking into this issue.
Handling large file sizes should not be something which would result the validator to crash. Is this something that can be fixed by for example offloading the download file to disk or skip the file content assertions for large file size and set them to manual?

**Comment by fabiovinci** [comment]
Dear @mwjsanders,

we reviewed the requirements for which the validator downloads the file, (i.e. [_Req. 43_](https://github.com/INSPIRE-MIF/technical-guidelines/blob/main/services/download-atom-wfs/DownloadServices.adoc#544-opensearch-description-get-spatial-data-set-operation-template) and [_Req. 44_](https://github.com/INSPIRE-MIF/technical-guidelines/blob/main/services/download-atom-wfs/DownloadServices.adoc#545-opensearch-description-spatial-dataset-identifiers)) and verified that we can test them avoiding the download.

In particular:

- for _Req. 43_, the validator will check that the content-type of the Get Spatial Data Set response is the same as that stated in the OpenSearch Description document without downloading the file;
- for _Req. 44_, we reformulated the related [ATS](https://github.com/inspire-eu-validation/download-service/blob/master/atom-pre-defined/opensearch-description-query-examples-for-each-dataset.md) and the validator will check the HTTP response code without downloading the file.

We will implement these fixes in staging and let you know when are ready for testing.

**Comment by arantzaetxebarria** [comment]
Dear @mwjsanders 

We have implemented a solution to avoid the download. Also, we have modified the test following the changes made for Req 44 in the [ATS](https://github.com/inspire-eu-validation/download-service/blob/master/atom-pre-defined/opensearch-description-query-examples-for-each-dataset.md).

These changes are ready to test in staging environment, could you please verify that all is working as expected? Thanks

Best regards

**Comment by mwjsanders** [comment]
@arantzaetxebarria 
I have tested 2 atom services that did not run to completion before:
- https://service.pdok.nl/rws/nwbwegen/atom/index.xml
- https://service.pdok.nl/cbs/wijkenbuurten/2022/atom/index.xml
In the staging environment these services are successfully validated. So this issue seems to be resolved.
Thanks!
