### ISSUE TITLE
Problem using ETF INSPIRE Validator with KVP-Authentication

### ISSUE THREAD

**Issue by ghost** [INSPIRE-MIF/helpdesk-validator#82]
When running the ETF INSPIRE Validator (WFS 2.0 Direct and WMS 1.3.0) there seems to be a problem with calling OGC TeamEngine.

Steps to reproduce:

1. choosing 'Conformance Class: Download Service -Direct WFS' (same for 'Conformance Class: View Service - WMS')
2. enter 'Service URL'
3. enter Parameters user and password as Endpoint (attachet to Service
4. press Start

Getting Error: (see Screenshot)
![tmpkvp](https://user-images.githubusercontent.com/38787131/60593268-ad580380-9da2-11e9-81e6-3e14c9d10148.jpg)

Expected Behavior:
Results from Testclass

Seems to be a problem submitting user and password when requested from server?

**Comment by josemasensio** [comment]
@DeordD thank you again for your message. 

We need the service to test it on the validator.

Thank you in advance, best regards.

**Comment by ghost** [comment]
Thanks a lot for the answer.

Could you please give me an official e-mail address where i can provide test service?

Thanks in advance.

**Comment by josemasensio** [comment]
Yes, you can send the service to idiazdecerio@bilbomatica.es.

Regards.

**Comment by ghost** [comment]
Credentials for WFS and WMS were forwarded on July 5 to idiazdecerio@bilbomatica.es.

**Comment by ghost** [comment]
https://github.com/inspire-eu-validation/community/issues/81#issuecomment-521923385

**Comment by ghost** [comment]
Hi,

Credentials are extended until 30.09.2019.

We are looking forward to new information from your side.

Thanks.

**Comment by carlospzurita** [comment]
Dear @DeordD 
We would need you to request the extension of the credentials, as we are still working in solving this issue.

Thanks and sorry for the inconveniences.

**Comment by ghost** [comment]
Hi @carlospzurita,

Credentials are extended.

We are looking forward to new information from your side.

Thanks.

**Comment by carlospzurita** [comment]
Dear  @DeordD 

We have uploaded to the [staging instance](http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/) a solution for the authentication in the TEAM engine validation. Please let us know if everything is correct.

Kind regards.

**Comment by carlospzurita** [comment]
Dear @DeordD 
Does the solution published in staging solves the authentication issue?

**Comment by ghost** [comment]
Hi @carlospzurita ,

I didn't have time to check it. 

Do you need my feedback before 13.03. in order to provide this improvement in the next version?

**Comment by carlospzurita** [comment]
Yes, it would be very much appreciated. Thank you

**Comment by ghost** [comment]
Ok, I will give my best to give you a feedback today for all issues where I am assigned to.

**Comment by ghost** [comment]
Hi @carlospzurita ,

i have just validated the WMS service I have encountered some problems.

In the log file following message is shown:
13.03.2020 09:28:04 - TestRunTask initialized
13.03.2020 09:28:04 ERROR Response status code:401 is not in acceptable list of status codes

In the report following problem is stated:
![grafik](https://user-images.githubusercontent.com/38787131/76608466-f0639c80-6515-11ea-9e85-301c4a385f8a.png)

In the initial-testcase following is stated:
![grafik](https://user-images.githubusercontent.com/38787131/76608569-24d75880-6516-11ea-9c74-b364abe5fdc0.png)

Can you reproduce obtained errors?
Is there a problem with the service or initial problem with KVP is still not solved?

**Comment by danielnavarrogeo** [comment]
Dear @DeordD 

For services WMS, WMTS, WCS and CSW the authentification shall be done using the credentials section. 

![imagen](https://user-images.githubusercontent.com/45062523/76611981-b39aa400-651b-11ea-9cc7-a3796d1ffebe.png)

KVP for these services is not supported.

Regards

**Comment by ghost** [comment]
Dear @danielnavarrogeo ,

thanks a lot for the information. 

Is KVP supported for Direct WFS?

**Comment by danielnavarrogeo** [comment]
Yes, KVP is supported in Direct WFS.

Regards

**Comment by ghost** [comment]
Dear @danielnavarrogeo 

The problem is solved for Direct WFS:
![grafik](https://user-images.githubusercontent.com/38787131/76614319-1beb8480-6520-11ea-98a8-bcd9ba01e554.png)

The problem for WMS doesn't have to be solved because KVP for WMS is not supported in the validator.

In my opinion this issue can be closed.

**Comment by danielnavarrogeo** [comment]
Thank you very much for your feedback @DeordD.

Regards
