### ISSUE TITLE
Rollout of INSPIRE Registry using Re3gistry v.2

### ISSUE THREAD

**Issue by jenriquesoriano** [INSPIRE-MIF/helpdesk-validator#820]
Dear INSPIRE validator community,

we are experiencing some issues with regard to the rollout of the Registry related to the access to Registry resources.
Please excuse the inconvenience. 
We will keep you posted.

Best regards,

**Comment by juanpelegrina** [comment]
Dear INSPIRE validator community,

The INSPIRE validator is working as expected. In the second attempt to roll out the INSPIRE Registry based on Re3gistry 2.3.1 today, there were some affectations on the Executable Test Suites.

As a result, the rollout is postponed, waiting for preparing proper integration tests between both applications.
We will provide more details about the new rollout date by using this thread (probably taken place in September 2022).
Excuses for any inconveniences caused today.

Regards
