### ISSUE TITLE
SNI Error validating services

### ISSUE THREAD

**Issue by stevenf** [INSPIRE-MIF/helpdesk-validator#823]
Hi,

We are validating some download and view services but encounter error we previously didn't encounter. It now appears the INSPIRE Validator cannot access the URL as the "Server Name Indication" is not supplied to our server.

When testing 
https://www.gdngeoservices.nl/inspire/downloads/services.atom
or https://www.gdngeoservices.nl/inspire/downloads/aardwarmte.atom
or https://www.gdngeoservices.nl/inspire/wms/oppervlaktegeologie?service=WMS&request=GetCapabilities&service=WMS&version=1.3.0

The INSPIRE Validator immediately seems to fail on "Check URL is accessible" (atom-feed download) or "http-request"  (WMS service).
When I click "Open saved response" the following error shows for both the view and download services:
```
Forbidden
You don't have permission to access this resource.Reason: The client software did not provide a hostname using Server Name Indication (SNI), which is required to access this server.
```
It appears to me the SNI is not supplied. Could it be this has been supplied before as previously we did not get this error? Or 

Thanks in advance!
Steven

**Comment by jenriquesoriano** [comment]
Dear @stevenf 
it seems to be related to the TLS protocol that is being used for the https connection of the related services.
Can you tell us if the certificates used or the protocols supporting https connections to your premises have been updated recently?
Thanks a lot

**Comment by stevenf** [comment]
Dear @jenriquesoriano ,
Thanks for your reaction! 
I asked our system administrators previously and they said we have been using SNI (which was mentioned in the error message) for ages.  I've sent your question to them, they were going to look into it again. So hopefully I have some updates soon.

**Comment by jenriquesoriano** [comment]
thanks for your feedback, the question is more related to changes on the TLS version that may differ the use of the SNI on the currently deployed instance of the Validator.

**Comment by stevenf** [comment]
@jenriquesoriano
One of sysadmins look at it and he noticed our WMS service was indeed called by the INSPIRE validator. It starts with a user-agent "ETF validator (2.0.0-b210423T1152)". This one works. And then another user-agent: "Apache-HttpClient/4.2.5 (java 1.5)". This one fails. 
The sysadmin says SNI is not supported by Java 1.5, which seems to be a really old Java version (I really don't understand it as the Validator did validate these services some months ago)

**Comment by stevenf** [comment]
@jenriquesoriano 
On advise of a colleague I ran a tool to check the TLS/SSL connection to out service. This tool (https://www.ssllabs.com/ssltest/analyze.html?d=acc.gdngeoservices.nl) does work.
![image](https://user-images.githubusercontent.com/80469380/190339381-135e1bd4-4bb0-4871-878f-6544a90a5a42.png)

**Comment by jenriquesoriano** [comment]
Dear @stevenf , 

thanks for reporting the issue and your valuable feedback.

We have investigated this issue from different perspectives taking into account your help, giving us as much information as we requested. 
This problem seems to be an error of TLS versions, because as the version of java we are using doesn't support TLS version 1.3 which you use in your domain in the communication (TLS 1.2 also supported as you pointed in the previous comment, but doesn't seem to be the case). 

We are working on the release of a new version of the ETF for the INSPIRE Reference Validator based on Java 11 which will allow to establish connections using TLS 1.3.
Keep you posted.

Best,

**Comment by stevenf** [comment]
Dear @jenriquesoriano,

Thanks for your reaction! Do you have any idea when a new version of the ETF for the INSPIRE Reference Validator will be released?

Best regards,
Steven

**Comment by stevenf** [comment]
Dear @jenriquesoriano,

We are still getting the same error when using the Validator. I wondered if the new version of the Validator based on Java 11 was released indeed? 

Best regards, Steven

**Comment by jenriquesoriano** [comment]
Dear @stevenf ,

we are progressing testing a beta version of the INSPIRE Reference Validator using the new version of the ETF 2.1.
There are still some issues we need to address in order to obtain a fully operational INSPIRE Reference Validator.
As soon it is ready for testing, it will be announced so you can verify its correct functioning.

Best regards

**Comment by manuelaromero-guadaltel** [comment]
Dear @stevenf,
we have published [v2023.2 release](https://github.com/INSPIRE-MIF/helpdesk-validator/releases/tag/v2023.2) containing a version of ETF v2.0 using java 11 which as we have commented previously, can potentially solve your issue. This version is already in the production and staging instance, so you can test it out in any of them. Please inform us if there is any more issues.

**Comment by fabiovinci** [comment]
Dear @stevenf,
were you able to solve the issue?
Did you try with the [latest version](https://github.com/INSPIRE-MIF/helpdesk-validator/releases/tag/v2023.2)?

**Comment by fabiovinci** [comment]
Dear @stevenf,

it seems the Validator is now able to validate your services.
We will therefore consider the issue as solved.

**Comment by stevenf** [comment]
Sorry for my late response. Indeed the issues were solved!
