### ISSUE TITLE
MD - Allow creation and revision dates for MD_Keywords

### ISSUE THREAD

**Issue by fabiovinci** [INSPIRE-MIF/helpdesk-validator#824]
According to the [MD TG change proposal](https://github.com/INSPIRE-MIF/technical-guidelines/issues/18), already endorsed and released with the [TG 2022.2 release](https://github.com/INSPIRE-MIF/technical-guidelines/releases/tag/v2022.2), the validator check related to the CI_DateTypeCode element of the MD_Keywords will be relaxed and the values `revision` and `creation` will be also allowed, in addition to the value `publication`.

The [related ATS](https://github.com/inspire-eu-validation/metadata/blob/2.0/common/keyword-originating-cv.md) has been already amended.

@dperezBM, @arantzaetxebarria, could you please modify the related ETS (it should be [this one](https://github.com/inspire-eu-validation/ets-repository/blob/a38ba6c676d72916cc7b1861b29e5ef674622757/metadata/2.0/common/ets-md-common-bsxets.xml#L617-L654)), thanks.

**Comment by dperezBM** [comment]
Hi @fabiovinci,
We are making the changes to relax this validation.

**Comment by fabiovinci** [comment]
I tested the solution already available in staging and it is ok.
We can include the fix in the next release.
