### ISSUE TITLE
remotefile without querystring leads to an error

### ISSUE THREAD

**Issue by rtrier** [INSPIRE-MIF/helpdesk-validator#829]
If a remotefile without a query string is validated the Javascript throws an error
This is obviously an error in the js code:
File: controller.js
Function: sendRunRequest

```
if (remoteFile != "") {


   if ($scope.select.typeResource == "metadata"){
				    var params = remoteFile.split("?");
				    var properties=[]
				    params=params[1] // params=undefined if remoteFile without ?
				    params=params.split("&") // undefined.split_ ERROR
				    var i=0
				    while (i<params.length){
				        var tempParams=params[i]
				        properties.push(tempParams.split("=")[0])
```				 

params=params[1]    **_// params=undefined if remoteFile without ?_**
params=params.split("&") **_// undefined.split_ ERROR**

**Comment by jenriquesoriano** [comment]
Dear @rtrier ,

thank you for contacting us and reporting the issue.
It seems to be related with the UI, as you point, indeed.
Could you please provide us with the URL you're testing as well as the selected test (metadata presumed), so we can reproduce the issue?
Thanks a lot!

Best

**Comment by rtrier** [comment]
Hallo Jenri,

it **must** happen if someone has metadata as an link  pointing to a file like metadata.xml

I had forgetten the params:
https://gis-bldam-brandenburg.de/inspire-bodendenkmale-view/ps/ows

Greeting Ralf

**Comment by jenriquesoriano** [comment]
Dear @rtrier , 

thanks for your feedback.
We're actually assessing in which extent we should complete this kind of query and correct the intended behaviour as a question mark is requested for the proper processing of the link.
We will keep you posted with the outcome of this analysis and the final decission at this regard.

Best,

**Comment by tilmanb** [comment]
I experienced the same behaviour. A workaround is to just add a "?" after the URL.

**Comment by fabiovinci** [comment]
Dear @rtrier,

were you able to test the suggested solution to add a "?" after the URL?

**Comment by rtrier** [comment]
Dear @fabiovinci 
Just tested. It's working as expected, with and without a "?".  Issue can be closed.
