### ISSUE TITLE
Sea Regions - SeaBedArea fails geometry constraint test

### ISSUE THREAD

**Issue by robblis** [INSPIRE-MIF/helpdesk-validator#830]
Hi Validator Team,

We are working on validating our Sea Regions theme.

When testing the SeaBedArea feature type we see the following failures for the Conformance Class 'Application schema, Sea Regions' > constraints > geometry test...

_XML document 'service.xml', SeaBedArea 'srSeaBedAreaS.6001': The constraint 'the geometry element is represented as either a surface or a point' is violated. 
XML document 'service.xml', SeaBedArea 'srSeaBedAreaS.6002': The constraint 'the geometry element is represented as either a surface or a point' is violated._ 

We are returning the following XML regarding the geometry...

_<sr:geometry>
  <gml:Polygon gml:id="srSeaBedAreaS.ifcid.6001.Shape.Geom_0" srsName="http://www.opengis.net/def/crs/EPSG/0/4258" srsDimension="2">
    <gml:exterior>
      <gml:LinearRing>
        <gml:posList>-14.323404255000 56.872340426000 -26.119148936000 90.995744681000 -54.344680851000 102.370212766000 -64.034042553000 104.897872340000 -96.472340426000 77.093617021000 -101.106382979000 55.608510638000 -99.421276596000 9.689361702000 -99.421276596000 -18.114893617000 -85.097872340000 -42.127659574000 -60.242553191000 -47.182978723000 -30.753191489000 -28.646808511000 -15.165957447000 16.429787234000 -14.323404255000 56.872340426000</gml:posList>
      </gml:LinearRing>
    </gml:exterior>
  </gml:Polygon>
</sr:geometry>_

We believe that the gml:Polygon is a valid surface type. Please see https://github.com/INSPIRE-MIF/helpdesk-validator/issues/458 for a similar issue and resolution. I've attached the service returned XML file.

We see the same constraint error for the SeaSurfaceArea feature type as well.

Please advise.

Thanks,
Robert
[SR_SeaBedArea_Service.zip](https://github.com/INSPIRE-MIF/helpdesk-validator/files/9397602/SR_SeaBedArea_Service.zip)

**Comment by fabiovinci** [comment]
Dear @robblis,

since a similar issue has been already discussed and solved, we will apply the same change also for the SR data theme.

**Comment by fabiovinci** [comment]
The related [ATS](https://github.com/inspire-eu-validation/data-sr/blob/master/sr-as/constraints.md) has been modified.

@dperezBM, @arantzaetxebarria, could you please update the related ETS? Thanks

**Comment by dperezBM** [comment]
Dear @robblis
The solution is in staging environment. Could you verify that the validation is now correct?
Regards

PS: @fabiovinci could you also check it?

**Comment by fabiovinci** [comment]
The fix is ok for me.
It can be included in the next release.

**Comment by robblis** [comment]
Hi @dperezBM ,

We've re-tested on staging and the tests pass for SeaBedArea and SeaSurfaceArea.

Thanks for the update.

Robert
