### ISSUE TITLE
Determination of correct template for GetSpatialDataset-query in Atom-Feed / OpenSearch is subject to errors

### ISSUE THREAD

**Issue by ejn** [INSPIRE-MIF/helpdesk-validator#835]
For the [test of the GetSpatialDataset operation via Atom / OpenSearch](https://github.com/inspire-eu-validation/download-atom/blob/master/atom-pre-defined/opensearch-description-one-url-get-spatial-dataset-operation.md) the template URL is currently determined as follows:
```
def getSpatialDataSetUrlTemplates = xmlHolder.getDomNodes(
	"/*:OpenSearchDescription/*:Url[@rel='results' and starts-with(@template,'http') and "+
	"contains(@template,'crs') and contains(@template,'spatial_dataset_identifier_code') and "+
	"contains(@template,'spatial_dataset_identifier_namespace') and contains(@template,'language')]");
```

Should the required OpenSearch-URLs (with `type` `application/atom+xml` and `text/xml` respectively) happen to also contain these strings then they will be incorrectly interpreted as GetSpatialDataset-URLs, leading to validation failures.

This could be avoided if the determination of the templates adds additional negative filters for `@type='application/atom+xml'` and `@type='text/xml'`, so that only the remaining `Url`-elements with `rel="results"` are interpreted as GetSpatialDataset-templates.

Example OpenSearchDescription which currently causes a false interpretation (only the final `Url` with `type="application/gml+xml` is a GetSpatialDataset template):
```xml
<?xml version="1.0" encoding="UTF-8"?>
<OpenSearchDescription xmlns="http://a9.com/-/spec/opensearch/1.1/" xmlns:inspire_dls="http://inspire.ec.europa.eu/schemas/inspire_dls/1.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://a9.com/-/spec/opensearch/1.1/ OpenSearch.xsd">
	<Description>OpenSearchDescription für INSPIRE-ATOM XXX</Description>
	<Tags>INSPIRE-ATOM XXX</Tags>
	<ShortName>INSPIRE-ATOM XXX</ShortName>
	<LongName>INSPIRE-ATOM XXX</LongName>
	<Language>de</Language>
	<Contact>admin@beispiel.de</Contact>
	<Url type="application/opensearchdescription+xml" rel="self" template="http://beispiel.de/atom/search"/>
	<Url type="application/atom+xml" rel="results" template="http://beispiel.de/atom/search?spatial_dataset_identifier_code=12345&amp;spatial_dataset_identifier_namespace=http://beispiel.de&amp;crs=EPSG:25832&amp;language=de&amp;q={searchTerms}"/>
	<Url type="text/html" rel="results" template="http://beispiel.de/atom/search?spatial_dataset_identifier_code=12345&amp;spatial_dataset_identifier_namespace=http://beispiel.de&amp;crs=EPSG:25832&amp;language=de&amp;q={searchTerms}"/>
	<Url type="application/atom+xml" rel="describedby" template="http://beispiel.de/atom/describe?spatial_dataset_identifier_code={inspire_dls:spatial_dataset_identifier_code}&amp;spatial_dataset_identifier_namespace={inspire_dls:spatial_dataset_identifier_namespace}&amp;crs={inspire_dls:crs?}&amp;language={language}"/>
	<Url type="application/gml+xml" rel="results" template="http://beispiel.de/atom/download?spatial_dataset_identifier_code={inspire_dls:spatial_dataset_identifier_code}&amp;spatial_dataset_identifier_namespace={inspire_dls:spatial_dataset_identifier_namespace}&amp;crs={inspire_dls:crs}&amp;language={language}"/>
	<Query role="example" inspire_dls:spatial_dataset_identifier_namespace="http://beispiel.de" inspire_dls:spatial_dataset_identifier_code="12345" inspire_dls:crs="EPSG:25832" language="de" title="XXX" count="1"/>
</OpenSearchDescription>
```
(note that this example is constructed, but the problem was encountered in a real-world case)

**Comment by ejn** [comment]
Sorry, this issue would be better-placed in https://github.com/INSPIRE-MIF/helpdesk-validator as it only concerns the implementation of the validator -> please feel free to move it.

**Comment by sMorrone** [comment]
Dear @ejn ,
you are right. @MarcoMinghini, could you please move this issue to the issue tracker of the https://github.com/INSPIRE-MIF/helpdesk-validator?

**Comment by sMorrone** [comment]
I am now moving this issue to the Validator helpdesk

**Comment by fabiovinci** [comment]
Dear @ejn,

could you please provide an example in order to reproduce the error? Thanks

**Comment by fabiovinci** [comment]
Dear @ejn,

in the latest release, some fixes related to the ATOM were introduced, so it is possible that the error you received is no more present.

Since we don't have your ATOM to test, I will close the issue, please reopen it if the error persists.
