### ISSUE TITLE
Validator does not accept WMS URL

### ISSUE THREAD

**Issue by bob-gdiby** [INSPIRE-MIF/helpdesk-validator#836]
Hello,

I'm trying to test a WMS service with the URL "https://wirtschaft-risby.bayern.de/RisGate/servlet/Sonnenscheindauer?".
When I try to run the test, a pop up window saying "An error has occured." appears, similiar to the problem described in this issue: https://github.com/INSPIRE-MIF/helpdesk-validator/issues/777

The certificate of the service should be valid, though.

I hope someone can help me with my Problem.

Thank you in advance and kind regards
Robin

**Comment by fabiovinci** [comment]
Dear @bob-gdiby,

I tried to use the following URL "http://wirtschaft-risby.bayern.de/RisGate/servlet/Sonnenscheindauer?service=WMS&request=GetCapabilities" and the validation started.

See the related report: https://inspire.ec.europa.eu/validator/test-run/details.html?id=EIDbc19ee31-613f-4359-ae73-175d85927d69

We will further check the error you reported when using the https URL.

**Comment by bob-gdiby** [comment]
Dear, @fabiovinci,

using the http Url I was also able to test the service. Thank you for the tip!

Kind regards

**Comment by jenriquesoriano** [comment]
Dear @bob-gdiby ,

we are implementing an improvement in the UI in order to ease the URL management.
Thanks for your feedback.
