### ISSUE TITLE
NPE when starting a Test Run with the API

### ISSUE THREAD

**Issue by kapil-agnihotri** [INSPIRE-MIF/helpdesk-validator#843]
We get NPE when starting tests for [WMS service](https://test.haleconnect.de/ows/services/org.472.c3bf1298-3629-437a-a925-382964393979_wms?SERVICE=WMS&REQUEST=GetCapabilities&VERSION=1.3.0) using the API call. 
NPE is observed only for the first time when this API is requested but on successive API calls the test runs successfully. 

We get `500` status code from etf-webapp with below stacktrace:

```
{"timestamp":"1662966957611","url":"http://etf.hc-test-mk8s.svc.cluster.local:8080/validator/v2/TestRuns","stacktrace":["java.lang.NullPointerException","\tat de.interactive_instruments.etf.testdriver.TaskPoolRegistry.release(TaskPoolRegistry.java:178)","\tat java.util.ArrayList.forEach(ArrayList.java:1249)","\tat de.interactive_instruments.etf.testdriver.TaskPoolRegistry.removeDone(TaskPoolRegistry.java:137)","\tat de.interactive_instruments.etf.webapp.controller.TestRunController.start(TestRunController.java:471)","\tat sun.reflect.GeneratedMethodAccessor308.invoke(Unknown Source)","\tat sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)","\tat java.lang.reflect.Method.invoke(Method.java:497)","\tat org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)","\tat org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:133)","\tat org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:97)","\tat org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:827)","\tat org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:738)","\tat org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)","\tat org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:967)","\tat org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:901)","\tat org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)","\tat org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:872)","\tat javax.servlet.http.HttpServlet.service(HttpServlet.java:707)","\tat org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)","\tat javax.servlet.http.HttpServlet.service(HttpServlet.java:790)","\tat org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:821)","\tat org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1685)","\tat de.interactive_instruments.etf.webapp.filter.ApiFilter.doFilterInternal(ApiFilter.java:89)","\tat org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)","\tat org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:347)","\tat org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:263)","\tat org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1668)","\tat org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:581)","\tat org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)","\tat org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)","\tat org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:226)","\tat org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1158)","\tat org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:511)","\tat org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)","\tat org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1090)","\tat org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)","\tat org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:213)","\tat org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:109)","\tat org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:119)","\tat org.eclipse.jetty.server.Server.handle(Server.java:517)","\tat org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:308)","\tat org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:242)","\tat org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:261)","\tat org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)","\tat org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:75)","\tat org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceAndRun(ExecuteProduceConsume.java:213)","\tat org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:147)","\tat org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:654)","\tat org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:572)","\tat java.lang.Thread.run(Thread.java:745)"]}
```

If I run the above WMS view service directly on the INSPIRE validator then I do get [the result of the test run](https://inspire.ec.europa.eu/validator/test-run/index.html?id=EIDcbdd59dc-e947-42d4-8703-9e84311b6019). Also if I re-run the test in our implementation even then the tests are completed with a result. The NPE is thrown only for the first time when some of these tests are run for new dataset. From the stacktrace above it appears as if NPE is thrown during the clean up process of the previous test.  

Also, I see that according to your [swagger API 4. Manage Test Runs documentation](https://inspire.ec.europa.eu/validator/swagger-ui.html#!/4._Manage_Test_Runs/startUsingPOST), we should also receive `"error": "Error message"` in case of `Internal error - 500` but we do not get any such human readable error message but only the `stacktrace` with `timestamp` and the `url` (as shown in the above stacktrace). It would be great to get such a human readable error response in these scenarios as these scenarios are frequent and happens during the first run for the tests. 

Please let me know if you need any further support to verify the issue. 

Attaching logs from etf service for your reference.
[etf-5f5c9f976d-f6qx5.log](https://github.com/etf-validator/etf-webapp/files/9549136/etf-5f5c9f976d-f6qx5.log)

[I created a GitHub issue on etf-webapp page but it was proposed to create an issue here instead](https://github.com/etf-validator/etf-webapp/issues/225) as the problem could be related to SoapUI ETS.

Looking forward to your feedback.

**Comment by sMorrone** [comment]
Dear @kapil-agnihotri ,
this space is used for discussions and announcements on general INSPIRE topics. Since your issue is related to the INSPIRE Validator , I am moving it to the dedicated helpdesk [Validator](https://github.com/INSPIRE-MIF/helpdesk-validator).

**Comment by kapil-agnihotri** [comment]
Dear @sMorrone,
thank you for your quick response. 
I am not able to follow where this issue was moved to? 
I see that the url link `https://github.com/INSPIRE-MIF/helpdesk-validator` referred in your comment redirects back to this repository.

**Comment by jenriquesoriano** [comment]
Dear @kapil-agnihotri ,

We have debugged the code looking for the origin of your issue, and analyzed where the part that produces the null pointer exception you refer. It is located in the class etf-core/src/main/java/de/interactive_instruments/etf/testdriver/TaskPoolRegistry.java, in the process of removing the already finished tasks form the taskpool.

```
   public void removeDone() {
        final List<EID> removeTaskIds = new ArrayList<>();
        for (final T c : tasks.values()) {
            final EID id = c.getId();
            if (id != null) {
                final Future f = cancelMap.get(id);
                if (f != null && f.isDone()) {
                    removeTaskIds.add(id);
                }
            }
        }
        removeTaskIds.forEach(this::release);

    }

```
However, it doesn't seem to be any problem with it.

To check if there was any problem we have tested in every environment different datasets, because it is specified in your issue that you receive the error once you change datasets. But we were unsuccesfull in recreating your issue.

Also, as you comment, it is only bounded to the execution of the first test, could you confirm this aspect?
Additionally, we would like to ask for more information, as which is the environment (which release version) you are launching the API calls? and could you send the details of your API call and client? body, header, everything please that could help us in any way to reproduce this issue.

**Comment by jenriquesoriano** [comment]
Dear @kapil-agnihotri , 
do you have any additional information on our last question?
Thanks!

**Comment by fabiovinci** [comment]
Dear @kapil-agnihotri,

since there was no response we will close the issue, please reopen it if the error persists.
