### ISSUE TITLE
The links to the ATSs, in the WMS test report, are incorrect

### ISSUE THREAD

**Issue by fabiovinci** [INSPIRE-MIF/helpdesk-validator#844]
In the test report for the WMS Conformance Class, all the links to the related ATS point to an old branch in the related GitHub repository.

In all links, the value "_review-ats-tg_3.11_" should be replaced with "_master_" because the master branch is aligned with the latest version of the TG.

![image](https://user-images.githubusercontent.com/22212406/190209539-ebf2525d-482d-4df0-ada3-2e8f0d3ac51f.png)

**Comment by dperezBM** [comment]
Hi @fabiovinci,
The WMS and WMTS links are updated in staging instance. Could you check that they are correct?
Regards

**Comment by fabiovinci** [comment]
They are ok, thank you.
We can include the fix in the next release.
