### ISSUE TITLE
INSPIRE Reference Validator - problem validate 'Metadata' for 'Data sets and data set series'

### ISSUE THREAD

**Issue by milanSch** [INSPIRE-MIF/helpdesk-validator#846]
Dear, 
I am trying to validate metadata for 'Data sets and data set series' using https://inspire.ec.europa.eu/validator/test-selection/index.html

1.)
![image](https://user-images.githubusercontent.com/4444428/190651409-e0c4e3ef-0a64-467f-8f8b-c3411d723c8e.png)
![image](https://user-images.githubusercontent.com/4444428/190657894-ea1aadfa-271f-4be0-bbab-a84a387c94bb.png)

Url to metadata of DataSet in catalog service is: https://rpi.gov.sk/rpi_csw/service.svc/get?request=GetRecordById&service=CSW&version=2.0.2&elementSetName=full&outputschema=http://www.isotc211.org/2005/gmd&Id=https://data.gov.sk/set/rpi/gmd/00626031/CF3D3C625D6E2358E0530110000A920EHULI_INSPIRE_CLC1990R_DTS_FID

After click 'Start test >' I received error in right bottom corner (red box).
  
Question: Where can I find out more detailed error log?

2.)
Url to the same DataSet record on INSPIRE Geoportal is: https://inspire-geoportal.ec.europa.eu/download_details.html?view=downloadDetails&resourceId=%2FINSPIRE-da77b119-9d6e-11e7-b5a7-52540023a883_20220504-213102%2Fservices%2F1%2FPullResults%2F121-140%2Fdatasets%2F1&expandedSection=metadata

![image](https://user-images.githubusercontent.com/4444428/190652554-954bee6f-53e0-4a25-8279-f34c507c497f.png)

I tried to validate metadata file harvested on INSPIRE Geoportal (url in red ellipse in picture above).
https://inspire-geoportal.ec.europa.eu/resources/INSPIRE-da77b119-9d6e-11e7-b5a7-52540023a883_20220504-213102/services/1/PullResults/121-140/1.iso19139.xml

After click  'Start test >'  there is no response.

Question: Is this functionality disabled?

3.) Both metadata files (url) mentioned above:
- I was able to successfully validate using https://inspire.ec.europa.eu/validator/test-selection/index.html on 29.04.2022 but not now .
- I am able to successfully validate using 'INSPIRE Reference Validator ver. 2022.1' https://github.com/INSPIRE-MIF/helpdesk-validator/releases/tag/v2022.1 installed in docker container on my local PC 

Question: Is this problem of ver. 2022.2?

thank you
milan

**Comment by fabiovinci** [comment]
Dear @milanSch,

to fix an issue for the metadata validation via url for those endpoints whose default response is non-ISO metadata (see #749), the validator adds the parameters: _&outputSchema=http://www.isotc211.org/2005/gmd_ and _&elementSetName=full_ if not present.

Probably in your case, the validator does not detect that they are already present and adds them a second time, so if you use the following URL:

https://rpi.gov.sk/rpi_csw/service.svc/get?request=GetRecordById&service=CSW&version=2.0.2&Id=https://data.gov.sk/set/rpi/gmd/00626031/CF3D3C625D6E2358E0530110000A920EHULI_INSPIRE_CLC1990R_DTS_FID

the validation starts, see the report https://inspire.ec.europa.eu/validator/test-run/details.html?id=EID47eb4715-dd3f-4a81-abc6-565f721f27f2.

In any case, we will investigate the issue with your link and also with the link to the XML file provided by Geoportal.

**Comment by milanSch** [comment]
Dear @fabiovinci 
thank you for your answer, great.  I see now. My fault.

In my issue problem 1.) there is different parameter:

&outputSchema vs &outputschema (upper or lower S)

My original url not posible to validate:
https://rpi.gov.sk/rpi_csw/service.svc/get?request=GetRecordById&service=CSW&version=2.0.2&elementSetName=full&outputschema=http://www.isotc211.org/2005/gmd&Id=https://data.gov.sk/set/rpi/gmd/00626031/CF3D3C625D6E2358E0530110000A920EHULI_INSPIRE_CLC1990R_DTS_FID

After changing to "S" in &outputSchema parameter it works.
https://rpi.gov.sk/rpi_csw/service.svc/get?request=GetRecordById&service=CSW&version=2.0.2&elementSetName=full&outputSchema=http://www.isotc211.org/2005/gmd&Id=https://data.gov.sk/set/rpi/gmd/00626031/CF3D3C625D6E2358E0530110000A920EHULI_INSPIRE_CLC1990R_DTS_FID



In my issue problem 2.)
There is need to add "?" at the end of url link to XML provided by Geoportal https://github.com/INSPIRE-MIF/helpdesk-validator/issues/793#issuecomment-1163071990

Validation doesn't work:
https://inspire-geoportal.ec.europa.eu/resources/INSPIRE-da77b119-9d6e-11e7-b5a7-52540023a883_20220504-213102/services/1/PullResults/121-140/1.iso19139.xml

Validation works:
[https://inspire-geoportal.ec.europa.eu/resources/INSPIRE-da77b119-9d6e-11e7-b5a7-52540023a883_20220504-213102/services/1/PullResults/121-140/1.iso19139.xml?](https://inspire-geoportal.ec.europa.eu/resources/INSPIRE-da77b119-9d6e-11e7-b5a7-52540023a883_20220504-213102/services/1/PullResults/121-140/1.iso19139.xml?)

Validation works too when I download XML to disk and validate it as local file.


thank you
milan

**Comment by fabiovinci** [comment]
Thank you for having spotted that the problem does not exist for the first case.

We will work on the second case.

**Comment by radochudy** [comment]
Dear @fabiovinci  I think problem num. 1 should be fixed at validator. According CSW 2.0.2 specification in "Table 65 — KVP encoding for GetRecords operation request " all KVP parameters name are case insensitive....

![image](https://user-images.githubusercontent.com/6662421/191288575-894b7990-d64b-4a29-afb5-21d96471bff1.png)

**Comment by fabiovinci** [comment]
Dear all,

thank you for your comments, we are working to improve the way the links are analyzed maintaining the already implemented fix for those endpoints whose default response is non-ISO metadata.

**Comment by jenriquesoriano** [comment]
Dear all, 

We are implementing a new feature in the UI that addresses your issue.
We will keep you posted for any update at this regard.
Thanks for your contribution.

Best,
