### ISSUE TITLE
New date scheduled for the past due release 2022.3?

### ISSUE THREAD

**Issue by g-weber** [INSPIRE-MIF/helpdesk-validator#848]
Dear all, I would like to ask if there is a new date scheduled for the past due release 2022.3?

Thanks in advance.

**Comment by MarcoMinghini** [comment]
The release is under preparation and will happen in the next days.

**Comment by arantzaetxebarria** [comment]
Dear @g-weber 

You can stay informed in this announcement https://github.com/INSPIRE-MIF/helpdesk-validator/discussions/850

Regards

**Comment by fabiovinci** [comment]
The v2022.3 release has been deployed successfully in the [production instance](https://inspire.ec.europa.eu/validator/home/index.html).
For further details, please visit the [release notes](https://github.com/INSPIRE-MIF/helpdesk-validator/releases/tag/v2022.3).
