### ISSUE TITLE
TN Theme - tn-ro:RoadNode The node is not located at the start or end of any link feature in the data set.

### ISSUE THREAD

**Issue by robblis** [INSPIRE-MIF/helpdesk-validator#849]
Testing tn-ro:RoadNode produces the following error.

https://inspiredemo.esri.com/arcgis/rest/services/tn5/MapServer/exts/InspireFeatureDownload/service?VERSION=2.0.0&SERVICE=WFS&REQUEST=GetFeature&LANGUAGE=&TYPENAMES=tn-ro%3ARoadNode&MAXFEATURES=&COUNT=100&f=image&Namespaces=xmlns(tn-ro,http%3A%2F%2Finspire.ec.europa.eu%2Fschemas%2Ftn-ro%2F4.0)

The dataset has 12 feature(s) with errors for this assertion.
XML document 'service.xml', RoadNode 'netElementP.259694': The node is not located at the start or end of any link feature in the data set.
XML document 'service.xml', RoadNode 'netElementP.259695': The node is not located at the start or end of any link feature in the data set.

We must use Resolve and ResolveDepth parameters to avoid the errors.

Can you add the fix for TN to recognize external links similar for the fix applied to the AU theme? 
See the following issue for similar resolutions. https://github.com/INSPIRE-MIF/helpdesk-validator/issues/788

**Comment by dperezBM** [comment]
Dear @robblis,

The provided example https://inspiredemo.esri.com/arcgis/rest/services/tn5/MapServer/exts/InspireFeatureDownload/service?VERSION=2.0.0&SERVICE=WFS&REQUEST=GetFeature&LANGUAGE=&TYPENAMES=tn-ro%3ARoadNode&MAXFEATURES=&COUNT=100&f=image&Namespaces=xmlns(tn-ro,http%3A%2F%2Finspire.ec.europa.eu%2Fschemas%2Ftn-ro%2F4.0) is currently displaying an access error.
Could you provide us another example of this service?

Thanks.

**Comment by robblis** [comment]
Hi @dperezBM ,

My apologies. The service was stopped. It's online now.

Thanks
Robert

**Comment by fabiovinci** [comment]
Dear @robblis,

we would reproduce the error but the service is not accessible.
Could you please check?
Thanks

**Comment by robblis** [comment]
Hi @fabiovinci,

The service is back online.

https://inspiredemo.esri.com/arcgis/rest/services/tn5/MapServer/exts/InspireFeatureDownload/service?VERSION=2.0.0&SERVICE=WFS&REQUEST=GetFeature&LANGUAGE=&TYPENAMES=tn-ro%3ARoadNode&MAXFEATURES=&COUNT=100&f=image&Namespaces=xmlns(tn-ro,http%3A%2F%2Finspire.ec.europa.eu%2Fschemas%2Ftn-ro%2F4.0)

Thanks,
Robert

**Comment by fabiovinci** [comment]
Hi @robblis,

we modified the related [ATS](https://github.com/inspire-eu-validation/data-tn/blob/3.2/tn-as/geometry.md) and will indroduce the fix in the ETS.
We will notify you when the fix is available in the staging instance.

**Comment by arantzaetxebarria** [comment]
Dear @robblis 

A fix has been uploaded to the [staging environment](http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/test-selection/index.html), could you please verify that all works as expected? Thanks.

**Comment by robblis** [comment]
Hi @arantzaetxebarria ,

We just re-tested TN RoadNode on the staging validator and all tests passed.

Thanks, for the fix.

Robert
