### ISSUE TITLE
Metadata 2.0 XML schema validation

### ISSUE THREAD

**Issue by skafka** [INSPIRE-MIF/helpdesk-validator#85]
I am attempting to run Metadata 2.0 test - Conformance Class 1: INSPIRE data sets and data set series baseline metadata.

I got this error report:
`'54622bbb-6730-4697-82be-6a64c0a80137.xml', record '54622bbb-6730-4697-82be-6a64c0a80137': 'Validation failed: 432:86: cvc-complex-type.2.4.a: Invalid content was found starting with element '{"http://www.opengis.net/gml":TimePeriod}'. One of '{"http://www.opengis.net/gml/3.2":AbstractTimePrimitive}' is expected.Validation failed: http://www.isotc211.org/2005/gmd/gmd.xsd, 2:35: s4s-elt-character: Non-whitespace characters are not allowed in schema elements other than 'xs:appinfo' and 'xs:documentation'. Saw '301 Moved Permanently'.Validation failed: 88:169: cvc-complex-type.2.4.a: Invalid content was found starting with element '{"http://www.isotc211.org/2005/gmx":Anchor}'. One of '{"http://www.isotc211.org/2005/gco":CharacterString}' is expected.'.`
(In Altova XMLSpy the file is valid!)

I use this schema location: https://www.isotc211.org/2005/gmd/gmd.xsd

When I change the schema location to: https://inspire.ec.europa.eu/draft-schemas/inspire-md-schemas-temp/apiso-inspire/apiso-inspire.xsd , the result is OK.

We could switch the schemas to "inspire" ones, but I would prefer stable ones rathet than draft...
The test should enable them as well.

Here is my test metadata file address: https://dev.bnhelp.cz/projects/micka6/record/xml/54622bbb-6730-4697-82be-6a64c0a80137

Thank you

**Comment by MarcoMinghini** [comment]
You can solve the problem by just substituting the namespace http://www.opengis.net/gml with http://www.opengis.net/gml/3.2. Schema validation works then.

**Comment by skafka** [comment]
Hmm, the schema https://www.isotc211.org/2005/gmd/gmd.xsd does not support http://www.opengis.net/gml/3.2 namespace. In Altova XMLSpy I get this message: 
File https://dev.bnhelp.cz/projects/micka6/record/xml/4e92de1c-50cc-4ae2-9eb3-14dec0a80137 is not valid.
	Element <gml:TimePeriod> is not allowed under element <gmd:extent>.
		Reason: The following elements are expected at this location (see below)
			'gml:AbstractTimePrimitive'
			'gml:AbstractTimeGeometricPrimitive'
			'gml:TimeInstant'
			'gml:TimePeriod'
			'gml:AbstractTimeTopologyPrimitive'
			'gml:TimeNode'
			'gml:TimeEdge'
		Error location: gmd:MD_Metadata / gmd:identificationInfo / gmd:MD_DataIdentification / gmd:extent / gmd:EX_Extent / gmd:temporalElement / gmd:EX_TemporalExtent / gmd:extent / gml:TimePeriod
		Details
			cvc-complex-type.1.4: Element <gml:TimePeriod> unexpected by type 'gts:TM_Primitive_PropertyType' of element <gmd:extent>.
			cvc-type.3.2: Element <gmd:extent> is not valid with respect to type definition 'gts:TM_Primitive_PropertyType'.
			cvc-elt.5.2.1: The element <gmd:extent> is not valid with respect to the actual type definition 'gts:TM_Primitive_PropertyType'.

Rename unexpected element **<gml:TimePeriod>** to expected **<{http://www.opengis.net/gml}:TimePeriod>**

**Comment by josemasensio** [comment]
Dear @skafka,

Running your test file, we didn't get any error on metadata `Conformance Class 1: INSPIRE data sets and data set series baseline metadata`. Is the error still happening to you?

Best regards.

**Comment by skafka** [comment]
Now the validation seems to be OK for both schemas (on INSPIRE and ISO sites). Thank you.
