### ISSUE TITLE
AU Theme: referenced resource cannot be accessed

### ISSUE THREAD

**Issue by Dnoack49** [INSPIRE-MIF/helpdesk-validator#853]
Dear all,

 validating the following AdministrativeUnit-dataset
https://inspire.brandenburg.de/services/au_bdlm_wfs?service=WFS&version=2.0.0&request=GetFeature&typenames=au:AdministrativeUnit&Count=10 

the following errors occurs for the TestSteps **au-ia.b.3: AdministrativeUnit.upperLevelUnit** and **au-ia.b.4:AdministrativeUnit.lowerLevelUnit** indicating that a the properties reference a resource which cannot be accessed.

TestReport: 
[Test run on 15 16 - 27.09.2022 with test suite Annex I - Administrative Units (AU).zip](https://github.com/INSPIRE-MIF/helpdesk-validator/files/9656582/Test.run.on.15.16.-.27.09.2022.with.test.suite.Annex.I.-.Administrative.Units.AU.zip)

Here an example:
![grafik](https://user-images.githubusercontent.com/8046960/192546646-30d29824-38ce-46c9-990e-5204c2ed7041.png)

However, the resources are accessible e.g. : https://registry.gdi-de.org/id/de.bb.inspire.au.atkis-bdlm/AdministrativeUnit_12

We'd appreciate your feedback on this.

**Comment by fabiovinci** [comment]
Dear @Dnoack49,
thank you for reporting the issue.

A very [similar issue](https://github.com/INSPIRE-MIF/helpdesk-validator/issues/559) is already open, we are already analyzing it and we will provide a solution asap.
I will label this issue as duplicate and close it, so I kindly ask you to follow the already open issue for any updates.
