### ISSUE TITLE
AccessPoint error

### ISSUE THREAD

**Issue by hallinpihlatie** [INSPIRE-MIF/helpdesk-validator#854]
We are working on making SDS metadata template and run into an AccessPoint error when validating with the invocable SDS service test.

Here are two SDS XML metadata files, one passing the validation (1), and the other not (2):

1) This XML passes the invocable SDS services validation test: https://www.paikkatietohakemisto.fi/geonetwork/srv/api/records/a1532cab-8452-43a0-8281-11df524cf6a3/formatters/xml?approved=true
[Validation report](https://paikkatietojentuottajat-koekaytto.maanmittauslaitos.fi/validointipalvelu//v2/TestRuns/EID7ecf55d5-60f8-48d9-8dc9-f6dbcd16be89.html)
 
2) This XML does not pass the same test due to an AccessPoint error: https://www.paikkatietohakemisto.fi/geonetwork/srv/api/records/c82e3155-8207-49f3-85ff-22c47f89634f/formatters/xml?approved=true
[Validation report](https://paikkatietojentuottajat-koekaytto.maanmittauslaitos.fi/validointipalvelu//v2/TestRuns/EID1d800f27-6512-4d9c-bbb7-1ee6165c3822.html)

The error says "The gmd:linkage/gmd:description child element gmd:CI_OnlineResource shall contain a gmx:Anchor element pointing to the value ""accessPoint"" of the code list OnLineDescriptionCode (""http://inspire.ec.europa.eu/metadatacodelist/OnLineDescriptionCode/accessPoint"" It does however contain the same information and structure as the metadata XML that passes the validation. Any hints on why? 

We would like to provide an SDS template to our data providers that passes the validation if this goal is possible to achieve as there is a clear need to get SDSs others than INSPIRE view, download etc services described. We started off with an invocable SDS example from the inspire web page that now seems to have been removed.

Btw, there's a typo in the error message - it should be *...metadata-codelist--"

**Comment by fabiovinci** [comment]
Dear @hallinpihlatie,

the error in the second metadata is due to the link in _htpps_ instead of _http_.

The HTPP URIs of the INSPIRE codelist values are in HTTP format.

You can find some metadata examples, containing as a comment the relevant requirements, [here](https://github.com/INSPIRE-MIF/helpdesk-validator/tree/master/examples).

Thank you for identifying the typo, we will correct it.

**Comment by fabiovinci** [comment]
@dperezBM, @arantzaetxebarria,

could you please update the error message for the test "`md sds-invocable 5.2: Resource Locator`"?

The current message is:

> The gmd:linkage/gmd:description child element gmd:CI_OnlineResource shall contain a gmx:Anchor element pointing to the value ""accessPoint"" of the code list OnLineDescriptionCode (""http://inspire.ec.europa.eu/metadatacodelist/OnLineDescriptionCode/accessPoint"")

It should be corrected as follows:

_The gmd:linkage/gmd:description child element gmd:CI_OnlineResource shall contain a gmx:Anchor element pointing to the value "accessPoint" of the code list OnLineDescriptionCode ("http://inspire.ec.europa.eu/metadata-codelist/OnLineDescriptionCode/accessPoint"). Please note that the codelist value is in http format._

**Comment by dperezBM** [comment]
Hi @hallinpihlatie,

The message is updated and available in staging instance. Could you check that it is correct?

@fabiovinci could you also have a look?

**Comment by fabiovinci** [comment]
Dear all,
I tested the solution in staging and it works fine.
