### ISSUE TITLE
Validation error for "INSPIRE Theme Keyword" on metadata for datasets 

### ISSUE THREAD

**Issue by dhdeangelis** [INSPIRE-MIF/helpdesk-validator#855]
While running metadata tests for the Swedish Agency for Marine and Water Management we found that **all** metadataposts for datasets now report the error below. This happens in metadataposts that have previously validated OK and have not changed recently. Point tests on metadataposts from other organisations and countries show similar error. 

Using a local docker instance of validator 2022.3, but the same error appears when using the 2022.1 version or the online validator instance.

What could be the cause of this?

Example:

https://www.geodata.se/geodataportalen/srv/eng/csw-inspire?request=GetRecordById&service=CSW&version=2.0.2&elementSetName=full&outputSchema=csw:IsoRecord&id=ebcb61ce-d76a-43fe-89d3-56cd3e741fdc

_A dataset (series) metadata record that uses 'GEMET - INSPIRE themes, version 1.0' as the title of the vocabulary that belongs to a block of descriptive keywords must have one keyword in this block that is a language specific or language neutral code value from the codelist at http://inspire.ec.europa.eu/theme._ 

![image](https://user-images.githubusercontent.com/51515911/194570906-6ca0f01e-1b1a-4e2a-b3d1-6be22570ab66.png)

**Comment by JohannaOtt** [comment]
Hi,

This requirement is part of the [current techincal guidance document on metadata](https://github.com/INSPIRE-MIF/technical-guidelines/blob/2022.2/metadata/metadata-iso19139/metadata-iso19139.pdf):

> TG Requirement C.15: metadata/2.0/req/common/keyword-originating-cv
> When using keywords originating from a controlled vocabulary, the originating controlled vocabulary shall be cited using the gmd:descriptiveKeywords /gmd:MD_Keywords/gmd:thesaurusName/gmd:CI_Citation element.

**Comment by dhdeangelis** [comment]
Thank you for your comment @JohannaOtt 

May be I am missing something but I cannot see how the error reported is related to the change you mention.

In the latest version for the metadata guidelines the following example is given for the C15 requirement:

`        <gmd:thesaurusName>
            <gmd:CI_Citation>
                <gmd:title>
                    <gmx:Anchor xlink:href="http://www.eionet.europa.eu/gemet/inspire_themes">GEMET - INSPIRE themes, version 1.0</gmx:Anchor>
                </gmd:title>
                <gmd:date>
                    <gmd:CI_Date>
                        <gmd:date>
                            <gco:date>2008-06-01</gco:date>
                        </gmd:date>
                        <gmd:dateType>
                            <gmd:CI_DateTypeCode codeList="http://standards.iso.org/iso/19139/resources/gmxCodelists.xml#gmxCodelists.xml#CI_DateTypeCode" codeListValue="publication">publication</gmd:CI_DateTypeCode>
                        </gmd:dateType>
                    </gmd:CI_Date>
                </gmd:date>
            </gmd:CI_Citation>
        </gmd:thesaurusName>`


while our metadata has that section coded in this way, which is for practical purposes the same:

`        <gmd:thesaurusName>
            <gmd:CI_Citation>
            <gmd:title>
                <gmx:Anchor xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="http://www.eionet.europa.eu/gemet/inspire_themes">GEMET - INSPIRE themes, version 1.0</gmx:Anchor>
            </gmd:title>
            <gmd:date>
                <gmd:CI_Date>
                <gmd:date>
                    <gco:Date xmlns:gco="http://www.isotc211.org/2005/gco">2008-06-01</gco:Date>
                </gmd:date>
                <gmd:dateType>
                    <gmd:CI_DateTypeCode codeListValue="publication" codeList="https://standards.iso.org/iso/19139/resources/gmxCodelists.xml#CI_DateTypeCode">publication</gmd:CI_DateTypeCode>
                </gmd:dateType>
                </gmd:CI_Date>
            </gmd:date>
            </gmd:CI_Citation>
        </gmd:thesaurusName>`


Also the validation error above points to this test case:
https://github.com/inspire-eu-validation/metadata/blob/2.0/datasets-and-series/inspire-theme-keyword.md

which to me should be well implemented in the metadata in question.

I will keep looking and eventually report back.

**Comment by JohannaOtt** [comment]
Hi,

I mentioned the wrong requirement - sorry for the confusion. I meant C.16:

> TG Requirement C.16: metadata/2.0/req/common/group-keywords-by-cv
> All keywords originating from the same controlled vocabulary, or its version, shall be grouped under one gmd:descriptiveKeywords/gmd:MD_Keywords element. A single gmd:MD_Keywords element may only contain keywords originating from the one cited controlled vocabulary, or its version.

But as you said, I would also say that this is implemented in the metadata in question (only took a quick look, might have missed something).

**Comment by manilly** [comment]
Can report the same issue for all AT data metadata. We didn't change anything in out metadata, but suddenly this error appears.
The error didn't appaer on the etf/ets docker version (2022.3) I installed on October 3rd. 
I had to pull the newest files again end of last week and now this seems to be a bug (on our local instance as well as on the public jrc validator).

**Comment by fabiovinci** [comment]
Dear all,

thank you for reporting the issue, seems to affect all metadata, even the [example metadata](https://github.com/INSPIRE-MIF/helpdesk-validator/blob/master/examples/Dataset_metadata_2.0_example.xml) that was 100% valid.

We are working on it and will inform you about the results.

**Comment by AntoRot** [comment]
I encountered the same error in the Italian metadata records.

Example of XML metadata record affected: https://geodati.gov.it/RNDT/rest/document?id=R_SARDEG:f252e629-3123-44bf-8b40-959ac84e3997 

Test report: https://inspire.ec.europa.eu/validator/test-run/details.html?id=EID22428f54-3d49-42c2-b42e-b360ae7aa700

**Comment by thomruhl** [comment]
FYI, same issue in Belgian (Brussels Region) metadata records. Thanks for looking into it.

**Comment by CMath04** [comment]
We have the same issue with the Luxembourg catalog as well (https://catalog.inspire.geoportail.lu/geonetwork/). 
This rule never success on datasets

**Comment by iverscar** [comment]
Many thanks for taking care of this issue. We are facing the same validation error at the European Environement Agency (https://sdi.eea.europa.eu/catalogue/srv/eng/catalog.search#/home)

**Comment by albertogmancha** [comment]
We have the same problem with the validation of the data set of the Instituto de Estadística y Cartografía de Andalucía. Thanks for your help

**Comment by fabiovinci** [comment]
Dear all,

thank you for your feedback.

The issue was due to a different structure of the [ATOM format](https://inspire.ec.europa.eu/theme/theme.en.atom) provided by the new version of the INSPIRE Registry, for the relevant codelist.

A fix has already been implemented in the Registry.

The error is no longer present, could you please test it and confirm? Thanks.

**Comment by iverscar** [comment]
Many thanks for the fix.

I have tested it a couple of times today and it works

Have a nice weekend

Best regards,
Carsten

**Comment by albertogmancha** [comment]
Thank you very much. I have been able to carry out several tests and it works.
Have a nice weekend

Best regards,
Alberto

**Comment by dhdeangelis** [comment]
I can also confirm that the validator is working OK again. Thank you @fabiovinci and colleagues. Have a nice weekend!

**Comment by AntoRot** [comment]
I also confirm that the validator is working now with regard to the issue raised.

Thank you!

**Comment by manilly** [comment]
same here, also in our local instance. Thx

**Comment by fabiovinci** [comment]
Thank you all for your confirmation.

I will close the issue.
