### ISSUE TITLE
Validation error for "Code list values in basic data types" for all datasets

### ISSUE THREAD

**Issue by fabiovinci** [INSPIRE-MIF/helpdesk-validator#856]
It seems that the error related to the "Code list values in basic data types" test case affects all datasets, even if the related codelists are not present in the dataset itself.

![image](https://user-images.githubusercontent.com/22212406/195064994-0ffa21d8-55d8-4b8b-a590-9a19c9529f22.png)

Please ignore this error for the moment, we are investigating and will let you know the results.

**Comment by Ana-SGA** [comment]
Dear all,

we also have the same problem as @fabiovinci - for every theme validation fails for code lists concerning Geographical names.

**Comment by fabiovinci** [comment]
Dear all,

the error was due to a NullPointerExeption for the relevant codelists by the INSPIRE Registry.

A fix has been implemented and released in the INSPIRE Registry, and the errors in the Validator are no longer present.

Could you please test it and provide your feedback? Thanks

**Comment by Ana-SGA** [comment]
Dear @fabiovinci ,

now the test passes for the theme Utility and governmental service (Administrative services), but the test for the Land use theme cannot be started at all, that is, the file upload isn't possible. On a staging instance the test for Land use also passes without error.

**Comment by fabiovinci** [comment]
The issue related to some codelists seems solved. 

@Ana-SGA, could you please open a dedicated issue if the problem with LU datasets persists? Thanks.
