### ISSUE TITLE
Error al cargar el archivo (Código 400- Solicitud incorrecta) 

### ISSUE THREAD

**Issue by geoloren** [INSPIRE-MIF/helpdesk-validator#857]
Hola !

Estoy intentando cargar el archivo XML que he trabajado para validarlo con el "Validador de referencia INSPIRE", pero
me está saliendo un  "Error al cargar el archivo (Código 400- Solicitud incorrecta) "

Alguien sabe de que trata? o de que podría tratar ese tipo de error?

**Comment by arantzaetxebarria** [comment]
Dear @geoloren 

Could you provide us with your example to reproduce and analyse the issue? Thanks.

Regards,

Arantza

**Comment by geoloren** [comment]
Hola! 
Aquí lo envío ...

[sitios-interes-uab-v1r0-2022.zip](https://github.com/INSPIRE-MIF/helpdesk-validator/files/9786716/sitios-interes-uab-v1r0-2022.zip)

**Comment by fabiovinci** [comment]
Dear @geoloren,

it seems there is an error in the `gmd` namespace declaration, you should replace the `xmlns:gmd` attribute with the following value:

`xmlns:gmd="http://www.isotc211.org/2005/gmd"`

By doing this substitution metadata can be loaded and validated (see report https://inspire.ec.europa.eu/validator/test-run/index.html?id=EID2c2cead7-e073-4025-aa1c-58a6cf22ed9e).

**Comment by fabiovinci** [comment]
Dear @geoloren,
since the fix is on your side, we will close the issue.
