### ISSUE TITLE
Unexpected failure due to html content in step Get INSPIRE Media Subtype

### ISSUE THREAD

**Issue by mwjsanders** [INSPIRE-MIF/helpdesk-validator#860]
### Context
validated resouce type: Predefined ATOM
validated service endpoint: https://service.pdok.nl/lv/bag/atom/index.xml
validation report: https://inspire.ec.europa.eu/validator/test-run/details.html?id=EID843b7bef-a2d9-442c-96e6-96d6a78c6508 

In the test step [Abstract Test Case 'Use INSPIRE media-types only'](http://inspire.ec.europa.eu/id/ats/download-atom/3.1/atom-pre-defined/dataset-feed-link-media-type)  a list of INSPIRE media sub types are retrieved using url http://inspire.ec.europa.eu/media-types/application with 'Accept'-Header 'application/atom+xml' (see sub step _Get INSPIRE Media Subtype_)

### Expected
The returned response from http://inspire.ec.europa.eu/media-types/application should contain xml data because the Accept header is set to application/atom+xml.

### Actual behaviour
The returned response contains html, which causes the sub step _Root  element 'feed' exists_ to fail because there is no feed element in the html response.

**Comment by ghost** [comment]
Yes, +1 on this

**Comment by jescriu** [comment]
Dear @mwjsanders,
Thanks for spotting the issue. 
The INSPIRE Registry team will be analysing the issue as soon as possible.

**Comment by arantzaetxebarria** [comment]
Dear @mwjsanders, @LarsAll 

A solution has been implemented in the INSPIRE Registry production environment. Could you please confirm that the [Abstract Test Case 'Use INSPIRE media-types only'](http://inspire.ec.europa.eu/id/ats/download-atom/3.1/atom-pre-defined/dataset-feed-link-media-type) is working properly now?

Regards

**Comment by ghost** [comment]
Hi @arantzaetxebarria! Nice one, works fine now 👍 

![image](https://user-images.githubusercontent.com/89914074/205281597-1ec3d4a6-6b64-416d-8c47-78c126b066a1.png)

**Comment by mwjsanders** [comment]
Thanks @arantzaetxebarria:

The problem does not occur any more

**Comment by ghost** [comment]
Hi @jescriu!

It does seem like as of today, the problem is back. Maybe we'll see if @mwjsanders reports the same issue.

**Comment by mwjsanders** [comment]
@jescriu 

I can confirm that the problem is. I just validated the service reported in the inital description of this issue.

**Comment by arantzaetxebarria** [comment]
Dear @mwjsanders, @LarsAll 

I have just tested in production environment, your example https://service.pdok.nl/lv/bag/atom/index.xml, and it works as expected.  https://inspire.ec.europa.eu/validator/test-run/details.html?id=EID5ab35475-b721-4ed7-b612-2a1649ebf408

![image](https://user-images.githubusercontent.com/64014694/207556698-f0301a0d-a80f-48bf-ad24-02e89bdba864.png)

Could you please confirm that it is now working correctly and that the error was a temporary one? Thanks

**Comment by ghost** [comment]
Hi @arantzaetxebarria!

Works very well now, cheers!

**Comment by mwjsanders** [comment]
Hi @arantzaetxebarria 

We don´t see this error happening any more.

**Comment by jesperschmidt** [comment]
I have the problem with 'Get the list of INSPIRE media sub types with 'Accept'-Header 'application/atom+xml'' in a local installation of the validator.
https://inspire.ec.europa.eu/media-types/application returns html not xml
I am using validator 2023.1 with the corresponding ets-repository
