### ISSUE TITLE
Local install of Validator fails test 'md common req C.1: XML Schema' for some dataset metadata

### ISSUE THREAD

**Issue by petbod-lm** [INSPIRE-MIF/helpdesk-validator#862]
We have setup a local instance of the Inspire Reference validator.
We have found that certain datasets fail the test 'md common req C.1: XML Schema' on our local validator but when I test the same dataset in the EU Inspire Reference validator the dataset passes this test.

URL to dataset that fails C1: XML Schema locally but passes in EU Validator:
https://www.geodata.se/geodataportalen/srv/eng/csw-inspire?request=GetRecordById&service=CSW&version=2.0.2&elementSetName=full&outputSchema=csw:IsoRecord&id=0dde1643-6323-4208-8d5b-daf0c9b718f8

Here is the Error Message from the test:
The metadata record set has 1 record(s) with errors for this assertion.
XML document 'csw-inspire.xml', record '0dde1643-6323-4208-8d5b-daf0c9b718f8': 'Validation failed: http://schemas.opengis.net/iso/19139/20070417/srv/1.0/serviceMetadata.xsd, 33:49: src-resolve: Cannot resolve the name 'gco:AbstractObject_Type' to a(n) 'type definition' component.'.

I have validated the metadata in XML Spy and it validates correctly.

I have updated this same dataset to use the same namespace declarations as the shown in the Dataset_metadata_2.0_example.xml
(https://github.com/INSPIRE-MIF/helpdesk-validator/blob/master/examples/Dataset_metadata_2.0_example.xml)
and the dataset continues to fail the XML Schema test.

I am at a loss as to why some datasets fail XML Schema validation while others pass while thier namespace declarations are the same.

Can you provide advice on how to I could find more detailed error logs from the Validator or what I should change/add to our local installation?

Thanks
/Pete

**Comment by petbod-lm** [comment]
And here is a dataset metadata post that passes XML Schema validation in both our local validator and the EU Reference Validator
https://www.geodata.se/geodataportalen/srv/eng/csw-inspire?request=GetRecordById&service=CSW&version=2.0.2&elementSetName=full&outputSchema=csw:IsoRecord&id=1f185d81-c699-48e3-9ada-c9e1ae297557

**Comment by fabiovinci** [comment]
Dear @petbod-lm,

could you please make a test using the official APISO schema?

You should replace the "schemaLocation" attribute in your metadata with the following value:

`xsi:schemaLocation="http://www.isotc211.org/2005/gmd http://schemas.opengis.net/csw/2.0.2/profiles/apiso/1.0.0/apiso.xsd"`

**Comment by petbod-lm** [comment]
Hi Fabio,
I have modified a local copy of the dataset metadata and changed the schema location entry to use the official APISO schema
`xsi:schemaLocation="http://www.isotc211.org/2005/gmd http://schemas.opengis.net/csw/2.0.2/profiles/apiso/1.0.0/apiso.xsd"`

I then submitted this updated metadata for validation on both the EU Inspire Reference Validator and our internal server with Inspire Valdator.
The metadata continues to pass validation on the EU Inspire Reference Validator and continues to fail validation on our server.
The metadata now fails validation in XML Spy as well due to the xlink namespace being already declared.

The updated metadata (with offical APISO schema) validates on the EU Inspire Reference Validator but not on our local installation .  What should I look at next?
Thanks
/Pete

**Comment by fabiovinci** [comment]
Dear @petbod-lm,

I have compared the two metadata, but there are no substantial differences that can lead to different results.

Could you please download and send the report of the failed metadata?

**Comment by petbod-lm** [comment]
I have validated the dataset using the GetRcordById URL 
https://www.geodata.se/geodataportalen/srv/eng/csw-inspire?request=GetRecordById&service=CSW&version=2.0.2&elementSetName=full&outputSchema=csw:IsoRecord&id=0dde1643-6323-4208-8d5b-daf0c9b718f8 
on our local installation of the Inspire Reference validator and attached are the downloaded report log file.  
I can see the failure but there is no detail provided by the ETF tests about why the xml schema test fails.

[Test run on 14_57 - 26.10.2022 with test suite Conformance Class 2_ INSPIRE data sets and data set series interoperability metadata..txt](https://github.com/INSPIRE-MIF/helpdesk-validator/files/9869723/Test.run.on.14_57.-.26.10.2022.with.test.suite.Conformance.Class.2_.INSPIRE.data.sets.and.data.set.series.interoperability.metadata.txt)

**Comment by fabiovinci** [comment]
Can you send the report in html format?

**Comment by petbod-lm** [comment]
[Test run on 14_57 - 26.10.2022 with test suite Conformance Class 2_ INSPIRE data sets and data set series interoperability metadata..html.zip](https://github.com/INSPIRE-MIF/helpdesk-validator/files/9869854/Test.run.on.14_57.-.26.10.2022.with.test.suite.Conformance.Class.2_.INSPIRE.data.sets.and.data.set.series.interoperability.metadata.html.zip)

I have to zip the html file to attach it to the comment
/Pete

**Comment by fabiovinci** [comment]
Dear @petbod-lm,

the different behaviour of the two instances is very strange, could you please try to install the latest version to verify if the error persists?

**Comment by petbod-lm** [comment]
Hej Fabio,
I have updated the local instance to use 2023.1 already and continue to see the same XML Schema validation error.
Can we organise a bilateral meeting together?  I can show you how we have implemented our local instance and hopefully identify where we should look deeper to find the source of the problem

**Comment by petbod-lm** [comment]
Hello,
can we origanise a bilateral meeting soon to review our setup of the ETF Validator?  We continue to see the metadata failing 'md common req C1:XML Schema' regularly (but not all the time - intermittently) and I cannot see any cause in the logs on the ETF validator server.

**Comment by jenriquesoriano** [comment]
Dear @petbod-lm ,
 
based on the information shared, we cannot deduce what the issue could be.
We kindly request you to contact `inspire.jrc AT guadaltel.com` to schedule a bilateral meeting and review your specific setup in detail.

Best regards,

**Comment by petbod-lm** [comment]
Thank you for the contact information.

**Comment by petbod-lm** [comment]
Hi,
we have solved the problem!  I have updated the proxy settings in the Docker file and our network team have also made some changes and now we can load XML schemas without error.
Thanks for the suggestions provided in our meeting.
/Pete

**Comment by jenriquesoriano** [comment]
These are very good news Peter, thanks a lot.
In case you have further comments, please, let us know.

Best regards,
