### ISSUE TITLE
Cross-theme tests give error

### ISSUE THREAD

**Issue by aquaterra** [INSPIRE-MIF/helpdesk-validator#867]
For MineralOccurrence from theme Mineral Resources (mr) the geometry is provided by the occurrence association between GeologicFeature and MappedFeature shown in the Geology data specification, as mentioned in the data specification of Mineral Resources.
In the validator I selected both themes, but it gives me the next error:
Invalid content was found starting with element '{"http://inspire.ec.europa.eu/schemas/mr-core/4.0":MineralOccurrence}'. One of '{"http://inspire.ec.europa.eu/schemas/ge-core/4.0":GeologicFeature}' is expected.

The mapping that was used:
<ge:MappedFeature><ge:specification><mr:MineralOccurrence>...

**Comment by fabiovinci** [comment]
Dear @aquaterra,

you can select only the MR data theme since the related XSD imports the Geology XSD.

If you give us a gml sample we can have a look and give you feedback.

**Comment by aquaterra** [comment]
OK, understood.
The validator doesn't give an error after selecting only theme MR.
Thanks for your answer!
