### ISSUE TITLE
OGC API Test

### ISSUE THREAD

**Issue by ghost** [INSPIRE-MIF/helpdesk-validator#869]
Hello!

I've been running some tests using the Geoserver extension and one error that is returned seems to be connected to the parameter "limit", running test getting features: _/collections/{collectionId}/items_

Looking at the log i see:

xx.xx.xx.xx - - [02/Nov/2022:15:10:14 +0100] "GET /geoserver/ogc/features/collections/Varldsarv%3APS.ProtectedSite/items?limit=unlimited HTTP/1.1" 400 87 "-" "Apache-HttpClient/4.5.13 (Java/1.8.0_332)" ORIGIN="-" "-" 0/3413

And surely, trying that value, "unlimited" returns an error _InvalidParameterValue_ and, it seems like there are flagged errors in the report linked to this test.

Looking at the core documentation, "limit" seems to be of type _integer_ only (which works). 

Having said that, I might be missing something :-)

Cheers!

//Lars

**Comment by fabiovinci** [comment]
Dear @LarsAll,

thank you for opening the issue.

Could you please provide us with the URL of the service under test, so we can reproduce the issue?

In any case, please take into consideration that the "OGC API - Features" test in the Validator simply uses, at the moment, the related "OGC API - Features Conformance Test Suite", so the related issue can be managed in the [related OGC repository](https://github.com/opengeospatial/ets-ogcapi-features10/issues).

**Comment by ghost** [comment]
@fabiovinci of course, https://insptest-v1.metria.se/geoserver/ogc/features/

Sorry for the delay!

**Comment by fabiovinci** [comment]
Dear @LarsAll,

it seems the resource provided is no longer available.

Do you still have the same error?

**Comment by fabiovinci** [comment]
Since there was no reply, we will close the issue.

Please open a new issue or reopen this one if the error persists.
