### ISSUE TITLE
Validation of metadata records with apiso.xsd in XML header leads to an error in HTML report.

### ISSUE THREAD

**Issue by ghost** [INSPIRE-MIF/helpdesk-validator#87]
Problem: 
Validation of metadata records with http://schemas.opengis.net/csw/2.0.2/profiles/apiso/1.0.0/apiso.xsd in XML header (schemaLocation attribute) leads to an error in HTML report. (permature end of file)

Description of the steps:
1. Validate a metadata record provided as an attachment ([dataset-metadata-apiso-xsd.zip](https://github.com/inspire-eu-validation/community/files/3405961/dataset-metadata-apiso-xsd.zip)) against Conformance Class 'XML encoding of ISO 19115/19119 metadata' in INSPIRE Validator
2. Observe HTML Report [Test run on 12 05 - 18.07.2019 with test suite Conformance class  Metadata for interoperability.zip](https://github.com/inspire-eu-validation/community/files/3406022/Test.run.on.12.05.-.18.07.2019.with.test.suite.Conformance.class.Metadata.for.interoperability.zip)
![schemaValidationError](https://user-images.githubusercontent.com/38787131/61448918-1ff4e180-a954-11e9-8d6f-c6e2dc5efe9f.jpg)
3. Name of the test that failed
http://inspire.ec.europa.eu/validator/v2/TestRuns/EIDdecc49d8-b259-468c-a82d-3c303f60bfb7.html?lang=de#EID1fb631b8-f77a-4e11-b25c-56680cdfcb0e
4. Validate a metadata record using AltovaXMLSpy.
Metadata record is valid according to AltovaXMLSpy.

The browser and version:
- Firefox Quantum 
- 60.8.0esr (64-Bit)

**Comment by josemasensio** [comment]
Dear @DeordD,

Thank you for your message. We have checked the issue and there is a problem with the schema location 
The current metadata schema location http://schemas.opengis.net/csw/2.0.2/profiles/apiso/1.0.0/apiso.xsd is throwing some errors because of HTTP/HTTPS conversion. As a temporal fix for this error we recommend to modify the schema location to https://inspire.ec.europa.eu/draft-schemas/inspire-md-schemas-temp/apiso-inspire/apiso-inspire.xsd.

Pleae, try to modify it and run again the validation.

Regards.

**Comment by josemasensio** [comment]
Dear @DeordD,

Does this solution work?

Regards.

**Comment by ghost** [comment]
Thanks a lot for the solution.

I have modified the schema location. (see [dataset-metadata-inspire-xsd.zip](https://github.com/inspire-eu-validation/community/files/3501616/dataset-metadata-inspire-xsd.zip))

Metadata record is valid. (see html report http://inspire.ec.europa.eu/validator/v2/TestRuns/EIDb8aa3e0e-0129-4eef-9bb2-11b63627c67e.html)

This temporary solution (workaround) works. 

When can we expect the solution where metadata records doesn't have to be modified every time before validation is started?

**Comment by ghost** [comment]
Like discussed in the workshop I have tested metadata record (https://github.com/inspire-eu-validation/community/files/3501616/dataset-metadata-inspire-xsd.zip) against following Testsuites:

1. Common Requirements for ISO/TC 19139:2007 based INSPIRE metadata records (TG 2.0)
2. Conformance class: XML encoding of ISO 19115/19119 metadata (XML-Validation standalone)

The reason why I have tested it against TG 2.0 is because this problem should only occur when testing against TG 1.3. 

Results:
1. Common Requirements for ISO/TC 19139:2007 based INSPIRE metadata records
![grafik](https://user-images.githubusercontent.com/38787131/66022290-c8472a80-e4ed-11e9-801f-e850ae79b1a3.png)
2. Conformance class: XML encoding of ISO 19115/19119 metadata 
![grafik](https://user-images.githubusercontent.com/38787131/66022303-db59fa80-e4ed-11e9-8472-46c36e1c8005.png)

The problem occurs when using only Conformance Class for XML-Encoding.

For more information see reports:
[apiso_TG2-0_191002.zip](https://github.com/inspire-eu-validation/community/files/3679718/apiso_TG2-0_191002.zip)
[apiso_XML_encoding_191002.zip](https://github.com/inspire-eu-validation/community/files/3679719/apiso_XML_encoding_191002.zip)

Is there any intention to solve the problem when using just this one class?

**Comment by fabiovin** [comment]
Dear @DeordD,
the schema validation behaviour for MD TG 1.3 has been modified, see relative [issue](https://github.com/inspire-eu-validation/community/issues/128).
You can test it in the staging instance.

**Comment by ghost** [comment]
Dear @fabiovin,

thanks a lot for the information.

Problem is solved. XML-Validation can be used in TG 1.3, TG 2.0 and standalone.
________________________________________________________________________________________________________
Here are the results of the tests in the staging instance in detail:

**1. Validation against **Conformance Class 'Metadata for interoperability'****

Metadata record for testing:
[dataset-metadata-apiso-xsd.zip](https://github.com/inspire-eu-validation/community/files/3738201/dataset-metadata-apiso-xsd.zip)

ETF-Report:
[TG_1-3_XML_Validation_APISO_191015.zip](https://github.com/inspire-eu-validation/community/files/3738219/TG_1-3_XML_Validation_APISO_191015.zip)

     Result: 
     Metadata record is valid as expected.
![grafik](https://user-images.githubusercontent.com/38787131/66811543-94c6c000-ef31-11e9-8e42-4d032ad2dbf8.png)

**2. Validation against **Conformance Class 'XML encoding of ISO 19115/19119 metadata'****

_CASE 1: XML is valid_

Metadata record for testing:
[dataset-metadata-apiso-xsd.zip](https://github.com/inspire-eu-validation/community/files/3738201/dataset-metadata-apiso-xsd.zip)

ETF-Report:
[XML_Validation_Standalone_APISO_191015.zip](https://github.com/inspire-eu-validation/community/files/3738190/XML_Validation_Standalone_APISO_191015.zip)

     Result: 
     Metadata record is valid as expected.
![grafik](https://user-images.githubusercontent.com/38787131/66813270-bd9c8480-ef34-11e9-98dd-b431ab74ec12.png)

_CASE 2: XML is not valid_

Metadata record for testing:
[dataset-metadata-apiso-xsd_not_valid.zip](https://github.com/inspire-eu-validation/community/files/3738205/dataset-metadata-apiso-xsd_not_valid.zip)

ETF-Report:     
[XML_Validation_Standalone_not_valid_APISO_191015.zip](https://github.com/inspire-eu-validation/community/files/3738197/XML_Validation_Standalone_not_valid_APISO_191015.zip)

     Result:
     Metadata record is not valid as expected.
![grafik](https://user-images.githubusercontent.com/38787131/66813960-0d2f8000-ef36-11e9-9b97-05d75c6d376d.png)

**Comment by ghost** [comment]
Dear @josemasensio ,

i am currently trying to validate https://github.com/inspire-eu-validation/community/files/3738201/dataset-metadata-apiso-xsd.zip considering "Description of the steps" from this issue.

Same problem occurs like stated in this issue.
![grafik](https://user-images.githubusercontent.com/38787131/68938941-ad7bfd00-079f-11ea-96b2-bcaf67624b82.png)


For more information see HTML report.
http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/v2/TestRuns/EID2f98196e-a416-412e-866f-95e540771c94.html 

Am I doing something wrong?

**Comment by josemasensio** [comment]
Dear @DeordD,

Thank you for your feedback. Please, can you open a new issue to get it tracked as a new incidence?
This will help us to organize the new deployment against production.

Thank you and best regards.

**Comment by ghost** [comment]
Dear @josemasensio ,

i will do it as you asked.

Bug description will be almost identical to https://github.com/inspire-eu-validation/community/issues/87#issue-469688483.

I will just provide link to new html report.

Is that ok for you?
