### ISSUE TITLE
Geometry error against GM_Curve

### ISSUE THREAD

**Issue by aquaterra** [INSPIRE-MIF/helpdesk-validator#871]
In application schema Geophysics of theme Geology I keep receiving this error:
"The constraint 'shape attribute of the spatial object type GeophProfile is of type GM_Curve' is violated."
I tried different things to avoid this error, but without success. gml:MultiCurve or gml:LineString should be OK as they both are subtypes of gml:AbstractGeometry, but I still get the same error. This is the case for as well sams:shape as for ge_gp:projectedGeometry.

An extract of the gml looks like:
<ge_gp:projectedGeometry><gml:LineString gml:id="projectedgeom.seis_1" srsDimension="2" srsName="http://www.opengis.net/def/crs/EPSG/0/4258"><gml:posList>51.04114952 5.67454198 51.04102307 5.67459549 51.04088762 5.67464876 51.04076116 5.67470227 51.0406347 5.67475578 51.04049926 5.67480904 ... </gml:posList></gml:LineString></ge_gp:projectedGeometry>

What am I doing wrong? Or is this an error wrongly given by the validator?

**Comment by fabiovinci** [comment]
Dear @aquaterra,

the shape attribute of the spatial object type _GeophProfile_ shall be of type `GM_Curve`, a sample encoding is the following:

```xml
            <sams:shape>
                <gml:Curve srsDimension="2" srsName="http://www.opengis.net/def/crs/EPSG/0/4258">
                    <gml:segments>
                        <gml:LineStringSegment interpolation="linear">
                            <gml:posList>51.04114952 5.67454198 51.04102307 5.67459549 51.04088762
                                5.67464876 51.04076116 5.67470227 51.0406347 5.67475578 51.04049926
                                5.67480904</gml:posList>
                        </gml:LineStringSegment>
                    </gml:segments>
                </gml:Curve>
            </sams:shape>
```

On the contrary, the projectedGeometry attribute of the spatial object types _GeophStation_, _GeophProfile_, _GeophObjectSet_ and _GeophSwath_ shall be of type `GM_Point`, `GM_Curve` or `GM_Surface`, therefore it can be encoded using different types of geometries.

I hope this helps you!

**Comment by aquaterra** [comment]
Thank you for your answer.
It looks a bit strange to me to map it this way. I made some changes and was able to map sams:shape as in your example. However for ge_gp:projectedGeometry it is impossible to do the same. From your comment it looks as if it should be easier than with sams:shape. I need to take a closer look at it to find a solution.

**Comment by aquaterra** [comment]
We found a solution on database-level. It needed a conversion to Curve before publishing in our geoserver.
Thanks a lot!
