### ISSUE TITLE
Unexpected CRS-error

### ISSUE THREAD

**Issue by aquaterra** [INSPIRE-MIF/helpdesk-validator#872]
For FeatureType Borehole in schema Geology elevation is given as depth only.
A specific coordinate reference system is used for this. It is also mentioned in the specification of geology theme (in table 2 as is given in the error message).
However, I do get an error on this in the validator:
"A spatial geometry uses an unexpected coordinate reference system 'http://www.opengis.net/gml/srs/epsg.xml#5730'. Please refer to table 2 of the data specification for the list of expected coordinate reference systems."

The code in gml is:
<ge:elevation srsDimension="1" srsName="http://www.opengis.net/def/crs/EPSG/0/5730">17.70</ge:elevation>

Is this an error in the validator? Or is there still something wrong in the code?

**Comment by fabiovinci** [comment]
Dear @aquaterra,

it seems that in the error message you reported there is a different URL than the one in the sample snippet, is correct?

Did you verify that all occurrences of the srsName attribute contain the right value (http://www.opengis.net/def/crs/EPSG/0/5730)?

**Comment by aquaterra** [comment]
Ah, the error was not in ge:elevation. It was in the shape of MappedInterval.
My mistake, apologies.
