### ISSUE TITLE
Validator INTERNAL_ERROR

### ISSUE THREAD

**Issue by Ana-SGA** [INSPIRE-MIF/helpdesk-validator#874]
Dear all,

when testing this service http://servisi.azo.hr/inspire/geos3/lcv/wfs?service=WFS&version=2.0.0&request=GetCapabilities I get "INTERNAL _ERROR" message on INSPIRE Validator + staging instance. Can you tell me is this connected to the INSPIRE Validator itself or is it something on part of the service?

**Comment by fabiovinci** [comment]
Dear @Ana-SGA,

the error is related to the OGC Test Suite, it seems the error message is quite clear, so you should try to fix the error in your service.

![image](https://user-images.githubusercontent.com/22212406/202144848-0bf3797f-c6a9-4ea4-9fc5-e2ea484cbf5f.png)

**Comment by Ana-SGA** [comment]
Dear @fabiovinci,
sorry, I didn't even try to open the report, my mistake. Thanks for helping.

**Comment by fabiovinci** [comment]
Dear @Ana-SGA,
since the fix is on your side, we will close the issue.
