### ISSUE TITLE
Link to an ETS assertion human description based on assertion GUID

### ISSUE THREAD

**Issue by klimeto** [INSPIRE-MIF/helpdesk-validator#88]
Dears,

I have been developing a customized validation report page, from where I would like to provide users with a link to further detailed description of a all assertion applied on tested object. Is there a way to build a URL to some documentation based on assertion GUID?

Example page:

![Screenshot_20190718-144457623](https://user-images.githubusercontent.com/7523262/61458377-a4525f00-a96a-11e9-8279-2a59261d5eb1.jpg)

The first column contains the assertion GUID extracted from ETF API.

Can it be used to get some further human readable description of the assertion?

Is there anything available?

Many thanks for support,
Tomáš

**Comment by josemasensio** [comment]
Dear @klimeto,

Thank you for your message.

We are checking the questions and we are going to answer you as soon as posible, so please be patient.

Best regards.

**Comment by carlospzurita** [comment]
Dear @klimeto 
You can use the API for this purpose. If you already located the TestSuite identifier, you can get a JSON representation using this call
`http://inspire.ec.europa.eu/validator/v2/ExecutableTestSuites/EIDe3500038-e37c-4dcf-806c-6bc82d585b3b`

Navigating through the executableTestSuite, testModules, testCases, testSteps until reaching the testAssertions key, you can find this representation

![imagen](https://user-images.githubusercontent.com/10537778/70793983-e5756080-1d9c-11ea-9794-0ca442013825.png)

You can take directly the description and use the HTML inside it.

If you have any other doubt or comments to this, please let us know.

**Comment by dperezBM** [comment]
Dear @klimeto,

We hope that the answer you were given would have helped you. In case you have any other questions or problems, please feel free to open a new issue.

Best regards.
