### ISSUE TITLE
Referencing code list outside INSPIRE register

### ISSUE THREAD

**Issue by marianhaluska** [INSPIRE-MIF/helpdesk-validator#882]
Hello,

I'm validating one of our datsets using INSPIRE validator. In this case I was testing the dataset interoperability against its INSPIRE schema. I would like to ask if there is a prefered way to use Empty code list. Should we use only INSPIRE pattern URI = http://inspire.ec.europa.eu/codelist/.... when mapping or can we use other patterns.

The problem I'm having is that the validator doesn't seem to accept other codelists references using HTTP URI, in this case provided by EIONET: http://dd.eionet.europa.eu/vocabulary/aq/zonetype/agg. I'm using this value to map specialisedZoneType in  schema for AM theme.

Remote file url that was tested: https://geo.shmu.sk/geoserver/am-aqmz/ows?service=WFS&version=2.0.0&request=GetFeature&typeNames=am-aqmz%3AManagementRestrictionOrRegulationZone&maxFeatures=1

![image](https://user-images.githubusercontent.com/118718455/203766696-c59912e0-dd12-4155-9fa1-36bc6dcfb5ff.png)

Can somesone help me with this issue.
Thank you very much in advance.

Marian

**Comment by fabiovinci** [comment]
Dear @marianhaluska,

the codelist value you used is ok, for empty codelists the validator only checks that the URL is valid.

I think it was a temporary problem in accessing the URL, I tried with the staging instance and the dataset is valid (see the report http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/test-run/details.html?id=EIDda615154-533b-453c-8315-af6b7cfe4d49)

**Comment by marianhaluska** [comment]
Dear @fabiovinci 

thank you for informing me. 

If you could elaborate a bit furder, as I understand it the validator checks if the URL provided is valid, meaning the URL is pointing to a specific location on the web. If the URL doesn't point to specific web location the test will fail, so you can't use lets say: http://inspire.ec.europa.eu/codelist/SpecialisedZoneTypeCode/agglomerations ,because the URL douesn't point to specific web location?

Thank you very much in advance.

Marian

**Comment by fabiovinci** [comment]
Dear @marianhaluska,

the check depends on the "[Extensibility](https://inspire.ec.europa.eu/registry/extensibility/)" property of the codelist:

- _Empty code list_: check that the URL is valid i.e. the codelist value is published in a register
- _Extensible with narrower values_ and _Extensible with values at any level_: check that the URL is valid if it doesn't come from the INSPIRE registry
- _Not extensible_: check that the value is one of the value present in the INSPIRE registry

For these reasons, the value "http://inspire.ec.europa.eu/codelist/SpecialisedZoneTypeCode/agglomerations" is not valid.

**Comment by marianhaluska** [comment]
Dear @fabiovinci 

Thank you for clarification. I will close the issue as the test was validated successfuly.

Thank you very much for your help.

Marian
