### ISSUE TITLE
LU - ExistingLandUseObject Code list test failing

### ISSUE THREAD

**Issue by robblis** [INSPIRE-MIF/helpdesk-validator#886]
Hi Validator Team,

We are testing the ExistingLandUseObject feature layer in the LU theme.

We see the following error reported by the Validator test...
Conformance class: 'Information accessibility, Land Use' > Code list > lu-ia.a.1.b: LandUseClassificationValue(specificValue)
Error: XML document 'service.xml', SpecificPercentage '': The attribute 'xlink:href' of the element 'LandUseClassificationValue' shall be provided.

We're not sure what this test is looking for. We are seeing the 'xlink:href' value returned in the xml snippet below
<lunom:SpecificPresence>
  <lunom:percentageList>
    <lunom:SpecificPercentage>
      <lunom:specificValue xlink:href="http://inspire.ec.europa.eu/codelist/LandUseClassificationValue/" xlink:title="1"/>
      <lunom:percentage>10</lunom:percentage>
    </lunom:SpecificPercentage>
  </lunom:percentageList>

Can we get some help on this?

Online service link: https://inspiredemo.esri.com/arcgis/rest/services/lu/MapServer/exts/InspireFeatureDownload/service?REQUEST=GetFeature&SERVICE=WFS&VERSION=2.0.0&TYPENAMES=elu:ExistingLandUseObject&COUNT=10&namespaces=xmlns(elu,http://inspire.ec.europa.eu/schemas/elu/4.0)

I've attached the service xml and the report if needed

Thanks,
Robert

[LU_ExistingLandUseObject_Service.zip](https://github.com/INSPIRE-MIF/helpdesk-validator/files/10117350/LU_ExistingLandUseObject_Service.zip)

**Comment by fabiovinci** [comment]
Dear @robblis,

please note that in your dataset there are five occurrences of an empty `lunom:specificValue` element, so the five errors refer to these elements.

![image](https://user-images.githubusercontent.com/22212406/206041821-0c968031-5f45-45fb-8fd6-4fc2ee3960ed.png)

**Comment by robblis** [comment]
Hi @fabiovinci ,

Thanks for the help.

We've retested after updating the data and all is good.

Robert
