### ISSUE TITLE
Why it is not possible to turn off test for Predefined WFS when testing Direct WFS?

### ISSUE THREAD

**Issue by Ana-SGA** [INSPIRE-MIF/helpdesk-validator#888]
Dear all,

can somebody explain why it is not possible to turn off test for Predefined WFS when testing Direct WFS?

**Comment by fabiovinci** [comment]
Dear @Ana-SGA,

we added the dependency to this conformance class because the tests included in it shall also be verified for a "Direct WFS".

See issue https://github.com/INSPIRE-MIF/helpdesk-validator/issues/476 for reference.

**Comment by Kate-Lyndegaard** [comment]
Dear @fabiovinci,

Where is it stated in the IRs, TGs or elsewhere, that a Direct WFS must serve stored queries? This issue is related to #890 

Kind regards,
Kate

**Comment by fabiovinci** [comment]
Dear all,
I'm closing this issue since it is duplicated.
Please follow issue #890 for updates on this topic.
