### ISSUE TITLE
Validate XML documents - how to express year only dates

### ISSUE THREAD

**Issue by felnne** [INSPIRE-MIF/helpdesk-validator#89]
Hello,

Attempting to validate [this file](https://gist.github.com/felnne/fd411703ce25ffa2ea4c42b6dab27fc0) as test run [EID838013e0-f6f2-4e7a-83bb-ba8d5db5f587](http://inspire.ec.europa.eu/validator/v2/TestRuns/EID838013e0-f6f2-4e7a-83bb-ba8d5db5f587.html) fails the *INSPIRE Profile based on EN ISO 19115 and EN ISO 19119* Conformance Class, specifically test: [md-iso.h.1: Temporal date](http://inspire.ec.europa.eu/validator/v2/TestRuns/EID838013e0-f6f2-4e7a-83bb-ba8d5db5f587.html?lang=en#EID563fcd5c-29cf-4f85-accd-ae1abc465241).

The validation error is:

```
The metadata record set has 1 record(s) with errors for this assertion.
XML document 'uk-pdc-test-record-iso-19115-inspire-gemini.xml', record 'b1a7d1b5-c419-41e7-9178-b1ffd76d5371': The metadata record has a date of publication, creation, or revision that is invalid (is not an xs:date or xs:dateTime). Found: 2018, 2018, 2018-10-08T14:40:44+00:00.
```

The expression is:

```
let $messages :=
	(for $record in $records
	 let $rid := $record/gmd:fileIdentifier/*/text()
	 let $timePeriods := $record/gmd:identificationInfo[1]/*/*[self::gmd:extent or self::srv:extent]/*/gmd:temporalElement/*/gmd:extent/*[self::gml:TimePeriod or self::gml31:TimePeriod]
	 let $invalidTimePeriods :=
		for $timePeriod in $timePeriods
		let $beginDate := ($timePeriod/*:begin/*:TimeInstant/*:timePosition/text(), $timePeriod/*:beginPosition/text())
		let $endDate := ($timePeriod/*:end/*:TimeInstant/*:timePosition/text(), $timePeriod/*:endPosition/text())
		(: NOTE: we exclude the case in which a gml:begin or gml:end references the gml:TimeInstant; this situation is checked by another test that this test depends upon :)
		let $validDate := (not($beginDate) or local:is-valid-date-or-dateTime($beginDate)) and (not($endDate) or local:is-valid-date-or-dateTime($endDate))
		return
		if ($validDate) then ()
		else $timePeriod
	 let $frameOnBeginPosition := boolean($timePeriods/*:beginPosition/*/@frame)
	 let $frameOnEndPosition := boolean($timePeriods/*:endPosition/*/@frame)
	 let $frameOnPeriod := boolean($timePeriods/@frame)
	 let $frameOnInstant := boolean($timePeriods/*:begin/*/@frame | $timePeriods/*:end/*/*:timePosition/@frame)
	 let $frameOnTimePosition := boolean($timePeriods/*:begin/*/@frame | $timePeriods/*:end/*/*:timePosition/@frame)
	 let $relevantDates := $record/gmd:identificationInfo[1]/*/gmd:citation/*/gmd:date/*[gmd:dateType/*/@codeListValue = ('publication','revision','creation')]/gmd:date/*
	 let $invalidRelevantDates :=
		for $relevantDate in $relevantDates
		let $validDate := local:is-valid-date-or-dateTime($relevantDate)
		return
		if ($validDate) then ()
		else $relevantDate
	 return
	 (if ($invalidTimePeriods) then
	 	let $invalidDates :=
			for $timePeriod in $timePeriods
			let $beginDate := ($timePeriod/*:begin/*:TimeInstant/*:timePosition/text(), $timePeriod/*:beginPosition/text())
			let $endDate := ($timePeriod/*:end/*:TimeInstant/*:timePosition/text(), $timePeriod/*:endPosition/text())
			return
			(if (local:is-valid-date-or-dateTime($beginDate)) then () else $beginDate,
			 if (local:is-valid-date-or-dateTime($endDate)) then () else $endDate)
		return
 		local:addMessage('TR.timePeriodWithInvalidDate', map { 'filename': local:filename($record), 'id': $rid, 'dates': fn:string-join($invalidDates, ', ') }) else (),
	  if ($frameOnBeginPosition) then
 		local:addMessage('TR.timePeriodWithFrameOnBeginPosition', map { 'filename': local:filename($record), 'id': $rid }) else (),
	  if ($frameOnEndPosition) then
		local:addMessage('TR.timePeriodWithFrameOnEndPosition', map { 'filename': local:filename($record), 'id': $rid }) else (),
	  if ($frameOnPeriod) then
		local:addMessage('TR.timePeriodWithFrame', map { 'filename': local:filename($record), 'id': $rid }) else (),
	  if ($frameOnInstant) then
		local:addMessage('TR.timePeriodWithFrameOnTimeInstant', map { 'filename': local:filename($record), 'id': $rid }) else (),
	  if ($frameOnTimePosition) then
		local:addMessage('TR.timePeriodWithFrameOnTimePosition', map { 'filename': local:filename($record), 'id': $rid }) else (),
	  if ($invalidRelevantDates) then
		local:addMessage('TR.invalidRelevantDate', map { 'filename': local:filename($record), 'id': $rid, 'dates': fn:string-join($relevantDates, ', ') }) else ())
	)[position() le $limitErrors]
return
(if ($messages) then 'FAILED' else 'PASSED',
 local:error-statistics('TR.recordsWithErrors', count(fn:distinct-values($messages//etf:argument[@token='id']/text()))),
 $messages)
```

In the case of this record only the year is known so a year only date was used. My understanding of `gco:Date` is that it's a union of:

* `xsd:date`
* `xsd:gYearMonth`
* `xsd:gYear`

In which case `2018` for example is a valid date as it's a valid `xsd:gYear`.

The ** test specifies:

> Relevant requirement(s):
> TG MD Requirement 24: The default reference system shall be the Gregorian calendar, with dates expressed in accordance with ISO 8601 (yyyy-mm-dd where yyyy is the year, mm is the month and dd is the day).

*TG Requirement C.11: metadata/2.0/req/common/temporal-reference* from [inspire-tg-metadata-iso19139-2.0.1.pdf](https://inspire.ec.europa.eu/sites/default/files/documents/metadata/inspire-tg-metadata-iso19139-2.0.1.pdf) states:

> The date values shall be expressed using Gregorian calendar and in accordance with [ISO 8601] with either date precision or date and time precision. For date precision the `gmd:CI_Date/gmd:date/gco:Date` element, and for date and time precision `gmd:CI_Date/gmd:date/gco:DateTime` element shall be used.

My reading of this is a year only date would be acceptable, as `gco:Date` and ISO 8601 both accept year only dates.

If a full date has to be used, is there a recommended way to represent unknown elements, as I want to avoid giving the impression that we know the month and date the resource was created when we don't (i.e. if we used `2018-01-01` instead).

**Comment by josemasensio** [comment]
Dear @felnne,

Thank you for your message. We are going to check what is happening here to give you an answer as soon as possible.

Best regards.

**Comment by josemasensio** [comment]
Dear @felnne,

We have been checking the issue and as you mentioned above, `gco:Date` must be `yyyy-mm-dd` where `yyyy` is the year, `mm` is the month and `dd` is the day, but maybe we can implement for just ask for the year. 

What do you think, @MarcoMinghini? Should we mark this for discussion?

Best regards.

**Comment by felnne** [comment]
Hi @bilbomaticaue,

Thanks for looking into this - can I just clarify where that definition of `gco:Date` comes from, as my reading of [this definition](http://www.datypic.com/sc/niem21/e-gco_Date.html) is that it's a union of:

* `xsd:date`
* `xsd:gYearMonth`
* `xsd:gYear`

In which case a year would be acceptable as it fits the requirements for `xsd:gYear`.

**Comment by josemasensio** [comment]
Dear @felnne,

We have checked the validation and nowadays we only check the `xs:date`. 

Is true that the validation or the TG must be changed. 

@MarcoMinghini, what do you think about modify the validation to allow the `xs:gYearMonth` and the `xs:gYear`?

Best regards.

**Comment by michellutz** [comment]
I looked a bit into this. 

Both IR and TG (v1.3 and v2.0) simply refer to ISO 8601-compliant dates and these also allow just specifying the year.

ISO 19115 says:

> **B.4.2 Date and DateTime information**
> Date: gives values for year, month and day. Character encoding of a date is a string which shall follow the format for date specified by ISO 8601. This class is documented in full in ISO/TS 19103.

ISO 19103 states:

> **6.5.2.8 Date**
> A date gives values for year, month and day. Figure 5 shows the Date type. Character encoding of a date is a string that shall follow the format for date specified in ISO 8601.

> ![image](https://user-images.githubusercontent.com/5517424/62048290-c8385f00-b20c-11e9-98b2-a4b38dc0b50f.png)

While the text is not that clear whether "only-year" dates are allowed in ISO 19100, the diagram indeed suggests that these are ok.

Since also the schema implementation allows it, I would suggest to relax the validation to allow also the `yyyy-mm` and `yyyy` dates.

I don't think the TGs would need any change.

**Comment by josemasensio** [comment]
Dear @felnne, 

We just relaxed de validation. The solution must be available soon. Waiting for your feedback

Best regards.

**Comment by felnne** [comment]
Hi @bilbomaticaue,

Thanks - I'm not sure what you meant about when this would be available to test, I just have and get the same error - http://inspire.ec.europa.eu/validator/v2/TestRuns/EID0430f9c5-3f01-4d3b-9335-6f316b445aa3.html

(There are two other failed tests which I'm aware of).

**Comment by michellutz** [comment]
@bilbomaticaue Please follow the agreed workflow for implementing bug fixes (i.e. using dedicated branches and pull requests), and give clear instructions to the users for testing a solution, once it is deployed in the staging instance. Thanks.

**Comment by josemasensio** [comment]
Dear @felnne,

Please, can you try on [staging enviroment](http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/) and give back your feedback please?

Best regards.

**Comment by felnne** [comment]
Hi @bilbomaticaue - just tried and that works 👍 

http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/v2/TestRuns/EID24564b35-feaa-4292-ba1a-d9befad15ccd.html

**Comment by josemasensio** [comment]
Dear @felnne,

Glad to hear good news. I will mark as solved this issue.

Regards.
