### ISSUE TITLE
OGC Team Engine timeout

### ISSUE THREAD

**Issue by Ana-SGA** [INSPIRE-MIF/helpdesk-validator#891]
Dear all, @jenriquesoriano,

testing of the WFS service http://servisi.azo.hr/tlo/wfs?request=GetCapabilities returns OGC Team Engine timeout and also doesn't execute tests for Direct WFS or Predefined WFS (test attached). Can anyone take a look?

Besides that, service http://services.bioportal.hr/wfs?service=WFS&request=GetCapabilities cannot be tested because the INSPIRE Validator keeps throwing an Error without explanation.

Are these errors a Validator issue or are they service errors?

**Comment by Ana-SGA** [comment]
Could the error for Direct WFS for the frist service be due to xmlns:tlo="http://tlo" definition in GetCapabilities that does'n exist? And also http://servisi.azo.hr/schemas/wfs/2.0/wfs.xsd that returns 503 Service Unavailable?

And for the second service error for xmlns:dzzpnpis="http://dzzpnpis" and http://services.bioportal.hr:80/schemas/wfs/2.0/wfs.xsd that doesn't open schema definition?

**Comment by fabiovinci** [comment]
Dear @Ana-SGA,

I confirm that the error related to the timeout of the OGC Team Engine is due to the unavailability of the wfs.xsd schema declared in the schema location attribute.

Please correct them (the official one is: http://schemas.opengis.net/wfs/2.0/wfs.xsd) and try to re-validate your services.

**Comment by Ana-SGA** [comment]
Dear @fabiovinci,

thank you, we will notify the contractor to fix the error. Thanks again!

**Comment by fabiovinci** [comment]
Dear @Ana-SGA,

since the fix is on your side, we will close the issue.
