### ISSUE TITLE
BU3D currentUse

### ISSUE THREAD

**Issue by StefanCiesilski** [INSPIRE-MIF/helpdesk-validator#898]
What ist the problem with the test bu-as.a11: currentUse:

![grafik](https://user-images.githubusercontent.com/50232158/208458227-39309a95-1034-4438-ad97-401e833d2d0d.png)

Testreport: https://yzyiqfakm4.execute-api.eu-west-1.amazonaws.com/validator/v2/TestRuns/EID42399cc9-d7d7-4027-8022-4b34cc34116e.xml

Data:
[BU3D_currentUse.zip](https://github.com/INSPIRE-MIF/helpdesk-validator/files/10260371/BU3D_currentUse.zip)

**Comment by fabiovinci** [comment]
Dear @StefanCiesilski,

the error is no longer present (see report https://inspire.ec.europa.eu/validator/test-run/index.html?id=EIDaae3c0cb-8776-4f6c-9f67-4952fb1e2b43), it was probably due to temporary unavailability of the INSPIRE Registry.

If the problem persists do not hesitate to reopen the issue.

**Comment by StefanCiesilski** [comment]
Dear @fabiovinci ,

the warning is also included in the report (report https://inspire.ec.europa.eu/validator/test-run/index.html?id=EIDaae3c0cb-8776-4f6c-9f67-4952fb1e2b43).

**Comment by fabiovinci** [comment]
Dear @StefanCiesilski,

sorry for the mistake, you are right the warning should not be present because you are using an INSPIRE codelist value.

We will review the related test.

**Comment by arantzaetxebarria** [comment]
Dear @StefanCiesilski 

We have implemented a solution that is present in the [staging environment](http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/home/index.html). Could you please verify that now is working as expected? Thanks

Regards,

Arantza

**Comment by StefanCiesilski** [comment]
Dear @arantzaetxebarria 
Super, it work!
