### ISSUE TITLE
Improving the user dialogue for the selection of the tests to execute

### ISSUE THREAD

**Issue by MarcoMinghini** [INSPIRE-MIF/helpdesk-validator#9]
After selecting the conformance classes to test, in the _Configure Test Run_ dialogue, the button _Optional Parameters_ allows to select the _Tests to execute_ by entering a regular expression. This is difficult to use for non-expert users. In addition, when clicking the _Test Suites_ button, a new section appears, which shows the selected test suites and related dependencies.

Therefore, a possible improvement would be to discard the _Tests to execute_ regular expression (thus, to discard the _Optional Parameters_ button) and to show the new section (opened from the the _Test Suites_ button) in the form of a tree, where the user can select/deselect some of the tests from the conformance classes previously selected by the user. The _Test Suites_ button may be renamed _Selected tests_ (or _Select tests_). The regular expression option would still be available through the API.

This mockup presents a possibility of displaying the dialogue with the new section in tree form:

![imagen](https://user-images.githubusercontent.com/10537778/47280387-82dc6680-d5d6-11e8-8b92-31e2dd04d9e6.png)

The tree may have more collapsible levels, since the Test Suites have more nested tags of TestModules, TestCases, TestSteps and Assertions. What is the "last" hierarchical level to show (and allow user to select)?

In addition, dependencies (between the conformance classes and test cases) must be taken into account when designing the tree, i.e. this improvement proposal is related to the improvement proposal #6. 

What are your views, comments and suggestions about this potential improvement?

**Comment by thijsbrentjens** [comment]
Nice to have, but low priority I think.

**Comment by MarcoMinghini** [comment]
[2017.4 meeting 2018-11-15]  the improvement proposal is considered to be nice, but with a low priority for implementation.

**Comment by frcaldeira** [comment]
This is a nice functionality, but  I agree that the priority should be low.

**Comment by AntoRot** [comment]
I agree too that the priority should be low.

**Comment by IGNCNIG** [comment]
I agree with @thijsbrentjens  and @AntoRot

**Comment by alitka** [comment]
I agree too: low priority.

**Comment by fabiovinci** [comment]
Dear all,

since this functionality has been introduced with the new UI, the issue can be closed.
