### ISSUE TITLE
OGC Team Engine endpoint requires credentials

### ISSUE THREAD

**Issue by jenriquesoriano** [INSPIRE-MIF/helpdesk-validator#900]
Dear Community,

a new version of the OGC Team Engine has been released requiring username and password for using it.
We are testing the use of these credentials in the [Staging ](http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/)environment for its correct operation and we will be working over the next days to adjust the production environment, so it is possible that you may encounter unavailability periods over time.
In the meantime, we recommend using the [Staging ](http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/)instance instead.

We apologise for the inconvenience.

**Comment by Ana-SGA** [comment]
Dear @jenriquesoriano,
when will we be able to test the services?

**Comment by jenriquesoriano** [comment]
Dear @Ana-SGA  
we are actively working to incorporate the credentials in the ETF. 
We will keep you posted by these means and as soon as it is solved, it will be communicated.

**Comment by Ana-SGA** [comment]
Dear @jenriquesoriano,

ok, thanks for the info.

**Comment by jenriquesoriano** [comment]
Dear @Ana-SGA , all,

we have aligned the [Staging ](http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/home/index.html)instance with the TEAM Engine instance using credentials.
We will propagate these changes to production in the short term and also include it in the upcoming v2023.0 release (exact release date to be announced as soon as this issue solved).

Please let us know if it works accordingly in the [Staging ](http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/home/index.html) instance.

**Comment by Ana-SGA** [comment]
Dear @jenriquesoriano,
now we can test download services on staging instance. At this moment we don't have services that have credentials, so I couldn't test it.

**Comment by jenriquesoriano** [comment]
Dear @Ana-SGA , all,

thanks for your feedback.
Just for clarification, the TEAM Engine services are requiring credentials at their end in order to use their services, then the INSPIRE Reference Validator needs to be registered in the TEAM Engine and send these credentials accordingly, so it needed some adjustments on the INSPIRE Reference Validator side source code.
This is not related with the credentials to access to an specific WFS service, so you can test these services regardless the WFS access is with our without credentials in the services endpoint.

**Comment by jenriquesoriano** [comment]
Dear all, 

we have propagated the TEAM Engine credentials to the production instance, so the services making use of them are operating accordingly.
This behaviour will be also incorporated in the [upcoming release v2023.0](https://github.com/INSPIRE-MIF/helpdesk-validator/issues/913).
Please let us know if you encounter any issue at this regard.

Best
