### ISSUE TITLE
Can't test download services

### ISSUE THREAD

**Issue by Ana-SGA** [INSPIRE-MIF/helpdesk-validator#906]
Dear all,

can someone tell me why it is not possible to test download services, mostly WFS? Thanks.

**Comment by jenriquesoriano** [comment]
Dear @Ana-SGA , 

thank you for your request.
Please note that the OGC has implemented the use of credentials in the Team Engine, so we are adapting all the services that make use of the Team Engine to incorporate these credentials.
As usual, we are testing it first in [Staging ](http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/home/index.html)and, once it is validated, we will upload it to the [Production environment](https://inspire.ec.europa.eu/validator/home/index.html).
We have created and pinned a specific [issue ](https://github.com/INSPIRE-MIF/helpdesk-validator/issues/900)to make it easier the follow up, through which we will communicate in a general level the progress made in this regard.

**Comment by Ana-SGA** [comment]
Dear @jenriquesoriano ,

so are the works you mentioned the cause of the impossibility of download service testing? It seems that the same thing happens on the staging instance.

**Comment by fabiovinci** [comment]
Dear @Ana-SGA,

the solution was released in production.
I will close this issue since duplicate the issue #900
