### ISSUE TITLE
I can't test data sets

### ISSUE THREAD

**Issue by Dominikinfair** [INSPIRE-MIF/helpdesk-validator#907]
Good morning,
Today testing of data sets is impossible (yesterday was ok).  After uploading the file and pressing "Start test", the message "An error has occured" is displayed.
Thanks in advance for help. Best regards.

**Comment by fabiovinci** [comment]
Dear @Dominikinfair,

looking at the test report page it seems that there are many tests executed this morning on datasets, it is possible that you tried at a time when the validator was overloaded.
