### ISSUE TITLE
ATOM Query examples for each dataset is skipped

### ISSUE THREAD

**Issue by Ana-SGA** [INSPIRE-MIF/helpdesk-validator#909]
Dear all,

can someone take a look at this service https://transformiraj.nipp.hr/services/bsp/org.4.67819338-7b65-42ee-ae93-76019be7ff75/service/atom/id_predefined_dataset? The test for OpenSearch Description - Query examples for each dataset is skipped and our contractor says they have checked the OpenSearch description of the provided Atom Feed example against the TG Requirement 44 and they are fulfilled. 

Test results https://inspire.ec.europa.eu/validator/test-run/details.html?id=EID11264b5c-c776-4fc2-8e32-a64d013fbd7b

**Comment by fabiovinci** [comment]
Dear @Ana-SGA,

the service is no longer available, could you please verify?

**Comment by Ana-SGA** [comment]
Dear @fabiovinci ,
sorry for the missing url, this one is correct https://transformiraj.nipp.hr/services/bsp/org.4.a172153a-3301-4d82-b3ec-4ea84817979b/service/atom/id_predefined_dataset, and the test https://inspire.ec.europa.eu/validator/test-run/details.html?id=EID7a48bc9f-063f-4873-8874-312477a1b8cf. Thanks for looking.

**Comment by fabiovinci** [comment]
Dear @Ana-SGA,

it seems the service is not available again.
I will close the issue but please reopen it if the service is restored and the error persists.
