### ISSUE TITLE
Unable to validate document via URL

### ISSUE THREAD

**Issue by felnne** [INSPIRE-MIF/helpdesk-validator#91]
I am trying to validate a document from a URL but am getting an error:

> Test Run initialization failure
> The test object type could not be determined. Check the uploaded / referenced resource. Uploaded files may only contain test data and no other files. If the problem persists, please contact the ETF system administrator of the server.

The URL I am testing is:

https://gist.githubusercontent.com/felnne/fd411703ce25ffa2ea4c42b6dab27fc0/raw/4a8e3e09b25612b95daad0601a605072d983417a/uk-pdc-test-record-iso-19115-inspire-gemini.xml

I've used this exact same successfully before (most recently as part of #89, but now don't seem able to.

Are there any specific things I should check? I don't quite understand what an *object type* is in this context?

Thanks.

**Comment by josemasensio** [comment]
Dear @felnne,

Is the same test that we fix on #89?

Regards.

**Comment by felnne** [comment]
Hi @bilbomaticaue - it's the same test, but it happens if I just use the ISO 19115 conformance class as well. As in it doesn't actually load the record to be validated.

**Comment by josemasensio** [comment]
Dear @felnne,

On your xml file you have to change this `<gco:Boolean nilReason=“unknown” />` to this                                 `<gco:Boolean nilReason="unknown">`

The quotation marks that are used are giving format error. Try to modify that and please give us your feedback.

Best regards.

**Comment by felnne** [comment]
Thanks @bilbomaticaue that's fixed it - didn't spot those had crept in.
