### ISSUE TITLE
File upload Error to test the metadata of a dataset

### ISSUE THREAD

**Issue by PatriciaCabrera** [INSPIRE-MIF/helpdesk-validator#910]
File upload to test the metadata of a dataset fails with these browsers:
Google Chrome Version 109.0.5414.74
Mozilla Firefox 108.0.2

ERROR
An error has occurred uploading file (Code: 400 - Bad Request)

The xml files I am testing are these:
- https://www.vliz.be/en/imis?module=dataset&dasid=7899&show=inspire
- https://www.vliz.be/en/imis?module=dataset&dasid=8141&show=inspire

**Comment by fabiovinci** [comment]
Dear @PatriciaCabrera,

the error seems due to the particular form of the URL you are using, even if it works in the browser the validator does not seem able to verify that it is a metadata document.

Do you have a different way to access the metadata, e.g. CSW request?

In any case, we will have a look, and in the meantime, you can save the metadata as XML and validate it through the "File upload" option.

**Comment by PatriciaCabrera** [comment]
Dear @fabiovinci 
Thank you for looking into my issue. 

We don't have a different way to access the metadata.
Saving the metadata in an xml file and using the file upload option works for me. 

I would like to know how to fix the form of our URL, for future tests and to avoid the step of having to save the file. 

Thank you,
Patricia

**Comment by manuelaromero-guadaltel** [comment]
Dear @PatriciaCabrera,

We have tested it and it seems that the metadata's server doesn't accept the following URL:
https://www.vliz.be/en/imis?module=dataset&dasid=7899&show=inspire&outputSchema=http://www.isotc211.org/2005/gmd&elementSetName=full

As you can see the INSPIRE Reference Validator add automatically two parameters if they are not defined. Those are "outputSchema" and "elementSetName", both needed to ensure the correct functioning of the INSPIRE Reference Validator.

At this moment, any access to this link will return a 403 Forbidden message

Please, modify the service to be able to access it through this URL and then you will be able to test this service through the remote file option.

**Comment by jenriquesoriano** [comment]
Dear @PatriciaCabrera ,

just to ping in order to know if you were able to progress with this issue or if you need addditional clarifications from our side.
Please let us know if you need further feedback.

**Comment by PatriciaCabrera** [comment]
Dear @jenriquesoriano ,

The IT departament is looking at this issue. Thanks for input and reminder. I will come back to this as soon as we have fixed it. Thanks!

**Comment by fabiovinci** [comment]
Dear @PatriciaCabrera,

it seems you were able to solve the issue since your metadata can now be loaded on the validator, do you confirm?

**Comment by PatriciaCabrera** [comment]
Dear @fabiovinci, yes it is solved! thanks a lot
