### ISSUE TITLE
Data set test fails - http://inspire.ec.europa.eu cannot be accessed and premature end of file

### ISSUE THREAD

**Issue by montsemarco** [INSPIRE-MIF/helpdesk-validator#911]
Hello,

We have a Production Facilities dataset that is not passing the INSPIRE Validator anymore. 
When we implemented the gml this dataset was passing it.

The failing data set is: http://sitmun.diba.cat/opendata/inspire/PF/SPADB-PF-INSPIRE-08004-4258.zip
The Validator Report is: https://inspire.ec.europa.eu/validator/test-run/details.html?id=EIDe45d48ef-fbe2-4719-b59d-cf38510304e7

The Validator is reporting this errors:
Error information:Code list http://inspire.ec.europa.eu/codelist/NativenessValue cannot be accessed.
Error information:Code list http://inspire.ec.europa.eu/codelist/NameStatusValue cannot be accessed.
Error information:Code list http://inspire.ec.europa.eu/codelist/GrammaticalGenderValue cannot be accessed.
Error information:Code list http://inspire.ec.europa.eu/codelist/GrammaticalNumberValue cannot be accessed.
-1:-1: Premature end of file.

And, efectively, when accessing the Web http://inspire.ec.europa.eu/codelist there is an unavailability error message.

What can we do to solve this validator errors? 
Thanks and best regards,
Montse

**Comment by fabiovinci** [comment]
Dear @montsemarco,

usually, this type of errors are due to a temporary unavailability of external resources.

Now it works and your dataset is valid, see the report https://inspire.ec.europa.eu/validator/test-run/index.html?id=EIDe678c004-4225-438a-b738-3a0048cfd91d
