### ISSUE TITLE
Feature references (HTTP status code 302)

### ISSUE THREAD

**Issue by Dnoack49** [INSPIRE-MIF/helpdesk-validator#912]
Dear all,

1.) a description of the steps to reproduce your issue

We have validated the following Address-Dataset: 
https://inspire.brandenburg.de/services/ad_alkis_wfs?service=WFS&version=2.0.0&request=GetFeature&Count=10&typenames=ad:Address 

and received error messages, that properties reference resources that cannot be accessed (for instance: https://registry.gdi-de.org/id/de.bb.inspire.ad.alkis/AdminUnitName_12062341) - the reason is: `The HTTP status code when requesting the resource is: '302'. A status code of '200' is expected.`

2.) used browser and version: `Firefox Browser 108.0.1 (64-Bit)`

3.) a screenshot illustrating the problem
![grafik](https://user-images.githubusercontent.com/8046960/213654588-6aeb2d07-ea87-4115-aea0-2bf75e173627.png)

4.) the Test Report
[Test run on 17 38 - 19.01.2023 with test suite Annex I - Addresses (AD).zip](https://github.com/INSPIRE-MIF/helpdesk-validator/files/10464655/Test.run.on.17.38.-.19.01.2023.with.test.suite.Annex.I.-.Addresses.AD.zip)

5.)  the name of the Test that failed :  
Conformance class: Information accessibility, Adresses // Feature references//ad-ia.b.1:Address.component

Indeed the GET-Request of e.g. https://registry.gdi-de.org/id/de.bb.inspire.ad.alkis/AdminUnitName_12062
leads to  a Code `302` (Found):
![grafik](https://user-images.githubusercontent.com/8046960/213656556-4258126e-6488-4693-b827-0ac4037ac497.png)

For us the question is: 
Shouldn't the validator also expect/accept 302 as a valid return ?
This might be treated similar to the issue  [md sds 3.6: Coupled Resource #190 ](https://github.com/INSPIRE-MIF/helpdesk-validator/issues/190)

kind regards

**Comment by fabiovinci** [comment]
Dear @Dnoack49,

thank you for the issue, it was already solved for all the data themes (see my [comment on issue 559](https://github.com/INSPIRE-MIF/helpdesk-validator/issues/559#issuecomment-1381928193)).

The solution is already available in the [staging instance](http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/home/index.html), see the [report for your dataset](http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/test-run/details.html?id=EIDb6d552a5-80f3-408f-9712-23f55bc60045).
The only remaining errors are related to the link https://registry.gdi-de.org/id/de.bb.inspire.ad.alkis/AdminUnitName_120 which is not available.

The solution will be included in the release 2023.0 that will be released in the coming days.

**Comment by Dnoack49** [comment]
Dear @fabiovinci ,
indeed it is fixed. Thank you, shall I close the issue?

**Comment by fabiovinci** [comment]
Thank you, @Dnoack49, for testing the solution.
We will close the issue after the release.
