### ISSUE TITLE
Can't validate data set because of coordinate reference system definition unavailable

### ISSUE THREAD

**Issue by Dominikinfair** [INSPIRE-MIF/helpdesk-validator#914]
Dear all,

We can not validate the data sets with declaration of crs: srsName="http://www.opengis.net/def/crs/EPSG/0/4258" srsDimension="2"  There are errors: "XML document 'RoadSource.gml', RoadLink 'RD_PL_28_599': A spatial or temporal geometry uses an unexpected coordinate reference system with identifier 'http://www.opengis.net/def/crs/EPSG/0/4258' that cannot be retrieved. Every URI must be a HTTP URI in a CRS register that when retrieved with HTTP GET returns a definition of the reference system."

![obraz](https://user-images.githubusercontent.com/122445420/214258652-1e376bc6-1708-4eda-a8a9-5c7be4298794.png)

It is probably because of "503 Service Temporarily Unavailable"  on http://www.opengis.net/def/crs/EPSG/0/4258 

Could you please advise us how to solve this problem and do the validations?

Best regards,
Dominik

**Comment by fabiovinci** [comment]
Dear @Dominikinfair,

thank you for reporting the error, since it is due to the unavailability of the resource and the value present in your dataset is the right one, you can skip it at the moment.

We will verify why the OpenGIS repository doesn't work.

**Comment by fabiovinci** [comment]
Dear @Dominikinfair,

the OpenGIS repository works properly now.
