### ISSUE TITLE
WMS Language Requirement error with GeoServer Internationalization capability

### ISSUE THREAD

**Issue by marianhaluska** [INSPIRE-MIF/helpdesk-validator#918]
Hello everyone,

I've been triing to identify a problem I'am facing. Recently we upgraded to newer version of GeoServer (2.21.2) that supports Internationalization (returning a GetCapabilities document in various languages). I did set language versions to support English and Slovak languages but it seems that there is some problem with the funcionality.

I'am sending WMS Capability dokument URL that was tested: https://geo.shmu.sk/geoserver/am-aqmz/ows?request=GetCapabilities&service=WMS&version=1.3.0 

As far as I was able to determine, the problem seems to by in the version of ISO standard that GeoServer uses for its encoding. Is there anyone that has expirienced this problem and could point me to a possible solution.

**Comment by fabiovinci** [comment]
Dear @marianhaluska,

we will take a look at your service and try to give you feedback.

**Comment by lorincztamas** [comment]
Hello!

I have the same problem with geoserver 2.22.4
(build 18-Jun-2023 11:14) when upgrading English and Hungarian language in "internationalization".

I was wondering if there is a solution yet.

Thanks
Tamás

**Comment by fabiovinci** [comment]
Dear all,

I had a look at the issue and it seems that it is related to GeoServer and not to the Validator, so I will move this issue in the Discussions section.

I saw your issue in the dedicated repository (https://osgeo-org.atlassian.net/browse/GEOS-10852), we hope there will soon be a solution.
