### ISSUE TITLE
Schema Validation Fails: xml encoding of ISO 19115/19119 metadata

### ISSUE THREAD

**Issue by svanlill** [INSPIRE-MIF/helpdesk-validator#92]
Hi 
I am validating a metadata document and I'm getting an error.  See attached ValidationFailed. Please note the URL (http://www.isotc211.org/2005/gmd) highlighted in yellow. This URL is in the xml document, but when I hit that in a browser, it redirects to https.  So I'm thinking, the issue is with the URL. It should be (https://www.isotc211.org/2005/gmd) in my xml. However, when I change that URL to https (see attached httpsChanged), I can't upload the file anymore (see attached uploadFailed).

Can you please:
(1) advise on why my xml is failing if that "http://www.isotc211.org/2005/gmd" is declared in gmd:MD_Metadata. Am I missing something here?
(2) advise on why I can't upload an xml that references "https://www.isotc211.org/2005/gmd" in gmd:MD_Metadata.

Thanks for all your help.
Schalk
![ValidationFailed](https://user-images.githubusercontent.com/20442578/62141645-d78adb80-b2e4-11e9-900a-618ca12ed131.PNG)
![httpsChange](https://user-images.githubusercontent.com/20442578/62141662-deb1e980-b2e4-11e9-977e-96bab07c11fc.PNG)
![UploadFailed](https://user-images.githubusercontent.com/20442578/62141670-e2457080-b2e4-11e9-9f0c-7e2c437542ad.PNG)

**Comment by fabiovin** [comment]
Dear @svanlill,

it seems that in your xml file is not present the attribute "`xsi:schemaLocation`" by which you must declare the reference namespace and schema.

Could you please try to add it (`xsi:schemaLocation="http://www.isotc211.org/2005/gmd https://inspire.ec.europa.eu/draft-schemas/inspire-md-schemas-temp/apiso-inspire/apiso-inspire.xsd"`) and validate again?

**Comment by svanlill** [comment]
Hi Fabio

Thanks very much for the prompt reply. Unfortunately, adding (xsi:schemaLocation="http://www.isotc211.org/2005/gmd http://schemas.opengis.net/csw/2.0.2/profiles/apiso/1.0.0/apiso.xsd<http://www.isotc211.org/2005/gmd%20http:/schemas.opengis.net/csw/2.0.2/profiles/apiso/1.0.0/apiso.xsd>") results in the same red “Upload failed” error.

I then tested adding (xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation=http://www.isotc211.org/2005/gmd http://schemas.opengis.net/csw/2.0.2/profiles/apiso/1.0.0/apiso.xsd<http://www.isotc211.org/2005/gmd%20http:/schemas.opengis.net/csw/2.0.2/profiles/apiso/1.0.0/apiso.xsd>). I can upload the file then, but get another error.  See screenshot suggesting Premature end of file.

[cid:image001.png@01D54779.5C3A57C0]

The XML I’m using is valid. Tested here: https://codebeautify.org/xmlvalidator

This is what I now have for namespaces:
[cid:image002.png@01D54779.9E98DA10]

Any help is appreciated.
Schalk

**Comment by fabiovin** [comment]
Hi @svanlill,

sorry for the mistake on the xsd link, I instantly edited my message but probably you referred to the notification email related to the first wrong message.

The right attribute is: 

`xsi:schemaLocation="http://www.isotc211.org/2005/gmd https://inspire.ec.europa.eu/draft-schemas/inspire-md-schemas-temp/apiso-inspire/apiso-inspire.xsd"`

**Comment by svanlill** [comment]
Hi @fabiovin,

Thanks very much for that. When I add that, without xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance", it fails to upload. So I add that text as well. Then I upload and test. It results in a fail with loads of these errors. XML document 'Test.xml': 5:17: schema_reference.4: Failed to read schema document 'https://schemas.opengis.net/csw/2.0.2/profiles/apiso/1.0.0/apiso.xsd', because 1) could not find the document; 2) the document could not be read; 3) the root element of the document is not <xsd:schema> (see [this link](http://inspire.ec.europa.eu/validator/v2/TestRuns/EIDfe6db5fb-33a5-4970-bcb3-636faea25bdf.html)). 

I then amended the namespaces to be https for the ones I added: 
<gmd:MD_Metadata
	xmlns:gmd="http://www.isotc211.org/2005/gmd"
	xmlns:gco="http://www.isotc211.org/2005/gco"
	xmlns:srv="http://www.isotc211.org/2005/srv"
	xmlns:gml="http://www.opengis.net/gml"
	xmlns:xlink="http://www.w3.org/1999/xlink"
	xmlns:xsi="https://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="https://www.isotc211.org/2005/gmd https://schemas.opengis.net/csw/2.0.2/profiles/apiso/1.0.0/apiso.xsd">
	<gmd:fileIdentifier>

It fails again with this error:
XML document 'Test.xml', record '{230A3121-F6A7-4210-AE7C-7FCD75F6EA8A}': 1:414: cvc-elt.1.a: Cannot find the declaration of element 'gmd:MD_Metadata'. 

So, I am unclear why it is failing. Any suggestions?

Regards
Schalk

**Comment by fabiovin** [comment]
Hi @svanlill,
the gmd namespace is: `http://www.isotc211.org/2005/gmd`,
and the `apiso.xsd` is not accessible from the opengis repository (due to an "http to https" redirect issue).

So, could you try to use **exactly** the following value:
**xsi:schemaLocation="http://www.isotc211.org/2005/gmd https://inspire.ec.europa.eu/draft-schemas/inspire-md-schemas-temp/apiso-inspire/apiso-inspire.xsd"**

**Comment by svanlill** [comment]
Hi @fabiovin 

Apologies. Copy/paste error. Alas, same result with same failed message. See [link](http://inspire.ec.europa.eu/validator/v2/TestRuns/EIDc43bf21b-93d5-4732-931a-96eb008ad9a4.html). So still not sure what the error refers to.  

Is the xsi:SchemaLocation attribute a requirement of the Validator or a requirement for Inspire metadata?

What I have for gmd:MD_Metadata:
<gmd:MD_Metadata xmlns:gmd="http://www.isotc211.org/2005/gmd" xmlns:gco="http://www.isotc211.org/2005/gco" xmlns:srv="http://www.isotc211.org/2005/srv" xmlns:gml="http://www.opengis.net/gml" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:xsi="https://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.isotc211.org/2005/gmd https://inspire.ec.europa.eu/draft-schemas/inspire-md-schemas-temp/apiso-inspire/apiso-inspire.xsd">

Thanks for the help!
Schalk

**Comment by fabiovin** [comment]
Hi @svanlill 
could you please send the XML file to check it out?

**Comment by svanlill** [comment]
Hi @fabiovin 

Thanks for your help with this. I attached the zipped xml.
[Test.zip](https://github.com/inspire-eu-validation/community/files/3452027/Test.zip)

Regards
Schalk

**Comment by fabiovin** [comment]
Hi @svanlill 

there are some wrong attributes in the header, please make the following substitutions:

- xmlns:gml="http://www.opengis.net/gml/ --> xmlns:gml="http://www.opengis.net/gml/3.2

- xmlns:xsi="https://www.w3.org/2001/XMLSchema-instance" --> xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance".

Now the file is valid: http://inspire.ec.europa.eu/validator/v2/TestRuns/EIDaf650edc-b6c6-45dc-9a8b-94753e4a716d.html

**Comment by svanlill** [comment]
Thanks very much for all your help @fabiovin 

Regards
Schalk

**Comment by josemasensio** [comment]
Dear @svanlill,

Has your problem been fixed?

Best regards.

**Comment by svanlill** [comment]
Hi @bilbomaticaue 

Yes. @fabiovin's advice helped to fix the issue I was having. 

Regards
Schalk
