### ISSUE TITLE
Test Report Page not loaded

### ISSUE THREAD

**Issue by manilly** [INSPIRE-MIF/helpdesk-validator#925]
Hi,
I have a problem on our local Validator instance: https://inspire.agrarforschung.at/
The Test Report Page (https://inspire.agrarforschung.at/test-reports/index.html) is not loading. The console output says: 
`angular.js:15697 ReferenceError: timeUpMessage is not defined
    at Object.<anonymous> (controller.js:7:25)
    at Object.invoke (angular.js:5208:16)
    at S.instance (angular.js:11814:24)
    at p (angular.js:10627:33)
    at g (angular.js:9942:13)
    at g (angular.js:9945:13)
    at angular.js:9807:30
    at angular.js:1968:11
    at m.$eval (angular.js:19523:16)
    at m.$apply (angular.js:19622:20)`

Do you have any idea, what could be the problem?

Thanks, Manuel

**Comment by manilly** [comment]
do you have any idea? Still doesn't work with 2023.1

**Comment by jenriquesoriano** [comment]
Dear @manilly ,

thanks for your feedback.

We don't know the details about your implementation but it seems that this issue could be related with a new message that appears in the test report page. 
A possible cause of this issue may be that there is a missing var called timeUpMessage in your config.js. 

However, as we don't know details of your implemantation, if you could share your config.js with us, we could progress with this approach.

If there is any more detail that could help us to find the cause and solution of this issue, please share it with us.

Best regards,

**Comment by manilly** [comment]
Thanks, this was the problem. We used a old config.js where timeUpMessage was missing.
