### ISSUE TITLE
Can't download or view validator report

### ISSUE THREAD

**Issue by manilly** [INSPIRE-MIF/helpdesk-validator#926]
Hello,
I'm not able to view or download the test report from this URL: https://yzyiqfakm4.execute-api.eu-west-1.amazonaws.com/validator/v2/TestRuns/EID1552ed95-e797-4a07-81e7-0bb793414366.html?download=true

```
// 20230227113617
// https://yzyiqfakm4.execute-api.eu-west-1.amazonaws.com/validator/v2/TestRuns/EID1552ed95-e797-4a07-81e7-0bb793414366.html


{
  "message": "Internal server error"
}
```

**Comment by fabiovinci** [comment]
Dear @manilly,

could you please send us the resource under test in order to reproduce the error? Thanks

**Comment by manilly** [comment]
The tested ressource is a csw getRecords Link
https://geometadaten.lfrz.at/at.lfrz.discoveryservices/srv/ger/csw?service=CSW&version=2.0.2&request=GetRecords&resultType=results&outputSchema=http://www.isotc211.org/2005/gmd&typeNames=gmd:MD_Metadata&elementSetName=full&maxRecords=1000&constraintLanguage=CQL_TEXT&constraint_language_version=1.1.0&constraint=Type=%27service%27

**Comment by fabiovinci** [comment]
Dear @manilly,

what is the resource you want to test? Is the CSW service or a metadata record?

In the link you used, there is the parameter "maxRecords=1000", so the validator is not able to generate a report for such a number of metadata.

**Comment by manilly** [comment]
Dear @fabiovinci,
I wan't to generate a report for all Austrian Metadata records. So I'm testing all records from the csw. Normally I do it in our austrian validator instance, unfortunately recently we have a problem there showing test reports, which I'm not able to fix (see https://github.com/INSPIRE-MIF/helpdesk-validator/issues/925)

**Comment by fabiovinci** [comment]
Dear @manilly,

for massive validations, I would suggest using the [Bulk validation tool](https://github.com/inspire-eu-validation/monitoring-bulk-validation-tool), used for the Monitoring&Reporting.
The tool allows for validating service and dataset metadata at once, generating separate reports.

The public validator instance cannot guarantee massive validations.

**Comment by fabiovinci** [comment]
It seems the staging instance was able to generate the report: http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/test-run/details.html?id=EID28adc0c1-dae0-4456-9e2a-cfac70383bc7

**Comment by manilly** [comment]
thanks
