### ISSUE TITLE
IACS Temporal reference - Citation date

### ISSUE THREAD

**Issue by m2fuhrmann** [INSPIRE-MIF/helpdesk-validator#927]
- [x] a description of the steps to reproduce your issue
1. ) go to: https://inspire.ec.europa.eu/validator/test-selection/index.html and configure the test: 

**Select the INSPIRE resource you would like to test**
  * Metadata
  
**Select the Technical Guidelines version**
  * Version 2.0

**Select the type of metadata record(s) to be tested**
  * Data sets and data set series

**Select the conformance classes to be assessed**
  * Common Requirements for ISO/TC 19139:2007 based INSPIRE metadata records
  * Conformance Class 1: 'Baseline metadata for data sets and data set series
  * Conformance Class 2: 'INSPIRE data sets and data set series interoperability metadata'
  * Conformance Class 2b: 'INSPIRE data sets and data set series metadata for Monitoring'
  * Conformance Class 2c: 'INSPIRE data sets and data set series metadata for IACS'

3.)  upload the XML-file and start the test  : 
[2022-12-01_9e95f21f-4ecf-4682-9a44-e5f7609f6fa0.zip](https://github.com/INSPIRE-MIF/helpdesk-validator/files/10870140/2022-12-01_9e95f21f-4ecf-4682-9a44-e5f7609f6fa0.zip)

- [x] the browser and version used : **Google Chrome Version 110.0.5481.178 (Offizieller Build) (64-Bit)**

- [x] a screenshot illustrating the problem:
![IACS_Temporal_reference](https://user-images.githubusercontent.com/126700157/222400574-3b25058c-78cb-4bee-a1e0-4ac98a8a94a7.PNG)

- [x] the Test Report (ideally as an attachment to the issue)
[Test run on 11_11 - 02.03.2023 with test suite Conformance Class 2c_ INSPIRE data sets and data set series metadata for IACS.html.zip](https://github.com/INSPIRE-MIF/helpdesk-validator/files/10870236/Test.run.on.11_11.-.02.03.2023.with.test.suite.Conformance.Class.2c_.INSPIRE.data.sets.and.data.set.series.metadata.for.IACS.html.zip)

- [x] the name of the Test that failed or better: change the `Level of Detail`
in the Report by clicking on `All Details`, then scroll down to the failed test
and copy the Link on the right-hand side of the `Assertion URI` : https://yzyiqfakm4.execute-api.eu-west-1.amazonaws.com/validator/v2/TestRuns/EID974aa279-bf3c-4fcc-8aeb-15c876cc6c29.html?lang=de#EID1d669a53-9c6c-4ced-a3c3-7d3e5be6ce70

- [x] the Problem:
The INSPIRE TG Version 2.0.1 says:
TG Requirement C.11:  ... The date values shall be expressed using Gregorian calendar and in accordance with [ISO 8601] with either date precision or date and time precision. For date precision the  ``` gmd:CI_Date/gmd:date/gco:Date``` element, and for date and time precision ``` gmd:CI_Date/gmd:date/gco:DateTime``` element shall be used.

So both variants (Date and DateTime) should be possible.
However, the test fails on DateTime.

```xml
X-Path: /gmd:MD_Metadata/gmd:identificationInfo/gmd:MD_DataIdentification/gmd:citation/gmd:CI_Citation/gmd:date/gmd:CI_Date/gmd:date/gco:DateTime

<gmd:date>
	<gmd:CI_Date>
		<gmd:date>
			<gco:DateTime>2022-06-24T00:00:00.000+02:00</gco:DateTime>
		</gmd:date>
		<gmd:dateType>
			<gmd:CI_DateTypeCode codeList="http://standards.iso.org/iso/19139/resources/gmxCodelists.xml#CI_DateTypeCode" codeListValue="revision"/>
		</gmd:dateType>
	</gmd:CI_Date>
</gmd:date>
```
Could you check that please?

Thanks & regards.

**Comment by fabiovinci** [comment]
Dear @m2fuhrmann,

thank you for opening the issue.

You are right, the test should pass even if the `<gco:DateTime>` element is used.

We will review the related ATS and ETS and notify you when the fix is available in staging.

**Comment by arantzaetxebarria** [comment]
Dear @m2fuhrmann 

A solution has been implemented and now is present in [staging environment](http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/home/index.html). Could you please verify and check that now is working as expected? Thanks

Regards

**Comment by fabiovinci** [comment]
Dear all,

I tested the fix in the staging instance and it works fine.
