### ISSUE TITLE
Metadata dataset: Spatial resolution / double type check

### ISSUE THREAD

**Issue by fxprunayre** [INSPIRE-MIF/helpdesk-validator#93]
Currently the test is checking that the value follow `let $regex_float := '^-?\d+\.\d{2,}'` which means `one.or.more.numbers-a.dot-two.or.more.numbers`

So currently, 100 is not valid but 100.00 is.

An XSD parser valid integer value for double. It also valid scientific notation like 100000e4. INF is also fine. It complains about non numeric.

```
Invalid or missing value. '100000AAA' is not a valid value for (double) in element Distance (gmd:distance).
```

gco:Distance is a double.
http://www.wmo.int/schemas/wmdr/1.0RC7/documentation/schemadoc/schemas/basicTypes_xsd_1/elements/Distance.html

XSD double is defined as https://www.w3.org/TR/xmlschema11-2/#double

So using regex '^-?\d+\.\d{2,}' sounds a bit restrictive to what a double is.

Using cast to double. If failure, then reports
```
[err:FORG0001] Cannot cast to xs:double: DADA.
```

The test is a duplicate with the XSD parsing done in common
requirements.

Here is fix for that https://github.com/inspire-eu-validation/ets-repository/pull/315/commits/8806b2ea44acc8f92963a4feac4eff4de00fd2b7

Relates to https://github.com/inspire-eu-validation/ets-repository/pull/315

**Comment by michellutz** [comment]
The proposed change looks reasonable to me.

**Comment by josemasensio** [comment]
Dear @fxprunayre,

Could you please cancel the pull request against `master` and create one request per issue/modification against `staying` branch?
Once each request is merged, we will test it to check that everything is correct and come back to you so you can also test that your changes are correct.

We appreciate your collaboration. Is good to see that the community is interested on improving this  tool.

Greetings.

**Comment by fxprunayre** [comment]
> and create one request per issue/modification against `staying` branch?

I think you can easily cherry-pick the relevant commits or copy/paste the couple of lines affected by the changes. HTH.

**Comment by josemasensio** [comment]
Dear @fxprunayre,

The solution you proposed is deployed on [staging instance](http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/). We will apreciate if you can give us your feedback.

Best regards.
