### ISSUE TITLE
Planned Landuse: Test "lu-gml.a.1: Land Use feature in dataset" fails with nested FeatureCollections in XML

### ISSUE THREAD

**Issue by ulbrichtd** [INSPIRE-MIF/helpdesk-validator#930]
Hi,

the test "lu-gml.a.1: Land Use feature in dataset" validates that featuretypes from Landuse application schema are present in the dataset, i.e. it scans for occurences of plu:SpatialPlan, plu:SupplementaryRegulation and others in the XML. Currently this test does not work with nested FeatureCollections. 

Nested FeatureCollections are generated by Geoserver-WFS when you query for more than one featuretype. The data structure looks like this and the INSPIRE validator does not find "plu:SpatialPlan":
```
<wfs:FeatureCollection>
  <wfs:member >
   <wfs:FeatureCollection>
    <wfs:member >
     <plu:SpatialPlan>…</plu:SpatialPlan>
    </wfs:member>
   </wfs:FeatureCollection>
 </wfs:member>
</wfs:FeatureCollection>
```
Currently the INSPIRE validator expects this data structure:
```
<wfs:FeatureCollection>
  <wfs:member >
   <plu:SpatialPlan>…</plu:SpatialPlan>
  </wfs:member>
</wfs:FeatureCollection>
```
The INSPIRE validator should accept nested FeatureCollections.

You can access our data here [WFS-GetFeature](https://gdi.berlin.de/services/wfs/plu_entwicklung?Request=GetFeature&Service=WFS&Version=2.0.0&typeNames=(plu_entwicklung:SpatialPlan)(plu_entwicklung:SupplementaryRegulation)&srsName=http://www.opengis.net/def/crs/EPSG/0/4258)

The test report you can find here [PLU_nested_featurecollection.zip](https://github.com/INSPIRE-MIF/helpdesk-validator/files/10933374/PLU_nested_featurecollection.zip)

There is a similar issue in the [ets-repository](https://github.com/inspire-eu-validation/ets-repository/issues/182) that discusses this problem for other INSPIRE data themes.

Best regards and many thanks
Damian

**Comment by fabiovinci** [comment]
Dear @ulbrichtd,

thank you for the issue.
Looking at the related issue it seems a solution was already provided for the Annex I data themes, so we will check it and implement the same fix for this data theme.

**Comment by arantzaetxebarria** [comment]
Dear @ulbrichtd 

We have uploaded a solution for this issue in [staging environment](http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/test-selection/index.html), could you please verify? Thanks

Regards

**Comment by ulbrichtd** [comment]
Hi,

I just tested. The problem is fixed in the staging environment. Thank you.

Best regards
Damian
