### ISSUE TITLE
Metadata dataset: Resource Locator / Add some context so that end user knows what the test is looking at.

### ISSUE THREAD

**Issue by fxprunayre** [INSPIRE-MIF/helpdesk-validator#94]
When checking URL, the validator reports:
```
XML document 'file.xml', record 'f6aa98bd-9785-4583-b334-1fabeb7f61a5': 
The provided Resource Locator URL is not working.
```
but if you have 30 urls in the record, end user don't know which one is wrong.

Advertise it in the error message
https://github.com/inspire-eu-validation/ets-repository/pull/315/commits/0e9151e8cff78af95a51bc761d70405a81f2abd3

After the changes, error is:
```
XML document 'file.xml', record 'c651bc41-d5da-49de-ba47-c51eabbb2007': The provided Resource Locator URL
 '/local/tr/geography/eea_ref_grids/eea_v_3035_100_km_eea-ref-grid-tr_2011/tr_100km.shp'
 is not working.
```

Relates to https://github.com/inspire-eu-validation/ets-repository/pull/315

**Comment by michellutz** [comment]
The proposed change looks good to me.

**Comment by josemasensio** [comment]
Dear @fxprunayre,

Could you please cancel the pull request against `master` and create one request per issue/modification against `staying` branch?
Once each request is merged, we will test it to check that everything is correct and come back to you so you can also test that your changes are correct.

We appreciate your collaboration. Is good to see that the community is interested on improving this  tool.

Greetings.

**Comment by fxprunayre** [comment]
> Could you please cancel the pull request against `master`

Sure.



> and create one request per issue/modification against `staying` branch?

I think you can easily cherry-pick the relevant commits or copy/paste the couple of lines affected by the changes. HTH.

**Comment by josemasensio** [comment]
Dear @fxprunayre,

Thank you for closing the issue. We will implement the issue. We will let you know when they are implemented.

Best regards.

**Comment by josemasensio** [comment]
Dear @fxprunayre,

The solution you proposed is deployed on [staging instance](http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/). We will apreciate if you can give us your feedback.

Best regards.
