### ISSUE TITLE
Cannot test xml files or csw files on Validator. Generic error coming up on screen

### ISSUE THREAD

**Issue by DDuffyesri** [INSPIRE-MIF/helpdesk-validator#940]
Before reporting an issue with the INSPIRE Reference Validator deployed at JRC, please:
- check whether a similar issue has already been opened
- try to validate your resource after cleaning the browser cache (in case of error during the upload of the resource) 
- check the [list of known limitations](https://github.com/INSPIRE-MIF/helpdesk-validator/wiki/Known-limitations).

To report an issue, please replace these lines with a brief summary of your issue and the expected behaviour.

To help us investigate the issue, you may want to include:

- a description of the steps to reproduce your issue
- the browser and version used
- a screenshot illustrating the problem
- the Test Report (ideally as an attachment to the issue)
- the name of the Test that failed or better: change the `Level of Detail`
in the Report by clicking on `All Details`, then scroll down to the failed test
and copy the Link on the right-hand side of the `Assertion URI`
- the URL of your service / the file you have uploaded or referenced (as
an attachment).

If your service is protected or you have confidential data that you cannot
upload here, you can request an email address to which you can send URLs / files.
Please note that issues cannot be investigated for services/datasets that we cannot
access.

**Comment by DDuffyesri** [comment]
Here is link we are using: https://inspire.geohive.ie/geoportal/rest/metadata/item/ie.marine.data%3Adataset.845/xml

**Comment by DDuffyesri** [comment]
Tried again today with same url and now got a 502 proxy error

**Comment by fabiovinci** [comment]
Dear @DDuffyesri,

it seems it was caused by heavy use since we detected that 80% of the CPU was in use.
Now, the situation seems to be back to normal.
This is the validation report of your metadata:
https://inspire.ec.europa.eu/validator/test-run/index.html?id=EID348a6209-467c-421a-bd64-c5f352444f1f

**Comment by DDuffyesri** [comment]
Thanks very much Fabio
