### ISSUE TITLE
Can't test datasets

### ISSUE THREAD

**Issue by Ana-SGA** [INSPIRE-MIF/helpdesk-validator#941]
Dear all,

we can't test any datasets on the INSPIRE Validator, does anyone know why?

**Comment by fabiovinci** [comment]
Dear @Ana-SGA,

it seems it was caused by heavy use since we detected that 80% of the CPU was in use.

Now, the situation seems to be back to normal.

Could you please check?

**Comment by Ana-SGA** [comment]
Dear @fabiovinci ,

no, now I can't even load INSPIRE Validator page (error attached). A while before this has occurred Validator returned error even if it uploaded file and keept running endlessly. Or it returned error 502 or 504.

**Comment by fabiovinci** [comment]
Dear @Ana-SGA,

could you please share the dataset you are testing to reproduce the error? Thanks

**Comment by Ana-SGA** [comment]
Dear @fabiovinci , 

at this moment Validator does not return an error, but keeps running endlessly when testing datasets, more than one hour - I can't attach those two files because they are too big for github. I can attach only dataset tn_complete (Transport Networks - Air, Railway, Road) for which upload runs endlessly (more than one hour). Thanks for looking into.

[tn - complete.zip](https://github.com/INSPIRE-MIF/helpdesk-validator/files/11199556/tn.-.complete.zip)

**Comment by jenriquesoriano** [comment]
Dear @Ana-SGA , 

thanks for your feedback.
With regard to tn - complete.zip, we were able to upload and run the test.
Please see it at: https://inspire.ec.europa.eu/validator/test-reports/details.html?id=EID701c623c-c0be-47fe-9fdc-796e02f69337
The unavailability you perceived is caused by a set of tests with high consumption of resources that some users are sending these days. We are working in order to prevent these unavailabilities from happening.
It may help you to deploy a local instance of the INSPIRE Reference Validator, please find the instructions for the latest release [here](https://github.com/INSPIRE-MIF/helpdesk-validator/releases/tag/v2023.1).
We can help you in the process, if needed.

With regard to the rest of files, please note that the upload of files is limited to 50MB.
Please see:
![imagen](https://user-images.githubusercontent.com/25343632/231206956-2487cdef-afae-4446-8b42-b9c3acc4cc62.png)
Could it be the cause of the issue?

Best regards,

**Comment by Ana-SGA** [comment]
Dear @jenriquesoriano ,

thanks for looking into - I hope you will solve this heavy loads soon, do you maybe know when? I could also run the test for dataset that I have attached tn-complete.zip. Don't know why the test runs this morning - I haven't change anything in dataset. It takes a little longer to run the test, but is acceptable.


> With regard to the rest of files, please note that the upload of files is limited to 50MB.  Could it be the cause of the issue?
> 
No, zipped files are less than 50MB.

**Comment by Ana-SGA** [comment]
Dear @jenriquesoriano ,

I tried to test refined dataset for tn-complete.zip (attached dataset for Transport Network theme, schemas Air, Railway, Road) and got an error again while running the test (picture attached).

![Error](https://user-images.githubusercontent.com/77394573/231691639-55430617-5e49-45da-b4cf-b4ca6706dc75.png)
[Prometne_mreze_iz_topografske_baze_Grada_Zagreba_2018.zip](https://github.com/INSPIRE-MIF/helpdesk-validator/files/11219589/Prometne_mreze_iz_topografske_baze_Grada_Zagreba_2018.zip)

**Comment by fabiovinci** [comment]
Dear @Ana-SGA,

it appears that the validation has been concluded:

![image](https://user-images.githubusercontent.com/22212406/231702476-f3ba2361-b25e-4830-a407-8766e88f111f.png)

https://inspire.ec.europa.eu/validator/test-reports/details.html?id=EID6028693b-8c3e-48ea-83bd-2eff5203e9dd

**Comment by Ana-SGA** [comment]
Dear @fabiovinci , 

which dataset did you test - tn-complete.zip or Prometne_mreze_iz_topografske_baze_Grada_Zagreba_2018.zip? For me the test still runs more than an hour for now.

**Comment by fabiovinci** [comment]
Dear @Ana-SGA,

I retrieved "your" validation report from the related menu.

In the test report, if you activate "All details" you can see the name of the tested resource.

![image](https://user-images.githubusercontent.com/22212406/232033627-99d4435c-3763-443d-a701-5e066d892482.png)

**Comment by Ana-SGA** [comment]
Dear @fabiovinci ,

for the same dataset I still get an error warning even though the test is started. It runs endlessly. I don't understand why you can run the test and I can't.

**Comment by fabiovinci** [comment]
Dear @Ana-SGA,

> I don't understand why you can run the test and I can't.
I didn't run a new test but I only retrieved the report from the "Test reports" menu.

It is possible that your browser does not update automatically and you see the test running even if it is completed. You can try clearing the browser cache or performing validation using an incognito window.

It seems that the report of your last validation is available:

![image](https://user-images.githubusercontent.com/22212406/232052334-84ce9951-92e3-436f-9ab2-0bec358e0f91.png)

**Comment by Ana-SGA** [comment]
Dear @fabiovinci,

at this moment the Validator page does not load. Just a few minutes ago, when trying to run the test (for dataset) there was 502 Proxy error (after clearing the cache and also inPrivate tab).

**Comment by Ana-SGA** [comment]
Dear @fabiovinci ,

just to add, 502 Proxy error appeared when trying to run the test for dataset.

**Comment by fabiovinci** [comment]
Dear @Ana-SGA,

it seems the validator was again busy this morning, but I was able to complete the validation for your dataset " Prometne_mreze_iz_topografske_baze_Grada_Zagreba_2018.zip".

See the report: https://inspire.ec.europa.eu/validator/test-reports/details.html?id=EID9d6be4fc-5f5f-4c24-aa9d-91252f5d574e

**Comment by Ana-SGA** [comment]
Dear @fabiovinci,
could this "space" problem with the Validator be resolved, it seems quite often? 

I was able to run test for another dataset on staging instance but got a lot of errors concerning code list values. Validator says: "System error in the Executable Test Suite. Please contact a system administrator. Error information:Code list http://inspire.ec.europa.eu/codelist/HydrologicalPersistenceValue cannot be accessed." This is just one example from the test http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/test-run/details.html?id=EID54f5e65e-c603-48eb-88c1-99dffe512da8. Can you please take a look?

**Comment by fabiovinci** [comment]
Dear @Ana-SGA,

yesterday, the validator was under maintenance, see [Announcement](https://github.com/INSPIRE-MIF/helpdesk-validator/discussions/945).

**Comment by Ana-SGA** [comment]
Dear @fabiovinci,

it was before maintenance started. 

Could you please tell me about this other error I have asked? It appears on production and staging instance.

**Comment by fabiovinci** [comment]
Dear @Ana-SGA,

> I was able to run test for another dataset on staging instance but got a lot of errors concerning code list values. Validator says: "System error in the Executable Test Suite. Please contact a system administrator. Error information:Code list http://inspire.ec.europa.eu/codelist/HydrologicalPersistenceValue cannot be accessed." This is just one example from the test http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/test-run/details.html?id=EID54f5e65e-c603-48eb-88c1-99dffe512da8. Can you please take a look?

Usually, this type of error is related to the temporary unavailability of the resource during validation.
Could you please verify if the error persists?

**Comment by Ana-SGA** [comment]
Dear @fabiovinci ,

the error is gone now on staging instance and on production. Thank you.
