### ISSUE TITLE
Error while uploading file and unable to Start Test

### ISSUE THREAD

**Issue by durmusarda** [INSPIRE-MIF/helpdesk-validator#942]
Dear all,

Today i am facing an issue when i tried to upload metadtaa file and getting error. Does anybody know why?
I have tried different ip and browsers already.

Thanks in advance.

**Comment by jenriquesoriano** [comment]
Dear @durmusarda , 
the INSPIRE Reference Validator is suffering of high demand and maybe you could experience this side effect.
In any case, could you provide us with the concrete file in order to reproduce the issue?
Thanks a lot.
Best regards,

**Comment by durmusarda** [comment]
It is working fine now! Thank you.

**Comment by fabiovinci** [comment]
Dear @durmusarda,

thank you for your feedback.

I will close the issue, please reopen it if the error persists.
