### ISSUE TITLE
AM - competentAuthority.role reported as missing even though the parent attribute is void

### ISSUE THREAD

**Issue by fabiovinci** [INSPIRE-MIF/helpdesk-validator#943]
The validator reports an error in case the `role` attribute is missing even if the `competentAuthority` attribute is void.

![image](https://user-images.githubusercontent.com/22212406/231414306-3645406f-a307-495f-8191-c8d56dcdf8d1.png)

The `competentAuthority` attribute is mandatory but voidable, so if it is not present in the dataset (i.e. encoded as follow: <am:competentAuthority xsi:nil="true" nilReason="https://inspire.ec.europa.eu/codelist/VoidReasonValue/Unknown"/>, for example) the validator should skip the check about the presence of the `role` attribute (see the related [ATS](https://github.com/inspire-eu-validation/data-am/blob/master/am-as/constraints.md)).

**Comment by arantzaetxebarria** [comment]
Dear @fabiovinci 

The solution is present in staging environment, could you please verify that it is working as expected? Thanks

Regards

**Comment by fabiovinci** [comment]
Dear @arantzaetxebarria,

I tested the fix in staging and it works, so this solution can be included in the next release.
