### ISSUE TITLE
Getting Validation Errors After Maintenance Update

### ISSUE THREAD

**Issue by durmusarda** [INSPIRE-MIF/helpdesk-validator#947]
Dear All,

We are getting these validation errors that i mentioned below after maintenance is there anybody know why? Everything seems normal and i have already tested a metadata that i downloaded from inspire geoportal before. It was same metadata and it has passed from the validator a week ago without any problem. 

Conformance Class 1: INSPIRE data sets and data set series baseline metadata.
	Identification
		md dataset-and-seies 1.4: INSPIRE Theme Keyword
	Distribution
		md dataset-and-series 1.10: Dataset Conformity
Conformance Class 2b: INSPIRE data sets and data set series metadata for Monitoring
	Monitoring requirements
		M.1: Spatial scope keyword
		M.2: Priority datasets keyword

I attached the inspire geoportal metadata xml that i tested as a txt file.

[45.iso19139.xml.txt](https://github.com/INSPIRE-MIF/helpdesk-validator/files/11272074/45.iso19139.xml.txt)

**Comment by jenriquesoriano** [comment]
Dear @durmusarda  ,

we have re-configured the deployment in order to address this redirection issue and it should be considered solved.
Please excuse the inconvenience.

Best regards,

**Comment by fabiovinci** [comment]
Dear @durmusarda,

the redirection issue has been solved and your metadata validates without errors (see [the report](https://inspire.ec.europa.eu/validator/test-run/index.html?id=EID6a755fc4-27b3-4e55-b720-a39138c354b6)).

I will close the issue, please reopen it if the error persists.
