### ISSUE TITLE
Some tests fail with 'System error in the Executable Test Suite. Please contact a system administrator.'

### ISSUE THREAD

**Issue by cschwartze** [INSPIRE-MIF/helpdesk-validator#948]
Now, using following Conformance Classes, various fail messages occur:

For **Conformance Class 1: 'Baseline metadata for data sets and data set series'**:
- 1.4 INSPIRE Theme Keyword: _System error in the Executable Test Suite. Please contact a system administrator. Error information:Code list http://inspire.ec.europa.eu/theme cannot be accessed._
- 1.10 Dataset Conformity: _System error in the Executable Test Suite. Please contact a system administrator. Error information:[err:FODC0002] "http://inspire.ec.europa.eu/schemas/common/1.0/enums/enum_bul.xsd" (Line 1): Premature end of file. 
 (985/15)_

For **Conformance Class 2b: 'INSPIRE data sets and data set series metadata for Monitoring'**:
- M.1 Spatial scope keyword: _System error in the Executable Test Suite. Please contact a system administrator. Error information:[err:FOER0000] Code list http://inspire.ec.europa.eu/metadata-codelist/SpatialScope cannot be accessed. 
 (245/11)_
- M.2 Priority datasets keyword: _System error in the Executable Test Suite. Please contact a system administrator. Error information:[err:FOER0000] Code list http://inspire.ec.europa.eu/metadata-codelist/PriorityDataset cannot be accessed. 
 (245/11)_

Report URI: https://yzyiqfakm4.execute-api.eu-west-1.amazonaws.com/validator/v2/TestRuns/EIDfdabb23b-eb10-4147-bde4-dc5c73f7f1d6.html?lang=de

I mean, the same test passed successfully a week ago...

**Comment by cschwartze** [comment]
> Now, using following Conformance Classes, various fail messages occur:
> 
> For **Conformance Class 1: 'Baseline metadata for data sets and data set series'**:
> 
>     * 1.4 INSPIRE Theme Keyword: _System error in the Executable Test Suite. Please contact a system administrator. Error information:Code list http://inspire.ec.europa.eu/theme cannot be accessed._
> 
>     * 1.10 Dataset Conformity: _System error in the Executable Test Suite. Please contact a system administrator. Error information:[err:FODC0002] "http://inspire.ec.europa.eu/schemas/common/1.0/enums/enum_bul.xsd" (Line 1): Premature end of file.
>       (985/15)_
> 
> 
> For **Conformance Class 2b: 'INSPIRE data sets and data set series metadata for Monitoring'**:
> 
>     * M.1 Spatial scope keyword: _System error in the Executable Test Suite. Please contact a system administrator. Error information:[err:FOER0000] Code list http://inspire.ec.europa.eu/metadata-codelist/SpatialScope cannot be accessed.
>       (245/11)_
> 
>     * M.2 Priority datasets keyword: _System error in the Executable Test Suite. Please contact a system administrator. Error information:[err:FOER0000] Code list http://inspire.ec.europa.eu/metadata-codelist/PriorityDataset cannot be accessed.
>       (245/11)_
> 
> 
> Report URI: https://yzyiqfakm4.execute-api.eu-west-1.amazonaws.com/validator/v2/TestRuns/EIDfdabb23b-eb10-4147-bde4-dc5c73f7f1d6.html?lang=de
> 
> I mean, the same test passed successfully a week ago...

Seems to be working again...

**Comment by jenriquesoriano** [comment]
Dear @cschwartze  , 

indeed we are operating the deployment in order to address the issue and it should be considered solved.
Please excuse the inconvenience.

Best,

**Comment by fabiovinci** [comment]
Dear @cschwartze,

the redirection issues should be solved.
I will close the issue, please reopen it if the error persists.
