### ISSUE TITLE
Wrong polygon orientation reported for CRS EPSG:3045/EPSG:4258

### ISSUE THREAD

**Issue by ulbrichtd** [INSPIRE-MIF/helpdesk-validator#950]
Hi,

in Berlin our data is organized in CRS EPSG:25833. We use Geoserver+WFS with appschema extension to provide reprojected data in CRS EPSG:3045/EPSG:4258. The CRS EPSG:25833 uses east-north axis order while EPSG:3045/EPSG:4258 use north-east axis order. 

We observed that the INSPIRE validator accepts polygons in EPSG:25833 and the validator reports wrong polygon orientation for EPSG:3045/EPSG:4258 in test "gmlas.d.10: Validate Geometries (1)". The error messages in these cases are "Error detected: Invalid polygon. Outer ring of polygon is clockwise within element MultiSurface" and "Error detected: Invalid polygon. Inner ring of polygon is counterclockwise within element MultiSurface".

Other software (FME GeometryValidator testing simple features) does not report errors in polygon orientation in these CRS.

Test reports for EPSG:3045/25833 (via staging instance of validator):

[plu_entwicklung - epsg 3045.zip](https://github.com/INSPIRE-MIF/helpdesk-validator/files/11285870/plu_entwicklung.-.epsg.3045.zip)
[plu_entwicklung - epsg 25833.zip](https://github.com/INSPIRE-MIF/helpdesk-validator/files/11285871/plu_entwicklung.-.epsg.25833.zip)

Links to the data:

[Data in EPSG:3045](https://gdi.berlin.de/services/wfs/plu_entwicklung?Request=GetFeature&Service=WFS&Version=2.0.0&typeNames=(plu_entwicklung:SpatialPlan)(plu_entwicklung:SupplementaryRegulation)&srsName=http://www.opengis.net/def/crs/EPSG/0/3045)

[Data in EPSG:25833](https://gdi.berlin.de/services/wfs/plu_entwicklung?Request=GetFeature&Service=WFS&Version=2.0.0&typeNames=(plu_entwicklung:SpatialPlan)(plu_entwicklung:SupplementaryRegulation)&srsName=http://www.opengis.net/def/crs/EPSG/0/25833)

Best regards & many thanks
Damian

**Comment by fabiovinci** [comment]
Dear @ulbrichtd,

thank you for opening the issue and providing the related resources and sorry for the late reply.

This is a known issue for which we are testing the related solution in the [BETA instance of the validator](http://beta-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/home/index.html).

We will use your sample datasets for further testing and report back on the results.

**Comment by fabiovinci** [comment]
Dear @ulbrichtd,

we introduced a fix in the beta instance for the EPSG:3045 reference system, so the datasets with this reference system pass the geometry test if the axis order is N-E (Lat-Lon) and the related polygons contain counterclockwise outer rings and clockwise inner rings.

Could you please test the provided solution?

**Comment by ulbrichtd** [comment]
Hi Fabio,

thank you. I tested with the data. The validator reports now correct polygon orientation for EPSG:3045/EPSG:4258. 

Unfortunately, test "lu-gml.a.1: Land Use feature in dataset" fails in the beta instance. The same data passes this test in the production instance of the validator. Please see attached reports [Beta_vs_production-epsg_3045.zip](https://github.com/INSPIRE-MIF/helpdesk-validator/files/11419927/Staging_vs_production-epsg_3045.zip).

Best regards,
Damian

**Comment by fabiovinci** [comment]
Dear @ulbrichtd,

thank you for the confirmation.
The error in the Beta instance is due to a temporary issue related to the redirection, which will be fixed soon.

**Comment by JohannaOtt** [comment]
@fabiovinci Is that fix limited to LU or is there any chance that it also fixes the general issue in https://github.com/inspire-eu-validation/ets-repository/issues/60?

**Comment by fabiovinci** [comment]
Hi @JohannaOtt,

the fix available in the BETA instance is a general fix for the issue related to polygon orientation.

**Comment by fabiovinci** [comment]
The fix has been made available in the Staging environment and will be included in the v2023.2 release.
