### ISSUE TITLE
Validator (staging instance) fails for Validation against INSPIRE official schema

### ISSUE THREAD

**Issue by Ana-SGA** [INSPIRE-MIF/helpdesk-validator#951]
Dear all,

Validator (staging instance) fails for Validation against INSPIRE official schema: "_XML document 'Grad_Zagreb_vrtici_i_skole_GOTOVO.gml': https://inspire.ec.europa.eu/schemas/us-govserv/4.0/GovernmentalServices.xsd, 1:930: src-import.3.1: The namespace attribute, 'https://inspire.ec.europa.eu/schemas/us-govserv/4.0', of an <import> element information item must be identical to the targetNamespace attribute, 'http://inspire.ec.europa.eu/schemas/us-govserv/4.0', of the imported document_."

GML files that were ok till now, now fail for the above mentioned error.

Additionally, those files that were fine, now also fail for: "_The XML documents representing the spatial data set do not contain a feature of any of the spatial object types in the 'Utility and Government Services' application schemas. Therefore, the spatial data set cannot conform to this conformance class. If you have expected to find spatial objects from the application schema in the data set, please consult the statistics information to see the spatial object types that have been found_."

Why do the tests fail now for these errors and were all right before?

**Comment by fabiovinci** [comment]
Dear @Ana-SGA,

this is a known bug, please refer to [this issue](https://github.com/INSPIRE-MIF/helpdesk-validator/issues/952) for an update on error resolution.
