### ISSUE TITLE
Release zipfile for inspire registry resources contains encoding errors

### ISSUE THREAD

**Issue by verendi** [INSPIRE-MIF/helpdesk-validator#954]
The zipfile for the inspire registry resources which got released with the latest version v2023.1 and which is available via the URL https://github.com/INSPIRE-MIF/helpdesk-validator/releases/download/v2023.1/inspire-registry-resources.zip contains encoding errors.
We found encoding errors at least in the files:

- ./schemas/common/1.0/enums/enum_ger.xsd
- ./theme/theme.de.atom

This leads to some tests in our local validator instance giving wrong results.

Could you please provide a new zipfile with clean utf-8 files?

**Comment by dperezBM** [comment]
Dear @verendi,

We are working on inspire-registry-resources.zip fixing the codification of the files. We will re-upload the zip file when it is fixed.

Regards.

**Comment by fabiovinci** [comment]
Dear @verendi,

thank you for reporting the error, we are checking the files contained in the zip and will provide soon an updated zip file.

**Comment by dperezBM** [comment]
Dear @verendi,

We have uploaded an updated zip file in https://github.com/INSPIRE-MIF/helpdesk-validator/releases/download/v2023.1/inspire-registry-resources.zip Could you please verify that now is working as expected? Thanks

Regards

**Comment by verendi** [comment]
Dear @dperezBM , 

I checked the zip file and it looks fine now.
Thanks for the quick solution.

Regards
