### ISSUE TITLE
NetworkService_WMS_metadata_2.0_example fails GEMINI 2.3 validator

### ISSUE THREAD

**Issue by nmtoken** [INSPIRE-MIF/helpdesk-validator#96]
Running the latest [NetworkService_WMS_metadata_2.0_example](https://github.com/inspire-eu-validation/community/blob/master/examples/NetworkService_WMS_metadata_2.0_example) through the GEMINI 2.3 validator and found three issues:

[1] 

`AP-1b: The gmd:version element shall have a value OR a nil reason of either 'inapplicable' or 'unknown'. This test may be called by the following Metadata Items: 21 - Data Format`

[2]

`System ID: https://raw.githubusercontent.com/inspire-eu-validation/community/master/examples/NetworkService_WMS_metadata_2.0_example
Main validation file: https://raw.githubusercontent.com/inspire-eu-validation/community/master/examples/NetworkService_WMS_metadata_2.0_example
Scenario name: GEMINI23
Engine name: ISO Schematron
Severity: error
Description: MI-47b (Hierarchy level name): Hierarchy level name for services must have value "service"
Start location: 30:0`

[3]

`System ID: https://raw.githubusercontent.com/inspire-eu-validation/community/master/examples/NetworkService_WMS_metadata_2.0_example
Main validation file: https://raw.githubusercontent.com/inspire-eu-validation/community/master/examples/NetworkService_WMS_metadata_2.0_example
Scenario name: GEMINI23
Engine name: ISO Schematron
Severity: error
Description: MI-48f (Quality Scope): Value (gmd:MD_ScopeDescription/gmd:other) should be "service"
Start location: 423:0`

For issue [1] the example has:

    <gmd:MD_Format>
        <gmd:name>
            <gmx:Anchor
              xlink:href="https://www.iana.org/assignments/media-types/image/png">png</gmx:Anchor>
        </gmd:name>
        <gmd:version
          gco:nilReason="http://inspire.ec.europa.eu/codelist/VoidReasonValue/Unknown" />
    </gmd:MD_Format>

The validator is expecting:

    <gmd:version gco:nilReason="unknown" /> or
    <gmd:version gco:nilReason="inapplicable" />

Though this is I think a false positive (or GEMINI 2.3 is too strict) as  anyURI is allowed as a valid gml:NilReasonType.  However I could see it as a possible issue that if any URI is allowed, how the validator will be able to check that the content of the resource equates to required values of _unknown_ or _inapplicable_

For issue [2] the example has:

    <gmd:hierarchyLevelName>
      <gco:CharacterString>Service</gco:CharacterString>
    </gmd:hierarchyLevelName>

GEMINI 2.3 is expecting case sensitive "service" here, on the basis that the value comes from the ISO 19115 MD_ScopeCode code list, and the code list has "service"

For issue [3] the example has:

    <gmd:scope>
        <gmd:DQ_Scope>
            <gmd:level>
                <gmd:MD_ScopeCode
                    codeList="http://standards.iso.org/iso/19139/resources/gmxCodelists.xml#MD_ScopeCode"
                    codeListValue="service"/>
            </gmd:level>
            <gmd:levelDescription>
            <gmd:MD_ScopeDescription>
                <gmd:other>
                    <gco:CharacterString>Service</gco:CharacterString>
                </gmd:other>
            </gmd:MD_ScopeDescription>
        </gmd:levelDescription>
        </gmd:DQ_Scope>
    </gmd:scope>

GEMINI 2.3 is also the expecting case sensitive "service" in the level description.  Note the actual example has a comment that reinforces this point like:

    ... Additionally the level shall be named using element gmd:scope/gmd:DQ_Scope/gmd:levelDescription/gmd:MD_ScopeDescription/gmd:other element with a Non-empty Free Text Element containing the term "service" in the language of the metadata.-->

For GEMINI the language is always English so "service" is always expected.

**Comment by josemasensio** [comment]
Dear @nmtoken,

Thanks for your message. We will check the issues that you reported and we will gave you feedback as soon as possible.

Regards.

**Comment by bilbomaticaue** [comment]
Please, can you refer the test results? This will help us to locate the issue.

Regards.

**Comment by nmtoken** [comment]
> Please, can you refer the test results? 

@bilbomaticaue I'm not sure I understand your request, as I have already cited the document at issue, and the issues.

The NetworkService_WMS_metadata_2.0_example is cited as passing the INSPIRE validator test, and I am saying that it fails another validator set up for testing conformance to the INSPIRE metadata TG.  So the issue appears to be with the tests in the INSPIRE validator.

**Comment by josemasensio** [comment]
Dear @nmtoken 

Okay, I understand what you mean. We will analyse your proposal and respond you when a decission is made. 

Greetings.

**Comment by AntoRot** [comment]
Concerning the issue [1], as the encoding metadata elements (i.e. format name and format version) are not required for the services, I submitted the relevant pull request https://github.com/inspire-eu-validation/community/pull/97.

**Comment by josemasensio** [comment]
Dear @nmtoken,

Thank you for your feedback. After some internal discussion, we have decided to take into account your propose. Feel free to provide us feedback at any time.
Best regards.

**Comment by josemasensio** [comment]
Dear @nmtoken,

We updated the [NetworkService_WMS_metadata_2.0_example](https://github.com/inspire-eu-validation/community/blob/master/examples/NetworkService_WMS_metadata_2.0_example) according to your proposal. Also, we added validation to check if the values of md sds 3.1 and md sds 3.8. The changes will be available soon on [staging instance](http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/). If you wish, you can check the changes on the [corresponding pull request](https://github.com/inspire-eu-validation/ets-repository/pull/373).

Thank you and best regards.

**Comment by josemasensio** [comment]
Dear @nmtoken,

The changes are available already on staging instance. We will appreciate it if you could provide us with your feedback. 

Best regards.

**Comment by josemasensio** [comment]
Dear @nmtoken,

We will appreciate it if you could provide us with your feedback.

Best regards.

**Comment by danielnavarrogeo** [comment]
Dear @nmtoken 

Could you please check the implemented solution in [staging](http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/) environment and provide us feedback?

Regards

**Comment by nmtoken** [comment]
The file at https://github.com/inspire-eu-validation/community/blob/master/examples/NetworkService_WMS_metadata_2.0_example fails the GEMINI 2.3 schematron validation.

Issue reported is:

> MI-17a (Spatial Reference System): At least one coordinate reference system used in the described dataset, dataset series, or service shall be given using gmd:referenceSystemInfo/gmd:MD_ReferenceSystem/gmd:referenceSystemIdentifier/gmd:RS_Identifier

The GEMINI rule checks conformance to the following INSPIRE Requirements:

- metadata/2.0/req/sds-interoperable/crs 

- metadata/2.0/req/isdss/crs 

For services (as in this case) the following section applies

> 4.4.1.1 Coordinate Reference System Identifier
It is mandatory for Interoperable Spatial Data Services indicate the coordinate reference system identifiers supported by the service. The element for describing this information is given in [Regulation1312/2014], Annex II, Part B 3:

**Comment by danielnavarrogeo** [comment]
Dear @nmtoken 

The provided metadata example for services is conformant with Common Requirements and Conformance Class 3 of MD TG 2.0. 

We do not know how GEMINI works but it may be related to that metadata indeed fails the requirement "6.1 Coordinate Reference System element" of CC6. It also fails in other requirements from CC5 and CC6.

However, that metadata was not intended to pass all the Conformance Classes, but only Common Requirement and CC3.

Regards

**Comment by nmtoken** [comment]
The GEMINI XML encoding is an ISO 19139 schema and  is a  profile of the INSPIRE Metadata TG.  A GEMINI XML record will be an INSPIRE compliant XML metadata record.
