### ISSUE TITLE
CAPTCHA does not work

### ISSUE THREAD

**Issue by lorincztamas** [INSPIRE-MIF/helpdesk-validator#961]
Dear Support

captha function of the validator does not work throws error 500 

Please help

Best regards:
Tamás

jquery-3.6.0.min.js:2     POST https://inspire.ec.europa.eu/validator/captcha/verify.php 500 (Internal Server Error)
send @ jquery-3.6.0.min.js:2
ajax @ jquery-3.6.0.min.js:2
(anonymous) @ controller.js:47
dispatch @ jquery-3.6.0.min.js:2
v.handle @ jquery-3.6.0.min.js:2

**Comment by fabiovinci** [comment]
Hi @lorincztamas,

thank you for the notification, we will have a look.

**Comment by fabiovinci** [comment]
Dear @lorincztamas,

it seems to be an external issue with the EC captcha service that doesn't allow the validator to verify the answers of the captcha.
We disabled the captcha to allow the users to perform validations and we will restore it when the problem is solved.

**Comment by lorincztamas** [comment]
Thank you for your help!

It's much faster to check without captcha.

Best regards:  Tamás

**Comment by lorincztamas** [comment]
Hi @fabiovinci,

The capthcha is not working again :(
I cannot validate my data. Please turn it off.
Thank you
Tamás

**Comment by fabiovinci** [comment]
Hi @lorincztamas,

the CAPTCHA is disabled, please try to clear the browser cache.

**Comment by jenriquesoriano** [comment]
Dear @lorincztamas , all,

the issue regarding the captcha verification process has been solved. 
The problem has been identified as a result of a change in the final endpoint URL.

Please excuse the inconvenience and thank you for your understanding.

Best regards,

**Comment by lorincztamas** [comment]
Hi!

The captcha is again just scrolling and not validating any further.

I tried it in other browsers/networks and the result is the same.

Thanks for the help!

Greetings, Tamás

Request URL: https://europa.eu/webtools/js/webtools.captcha.js?t=1689776520
Request Method: GET
Status Code: 502 Bad Gateway
Remote Address: 147.67.210.45:443
Referrer Policy: strict-origin-when-cross-origin
Waiting for server response. 2.3 min
Thu, 20 Jul 2023 08:38:54 GMT

**Comment by fabiovinci** [comment]
Dear @lorincztamas,

it seems there is a general issue with the domain ec.europa.eu.

The captcha loads very slowly now, but after a while, it seems working.

![image](https://github.com/INSPIRE-MIF/helpdesk-validator/assets/22212406/fee0bd97-7f4d-467b-8d20-eb89f2f3cfc8)

**Comment by lorincztamas** [comment]
I went out for lunch and had coffee, but I'm still on a roll...
