### ISSUE TITLE
Problem detected on the validation of INSPIRE Registry's URLs status check

### ISSUE THREAD

**Issue by arantzaetxebarria** [INSPIRE-MIF/helpdesk-validator#963]
Dear community,

Due to a problem on the front of the INSPIRE Registry, an issue has been detected affecting the behaviour of the INSPIRE Validator when checking the status of an INSPIRE Registry URL that does not exist. 

The problem on the INSPIRE Registry is that the front page load a 200 message even when the Item doesn´t exist on the INSPIRE Registry (it should load a 404 error) which could generate false positives in the INSPIRE Validator, please visit issue [242](https://github.com/ec-jrc/re3gistry/issues/242) for more detail 

To correct this behaviour, it has been decided to replace the way that the INSPIRE Validator checks the results from the INSPIRE Registry, so the INSPIRE Registry front-end calls will be replaced by API calls which return the correct status code updating the related ETSs accordingly.

E.g.
This URL returns a 200 status code: https://inspire.ec.europa.eu/codelist/SpecificExposedElementTypeValue/soilErosionFAIL

From now on, in the tests related to the resource status check, the validator will make this call via API: https://inspire.ec.europa.eu/registry/rest?uri=https://inspire.ec.europa.eu/codelist/SpecificExposedElementTypeValue/soilErosionFAIL&lang=en&format=jsonc

**Comment by dperezBM** [comment]
The solution has been applied in [staging environment](http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/) and it is working as expected.
