### ISSUE TITLE
Codelist retreival blocked 403

### ISSUE THREAD

**Issue by mwjsanders** [INSPIRE-MIF/helpdesk-validator#972]
I hope I have used the right channel for reporting the below issue. If not please direct me the right channel.

Since last thursday (28 june) our automated Inspire service validator which runs an instance of the Inspire reference validator locally in our cluster is not able to retrieve any inspire codelist any more. For example a request like:

http://inspire.ec.europa.eu/metadata-codelist/SpatialDataServiceCategory/SpatialDataServiceCategory.en.xml

returns a http status code 403 with a body:
```
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<HTML><HEAD><META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=iso-8859-1">
<TITLE>ERROR: The request could not be satisfied</TITLE>
</HEAD><BODY>
<H1>403 ERROR</H1>
<H2>The request could not be satisfied.</H2>
<HR noshade size="1px">
Request blocked.
We can't connect to the server for this app or website at this time. There might be too much traffic or a configuration error. Try again later, or contact the app or website owner.
<BR clear="all">
If you provide content to customers through CloudFront, you can find steps to troubleshoot and help prevent this error by reviewing the CloudFront documentation.
<BR clear="all">
<HR noshade size="1px">
<PRE>
Generated by cloudfront (CloudFront)
Request ID: Lxwv0_F1z4pr1jOvD4ncdM56cJFklbV7Pf2YphmrEhgXF9kXBWYvsA==
</PRE>
<ADDRESS>
</ADDRESS>
</BODY></HTML> 
```
It looks like we have been blacklisted due to too many request, if so what are the thresholds and can we be removed from the blacklist?
We are also looking into using a proxy cache for all inspire codelist url's

Kind regards
Mark Sanders

**Comment by sMorrone** [comment]
Dear @mwjsanders , 
the problem may not actually relate to the validator, but to the codelist registry, which is currently not working (see https://github.com/INSPIRE-MIF/helpdesk-registry/issues/58). In any case, I am moving this issue to the[ validator helpdesk](https://github.com/INSPIRE-MIF/helpdesk-validator) (which is the validator-specific helpdesk), so that the validator team can investigate better.
Kind regards 
Stefania

**Comment by fabiovinci** [comment]
Dear @mwjsanders,

the INSPIRE Registry issue has been solved, so now there are no problems accessing it by the validator.

**Comment by mwjsanders** [comment]
@sMorrone Thanks for the quick reply,

unfortunately we are still experience the same problems in that we get a Http statuscode 403 while running any test in our production cluster. These errors don't occur while running the reference in a docker container on a local machine. It looks like requests from our production cluster is being blocked by the service providing the inspire codelists.

Kind regards
Mark

**Comment by fabiovinci** [comment]
Dear @mwjsanders,

thank you for the feedback, the registry team is working on that.

**Comment by mwjsanders** [comment]
As of the 5th of July, the blocking of inspire registry codelists as mentioned in this issue has gone.

**Comment by fabiovinci** [comment]
Dear @mwjsanders,

thank you for the notice, I will close the issue.
