### ISSUE TITLE
Staging instance down?

### ISSUE THREAD

**Issue by Ana-SGA** [INSPIRE-MIF/helpdesk-validator#973]
Dear all,

I'm trying to test some metadata for datasets, but Reference Validator runs the test endlessly and Staging instance is down. Does anyone knows why?

**Comment by fabiovinci** [comment]
Dear @Ana-SGA,

you may have encountered a temporary overload, now it seems to work normally and there are no tests in the queue.

![image](https://github.com/INSPIRE-MIF/helpdesk-validator/assets/22212406/84f1ff58-1d9c-4bbc-bf8d-6a918816407e)

Regarding the staging instance, there is an issue with the UI, we are working on it.

**Comment by Ana-SGA** [comment]
Dear @fabiovinci ,

yes, it seems that Reference Validator works now. Staging instance is still down.

**Comment by jenriquesoriano** [comment]
Dear @Ana-SGA ,

[Staging instance](http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/home/index.html) is back to normal.
Please excuse the inconvenience.

Best,
