### ISSUE TITLE
Encoding (?) problem with test reports on national installation

### ISSUE THREAD

**Issue by manilly** [INSPIRE-MIF/helpdesk-validator#974]
Hi,
we have a national installation of etf validator running on https://inspire.agrarforschung.at/home/index.html

When I try to validate my data (annex III - EF) the validation is running without any problems (according to the log file https://inspire.agrarforschung.at/validator/v2/TestRuns/EID394f0be0-3404-4785-9269-59d77d25ef6a/log), but I can't display the report correctly (see https://inspire.agrarforschung.at/test-reports/details.html?id=EID394f0be0-3404-4785-9269-59d77d25ef6a). 

Do you have any idea, what could be the problem?

**Comment by fabiovinci** [comment]
Dear @manilly,

it seems that the report is displayed correctly, do you confirm?

**Comment by manilly** [comment]
hmm, that's right. At first i got some strange characters. Now it works.

**Comment by manilly** [comment]
Hi,
I've got the same problem again with e.g. this report: https://inspire.agrarforschung.at/test-reports/details.html?id=EID98154fb8-e324-4aa8-9cc5-9cc10cb141f0

![image](https://github.com/INSPIRE-MIF/helpdesk-validator/assets/45065613/df2ece68-18d7-4889-b024-a9ab2ebf2478)

**Comment by fabiovinci** [comment]
Dear @manilly,

still having trouble reading test reports?

**Comment by manilly** [comment]
Thanks, not at the moment
