### ISSUE TITLE
v2023.2 - 21/06/2023 installation problem

### ISSUE THREAD

**Issue by TeijoKal** [INSPIRE-MIF/helpdesk-validator#981]
Tried to build the docker release. It started normally but then hit an error:

STEP 40/64: RUN openssl s_client -servername wms.mapama.gob.es -connect wms.mapama.gob.es:443 </dev/null | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' > /tmp/certificate.pem
140665508160832:error:0200206E:system library:connect:Connection timed out:../crypto/bio/b_sock2.c:110:
140665508160832:error:2008A067:BIO routines:BIO_connect:connect error:../crypto/bio/b_sock2.c:111:
connect:errno=110
--> af1404edacb
STEP 41/64: RUN keytool -importcert -noprompt -trustcacerts -file /tmp/certificate.pem -keystore /usr/local/openjdk-11/lib/security/cacerts -alias wms.mapama.gob.es -storepass changeit
Warning: use -cacerts option to access cacerts keystore
keytool error: java.lang.Exception: Input not an X.509 certificate
Error: building at STEP "RUN keytool -importcert -noprompt -trustcacerts -file /tmp/certificate.pem -keystore /usr/local/openjdk-11/lib/security/cacerts -alias wms.mapama.gob.es -storepass changeit": while running runtime: exit status 1

I know that our corporate network is restricted. So do we need to allow access to some server??

**Comment by manuelaromero-guadaltel** [comment]
Dear @TeijoKal,
It seems that as you have mentioned in the description, your corporate network doesn't allow you to add those certificates. Nevertheless, they are not strictly necessary for the proper functioning of the INSPIRE Reference Validator. Thus, a solution would be for you to delete the lines related to certificates from the Dockerfile, which are lines 91 to 140, both included, and then try to build again.
If you encounter any more issues in the deployment or this advice doesn't help you, please contact us again, we are glad to help you.

**Comment by TeijoKal** [comment]
Managed to remove the certificate parts in Dockerfile

**Comment by TeijoKal** [comment]
Managed to remove the certificate parts in Dockerfile

**Comment by fabiovinci** [comment]
Dear @TeijoKal,
did you manage to fix the issue?
Can we close the issue?

**Comment by TeijoKal** [comment]
Yes it was fixed by removing the certificate parts in Dockerfile.

Teijo
