### ISSUE TITLE
inspire validator program not available

### ISSUE THREAD

**Issue by lorincztamas** [INSPIRE-MIF/helpdesk-validator#982]
Hi,
The "https://inspire.ec.europa.eu/validator/test-selection/index.html" interface displays incorrectly with a about 5-10-minute response time.
Please fix it.
Thank you!

Al the best,
Tamás Lőrincz

**Comment by lorincztamas** [comment]
502 ERROR
The request could not be satisfied.
The origin closed the connection. We can't connect to the server for this app or website at this time. There might be too much traffic or a configuration error. Try again later, or contact the app or website owner.
If you provide content to customers through CloudFront, you can find steps to troubleshoot and help prevent this error by reviewing the CloudFront documentation.
Generated by cloudfront (CloudFront)
Request ID: iWhQB5PL9FPbgBBGldMGY_jaOnlRfY29q9rqnmbfFwR5l2GeO8Q_og==

**Comment by fabiovinci** [comment]
Dear @lorincztamas,

it seems that the "Test selection" works now, but regarding the test execution it seems there are many tests in the queue, as you can see from the "Test Report" page:
![image](https://github.com/INSPIRE-MIF/helpdesk-validator/assets/22212406/2456aa3f-b37b-46c8-a37d-3637c8f94c35)

You should wait a bit or use the [Staging instance](http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/home/index.html).

**Comment by fabiovinci** [comment]
Dear @lorincztamas,

were you able to validate your resource?

**Comment by lorincztamas** [comment]
Dear Fabio Vinci,

Unfortunately not!
The updated geoserver (2.22.4) doesn't meet the language requirements and the validator throws an unidentified error for getmap :(

This is my tested service:

https://inspire.lechnerkozpont.hu/geoserver/OI.2000/ows?SERVICE=WMS&service=WMS&version=1.3.0&request=GetCapabilities

Got an idea?
Thank you

Best,
Tamás

**Comment by fabiovinci** [comment]
Dear @lorincztamas,

since you were able to validate your service I will close the issue.
Regarding the errors you encountered, could you please check if specific issues are already open, otherwise please open a new one.

**Comment by lorincztamas** [comment]
OK
