### ISSUE TITLE
v2023.2 - 21/06/2023 installation problem with squid using podman

### ISSUE THREAD

**Issue by TeijoKal** [INSPIRE-MIF/helpdesk-validator#987]
We can not use docker in our corporate network. So we are using podman instead.

Have the following issue with installing the validator.

After running
podman build -t validator .

It causes the following error:

STEP 33/42: RUN apt-get -y install squid
Reading package lists...
Building dependency tree...
Reading state information...
Package squid is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'squid' has no installation candidate
Error: building at STEP "RUN apt-get -y install squid": while running runtime: exit status 100

**Comment by TeijoKal** [comment]
I think i found the reason for this.

You have made the package in Debian environment and our environment is Redhat 9 . This is the reason for this.

But now we come to the next problem:

I installed new Debian environment and tried to build. Did not work because it did not find the needed packages in repositories. So the question now is that which repositories have to be installed in fresh Debian environment so the build will work??

And next question is how can the freshly build package can be transfered to another environment??

**Comment by DanielMartinPerezdeLeon** [comment]
Dear @TeijoKal ,

thank you very much for reporting the issue.
As far as we understand, the current set-up of the INSPIRE Reference Validator doesn't align with your infrastructure, as you are deploying it with Podman, so our support is constrained by your technological environment.

From our perspective, it appears that the issue you have encountered is related to the OS instructions of the Dockerfile used by the INSPIRE Reference Validator Docker instance that need to be adapted to your specific needs.
More specifically, it seems to be related to these lines:

```
RUN apt-get update; true
RUN apt-get -y install squid
```

Our Dockerfile is configured to install all the required packages in the Debian 11 environment where we are currently running the INSPIRE Reference Validator.
If you wish to use the Docker instance with a different operating system, the Dockerfile instructions must be adapted to that specific OS.

For example, if you are using Alpine Linux as the base OS for the Docker instance, the aforementioned lines should be changed to:

```
RUN apk update; true
RUN apk add squid
```

Please make these changes to the Dockerfile and try to deploy the Podman again.

Feel free to contact us if you have any questions or if the problem persists.

Regards,

**Comment by TeijoKal** [comment]
Ok. Thank you for the reply. I will try that.

Teijo

Lähettäjä: Daniel Martín Pérez de León ***@***.***>
Lähetetty: tiistai 7. marraskuuta 2023 18.47
Vastaanottaja: INSPIRE-MIF/helpdesk-validator ***@***.***>
Kopio: Kalliomäki Teijo ***@***.***>; Mention ***@***.***>
Aihe: Re: [INSPIRE-MIF/helpdesk-validator] v2023.2 - 21/06/2023 installation problem with squid using podman (Issue #987)


Dear @TeijoKal<https://github.com/TeijoKal> ,

thank you very much for reporting the issue.
As far as we understand, the current set-up of the INSPIRE Reference Validator doesn't align with your infrastructure, as you are deploying it with Podman, so our support is constrained by your technological environment.

From our perspective, it appears that the issue you have encountered is related to the OS instructions of the Dockerfile used by the INSPIRE Reference Validator Docker instance that need to be adapted to your specific needs.
More specifically, it seems to be related to these lines:

RUN apt-get update; true

RUN apt-get -y install squid

Our Dockerfile is configured to install all the required packages in the Debian 11 environment where we are currently running the INSPIRE Reference Validator.
If you wish to use the Docker instance with a different operating system, the Dockerfile instructions must be adapted to that specific OS.

For example, if you are using Alpine Linux as the base OS for the Docker instance, the aforementioned lines should be changed to:

RUN apk update; true

RUN apk add squid

Please make these changes to the Dockerfile and try to deploy the Podman again.

Feel free to contact us if you have any questions or if the problem persists.

Regards,

-

**Comment by DanielMartinPerezdeLeon** [comment]
Dear @TeijoKal ,

Regarding the OS repositories, please note that v2023.3 is using a base image jetty:9.4.48-jre11-openjdk which relies on Debian 11-Bullseye, so, if you are using a different version of the OS, you may not find the required components in the repositories defined for the OS version you're using.

Regards,

**Comment by fabiovinci** [comment]
Dear user,

we hope the solution provided helps you to resolve the issue.
So we close this issue.
If there are any further questions or problems, please do not hesitate to reopen it or create a new issue.
