### ISSUE TITLE
Schema Validation error with gmd:report/gmd:DQ_AbsoluteExternalPositionalAccuracy

### ISSUE THREAD

**Issue by sparlar** [INSPIRE-MIF/helpdesk-validator#99]
Hello,

I got Schema Validation Error with an INSPIRE Metadata file, as I ran it through the Inspire validator http://inspire.ec.europa.eu/validator/ ->Metadata (TG version1.3) -> Conformance class: INSPIRE Profile based on EN ISO 19115 and EN ISO 19119.

**a description of the steps to reproduce your issue:**

The issue occured as I included two "gmd:report/gmd:DQ_AbsoluteExternalPositionalAccuracy" blocks in the INSPIRE.xml, as below (it is allowed to include none or more gmd:report with respect to https://www.isotc211.org/2005/gmd/dataQuality.xsd):

<gmd:report>
            <gmd:DQ_AbsoluteExternalPositionalAccuracy>
               <gmd:nameOfMeasure>
                  <gco:CharacterString>text</gco:CharacterString>
               </gmd:nameOfMeasure>
               <gmd:result>
                  <gmd:DQ_QuantitativeResult>
                     <gmd:valueUnit>
                        <gml:UnitDefinition gml:id="metre">
                           <gml:identifier codeSpace="URL"/>
                        </gml:UnitDefinition>
                     </gmd:valueUnit>
                     <gmd:value>
                        <gco:Record>
                           <gco:Decimal>2</gco:Decimal>
                        </gco:Record>
                     </gmd:value>
                  </gmd:DQ_QuantitativeResult>
               </gmd:result>
            </gmd:DQ_AbsoluteExternalPositionalAccuracy>
         </gmd:report>
         <gmd:report>
            <gmd:DQ_AbsoluteExternalPositionalAccuracy>
               <gmd:nameOfMeasure>
                  <gco:CharacterString>text</gco:CharacterString>
               </gmd:nameOfMeasure>
               <gmd:result>
                  <gmd:DQ_QuantitativeResult>
                     <gmd:valueUnit>
                        <gml:UnitDefinition gml:id="metre">
                           <gml:identifier codeSpace="URL"/>
                        </gml:UnitDefinition>
                     </gmd:valueUnit>
                     <gmd:value>
                        <gco:Record>
                           <gco:Decimal>1</gco:Decimal>
                        </gco:Record>
                     </gmd:value>
                  </gmd:DQ_QuantitativeResult>
               </gmd:result>
            </gmd:DQ_AbsoluteExternalPositionalAccuracy>
         </gmd:report>

**the browser and version used**
Firefox 68.0.1

**a screenshot illustrating the problem**

![schema_validation](https://user-images.githubusercontent.com/54098274/63092770-1bc3e000-bf63-11e9-8a56-97632a3d0ec4.PNG)

**the Test Report (ideally as an attachment to the issue)**
Regarding the Test Report I have the following questions:

1) Error Message: "The value 'metre' of attribute 'gml:id' on element 'gml:UnitDefinition' is not valid with respect to its type, 'ID'":
 
If this error message should be valid, then I should have got also a schema validation error, as I included only one "gmd:report/gmd:DQ_AbsoluteExternalPositionalAccuracy" block in the INSPIRE.xml. However, I got this error message only then, as I included two "gmd:report/gmd:DQ_AbsoluteExternalPositionalAccuracy" blocks in the INSPIRE.xml.

Could you please clarify this point?

2) There are multiple occurences of ID value ‚metre‘:
 
I cannot understand, why the occurence of two times "metre" disturbs the validator. If more "gmd:report" blocks are allowed, should it be not possible to use the content of the first "gmd:report" block in the second "gmd:report" block?

However, I gave a try and removed "gml:UnitDefinition" tag from the second "gmd:report" block (as below):

<gmd:report>
            <gmd:DQ_AbsoluteExternalPositionalAccuracy>
               <gmd:nameOfMeasure>
                  <gco:CharacterString>text</gco:CharacterString>
               </gmd:nameOfMeasure>
               <gmd:result>
                  <gmd:DQ_QuantitativeResult>
                     <gmd:valueUnit>
                        <gml:UnitDefinition gml:id="metre">
                           <gml:identifier codeSpace="URL"/>
                        </gml:UnitDefinition>
                     </gmd:valueUnit>
                     <gmd:value>
                        <gco:Record>
                           <gco:Decimal>2</gco:Decimal>
                        </gco:Record>
                     </gmd:value>
                  </gmd:DQ_QuantitativeResult>
               </gmd:result>
            </gmd:DQ_AbsoluteExternalPositionalAccuracy>
         </gmd:report>
         <gmd:report>
            <gmd:DQ_AbsoluteExternalPositionalAccuracy>
               <gmd:nameOfMeasure>
                  <gco:CharacterString>text</gco:CharacterString>
               </gmd:nameOfMeasure>
               <gmd:result>
                  <gmd:DQ_QuantitativeResult>
                     <gmd:valueUnit>
                     </gmd:valueUnit>
                     <gmd:value>
                        <gco:Record>
                           <gco:Decimal>1</gco:Decimal>
                        </gco:Record>
                     </gmd:value>
                  </gmd:DQ_QuantitativeResult>
               </gmd:result>
            </gmd:DQ_AbsoluteExternalPositionalAccuracy>
         </gmd:report>

Then I got no more schema validation error. The test was passed. However, I could not understand why it was necessary to remove "gml:UnitDefinition" from the second "gmd:report" block.

Could you please help to understand?

Kind regards

**Comment by josemasensio** [comment]
Dear @sparlar,

Thank you for your message. 
We will check why is this happening and we will came back with an answer.

Best regards.

**Comment by josemasensio** [comment]
Dear @sparlar,

We have been checking the issue and we think that it could be a validation of the schema. Please, could you provide us with the file?

Best regards.

**Comment by josemasensio** [comment]
Dear @sparlar,

Please, we need the file to check what happens. 

Best regards.

**Comment by dperezBM** [comment]
Dear @sparlar,

In case you have any other questions or problems, please feel free to open a new issue.

Best regards.
