### ISSUE TITLE
WFS test fails for OGC 09-025r2/ISO 19142

### ISSUE THREAD

**Issue by Ana-SGA** [INSPIRE-MIF/helpdesk-validator#998]
Hello,

when testing this service WFS https://transformiraj.nipp.hr/ows/services/org.4.8c49ed7b-601e-4c7e-a993-9f1919051ed0_wfs?SERVICE=WFS&REQUEST=GetCapabilities&VERSION=2.0.0 via INSPIRE Validator https://inspire.ec.europa.eu/validator/test-selection/index.html we get an error for OGC 09-025r2/ISO 19142 (report attached):
"OGC TEAM Engine returned HTTP status code: 504 (Gateway Timeout). Message: The following error was encountered while trying to retrieve the URL: http://cite.opengeospatial.org/teamengine/rest/suites/wfs20/run?
Read Timeout
The system returned: [No Error]
A Timeout occurred while waiting to read data from the network. The network or server may be down or congested. Please retry your request.
Your cache administrator is webmaster.
Generated Wed, 04 Oct 2023 13:19:00 GMT by b4a96398fb03 (squid/4.13)"

Can someone please take a look?
[1398_WFS.zip](https://github.com/INSPIRE-MIF/helpdesk-validator/files/12813312/1398_WFS.zip)

I have asked also on this site https://github.com/opengeospatial/ets-wfs20/issues/284 but they have redirected me here. The above service serves a large amount of data - could this be the reason why this test fails on the INSPIRE Validator?

**Comment by fabiovinci** [comment]
Dear @Ana-SGA,

the timeout of the OGC Conformance class is due to a large amount of data but also to a possible temporary congestion of the validator.

I validated your service in staging and the validation was completed, see the related report: http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/test-run/details.html?id=EID3ce4f4dd-c2a9-48a2-be0a-58e354d9e1f5

**Comment by Ana-SGA** [comment]
Dear @fabiovinci,

thank you. Today I managed to run and complete the test on both Reference Validator and on staging instance. So I guess that the first error was due R. Validator overload. Thank you again!
